import type { HealthColleV1 } from './health-colle.types';

export const HEALTH_COLLES_UE14_V1: HealthColleV1[] = [
  {
    id: 'c01',
    code: 'C01',
    title: 'Chimie — Fondamentaux',
    dominantPerimeter: 'Chimie générale Ch1→4',
    chaptersSummary:
      'Éléments chimiques & classification, liaisons & électronégativité, orbitales moléculaires, forces intermoléculaires.',
    questionCount: 20,
    durationMinutes: 30,
    durationLabel: '30 min',
    badgeType: 'TRANSVERSALE',
    badgeLabel: 'Transversale',
    ecCode: 'Chimie',
    description: 'Évaluation sur les notions fondamentales de chimie générale.',
  },
  {
    id: 'c02',
    code: 'C02',
    title: 'Biochimie — Glucides',
    dominantPerimeter: 'Biochimie Ch1→3',
    chaptersSummary:
      'Généralités et structure des glucides, oses simples et dérivés, osides.',
    questionCount: 20,
    durationMinutes: 30,
    durationLabel: '30 min',
    badgeType: 'TRANSVERSALE',
    badgeLabel: 'Transversale',
    ecCode: 'Biochimie',
    description: 'Évaluation ciblée sur les glucides et leurs structures.',
  },
  {
    id: 'c03',
    code: 'C03',
    title: 'Biologie cellulaire — Architecture cellulaire',
    dominantPerimeter: 'Biocell Ch1→3',
    chaptersSummary:
      'Organisation et méthodes d’étude de la cellule, membrane plasmique & transports, cytosquelette.',
    questionCount: 20,
    durationMinutes: 30,
    durationLabel: '30 min',
    badgeType: 'TRANSVERSALE',
    badgeLabel: 'Transversale',
    ecCode: 'Biologie cellulaire',
    description: 'Évaluation sur l’organisation, la membrane et le cytosquelette.',
  },
  {
    id: 'c04',
    code: 'C04',
    title: 'Chimie — Des atomes aux molécules organiques',
    dominantPerimeter: 'Chimie générale + Orga 2.1→2.3',
    chaptersSummary:
      'Chimie générale (Ch1→4), nomenclature & fonctions, isomérie & énantiomérie, hydrocarbures.',
    questionCount: 25,
    durationMinutes: 37.5,
    durationLabel: '37 min 30',
    badgeType: 'TRANSVERSALE',
    badgeLabel: 'Transversale',
    ecCode: 'Chimie',
    description: 'Décloisonnement de la chimie générale et début de la chimie organique.',
  },
  {
    id: 'c05',
    code: 'C05',
    title: 'Biochimie — Lipides',
    dominantPerimeter: 'Biochimie Ch4→8 + rappels Ch1→3',
    chaptersSummary:
      'Introduction aux lipides & acides gras, eicosanoïdes, glycérides, sphingolipides, stérols/stéroïdes + rappels glucides.',
    questionCount: 25,
    durationMinutes: 37.5,
    durationLabel: '37 min 30',
    badgeType: 'CUMULATIVE',
    badgeLabel: 'Cumulative',
    ecCode: 'Biochimie',
    description: 'Évaluation sur les lipides avec remobilisation des notions de glucides.',
  },
  {
    id: 'c06',
    code: 'C06',
    title: 'Biologie cellulaire — Trafic et compartiments',
    dominantPerimeter: 'Biocell Ch4→6 + rappels Ch1→3',
    chaptersSummary:
      'Système endomembranaire (flux vésiculaires, RE, Golgi, lysosomes), peroxysomes + rappels Ch1→3.',
    questionCount: 20,
    durationMinutes: 30,
    durationLabel: '30 min',
    badgeType: 'CUMULATIVE',
    badgeLabel: 'Cumulative',
    ecCode: 'Biologie cellulaire',
    description: 'Trafic vésiculaire, peroxysomes et mitochondries avec rappels des fondamentaux.',
  },
  {
    id: 'c07',
    code: 'C07',
    title: 'Chimie — Fonctions et réactivité',
    dominantPerimeter: 'Chimie générale + Orga 2.1→2.5',
    chaptersSummary:
      'Dérivés monofonctionnels (alcools, amines, halogénés), esters & amides, aldéhydes & cétones + synthèse chimie générale.',
    questionCount: 25,
    durationMinutes: 37.5,
    durationLabel: '37 min 30',
    badgeType: 'CUMULATIVE',
    badgeLabel: 'Cumulative',
    ecCode: 'Chimie',
    description: 'Synthèse progressive couvrant les fonctions organiques et la réactivité.',
  },
  {
    id: 'c08',
    code: 'C08',
    title: 'Biochimie — Acides aminés et protéines',
    dominantPerimeter: 'Biochimie Ch9→12 + acquis antérieurs',
    chaptersSummary:
      'Structure et rôles des acides aminés, peptides et protéines (parties 1 et 2) + rappels glucides et lipides.',
    questionCount: 25,
    durationMinutes: 37.5,
    durationLabel: '37 min 30',
    badgeType: 'CUMULATIVE',
    badgeLabel: 'Cumulative',
    ecCode: 'Biochimie',
    description: 'Évaluation approfondie sur la structure et les fonctions des protéines.',
  },
  {
    id: 'c09',
    code: 'C09',
    title: 'Biologie cellulaire — Cellule intégrée',
    dominantPerimeter: 'Biocell Ch7→9 + rappels Ch1→6',
    chaptersSummary:
      'La mitochondrie, le noyau et le cycle cellulaire + rappels compartiments et architecture cellulaire.',
    questionCount: 25,
    durationMinutes: 37.5,
    durationLabel: '37 min 30',
    badgeType: 'CUMULATIVE',
    badgeLabel: 'Cumulative',
    ecCode: 'Biologie cellulaire',
    description: 'Évaluation de synthèse sur l’intégration cellulaire et le cycle cellulaire.',
  },
  {
    id: 'c10',
    code: 'C10',
    title: 'Chimie — Colle cumulative EC',
    dominantPerimeter: 'Toute la chimie générale + toute l’organique',
    chaptersSummary:
      'Ensemble de la chimie générale (Ch1→4) et de la chimie organique (Ch1→8).',
    questionCount: 30,
    durationMinutes: 45,
    durationLabel: '45 min',
    badgeType: 'CUMULATIVE_EC',
    badgeLabel: 'Cumulative EC',
    ecCode: 'Chimie',
    description: 'Colle récapitulative couvrant l’intégralité de l’EC de Chimie.',
  },
  {
    id: 'c11',
    code: 'C11',
    title: 'Biochimie — Colle cumulative EC',
    dominantPerimeter: 'Biochimie Ch13→15 + Ch1→12',
    chaptersSummary:
      'Ensemble de la biochimie : Glucides, Lipides, Protéines et Enzymologie (15 chapitres).',
    questionCount: 30,
    durationMinutes: 45,
    durationLabel: '45 min',
    badgeType: 'CUMULATIVE_EC',
    badgeLabel: 'Cumulative EC',
    ecCode: 'Biochimie',
    description: 'Colle récapitulative couvrant l’intégralité de l’EC de Biochimie.',
  },
  {
    id: 'c12',
    code: 'C12',
    title: 'Grande colle UE14',
    dominantPerimeter: 'Chimie + Biochimie + Biologie cellulaire',
    chaptersSummary:
      'Épreuve transversale globale couvrant l’ensemble des 3 EC (Chimie, Biochimie, Biologie cellulaire).',
    questionCount: 50,
    durationMinutes: 75,
    durationLabel: '75 min (1 h 15)',
    badgeType: 'GRANDE_COLLE',
    badgeLabel: 'Grande colle UE14',
    ecCode: 'UE14',
    description: 'Épreuve transversale d’évaluation globale UE14.',
  },
];
