import type { HealthTrainingAuthorQuestion } from '@/core/questions/health-author-question.types';

/**
 * UE14 — Colle C03 — Biologie cellulaire — Architecture cellulaire
 * Questions dédiées à l’évaluation ; ne pas exposer dans les quiz d’apprentissage.
 * Périmètre : Biologie cellulaire Ch. 1 à 3 — organisation/méthodes, membrane plasmique, cytosquelette.
 */
export const UE14_COLLE_C03_QUESTIONS: HealthTrainingAuthorQuestion[] = [
  {
    order: 1,
    difficulty: 'HARD',
    format: 'QRM',
    question: "Pour localiser la protéine X et suivre sa dynamique cellulaire, quelles propositions sont exactes ?",
    explanation: "Les méthodes de marquage ne répondent pas toutes au même objectif. L’immunomarquage d’une cible intracellulaire est classiquement réalisé sur des cellules fixées et perméabilisées afin de permettre l’accès des anticorps. L’hybridation in situ repose sur l’appariement d’une sonde nucléotidique avec une séquence complémentaire d’ADN ou d’ARN. Une protéine chimérique fusionnée à une protéine fluorescente telle que la GFP peut, elle, être suivie dans une cellule vivante.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:methodes-etude-cellulaire'],
    choices: [
      {
        content: "Un immunomarquage sur une protéine intracellulaire nécessite des cellules fixées puis rendues perméables aux anticorps.",
        correct: true,
        explanation: "Vrai. La fixation immobilise les structures cellulaires et la perméabilisation permet aux anticorps d’atteindre une cible intracellulaire.",
      },
      {
        content: "Une hybridation in situ permet de localiser une séquence d’ADN ou d’ARN grâce à une sonde nucléotidique complémentaire.",
        correct: true,
        explanation: "Vrai. L’hybridation in situ exploite la complémentarité des séquences nucléotidiques.",
      },
      {
        content: "Une protéine fusionnée à la GFP peut être observée au cours du temps dans une cellule vivante.",
        correct: true,
        explanation: "Vrai. Une fusion à la GFP permet de visualiser la localisation et éventuellement la dynamique d’une protéine dans une cellule vivante.",
      },
      {
        content: "L’électroporation consiste à fixer irréversiblement la membrane plasmique afin d’empêcher tout échange avec le milieu.",
        correct: false,
        explanation: "Faux. L’électroporation provoque transitoirement une perméabilisation de la membrane par une impulsion électrique ; elle ne sert pas à fixer la cellule.",
      },
      {
        content: "L’hybridation in situ repose sur la reconnaissance antigène–anticorps.",
        correct: false,
        explanation: "Faux. La reconnaissance antigène–anticorps relève de l’immunomarquage, pas de l’hybridation in situ.",
      },
    ],
  },
  {
    order: 2,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: "Après confluence, ces cellules sont décollées puis repiquées une première fois. Comment appelle-t-on la culture obtenue après ce premier passage ?",
    explanation: "La culture obtenue directement après l’isolement des cellules constitue la culture primaire. Lorsqu’elles atteignent la confluence, les cellules peuvent être décollées puis repiquées : après ce premier passage, on obtient une culture secondaire.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:culture-cellulaire'],
    answer: {
      type: 'text',
      acceptedAnswers: ['culture secondaire', 'secondaire'],
      normalization: {
        trim: true,
        collapseWhitespace: true,
        caseSensitive: false,
        ignoreAccents: true,
        normalizeUnicode: true,
      },
    },
  },
  {
    order: 3,
    difficulty: 'MEDIUM',
    format: 'QRU',
    question: "Après différenciation, les cellules présentent des domaines membranaires apical et basolatéral distincts. Quel dispositif contribue directement à empêcher la diffusion latérale des protéines d’un domaine à l’autre ?",
    explanation: "Les jonctions serrées forment une barrière au niveau de la région apico-latérale de nombreuses cellules épithéliales. Elles participent au maintien de la polarité en limitant notamment la diffusion latérale de constituants membranaires entre les domaines apical et basolatéral.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:polarite-membranaire'],
    choices: [
      {
        content: "Les jonctions serrées.",
        correct: true,
        explanation: "Vrai. Les jonctions serrées séparent les domaines apical et basolatéral.",
      },
      {
        content: "Les ribosomes libres.",
        correct: false,
        explanation: "Faux. Les ribosomes participent à la synthèse protéique.",
      },
      {
        content: "Les lysosomes.",
        correct: false,
        explanation: "Faux. Les lysosomes sont des compartiments de dégradation.",
      },
      {
        content: "Les nucléoles.",
        correct: false,
        explanation: "Faux. Le nucléole est une structure nucléaire.",
      },
      {
        content: "Les corpuscules basaux.",
        correct: false,
        explanation: "Faux. Les corpuscules basaux organisent les microtubules des cils.",
      },
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: "Sélectionnez exactement les deux exemples de transport passif à travers la membrane plasmique.",
    explanation: "Un transport passif suit le gradient électrochimique et ne nécessite pas d’apport énergétique pour déplacer le soluté contre ce gradient.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:transport-passif'],
    choices: [
      { content: "L’export d’un médicament par un transporteur ABC utilisant directement l’ATP.", correct: false, explanation: "L’utilisation directe de l’énergie de l’ATP caractérise ici un transport actif primaire." },
      { content: "Le passage de l’oxygène directement à travers la bicouche lipidique.", correct: true, explanation: "Une petite molécule liposoluble comme l’oxygène peut diffuser directement à travers la bicouche selon son gradient." },
      { content: "Le déplacement d’un soluté contre son gradient grâce à l’hydrolyse d’ATP.", correct: false, explanation: "Un déplacement contre le gradient avec consommation directe d’ATP relève d’un transport actif." },
      { content: "L’entrée d’un soluté contre son gradient couplée au passage d’un ion suivant son propre gradient.", correct: false, explanation: "Ce couplage correspond à un transport actif secondaire." },
      { content: "Le passage de l’eau par une aquaporine selon son gradient.", correct: true, explanation: "Une aquaporine est un canal permettant un transport passif rapide de l’eau." },
    ],
  },
  {
    order: 5,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: "À propos de l’organisation et de la dynamique de la membrane plasmique, quelles propositions sont exactes ?",
    explanation: "La membrane est une bicouche lipidique fluide et asymétrique. Sa fluidité dépend notamment de la composition en acides gras et du cholestérol, tandis que les glucides membranaires sont exposés du côté extracellulaire.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:structure-membrane'],
    choices: [
      { content: "Les phospholipides sont amphiphiles et s’organisent spontanément de façon à soustraire leurs chaînes hydrophobes au milieu aqueux.", correct: true, explanation: "Le caractère amphiphile des phospholipides favorise leur organisation en bicouche dans un environnement aqueux." },
      { content: "Des chaînes d’acides gras plus longues et plus saturées tendent à diminuer la fluidité de la bicouche.", correct: true, explanation: "Elles renforcent les interactions hydrophobes et les forces de Van der Waals entre chaînes." },
      { content: "Les glycolipides et les chaînes glucidiques des glycoprotéines sont confinés au feuillet cytosolique de la membrane plasmique.", correct: false, explanation: "Les glucides membranaires sont exposés du côté extracellulaire et participent notamment au glycocalyx." },
      { content: "Les deux feuillets de la membrane plasmique ont nécessairement une composition lipidique identique.", correct: false, explanation: "La membrane est asymétrique : certains phospholipides sont enrichis préférentiellement dans l’un ou l’autre feuillet." },
      { content: "Les protéines et les lipides membranaires sont totalement immobiles dans le plan de la bicouche.", correct: false, explanation: "La membrane est fluide ; de nombreux constituants diffusent latéralement dans son plan." },
    ],
  },
  {
    order: 6,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: "Combien de protofilaments comporte typiquement un microtubule cytoplasmique ? Donnez uniquement la valeur numérique.",
    explanation: "Un microtubule cytoplasmique canonique est un cylindre creux constitué de 13 protofilaments.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:microtubules'],
    answer: { type: 'number', value: 13, tolerance: 0 },
  },
  {
    order: 7,
    difficulty: 'MEDIUM',
    format: 'QRU',
    question: "Une cellule libère un médiateur qui diffuse sur quelques micromètres et agit sur des cellules voisines. Quel mode de communication est décrit ?",
    explanation: "La communication paracrine correspond à l’action locale d’un signal diffusible sur des cellules proches de la cellule émettrice.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:communication-cellulaire'],
    choices: [
      { content: "Communication endocrine.", correct: false, explanation: "La communication endocrine utilise la circulation sanguine pour atteindre des cibles souvent éloignées." },
      { content: "Communication juxtacrine.", correct: false, explanation: "La communication juxtacrine nécessite un contact physique entre cellules ou entre une cellule et la matrice extracellulaire." },
      { content: "Communication paracrine.", correct: true, explanation: "Le signal agit localement sur des cellules voisines." },
      { content: "Communication autocrine.", correct: false, explanation: "Dans une communication autocrine, la cellule émettrice répond elle-même au signal qu’elle produit." },
      { content: "Communication synaptique chimique.", correct: false, explanation: "La communication synaptique implique la libération ciblée d’un neurotransmetteur dans une fente synaptique." },
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: "Sélectionnez exactement les deux associations correctes concernant les polymères du cytosquelette.",
    explanation: "Les microtubules sont construits à partir de tubuline α/β et les microfilaments à partir d’actine. Les filaments intermédiaires forment une famille distincte de polymères fibreux.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:cytosquelette-composition'],
    choices: [
      { content: "Microtubule — hétérodimères de tubuline α/β.", correct: true, explanation: "Les hétérodimères α/β-tubuline s’assemblent en protofilaments puis en microtubules." },
      { content: "Filament intermédiaire — polymère de tubuline β exclusivement.", correct: false, explanation: "Les filaments intermédiaires sont constitués de protéines fibreuses variées telles que kératines, vimentine, neurofilaments ou lamines." },
      { content: "Microtubule — polymère de myosine II.", correct: false, explanation: "La myosine II est une protéine motrice associée à l’actine, pas le monomère constitutif des microtubules." },
      { content: "Microfilament — actine.", correct: true, explanation: "Les microfilaments correspondent à de l’actine F formée par polymérisation de l’actine G." },
      { content: "Microfilament — dimères de spectrine.", correct: false, explanation: "La spectrine participe notamment au cytosquelette membranaire de l’hématie ; les microfilaments sont constitués d’actine." },
    ],
  },
  {
    order: 9,
    difficulty: 'MEDIUM',
    format: 'QRPL',
    requiredSelectionCount: 5,
    question: "Parmi ces dix propositions couvrant méthodes d’étude, membrane plasmique et cytosquelette, sélectionnez exactement les cinq correctes.",
    explanation: "Cette synthèse mobilise les trois premiers chapitres : choix des méthodes selon l’état vivant ou fixé de la cellule, asymétrie membranaire et transport, ainsi que structure et dynamique des principaux polymères du cytosquelette.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:synthese-ch1-ch3'],
    choices: [
      { content: "Une culture primaire peut être obtenue à partir de cellules dissociées d’un tissu.", correct: true, explanation: "Des cellules isolées d’un tissu peuvent être mises en culture pour constituer une culture primaire." },
      { content: "L’hybridation in situ est une méthode destinée uniquement à identifier des protéines.", correct: false, explanation: "Elle met en évidence des séquences d’ADN ou d’ARN par complémentarité nucléotidique." },
      { content: "Les glucides de la membrane plasmique sont exposés du côté extracellulaire.", correct: true, explanation: "Ils participent au glycocalyx du feuillet exoplasmique." },
      { content: "Une scramblase tend à rééquilibrer des phospholipides entre les deux feuillets.", correct: true, explanation: "Son action favorise une redistribution bidirectionnelle et tend à réduire l’asymétrie pour les phospholipides concernés." },
      { content: "Une diffusion facilitée déplace nécessairement un soluté contre son gradient.", correct: false, explanation: "La diffusion facilitée est un transport passif qui suit le gradient électrochimique." },
      { content: "La β-tubuline peut fixer et hydrolyser le GTP.", correct: true, explanation: "Le GTP porté par la β-tubuline est hydrolysable et participe à la dynamique des microtubules." },
      { content: "Les filaments intermédiaires possèdent une polarité structurale +/− aussi marquée que celle des microtubules.", correct: false, explanation: "Les filaments intermédiaires sont considérés comme non polarisés, avec deux extrémités équivalentes." },
      { content: "La myosine II peut participer à une contraction en association avec l’actine.", correct: true, explanation: "L’interaction actine–myosine II permet notamment la contraction des structures actomyosiniques." },
      { content: "Les microtubules cytoplasmiques sont constitués d’actine G.", correct: false, explanation: "Ils sont constitués de tubuline α/β ; l’actine G polymérise en microfilaments." },
      { content: "Un axonème de cil mobile est constitué de neuf triplets périphériques autour d’un triplet central.", correct: false, explanation: "Le schéma classique d’un cil ou flagelle mobile est formé de neuf doublets périphériques autour d’une paire centrale de microtubules." },
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    format: 'QRM',
    question: "À propos de la culture cellulaire, quelles propositions sont exactes ?",
    explanation: "La culture cellulaire permet de maintenir et multiplier des cellules hors de leur environnement naturel. Les cellules normales ont généralement une capacité de prolifération limitée, tandis que des lignées tumorales ou transformées peuvent devenir immortelles.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:culture-cellulaire'],
    choices: [
      { content: "Une culture primaire peut provenir de cellules normales ou tumorales fraîchement isolées.", correct: true, explanation: "La notion de culture primaire décrit la mise en culture initiale de cellules isolées, quelle que soit l’origine normale ou tumorale du tissu." },
      { content: "Le passage cellulaire consiste notamment à décoller puis repiquer des cellules devenues confluentes.", correct: true, explanation: "Le repiquage permet de poursuivre la culture après confluence." },
      { content: "Des cellules normales ont généralement une durée de vie en culture illimitée sans transformation.", correct: false, explanation: "Les cellules normales finissent généralement par cesser de proliférer après un nombre limité de passages." },
      { content: "Une lignée tumorale ou une cellule transformée peut acquérir un potentiel de division durable.", correct: true, explanation: "L’immortalisation permet une prolifération prolongée dans des conditions de culture adaptées." },
      { content: "Des cellules dissociées peuvent être cultivées en modèles 3D ou en interface air–liquide selon l’objectif expérimental.", correct: true, explanation: "La culture cellulaire ne se limite pas aux monocouches 2D : des modèles 3D et des interfaces air–liquide sont également utilisés." },
    ],
  },
  {
    order: 11,
    difficulty: 'HARD',
    format: 'QROC',
    question: "Quel centre organisateur, situé près du noyau, organise et ancre une grande partie des microtubules cytoplasmiques ?",
    explanation: "Le centrosome est le principal centre organisateur des microtubules dans de nombreuses cellules animales ; les extrémités − des microtubules y sont généralement ancrées.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:centrosome'],
    answer: { type: 'text', acceptedAnswers: ['centrosome', 'le centrosome'], normalization: { trim: true, collapseWhitespace: true, caseSensitive: false, ignoreAccents: true, normalizeUnicode: true } },
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    format: 'QRU',
    question: "Un transporteur fait entrer un soluté contre son gradient en utilisant l’énergie libérée par l’entrée simultanée d’un ion suivant son propre gradient. Comment qualifier ce mécanisme ?",
    explanation: "L’énergie ne provient pas ici d’une hydrolyse directe d’ATP par le transporteur du soluté : elle provient du gradient d’un autre ion. Il s’agit donc d’un transport actif secondaire.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:transport-actif-secondaire'],
    choices: [
      { content: "Diffusion simple.", correct: false, explanation: "La diffusion simple ne fait intervenir ni transporteur ni couplage énergétique." },
      { content: "Transport actif secondaire.", correct: true, explanation: "Le gradient d’un premier soluté fournit l’énergie permettant le déplacement défavorable du second." },
      { content: "Transport actif primaire.", correct: false, explanation: "Le transport actif primaire utilise directement une source d’énergie, par exemple l’hydrolyse d’ATP." },
      { content: "Osmose pure.", correct: false, explanation: "L’osmose décrit un mouvement d’eau en réponse à une différence de potentiel osmotique." },
      { content: "Diffusion facilitée indépendante de tout gradient.", correct: false, explanation: "Une diffusion facilitée reste passive et suit le gradient électrochimique du soluté transporté." },
    ],
  },
  {
    order: 13,
    difficulty: 'HARD',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: "Sélectionnez exactement les deux organisations microtubulaires correctement associées à leur structure.",
    explanation: "Les centrioles et corpuscules basaux comportent neuf triplets de microtubules, tandis qu’un cil ou flagelle mobile possède classiquement un axonème à neuf doublets périphériques et une paire centrale.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:microtubules-stabilises'],
    choices: [
      { content: "Cil primaire — neuf triplets périphériques autour d’une paire centrale.", correct: false, explanation: "Le cil primaire comporte classiquement neuf doublets périphériques sans paire centrale." },
      { content: "Centriole — neuf triplets de microtubules.", correct: true, explanation: "Un centriole est construit à partir de neuf triplets disposés en cylindre." },
      { content: "Corpuscule basal — treize protofilaments libres non organisés en triplets.", correct: false, explanation: "Le corpuscule basal possède une organisation en neuf triplets, proche de celle du centriole." },
      { content: "Microtubule cytoplasmique — neuf doublets accolés.", correct: false, explanation: "Un microtubule cytoplasmique individuel est un cylindre généralement constitué de 13 protofilaments." },
      { content: "Cil mobile — neuf doublets périphériques autour d’une paire centrale.", correct: true, explanation: "C’est l’organisation axonémale classique dite 9 + 2." },
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: "Une cellule en migration forme des lamellipodes et des filopodes à son front. Quelles propositions sont exactes ?",
    explanation: "La migration cellulaire mobilise fortement l’actine : polymérisation au front, organisation en faisceaux ou réseaux, puis contraction et recyclage dans les régions plus postérieures.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:actine-migration'],
    choices: [
      { content: "La polymérisation de l’actine à l’avant de la cellule contribue à pousser la membrane plasmique.", correct: true, explanation: "L’allongement des filaments d’actine participe à la protrusion du bord d’attaque." },
      { content: "Les lamellipodes comportent notamment des réseaux d’actine associés à la filamine.", correct: true, explanation: "La filamine organise des réseaux d’actine participant à l’architecture des lamellipodes." },
      { content: "La myosine II peut participer aux structures contractiles responsables de la rétraction.", correct: true, explanation: "Les interactions actine–myosine II génèrent des forces contractiles." },
      { content: "Les filaments d’actine sont dépourvus de polarité structurale.", correct: false, explanation: "Les microfilaments possèdent des extrémités + et − distinctes." },
      { content: "La migration cellulaire repose exclusivement sur des filaments intermédiaires immobiles.", correct: false, explanation: "Elle dépend fortement de la dynamique de l’actine, en coordination avec les adhérences et d’autres éléments du cytosquelette." },
    ],
  },
  {
    order: 15,
    difficulty: 'EASY',
    format: 'QROC',
    question: "Quel moteur moléculaire se déplace classiquement vers l’extrémité − des microtubules cytoplasmiques ?",
    explanation: "La dynéine cytoplasmique assure classiquement un transport rétrograde vers l’extrémité − des microtubules.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:moteurs-microtubules'],
    answer: { type: 'text', acceptedAnswers: ['dynéine', 'dyneine', 'dynéine cytoplasmique', 'dyneine cytoplasmique'], normalization: { trim: true, collapseWhitespace: true, caseSensitive: false, ignoreAccents: true, normalizeUnicode: true } },
  },
  {
    order: 16,
    difficulty: 'EASY',
    format: 'QRU',
    question: "Quelle protéine appartient aux filaments intermédiaires nucléaires ?",
    explanation: "Les lamines forment le réseau de filaments intermédiaires associé à la face interne de l’enveloppe nucléaire. Elles ne doivent pas être confondues avec la laminine, glycoprotéine de la matrice extracellulaire.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:filaments-intermediaires'],
    choices: [
      { content: "La laminine.", correct: false, explanation: "La laminine est une glycoprotéine de la matrice extracellulaire, notamment des lames basales." },
      { content: "La tubuline β.", correct: false, explanation: "La tubuline β entre dans la constitution des microtubules." },
      { content: "La myosine I.", correct: false, explanation: "La myosine I est une protéine motrice associée à l’actine." },
      { content: "La lamine.", correct: true, explanation: "Les lamines sont les protéines de filaments intermédiaires formant la lamina nucléaire." },
      { content: "La fibronectine.", correct: false, explanation: "La fibronectine est une glycoprotéine de la matrice extracellulaire." },
    ],
  },
  {
    order: 17,
    difficulty: 'HARD',
    format: 'QRM',
    question: "En vous appuyant sur l’organisation de cet entérocyte polarisé, quelles propositions sont exactes ?",
    explanation: "L’entérocyte illustre la polarité d’une cellule épithéliale. Les microvillosités apicales sont soutenues par des faisceaux d’actine, tandis que les jonctions serrées participent au maintien de domaines membranaires distincts. Les intégrines sont surtout des récepteurs d’adhérence cellule–matrice ; le glycocalyx est exposé du côté extracellulaire. Enfin, les lamines sont des filaments intermédiaires nucléaires, à distinguer de la laminine de la matrice extracellulaire.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:architecture-epitheliale'],
    choices: [
      {
        content: "Les microvillosités apicales sont soutenues par des faisceaux de filaments d’actine.",
        correct: true,
        explanation: "Vrai. Le cœur cytosquelettique des microvillosités est constitué de faisceaux parallèles de filaments d’actine.",
      },
      {
        content: "Les jonctions serrées contribuent à maintenir la distinction entre domaines apical et basolatéral.",
        correct: true,
        explanation: "Vrai. Les jonctions serrées participent à la séparation fonctionnelle des domaines apical et basolatéral.",
      },
      {
        content: "Les intégrines assurent exclusivement des liaisons homophiles entre deux cellules épithéliales voisines.",
        correct: false,
        explanation: "Faux. Les intégrines assurent principalement des interactions cellule–matrice et ne sont pas définies comme des molécules d’adhérence homophile entre deux cellules voisines.",
      },
      {
        content: "Le glycocalyx est porté exclusivement par la face cytosolique de la membrane plasmique.",
        correct: false,
        explanation: "Faux. Les glucides membranaires et le glycocalyx sont exposés du côté extracellulaire.",
      },
      {
        content: "La laminine est un filament intermédiaire nucléaire qui remplace les lamines dans les cellules épithéliales.",
        correct: false,
        explanation: "Faux. Les lamines constituent la lamina nucléaire ; la laminine est une protéine de matrice extracellulaire.",
      },
    ],
  },
  {
    order: 18,
    difficulty: 'HARD',
    format: 'QRM',
    question: "Cet entérocyte absorbe du glucose depuis la lumière intestinale puis le libère vers le sang. Quelles propositions décrivent correctement les principes de transport impliqués ?",
    explanation: "L’absorption intestinale du glucose repose sur la polarité de l’entérocyte. À l’apex, le cotransport sodium–glucose est un transport actif secondaire : il exploite le gradient électrochimique du sodium sans hydrolyser lui-même l’ATP. Ce gradient est entretenu notamment par la Na⁺/K⁺-ATPase basolatérale. Le glucose peut ensuite quitter la cellule au pôle basolatéral par diffusion facilitée. La répartition asymétrique des transporteurs rend l’ensemble du transport vectoriel.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:transport-glucose'],
    choices: [
      {
        content: "L’entrée apicale du glucose couplée à celle du sodium peut utiliser l’énergie stockée dans le gradient de sodium.",
        correct: true,
        explanation: "Vrai. Le gradient de sodium fournit l’énergie au cotransport apical.",
      },
      {
        content: "La Na⁺/K⁺-ATPase contribue indirectement à l’absorption apicale du glucose en maintenant le gradient de sodium.",
        correct: true,
        explanation: "Vrai. La Na⁺/K⁺-ATPase entretient le gradient de sodium indispensable au transport actif secondaire.",
      },
      {
        content: "La sortie basolatérale du glucose peut relever d’un transport facilité suivant son gradient.",
        correct: true,
        explanation: "Vrai. La sortie basolatérale du glucose peut s’effectuer par diffusion facilitée.",
      },
      {
        content: "Le symport sodium–glucose hydrolyse obligatoirement lui-même une molécule d’ATP pour chaque glucose transporté.",
        correct: false,
        explanation: "Faux. Le cotransporteur sodium–glucose utilise indirectement l’énergie de l’ATP via le gradient de sodium ; il n’est pas lui-même une ATPase.",
      },
      {
        content: "Le caractère vectoriel de l’absorption dépend notamment d’une distribution différente des transporteurs entre domaines apical et basolatéral.",
        correct: true,
        explanation: "Vrai. La polarisation des transporteurs entre les deux domaines membranaires permet un flux orienté de la lumière intestinale vers le milieu intérieur.",
      },
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    format: 'QZONE',
    question: "Sur l’agrandissement d’une microvillosité apicale, sélectionnez le faisceau de filaments d’actine qui en constitue l’axe cytosquelettique.",
    explanation: "Les microvillosités des cellules épithéliales digestives sont soutenues par des faisceaux parallèles de microfilaments d’actine. Ces faisceaux maintiennent l’architecture des microvillosités et se prolongent vers le réseau d’actine sous-apical.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:qzone-actine-microvillosited'],
    image: {
      src: '/images/training/ue14/colles/c03/enterocyte-linked-q17-q19.svg',
      alt: 'Schéma d’un entérocyte polarisé avec microvillosités apicales, membranes apicale et basolatérale, jonction apico-latérale et agrandissement d’une microvillosité.',
      width: 1200,
      height: 700,
    },
    expectedZones: [
      {
        id: 'target-actin-bundle',
        label: 'Faisceau de filaments d’actine',
        x: 0.7708,
        y: 0.5143,
        tolerance: 0.05,
      },
    ],
    defaultTolerance: 0.05,
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: "Comparez microtubules, microfilaments d’actine et filaments intermédiaires. Quelles propositions sont exactes ?",
    explanation: "Les trois réseaux diffèrent par leur composition, leur polarité et leurs fonctions. Microtubules et actine sont très dynamiques et polarisés, tandis que les filaments intermédiaires sont plus stables et assurent surtout une résistance mécanique.",
    tags: ['usage:COLLE', 'ue:UE14', 'colle:C03', 'ec:BIOLOGIE_CELLULAIRE', 'theme:comparaison-cytosquelette'],
    choices: [
      { content: "Les microtubules participent au transport intracellulaire en servant de rails à des moteurs comme les kinésines et les dynéines.", correct: true, explanation: "Des vésicules et organites peuvent être transportés le long des microtubules par des protéines motrices." },
      { content: "Les microfilaments d’actine peuvent participer à la contraction avec la myosine II.", correct: true, explanation: "L’interaction actine–myosine II est à la base de nombreuses structures contractiles." },
      { content: "Les filaments intermédiaires contribuent à la résistance mécanique des cellules et des tissus.", correct: true, explanation: "Ils résistent particulièrement bien aux forces d’étirement et de déformation." },
      { content: "Les filaments intermédiaires sont des polymères très polarisés dont l’extrémité + sert de piste à la dynéine.", correct: false, explanation: "Les filaments intermédiaires sont non polarisés et la dynéine est un moteur associé aux microtubules." },
      { content: "Kinésines et dynéines utilisent les filaments intermédiaires comme rails principaux de transport intracellulaire.", correct: false, explanation: "Ces moteurs se déplacent principalement le long des microtubules ; les filaments intermédiaires assurent surtout des fonctions de résistance et d’architecture." },
    ],
  },
];
