import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_E_ORDER = 5;

export const SECTION_E_SYNTHESIS_PRACTICE_QUIZ_SLUG =
  `section-e-synthesis-practice-acides-divers`;
export const SECTION_E_SYNTHESIS_MASTER_QUIZ_SLUG =
  `section-e-synthesis-master-examen-acides-divers`;

export const SECTION_E_SYNTHESIS_PRACTICE_QUESTION_ORDERS: number[] = [121, 122, 123, 124, 125, 126, 127, 128, 129, 130];
export const SECTION_E_SYNTHESIS_MASTER_QUESTION_ORDERS: number[] = [131, 132, 133, 134, 135, 136, 137, 138, 139, 140];

export const SECTION_E_QUIZZES: SeedQuiz[] = [
  {
    order: 13,
    slug: SECTION_E_SYNTHESIS_PRACTICE_QUIZ_SLUG,
    title: `Synthèse guidée : acides et acides nucléiques`,
    description: `Mobiliser nomenclature, acidité, voies de préparation, décarboxylation et structure des nucléotides.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_E_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 121 },
      { type: 'QUESTION', questionOrder: 122 },
      { type: 'QUESTION', questionOrder: 123 },
      { type: 'QUESTION', questionOrder: 124 },
      { type: 'QUESTION', questionOrder: 125 },
      { type: 'QUESTION', questionOrder: 126 },
      { type: 'QUESTION', questionOrder: 127 },
      {
        type: 'GROUP',
        title: `Carboxylation puis décarboxylation`,
        sharedStatement: `Le bromure de propylmagnésium réagit avec $\\mathrm{CO_2}$ pour former un acide après traitement. Cet acide est ensuite placé dans des conditions de décarboxylation.`,
        questionOrders: [128, 129, 130],
      },
    ],
  },
  {
    order: 14,
    slug: SECTION_E_SYNTHESIS_MASTER_QUIZ_SLUG,
    title: `Synthèse type examen : les acides et divers`,
    description: `Résoudre des questions transversales mêlant dérivés d'''acides, bilan carbone, nucléotides et toxicologie.`,
    stage: 'MASTER',
    sectionOrder: SECTION_E_ORDER,
    items: [
      {
        type: 'GROUP',
        title: `De l'''acide butyrique à un amide`,
        sharedStatement: `Un laboratoire dispose d'''acide butyrique, souhaite caractériser sa base conjuguée puis préparer un amide à partir de cet acide.`,
        questionOrders: [131, 132, 133],
      },
      { type: 'QUESTION', questionOrder: 134 },
      { type: 'QUESTION', questionOrder: 135 },
      { type: 'QUESTION', questionOrder: 136 },
      { type: 'QUESTION', questionOrder: 137 },
      {
        type: 'GROUP',
        title: `Décarboxylation enzymatique`,
        sharedStatement: `Une enzyme transforme un acide organique carbonylé en un produit possédant un carbone de moins, avec dégagement gazeux.`,
        questionOrders: [138, 139, 140],
      },
    ],
  },
];

export const SECTION_E_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `�' propos de l'acide éthanoïque :`,
    choices: [
      `Sa formule est $\\mathrm{CH_3COOH}$.`,
      `Sa base conjuguée est l'ion acétate.`,
      `Son nom usuel est acide acétique.`,
      `Il s'agit d'un nucléoside.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette question rassemble structure, nomenclature et comportement acido-basique.`,
    choiceExplanations: [
      `Il possède deux carbones.`,
      `La perte de $\\mathrm{H^+}$ donne $\\mathrm{CH_3COO^-}$.`,
      `Les deux noms sont synonymes.`,
      `C'est un acide carboxylique simple.`,
    ],
  },
  {
    order: 122,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La faible électrophilie d'un acide carboxylique non activé s'explique par :`,
    choices: [
      `La délocalisation électronique impliquant les deux oxygènes.`,
      `La mauvaise aptitude du groupe $\\mathrm{OH}$ à partir dans de nombreuses conditions.`,
      `L'absence totale de carbonyle.`,
      `Une charge positive entière sur chaque oxygène.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'activation remédie à ces deux limites en augmentant l'électrophilie et en introduisant un meilleur groupe partant.`,
    choiceExplanations: [
      `Elle stabilise la fonction.`,
      `Cela limite les substitutions d'acyle.`,
      `Le groupe $\\mathrm{C{=}O}$ est présent.`,
      `Ce n'est pas la structure de l'acide.`,
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les transformations suivantes, lesquelles préparent un acide carboxylique ?`,
    choices: [
      `Oxydation poussée d'un alcool primaire.`,
      `Hydrolyse complète d'un nitrile.`,
      `Carboxylation d'un organomagnésien par $\\mathrm{CO_2}$.`,
      `Oxydation simple d'un alcool secondaire sans rupture.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Plusieurs voies sont possibles, mais elles n'ont pas le même effet sur le nombre de carbones.`,
    choiceExplanations: [
      `Elle mène à $\\mathrm{RCOOH}$.`,
      `Elle passe par un amide.`,
      `Elle ajoute un carbone.`,
      `Elle donne une cétone.`,
    ],
  },
  {
    order: 124,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une décarboxylation :`,
    choices: [
      `Libère $\\mathrm{CO_2}$.`,
      `Réduit d'une unité le nombre de carbones du produit organique.`,
      `Est facilitée dans certains composés portant un carbonyle voisin.`,
      `Ajoute toujours un groupe phosphate.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La structure du substrat détermine la facilité de la perte du carboxyle.`,
    choiceExplanations: [
      `C'est le produit caractéristique.`,
      `Le carbone carboxylique est perdu.`,
      `La délocalisation stabilise la transformation.`,
      `Les deux notions sont indépendantes.`,
    ],
  },
  {
    order: 125,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans un nucléotide :`,
    choices: [
      `La base peut être nucléophile.`,
      `Le phosphate contribue à l'acidité.`,
      `Le sucre peut être ribose ou 2-désoxyribose.`,
      `Une fonction $\\mathrm{COOH}$ est obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une même molécule combine une base de Lewis et un groupe acide.`,
    choiceExplanations: [
      `Ses hétéroatomes peuvent donner des électrons.`,
      `Il porte des protons ionisables et des charges.`,
      `Selon ARN ou ADN.`,
      `L'acidité est phosphate, pas carboxylique.`,
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un dérivé halogéné électrophile rencontre une base nucléique :`,
    choices: [
      `Une substitution nucléophile peut modifier la base.`,
      `Une liaison covalente anormale peut être formée.`,
      `Une mutation est possible si la lésion persiste.`,
      `Le dérivé devient obligatoirement un acide butanoïque.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le contexte biologique repose sur les mêmes principes de réactivité organique que les substitutions étudiées.`,
    choiceExplanations: [
      `Le doublet de la base attaque le carbone électrophile.`,
      `C'est un adduit.`,
      `Elle peut être fixée lors de la réplication.`,
      `Aucune transformation de ce type n'est nécessaire.`,
    ],
  },
  {
    order: 127,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On souhaite obtenir l'acide propanoïque. Quelles stratégies sont cohérentes ?`,
    choices: [
      `Oxyder le propan-1-ol.`,
      `Hydrolyser le propanenitrile.`,
      `Faire réagir l'éthylmagnésium avec $\\mathrm{CO_2}$.`,
      `Décarboxyler l'acide propanoïque.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Trois voies différentes convergent vers le même acide en respectant le bilan carbone.`,
    choiceExplanations: [
      `Le nombre de carbones est conservé.`,
      `Le carbone cyano devient carboxyle.`,
      `Le produit gagne un carbone.`,
      `Cela donnerait un produit à deux carbones.`,
    ],
  },
  {
    order: 128,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quel est le produit acide attendu ?`,
    choices: [
      `L'acide butanoïque.`,
      `L'acide propanoïque.`,
      `Un acide à quatre carbones.`,
      `Une cétone à trois carbones.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Le carbone du dioxyde de carbone devient le carbone de la fonction carboxylique.`,
    choiceExplanations: [
      `Trois carbones du propyle plus celui du $\\mathrm{CO_2}$.`,
      `Il manquerait le carbone du $\\mathrm{CO_2}$.`,
      `Le bilan carbone l'impose.`,
      `Avec $\\mathrm{CO_2}$, on forme un acide.`,
    ],
  },
  {
    order: 129,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `�' propos du mécanisme conceptuel :`,
    choices: [
      `Le carbone du fragment propyle est nucléophile.`,
      `Le carbone du $\\mathrm{CO_2}$ est électrophile.`,
      `Une nouvelle liaison $\\mathrm{C{-}C}$ est formée.`,
      `Le $\\mathrm{CO_2}$ agit comme nucléophile principal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réaction est une addition nucléophile sur un carbone électrophile suivie de la formation de l'acide.`,
    choiceExplanations: [
      `La liaison C''�Mg lui confère un caractère riche en électrons.`,
      `Les oxygènes attirent la densité électronique.`,
      `Elle relie le propyle au carbone carboxylique.`,
      `Il est l'accepteur d'électrons.`,
    ],
  },
  {
    order: 130,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si l'acide formé subit ensuite une décarboxylation :`,
    choices: [
      `Le carbone apporté par le $\\mathrm{CO_2}$ peut être éliminé.`,
      `Le produit organique peut retrouver trois carbones.`,
      `Une seconde unité $\\mathrm{CO_2}$ est nécessairement incorporée.`,
      `Le produit final possède obligatoirement cinq carbones.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'enchaînement carboxylation''�décarboxylation permet de suivre précisément le devenir du carbone du $\\mathrm{CO_2}$.`,
    choiceExplanations: [
      `Il constitue le carboxyle.`,
      `Le squelette propyle initial subsiste.`,
      `La décarboxylation libère du gaz.`,
      `Il en perd un.`,
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un composé inconnu est nommé acide butyrique. On peut affirmer :`,
    choices: [
      `Qu'il s'agit de l'acide butanoïque.`,
      `Qu'il possède quatre carbones.`,
      `Que sa formule condensée peut être $\\mathrm{CH_3CH_2CH_2COOH}$.`,
      `Qu'il est un nucléotide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La nomenclature doit être reliée à la structure sans confondre noms usuels et classes biologiques.`,
    choiceExplanations: [
      `Butyrique est le nom usuel.`,
      `Le carbone carboxylique est inclus.`,
      `C'est la structure linéaire correspondante.`,
      `Il ne comporte ni base ni phosphate.`,
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L'ion butanoate formé par déprotonation :`,
    choices: [
      `Porte une charge négative délocalisée.`,
      `Est la base conjuguée de l'acide butanoïque.`,
      `Est plus riche en électrons que l'acide neutre.`,
      `Possède un groupe phosphate obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La déprotonation ne modifie ni le nombre de carbones ni le squelette, seulement l'état protonique et électronique.`,
    choiceExplanations: [
      `Elle est répartie sur les deux oxygènes.`,
      `Le couple diffère d'un proton.`,
      `Il porte une charge négative.`,
      `Aucun phosphore n'est présent.`,
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour transformer efficacement cet acide en amide :`,
    choices: [
      `Une activation du groupe carboxyle peut être nécessaire.`,
      `Un chlorure d'acyle est un intermédiaire possible.`,
      `Une amine peut jouer le rôle de nucléophile.`,
      `La suppression de tout atome d'azote est indispensable.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La formation de l'amide réunit activation d'un électrophile et attaque d'un nucléophile azoté.`,
    choiceExplanations: [
      `L'acide libre est peu électrophile.`,
      `Il réagit facilement avec une amine.`,
      `Son doublet attaque le carbonyle.`,
      `L'azote forme la liaison amide.`,
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une structure contient une base azotée liée à un 2-désoxyribose, sans phosphate. Elle est :`,
    choices: [
      `Un nucléoside.`,
      `Compatible avec la série ADN.`,
      `Un nucléotide.`,
      `Un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La classification se fait en deux étapes : nature du sucre puis présence ou absence du phosphate.`,
    choiceExplanations: [
      `Base + sucre sans phosphate.`,
      `Le sucre est le 2-désoxyribose.`,
      `Le phosphate manque.`,
      `Aucun groupe carboxyle n'est indiqué.`,
    ],
  },
  {
    order: 135,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Après ajout d'un phosphate à cette structure :`,
    choices: [
      `Elle devient un nucléotide.`,
      `Son caractère acide augmente.`,
      `Le sucre devient automatiquement un ribose.`,
      `La base perd tous ses atomes d'azote.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'ajout du phosphate modifie la catégorie et les propriétés ioniques, pas l'identité du sucre ou de la base.`,
    choiceExplanations: [
      `Les trois composants sont réunis.`,
      `Le phosphate introduit des sites ionisables.`,
      `La phosphorylation ne change pas le groupe en 2'.`,
      `Elle est conservée.`,
    ],
  },
  {
    order: 136,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un électrophile halogéné réagit sur la base de ce nucléotide. Les affirmations exactes sont :`,
    choices: [
      `La base agit comme nucléophile.`,
      `Une modification covalente peut perturber l'appariement.`,
      `Le phosphate empêche absolument toute réaction de la base.`,
      `Une lésion mal réparée peut devenir une mutation.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Cette situation relie chimie de Lewis, structure des nucléotides et toxicologie génétique.`,
    choiceExplanations: [
      `Elle fournit une paire d'électrons.`,
      `La structure et les liaisons hydrogène peuvent changer.`,
      `Il n'annule pas nécessairement sa nucléophilie.`,
      `Elle peut être fixée lors de la réplication.`,
    ],
  },
  {
    order: 137,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les énoncés suivants, lesquels associent correctement réaction et bilan carbone ?`,
    choices: [
      `Carboxylation d'un organomagnésien : +1 carbone.`,
      `Décarboxylation : '��1 carbone.`,
      `Hydrolyse d'un nitrile : nombre de carbones conservé.`,
      `Oxydation d'un alcool primaire : '��2 carbones.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le suivi du nombre de carbones permet de résoudre de nombreux QCM de synthèse.`,
    choiceExplanations: [
      `Le $\\mathrm{CO_2}$ est incorporé.`,
      `Le $\\mathrm{CO_2}$ est libéré.`,
      `Le carbone cyano devient carboxyle.`,
      `Le squelette est normalement conservé.`,
    ],
  },
  {
    order: 138,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La réaction observée est-elle une décarboxylation ?`,
    choices: [
      `Oui, car du $\\mathrm{CO_2}$ est libéré.`,
      `Oui, car le produit organique possède un carbone de moins.`,
      `Non, car une enzyme est impliquée.`,
      `Non, car le substrat est biologique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les critères chimiques priment sur le contexte expérimental.`,
    choiceExplanations: [
      `C'est le critère principal.`,
      `Le bilan carbone le confirme.`,
      `Une décarboxylation peut être enzymatique.`,
      `La nature biologique n'exclut pas la réaction.`,
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quel facteur structural peut faciliter la réaction ?`,
    choices: [
      `La présence d'un carbonyle voisin du carboxyle.`,
      `Une possibilité de délocalisation électronique.`,
      `L'absence de toute fonction oxygénée.`,
      `Un groupe phosphate obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le motif carboxyle''�carbonyle est le cas favorable mis en avant dans la fiche.`,
    choiceExplanations: [
      `Il stabilise les électrons lors de la perte de $\\mathrm{CO_2}$.`,
      `Elle abaisse l'énergie de l'intermédiaire.`,
      `Le substrat doit au moins posséder le carboxyle.`,
      `Il n'est pas requis.`,
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Conséquences possibles de la réaction :`,
    choices: [
      `Le produit peut être moins acide si le seul carboxyle a disparu.`,
      `La masse molaire du produit organique diminue.`,
      `Le nombre de carbones du produit augmente.`,
      `Le gaz formé peut contribuer à déplacer la réaction.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La décarboxylation modifie à la fois le squelette, la masse et les propriétés acido-basiques du produit.`,
    choiceExplanations: [
      `La source principale de proton est perdue.`,
      `Une unité $\\mathrm{CO_2}$ est éliminée.`,
      `Il diminue.`,
      `Son échappement favorise souvent l'avancement.`,
    ],
  },
];
