import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_ORDER = 2;

export const SECTION_B_CLASSIC_ROUTES_DISCOVERY_QUIZ_SLUG =
  `section-b-discovery-preparation-oxydation-hydrolyse`;
export const SECTION_B_NITRILES_PRACTICE_QUIZ_SLUG =
  `section-b-practice-hydrolyse-nitriles`;
export const SECTION_B_SYNTHESIS_MASTER_QUIZ_SLUG =
  `section-b-master-carboxylation-organomagnesiens`;

export const SECTION_B_CLASSIC_ROUTES_DISCOVERY_QUESTION_ORDERS: number[] = [31, 32, 33, 34, 35, 36, 37, 38, 39, 40];
export const SECTION_B_NITRILES_PRACTICE_QUESTION_ORDERS: number[] = [41, 42, 43, 44, 45, 46, 47, 48, 49, 50];
export const SECTION_B_SYNTHESIS_MASTER_QUESTION_ORDERS: number[] = [51, 52, 53, 54, 55, 56, 57, 58, 59, 60];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: SECTION_B_CLASSIC_ROUTES_DISCOVERY_QUIZ_SLUG,
    title: `Préparer un acide par oxydation ou hydrolyse`,
    description: `Maîtriser les bilans simples à partir d'''un alcool primaire, d'''un ester ou d'''un amide.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_B_ORDER,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: SECTION_B_NITRILES_PRACTICE_QUIZ_SLUG,
    title: `Hydrolyse des nitriles`,
    description: `Suivre la transformation nitrile '�� amide '�� acide et compter correctement le carbone du groupe cyano.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 41 },
      { type: 'QUESTION', questionOrder: 42 },
      { type: 'QUESTION', questionOrder: 43 },
      { type: 'QUESTION', questionOrder: 44 },
      { type: 'QUESTION', questionOrder: 45 },
      { type: 'QUESTION', questionOrder: 46 },
      { type: 'QUESTION', questionOrder: 47 },
      {
        type: 'GROUP',
        title: `Allonger une chaîne avec le dioxyde de carbone`,
        sharedStatement: `Un organomagnésien est mis en présence de $\\mathrm{CO_2}$, puis le produit est traité pour obtenir l'''acide carboxylique final.`,
        questionOrders: [48, 49, 50],
      },
    ],
  },
  {
    order: 6,
    slug: SECTION_B_SYNTHESIS_MASTER_QUIZ_SLUG,
    title: `Choisir une voie de synthèse d'''un acide`,
    description: `Comparer hydrolyses, oxydation et carboxylation d'''organomagnésiens dans des problèmes de synthèse.`,
    stage: 'MASTER',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 51 },
      { type: 'QUESTION', questionOrder: 52 },
      { type: 'QUESTION', questionOrder: 53 },
      { type: 'QUESTION', questionOrder: 54 },
      { type: 'QUESTION', questionOrder: 55 },
      { type: 'QUESTION', questionOrder: 56 },
      {
        type: 'GROUP',
        title: `Préparation de l'''acide butanoïque`,
        sharedStatement: `On recherche une voie de synthèse efficace de l'''acide butanoïque en contrôlant le nombre de carbones du précurseur.`,
        questionOrders: [57, 58, 59],
      },
      { type: 'QUESTION', questionOrder: 60 },
    ],
  },
];

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'oxydation d'un alcool primaire peut conduire :`,
    choices: [
      `�' un acide carboxylique.`,
      `�' un alcool tertiaire.`,
      `�' une amine.`,
      `�' un dérivé halogéné sans oxygène.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L'alcool primaire peut passer par un aldéhyde avant d'atteindre l'acide carboxylique.`,
    choiceExplanations: [
      `Une oxydation suffisamment poussée transforme $\\mathrm{RCH_2OH}$ en $\\mathrm{RCOOH}$.`,
      `Ce n'est pas une oxydation.`,
      `Aucun azote n'est introduit.`,
      `Le produit reste oxygéné.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'hydrolyse d'un ester donne, dans le bilan simplifié du cours :`,
    choices: [
      `Un acide carboxylique.`,
      `Un alcool.`,
      `Un nitrile.`,
      `Du dioxyde de carbone comme seul produit.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le bilan est $\\mathrm{ester + eau \\rightarrow acide + alcool}$.`,
    choiceExplanations: [
      `Le fragment acyle devient acide.`,
      `Le fragment alkoxy devient alcool.`,
      `Aucun groupe cyano n'est formé.`,
      `Cela correspondrait à une décarboxylation, pas à une hydrolyse.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'hydrolyse d'un amide conduit :`,
    choices: [
      `�' un acide carboxylique.`,
      `�' une amine ou une espèce ammonium selon le milieu.`,
      `�' un alcène uniquement.`,
      `�' un chlorure d'acyle.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La rupture hydrolytique de la liaison amide fournit les deux partenaires dont elle pouvait être issue.`,
    choiceExplanations: [
      `Le fragment acyle devient acide.`,
      `Le fragment azoté est libéré.`,
      `Aucune élimination n'est décrite.`,
      `L'eau ne transforme pas spontanément l'amide en chlorure d'acyle.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `�' propos de la saponification des esters dans cette fiche :`,
    choices: [
      `Elle est citée comme voie de préparation d'un acide ou carboxylate.`,
      `Elle n'est pas développée en détail.`,
      `Elle correspond à la réduction d'un nitrile.`,
      `Elle forme nécessairement une cétone.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le quiz reste volontairement au niveau du bilan général car le mécanisme n'est pas détaillé dans le document.`,
    choiceExplanations: [
      `La voie est mentionnée.`,
      `La fiche indique explicitement « pas développé ».`,
      `Il s'agit d'une hydrolyse basique d'ester.`,
      `Le produit organique acyle est un carboxylate.`,
    ],
  },
  {
    order: 35,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On oxyde fortement le propan-1-ol. Le produit carboxylique attendu :`,
    choices: [
      `Est l'acide propanoïque.`,
      `Possède trois carbones.`,
      `Est l'acide éthanoïque.`,
      `Est la propanone.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'oxydation d'un alcool primaire conserve le squelette carboné tout en augmentant le degré d'oxydation du carbone fonctionnel.`,
    choiceExplanations: [
      `Le nombre de carbones est conservé.`,
      `Le carbone alcool devient le carbone carboxylique.`,
      `Aucun carbone n'est perdu.`,
      `Une cétone provient de l'oxydation d'un alcool secondaire.`,
    ],
  },
  {
    order: 36,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'hydrolyse de l'éthanoate de méthyle $\\mathrm{CH_3COOCH_3}$ peut produire :`,
    choices: [
      `L'acide éthanoïque.`,
      `Le méthanol.`,
      `L'acide méthanoïque.`,
      `L'éthanamine.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Pour prévoir les produits, on coupe conceptuellement la liaison acyle''�oxygène de l'ester.`,
    choiceExplanations: [
      `Le fragment $\\mathrm{CH_3CO{-}}$ devient $\\mathrm{CH_3COOH}$.`,
      `Le fragment $\\mathrm{-OCH_3}$ devient $\\mathrm{CH_3OH}$.`,
      `Le carbone du groupe méthyle lié à l'oxygène ne devient pas le carbone acide.`,
      `Aucun azote n'est présent.`,
    ],
  },
  {
    order: 37,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une molécule contient à la fois une fonction ester et une fonction amide. D'après les chapitres précédents :`,
    choices: [
      `L'ester est généralement hydrolysé plus facilement que l'amide.`,
      `Des conditions douces peuvent hydrolyser l'ester sans toucher l'amide.`,
      `L'amide est toujours détruit avant l'ester.`,
      `Aucune des deux fonctions n'est hydrolysable.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Cette question réinvestit la stabilité relative des dérivés d'acides.`,
    choiceExplanations: [
      `La liaison amide est stabilisée par résonance.`,
      `Cette sélectivité a été explicitement présentée.`,
      `C'est l'inverse en conditions comparables.`,
      `Les deux le sont, avec des difficultés différentes.`,
    ],
  },
  {
    order: 38,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Préparer un acide par hydrolyse signifie :`,
    choices: [
      `Utiliser l'eau comme réactif de rupture.`,
      `Rompre une liaison d'un dérivé d'acide.`,
      `Retirer obligatoirement $\\mathrm{CO_2}$.`,
      `Réduire le nombre d'atomes d'oxygène à zéro.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Plusieurs voies convergent vers le même groupe $\\mathrm{-COOH}$ par incorporation des éléments de l'eau.`,
    choiceExplanations: [
      `L'eau fournit les groupes nécessaires aux produits.`,
      `Ester, amide ou nitrile peuvent être hydrolysés.`,
      `Cela définirait une décarboxylation.`,
      `L'acide final contient deux oxygènes.`,
    ],
  },
  {
    order: 39,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un ester est hydrolysé en milieu acide. Parmi les propositions suivantes :`,
    choices: [
      `La fonction acide carboxylique du produit retrouve un groupe $\\mathrm{OH}$.`,
      `Le groupe alkoxy de l'ester donne un alcool.`,
      `Le nombre total de carbones des produits doit être inférieur à celui de l'ester.`,
      `La réaction est une décarboxylation.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le bilan conserve les atomes de carbone et scinde la molécule en deux composés oxygénés.`,
    choiceExplanations: [
      `L'hydrolyse régénère l'acide.`,
      `Il est protoné dans le bilan.`,
      `Les carbones sont répartis entre deux produits sans être perdus.`,
      `Aucun $\\mathrm{CO_2}$ n'est éliminé.`,
    ],
  },
  {
    order: 40,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour obtenir l'acide butanoïque sans changer le nombre de carbones, quelles voies sont cohérentes ?`,
    choices: [
      `Oxydation du butan-1-ol.`,
      `Hydrolyse d'un ester de l'acide butanoïque.`,
      `Oxydation du butan-2-ol.`,
      `Hydrolyse de l'éthanoate de méthyle.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La structure du précurseur doit déjà contenir le squelette carboné de l'acide visé, sauf dans la carboxylation par $\\mathrm{CO_2}$.`,
    choiceExplanations: [
      `Le squelette à quatre carbones est conservé.`,
      `Le fragment butanoyle régénère l'acide.`,
      `Elle donne une cétone, la butan-2-one.`,
      `Cette voie donne l'acide éthanoïque.`,
    ],
  },
  {
    order: 41,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'hydrolyse complète d'un nitrile suit le bilan :`,
    choices: [
      `Nitrile $\\rightarrow$ amide $\\rightarrow$ acide.`,
      `Nitrile $\\rightarrow$ alcène $\\rightarrow$ alcool.`,
      `Nitrile $\\rightarrow$ chlorure d'acyle uniquement.`,
      `Nitrile $\\rightarrow$ cétone obligatoirement.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le carbone du groupe $\\mathrm{C\\equiv N}$ devient le carbone du groupe carboxyle.`,
    choiceExplanations: [
      `L'amide est l'intermédiaire fonctionnel.`,
      `Cette séquence ne correspond pas à l'hydrolyse.`,
      `Aucun chlore n'est introduit.`,
      `Le produit final est un acide carboxylique.`,
    ],
  },
  {
    order: 42,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la transformation d'un nitrile en acide :`,
    choices: [
      `Le carbone du groupe cyano est conservé.`,
      `Un amide peut apparaître comme intermédiaire.`,
      `Le groupe cyano est éliminé sous forme de $\\mathrm{CO_2}$.`,
      `Le nombre de carbones diminue systématiquement d'une unité.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La voie nitrile est utile car elle permet de convertir un groupe $\\mathrm{-C\\equiv N}$ en $\\mathrm{-COOH}$.`,
    choiceExplanations: [
      `Il devient le carbone carbonylé de l'acide.`,
      `C'est le premier produit d'hydrolyse.`,
      `Il est transformé, pas perdu.`,
      `Il reste inchangé.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'hydrolyse du propanenitrile $\\mathrm{CH_3CH_2CN}$ conduit finalement :`,
    choices: [
      `�' l'acide propanoïque.`,
      `�' un acide possédant trois carbones.`,
      `�' l'acide éthanoïque.`,
      `�' la propanone.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le piège classique consiste à ne pas compter le carbone du groupe nitrile dans la chaîne finale.`,
    choiceExplanations: [
      `Le carbone du nitrile compte dans les trois carbones.`,
      `Aucun carbone n'est perdu.`,
      `Ce serait oublier le carbone du groupe cyano.`,
      `Le produit est carboxylique.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'intermédiaire formé lors de l'hydrolyse partielle de $\\mathrm{R{-}C\\equiv N}$ :`,
    choices: [
      `Peut être $\\mathrm{RCONH_2}$.`,
      `Contient encore le même nombre de carbones.`,
      `Est nécessairement un ester.`,
      `Ne contient plus d'azote.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'hydrolyse complète nécessite une seconde étape pour convertir l'amide en acide.`,
    choiceExplanations: [
      `C'est l'amide correspondant.`,
      `Le carbone nitrile devient carbonylé.`,
      `Le premier produit est un amide.`,
      `L'amide contient encore l'azote.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `�' propos d'un organomagnésien $\\mathrm{R{-}MgX}$ réagissant avec $\\mathrm{CO_2}$ :`,
    choices: [
      `Le fragment $\\mathrm{R}$ se comporte comme nucléophile.`,
      `Le bilan conduit à un acide carboxylique après traitement approprié.`,
      `Le $\\mathrm{CO_2}$ retire un carbone au squelette.`,
      `Le produit final est toujours un alcool tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La carboxylation des organomagnésiens est une méthode d'allongement de chaîne d'un carbone.`,
    choiceExplanations: [
      `Le carbone lié au magnésium attaque le carbone électrophile de $\\mathrm{CO_2}$.`,
      `La carboxylation forme $\\mathrm{RCOOH}$.`,
      `Il apporte au contraire un carbone.`,
      `Avec $\\mathrm{CO_2}$, le produit est un acide.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour préparer l'acide propanoïque par carboxylation, l'organomagnésien doit contenir :`,
    choices: [
      `Deux carbones dans son fragment organique.`,
      `Un carbone de moins que l'acide final.`,
      `Trois carbones, car le $\\mathrm{CO_2}$ ne compte pas.`,
      `Aucun carbone.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le bromure d'éthylmagnésium est un précurseur cohérent de l'acide propanoïque.`,
    choiceExplanations: [
      `Le $\\mathrm{CO_2}$ apporte le troisième carbone.`,
      `C'est la règle donnée dans la fiche.`,
      `Le carbone du $\\mathrm{CO_2}$ devient le carboxyle.`,
      `Le radical $\\mathrm{R}$ constitue le reste de la chaîne.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le bilan global $\\mathrm{R{-}MgX + CO_2 \\rightarrow R{-}COOH}$ montre :`,
    choices: [
      `La formation d'une nouvelle liaison carbone''�carbone.`,
      `Une augmentation d'un carbone du squelette organique.`,
      `Une décarboxylation.`,
      `La disparition du groupe $\\mathrm{R}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Cette réaction est un exemple de construction de squelette carboné par un nucléophile organomagnésien.`,
    choiceExplanations: [
      `Le carbone de $\\mathrm{R}$ se lie au carbone du $\\mathrm{CO_2}$.`,
      `Le carbone carboxylique est nouveau.`,
      `C'est la réaction inverse sur le plan du bilan carbone.`,
      `Il est conservé dans le produit.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On souhaite obtenir l'acide butanoïque à partir d'un organomagnésien. Le fragment $\\mathrm{R}$ approprié :`,
    choices: [
      `Est un groupe propyle.`,
      `Doit contenir trois carbones.`,
      `Est un groupe butyle.`,
      `Est un groupe méthyle.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le choix du radical permet de programmer exactement la longueur de la chaîne finale.`,
    choiceExplanations: [
      `Trois carbones plus celui du $\\mathrm{CO_2}$ donnent quatre.`,
      `Il en faut un de moins que le produit.`,
      `Il conduirait à un acide à cinq carbones.`,
      `Il conduirait à l'acide éthanoïque.`,
    ],
  },
  {
    order: 49,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Comparer hydrolyse d'un nitrile et carboxylation d'un organomagnésien :`,
    choices: [
      `Les deux voies peuvent conduire à un acide carboxylique.`,
      `L'hydrolyse conserve le nombre de carbones déjà présent dans le nitrile.`,
      `La carboxylation ajoute le carbone du $\\mathrm{CO_2}$.`,
      `Les deux voies éliminent obligatoirement $\\mathrm{CO_2}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le comptage des carbones est le principal outil pour choisir entre ces voies de synthèse.`,
    choiceExplanations: [
      `C'est leur point commun.`,
      `Le carbone cyano est déjà dans le substrat.`,
      `Le squelette est allongé d'une unité.`,
      `Aucune ne correspond à une décarboxylation.`,
    ],
  },
  {
    order: 50,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un étudiant propose d'obtenir l'acide éthanoïque à partir du bromure de méthylmagnésium et de $\\mathrm{CO_2}$. Son raisonnement :`,
    choices: [
      `Est cohérent avec le bilan du cours.`,
      `Implique la création d'une liaison $\\mathrm{C{-}C}$.`,
      `Devrait conduire à l'acide méthanoïque.`,
      `Est une hydrolyse d'ester.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La réaction fournit une voie directe vers un acide possédant un carbone de plus que l'organomagnésien.`,
    choiceExplanations: [
      `Un carbone du méthyle plus celui du $\\mathrm{CO_2}$ donnent deux carbones.`,
      `Le méthyle se lie au carbone du dioxyde de carbone.`,
      `Il y aurait alors perte du carbone du méthyle.`,
      `C'est une carboxylation d'organomagnésien.`,
    ],
  },
  {
    order: 51,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On hydrolyse un amide $\\mathrm{RCONHCH_3}$. Les produits attendus comprennent :`,
    choices: [
      `Un acide $\\mathrm{RCOOH}$.`,
      `Une espèce dérivée de la méthylamine.`,
      `Un alcane $\\mathrm{RH}$ comme seul produit.`,
      `Un chlorure d'acyle.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'hydrolyse rompt la liaison acyle''�azote sans perdre le squelette carboné de l'acide.`,
    choiceExplanations: [
      `Le fragment acyle devient acide.`,
      `Le fragment azoté est libéré.`,
      `Le carbonyle n'est pas supprimé.`,
      `Aucun réactif chlorant n'est présent.`,
    ],
  },
  {
    order: 52,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une voie de préparation de l'acide éthanoïque peut partir :`,
    choices: [
      `De l'éthanol par oxydation poussée.`,
      `D'un ester acétique par hydrolyse.`,
      `De l'acétonitrile par hydrolyse complète.`,
      `Du propylmagnésium et $\\mathrm{CO_2}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Plusieurs familles de précurseurs peuvent converger vers le même acide si le comptage des carbones est correct.`,
    choiceExplanations: [
      `L'alcool primaire conserve ses deux carbones.`,
      `Le fragment acétyle régénère l'acide.`,
      `Le carbone du nitrile devient carboxylique.`,
      `Cette voie donnerait un acide à quatre carbones.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour préparer un acide à cinq carbones par $\\mathrm{RMgX + CO_2}$ :`,
    choices: [
      `$\\mathrm{R}$ doit contenir quatre carbones.`,
      `Le carbone du carboxyle provient du $\\mathrm{CO_2}$.`,
      `$\\mathrm{R}$ doit déjà contenir cinq carbones.`,
      `La réaction retire un carbone de $\\mathrm{R}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La règle « un carbone de moins » doit être appliquée avant de choisir le réactif de Grignard.`,
    choiceExplanations: [
      `Le $\\mathrm{CO_2}$ apporte le cinquième.`,
      `Il devient le centre carbonylé.`,
      `Le produit en aurait alors six.`,
      `Le radical est conservé.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L'hydrolyse d'un nitrile à quatre carbones :`,
    choices: [
      `Conduit à un acide à quatre carbones.`,
      `Passe par un amide à quatre carbones.`,
      `Conduit nécessairement à un acide à cinq carbones.`,
      `Est une réaction de décarboxylation.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Il faut opposer cette conservation du squelette à l'allongement observé avec $\\mathrm{CO_2}$.`,
    choiceExplanations: [
      `Le carbone nitrile est déjà compté.`,
      `L'hydrolyse partielle conserve le squelette.`,
      `Aucun carbone extérieur n'est ajouté.`,
      `Aucun carbone n'est éliminé.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une synthèse doit transformer $\\mathrm{CH_3CH_2CN}$ en $\\mathrm{CH_3CH_2COOH}$. Quelles propositions sont exactes ?`,
    choices: [
      `Il s'agit d'une hydrolyse de nitrile.`,
      `Un amide peut être observé comme intermédiaire.`,
      `Le produit contient un carbone de plus que le nitrile initial.`,
      `Le produit est l'acide propanoïque.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le comptage doit inclure le carbone du groupe $\\mathrm{C\\equiv N}$ dès le départ.`,
    choiceExplanations: [
      `Le groupe cyano devient carboxyle.`,
      `La première hydrolyse donne $\\mathrm{CH_3CH_2CONH_2}$.`,
      `Le carbone du nitrile était déjà présent.`,
      `La chaîne finale compte trois carbones.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un laboratoire dispose de bromure d'éthylmagnésium. Après réaction avec $\\mathrm{CO_2}$, le produit acide :`,
    choices: [
      `Possède trois carbones.`,
      `Est l'acide propanoïque.`,
      `Est l'acide éthanoïque.`,
      `Est formé par perte de $\\mathrm{CO_2}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La réaction illustre l'allongement de chaîne d'une unité par carboxylation.`,
    choiceExplanations: [
      `Deux proviennent de l'éthyle et un du $\\mathrm{CO_2}$.`,
      `C'est l'acide linéaire à trois carbones.`,
      `Ce produit aurait un carbone de moins.`,
      `Le dioxyde de carbone est incorporé.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les associations précurseur '�� acide, lesquelles sont cohérentes ?`,
    choices: [
      `Butan-1-ol '�� acide butanoïque.`,
      `Propanenitrile '�� acide propanoïque.`,
      `Méthylmagnésium + $\\mathrm{CO_2}$ '�� acide éthanoïque.`,
      `Propan-2-ol '�� acide propanoïque sans rupture de chaîne.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Chaque association doit respecter à la fois la classe fonctionnelle et le nombre de carbones.`,
    choiceExplanations: [
      `Oxydation d'un alcool primaire.`,
      `Hydrolyse complète du nitrile.`,
      `Le produit gagne un carbone.`,
      `Son oxydation donne une cétone.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour choisir une voie de préparation d'un acide, il faut notamment vérifier :`,
    choices: [
      `La classe primaire ou secondaire de l'alcool de départ.`,
      `Le nombre de carbones du nitrile.`,
      `Le carbone ajouté par le $\\mathrm{CO_2}$ dans une carboxylation.`,
      `Que toute hydrolyse diminue toujours le nombre de carbones.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le raisonnement repose sur la conservation ou l'ajout contrôlé du squelette carboné.`,
    choiceExplanations: [
      `Seul l'alcool primaire mène directement à l'acide par oxydation usuelle.`,
      `Il est conservé lors de l'hydrolyse.`,
      `Il devient le carbone carboxylique.`,
      `Elle répartit ou transforme les fragments sans perte systématique.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On veut préparer l'acide butanoïque à partir d'un composé à trois carbones. Quelle stratégie convient ?`,
    choices: [
      `Utiliser un organomagnésien propyle et $\\mathrm{CO_2}$.`,
      `Hydrolyser le propanenitrile.`,
      `Oxyder le propan-1-ol.`,
      `Décarboxyler un acide à trois carbones.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Seule la carboxylation réalise ici l'allongement nécessaire d'une unité.`,
    choiceExplanations: [
      `Le dioxyde de carbone apporte le quatrième carbone.`,
      `Cette voie conserve trois carbones.`,
      `Cette voie donne l'acide propanoïque.`,
      `La décarboxylation réduirait encore la chaîne.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse et réactivité des acides :`,
    choices: [
      `L'oxydation d'un alcool primaire peut créer la fonction acide sans modifier le nombre de carbones.`,
      `L'hydrolyse d'un nitrile conserve son carbone cyano dans l'acide.`,
      `La carboxylation d'un organomagnésien ajoute le carbone du $\\mathrm{CO_2}$.`,
      `Toutes ces voies sont des décarboxylations.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois grandes stratégies se distinguent par leur effet sur le squelette carboné.`,
    choiceExplanations: [
      `Le carbone fonctionnel est oxydé sur place.`,
      `Il devient le carbone du carboxyle.`,
      `Une nouvelle liaison carbone''�carbone est formée.`,
      `Aucune ne libère $\\mathrm{CO_2}$.`,
    ],
  },
];
