/** Cartographie éditoriale V2 — auteur */

export const UE14_BIOCH_CH11_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-besoins-utilisations-aa",
    "title": "Besoins et utilisations métaboliques des acides aminés",
    "description": "Groupes d’acides aminés indispensables, besoins pendant la croissance, interconversions et rôles métaboliques.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-metabolisme-aa",
    "title": "Besoins et utilisations métaboliques des acides aminés",
    "description": "Applications sur uréogenèse, transamination et devenirs énergétiques des acides aminés.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-precurseurs-biologiques-aa",
    "title": "Précurseurs biologiques et formation des peptides",
    "description": "Tyrosine, tryptophane, glutamate, glycine, créatine et premières notions de peptides.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-formation-peptides-insuline-pomc",
    "title": "Précurseurs biologiques et formation des peptides",
    "description": "Applications sur insuline, peptide C, POMC et maturation peptidique.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-peptides-therapeutiques-hormones",
    "title": "Peptides thérapeutiques et hormones peptidiques",
    "description": "Insuline, POMC, glutathion, peptides thérapeutiques et glucagon.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-hormones-peptides-cliniques",
    "title": "Peptides thérapeutiques et hormones peptidiques",
    "description": "Applications sur peptides pancréatiques, natriurétiques et marqueurs cliniques.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-facteurs-cytokines-neuromediateurs",
    "title": "Facteurs de croissance, cytokines, neuromédiateurs et amyloïde",
    "description": "Repères sur facteurs de croissance, cytokines, interférons, chimiokines et peptides opioïdes.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-inflammation-opioides-amyloide",
    "title": "Facteurs de croissance, cytokines, neuromédiateurs et amyloïde",
    "description": "Applications sur inflammation, BNP/NT-proBNP, opioïdes et APP/amyloïde.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-signalisation-peptides-pathologies",
    "title": "Signalisation peptidique et applications cliniques",
    "description": "Maîtrise transversale des hormones, cytokines, biomarqueurs et peptides pathologiques.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-roles-aa-peptides",
    "title": "Synthèse du chapitre",
    "description": "Consolidation des rôles biologiques des acides aminés et peptides.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-roles-biologiques-acides-amines-peptides",
    "title": "Synthèse du chapitre",
    "description": "Maîtrise du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH11_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["un groupe de huit acides aminés indispensables"],
  2: ["un groupe de huit acides aminés indispensables"],
  3: ["les besoins en histidine et en arginine pendant la croissance"],
  4: ["les besoins en arginine pendant la croissance"],
  5: ["les réactions d’interconversion des acides aminés"],
  6: ["les réactions d’interconversion des acides aminés"],
  7: ["le rôle structural des acides aminés"],
  8: ["le rôle structural des acides aminés"],
  9: ["le cycle de l’uréogenèse"],
  10: ["le cycle de l’uréogenèse"],
  11: ["la méthionine comme donneur de méthyle"],
  12: ["la méthionine comme donneur de méthyle"],
  13: ["la transamination Asp–2-oxoglutarate"],
  14: ["la transamination Asp–2-oxoglutarate"],
  15: ["les acides aminés en excès"],
  16: ["les acides aminés en excès"],
  17: ["les acides aminés glucoformateurs"],
  18: ["les acides aminés glucoformateurs"],
  19: ["les acides aminés cétoformateurs"],
  20: ["les acides aminés cétoformateurs"],
  21: ["la place de l’alimentation dans les besoins en acides aminés"],
  22: ["la place de l’alimentation dans les besoins en acides aminés"],
  23: ["la tyrosine comme précurseur"],
  24: ["la tyrosine comme précurseur"],
  25: ["le tryptophane comme précurseur"],
  26: ["le tryptophane comme précurseur"],
  27: ["l’acide glutamique dans le système nerveux"],
  28: ["l’acide glutamique dans le système nerveux"],
  29: ["la glycine et l’hème"],
  30: ["la glycine et l’hème"],
  31: ["la glycine et les acides biliaires"],
  32: ["la glycine et les acides biliaires"],
  33: ["les précurseurs des bases azotées"],
  34: ["les précurseurs des bases azotées"],
  35: ["la créatine"],
  36: ["la créatine"],
  37: ["la définition d’un peptide"],
  38: ["la définition d’un peptide"],
  39: ["le seuil conventionnel entre peptide et protéine"],
  40: ["le seuil conventionnel entre peptide et protéine"],
  41: ["la formation de l’insuline"],
  42: ["la formation de l’insuline"],
  43: ["le peptide C"],
  44: ["le peptide C"],
  45: ["l’insuline mature"],
  46: ["l’insuline mature"],
  47: ["les cellules productrices d’insuline"],
  48: ["les cellules productrices d’insuline"],
  49: ["la pro-opiomélanocortine"],
  50: ["la pro-opiomélanocortine"],
  51: ["la synthèse non ribosomale de petits peptides"],
  52: ["la synthèse non ribosomale de petits peptides"],
  53: ["le glutathion"],
  54: ["le glutathion"],
  55: ["la liaison particulière du glutathion"],
  56: ["la liaison particulière du glutathion"],
  57: ["la maturation de la proinsuline et le peptide C"],
  58: ["les peptides antibiotiques et les acides aminés D"],
  59: ["la cyclosporine"],
  60: ["la cyclosporine"],
  61: ["l’aspartame"],
  62: ["l’aspartame"],
  63: ["le glucagon"],
  64: ["le glucagon"],
  65: ["les peptides natriurétiques"],
  66: ["les peptides natriurétiques"],
  67: ["l’ANP et le BNP"],
  68: ["l’ANP et le BNP"],
  69: ["les effets des peptides natriurétiques"],
  70: ["les effets des peptides natriurétiques"],
  71: ["le BNP et le NT-proBNP en biologie clinique"],
  72: ["le BNP et le NT-proBNP en biologie clinique"],
  73: ["les facteurs de croissance"],
  74: ["les facteurs de croissance"],
  75: ["les cytokines"],
  76: ["les cytokines"],
  77: ["les interleukines"],
  78: ["les interleukines"],
  79: ["les interférons de type I"],
  80: ["les interférons de type I"],
  81: ["l’interféron γ"],
  82: ["l’interféron γ"],
  83: ["les chimiokines"],
  84: ["les chimiokines"],
  85: ["les endorphines et encéphalines"],
  86: ["les endorphines et encéphalines"],
  87: ["le peptide β-amyloïde et la maladie d’Alzheimer"],
  88: ["le peptide β-amyloïde et la maladie d’Alzheimer"],
  89: ["l’intégration des signaux peptidiques en clinique"],
  90: ["l’intégration des signaux peptidiques en clinique"],
  91: ["l’opposition insuline–glucagon"],
  92: ["l’opposition insuline–glucagon"],
  93: ["les précurseurs polypeptidiques"],
  94: ["les précurseurs polypeptidiques"],
  95: ["l’inflammation et les cytokines"],
  96: ["l’inflammation et les cytokines"],
  97: ["la signalisation cardiaque par peptides natriurétiques"],
  98: ["la signalisation cardiaque par peptides natriurétiques"],
  99: ["les peptides opioïdes et amyloïdes"],
  100: ["les peptides opioïdes et amyloïdes"],
  101: ["un groupe de huit acides aminés indispensables"],
  102: ["un groupe de huit acides aminés indispensables"],
  103: ["le cycle de l’uréogenèse"],
  104: ["le cycle de l’uréogenèse"],
  105: ["les acides aminés glucoformateurs"],
  106: ["les acides aminés glucoformateurs"],
  107: ["la tyrosine comme précurseur"],
  108: ["la tyrosine comme précurseur"],
  109: ["l’acide glutamique dans le système nerveux"],
  110: ["l’acide glutamique dans le système nerveux"],
  111: ["la formation de l’insuline"],
  112: ["la formation de l’insuline"],
  113: ["l’insuline mature"],
  114: ["l’insuline mature"],
  115: ["la pro-opiomélanocortine"],
  116: ["la pro-opiomélanocortine"],
  117: ["le glucagon"],
  118: ["le glucagon"],
  119: ["le BNP et le NT-proBNP en biologie clinique"],
  120: ["le BNP et le NT-proBNP en biologie clinique"],
  121: ["le peptide β-amyloïde et la maladie d’Alzheimer"],
  122: ["le peptide β-amyloïde et la maladie d’Alzheimer"],
};
