import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_ORDER = 2;

export const SECTION_B_ESTERIFICATION_HEMIACETALS_DISCOVERY_QUIZ_SLUG =
  `section-b-discovery-esterification-hemiacetals`;
export const SECTION_B_OXIDATION_PRACTICE_QUIZ_SLUG =
  `section-b-practice-oxydation-alcools`;
export const SECTION_B_DEHYDRATION_MASTER_QUIZ_SLUG =
  `section-b-master-deshydratation-transformations-alcools`;

export const SECTION_B_ESTERIFICATION_HEMIACETALS_DISCOVERY_QUESTION_ORDERS: number[] = [31, 32, 33, 34, 35, 36, 37, 38, 39, 40];
export const SECTION_B_OXIDATION_PRACTICE_QUESTION_ORDERS: number[] = [41, 42, 43, 44, 45, 46, 47, 48, 49, 50];
export const SECTION_B_DEHYDRATION_MASTER_QUESTION_ORDERS: number[] = [51, 52, 53, 54, 55, 56, 57, 58, 59, 60];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: SECTION_B_ESTERIFICATION_HEMIACETALS_DISCOVERY_QUIZ_SLUG,
    title: `Estérification et formation des hémiacétals`,
    description: `Reconnaître les acides activés, prévoir la formation d'un ester et comprendre la formation d'un hémiacétal à partir d'un alcool et d'un aldéhyde.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_B_ORDER,
    questionOrders: SECTION_B_ESTERIFICATION_HEMIACETALS_DISCOVERY_QUESTION_ORDERS,
  },
  {
    order: 5,
    slug: SECTION_B_OXIDATION_PRACTICE_QUIZ_SLUG,
    title: `Oxydation des alcools`,
    description: `Relier la classe d'un alcool à son produit d'oxydation et distinguer oxydation douce et oxydation forte.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 41 },
      { type: 'QUESTION', questionOrder: 42 },
      { type: 'QUESTION', questionOrder: 43 },
      { type: 'QUESTION', questionOrder: 44 },
      { type: 'QUESTION', questionOrder: 45 },
      { type: 'QUESTION', questionOrder: 46 },
      { type: 'QUESTION', questionOrder: 47 },
      {
        type: 'GROUP',
        title: `Trois alcools soumis à une oxydation`,
        sharedStatement: `On étudie séparément **A**, l'éthanol $\mathrm{CH_3{-}CH_2OH}$ ; **B**, le propan-2-ol $\mathrm{CH_3{-}CH(OH){-}CH_3}$ ; **C**, le 2-méthylpropan-2-ol $\mathrm{(CH_3)_3C{-}OH}$.`,
        questionOrders: [48, 49, 50],
      },
    ],
  },
  {
    order: 6,
    slug: SECTION_B_DEHYDRATION_MASTER_QUIZ_SLUG,
    title: `Déshydratation et choix d’une transformation`,
    description: `Identifier l'élimination d'eau conduisant à un alcène et choisir la transformation adaptée parmi les principales réactions des alcools.`,
    stage: 'MASTER',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 51 },
      { type: 'QUESTION', questionOrder: 52 },
      { type: 'QUESTION', questionOrder: 53 },
      { type: 'QUESTION', questionOrder: 54 },
      { type: 'QUESTION', questionOrder: 55 },
      { type: 'QUESTION', questionOrder: 56 },
      { type: 'QUESTION', questionOrder: 57 },
      {
        type: 'GROUP',
        title: `Trois devenirs du propan-1-ol`,
        sharedStatement: `Le propan-1-ol $\mathrm{CH_3{-}CH_2{-}CH_2OH}$ est utilisé comme substrat dans trois expériences : **I**, réaction avec un chlorure d'acyle ; **II**, oxydation forte ; **III**, déshydratation.`,
        questionOrders: [58, 59, 60],
      },
    ],
  },
];

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'estérification d'un alcool par un acide activé :`,
    choices: [
      `Le produit organique recherché est un ester.`,
      `Le groupe alcool participe à la formation de la liaison ester.`,
      `La transformation conduit nécessairement à une amine.`,
      `Le bilan simplifié peut s'écrire : alcool + acide activé → ester.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Un alcool peut réagir avec un dérivé activé d'acide carboxylique pour former un ester.`,
    choiceExplanations: [
      `C'est le produit fonctionnel attendu.`,
      `L'oxygène de l'alcool est retrouvé dans le motif ester.`,
      `Aucune fonction amine n'est créée par cette réaction.`,
      `Ce bilan correspond à celui indiqué dans la fiche.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les espèces suivantes, lesquelles sont des acides activés cités dans le cours ?`,
    choices: [
      `Un chlorure d'acyle $\mathrm{R{-}COCl}$.`,
      `Un anhydride d'acide $\mathrm{R{-}CO{-}O{-}CO{-}R'}$.`,
      `Un alcane $\mathrm{R{-}H}$.`,
      `Un alcool $\mathrm{R{-}OH}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le cours retient les chlorures d'acyle et les anhydrides d'acide comme dérivés activés utilisés pour l'estérification et l'amidification.`,
    choiceExplanations: [
      `Le chlore lié au groupe acyle caractérise le chlorure d'acyle.`,
      `Deux groupes acyles reliés par un oxygène caractérisent l'anhydride.`,
      `Un alcane n'est pas un dérivé activé d'acide.`,
      `L'alcool est le nucléophile de la réaction, non l'acide activé.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formule générale $\mathrm{R{-}COCl}$ correspond :`,
    choices: [
      `À un chlorure d'acyle.`,
      `À un dérivé activé d'acide carboxylique.`,
      `À un alcool primaire.`,
      `À un dérivé contenant un groupe carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le chlorure d'acyle comporte un groupe carbonyle lié à un atome de chlore et constitue un acide activé.`,
    choiceExplanations: [
      `C'est sa formule générale.`,
      `Il est plus réactif qu'un acide carboxylique non activé dans ce contexte.`,
      `La formule ne contient pas de groupe hydroxyle alcoolique.`,
      `Le motif $\mathrm{C{=}O}$ est bien présent.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant un anhydride d'acide :`,
    choices: [
      `Il possède deux groupes acyles reliés par un oxygène.`,
      `Il peut être utilisé pour transformer un alcool en ester.`,
      `Sa formule générale peut comporter le motif $\mathrm{CO{-}O{-}CO}$.`,
      `Il s'agit nécessairement d'une amine tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Un anhydride d'acide est un dérivé activé contenant le motif $\mathrm{R{-}CO{-}O{-}CO{-}R'}$.`,
    choiceExplanations: [
      `Cette organisation définit la fonction anhydride.`,
      `Il acyle le groupe hydroxyle de l'alcool.`,
      `Ce motif est caractéristique.`,
      `La structure ne contient pas nécessairement d'azote.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `On fait réagir l'éthanol $\mathrm{CH_3CH_2OH}$ avec un chlorure d'acyle $\mathrm{RCOCl}$. À propos du produit :`,
    choices: [
      `Il contient le fragment éthoxy $\mathrm{CH_3CH_2O{-}}$.`,
      `Il possède une fonction ester.`,
      `Il peut s'écrire sous la forme générale $\mathrm{RCOOCH_2CH_3}$.`,
      `Il s'agit d'un alcool tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'oxygène de l'éthanol se lie au groupe acyle pour former l'ester $\mathrm{RCOOCH_2CH_3}$.`,
    choiceExplanations: [
      `Le radical éthyle et l'oxygène de l'alcool sont conservés ensemble.`,
      `Le motif $\mathrm{COO}$ est celui d'un ester.`,
      `Cette écriture correspond au produit attendu.`,
      `Le groupe hydroxyle a été transformé : le produit n'est plus un alcool.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Lors de la synthèse d'un intermédiaire pharmaceutique, un groupe alcool est acylé par un chlorure d'acyle.`,
    choices: [
      `La fonction alcool est convertie en fonction ester.`,
      `Le chlorure d'acyle joue le rôle d'acide activé.`,
      `La réaction forme nécessairement un groupe hydroxyle supplémentaire.`,
      `La transformation relève de l'estérification étudiée dans le cours.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'acylation d'un alcool par un chlorure d'acyle constitue une voie de formation d'un ester.`,
    choiceExplanations: [
      `Le motif $\mathrm{R{-}OH}$ devient un motif ester.`,
      `Il apporte le groupe acyle réactif.`,
      `Le groupe hydroxyle initial est consommé.`,
      `C'est précisément l'une des réactions présentées.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la formation d'un hémiacétal :`,
    choices: [
      `Elle met en jeu un alcool et un aldéhyde.`,
      `Le carbone initialement carbonylé porte ensuite un groupe $\mathrm{-OH}$ et un groupe $\mathrm{-OR}$.`,
      `Elle produit nécessairement un alcène.`,
      `Le bilan simplifié est : alcool + aldéhyde → hémiacétal.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'addition d'un alcool sur un aldéhyde conduit à un carbone portant simultanément un groupe hydroxyle et un groupe alkoxy.`,
    choiceExplanations: [
      `Ce sont les deux familles de réactifs indiquées.`,
      `Cette double substitution oxygénée caractérise l'hémiacétal.`,
      `Aucune double liaison carbone-carbone n'est créée.`,
      `Ce bilan reprend celui de la fiche.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un hémiacétal, le même atome de carbone est lié :`,
    choices: [
      `À un groupe hydroxyle $\mathrm{-OH}$.`,
      `À un groupe alkoxy $\mathrm{-OR}$.`,
      `Nécessairement à deux atomes d'halogène.`,
      `À des substituants provenant du composé carbonylé initial.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le carbone hémiacétalique porte un groupe $\mathrm{-OH}$, un groupe $\mathrm{-OR}$ et les substituants issus de l'aldéhyde.`,
    choiceExplanations: [
      `C'est l'un des deux groupes oxygénés caractéristiques.`,
      `Le groupe alcool ajouté devient le groupe alkoxy.`,
      `Les halogènes ne définissent pas un hémiacétal.`,
      `Le squelette du composé carbonylé est conservé.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La cyclisation de nombreux sucres est citée comme exemple de formation d'hémiacétal. Dans ce contexte :`,
    choices: [
      `Un groupe alcool de la molécule peut réagir avec un groupe aldéhyde de la même molécule.`,
      `La réaction peut conduire à une structure cyclique.`,
      `La forme hémiacétalique est fréquente en biochimie.`,
      `La cyclisation impose la disparition de tous les atomes d'oxygène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une réaction intramoléculaire entre un alcool et un aldéhyde permet la fermeture du cycle et la formation d'un hémiacétal.`,
    choiceExplanations: [
      `Les deux fonctions peuvent appartenir au même sucre.`,
      `La nouvelle liaison ferme le cycle.`,
      `C'est l'exemple explicitement mentionné dans la fiche.`,
      `Les oxygènes participent au contraire à la structure du produit.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des réactions d'un alcool avec un composé carbonylé ou un acide activé :`,
    choices: [
      `Avec un acide activé, l'alcool peut donner un ester.`,
      `Avec un aldéhyde, l'alcool peut donner un hémiacétal.`,
      `Un chlorure d'acyle est un acide activé.`,
      `Toutes les propositions précédentes sont exactes.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les trois premières propositions résument les voies étudiées ; l'item récapitulatif est donc également exact.`,
    choiceExplanations: [
      `C'est le bilan de l'estérification.`,
      `C'est le bilan de la formation d'un hémiacétal.`,
      `Sa formule générale est $\mathrm{RCOCl}$.`,
      `Les trois affirmations précédentes sont justes.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'oxydation douce d'un alcool primaire :`,
    choices: [
      `Conduit à un aldéhyde.`,
      `Conserve le nombre d'atomes de carbone.`,
      `Conduit directement à une cétone.`,
      `Transforme le motif $\mathrm{-CH_2OH}$ en motif $\mathrm{-CHO}$.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Une oxydation ménagée d'un alcool primaire s'arrête au stade aldéhyde.`,
    choiceExplanations: [
      `C'est le produit caractéristique.`,
      `Le squelette carboné n'est pas fragmenté dans le bilan du cours.`,
      `Une cétone provient de l'oxydation d'un alcool secondaire.`,
      `Cette conversion décrit l'évolution du carbone fonctionnel.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'oxydation forte d'un alcool primaire :`,
    choices: [
      `Peut conduire à un acide carboxylique.`,
      `Passe par le niveau d'oxydation de l'aldéhyde.`,
      `Produit nécessairement un alcool secondaire.`,
      `Transforme finalement le carbone fonctionnel en carbone carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `En conditions fortes, l'alcool primaire est oxydé au-delà de l'aldéhyde jusqu'à l'acide carboxylique.`,
    choiceExplanations: [
      `C'est le produit final présenté.`,
      `L'aldéhyde constitue l'intermédiaire d'oxydation.`,
      `La classe alcool ne devient pas secondaire : la fonction change.`,
      `Le motif final est $\mathrm{-COOH}$.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'oxydation d'un alcool secondaire :`,
    choices: [
      `Conduit à une cétone.`,
      `Transforme le carbone portant $\mathrm{-OH}$ en carbone carbonylé.`,
      `Conserve les deux groupes carbonés liés à ce carbone.`,
      `Conduit toujours à un acide carboxylique sans rupture de chaîne.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le carbone fonctionnel d'un alcool secondaire porte deux substituants carbonés ; après oxydation, il devient le carbone d'une cétone.`,
    choiceExplanations: [
      `C'est le produit attendu.`,
      `Le motif $\mathrm{C{-}OH}$ devient $\mathrm{C{=}O}$.`,
      `Ils restent attachés au carbone carbonylé.`,
      `Le produit direct du cours est une cétone.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans les conditions d'oxydation présentées dans la fiche, un alcool tertiaire :`,
    choices: [
      `Est considéré comme insensible à l'oxydation.`,
      `Ne possède pas d'hydrogène sur le carbone portant $\mathrm{-OH}$.`,
      `Donne directement un aldéhyde.`,
      `Ne suit pas les mêmes transformations simples que les alcools primaires et secondaires.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le carbone fonctionnel d'un alcool tertiaire est lié à trois carbones et ne porte aucun hydrogène ; la fiche indique qu'il ne s'oxyde pas dans ces conditions.`,
    choiceExplanations: [
      `C'est la conclusion du cours.`,
      `Ses quatre liaisons impliquent trois carbones et l'oxygène.`,
      `Un aldéhyde provient d'un alcool primaire.`,
      `L'absence d'hydrogène fonctionnel bloque le schéma simple étudié.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'éthanol peut subir une oxydation douce en éthanal. À propos de cette transformation :`,
    choices: [
      `L'éthanol est un alcool primaire.`,
      `L'éthanal est un aldéhyde.`,
      `Le nombre de carbones reste égal à deux.`,
      `Le produit est la propanone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le motif terminal $\mathrm{-CH_2OH}$ de l'éthanol devient le motif aldéhyde $\mathrm{-CHO}$.`,
    choiceExplanations: [
      `Le carbone fonctionnel est lié à un seul carbone.`,
      `Son groupe caractéristique est $\mathrm{-CHO}$.`,
      `Aucun carbone n'est ajouté ni retiré.`,
      `La propanone contient trois carbones et est une cétone.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors d'une oxydation forte de l'éthanol :`,
    choices: [
      `L'acide éthanoïque peut être obtenu.`,
      `L'éthanal peut constituer un intermédiaire.`,
      `Le produit final possède une fonction acide carboxylique.`,
      `Le produit final est nécessairement un alcool tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'alcool primaire est d'abord oxydé en aldéhyde puis en acide carboxylique lorsque l'oxydation est poussée.`,
    choiceExplanations: [
      `C'est l'acide à deux carbones correspondant.`,
      `Il représente le stade d'oxydation intermédiaire.`,
      `Le motif final est $\mathrm{-COOH}$.`,
      `La fonction alcool disparaît au cours de l'oxydation.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le propan-2-ol est oxydé en propanone. On peut en déduire que :`,
    choices: [
      `Le propan-2-ol est un alcool secondaire.`,
      `La propanone est une cétone.`,
      `Le carbone fonctionnel reste lié à deux groupes méthyle.`,
      `La transformation donne un aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le carbone central du propan-2-ol devient le carbone carbonylé de la propanone tout en conservant ses deux substituants méthyle.`,
    choiceExplanations: [
      `Il est lié à deux carbones.`,
      `Son carbonyle est lié à deux groupes carbonés.`,
      `Le squelette est conservé.`,
      `L'oxydation d'un alcool secondaire produit une cétone.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'oxydation du composé **A** :`,
    choices: [
      `Une oxydation douce peut donner l'éthanal.`,
      `Une oxydation forte peut donner l'acide éthanoïque.`,
      `Le composé A est un alcool primaire.`,
      `Une oxydation simple donne nécessairement la propanone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'éthanol est primaire : il donne l'éthanal en oxydation douce et l'acide éthanoïque en oxydation forte.`,
    choiceExplanations: [
      `Le stade aldéhyde est accessible.`,
      `L'oxydation poussée mène à l'acide carboxylique.`,
      `Le carbone portant $\mathrm{-OH}$ n'a qu'un voisin carboné.`,
      `La propanone provient du propan-2-ol.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'oxydation du composé **B** :`,
    choices: [
      `Le produit attendu est la propanone.`,
      `Le composé B est un alcool secondaire.`,
      `Le produit possède une fonction cétone.`,
      `Le produit attendu est l'acide propanoïque dans le schéma direct du cours.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le propan-2-ol est secondaire et son oxydation conduit à la propanone.`,
    choiceExplanations: [
      `Le carbone central devient carbonylé.`,
      `Il est lié à deux groupes méthyle.`,
      `La propanone est une cétone.`,
      `Le schéma étudié s'arrête à la cétone.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'oxydation du composé **C** :`,
    choices: [
      `Le composé C est un alcool tertiaire.`,
      `Il est considéré comme insensible à l'oxydation dans les conditions du cours.`,
      `Son carbone fonctionnel ne porte aucun hydrogène.`,
      `Il donne directement le 2-méthylpropanal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le tert-butanol ne possède aucun hydrogène sur le carbone portant $\mathrm{-OH}$ ; aucune oxydation simple n'est retenue dans la fiche.`,
    choiceExplanations: [
      `Le carbone fonctionnel est lié à trois groupes méthyle.`,
      `C'est le comportement indiqué.`,
      `Cette caractéristique le distingue des alcools primaire et secondaire.`,
      `Aucun aldéhyde n'est formé selon ce schéma.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La déshydratation d'un alcool :`,
    choices: [
      `Correspond à une élimination.`,
      `Conduit à un alcène et à de l'eau.`,
      `Crée une double liaison carbone-carbone.`,
      `Ajoute globalement une molécule d'eau à un alcène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La déshydratation élimine les éléments de l'eau sur deux carbones voisins et forme une double liaison.`,
    choiceExplanations: [
      `Une petite molécule est éliminée.`,
      `C'est le bilan du cours.`,
      `La liaison simple devient une double liaison.`,
      `Cette proposition décrit l'hydratation, réaction inverse.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour qu'un alcool forme un alcène par déshydratation selon le schéma du cours :`,
    choices: [
      `Le groupe $\mathrm{-OH}$ est perdu avec un hydrogène porté par un carbone voisin.`,
      `Une liaison $\mathrm{C{=}C}$ apparaît entre les deux carbones concernés.`,
      `Le produit conserve nécessairement le groupe hydroxyle.`,
      `Une molécule d'eau figure parmi les produits.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'élimination combine le groupe hydroxyle et un hydrogène voisin pour former l'eau, tandis que les deux carbones établissent une double liaison.`,
    choiceExplanations: [
      `Ces éléments constituent la molécule d'eau éliminée.`,
      `C'est la conséquence de l'élimination.`,
      `Le groupe hydroxyle est consommé.`,
      `Le bilan inclut bien $\mathrm{H_2O}$.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La déshydratation du propan-2-ol $\mathrm{CH_3{-}CH(OH){-}CH_3}$ peut conduire au propène $\mathrm{CH_3{-}CH{=}CH_2}$.`,
    choices: [
      `Le produit est un alcène.`,
      `Le nombre de carbones est conservé.`,
      `Une molécule d'eau est éliminée.`,
      `La transformation est une hydratation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le propan-2-ol perd les éléments de l'eau et forme la double liaison du propène.`,
    choiceExplanations: [
      `Le propène possède une liaison $\mathrm{C{=}C}$.`,
      `Les trois carbones restent dans le squelette.`,
      `C'est le coproducteur du bilan.`,
      `L'hydratation est le sens opposé.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On compare l'hydratation d'un alcène et la déshydratation d'un alcool.`,
    choices: [
      `Ce sont deux transformations de sens opposés dans le bilan simplifié.`,
      `L'hydratation consomme de l'eau.`,
      `La déshydratation produit de l'eau.`,
      `Les deux transformations conservent toujours simultanément la double liaison et le groupe hydroxyle.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'hydratation ajoute les éléments de l'eau sur une double liaison ; la déshydratation les élimine pour reformer une double liaison.`,
    choiceExplanations: [
      `Les bilans sont inverses.`,
      `L'eau est un réactif de l'hydratation.`,
      `L'eau est un produit de l'élimination.`,
      `La fonction et l'insaturation s'interconvertissent.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un alcool primaire est soumis à trois transformations possibles. Quelle(s) association(s) est(sont) correcte(s) ?`,
    choices: [
      `Oxydation douce → aldéhyde.`,
      `Oxydation forte → acide carboxylique.`,
      `Déshydratation → alcène + eau.`,
      `Estérification par un acide activé → amine tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois premières associations correspondent aux réactions étudiées ; l'estérification conduit à un ester.`,
    choiceExplanations: [
      `C'est le premier stade d'oxydation.`,
      `L'oxydation poussée atteint l'acide.`,
      `C'est le bilan de l'élimination.`,
      `Le produit est un ester et non une amine.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une synthèse, on souhaite transformer un groupe alcool en une double liaison carbone-carbone sans modifier le nombre de carbones.`,
    choices: [
      `Une déshydratation est adaptée.`,
      `La transformation est une élimination.`,
      `Une molécule d'eau est formée.`,
      `Une oxydation douce est nécessairement la voie directe recherchée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La déshydratation retire $\mathrm{H}$ et $\mathrm{OH}$ sur deux carbones voisins et crée la double liaison.`,
    choiceExplanations: [
      `Elle remplit l'objectif annoncé.`,
      `Une petite molécule est éliminée.`,
      `Les éléments retirés forment $\mathrm{H_2O}$.`,
      `Une oxydation douce d'un alcool primaire conduit plutôt à un aldéhyde.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos des principales réactions de la section consacrée aux alcools :`,
    choices: [
      `L'estérification modifie le groupe $\mathrm{-OH}$ en motif ester.`,
      `L'oxydation peut créer un groupe carbonyle.`,
      `La déshydratation peut créer une liaison $\mathrm{C{=}C}$.`,
      `La formation d'un hémiacétal implique un aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Chaque proposition correspond à une transformation différente du groupe alcool présentée dans le cours.`,
    choiceExplanations: [
      `L'alcool est acylé.`,
      `Aldéhydes et cétones contiennent un carbonyle.`,
      `L'élimination forme l'alcène.`,
      `L'alcool s'additionne sur le groupe aldéhyde.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'expérience **I** :`,
    choices: [
      `Un ester peut être formé.`,
      `Le chlorure d'acyle est un acide activé.`,
      `Le groupe alcool du propan-1-ol est acylé.`,
      `Le produit principal est nécessairement le propène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réaction d'un alcool avec un chlorure d'acyle correspond à une estérification.`,
    choiceExplanations: [
      `C'est le produit fonctionnel attendu.`,
      `Il appartient aux deux familles d'acides activés citées.`,
      `Le motif $\mathrm{-OH}$ participe à la liaison ester.`,
      `Le propène serait attendu lors d'une déshydratation.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'expérience **II** :`,
    choices: [
      `L'acide propanoïque peut être obtenu.`,
      `Le propan-1-ol est un alcool primaire.`,
      `Une oxydation forte peut dépasser le stade propanal.`,
      `La propanone est le produit final attendu.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une oxydation forte d'un alcool primaire conduit à l'acide carboxylique de même squelette.`,
    choiceExplanations: [
      `Trois carbones sont conservés et la fonction finale est $\mathrm{-COOH}$.`,
      `Le carbone fonctionnel est terminal.`,
      `Le propanal est le stade intermédiaire.`,
      `Une cétone provient d'un alcool secondaire.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'expérience **III** :`,
    choices: [
      `Le propène peut être obtenu.`,
      `Une molécule d'eau est éliminée.`,
      `La transformation crée une double liaison carbone-carbone.`,
      `Le produit reste un alcool primaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La déshydratation du propan-1-ol conduit à l'alcène correspondant et consomme le groupe hydroxyle.`,
    choiceExplanations: [
      `Le squelette à trois carbones donne le propène.`,
      `C'est le petit produit éliminé.`,
      `La liaison double apparaît entre deux carbones voisins.`,
      `La fonction alcool disparaît.`,
    ],
  },
];
