/**
 * UE14 – Biologie cellulaire – Chapitre 7
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SYNTHESIS_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La mitochondrie peut être décrite comme :`,
    choices: [
      `Un organite à double membrane.`,
      `Un compartiment possédant un génome propre mais une autonomie limitée.`,
      `Un site majeur de synthèse d’ATP.`,
      `Un organite présent dans les hématies matures selon la fiche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche exclut les hématies de la présence mitochondriale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 122,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La complémentarité des compartiments mitochondriaux repose sur :`,
    choices: [
      `La membrane externe et ses systèmes d’import.`,
      `La membrane interne et ses complexes respiratoires.`,
      `La matrice et ses enzymes métaboliques.`,
      `Un noyau mitochondrial entourant l’ADNmt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ADNmt se trouve dans la matrice sans enveloppe nucléaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Du glucose à l’ATP, les étapes mobilisent :`,
    choices: [
      `La formation de pyruvate.`,
      `L’acétyl-CoA et le cycle de Krebs.`,
      `NADH/FADH2 et la chaîne respiratoire.`,
      `Le gradient protonique et l’ATP synthase.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Le chapitre met en continuité catabolisme, transfert électronique et phosphorylation oxydative.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 124,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les complexes de la chaîne respiratoire :`,
    choices: [
      `Sont localisés dans la membrane interne.`,
      `Transfèrent les électrons vers l’oxygène.`,
      `Pompent des protons pour I, III et IV.`,
      `Pompent tous exactement le même nombre de protons.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le complexe II ne pompe pas de protons et les quantités indiquées diffèrent selon les complexes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 125,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les systèmes TOM, TIM et SAM illustrent :`,
    choices: [
      `La dépendance de la mitochondrie à l’égard du génome nucléaire.`,
      `L’import de protéines synthétisées dans le cytosol.`,
      `La spécialisation des deux membranes.`,
      `La synthèse des antigènes ABO.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces translocases concernent l’adressage mitochondrial des protéines.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition de la chaîne respiratoire peut entraîner :`,
    choices: [
      `Une diminution du gradient protonique.`,
      `Une diminution de la synthèse d’ATP.`,
      `Une souffrance des tissus à forte demande énergétique.`,
      `Une augmentation garantie du bilan énergétique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le blocage de la respiration compromet la phosphorylation oxydative.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 127,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’ATP synthase :`,
    choices: [
      `Associe F0 et F1.`,
      `Utilise le retour des H+ vers la matrice.`,
      `Peut fonctionner en sens inverse en hydrolysant l’ATP selon la fiche.`,
      `Est identique au complexe IV.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ATP synthase est distincte de la cytochrome oxydase du complexe IV.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 128,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les fonctions non énergétiques directes comprennent :`,
    choices: [
      `La synthèse de prégnénolone en coopération avec le REL.`,
      `La participation à l’apoptose intrinsèque.`,
      `La thermogenèse par UCP.`,
      `La production contrôlée ou accidentelle de radicaux libres.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La mitochondrie participe à de multiples fonctions physiologiques et pathologiques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 129,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les cytopathies mitochondriales peuvent être comprises à partir :`,
    choices: [
      `De la dépendance des muscles et du nerf optique à l’ATP.`,
      `De mutations touchant des protéines mitochondriales.`,
      `De l’autonomie limitée et de la double origine génétique des constituants.`,
      `Du système ABO uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les tissus énergétiquement exigeants sont particulièrement sensibles aux défauts mitochondriaux.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 130,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est la plus fidèle au chapitre ?`,
    choices: [
      `La mitochondrie associe métabolisme, respiration, signalisation de mort et thermogenèse.`,
      `Sa double membrane est indispensable à la force motrice protonique.`,
      `Son fonctionnement dépend de coopérations avec le cytosol, le noyau, le REL et les lysosomes.`,
      `Elle constitue un compartiment totalement indépendant de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitochondrie est intégrée à de nombreuses coopérations cellulaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un patient présente une faiblesse musculaire associée à une baisse de production d’ATP. Une cytopathie mitochondriale est envisagée. Quelle(s) proposition(s) est(sont) cohérente(s) ?`,
    choices: [
      `Le muscle possède des besoins énergétiques élevés.`,
      `Les mitochondries sont normalement disposées près des myofibrilles.`,
      `Un défaut de chaîne respiratoire peut réduire la phosphorylation oxydative.`,
      `Les hématies sont le seul tissu musculaire atteint.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le muscle est un tissu particulièrement sensible aux déficits de production mitochondriale d’ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans le même dossier, une atteinte du complexe I est identifiée. On peut attendre :`,
    choices: [
      `Une perturbation de l’utilisation du NADH.`,
      `Une diminution d’un site de pompage protonique.`,
      `Une diminution du rendement énergétique.`,
      `Un blocage direct et exclusif de l’import par TIM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le complexe I appartient à la chaîne respiratoire, non au système d’import TIM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une exposition au cyanure provoque un effondrement rapide de la respiration cellulaire. Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Le complexe IV est ciblé.`,
      `Le transfert final des électrons à l’oxygène est empêché.`,
      `La formation du gradient protonique et de l’ATP est compromise.`,
      `Le cyanure active l’ATP synthase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cyanure bloque la cytochrome oxydase et interrompt la chaîne respiratoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une exposition à l’oligomycine, dans un autre cas, entraîne :`,
    choices: [
      `Une inhibition de l’ATP synthase.`,
      `Une perturbation du retour des protons par F0.`,
      `Une baisse de la synthèse d’ATP.`,
      `Une activation de TOM et SAM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’oligomycine cible l’ATP synthase et non les complexes d’import protéique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 135,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Chez un nouveau-né, la graisse brune contribue au maintien de la température. Cette thermogenèse repose sur :`,
    choices: [
      `Une abondance de mitochondries.`,
      `La thermogénine ou UCP.`,
      `La dissipation de la force motrice protonique en chaleur.`,
      `Une augmentation maximale du couplage à la synthèse d’ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le mécanisme est un découplage favorisant la chaleur plutôt que la production maximale d’ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 136,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une cellule engagée dans l’apoptose intrinsèque :`,
    choices: [
      `Le potentiel mitochondrial peut chuter.`,
      `Le cytochrome c peut être libéré.`,
      `Un apoptosome et des caspases peuvent être activés.`,
      `La synthèse d’ATP augmente nécessairement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie intrinsèque est associée à une défaillance mitochondriale et à l’activation des caspases.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 137,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une augmentation des radicaux superoxydes produits par les complexes I et III peut :`,
    choices: [
      `Endommager l’ADN, les protéines et les lipides.`,
      `Participer au vieillissement et à des maladies dégénératives.`,
      `Être limitée par la SOD, la glutathion peroxydase et la peroxyrédoxine.`,
      `Améliorer systématiquement le fonctionnement mitochondrial.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les espèces réactives de l’oxygène deviennent délétères lorsqu’elles dépassent les défenses antioxydantes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 138,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour 4 NADH et 4 FADH2, le rendement théorique indiqué est :`,
    choices: [
      `16 ATP.`,
      `10 ATP issus des NADH.`,
      `6 ATP issus des FADH2.`,
      `20 ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le calcul est 4 × 2,5 + 4 × 1,5 = 16 ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les trois figures suivantes résument la structure, la chaîne respiratoire et les autres fonctions de la mitochondrie.

![Structure](/images/training/ue14/biologie-cellulaire/mitochondrie/structure-compartiments-mitochondrie.png)

![Chaîne respiratoire](/images/training/ue14/biologie-cellulaire/mitochondrie/chaine-respiratoire-atp-synthase.png)

![Autres fonctions](/images/training/ue14/biologie-cellulaire/mitochondrie/autres-fonctions-mitochondrie.png)

En croisant les informations, quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `La compartimentation rend possible le gradient protonique.`,
      `La membrane interne porte la chaîne respiratoire et des protéines de découplage.`,
      `La mitochondrie intervient dans la production d’ATP, l’apoptose et la thermogenèse.`,
      `Le génome mitochondrial rend inutile tout import protéique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les figures montrent une mitochondrie compartimentée, multifonctionnelle et dépendante de protéines importées.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle conclusion générale est la plus fidèle au chapitre ?`,
    choices: [
      `La mitochondrie transforme l’énergie des nutriments en ATP grâce à la respiration et au gradient protonique.`,
      `Elle possède un génome propre mais dépend largement du génome nucléaire.`,
      `Elle intervient aussi dans les stéroïdes, l’apoptose, la chaleur et le stress oxydant.`,
      `Elle est un organite simple à membrane unique sans relation avec les pathologies.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitochondrie est un organite complexe à double membrane, central pour l’énergie et de nombreuses autres fonctions cellulaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
];

export const SYNTHESIS_QUIZZES: SeedQuiz[] = [
  {
    order: 13,
    slug: `organisation-respiration-fonctions-mitochondrie`,
    title: `Organisation, respiration et fonctions mitochondriales`,
    description: `Révision transversale de la structure, de la bioénergétique et des autres fonctions.`,
    stage: 'PRACTICE',
    sectionOrder: 5,
    questionOrders: [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
  },
  {
    order: 14,
    slug: `synthese-clinique-experimentale-mitochondrie`,
    title: `Synthèse clinique et expérimentale du chapitre`,
    description: `Situations intégratives sur les cytopathies, les inhibiteurs, la thermogenèse et l’apoptose.`,
    stage: 'MASTER',
    sectionOrder: 5,
    items: [
      {
        type: 'GROUP',
        title: `Cytopathie mitochondriale musculaire`,
        sharedStatement: `Un patient présente une faiblesse musculaire et une diminution de la production d’ATP. Une atteinte du complexe I de la chaîne respiratoire est mise en évidence.`,
        questionOrders: [131, 132],
      },
      {
        type: 'GROUP',
        title: `Intoxications mitochondriales`,
        sharedStatement: `Deux expositions toxiques sont comparées : l’une au cyanure, l’autre à l’oligomycine.`,
        questionOrders: [133, 134],
      },
      {
        type: 'GROUP',
        title: `Destin cellulaire et thermogenèse`,
        sharedStatement: `Une équipe compare une cellule de graisse brune active et une cellule engagée dans la voie intrinsèque d’apoptose.`,
        questionOrders: [135, 136],
      },
      { type: 'QUESTION', questionOrder: 137 },
      { type: 'QUESTION', questionOrder: 138 },
      { type: 'QUESTION', questionOrder: 139 },
      { type: 'QUESTION', questionOrder: 140 },
    ],
  },
];
