/**
 * UE14 – Biologie cellulaire – Chapitre 4
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’endocytose correspond :`,
    choices: [
      `À l’internalisation d’un petit volume de MEC.`,
      `À l’internalisation d’une portion de membrane plasmique.`,
      `À une entrée de matériel dans la cellule.`,
      `À une exportation vers le MEC.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’exportation vers le MEC correspond à l’exocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Endocytose et exocytose sont :`,
    choices: [
      `Continues.`,
      `Équilibrées.`,
      `Dépendantes du SEM et du cytosquelette.`,
      `Indépendantes de l’ATP et du GTP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche mentionne une consommation d’ATP et de GTP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les quatre types d’endocytose cités sont :`,
    choices: [
      `Pinocytose.`,
      `Phagocytose.`,
      `Endocytose via des récepteurs.`,
      `Endocytose par cavéoles.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Ces quatre voies sont explicitement listées.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La pinocytose :`,
    choices: [
      `Correspond à « boire ».`,
      `Internalise un faible volume de milieu extracellulaire.`,
      `Concerne des particules de petite taille, inférieures à 150 nm.`,
      `Est réservée aux macrophages.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Toutes les cellules ingèrent en permanence du liquide par pinocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les étapes de la pinocytose comprennent :`,
    choices: [
      `Piégeage des particules.`,
      `Invagination et pincement de membrane.`,
      `Formation d’une vésicule.`,
      `Équilibrage par exocytose.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La fiche détaille cette séquence en quatre temps.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La phagocytose :`,
    choices: [
      `Correspond à « manger ».`,
      `Concerne de grosses particules ou débris.`,
      `Peut ingérer des cellules entières.`,
      `Est réalisée de façon identique par toutes les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Elle est réalisée par des cellules spécialisées.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les cellules spécialisées dans la phagocytose comprennent :`,
    choices: [
      `Les macrophages.`,
      `Les polynucléaires neutrophiles.`,
      `Tous les entérocytes.`,
      `Les hématies.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La fiche cite macrophages et PNN.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La phagocytose comporte :`,
    choices: [
      `Fixation via des récepteurs CAM.`,
      `Formation d’un phagosome.`,
      `Fusion avec un lysosome.`,
      `Dégradation de la cible.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La séquence mène de l’adhérence à la digestion lysosomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’endocytose médiée par récepteurs :`,
    choices: [
      `Est la plus fréquente.`,
      `Capte spécifiquement des molécules du MEC.`,
      `Peut concentrer les ligands jusqu’à ×1000.`,
      `Ne fait jamais intervenir la clathrine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les puits de clathrine sont au cœur de cette voie.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les ligands cités pour l’endocytose par récepteurs :`,
    choices: [
      `La transferrine.`,
      `Des facteurs de croissance et leurs récepteurs.`,
      `Les LDL.`,
      `Les histones nucléaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche cite transferrine, facteurs de croissance et LDL.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Quatre types d’endocytose](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-1/quatre-types-endocytose.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `La pinocytose concerne de petites particules.`,
      `La phagocytose concerne de grosses particules.`,
      `La voie par récepteurs est spécifique.`,
      `Les cavéoles sont associées à la cavéoline.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La figure compare les quatre grandes voies de la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’exemple du LDL illustre :`,
    choices: [
      `Une capture depuis le sang.`,
      `Une internalisation du cholestérol contenu dans le LDL.`,
      `Une endocytose médiée par récepteurs.`,
      `Une diffusion simple à travers la membrane.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le LDL entre par récepteurs et puits recouverts de clathrine.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Au début de l’endocytose du LDL :`,
    choices: [
      `Le LDL se lie à son récepteur.`,
      `Les complexes se concentrent sur la membrane plasmique.`,
      `Les adaptines participent à l’incurvation.`,
      `Le cholestérol est immédiatement libéré dans le cytosol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La libération du cholestérol survient après le trajet endosomal et lysosomal.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La clathrine :`,
    choices: [
      `S’organise en triskèles.`,
      `Chaque molécule comprend une chaîne lourde et une chaîne légère selon la fiche.`,
      `Forme une cage sphérique.`,
      `Est une enzyme lysosomale acide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La clathrine constitue un revêtement, non une hydrolase lysosomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La dynamine :`,
    choices: [
      `Est une protéine G monomérique.`,
      `Utilise du GTP.`,
      `Participe au détachement du puits.`,
      `Déshabille la vésicule grâce à l’ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le déshabillage est attribué à HSP70 et à l’ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le déshabillage d’une vésicule de clathrine :`,
    choices: [
      `Fait intervenir HSP70.`,
      `Consomme de l’ATP.`,
      `Permet le transport de la vésicule.`,
      `Est assuré par la dynamine et le GTP exclusivement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Dynamine/GTP assurent plutôt la scission ; HSP70/ATP le déshabillage.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans la voie LDL :`,
    choices: [
      `L’endosome précoce est associé à un pH 7,4.`,
      `L’endosome tardif est associé à un pH 6,5.`,
      `La diminution du pH favorise le découplage ligand–récepteur.`,
      `Le pH augmente progressivement jusqu’à 9.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie endosomale s’acidifie.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Après dissociation du LDL et de son récepteur :`,
    choices: [
      `Le récepteur peut être recyclé.`,
      `Le récepteur peut être détruit.`,
      `Le LDL peut être hydrolysé.`,
      `Le cholestérol reste obligatoirement bloqué dans le lysosome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cholestérol peut sortir du lysosome via une perméase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le cholestérol issu du LDL :`,
    choices: [
      `Est libéré après hydrolyse du LDL.`,
      `Sort du lysosome grâce à une perméase.`,
      `Rejoint le cytosol pour être métabolisé.`,
      `Est directement transcrit en ARN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cholestérol est un lipide métabolisé, non transcrit.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’endocytose par cavéoles :`,
    choices: [
      `Utilise un revêtement de cavéoline.`,
      `Peut concerner virus, parasites ou bactéries.`,
      `Peut conduire à des cavéosomes.`,
      `Est identique à la phagocytose de grosses cellules entières.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie caveolaire est distincte de la phagocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule internalise en permanence un peu de liquide et des particules <150 nm. Il s’agit :`,
    choices: [
      `De pinocytose.`,
      `D’une voie présente dans toutes les cellules.`,
      `D’un mécanisme compensé par l’exocytose.`,
      `D’une phagocytose spécialisée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le scénario correspond à la pinocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un macrophage entoure une bactérie, forme un phagosome puis le fusionne avec un lysosome. Ce processus implique :`,
    choices: [
      `Une phagocytose.`,
      `Des récepteurs CAM.`,
      `Une digestion lysosomale.`,
      `Une sécrétion constitutive.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le scénario décrit les étapes de la phagocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut de dynamine pourrait :`,
    choices: [
      `Empêcher le détachement correct du puits.`,
      `Réduire la formation de vésicules recouvertes.`,
      `Perturber l’endocytose du LDL.`,
      `Accélérer automatiquement l’hydrolyse lysosomale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La dynamine intervient avant l’étape lysosomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut de HSP70 pourrait :`,
    choices: [
      `Perturber le déshabillage.`,
      `Maintenir des vésicules recouvertes.`,
      `Gêner le transport vers les endosomes.`,
      `Empêcher la liaison initiale du LDL au récepteur uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `HSP70 agit après la formation de la vésicule.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Endocytose du LDL](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-1/endocytose-ldl-recepteurs.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `La liaison au récepteur précède la formation du puits.`,
      `La dynamine intervient avant le déshabillage.`,
      `L’endosome tardif est plus acide que l’endosome précoce.`,
      `Le cholestérol est libéré avant toute hydrolyse.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La libération du cholestérol survient après hydrolyse lysosomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’acidification endosomale permet notamment :`,
    choices: [
      `Le découplage ligand–récepteur.`,
      `Le tri entre recyclage et dégradation.`,
      `La progression vers des compartiments tardifs.`,
      `La transformation de la clathrine en cholestérol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La clathrine et le cholestérol ont des rôles et natures distincts.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une endocytose très spécifique et concentratrice est cohérente avec :`,
    choices: [
      `Des récepteurs membranaires.`,
      `Des puits recouverts de clathrine.`,
      `Une concentration possible des ligands.`,
      `Une diffusion aléatoire sans reconnaissance.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La spécificité s’oppose à une diffusion aléatoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le recyclage d’un récepteur LDL :`,
    choices: [
      `Économise la synthèse d’un nouveau récepteur.`,
      `Se fait après dissociation du ligand.`,
      `Peut ramener le récepteur à la membrane plasmique.`,
      `Exige que le récepteur soit hydrolysé en cholestérol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le récepteur et le ligand suivent des devenirs distincts.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition de l’acidification endosomale pourrait :`,
    choices: [
      `Retarder la dissociation ligand–récepteur.`,
      `Perturber le recyclage.`,
      `Modifier la maturation endosomale.`,
      `Augmenter nécessairement le pH lysosomal à 14.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours permet d’inférer une perturbation du tri, sans valeur extrême imposée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte sur l’endocytose ?`,
    choices: [
      `Elle peut être non spécifique ou spécifique.`,
      `Elle internalise membrane et matériel extracellulaire.`,
      `Elle mobilise cytosquelette et énergie.`,
      `Elle exclut toujours les lysosomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La phagocytose et la voie LDL aboutissent notamment aux lysosomes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: `types-endocytose`,
    title: `Types d’endocytose`,
    description: `Pinocytose, phagocytose, endocytose par récepteurs et cavéoles.`,
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: `endocytose-ldl`,
    title: `Endocytose du LDL`,
    description: `Puits de clathrine, dynamine, déshabillage et maturation endosomale.`,
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 9,
    slug: `endocytose-et-tri-endosomal`,
    title: `Endocytose et tri endosomal`,
    description: `Applications sur phagocytose, recyclage des récepteurs et acidification.`,
    stage: 'MASTER',
    sectionOrder: 3,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];
