/** UE14 – Biologie cellulaire – Chapitre 9 : Le cycle cellulaire — V2 active */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';
const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'cycle-cellulaire';
const sections: SeedSection[] = [
  { order: 1, title: `Renouvellement, interphase et quantité d’ADN`, description: `Homéostasie, G0, G1, S, G2 et relations entre chromosomes, chromatides et quantité d’ADN.`, kind: 'THEME' },
  { order: 2, title: `Cyclines, CDK et transitions`, description: `Complexes cycline-CDK, Rb-E2F, progression G1/S et activation de CDK1.`, kind: 'THEME' },
  { order: 3, title: `Points de contrôle et dommages de l’ADN`, description: `Point de restriction, p53-p21, p16, Cdc25, Wee1 et contrôle G2/M.`, kind: 'THEME' },
  { order: 4, title: `Mitose, fuseau et sortie de mitose`, description: `Caryodiérèse, fuseau mitotique, kinétochores, SAC, APC/C, séparase et cytodiérèse.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Raisonnement transversal sur la progression, les checkpoints et la ségrégation chromosomique.`, kind: 'SYNTHESIS' },
];
const questions: SeedQuestion[] = [...SECTION_A_QUESTIONS, ...SECTION_B_QUESTIONS, ...SECTION_C_QUESTIONS, ...SECTION_D_QUESTIONS, ...SYNTHESIS_QUESTIONS];
const quizSeeds: SeedQuiz[] = [...SECTION_A_QUIZZES, ...SECTION_B_QUIZZES, ...SECTION_C_QUIZZES, ...SECTION_D_QUIZZES, ...SYNTHESIS_QUIZZES];
const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Renouvellement et phases du cycle`],
  2: [`Renouvellement et phases du cycle`],
  3: [`Renouvellement et phases du cycle`],
  4: [`Renouvellement et phases du cycle`],
  5: [`Renouvellement et phases du cycle`],
  6: [`Renouvellement et phases du cycle`],
  7: [`Renouvellement et phases du cycle`],
  8: [`Renouvellement et phases du cycle`],
  9: [`Renouvellement et phases du cycle`],
  10: [`Renouvellement et phases du cycle`],
  11: [`Renouvellement et phases du cycle`],
  12: [`Renouvellement et phases du cycle`],
  13: [`Renouvellement et phases du cycle`],
  14: [`Renouvellement et phases du cycle`],
  15: [`Renouvellement et phases du cycle`],
  16: [`Renouvellement et phases du cycle`],
  17: [`Renouvellement et phases du cycle`],
  18: [`Renouvellement et phases du cycle`],
  19: [`Renouvellement et phases du cycle`],
  20: [`Renouvellement et phases du cycle`],
  21: [`Renouvellement et phases du cycle`],
  22: [`Renouvellement et phases du cycle`],
  23: [`Cyclines et CDK`],
  24: [`Cyclines et CDK`],
  25: [`Cyclines et CDK`],
  26: [`Cyclines et CDK`],
  27: [`Cyclines et CDK`],
  28: [`Cyclines et CDK`],
  29: [`Cyclines et CDK`],
  30: [`Cyclines et CDK`],
  31: [`Cyclines et CDK`],
  32: [`Cyclines et CDK`],
  33: [`Cyclines et CDK`],
  34: [`Cyclines et CDK`],
  35: [`Cyclines et CDK`],
  36: [`Cyclines et CDK`],
  37: [`Cyclines et CDK`],
  38: [`Cyclines et CDK`],
  39: [`Cyclines et CDK`],
  40: [`Cyclines et CDK`],
  41: [`Cyclines et CDK`],
  42: [`Cyclines et CDK`],
  43: [`Cyclines et CDK`],
  44: [`Cyclines et CDK`],
  45: [`Points de contrôle`],
  46: [`Points de contrôle`],
  47: [`Points de contrôle`],
  48: [`Points de contrôle`],
  49: [`Points de contrôle`],
  50: [`Points de contrôle`],
  51: [`Points de contrôle`],
  52: [`Points de contrôle`],
  53: [`Points de contrôle`],
  54: [`Points de contrôle`],
  55: [`Points de contrôle`],
  56: [`Points de contrôle`],
  57: [`Points de contrôle`],
  58: [`Points de contrôle`],
  59: [`Points de contrôle`],
  60: [`Points de contrôle`],
  61: [`Points de contrôle`],
  62: [`Points de contrôle`],
  63: [`Points de contrôle`],
  64: [`Points de contrôle`],
  65: [`Points de contrôle`],
  66: [`Points de contrôle`],
  67: [`Mitose et fuseau`],
  68: [`Mitose et fuseau`],
  69: [`Mitose et fuseau`],
  70: [`Mitose et fuseau`],
  71: [`Mitose et fuseau`],
  72: [`Mitose et fuseau`],
  73: [`Mitose et fuseau`],
  74: [`Mitose et fuseau`],
  75: [`Mitose et fuseau`],
  76: [`Mitose et fuseau`],
  77: [`Mitose et fuseau`],
  78: [`Mitose et fuseau`],
  79: [`Mitose et fuseau`],
  80: [`Mitose et fuseau`],
  81: [`Mitose et fuseau`],
  82: [`Mitose et fuseau`],
  83: [`Mitose et fuseau`],
  84: [`Mitose et fuseau`],
  85: [`Mitose et fuseau`],
  86: [`Mitose et fuseau`],
  87: [`Mitose et fuseau`],
  88: [`Mitose et fuseau`],
  89: [`Mitose et fuseau`],
  90: [`Mitose et fuseau`],
  91: [`Mitose et fuseau`],
  92: [`Mitose et fuseau`],
  93: [`Mitose et fuseau`],
  94: [`Mitose et fuseau`],
  95: [`Mitose et fuseau`],
  96: [`Mitose et fuseau`],
  97: [`Mitose et fuseau`],
  98: [`Mitose et fuseau`],
  99: [`Mitose et fuseau`],
  100: [`Mitose et fuseau`],
  101: [`Synthèse du cycle cellulaire`],
  102: [`Synthèse du cycle cellulaire`],
  103: [`Synthèse du cycle cellulaire`],
  104: [`Synthèse du cycle cellulaire`],
  105: [`Synthèse du cycle cellulaire`],
  106: [`Synthèse du cycle cellulaire`],
  107: [`Synthèse du cycle cellulaire`],
  108: [`Synthèse du cycle cellulaire`],
  109: [`Synthèse du cycle cellulaire`],
  110: [`Synthèse du cycle cellulaire`],
  111: [`Synthèse du cycle cellulaire`],
  112: [`Synthèse du cycle cellulaire`],
  113: [`Synthèse du cycle cellulaire`],
  114: [`Synthèse du cycle cellulaire`],
  115: [`Synthèse du cycle cellulaire`],
  116: [`Synthèse du cycle cellulaire`],
  117: [`Synthèse du cycle cellulaire`],
  118: [`Synthèse du cycle cellulaire`],
  119: [`Synthèse du cycle cellulaire`],
  120: [`Synthèse du cycle cellulaire`],
  121: [`Synthèse du cycle cellulaire`],
  122: [`Synthèse du cycle cellulaire`],
};
export async function seedHealthTrainingUe14BiologieCellulaireCycleCellulaire(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 9',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
    purgeObsoleteQuestions: true,
  });
}
