/**
 * UE14 – Biologie cellulaire – Chapitre 4
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du système endomembranaire (SEM) :`,
    choices: [
      `Il est présent uniquement chez les eucaryotes.`,
      `Il est constitué de cavités délimitées par une membrane.`,
      `Il comprend les mitochondries.`,
      `Il comprend les peroxysomes.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le SEM est propre aux eucaryotes et exclut mitochondries et peroxysomes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une cavité du SEM comprend :`,
    choices: [
      `Une membrane.`,
      `Une lumière.`,
      `Des protéines transmembranaires possibles.`,
      `Obligatoirement un génome propre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une cavité associe membrane et lumière ; elle peut contenir des protéines membranaires et luminales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les compartiments du SEM :`,
    choices: [
      `Le réticulum endoplasmique.`,
      `L’appareil de Golgi.`,
      `Les endosomes et lysosomes.`,
      `Les mitochondries.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les mitochondries sont explicitement exclues du SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le réticulum endoplasmique peut être :`,
    choices: [
      `Lisse.`,
      `Rugueux ou granuleux lorsqu’il porte des ribosomes.`,
      `En continuité avec l’enveloppe nucléaire.`,
      `Un organite à double membrane avec ADN propre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche distingue REL et RER/REG et rappelle la continuité avec l’enveloppe nucléaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les petites cavités du SEM comprennent notamment :`,
    choices: [
      `Les endosomes.`,
      `Les lysosomes.`,
      `Les cavéoles et canalicules.`,
      `Les peroxysomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les peroxysomes ne font pas partie du SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Quantitativement, le SEM représente environ :`,
    choices: [
      `20 % du volume cellulaire.`,
      `60 % de la surface totale de la cellule.`,
      `60 % du volume cellulaire.`,
      `20 % de la surface totale de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les valeurs retenues dans la fiche sont 20 % du volume et 60 % de la surface.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les vésicules du SEM peuvent transporter :`,
    choices: [
      `Du matériel membranaire.`,
      `Du matériel soluble.`,
      `Des agents pathogènes.`,
      `Uniquement des lipides.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le contenu vésiculaire peut être membranaire, soluble ou pathogène.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les protéines transportées dans les vésicules peuvent porter :`,
    choices: [
      `Des signaux d’adressage.`,
      `Des signaux de rétention.`,
      `Au moins deux signaux différents sur une même protéine.`,
      `Uniquement un signal de dégradation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche insiste sur l’adressage et la rétention, parfois combinés sur une même protéine.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les flux membranaires sont :`,
    choices: [
      `Permanents.`,
      `Responsables d’un système dynamique.`,
      `Au nombre de quatre dans le cours.`,
      `Indépendants de tout compartiment de départ et d’arrivée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les vésicules sont orientées selon leurs compartiments de départ et d’arrivée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Le flux principal ou vectoriel permanent se fait :`,
    choices: [
      `Dans le sens de l’exocytose.`,
      `Dans le sens exclusif de la phagocytose.`,
      `Uniquement du lysosome vers le RE.`,
      `Sans passer par le Golgi.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le flux principal sortant suit le sens de l’exocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le flux principal débute au RE puis passe par :`,
    choices: [
      `L’appareil de Golgi.`,
      `Le carrefour endosomal.`,
      `La membrane plasmique.`,
      `La mitochondrie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le flux principal suit RE → Golgi → carrefour endosomal et/ou membrane plasmique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le second flux, rétrograde et centré sur les endosomes, peut conduire vers :`,
    choices: [
      `L’appareil de Golgi.`,
      `Les lysosomes.`,
      `La membrane plasmique pour recyclage.`,
      `Le noyau par un pore nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ce flux redistribue le matériel endocyté vers Golgi, lysosomes ou membrane recyclée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le troisième flux rétrograde :`,
    choices: [
      `Assure un retour du Golgi vers le RE.`,
      `Peut impliquer des endosomes et cavéosomes.`,
      `Se fait sous forme de canalicules selon la fiche.`,
      `Correspond à une exocytose vers le MEC.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le troisième flux rétrograde va du Golgi vers le RE, notamment via des canalicules.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le quatrième flux rétrograde :`,
    choices: [
      `Transporte directement des cavéosomes vers le RE.`,
      `Peut véhiculer virus, bactéries, toxines ou parasites.`,
      `Est un flux sortant vers le milieu extracellulaire.`,
      `Appartient aux flux orientés vers le RE.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le quatrième flux conduit directement les cavéosomes au RE.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Compartiments et flux du SEM](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-1/sem-compartiments-quatre-flux.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Le flux orange correspond au flux principal sortant.`,
      `Le flux violet est centré sur les endosomes.`,
      `Un retour Golgi → RE est représenté.`,
      `La mitochondrie est représentée comme compartiment central du SEM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure synthétise les quatre flux sans inclure la mitochondrie dans le SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le carrefour endosomal peut comprendre ou communiquer avec :`,
    choices: [
      `Des endosomes.`,
      `Des lysosomes.`,
      `Des grains de sécrétion.`,
      `Un génome mitochondrial.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le carrefour endosomal regroupe les voies vers endosomes, lysosomes et grains de sécrétion.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les échanges du SEM ont lieu :`,
    choices: [
      `Avec le cytosol.`,
      `Avec le milieu extracellulaire.`,
      `Uniquement entre cavités parfaitement isolées.`,
      `Par vésicules ou canalicules.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les compartiments communiquent entre eux et échangent aussi avec cytosol et MEC.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une protéine luminale du SEM :`,
    choices: [
      `Se trouve dans la lumière d’une cavité.`,
      `Est distincte d’une protéine cytosolique.`,
      `Peut être transportée par une vésicule.`,
      `Est nécessairement une protéine transmembranaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les protéines luminales sont solubles dans la lumière et peuvent être transportées.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une protéine transmembranaire transportée par une vésicule :`,
    choices: [
      `Reste insérée dans une membrane.`,
      `Peut porter un signal d’adressage.`,
      `Peut changer de compartiment au cours d’un flux.`,
      `Devient automatiquement une protéine luminale soluble.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La topologie membranaire est conservée pendant le transport vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le caractère dynamique du SEM est lié :`,
    choices: [
      `À la permanence des flux.`,
      `Au transport entre compartiments.`,
      `À l’équilibre entre endocytose et exocytose.`,
      `À l’absence totale de cytosquelette.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cytosquelette participe au contraire au transport vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule eucaryote possède un compartiment à membrane et lumière, relié à d’autres cavités par des vésicules. Cette description est compatible avec :`,
    choices: [
      `Un compartiment du SEM.`,
      `Une cavité luminale.`,
      `Un système d’échanges membranaires.`,
      `Une mitochondrie nécessairement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La définition correspond au SEM sans désigner nécessairement une mitochondrie.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine quitte le RE, passe par le Golgi puis atteint la membrane plasmique. Ce trajet correspond :`,
    choices: [
      `Au flux principal sortant.`,
      `Au sens de l’exocytose.`,
      `À un flux vectoriel permanent.`,
      `Au quatrième flux rétrograde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le trajet RE → Golgi → membrane appartient au flux principal.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un récepteur endocyté revient à la membrane plasmique. Cette situation relève :`,
    choices: [
      `Du recyclage membranaire.`,
      `Du second flux rétrograde centré sur les endosomes.`,
      `D’un trajet passant par le carrefour endosomal.`,
      `Du flux principal sortant depuis le RE uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le recyclage des récepteurs appartient au flux endosomal rétrograde.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un cavéosome contenant une toxine rejoint directement le RE. Cette situation illustre :`,
    choices: [
      `Le quatrième flux.`,
      `Un flux rétrograde.`,
      `Un trajet direct cavéosome → RE.`,
      `Une sécrétion constitutive.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche associe le quatrième flux au transport direct des cavéosomes vers le RE.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une anomalie des signaux d’adressage pourrait :`,
    choices: [
      `Perturber la destination d’une protéine.`,
      `Modifier sa rétention dans un compartiment.`,
      `Désorganiser un flux vésiculaire.`,
      `Transformer un peroxysome en compartiment du SEM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’adressage et la rétention conditionnent la localisation des protéines.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule très riche en membranes internes peut présenter :`,
    choices: [
      `Une forte contribution du SEM à sa surface totale.`,
      `Des échanges vésiculaires importants.`,
      `Une organisation en compartiments.`,
      `L’inclusion obligatoire des mitochondries dans le SEM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La richesse en membranes internes ne change pas l’exclusion des mitochondries.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les couples trajet–flux, lesquels sont corrects ?`,
    choices: [
      `RE → Golgi : flux principal.`,
      `Endosome → membrane : recyclage du second flux.`,
      `Golgi → RE : troisième flux.`,
      `Cavéosome → RE : quatrième flux.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les quatre couples correspondent à la cartographie des flux de la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le SEM est défini comme un ensemble de cavités :`,
    choices: [
      `Limitées par une membrane.`,
      `Possédant une lumière.`,
      `Communiquant par vésicules ou canalicules.`,
      `Toujours séparées sans aucun échange.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La communication entre cavités est une caractéristique essentielle du SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À partir de la figure des quatre flux :

![Compartiments et flux du SEM](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-1/sem-compartiments-quatre-flux.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Les endosomes occupent une position de carrefour.`,
      `Les lysosomes reçoivent une partie du matériel endocyté.`,
      `La membrane plasmique peut participer à la fois à l’endocytose et à l’exocytose.`,
      `Le RE est absent de tout flux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le RE est au contraire le point de départ du flux principal et la destination de flux rétrogrades.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est la plus fidèle au cours ?`,
    choices: [
      `Le SEM est un réseau de cavités dynamiques.`,
      `Les protéines et les membranes y sont triées selon des signaux.`,
      `Les flux relient RE, Golgi, endosomes, lysosomes et membrane plasmique.`,
      `Mitochondries et peroxysomes en constituent les principaux compartiments.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Mitochondries et peroxysomes sont explicitement exclus du SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `definition-et-compartiments-sem`,
    title: `Définition et compartiments du SEM`,
    description: `Cavités, compartiments et importance quantitative du système endomembranaire.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `flux-membranaires`,
    title: `Flux membranaires`,
    description: `Flux principal, flux endosomal et retours vers le réticulum endoplasmique.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `organisation-dynamique-sem`,
    title: `Organisation dynamique du SEM`,
    description: `Applications sur les compartiments, les signaux d’adressage et les quatre flux.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
