import type { SeedQuestion, SeedQuiz } from './health-training-ue13.shared';

export const SYNTHESIS_QUESTIONS: SeedQuestion[] = [
  {
    order: 101,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une biopsie doit être transformée en lame HES. Parmi les étapes cohérentes :",
    choices: [
      "Fixation rapide au formol.",
      "Sélection macroscopique et mise en cassette.",
      "Inclusion en paraffine puis coupe au microtome.",
      "Coloration HES après création de la lame blanche.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "La séquence complète va de la fixation du prélèvement à la coloration de la coupe.",
    choiceExplanations: [
      "La fixation préserve les structures.",
      "La macroscopie choisit les zones d’intérêt.",
      "L’inclusion fournit le bloc et le microtome réalise la coupe.",
      "La coloration intervient sur la coupe adhérente au verre.",
    ],
  },
  {
    order: 102,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Dans cette même chaîne, une fixation tardive et une coupe trop épaisse risquent respectivement :",
    choices: [
      "De laisser débuter l’autolyse.",
      "De compromettre la conservation des structures.",
      "D’augmenter les superpositions cellulaires.",
      "D’améliorer systématiquement la résolution optique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La qualité finale dépend de la rapidité de fixation et de la finesse de la coupe.",
    choiceExplanations: [
      "Le retard expose à l’autolyse.",
      "La dégradation altère l’interprétation.",
      "Une coupe épaisse superpose davantage de cellules.",
      "La résolution dépend du microscope et n’est pas améliorée par une coupe trop épaisse.",
    ],
  },
  {
    order: 103,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une lame montre des noyaux violets, des cytoplasmes roses et du collagène orange, mais le mucus reste peu visible. Une stratégie cohérente est :",
    choices: [
      "Identifier l’HES comme coloration de base.",
      "Demander un PAS pour le mucus.",
      "Rechercher une teinte fuchsia après PAS.",
      "Conclure que l’hématoxyline colore le mucus en noir.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’HES donne les contrastes généraux et le PAS complète l’analyse du mucus.",
    choiceExplanations: [
      "Le profil de couleurs correspond à l’HES.",
      "Le PAS est indiqué pour le mucus.",
      "Le fuchsia est la teinte attendue.",
      "L’hématoxyline colore surtout les noyaux en violet.",
    ],
  },
  {
    order: 104,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Comparer une biopsie incluse en paraffine et un frottis cervico-utérin :",
    choices: [
      "La biopsie permet d’étudier l’architecture d’un tissu.",
      "Le frottis permet d’étudier des cellules déposées sur une lame.",
      "Le frottis peut participer au dépistage du cancer du col.",
      "Les deux préparations nécessitent obligatoirement une coupe au microtome de 4 µm.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’histologie et la cytologie répondent à des questions complémentaires avec des préparations différentes.",
    choiceExplanations: [
      "La coupe conserve l’organisation tissulaire.",
      "Le frottis est une préparation cytologique.",
      "C’est l’exemple clinique du cours.",
      "Les cellules d’un frottis ne sont pas coupées comme un bloc de paraffine.",
    ],
  },
  {
    order: 105,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Associer une échelle ou une structure à l’outil le plus adapté :",
    choices: [
      "Organisation d’un tissu coloré — microscope optique.",
      "Ultrastructure intracellulaire — MET.",
      "Relief d’une surface ciliée — MEB.",
      "Molécules individuelles — macroscopie à l’œil nu.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le choix de l’outil dépend de l’échelle et du type d’information recherché.",
    choiceExplanations: [
      "Le fond clair est adapté à la lame histologique.",
      "Le MET donne accès aux détails internes nanométriques.",
      "Le MEB décrit les reliefs.",
      "L’œil nu ne permet pas l’observation moléculaire.",
    ],
  },
  {
    order: 106,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Plusieurs erreurs techniques sont observées. Lesquelles peuvent directement altérer la qualité de la lame ?",
    choices: [
      "Retarder la fixation au-delà du délai recommandé.",
      "Omettre l’étape de déshydratation avant la paraffine.",
      "Mal faire adhérer la coupe sur la lame blanche.",
      "Confondre grossissement et résolution lors de l’interprétation.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "La qualité dépend à la fois de la préparation du tissu et de l’interprétation correcte des capacités du microscope.",
    choiceExplanations: [
      "Le retard favorise les altérations.",
      "La séquence d’inclusion décrite serait rompue.",
      "La coupe risque de se décoller.",
      "Un fort grossissement sans résolution suffisante peut donner une image floue.",
    ],
  },
  {
    order: 107,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un laboratoire reçoit trois demandes : rechercher du mucus, visualiser des fibres élastiques et identifier du collagène III. Les choix adaptés sont respectivement :",
    choices: [
      "PAS pour le mucus.",
      "Orcéine pour les fibres élastiques.",
      "Réticuline pour le collagène III.",
      "Hématoxyline seule pour les trois cibles.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les colorations spéciales sont choisies selon la structure recherchée.",
    choiceExplanations: [
      "Le PAS donne un mucus fuchsia.",
      "L’orcéine révèle l’élastine.",
      "La réticuline cible le collagène III.",
      "L’hématoxyline est avant tout un colorant nucléaire.",
    ],
  },
  {
    order: 108,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "À propos des quatre tissus fondamentaux et de leur observation :",
    choices: [
      "Le tissu épithélial associe des cellules jointives et des fonctions de séparation.",
      "Le tissu musculaire est caractérisé par la capacité de contraction.",
      "Le tissu nerveux participe à la communication.",
      "L’histologie étudie leur organisation à une échelle située entre cellule et organe.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les caractéristiques introductives des tissus s’articulent avec l’échelle propre de l’histologie.",
    choiceExplanations: [
      "Cette caractéristique appartient au tissu épithélial.",
      "La contraction définit le tissu musculaire.",
      "La communication caractérise le tissu nerveux.",
      "Cette position d’échelle est celle du cours.",
    ],
  },
  {
    order: 109,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un liquide d’urines, une pièce opératoire et une surface cervico-utérine sont prélevés. Les orientations cohérentes sont :",
    choices: [
      "Urines — préparation cytologique possible.",
      "Pièce opératoire — macroscopie puis technique histologique.",
      "Surface cervico-utérine — frottis cytologique possible.",
      "Tous ces prélèvements doivent nécessairement être traités de façon strictement identique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La nature du prélèvement détermine la chaîne de préparation la plus pertinente.",
    choiceExplanations: [
      "Les urines peuvent fournir des cellules pour la cytologie.",
      "La pièce est sélectionnée et incluse avant la coupe.",
      "Le frottis est l’exemple du cours.",
      "Les techniques diffèrent selon le support et l’objectif.",
    ],
  },
  {
    order: 110,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Du prélèvement à l’image, quelles affirmations résument correctement le chapitre ?",
    choices: [
      "La fixation préserve les structures avant l’inclusion et la coupe.",
      "La coloration crée des contrastes interprétables.",
      "La cytologie étudie des cellules sans conserver toute l’architecture tissulaire.",
      "Le choix entre optique, MET et MEB dépend de l’échelle et du type d’information recherché.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le chapitre relie trois dimensions : préparation, coloration et choix du dispositif d’observation.",
    choiceExplanations: [
      "La fixation est le point de départ de la conservation.",
      "Sans contraste, la plupart des structures seraient peu visibles.",
      "Cette limite distingue la cytologie de l’histologie.",
      "Chaque microscope apporte une information spécifique.",
    ],
  },
];

export const SYNTHESIS_QUIZZES: SeedQuiz[] = [
  {
    order: 11,
    slug: "du-prelevement-a-image-microscopique",
    title: "Du prélèvement à l’image microscopique",
    description: "Quiz transversal sur la préparation, la coloration, la cytologie et le choix du microscope.",
    stage: 'MASTER',
    sectionOrder: 6,
    items: [
      {
        type: 'GROUP',
        title: "Parcours d’une biopsie",
        sharedStatement: "Une biopsie est adressée au laboratoire afin d’obtenir une lame HES interprétable.",
        questionOrders: [101, 102],
      },
      { type: 'QUESTION', questionOrder: 103 },
      { type: 'QUESTION', questionOrder: 104 },
      { type: 'QUESTION', questionOrder: 105 },
      { type: 'QUESTION', questionOrder: 106 },
      { type: 'QUESTION', questionOrder: 107 },
      { type: 'QUESTION', questionOrder: 108 },
      { type: 'QUESTION', questionOrder: 109 },
      { type: 'QUESTION', questionOrder: 110 },
    ],
  },
];
