/** UE14 – Biologie cellulaire – Chapitre 2 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La membrane plasmique est décrite comme :` ,
    choices: [
      `Fluide.`,
      `Dynamique.`,
      `Totalement figée.`,
      `Fonctionnelle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La membrane n’est pas figée à l’échelle moléculaire.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La fluidité membranaire permet :` ,
    choices: [
      `Une réparation rapide après petite déchirure.`,
      `Une variation de surface.`,
      `L’immobilisation définitive de tous les transporteurs.`,
      `Une adaptation fonctionnelle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fluidité favorise la réorganisation locale des lipides.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La fluidité dépend :` ,
    choices: [
      `Des interactions de Van der Waals.`,
      `De la longueur des acides gras.`,
      `Du degré d’insaturation.`,
      `De la quantité de cholestérol.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Tous ces facteurs modulent la cohésion de la bicouche.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Des acides gras longs et saturés rendent la membrane plutôt :` ,
    choices: [
      `Moins fluide.`,
      `Plus cohésive.`,
      `Plus fluidifiée que des chaînes insaturées.`,
      `Plus facile à empaqueter.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les insaturations augmentent au contraire la fluidité.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les mouvements des phospholipides :` ,
    choices: [
      `Diffusion latérale.`,
      `Rotation et flexion.`,
      `Bascule entre feuillets.`,
      `Immobilité complète.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane est dynamique ; plusieurs mouvements sont possibles.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `L’ordre de grandeur indiqué pour la diffusion latérale est :` ,
    choices: [
      `≈ 2 µm/s.`,
      `≈ 2 cm/s.`,
      `≈ 1 fois/mois.`,
      `≈ 2 nm/an.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La diffusion latérale est rapide à l’échelle cellulaire.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `La bascule d’un phospholipide d’un feuillet à l’autre est :` ,
    choices: [
      `Rare, de l’ordre d’une fois par mois.`,
      `Le mouvement le plus rapide.`,
      `Impossible dans une cellule vivante.`,
      `Toujours spontanée et unidirectionnelle.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le flip-flop spontané est décrit comme rare.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant l’asymétrie membranaire :` ,
    choices: [
      `Les deux feuillets diffèrent en composition.`,
      `PS et PE sont plutôt internes.`,
      `PC est plutôt externe.`,
      `Les glycoprotéines du glycocalyx sont surtout internes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les glycoprotéines du glycocalyx sont externes.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des flippases et scramblases :` ,
    choices: [
      `Les flippases maintiennent l’asymétrie.`,
      `Les scramblases tendent à symétriser certains phospholipides.`,
      `Ce sont des protéines membranaires spécifiques.`,
      `Les scramblases sont des molécules de jonction serrée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces protéines régulent la répartition des phospholipides entre feuillets.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le glycocalyx :` ,
    choices: [
      `Participe à l’asymétrie.`,
      `Est externe.`,
      `Résulte en partie des glycolipides et glycoprotéines.`,
      `Correspond au cytosquelette de spectrine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le glycocalyx est un revêtement glucidique externe.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’entérocyte est une cellule polarisée car :` ,
    choices: [
      `Il possède un domaine apical.`,
      `Il possède un domaine baso-latéral.`,
      `Les deux domaines sont séparés par des jonctions serrées.`,
      `Toutes les protéines diffusent librement entre les deux domaines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les jonctions serrées limitent la diffusion latérale entre domaines.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le rôle principal des jonctions serrées est de :` ,
    choices: [
      `Constituer une barrière latérale.`,
      `Empêcher la diffusion latérale de protéines.`,
      `Maintenir des compositions différentes entre domaines.`,
      `Fusionner définitivement les membranes voisines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les membranes restent distinctes malgré l’adhérence.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Si une membrane est perforée de façon minime, la fluidité permet :` ,
    choices: [
      `Le rapprochement des phospholipides.`,
      `Une réparation rapide.`,
      `La disparition irréversible de la bicouche.`,
      `Une restauration de la continuité.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La membrane peut s’auto-réparer après une petite lésion.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quels éléments diminuent plutôt la fluidité ?` ,
    choices: [
      `Des acides gras longs.`,
      `Un degré élevé de saturation.`,
      `Beaucoup de doubles liaisons.`,
      `Des interactions de Van der Waals plus fortes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les doubles liaisons gênent l’empilement et augmentent la fluidité.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Quel mouvement est présenté comme un mouvement avec déplacement ?` ,
    choices: [
      `La diffusion latérale.`,
      `La rotation.`,
      `La flexion.`,
      `Aucun.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La diffusion latérale déplace les molécules dans le plan de la membrane.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À partir de la figure de structure :` ,
    choices: [
      `PC est indiquée comme plutôt externe.`,
      `PS/PE sont plutôt internes.`,
      `La figure illustre l’asymétrie.`,
      `La figure montre une symétrie parfaite.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La répartition inégale des lipides est explicitement montrée.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 47,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une membrane enrichie en acides gras insaturés sera plutôt :` ,
    choices: [
      `Plus fluide.`,
      `Moins bien empaquetée.`,
      `Plus cohésive au maximum.`,
      `Moins favorable aux interactions efficaces entre chaînes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les doubles liaisons gênent l’empilement des chaînes.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 48,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’inhibition des flippases peut entraîner :` ,
    choices: [
      `Une perturbation du maintien de l’asymétrie.`,
      `Une diminution des transferts orientés entre feuillets.`,
      `La transformation des scramblases en occludines.`,
      `Une modification de la répartition des phospholipides.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les flippases participent au maintien actif de l’asymétrie.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 49,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La polarité de l’entérocyte repose sur :` ,
    choices: [
      `Deux domaines membranaires de compositions différentes.`,
      `Des jonctions serrées.`,
      `Une diffusion totalement libre des protéines membranaires.`,
      `Des fonctions distinctes entre pôles apical et baso-latéral.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La polarité suppose au contraire une diffusion latérale limitée entre domaines.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 50,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos du cholestérol membranaire :` ,
    choices: [
      `Il est plus petit et plus rigide.`,
      `Il participe à la stabilisation de la bicouche.`,
      `Il se situe uniquement dans le glycocalyx.`,
      `Sa quantité influence les propriétés de la membrane.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le cholestérol est inséré dans la bicouche lipidique.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les mouvements sans déplacement des phospholipides comprennent :` ,
    choices: [
      `La rotation.`,
      `La flexion.`,
      `Une modification locale d’orientation.`,
      `La diffusion latérale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La diffusion latérale est un mouvement avec déplacement.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une membrane strictement homogène serait en contradiction avec :` ,
    choices: [
      `La variabilité de composition selon les zones.`,
      `La notion de polarité cellulaire.`,
      `L’exemple de l’entérocyte.`,
      `La réalité des membranes biologiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les membranes biologiques sont organisées et non uniformes.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si des protéines baso-latérales apparaissent au pôle apical :` ,
    choices: [
      `On peut suspecter une altération des jonctions serrées.`,
      `La polarité cellulaire peut être diminuée.`,
      `La diffusion latérale devient moins contrôlée.`,
      `La séparation des domaines est renforcée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le mélange des domaines traduit une perte de polarité.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les scramblases :` ,
    choices: [
      `Tendent à symétriser la distribution de certains phospholipides.`,
      `Agissent sur des phospholipides chargés négativement.`,
      `Ont exactement la même fonction que les flippases.`,
      `Modifient la composition relative des feuillets.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Leur rôle est distinct de celui des flippases.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?` ,
    choices: [
      `La membrane est fluide, asymétrique et hétérogène.`,
      `La fluidité dépend des acides gras et du cholestérol.`,
      `Certaines cellules exploitent cette organisation en domaines polarisés.`,
      `Les constituants des deux feuillets sont immobiles et identiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane est dynamique et organisée.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le maintien d’une composition différente entre pôle apical et pôle baso-latéral nécessite :` ,
    choices: [
      `Des jonctions serrées.`,
      `Une limitation de la diffusion latérale.`,
      `Deux domaines fonctionnels distincts.`,
      `La disparition complète de la fluidité.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polarité n’implique pas l’absence de fluidité.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `Quel couple est correctement associé ?` ,
    choices: [
      `Flippase — maintien de l’asymétrie.`,
      `Scramblase — jonction serrée.`,
      `Occludine — symétrisation des phospholipides.`,
      `Phosphatidylcholine — localisation principalement interne.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Les trois autres associations sont erronées.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une augmentation des chaînes saturées devrait :` ,
    choices: [
      `Augmenter la cohésion.`,
      `Diminuer la fluidité.`,
      `Favoriser l’empilement régulier.`,
      `Mimer l’effet des doubles liaisons.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les doubles liaisons ont un effet opposé.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Chez une cellule polarisée, la répartition non uniforme des molécules signifie :` ,
    choices: [
      `Des régions de composition différente.`,
      `Certaines protéines confinées à un domaine.`,
      `Une organisation spatiale de la membrane.`,
      `La perte du caractère bilamellaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polarité modifie l’organisation spatiale, pas la nature bilamellaire.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Conclusion de cette section :` ,
    choices: [
      `Les membranes biologiques sont dynamiques.`,
      `Les deux feuillets peuvent différer en composition.`,
      `La polarité cellulaire exploite cette hétérogénéité.`,
      `Les mouvements entre feuillets sont tous fréquents et non régulés.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Certains mouvements sont rares et/ou régulés.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `fluidite-membranaire`,
    title: `Fluidité membranaire`,
    description: `Fluidité, cohésion et mouvements lipidiques.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `asymetrie-et-jonctions-serrees`,
    title: `Asymétrie et jonctions serrées`,
    description: `Asymétrie des feuillets, flippases, scramblases et polarité.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `polarite-et-organisation-membranaire`,
    title: `Polarité et organisation membranaire`,
    description: `Raisonnement autour de la polarité et des propriétés membranaires.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
