/** Cartographie éditoriale V2 — auteur */

export const UE14_BIOCH_CH9_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-generalites-structure-aa",
    "title": "Généralités et structure des acides aminés",
    "description": "Repères sur les acides aminés protéinogènes, la structure commune, le radical R et la nomenclature.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-nomenclature-aa-essentiels",
    "title": "Généralités et structure des acides aminés",
    "description": "Applications sur nomenclature, acides aminés essentiels et statut lié à la croissance.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-classification-radical-aa",
    "title": "Classification selon la nature du radical",
    "description": "Identifier les grandes familles de chaînes latérales et leurs groupements caractéristiques.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-familles-chaines-laterales-aa",
    "title": "Classification selon la nature du radical",
    "description": "Comparer acides aminés aliphatiques, hydroxylés, soufrés, acides, amides et basiques.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-aromatiques-proline-polarite",
    "title": "Aromatiques, proline, polarité et chiralité",
    "description": "Repères sur les aromatiques, la proline et les classes de polarité.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-polarite-solubilite-chiralite",
    "title": "Aromatiques, proline, polarité et chiralité",
    "description": "Applications sur solubilité, chiralité, série D/L et exception de la glycine.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-uv-ionisation-pi",
    "title": "Propriétés spectrales, ionisation et réactions chimiques",
    "description": "Repères sur absorption UV, amphotérie, zwitterion et point isoélectrique.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-charge-ph-ninhydrine",
    "title": "Propriétés spectrales, ionisation et réactions chimiques",
    "description": "Applications sur charge selon le pH, pHi et réaction à la ninhydrine.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-ionisation-ninhydrine-aa",
    "title": "Ionisation et analyse des acides aminés",
    "description": "Maîtrise transversale des formes ioniques, pHi et usages analytiques de la ninhydrine.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-acides-amines",
    "title": "Synthèse du chapitre",
    "description": "Consolidation transversale de la structure, classification et propriétés des acides aminés.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-acides-amines-structure-roles-biologiques",
    "title": "Synthèse du chapitre",
    "description": "Maîtrise de l’ensemble du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH9_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["les acides aminés du monde vivant"],
  2: ["les acides aminés du monde vivant"],
  3: ["les acides aminés protéinogènes"],
  4: ["les acides aminés protéinogènes"],
  5: ["la structure commune d’un acide aminé"],
  6: ["la structure commune d’un acide aminé"],
  7: ["le carbone α"],
  8: ["le carbone α"],
  9: ["la nomenclature des acides aminés"],
  10: ["la nomenclature des acides aminés"],
  11: ["la notion d’acide aminé essentiel"],
  12: ["la notion d’acide aminé essentiel"],
  13: ["un groupe de huit acides aminés indispensables"],
  14: ["un exemple d’acide aminé indispensable"],
  15: ["les besoins en histidine et en arginine pendant la croissance"],
  16: ["l’arginine conditionnellement indispensable"],
  17: ["les réactions d’interconversion"],
  18: ["les réactions d’interconversion"],
  19: ["la glycine comme cas structural"],
  20: ["la glycine comme cas structural"],
  21: ["la relation entre acides aminés et protéines"],
  22: ["la relation entre acides aminés et protéines"],
  23: ["les acides aminés aliphatiques"],
  24: ["les acides aminés aliphatiques"],
  25: ["la glycine et l’alanine"],
  26: ["la glycine et l’alanine"],
  27: ["les acides aminés branchés"],
  28: ["les acides aminés branchés"],
  29: ["la leucine et l’isoleucine"],
  30: ["la leucine et l’isoleucine"],
  31: ["les acides aminés hydroxylés"],
  32: ["les acides aminés hydroxylés"],
  33: ["les acides aminés soufrés"],
  34: ["les acides aminés soufrés"],
  35: ["les acides aminés acides"],
  36: ["les acides aminés acides"],
  37: ["l’asparagine et la glutamine"],
  38: ["l’asparagine et la glutamine"],
  39: ["la lysine"],
  40: ["la lysine"],
  41: ["l’arginine"],
  42: ["l’arginine"],
  43: ["l’histidine"],
  44: ["l’histidine"],
  45: ["la phénylalanine"],
  46: ["la phénylalanine"],
  47: ["la tyrosine"],
  48: ["la tyrosine"],
  49: ["le tryptophane"],
  50: ["le tryptophane"],
  51: ["la proline"],
  52: ["la proline"],
  53: ["la 4-hydroxyproline"],
  54: ["la 4-hydroxyproline"],
  55: ["les acides aminés à chaîne latérale acide"],
  56: ["les acides aminés non polaires et hydrophobes"],
  57: ["les acides aminés polaires neutres"],
  58: ["les acides aminés polaires neutres"],
  59: ["les acides aminés polaires acides"],
  60: ["les acides aminés polaires acides"],
  61: ["les acides aminés polaires basiques"],
  62: ["les acides aminés polaires basiques"],
  63: ["la solubilité des acides aminés"],
  64: ["la chiralité des acides aminés"],
  65: ["la chiralité des acides aminés"],
  66: ["la chiralité des acides aminés"],
  67: ["l’absorption UV générale des acides aminés"],
  68: ["l’absorption UV générale des acides aminés"],
  69: ["l’absorption autour de 280 nm"],
  70: ["l’absorption autour de 280 nm"],
  71: ["l’ionisation des acides aminés"],
  72: ["l’ionisation des acides aminés"],
  73: ["le caractère amphotère"],
  74: ["le caractère amphotère"],
  75: ["la forme en milieu acide"],
  76: ["la forme en milieu acide"],
  77: ["le zwitterion en milieu neutre"],
  78: ["l’absorbance des protéines à 280 nm"],
  79: ["la forme en milieu basique"],
  80: ["la forme en milieu basique"],
  81: ["le point isoélectrique"],
  82: ["le point isoélectrique"],
  83: ["l’influence de la chaîne latérale sur le pHi"],
  84: ["l’influence de la chaîne latérale sur le pHi"],
  85: ["le pHi de la lysine"],
  86: ["le pHi de la lysine"],
  87: ["le pHi de l’acide aspartique"],
  88: ["le pHi de l’acide aspartique"],
  89: ["zwitterion et charges locales"],
  90: ["la charge des acides aminés selon le pH"],
  91: ["le zwitterion et le point isoélectrique"],
  92: ["le pHi de la lysine"],
  93: ["la réaction à la ninhydrine des acides aminés primaires"],
  94: ["la réaction à la ninhydrine des acides aminés primaires"],
  95: ["la réaction à la ninhydrine de la proline"],
  96: ["la réaction à la ninhydrine de la proline"],
  97: ["le mécanisme de la réaction à la ninhydrine"],
  98: ["le mécanisme de la réaction à la ninhydrine"],
  99: ["l’usage analytique de la ninhydrine"],
  100: ["l’usage analytique de la ninhydrine"],
  101: ["la structure commune d’un acide aminé"],
  102: ["la structure commune d’un acide aminé"],
  103: ["un groupe de huit acides aminés indispensables"],
  104: ["un exemple d’acide aminé indispensable"],
  105: ["les acides aminés hydroxylés"],
  106: ["les acides aminés hydroxylés"],
  107: ["les acides aminés soufrés"],
  108: ["les acides aminés soufrés"],
  109: ["les acides aminés acides"],
  110: ["synthèse : classification, chiralité et propriétés spectrales"],
  111: ["la proline"],
  112: ["la proline"],
  113: ["la solubilité des acides aminés"],
  114: ["la solubilité des acides aminés"],
  115: ["la chiralité des acides aminés"],
  116: ["la chiralité des acides aminés"],
  117: ["les vingt acides aminés standards"],
  118: ["l’absorption autour de 280 nm"],
  119: ["le point isoélectrique"],
  120: ["le point isoélectrique"],
  121: ["la réaction à la ninhydrine de la proline"],
  122: ["la réaction à la ninhydrine de la proline"],
};
