/**
 * UE14 – Biologie cellulaire – Chapitre 5
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’appareil de Golgi :`,
    choices: [
      `Est formé de dictyosomes en pile de saccules.`,
      `Est entouré de nombreuses vésicules.`,
      `Est proche du noyau et du centrosome.`,
      `Est indépendant du cytosquelette.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le Golgi est lié au cytosquelette et son organisation dépend de l’activité cellulaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le nombre de dictyosomes :`,
    choices: [
      `Peut augmenter avec l’activité cellulaire.`,
      `Est toujours identique dans toutes les cellules.`,
      `Reflète en partie l’intensité du trafic sécrétoire.`,
      `Devient nul dans les cellules très actives.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Le développement du Golgi accompagne l’activité biosynthétique et sécrétoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les trois grandes régions golgiennes sont :`,
    choices: [
      `cis.`,
      `médiane.`,
      `trans.`,
      `La matrice mitochondriale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le TGN correspond à la région trans spécialisée dans le tri et l’exportation.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le réseau transgolgien (TGN) :`,
    choices: [
      `Est proche du carrefour endosomal.`,
      `Est en interface avec la membrane plasmique.`,
      `Participe au tri des protéines.`,
      `Correspond au feuillet interne de l’enveloppe nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le TGN constitue une plateforme de tri en aval des citernes golgiennes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 35,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante :

![Organisation du Golgi](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-2/golgi-compartiments-tri.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Le matériel arrive du RE du côté cis.`,
      `Les compartiments golgiens ont des fonctions différentes.`,
      `Le TGN assure le tri vers plusieurs destinations.`,
      `Le flux principal va du TGN vers le RE uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le flux principal progresse du RE vers Golgi puis vers les destinations d’exocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’O-glycosylation golgienne :`,
    choices: [
      `Poursuit la maturation après la N-glycosylation du RE.`,
      `Utilise des glycosyltransférases.`,
      `Peut concerner des protéines solubles ou transmembranaires.`,
      `Détruit toutes les chaînes glucidiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le Golgi modifie séquentiellement les chaînes polysaccharidiques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les sucres ou dérivés ajoutés dans le Golgi :`,
    choices: [
      `N-acétylglucosamine.`,
      `Galactose.`,
      `NANA.`,
      `Uniquement du glucose libre non activé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les transferts utilisent des sucres activés, par exemple l’UDP-galactose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 38,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le mannose-6-phosphate :`,
    choices: [
      `Peut être ajouté dans le Golgi cis.`,
      `Participe à l’adressage des enzymes lysosomales.`,
      `Est reconnu plus tard par un récepteur spécifique.`,
      `Est le signal de rétention KDEL des protéines solubles du RE.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le M6P et KDEL sont des signaux distincts pour des destinations différentes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 39,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le Golgi peut réaliser :`,
    choices: [
      `La sulfatation des glycosaminoglycanes.`,
      `La sulfatation des protéoglycanes.`,
      `La synthèse progressive de sphingolipides.`,
      `La réplication de l’ADN mitochondrial.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le Golgi joue des rôles de maturation glucidique et lipidique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 40,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le stockage du Ca2+ dans le Golgi :`,
    choices: [
      `Utilise une pompe Ca2+/ATPase pour l’entrée.`,
      `Implique une fixation par des protéines luminales.`,
      `Peut utiliser un canal de sortie dépendant de l’IP3.`,
      `Est impossible dans les citernes golgiennes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le Golgi partage avec le RE plusieurs mécanismes de stockage du Ca2+.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le TGN contient notamment :`,
    choices: [
      `Une phosphatase acide.`,
      `Des endoprotéases membranaires.`,
      `Des perméases à ATP.`,
      `Uniquement des ribosomes fixés à sa face luminale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le TGN participe à la maturation et au transport de différents constituants.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les endoprotéases du TGN :`,
    choices: [
      `Peuvent cliver des protéines.`,
      `Participent à la maturation de peptides.`,
      `Interviennent dans la maturation de certaines hormones.`,
      `Sont des canaux à Ca2+ sans activité enzymatique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le clivage protéolytique peut convertir un précurseur inactif en produit actif.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 43,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les vésicules COP ou coatomères :`,
    choices: [
      `Participent au transport RE-Golgi.`,
      `Participent au transport entre compartiments golgiens.`,
      `Constituent un revêtement vésiculaire.`,
      `Sont des hydrolases acides de la lumière lysosomale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les protéines COP sont des protéines de revêtement, non des enzymes lysosomales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Au niveau du TGN, la sécrétion constitutive :`,
    choices: [
      `Peut concerner les GAG et les protéoglycanes.`,
      `Peut utiliser un revêtement ARF-FAPP.`,
      `Peut utiliser la cavéoline.`,
      `Nécessite toujours un signal extracellulaire déclencheur.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La sécrétion constitutive est permanente et ne dépend pas d’un signal déclencheur.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La sécrétion régulée à partir du TGN :`,
    choices: [
      `Concerne les grains de sécrétion.`,
      `Peut concerner des vésicules destinées aux lysosomes.`,
      `Utilise clathrine, adaptines et dynamine.`,
      `Est permanente et indépendante de tout signal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La sécrétion régulée attend un signal avant la fusion finale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 46,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le carrefour endosomal :`,
    choices: [
      `Se situe entre TGN et membrane plasmique.`,
      `Est morphologiquement hétérogène.`,
      `Comprend endosomes, lysosomes, exosomes et grains de sécrétion.`,
      `Est totalement isolé des agents pathogènes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Des agents pathogènes peuvent circuler dans ce réseau, ce qui en fait une cible thérapeutique potentielle.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les grains de sécrétion :`,
    choices: [
      `Transportent le matériel de la sécrétion régulée.`,
      `Peuvent contenir un matériel initialement inactif.`,
      `Peuvent subir des modifications de pH et des clivages enzymatiques.`,
      `Sont toujours moins denses aux électrons au cours de leur maturation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La maturation peut s’accompagner d’une augmentation de la taille et de la densité aux électrons.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les exemples de matériel sécrété après maturation :`,
    choices: [
      `Enzymes pancréatiques.`,
      `Hormones antéhypophysaires.`,
      `Insuline issue de la pro-insuline.`,
      `ADN nucléaire exporté par exocytose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ADN nucléaire n’est pas un matériel de sécrétion du Golgi.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 49,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La maturation de la pro-insuline :`,
    choices: [
      `Implique une protéolyse.`,
      `Transforme un précurseur inactif en hormone active.`,
      `Peut se dérouler dans des grains de sécrétion.`,
      `Correspond à une N-glycosylation dans le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La pro-insuline est maturée par clivage protéolytique dans la voie sécrétoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 50,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Certaines maladies auto-immunes peuvent comporter :`,
    choices: [
      `Des auto-anticorps contre des protéines golgiennes.`,
      `Une atteinte de l’organisation du Golgi.`,
      `Des perturbations du trafic membranaire.`,
      `Une disparition systématique de toutes les mitochondries.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’atteinte est centrée sur des protéines golgiennes, sans impliquer obligatoirement les mitochondries.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Certains virus comme le VIH, Ebola ou la grippe :`,
    choices: [
      `Nécessitent un clivage de protéines virales pour leur maturation.`,
      `Peuvent exploiter les endoprotéases de la voie sécrétoire.`,
      `Dépendent de certaines étapes golgiennes.`,
      `Sont assemblés exclusivement dans la matrice mitochondriale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La maturation protéolytique dans le SEM peut être essentielle à l’infection.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la toxine cholérique selon la fiche :`,
    choices: [
      `Elle peut être endocytée par des cavéosomes.`,
      `Elle peut être clivée dans les compartiments endosomaux et golgiens.`,
      `Des fragments suivent un flux rétrograde vers le RE.`,
      `Elle agit uniquement dans la lumière du lysosome sans atteindre le cytosol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Après le flux rétrograde, un fragment peut atteindre le cytosol et agir sur les protéines G.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le flux rétrograde de la toxine cholérique peut suivre :`,
    choices: [
      `TGN puis RE.`,
      `Translocon puis cytosol.`,
      `Une action sur des protéines G hétérotrimériques.`,
      `Un trajet exclusif vers la matrice mitochondriale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours décrit un détournement du trafic rétrograde jusqu’au cytosol.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 54,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le Golgi est qualifié de carrefour de flux car :`,
    choices: [
      `Il reçoit du matériel du RE.`,
      `Il envoie du matériel vers le carrefour endosomal et la membrane plasmique.`,
      `Il participe à des flux rétrogrades.`,
      `Il ne possède qu’une seule destination possible.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le Golgi reçoit, modifie, trie et redistribue de nombreux constituants.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation perturbant l’ajout du M6P dans le Golgi cis risque de :`,
    choices: [
      `Compromettre l’adressage des hydrolases lysosomales.`,
      `Modifier le contenu enzymatique des lysosomes.`,
      `Provoquer une maladie de surcharge.`,
      `Améliorer automatiquement la dégradation lysosomale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le M6P est essentiel au tri des enzymes lysosomales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une perméase à ATP du TGN peut :`,
    choices: [
      `Transporter certains ions comme le cuivre.`,
      `Participer à la composition luminale du TGN.`,
      `Être distincte des endoprotéases.`,
      `Remplacer toutes les glycosyltransférases.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les perméases assurent des transports, tandis que les glycosyltransférases catalysent des modifications glucidiques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine sécrétée constitutivement :`,
    choices: [
      `Peut être modifiée dans les citernes golgiennes.`,
      `Peut être triée au TGN.`,
      `Peut voyager dans des vésicules ARF-FAPP ou à cavéoline.`,
      `Attend obligatoirement une augmentation de Ca2+ avant toute sortie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’attente d’un signal caractérise plutôt la sécrétion régulée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une hormone peptidique stockée avant libération :`,
    choices: [
      `Peut être contenue dans un grain de sécrétion.`,
      `Peut être maturée par clivage enzymatique.`,
      `Relève d’une sécrétion régulée.`,
      `Est libérée en permanence sans aucun signal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le stockage et le déclenchement par signal sont caractéristiques de la voie régulée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle(s) relation(s) est(sont) correcte(s) ?`,
    choices: [
      `N-glycosylation : RE.`,
      `O-glycosylation et maturation glucidique : Golgi.`,
      `M6P : adressage lysosomal.`,
      `KDEL : adressage des enzymes lysosomales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `KDEL est un signal de rétention des protéines solubles du RE.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse du Golgi est correcte ?`,
    choices: [
      `Il assure maturation, tri et exportation.`,
      `Ses compartiments possèdent des enzymes différentes.`,
      `Le TGN est une interface majeure avec le carrefour endosomal.`,
      `Il ne participe ni aux lipides ni au stockage du Ca2+.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le Golgi synthétise notamment des sphingolipides et peut stocker du Ca2+.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `organisation-appareil-golgi`,
    title: `Organisation de l’appareil de Golgi`,
    description: `Dictyosomes, compartiments cis, médian, trans et TGN.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `maturation-tri-et-secretion-golgi`,
    title: `Maturation, tri et sécrétion golgienne`,
    description: `O-glycosylation, M6P, vésicules COP et voies de sécrétion.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `golgi-pathologies-et-detournements`,
    title: `Golgi : pathologies et détournements du trafic`,
    description: `Maturation hormonale, virus, toxines et flux rétrograde.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
