/**
 * UE14 – Biologie cellulaire – Chapitre 9 : Le cycle cellulaire
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les trois grands points de contrôle sont situés :`,
    choices: [
      `En G1.`,
      `En G2.`,
      `En métaphase.`,
      `Exclusivement en phase S.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche distingue un contrôle G1, un contrôle G2 et un contrôle mitotique en métaphase.`,
    choiceExplanations: [
      `Exact. La fiche distingue un contrôle G1, un contrôle G2 et un contrôle mitotique en métaphase.`,
      `Exact. La fiche distingue un contrôle G1, un contrôle G2 et un contrôle mitotique en métaphase.`,
      `Exact. La fiche distingue un contrôle G1, un contrôle G2 et un contrôle mitotique en métaphase.`,
      `Faux. La fiche distingue un contrôle G1, un contrôle G2 et un contrôle mitotique en métaphase.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le point de restriction en G1 contrôle :`,
    choices: [
      `L’entrée en phase S.`,
      `L’environnement extracellulaire.`,
      `Le volume cellulaire.`,
      `L’intégrité de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Le franchissement dépend de conditions extracellulaires, de la taille et de l’état du génome.`,
    choiceExplanations: [
      `Exact. Le franchissement dépend de conditions extracellulaires, de la taille et de l’état du génome.`,
      `Exact. Le franchissement dépend de conditions extracellulaires, de la taille et de l’état du génome.`,
      `Exact. Le franchissement dépend de conditions extracellulaires, de la taille et de l’état du génome.`,
      `Exact. Le franchissement dépend de conditions extracellulaires, de la taille et de l’état du génome.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Si le point de restriction G1 n’est pas franchi :`,
    choices: [
      `La cellule peut entrer en G0.`,
      `La cellule peut entrer en apoptose.`,
      `La cellule doit obligatoirement commencer S.`,
      `Le cycle est arrêté avant la réplication.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le point G1 est un point de décision avant l’engagement dans la phase S.`,
    choiceExplanations: [
      `Exact. Le point G1 est un point de décision avant l’engagement dans la phase S.`,
      `Exact. Le point G1 est un point de décision avant l’engagement dans la phase S.`,
      `Faux. Le point G1 est un point de décision avant l’engagement dans la phase S.`,
      `Exact. Le point G1 est un point de décision avant l’engagement dans la phase S.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les facteurs de croissance en G1 précoce :`,
    choices: [
      `Favorisent la formation de D/CDK4-6.`,
      `Permettent le franchissement du point de restriction.`,
      `Deviennent indispensables même après le franchissement du point de restriction.`,
      `Peuvent réactiver une cellule entrée en G0 selon le cours.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Après franchissement du point de restriction, la cellule peut achever son cycle même sans facteurs de croissance.`,
    choiceExplanations: [
      `Exact. Après franchissement du point de restriction, la cellule peut achever son cycle même sans facteurs de croissance.`,
      `Exact. Après franchissement du point de restriction, la cellule peut achever son cycle même sans facteurs de croissance.`,
      `Faux. Après franchissement du point de restriction, la cellule peut achever son cycle même sans facteurs de croissance.`,
      `Exact. Après franchissement du point de restriction, la cellule peut achever son cycle même sans facteurs de croissance.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le contrôle du volume cellulaire a été illustré par :`,
    choices: [
      `Des cultures d’amibes.`,
      `Une réduction cytoplasmique.`,
      `L’arrêt de la division après réduction du cytoplasme.`,
      `Une augmentation obligatoire de la quantité d’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette expérience montre qu’un volume insuffisant peut empêcher la division.`,
    choiceExplanations: [
      `Exact. Cette expérience montre qu’un volume insuffisant peut empêcher la division.`,
      `Exact. Cette expérience montre qu’un volume insuffisant peut empêcher la division.`,
      `Exact. Cette expérience montre qu’un volume insuffisant peut empêcher la division.`,
      `Faux. Cette expérience montre qu’un volume insuffisant peut empêcher la division.`,
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En cas d’anomalie de l’ADN en G1 :`,
    choices: [
      `p16 peut être activée.`,
      `La progression peut être bloquée.`,
      `La cellule peut entrer en G0 ou en apoptose.`,
      `Le complexe D/CDK4-6 doit être renforcé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `p16 est une protéine inhibitrice visant à arrêter les complexes de G1.`,
    choiceExplanations: [
      `Exact. p16 est une protéine inhibitrice visant à arrêter les complexes de G1.`,
      `Exact. p16 est une protéine inhibitrice visant à arrêter les complexes de G1.`,
      `Exact. p16 est une protéine inhibitrice visant à arrêter les complexes de G1.`,
      `Faux. p16 est une protéine inhibitrice visant à arrêter les complexes de G1.`,
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La voie longue de réponse aux lésions de l’ADN en G1 implique :`,
    choices: [
      `p53.`,
      `La synthèse de p21.`,
      `L’inhibition des complexes E/CDK2 et A/CDK2.`,
      `L’activation du MPF.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `p53 favorise la production de p21, qui bloque la transition G1-S.`,
    choiceExplanations: [
      `Exact. p53 favorise la production de p21, qui bloque la transition G1-S.`,
      `Exact. p53 favorise la production de p21, qui bloque la transition G1-S.`,
      `Exact. p53 favorise la production de p21, qui bloque la transition G1-S.`,
      `Faux. p53 favorise la production de p21, qui bloque la transition G1-S.`,
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le point de contrôle G2 dépend :`,
    choices: [
      `De l’achèvement de la réplication.`,
      `De l’intégrité de l’ADN.`,
      `Du complexe B/CDK1.`,
      `De l’absence totale de chromosomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La transition G2-M n’a lieu que si le génome est complètement répliqué et non lésé.`,
    choiceExplanations: [
      `Exact. La transition G2-M n’a lieu que si le génome est complètement répliqué et non lésé.`,
      `Exact. La transition G2-M n’a lieu que si le génome est complètement répliqué et non lésé.`,
      `Exact. La transition G2-M n’a lieu que si le génome est complètement répliqué et non lésé.`,
      `Faux. La transition G2-M n’a lieu que si le génome est complètement répliqué et non lésé.`,
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Lorsqu’il n’y a pas d’anomalie en G2 :`,
    choices: [
      `cdc25 active le complexe B/CDK1.`,
      `CAK participe à son activation.`,
      `Wee1 inhibe obligatoirement le complexe.`,
      `La cellule peut entrer en mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Wee1 est surtout activée lorsqu’il faut bloquer la transition G2-M.`,
    choiceExplanations: [
      `Exact. Wee1 est surtout activée lorsqu’il faut bloquer la transition G2-M.`,
      `Exact. Wee1 est surtout activée lorsqu’il faut bloquer la transition G2-M.`,
      `Faux. Wee1 est surtout activée lorsqu’il faut bloquer la transition G2-M.`,
      `Exact. Wee1 est surtout activée lorsqu’il faut bloquer la transition G2-M.`,
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le point de contrôle en métaphase vérifie :`,
    choices: [
      `L’attachement des chromosomes au fuseau.`,
      `La bi-orientation des chromosomes.`,
      `L’alignement en plaque métaphasique.`,
      `La réplication de l’ADN en phase S.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le contrôle mitotique autorise l’anaphase seulement lorsque tous les chromosomes sont correctement attachés et orientés.`,
    choiceExplanations: [
      `Exact. Le contrôle mitotique autorise l’anaphase seulement lorsque tous les chromosomes sont correctement attachés et orientés.`,
      `Exact. Le contrôle mitotique autorise l’anaphase seulement lorsque tous les chromosomes sont correctement attachés et orientés.`,
      `Exact. Le contrôle mitotique autorise l’anaphase seulement lorsque tous les chromosomes sont correctement attachés et orientés.`,
      `Faux. Le contrôle mitotique autorise l’anaphase seulement lorsque tous les chromosomes sont correctement attachés et orientés.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Points de contrôle](/images/training/ue14/biologie-cellulaire/cycle-cellulaire/points-controle.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Le contrôle G1 précède la réplication.`,
      `Le contrôle G2 précède la mitose.`,
      `Le contrôle métaphasique précède l’anaphase.`,
      `Les trois contrôles vérifient exactement la même condition.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Chaque point de contrôle répond à des conditions spécifiques de la phase considérée.`,
    choiceExplanations: [
      `Exact. Chaque point de contrôle répond à des conditions spécifiques de la phase considérée.`,
      `Exact. Chaque point de contrôle répond à des conditions spécifiques de la phase considérée.`,
      `Exact. Chaque point de contrôle répond à des conditions spécifiques de la phase considérée.`,
      `Faux. Chaque point de contrôle répond à des conditions spécifiques de la phase considérée.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La protéine cdc25 :`,
    choices: [
      `Est une phosphatase activatrice.`,
      `Peut activer des complexes cycline/CDK.`,
      `Est bloquée rapidement lors de dommages de l’ADN.`,
      `Est une kinase inhibitrice identique à Wee1.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Wee1 est une kinase inhibitrice, tandis que cdc25 est une phosphatase activatrice.`,
    choiceExplanations: [
      `Exact. Wee1 est une kinase inhibitrice, tandis que cdc25 est une phosphatase activatrice.`,
      `Exact. Wee1 est une kinase inhibitrice, tandis que cdc25 est une phosphatase activatrice.`,
      `Exact. Wee1 est une kinase inhibitrice, tandis que cdc25 est une phosphatase activatrice.`,
      `Faux. Wee1 est une kinase inhibitrice, tandis que cdc25 est une phosphatase activatrice.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La protéine p21 :`,
    choices: [
      `Est induite par p53.`,
      `Inhibe E/CDK2 et A/CDK2.`,
      `Bloque la transition G1-S.`,
      `Dégrade directement les cohésines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le clivage des cohésines dépend de la séparase pendant l’anaphase.`,
    choiceExplanations: [
      `Exact. Le clivage des cohésines dépend de la séparase pendant l’anaphase.`,
      `Exact. Le clivage des cohésines dépend de la séparase pendant l’anaphase.`,
      `Exact. Le clivage des cohésines dépend de la séparase pendant l’anaphase.`,
      `Faux. Le clivage des cohésines dépend de la séparase pendant l’anaphase.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En G2, la protéine Wee1 :`,
    choices: [
      `Inhibe B/CDK1.`,
      `Favorise un maintien en G2 si l’ADN est lésé.`,
      `Active l’entrée en mitose.`,
      `S’oppose à cdc25 et CAK.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Wee1 participe au blocage de la transition G2-M.`,
    choiceExplanations: [
      `Exact. Wee1 participe au blocage de la transition G2-M.`,
      `Exact. Wee1 participe au blocage de la transition G2-M.`,
      `Faux. Wee1 participe au blocage de la transition G2-M.`,
      `Exact. Wee1 participe au blocage de la transition G2-M.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les régulateurs positifs des CDK cités sont :`,
    choices: [
      `cdc25.`,
      `CAK.`,
      `p16.`,
      `p21.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `p16 et p21 sont des inhibiteurs de CDK.`,
    choiceExplanations: [
      `Exact. p16 et p21 sont des inhibiteurs de CDK.`,
      `Exact. p16 et p21 sont des inhibiteurs de CDK.`,
      `Faux. p16 et p21 sont des inhibiteurs de CDK.`,
      `Faux. p16 et p21 sont des inhibiteurs de CDK.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les régulateurs négatifs des complexes cycline/CDK comprennent :`,
    choices: [
      `p16.`,
      `p21.`,
      `Wee1.`,
      `Myc activé par un facteur de croissance.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Myc favorise l’expression de cycline D et donc l’entrée en G1.`,
    choiceExplanations: [
      `Exact. Myc favorise l’expression de cycline D et donc l’entrée en G1.`,
      `Exact. Myc favorise l’expression de cycline D et donc l’entrée en G1.`,
      `Exact. Myc favorise l’expression de cycline D et donc l’entrée en G1.`,
      `Faux. Myc favorise l’expression de cycline D et donc l’entrée en G1.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le point de restriction G1 est un point de non-retour car :`,
    choices: [
      `Après son franchissement, la cellule termine son cycle même sans facteurs de croissance.`,
      `Avant son franchissement, une privation de facteurs de croissance favorise G0.`,
      `Il se situe après la mitose et avant S.`,
      `Il déclenche directement l’anaphase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le point métaphasique, non le point G1, contrôle l’anaphase.`,
    choiceExplanations: [
      `Exact. Le point métaphasique, non le point G1, contrôle l’anaphase.`,
      `Exact. Le point métaphasique, non le point G1, contrôle l’anaphase.`,
      `Exact. Le point métaphasique, non le point G1, contrôle l’anaphase.`,
      `Faux. Le point métaphasique, non le point G1, contrôle l’anaphase.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une cellule en G2 avec réplication inachevée :`,
    choices: [
      `Doit bloquer l’entrée en mitose.`,
      `Peut inhiber cdc25 et CAK.`,
      `Peut activer Wee1.`,
      `Doit activer immédiatement APC/cdc20.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `APC/cdc20 intervient au point de contrôle métaphasique.`,
    choiceExplanations: [
      `Exact. APC/cdc20 intervient au point de contrôle métaphasique.`,
      `Exact. APC/cdc20 intervient au point de contrôle métaphasique.`,
      `Exact. APC/cdc20 intervient au point de contrôle métaphasique.`,
      `Faux. APC/cdc20 intervient au point de contrôle métaphasique.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les complexes APC/C :`,
    choices: [
      `Contiennent une activité E3 ubiquitine ligase.`,
      `Permettent l’ubiquitination de protéines cibles.`,
      `Favorisent leur dégradation par le protéasome.`,
      `Sont des récepteurs aux facteurs de croissance.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `APC/C régule la mitose par ubiquitination de cibles comme la sécurine ou la cycline B.`,
    choiceExplanations: [
      `Exact. APC/C régule la mitose par ubiquitination de cibles comme la sécurine ou la cycline B.`,
      `Exact. APC/C régule la mitose par ubiquitination de cibles comme la sécurine ou la cycline B.`,
      `Exact. APC/C régule la mitose par ubiquitination de cibles comme la sécurine ou la cycline B.`,
      `Faux. APC/C régule la mitose par ubiquitination de cibles comme la sécurine ou la cycline B.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un défaut d’attachement d’un chromosome en métaphase :`,
    choices: [
      `Inhibe APC/cdc20.`,
      `Empêche la séparation des chromatides.`,
      `Maintient la cellule en métaphase.`,
      `Active immédiatement la séparase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La séparase reste inactive tant que la sécurine n’est pas détruite.`,
    choiceExplanations: [
      `Exact. La séparase reste inactive tant que la sécurine n’est pas détruite.`,
      `Exact. La séparase reste inactive tant que la sécurine n’est pas détruite.`,
      `Exact. La séparase reste inactive tant que la sécurine n’est pas détruite.`,
      `Faux. La séparase reste inactive tant que la sécurine n’est pas détruite.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule privée de facteurs de croissance en G1 précoce :`,
    choices: [
      `Peut ne pas franchir le point de restriction.`,
      `Peut entrer en G0.`,
      `A déjà forcément activé E/CDK2.`,
      `Peut reprendre le cycle si les facteurs de croissance sont réintroduits.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le cours présente une quiescence réversible dépendante des signaux externes.`,
    choiceExplanations: [
      `Exact. Le cours présente une quiescence réversible dépendante des signaux externes.`,
      `Exact. Le cours présente une quiescence réversible dépendante des signaux externes.`,
      `Faux. Le cours présente une quiescence réversible dépendante des signaux externes.`,
      `Exact. Le cours présente une quiescence réversible dépendante des signaux externes.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation rendant p16 inactive pourrait :`,
    choices: [
      `Réduire un frein au complexe D/CDK4-6.`,
      `Diminuer l’arrêt en G1 face à une anomalie de l’ADN.`,
      `Renforcer nécessairement l’apoptose.`,
      `Favoriser une progression inappropriée dans le cycle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `p16 est un inhibiteur important du point de contrôle G1.`,
    choiceExplanations: [
      `Exact. p16 est un inhibiteur important du point de contrôle G1.`,
      `Exact. p16 est un inhibiteur important du point de contrôle G1.`,
      `Faux. p16 est un inhibiteur important du point de contrôle G1.`,
      `Exact. p16 est un inhibiteur important du point de contrôle G1.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une perte de fonction de p53 pourrait :`,
    choices: [
      `Réduire l’induction de p21.`,
      `Affaiblir le blocage G1-S après dommage de l’ADN.`,
      `Renforcer automatiquement la réparation de l’ADN.`,
      `Contribuer à une prolifération non contrôlée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `p53 est un suppresseur de tumeur favorisant l’arrêt du cycle via p21.`,
    choiceExplanations: [
      `Exact. p53 est un suppresseur de tumeur favorisant l’arrêt du cycle via p21.`,
      `Exact. p53 est un suppresseur de tumeur favorisant l’arrêt du cycle via p21.`,
      `Faux. p53 est un suppresseur de tumeur favorisant l’arrêt du cycle via p21.`,
      `Exact. p53 est un suppresseur de tumeur favorisant l’arrêt du cycle via p21.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une activation constitutive de cdc25 en G2 pourrait :`,
    choices: [
      `Favoriser l’activation de B/CDK1.`,
      `Permettre une entrée en mitose malgré des signaux défavorables.`,
      `Renforcer l’effet inhibiteur de Wee1.`,
      `Compromettre le contrôle de l’intégrité du génome.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `cdc25 active le MPF ; son activation non contrôlée peut contourner le checkpoint G2.`,
    choiceExplanations: [
      `Exact. cdc25 active le MPF ; son activation non contrôlée peut contourner le checkpoint G2.`,
      `Exact. cdc25 active le MPF ; son activation non contrôlée peut contourner le checkpoint G2.`,
      `Faux. cdc25 active le MPF ; son activation non contrôlée peut contourner le checkpoint G2.`,
      `Exact. cdc25 active le MPF ; son activation non contrôlée peut contourner le checkpoint G2.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une activation excessive de Wee1 :`,
    choices: [
      `Maintient B/CDK1 inhibé.`,
      `Peut prolonger la phase G2.`,
      `Déclenche directement l’anaphase.`,
      `S’oppose à l’entrée en mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Wee1 est une kinase inhibitrice du complexe cycline B/CDK1.`,
    choiceExplanations: [
      `Exact. Wee1 est une kinase inhibitrice du complexe cycline B/CDK1.`,
      `Exact. Wee1 est une kinase inhibitrice du complexe cycline B/CDK1.`,
      `Faux. Wee1 est une kinase inhibitrice du complexe cycline B/CDK1.`,
      `Exact. Wee1 est une kinase inhibitrice du complexe cycline B/CDK1.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’expérience de réduction cytoplasmique chez l’amibe indique que :`,
    choices: [
      `Le volume cellulaire participe au contrôle de division.`,
      `Une cellule trop petite peut ne plus se diviser.`,
      `Le contrôle G1 ne dépend que de l’ADN.`,
      `La taille cellulaire est un paramètre du point de restriction.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le point G1 intègre aussi bien l’environnement, le volume et l’état de l’ADN.`,
    choiceExplanations: [
      `Exact. Le point G1 intègre aussi bien l’environnement, le volume et l’état de l’ADN.`,
      `Exact. Le point G1 intègre aussi bien l’environnement, le volume et l’état de l’ADN.`,
      `Faux. Le point G1 intègre aussi bien l’environnement, le volume et l’état de l’ADN.`,
      `Exact. Le point G1 intègre aussi bien l’environnement, le volume et l’état de l’ADN.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule avec ADN lésé en G1 peut activer successivement :`,
    choices: [
      `Une voie rapide inhibant cdc25.`,
      `Une voie plus longue p53-p21.`,
      `Un blocage des complexes E/CDK2 et A/CDK2.`,
      `Une activation obligatoire du MPF.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le MPF intervient à G2-M et doit être évité si le génome est lésé.`,
    choiceExplanations: [
      `Exact. Le MPF intervient à G2-M et doit être évité si le génome est lésé.`,
      `Exact. Le MPF intervient à G2-M et doit être évité si le génome est lésé.`,
      `Exact. Le MPF intervient à G2-M et doit être évité si le génome est lésé.`,
      `Faux. Le MPF intervient à G2-M et doit être évité si le génome est lésé.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les trois points de contrôle ont en commun :`,
    choices: [
      `D’interrompre la progression si une condition essentielle n’est pas remplie.`,
      `De protéger l’intégrité de la division.`,
      `De dépendre exclusivement de p53.`,
      `De réguler l’activité de complexes protéiques.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les régulateurs varient selon les checkpoints ; p53 n’est pas l’unique acteur.`,
    choiceExplanations: [
      `Exact. Les régulateurs varient selon les checkpoints ; p53 n’est pas l’unique acteur.`,
      `Exact. Les régulateurs varient selon les checkpoints ; p53 n’est pas l’unique acteur.`,
      `Faux. Les régulateurs varient selon les checkpoints ; p53 n’est pas l’unique acteur.`,
      `Exact. Les régulateurs varient selon les checkpoints ; p53 n’est pas l’unique acteur.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le passage métaphase-anaphase est conditionné par :`,
    choices: [
      `La bi-orientation de tous les chromosomes.`,
      `L’activation d’APC/cdc20.`,
      `La destruction de la sécurine.`,
      `La conservation intacte des cohésines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cohésines doivent être clivées par la séparase pour permettre l’anaphase.`,
    choiceExplanations: [
      `Exact. Les cohésines doivent être clivées par la séparase pour permettre l’anaphase.`,
      `Exact. Les cohésines doivent être clivées par la séparase pour permettre l’anaphase.`,
      `Exact. Les cohésines doivent être clivées par la séparase pour permettre l’anaphase.`,
      `Faux. Les cohésines doivent être clivées par la séparase pour permettre l’anaphase.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `Les checkpoints empêchent une progression prématurée.`,
      `G1 vérifie notamment environnement, taille et ADN.`,
      `G2 vérifie réplication et intégrité de l’ADN.`,
      `Le point métaphasique vérifie l’attachement au fuseau.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les trois checkpoints surveillent des étapes complémentaires du cycle.`,
    choiceExplanations: [
      `Exact. Les trois checkpoints surveillent des étapes complémentaires du cycle.`,
      `Exact. Les trois checkpoints surveillent des étapes complémentaires du cycle.`,
      `Exact. Les trois checkpoints surveillent des étapes complémentaires du cycle.`,
      `Exact. Les trois checkpoints surveillent des étapes complémentaires du cycle.`,
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: `points-de-controle-g1-g2-m`,
    title: `Points de contrôle G1, G2 et mitotique`,
    description: `Conditions vérifiées et conséquences d’un arrêt du cycle.`,
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: `regulateurs-des-checkpoints`,
    title: `Régulateurs des points de contrôle`,
    description: `p16, p53, p21, cdc25, CAK, Wee1 et APC/C.`,
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 9,
    slug: `defaillances-des-points-de-controle`,
    title: `Défaillances des points de contrôle`,
    description: `Raisonnement sur les anomalies de régulation et leurs conséquences.`,
    stage: 'MASTER',
    sectionOrder: 3,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];
