/** UE14 – Biologie cellulaire – Chapitre 8 : Le noyau */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-noyau.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-noyau.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-noyau.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-noyau.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-noyau.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';

const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'noyau';

const sections: SeedSection[] = [
  { order: 1, title: `Organisation générale et enveloppe nucléaire`, description: `Caractéristiques, fonctions, morphologie, mitose et anatomopathologie.`, kind: 'THEME' },
  { order: 2, title: `Échanges nucléocytoplasmiques`, description: `Nucléoplasmine, signal NLS, structure des pores et transports passifs ou actifs.`, kind: 'THEME' },
  { order: 3, title: `Matrice nucléaire et organisation de la chromatine`, description: `Lamina, NuMA, LAD, MAR, nucléosomes, compaction et territoires chromosomiques.`, kind: 'THEME' },
  { order: 4, title: `Activité de la chromatine et nucléole`, description: `Euchromatine, hétérochromatine, ARNr et biogenèse ribosomale.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Consolidation transversale et raisonnement expérimental.`, kind: 'SYNTHESIS' },
];

const questions: SeedQuestion[] = [
  ...SECTION_A_QUESTIONS, ...SECTION_B_QUESTIONS, ...SECTION_C_QUESTIONS, ...SECTION_D_QUESTIONS, ...SYNTHESIS_QUESTIONS,
];
const quizSeeds: SeedQuiz[] = [
  ...SECTION_A_QUIZZES, ...SECTION_B_QUIZZES, ...SECTION_C_QUIZZES, ...SECTION_D_QUIZZES, ...SYNTHESIS_QUIZZES,
];

const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Organisation et enveloppe`],
  2: [`Organisation et enveloppe`],
  3: [`Organisation et enveloppe`],
  4: [`Organisation et enveloppe`],
  5: [`Organisation et enveloppe`],
  6: [`Organisation et enveloppe`],
  7: [`Organisation et enveloppe`],
  8: [`Organisation et enveloppe`],
  9: [`Organisation et enveloppe`],
  10: [`Organisation et enveloppe`],
  11: [`Organisation et enveloppe`],
  12: [`Organisation et enveloppe`],
  13: [`Organisation et enveloppe`],
  14: [`Organisation et enveloppe`],
  15: [`Organisation et enveloppe`],
  16: [`Organisation et enveloppe`],
  17: [`Organisation et enveloppe`],
  18: [`Organisation et enveloppe`],
  19: [`Organisation et enveloppe`],
  20: [`Organisation et enveloppe`],
  21: [`Organisation et enveloppe`],
  22: [`Organisation et enveloppe`],
  23: [`Organisation et enveloppe`],
  24: [`Organisation et enveloppe`],
  25: [`Organisation et enveloppe`],
  26: [`Organisation et enveloppe`],
  27: [`Organisation et enveloppe`],
  28: [`Organisation et enveloppe`],
  29: [`Organisation et enveloppe`],
  30: [`Organisation et enveloppe`],
  31: [`Échanges nucléocytoplasmiques`],
  32: [`Échanges nucléocytoplasmiques`],
  33: [`Échanges nucléocytoplasmiques`],
  34: [`Échanges nucléocytoplasmiques`],
  35: [`Échanges nucléocytoplasmiques`],
  36: [`Échanges nucléocytoplasmiques`],
  37: [`Échanges nucléocytoplasmiques`],
  38: [`Échanges nucléocytoplasmiques`],
  39: [`Échanges nucléocytoplasmiques`],
  40: [`Échanges nucléocytoplasmiques`],
  41: [`Échanges nucléocytoplasmiques`],
  42: [`Échanges nucléocytoplasmiques`],
  43: [`Échanges nucléocytoplasmiques`],
  44: [`Échanges nucléocytoplasmiques`],
  45: [`Échanges nucléocytoplasmiques`],
  46: [`Échanges nucléocytoplasmiques`],
  47: [`Échanges nucléocytoplasmiques`],
  48: [`Échanges nucléocytoplasmiques`],
  49: [`Échanges nucléocytoplasmiques`],
  50: [`Échanges nucléocytoplasmiques`],
  51: [`Échanges nucléocytoplasmiques`],
  52: [`Échanges nucléocytoplasmiques`],
  53: [`Échanges nucléocytoplasmiques`],
  54: [`Échanges nucléocytoplasmiques`],
  55: [`Échanges nucléocytoplasmiques`],
  56: [`Échanges nucléocytoplasmiques`],
  57: [`Échanges nucléocytoplasmiques`],
  58: [`Échanges nucléocytoplasmiques`],
  59: [`Échanges nucléocytoplasmiques`],
  60: [`Échanges nucléocytoplasmiques`],
  61: [`Matrice et chromatine`],
  62: [`Matrice et chromatine`],
  63: [`Matrice et chromatine`],
  64: [`Matrice et chromatine`],
  65: [`Matrice et chromatine`],
  66: [`Matrice et chromatine`],
  67: [`Matrice et chromatine`],
  68: [`Matrice et chromatine`],
  69: [`Matrice et chromatine`],
  70: [`Matrice et chromatine`],
  71: [`Matrice et chromatine`],
  72: [`Matrice et chromatine`],
  73: [`Matrice et chromatine`],
  74: [`Matrice et chromatine`],
  75: [`Matrice et chromatine`],
  76: [`Matrice et chromatine`],
  77: [`Matrice et chromatine`],
  78: [`Matrice et chromatine`],
  79: [`Matrice et chromatine`],
  80: [`Matrice et chromatine`],
  81: [`Matrice et chromatine`],
  82: [`Matrice et chromatine`],
  83: [`Matrice et chromatine`],
  84: [`Matrice et chromatine`],
  85: [`Matrice et chromatine`],
  86: [`Matrice et chromatine`],
  87: [`Matrice et chromatine`],
  88: [`Matrice et chromatine`],
  89: [`Matrice et chromatine`],
  90: [`Matrice et chromatine`],
  91: [`Chromatine active et nucléole`],
  92: [`Chromatine active et nucléole`],
  93: [`Chromatine active et nucléole`],
  94: [`Chromatine active et nucléole`],
  95: [`Chromatine active et nucléole`],
  96: [`Chromatine active et nucléole`],
  97: [`Chromatine active et nucléole`],
  98: [`Chromatine active et nucléole`],
  99: [`Chromatine active et nucléole`],
  100: [`Chromatine active et nucléole`],
  101: [`Chromatine active et nucléole`],
  102: [`Chromatine active et nucléole`],
  103: [`Chromatine active et nucléole`],
  104: [`Chromatine active et nucléole`],
  105: [`Chromatine active et nucléole`],
  106: [`Chromatine active et nucléole`],
  107: [`Chromatine active et nucléole`],
  108: [`Chromatine active et nucléole`],
  109: [`Chromatine active et nucléole`],
  110: [`Chromatine active et nucléole`],
  111: [`Chromatine active et nucléole`],
  112: [`Chromatine active et nucléole`],
  113: [`Chromatine active et nucléole`],
  114: [`Chromatine active et nucléole`],
  115: [`Chromatine active et nucléole`],
  116: [`Chromatine active et nucléole`],
  117: [`Chromatine active et nucléole`],
  118: [`Chromatine active et nucléole`],
  119: [`Chromatine active et nucléole`],
  120: [`Chromatine active et nucléole`],
  121: [`Synthèse du noyau`],
  122: [`Synthèse du noyau`],
  123: [`Synthèse du noyau`],
  124: [`Synthèse du noyau`],
  125: [`Synthèse du noyau`],
  126: [`Synthèse du noyau`],
  127: [`Synthèse du noyau`],
  128: [`Synthèse du noyau`],
  129: [`Synthèse du noyau`],
  130: [`Synthèse du noyau`],
  131: [`Synthèse du noyau`],
  132: [`Synthèse du noyau`],
  133: [`Synthèse du noyau`],
  134: [`Synthèse du noyau`],
  135: [`Synthèse du noyau`],
  136: [`Synthèse du noyau`],
  137: [`Synthèse du noyau`],
  138: [`Synthèse du noyau`],
  139: [`Synthèse du noyau`],
  140: [`Synthèse du noyau`],
};

export async function seedHealthTrainingUe14BiologieCellulaireNoyau(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 8',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
  });
}
