/**
 * Cartographie éditoriale V2 — auteur.
 * Les stages décrivent la progression pédagogique, jamais un chronométrage.
 */

export const UE14_BIOCH_CH4_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-definition-classification-lipides",
    "title": "Lipides et acides gras : définitions",
    "description": "Définition des lipides, structure générale des acides gras, pôles et critères de classification.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-structure-numerotation-acides-gras",
    "title": "Structure et numérotation des acides gras",
    "description": "Applications sur pôles hydrophile/hydrophobe, C1, carbone α et carbone ω.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-acides-gras-satures",
    "title": "Acides gras saturés",
    "description": "Repères sur nombres de carbones, palmitique, stéarique et classes de longueur.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-longueurs-nomenclature-satures",
    "title": "Longueur de chaîne et acides gras saturés",
    "description": "Applications de nomenclature et de classification des chaînes saturées.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-acides-gras-desatures",
    "title": "Acides gras désaturés",
    "description": "Repères sur cis/trans, positions Δ, séries ω et acides gras de référence.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-delta-omega-acides-gras-essentiels",
    "title": "Nomenclature Δ/ω et acides gras indispensables",
    "description": "Applications sur oléique, palmitoléique, linoléique, linolénique et l’indispensabilité alimentaire.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 3,
    "order": 3,
    "slug": "section-c-master-nomenclature-desaturation",
    "title": "Nomenclature et désaturation",
    "description": "Maîtrise du passage entre notations Δ et ω et identification des acides gras désaturés.",
    "stage": "MASTER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76,
      77,
      78
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-proprietes-acides-gras",
    "title": "Propriétés des acides gras",
    "description": "Repères sur densité, solubilité, point de fusion, estérification et rôles biologiques.",
    "stage": "DISCOVER",
    "questionOrders": [
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-proprietes-roles-trans",
    "title": "Propriétés, rôles et acides gras trans",
    "description": "Applications sur solubilité, point de fusion, membranes, énergie et informations santé du support.",
    "stage": "PRACTICE",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-lipides-acides-gras",
    "title": "Lipides et acides gras",
    "description": "Synthèse appliquée des structures, nomenclatures, propriétés et rôles.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-lipides-acides-gras",
    "title": "Lipides et acides gras",
    "description": "Maîtrise transversale du chapitre dans l’esprit de l’examen, sans constituer un examen blanc.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH4_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Lipides et acides gras : repères"],
  2: ["Lipides et acides gras : repères"],
  3: ["Lipides et acides gras : repères"],
  4: ["Lipides et acides gras : repères"],
  5: ["Lipides et acides gras : repères"],
  6: ["Lipides et acides gras : repères"],
  7: ["Lipides et acides gras : repères"],
  8: ["Lipides et acides gras : repères"],
  9: ["Lipides et acides gras : repères"],
  10: ["Lipides et acides gras : repères"],
  11: ["Structure et numérotation : applications"],
  12: ["Structure et numérotation : applications"],
  13: ["Structure et numérotation : applications"],
  14: ["Structure et numérotation : applications"],
  15: ["Structure et numérotation : applications"],
  16: ["Structure et numérotation : applications"],
  17: ["Structure et numérotation : applications"],
  18: ["Structure et numérotation : applications"],
  19: ["Structure et numérotation : applications"],
  20: ["Structure et numérotation : applications"],
  21: ["Structure et numérotation : applications"],
  22: ["Structure et numérotation : applications"],
  23: ["Acides gras saturés : repères"],
  24: ["Acides gras saturés : repères"],
  25: ["Acides gras saturés : repères"],
  26: ["Acides gras saturés : repères"],
  27: ["Acides gras saturés : repères"],
  28: ["Acide undécylénique et cuir chevelu"],
  29: ["Acides gras saturés : repères"],
  30: ["Acides gras saturés : repères"],
  31: ["Acides gras saturés : repères"],
  32: ["Acides gras saturés : repères"],
  33: ["Saturés et longueurs : applications"],
  34: ["Saturés et longueurs : applications"],
  35: ["Saturés et longueurs : applications"],
  36: ["Saturés et longueurs : applications"],
  37: ["Saturés et longueurs : applications"],
  38: ["Saturés et longueurs : applications"],
  39: ["Saturés et longueurs : applications"],
  40: ["Saturés et longueurs : applications"],
  41: ["Saturés et longueurs : applications"],
  42: ["Saturés et longueurs : applications"],
  43: ["Saturés et longueurs : applications"],
  44: ["Saturés et longueurs : applications"],
  45: ["Acides gras désaturés : repères"],
  46: ["Acides gras désaturés : repères"],
  47: ["Acides gras désaturés : repères"],
  48: ["Acides gras désaturés : repères"],
  49: ["Acides gras désaturés : repères"],
  50: ["Acides gras désaturés : repères"],
  51: ["Acides gras désaturés : repères"],
  52: ["Acides gras désaturés : repères"],
  53: ["Acides gras désaturés : repères"],
  54: ["Acides gras indispensables"],
  55: ["Nomenclature Δ/ω : applications"],
  56: ["Nomenclature Δ/ω : applications"],
  57: ["Nomenclature Δ/ω : applications"],
  58: ["Nomenclature Δ/ω : applications"],
  59: ["Nomenclature Δ/ω : applications"],
  60: ["Nomenclature Δ/ω : applications"],
  61: ["Nomenclature Δ/ω : applications"],
  62: ["Nomenclature Δ/ω : applications"],
  63: ["Acides gras indispensables : alimentation"],
  64: ["Nomenclature Δ/ω : applications"],
  65: ["QZONE : double liaison Δ9"],
  66: ["Nomenclature Δ/ω : applications"],
  67: ["Désaturation : maîtrise"],
  68: ["Désaturation : maîtrise"],
  69: ["Désaturation : maîtrise"],
  70: ["Désaturation : maîtrise"],
  71: ["Désaturation : maîtrise"],
  72: ["Désaturation : maîtrise"],
  73: ["Désaturation : maîtrise"],
  74: ["Désaturation : maîtrise"],
  75: ["Nutrition : linoléique/linolénique"],
  76: ["Désaturation : maîtrise"],
  77: ["Désaturation : maîtrise"],
  78: ["Désaturation : maîtrise"],
  79: ["Propriétés des acides gras : repères"],
  80: ["Propriétés des acides gras : repères"],
  81: ["Propriétés des acides gras : repères"],
  82: ["Propriétés des acides gras : repères"],
  83: ["Propriétés des acides gras : repères"],
  84: ["Propriétés des acides gras : repères"],
  85: ["Propriétés des acides gras : repères"],
  86: ["Propriétés des acides gras : repères"],
  87: ["Acides gras trans : information santé du support"],
  88: ["Propriétés des acides gras : repères"],
  89: ["Propriétés et rôles : applications"],
  90: ["Propriétés et rôles : applications"],
  91: ["Propriétés et rôles : applications"],
  92: ["Propriétés et rôles : applications"],
  93: ["Propriétés et rôles : applications"],
  94: ["Propriétés et rôles : applications"],
  95: ["Rôle structural membranaire"],
  96: ["Propriétés et rôles : applications"],
  97: ["Propriétés et rôles : applications"],
  98: ["Acides gras trans : prudence éditoriale"],
  99: ["Propriétés et rôles : applications"],
  100: ["Propriétés et rôles : applications"],
  101: ["Synthèse lipides/acides gras"],
  102: ["Synthèse lipides/acides gras"],
  103: ["Synthèse lipides/acides gras"],
  104: ["Synthèse lipides/acides gras"],
  105: ["Acides gras indispensables : contexte nutritionnel"],
  106: ["Synthèse lipides/acides gras"],
  107: ["Synthèse lipides/acides gras"],
  108: ["Synthèse lipides/acides gras"],
  109: ["Synthèse lipides/acides gras"],
  110: ["Synthèse lipides/acides gras"],
  111: ["Maîtrise transversale lipides/acides gras"],
  112: ["Maîtrise transversale lipides/acides gras"],
  113: ["Maîtrise transversale lipides/acides gras"],
  114: ["Maîtrise transversale lipides/acides gras"],
  115: ["Maîtrise transversale lipides/acides gras"],
  116: ["Acides gras trans : contexte santé du support"],
  117: ["Maîtrise transversale lipides/acides gras"],
  118: ["Maîtrise transversale lipides/acides gras"],
  119: ["Maîtrise transversale lipides/acides gras"],
  120: ["Maîtrise transversale lipides/acides gras"],
  121: ["Maîtrise transversale lipides/acides gras"],
  122: ["Maîtrise transversale lipides/acides gras"],
};
