/**
 * Cartographie éditoriale V2
 * UE14 – Biochimie – Chapitre 1.1
 * Les glucides : généralités et structure
 */

export const UE14_BIOCH_CH1_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'section-a-discovery-generalites-structure-oses',
    title: `Généralités, structure et nomenclature des oses`,
    description: `Repères sur les rôles des glucides, leur structure générale, les aldoses/cétoses et la nomenclature selon le nombre de carbones.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'section-a-practice-classification-nomenclature-oses',
    title: `Généralités, structure et nomenclature des oses`,
    description: `Applications sur la lecture des fonctions, la numérotation, les formules générales et la classification des oses.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,21,22],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'section-b-discovery-chiralite-series-d-l',
    title: `Chiralité, représentations et filiation`,
    description: `Repères sur les carbones asymétriques, le glycéraldéhyde, les projections de Newman/Fischer et les séries D/L.`,
    stage: 'DISCOVER' as const,
    questionOrders: [23,24,25,26,27,28,29,30,31,32],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'section-b-practice-fischer-filiation-stereoisomeres',
    title: `Chiralité, représentations et filiation`,
    description: `Applications sur la lecture de Fischer, les exceptions biologiques de série L et le calcul des stéréoisomères d'aldoses et cétoses.`,
    stage: 'PRACTICE' as const,
    questionOrders: [33,34,35,36,37,38,39,40,41,42,43,44],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'section-c-discovery-isomerie-enantiomerie-epimerie',
    title: `Isomérie, énantiomérie et épimérie`,
    description: `Repères sur isomères de fonction, stéréoisomères, énantiomères, diastéréoisomères et épimères.`,
    stage: 'DISCOVER' as const,
    questionOrders: [45,46,47,48,49,50,51,52,53,54],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'section-c-practice-epimeres-epimerisation',
    title: `Isomérie, énantiomérie et épimérie`,
    description: `Applications sur les épimères du glucose, l'épimérisation enzymatique et la galactosémie par déficit en UDP-galactose 4-épimérase.`,
    stage: 'PRACTICE' as const,
    questionOrders: [55,56,57,58,59,60,61,62,63,64,65,66],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'section-d-discovery-cyclisation-anomeres',
    title: `Cyclisation, interconversion et pouvoir rotatoire`,
    description: `Repères sur pyranoses/furanoses, cyclisation du glucose, conformations et naissance du carbone anomérique.`,
    stage: 'DISCOVER' as const,
    questionOrders: [67,68,69,70,71,72,73,74,75,76],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'section-d-practice-interconversion-conformations',
    title: `Cyclisation, interconversion et pouvoir rotatoire`,
    description: `Applications sur les anomères, la cyclisation du fructose, les équilibres de formes et les notions de dextro-/lévogyre.`,
    stage: 'PRACTICE' as const,
    questionOrders: [77,78,79,80,81,82,83,84,85,86,87,88],
  },
  {
    sectionOrder: 4,
    order: 3,
    slug: 'section-d-master-pouvoir-rotatoire-mutarotation',
    title: `Cyclisation, interconversion et pouvoir rotatoire`,
    description: `Maîtrise des carbones anomériques, de la mutarotation, des équilibres de formes et des calculs simples de pouvoir rotatoire.`,
    stage: 'MASTER' as const,
    questionOrders: [89,90,91,92,93,94,95,96,97,98,99,100],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'section-e-synthesis-practice-glucides',
    title: `Glucides : généralités et structure`,
    description: `Synthèse appliquée croisant structure, classification, filiation, stéréochimie, cyclisation et pouvoir rotatoire.`,
    stage: 'PRACTICE' as const,
    questionOrders: [101,102,103,104,105,106,107,108,109,110],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'maitriser-synthese-glucides-generalites-structure',
    title: `Glucides : généralités et structure`,
    description: `Maîtrise transversale du chapitre dans des situations proches de l'examen, sans transformer le quiz en examen blanc.`,
    stage: 'MASTER' as const,
    questionOrders: [111,112,113,114,115,116,117,118,119,120,121,122],
  },
] as const;

export const UE14_BIOCH_CH1_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Glucides : généralités et structure`],
  2: [`Glucides : généralités et structure`],
  3: [`Énergie fournie par les macronutriments`],
  4: [`Glucides : généralités et structure`],
  5: [`Glucides : généralités et structure`],
  6: [`Glucides : généralités et structure`],
  7: [`Pathologies liées aux glucides`],
  8: [`Intolérance au lactose vs allergie au lait`],
  9: [`Glucides : généralités et structure`],
  10: [`Glucides : généralités et structure`],
  11: [`Oses : classification et nomenclature`],
  12: [`Oses : classification et nomenclature`],
  13: [`Oses : classification et nomenclature`],
  14: [`Formule générale des aldoses`],
  15: [`Formule générale des cétoses`],
  16: [`Oses : classification et nomenclature`],
  17: [`Oses : classification et nomenclature`],
  18: [`Oses : classification et nomenclature`],
  19: [`Oses : classification et nomenclature`],
  20: [`Oses : classification et nomenclature`],
  21: [`Oses : classification et nomenclature`],
  22: [`Structure et nomenclature : QRPL`],
  23: [`Chiralité et séries D/L`],
  24: [`Glycéraldéhyde : chiralité`],
  25: [`Dihydroxyacétone : achiralité`],
  26: [`Chiralité et séries D/L`],
  27: [`Priorités autour du C*`],
  28: [`Chiralité et séries D/L`],
  29: [`Chiralité et séries D/L`],
  30: [`Fischer : séries D/L`],
  31: [`Chiralité et séries D/L`],
  32: [`Séries D/L : répartition biologique`],
  33: [`Fischer, filiation et stéréoisomères`],
  34: [`Fischer, filiation et stéréoisomères`],
  35: [`Fischer, filiation et stéréoisomères`],
  36: [`Fischer, filiation et stéréoisomères`],
  37: [`Fischer, filiation et stéréoisomères`],
  38: [`Nombre de stéréoisomères`],
  39: [`Fischer, filiation et stéréoisomères`],
  40: [`Fischer, filiation et stéréoisomères`],
  41: [`Fischer, filiation et stéréoisomères`],
  42: [`QZONE : dernier carbone asymétrique`],
  43: [`Fischer, filiation et stéréoisomères`],
  44: [`Chiralité/filiation : QRPL`],
  45: [`Isomérie, énantiomérie et épimérie : repères`],
  46: [`Glycéraldéhyde vs dihydroxyacétone`],
  47: [`Isomérie, énantiomérie et épimérie : repères`],
  48: [`Isomérie, énantiomérie et épimérie : repères`],
  49: [`Isomérie, énantiomérie et épimérie : repères`],
  50: [`Isomérie, énantiomérie et épimérie : repères`],
  51: [`Isomérie, énantiomérie et épimérie : repères`],
  52: [`Isomérie, énantiomérie et épimérie : repères`],
  53: [`Glucose/galactose : épimérie C4`],
  54: [`Glucose/mannose : épimérie C2`],
  55: [`Épimères, épimérisation et galactosémie`],
  56: [`Épimères, épimérisation et galactosémie`],
  57: [`Épimères, épimérisation et galactosémie`],
  58: [`Épimères, épimérisation et galactosémie`],
  59: [`Épimères, épimérisation et galactosémie`],
  60: [`Galactosémie et épimérase`],
  61: [`Épimères, épimérisation et galactosémie`],
  62: [`Épimères, épimérisation et galactosémie`],
  63: [`Épimères, épimérisation et galactosémie`],
  64: [`Épimères, épimérisation et galactosémie`],
  65: [`Épimères, épimérisation et galactosémie`],
  66: [`Isomérie : QRPL`],
  67: [`Cyclisation et anomères : repères`],
  68: [`Cyclisation et anomères : repères`],
  69: [`Cyclisation et anomères : repères`],
  70: [`D-glucose : cyclisation pyranique C1-C5`],
  71: [`D-glucose : forme furanique C1-C4`],
  72: [`Cyclisation et anomères : repères`],
  73: [`Naissance du carbone anomérique`],
  74: [`Cyclisation et anomères : repères`],
  75: [`Cyclisation et anomères : repères`],
  76: [`Cyclisation et anomères : repères`],
  77: [`Interconversion et pouvoir rotatoire : applications`],
  78: [`D-fructose : cyclisations`],
  79: [`Équilibre des formes à pH 7`],
  80: [`Oses réducteurs en milieu basique`],
  81: [`Interconversion et pouvoir rotatoire : applications`],
  82: [`Interconversion et pouvoir rotatoire : applications`],
  83: [`Interconversion et pouvoir rotatoire : applications`],
  84: [`Interconversion et pouvoir rotatoire : applications`],
  85: [`Interconversion et pouvoir rotatoire : applications`],
  86: [`Indépendance D/L et signe optique`],
  87: [`Rotation des anomères du glucose`],
  88: [`Mélange racémique D/L glucose`],
  89: [`QZONE : carbone anomérique du glucopyranose`],
  90: [`Cyclisation et pouvoir rotatoire : maîtrise`],
  91: [`Cyclisation et pouvoir rotatoire : maîtrise`],
  92: [`Cyclisation et pouvoir rotatoire : maîtrise`],
  93: [`Calcul : proportion β à pH 7`],
  94: [`Calcul : mélange racémique`],
  95: [`Calcul : mélange non racémique`],
  96: [`Cyclisation et pouvoir rotatoire : maîtrise`],
  97: [`Cyclisation et pouvoir rotatoire : maîtrise`],
  98: [`Cyclisation et pouvoir rotatoire : maîtrise`],
  99: [`Cyclisation et pouvoir rotatoire : maîtrise`],
  100: [`Cyclisation/pouvoir rotatoire : QRPL`],
  101: [`Synthèse appliquée des glucides`],
  102: [`Synthèse appliquée des glucides`],
  103: [`Synthèse appliquée des glucides`],
  104: [`Synthèse appliquée des glucides`],
  105: [`Synthèse appliquée des glucides`],
  106: [`Synthèse appliquée des glucides`],
  107: [`Synthèse appliquée des glucides`],
  108: [`Synthèse appliquée des glucides`],
  109: [`Galactosémie : application`],
  110: [`Synthèse PRACTICE : QRPL`],
  111: [`Maîtrise transversale des glucides`],
  112: [`Maîtrise transversale des glucides`],
  113: [`Maîtrise transversale des glucides`],
  114: [`Maîtrise transversale des glucides`],
  115: [`Maîtrise transversale des glucides`],
  116: [`Maîtrise transversale des glucides`],
  117: [`Pouvoir rotatoire : mélange racémique`],
  118: [`Équilibre β : calcul`],
  119: [`Maîtrise transversale des glucides`],
  120: [`Maîtrise transversale des glucides`],
  121: [`Maîtrise transversale des glucides`],
  122: [`Synthèse MASTER : QRPL`],
};
