import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_ORDER = 4;

export const SECTION_D_LEWIS_BASES_DISCOVERY_QUIZ_SLUG =
  `section-d-discovery-bases-nucleiques-nucleophilie`;
export const SECTION_D_NUCLEOSIDES_PRACTICE_QUIZ_SLUG =
  `section-d-practice-nucleosides-nucleotides`;
export const SECTION_D_TOXICOLOGY_MASTER_QUIZ_SLUG =
  `section-d-master-electrophiles-mutagenicite`;

export const SECTION_D_LEWIS_BASES_DISCOVERY_QUESTION_ORDERS: number[] = [91, 92, 93, 94, 95, 96, 97, 98, 99, 100];
export const SECTION_D_NUCLEOSIDES_PRACTICE_QUESTION_ORDERS: number[] = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110];
export const SECTION_D_TOXICOLOGY_MASTER_QUESTION_ORDERS: number[] = [111, 112, 113, 114, 115, 116, 117, 118, 119, 120];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: SECTION_D_LEWIS_BASES_DISCOVERY_QUIZ_SLUG,
    title: `Bases nucléiques : basicité et nucléophilie`,
    description: `Relier les doublets des atomes d'''azote et d'''oxygène au comportement de base de Lewis et de nucléophile.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_D_ORDER,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: SECTION_D_NUCLEOSIDES_PRACTICE_QUIZ_SLUG,
    title: `Bases, nucléosides et nucléotides`,
    description: `Distinguer base, nucléoside et nucléotide, puis associer ribose à l'''ARN et 2-désoxyribose à l'''ADN.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_D_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 101 },
      { type: 'QUESTION', questionOrder: 102 },
      { type: 'QUESTION', questionOrder: 103 },
      { type: 'QUESTION', questionOrder: 104 },
      { type: 'QUESTION', questionOrder: 105 },
      { type: 'QUESTION', questionOrder: 106 },
      { type: 'QUESTION', questionOrder: 107 },
      {
        type: 'GROUP',
        title: `Identifier une unité d'''acide nucléique`,
        sharedStatement: `On analyse une structure composée d'''une base azotée liée à un sucre, avec ou sans groupement phosphate.`,
        questionOrders: [108, 109, 110],
      },
    ],
  },
  {
    order: 12,
    slug: SECTION_D_TOXICOLOGY_MASTER_QUIZ_SLUG,
    title: `Électrophiles, bases nucléiques et mutagénicité`,
    description: `Comprendre comment certains dérivés halogénés peuvent modifier les bases nucléiques et produire des lésions mutagènes.`,
    stage: 'MASTER',
    sectionOrder: SECTION_D_ORDER,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la définition électronique du chapitre, une base :`,
    choices: [
      `Peut donner une paire d'électrons.`,
      `Peut agir comme nucléophile.`,
      `Doit toujours libérer un proton.`,
      `Est nécessairement dépourvue d'azote et d'oxygène.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le lien base de Lewis''�nucléophile est central pour comprendre la réactivité des bases nucléiques.`,
    choiceExplanations: [
      `C'est une base de Lewis.`,
      `Un nucléophile donne des électrons à un électrophile.`,
      `Cela définit un acide de Brønsted.`,
      `Ces hétéroatomes portent souvent les doublets donneurs.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la définition électronique du chapitre, un acide :`,
    choices: [
      `Peut capter une paire d'électrons.`,
      `Peut être qualifié d'électrophile.`,
      `Doit toujours porter une charge négative.`,
      `Donne toujours un doublet à une base.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Acide de Lewis et électrophile décrivent deux aspects du même comportement accepteur.`,
    choiceExplanations: [
      `C'est un acide de Lewis.`,
      `Il recherche une densité électronique.`,
      `Un électrophile est souvent neutre ou positif.`,
      `C'est la base qui donne le doublet.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les bases nucléiques contiennent fréquemment :`,
    choices: [
      `Des atomes d'azote.`,
      `Parfois des atomes d'oxygène.`,
      `Uniquement du carbone et de l'hydrogène.`,
      `Obligatoirement un atome de chlore.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les hétéroatomes riches en électrons expliquent une part de la réactivité des bases nucléiques.`,
    choiceExplanations: [
      `Leurs doublets participent à la basicité et à la nucléophilie.`,
      `La thymine en contient notamment.`,
      `Les hétéroatomes sont essentiels.`,
      `Le chlore n'est pas un constituant normal des bases montrées.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Pourquoi une base nucléique peut-elle agir comme nucléophile ?`,
    choices: [
      `Elle possède des doublets électroniques disponibles sur des hétéroatomes.`,
      `Elle peut attaquer un centre électrophile.`,
      `Elle ne contient aucun électron non liant.`,
      `Elle libère nécessairement du $\\mathrm{CO_2}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La structure électronique des atomes d'azote et d'oxygène rend possibles des réactions covalentes.`,
    choiceExplanations: [
      `Ces électrons peuvent être donnés.`,
      `C'est le comportement d'un nucléophile.`,
      `Les doublets non liants sont précisément impliqués.`,
      `Cela n'a aucun lien avec la nucléophilie.`,
    ],
  },
  {
    order: 95,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'adénine représentée dans le cours :`,
    choices: [
      `Est une base nucléique.`,
      `Contient plusieurs atomes d'azote.`,
      `Est un nucléotide complet à elle seule.`,
      `Est un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Une base isolée ne doit pas être confondue avec le nucléoside ou le nucléotide qui la contient.`,
    choiceExplanations: [
      `Elle appartient aux bases azotées.`,
      `Son hétérocycle est riche en azote.`,
      `Il lui manque un sucre et un phosphate.`,
      `Elle ne porte pas de groupe $\\mathrm{COOH}$.`,
    ],
  },
  {
    order: 96,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La thymine représentée dans le cours :`,
    choices: [
      `Est une base nucléique.`,
      `Contient des atomes d'azote et d'oxygène.`,
      `Est un dérivé halogéné très toxique.`,
      `Est un nucléoside complet.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'identification repose sur la distinction entre base, sucre et phosphate.`,
    choiceExplanations: [
      `Elle appartient aux bases pyrimidiques.`,
      `Sa structure possède ces hétéroatomes.`,
      `Aucun halogène n'est présent dans la structure montrée.`,
      `Aucun sucre n'est lié dans la base seule.`,
    ],
  },
  {
    order: 97,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le caractère nucléophile d'une base nucléique signifie qu'elle :`,
    choices: [
      `Peut former une liaison en donnant une paire d'électrons.`,
      `Réagit préférentiellement avec un électrophile.`,
      `Est nécessairement un acide de Lewis.`,
      `Ne peut subir aucune modification covalente.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Cette réactivité est physiologique dans certaines réactions, mais peut aussi être exploitée par des agents toxiques.`,
    choiceExplanations: [
      `C'est la définition opérationnelle.`,
      `Les caractères sont complémentaires.`,
      `Elle agit ici comme base de Lewis.`,
      `Elle peut justement être alkylée ou modifiée.`,
    ],
  },
  {
    order: 98,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans une interaction acide''�base de Lewis :`,
    choices: [
      `La base fournit les deux électrons de la nouvelle liaison.`,
      `L'acide accepte ce doublet.`,
      `Les rôles sont définis par un transfert obligatoire de proton.`,
      `Aucune liaison ne peut se former.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le modèle de Lewis étend l'acido-basicité au-delà des seules réactions protoniques.`,
    choiceExplanations: [
      `Le doublet provient du donneur.`,
      `Il possède un centre déficient en électrons.`,
      `La définition de Lewis n'exige pas de proton.`,
      `Une liaison de coordination ou covalente peut résulter de l'interaction.`,
    ],
  },
  {
    order: 99,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une base nucléique possède plusieurs atomes d'azote. Cela implique :`,
    choices: [
      `Que certains sites peuvent porter des doublets libres.`,
      `Que tous les azotes ont nécessairement exactement la même réactivité.`,
      `Que la molécule peut présenter plusieurs sites d'interaction.`,
      `Qu'elle est automatiquement un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `La réactivité réelle dépend de la disponibilité du doublet, de la mésomérie et de l'environnement moléculaire.`,
    choiceExplanations: [
      `Ces doublets sont des sites nucléophiles potentiels.`,
      `Leur environnement électronique diffère.`,
      `Les sites donneurs et accepteurs varient.`,
      `La présence d'azote ne crée pas de $\\mathrm{COOH}$.`,
    ],
  },
  {
    order: 100,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Comparer un acide carboxylique et une base nucléique dans le cadre du chapitre :`,
    choices: [
      `L'acide carboxylique peut donner un proton.`,
      `La base nucléique peut donner une paire d'électrons.`,
      `Ces deux dons concernent exactement la même particule.`,
      `Aucun des deux ne peut participer à une réaction chimique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Il faut savoir passer d'une définition protonique à une définition électronique selon la question posée.`,
    choiceExplanations: [
      `Comportement de Brønsted.`,
      `Comportement de Lewis.`,
      `L'un porte sur un proton, l'autre sur des électrons.`,
      `Ils sont définis par leur réactivité.`,
    ],
  },
  {
    order: 101,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un nucléoside est constitué :`,
    choices: [
      `D'une base nucléique.`,
      `D'un sucre.`,
      `Obligatoirement d'un phosphate.`,
      `Obligatoirement d'un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La distinction nucléoside/nucléotide repose principalement sur la présence du phosphate.`,
    choiceExplanations: [
      `La base est liée au sucre.`,
      `Ribose ou 2-désoxyribose selon la série.`,
      `Le phosphate transforme le nucléoside en nucléotide.`,
      `Aucun groupe $\\mathrm{COOH}$ n'est requis.`,
    ],
  },
  {
    order: 102,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un nucléotide comprend :`,
    choices: [
      `Une base nucléique.`,
      `Un sucre.`,
      `Au moins un groupement phosphate dans le modèle du cours.`,
      `Nécessairement une fonction $\\mathrm{COOH}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Base + sucre + phosphate forme l'unité nucléotidique des acides nucléiques.`,
    choiceExplanations: [
      `C'est la partie hétérocyclique.`,
      `Il relie la base au phosphate.`,
      `C'est la différence avec le nucléoside.`,
      `L'acidité provient du phosphate.`,
    ],
  },
  {
    order: 103,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le ribose est associé principalement :`,
    choices: [
      `�' la série ARN.`,
      `�' un groupe hydroxyle supplémentaire par rapport au 2-désoxyribose.`,
      `�' la série ADN exclusivement.`,
      `�' l'absence totale d'oxygène.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le préfixe « désoxy » indique précisément la perte d'un oxygène par rapport au ribose.`,
    choiceExplanations: [
      `Le cours le place à droite dans la comparaison.`,
      `Il porte un $\\mathrm{OH}$ en position 2'.`,
      `L'ADN utilise le 2-désoxyribose.`,
      `Le ribose contient plusieurs oxygènes.`,
    ],
  },
  {
    order: 104,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le 2-désoxyribose est associé principalement :`,
    choices: [
      `�' la série ADN.`,
      `�' l'absence de groupe $\\mathrm{OH}$ en position 2' par rapport au ribose.`,
      `�' la série ARN exclusivement.`,
      `�' une fonction acide carboxylique obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La différence structurale entre les deux sucres est petite mais essentielle à l'identité ADN/ARN.`,
    choiceExplanations: [
      `Il constitue le sucre de l'ADN.`,
      `Un hydrogène remplace ce groupe.`,
      `L'ARN contient du ribose.`,
      `Le sucre ne porte pas de $\\mathrm{COOH}$.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour passer d'une base nucléique à un nucléoside :`,
    choices: [
      `On ajoute une unité sucre.`,
      `Aucun phosphate n'est encore indispensable.`,
      `On doit éliminer tous les atomes d'azote.`,
      `On forme obligatoirement un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La progression conceptuelle est base '�� nucléoside '�� nucléotide.`,
    choiceExplanations: [
      `Une liaison glycosidique relie les deux parties.`,
      `Le composé reste un nucléoside.`,
      `La base est conservée.`,
      `Le groupement phosphate n'est même pas encore présent.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour passer d'un nucléoside à un nucléotide :`,
    choices: [
      `On ajoute un groupement phosphate.`,
      `La base et le sucre sont conservés.`,
      `On retire obligatoirement le sucre.`,
      `On transforme nécessairement l'azote en chlore.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La phosphorylation introduit le groupe responsable de l'acidité des nucléotides dans la fiche.`,
    choiceExplanations: [
      `Le phosphate distingue le nucléotide.`,
      `Ils constituent le nucléoside initial.`,
      `Il reste au centre de la structure.`,
      `Aucune halogénation n'est requise.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'acidité d'un nucléotide est attribuée principalement :`,
    choices: [
      `Au groupement phosphate.`,
      `�' une fonction carboxylate obligatoire.`,
      `�' la présence du sucre uniquement.`,
      `�' un atome de chlore.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le terme « acide nucléique » ne signifie pas que chaque unité porte une fonction carboxylique.`,
    choiceExplanations: [
      `Il peut porter ou libérer des protons et des charges négatives.`,
      `Les nucléotides n'ont pas besoin de $\\mathrm{COO^-}$.`,
      `Le sucre n'est pas le principal groupe acide indiqué.`,
      `Aucun chlore n'est requis.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparer carboxylate et phosphate :`,
    choices: [
      `Ils peuvent tous deux porter des charges négatives.`,
      `Ils contribuent à l'acidité et à la solubilité des molécules.`,
      `Ils sont chimiquement identiques.`,
      `Le phosphate ne contient aucun oxygène.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le cours propose une analogie fonctionnelle, pas une identité structurale.`,
    choiceExplanations: [
      `Leur déprotonation produit des anions.`,
      `Les charges influencent les propriétés en solution.`,
      `Leurs atomes centraux et leurs géométries diffèrent.`,
      `Il en contient plusieurs.`,
    ],
  },
  {
    order: 109,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une structure comprend une base liée à un ribose mais aucun phosphate. Il s'agit :`,
    choices: [
      `D'un nucléoside.`,
      `D'une unité de série ARN par la nature du sucre.`,
      `D'un nucléotide complet.`,
      `D'un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'analyse doit porter séparément sur la présence du sucre et celle du phosphate.`,
    choiceExplanations: [
      `Base + sucre suffit.`,
      `Le ribose est celui de l'ARN.`,
      `Il manque le phosphate.`,
      `Aucun carboxyle n'est indiqué.`,
    ],
  },
  {
    order: 110,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une structure comprend une base, un 2-désoxyribose et un phosphate. Elle :`,
    choices: [
      `Est un nucléotide.`,
      `Est compatible avec la série ADN.`,
      `Est un simple nucléoside.`,
      `Tire nécessairement son acidité d'une fonction $\\mathrm{COOH}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Cette question combine les deux distinctions structurales essentielles du cours.`,
    choiceExplanations: [
      `Les trois composants sont présents.`,
      `Le sucre est le 2-désoxyribose.`,
      `La présence du phosphate change la catégorie.`,
      `Le phosphate en est responsable.`,
    ],
  },
  {
    order: 111,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans le modèle toxicologique présenté, les dérivés halogénés réactifs :`,
    choices: [
      `Peuvent se comporter comme électrophiles.`,
      `Peuvent réagir avec des bases nucléiques nucléophiles.`,
      `Sont tous nécessairement inoffensifs.`,
      `Ne peuvent jamais modifier l'ADN.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'association électrophile''�nucléophile explique le mécanisme chimique général de certaines génotoxicités.`,
    choiceExplanations: [
      `Le carbone lié à l'halogène peut être déficient en électrons.`,
      `Une liaison covalente anormale peut se former.`,
      `Le cours insiste sur leur toxicité potentielle.`,
      `La modification des bases est précisément le risque évoqué.`,
    ],
  },
  {
    order: 112,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La modification covalente d'une base nucléique peut :`,
    choices: [
      `Altérer ses propriétés d'appariement.`,
      `Favoriser une mutation lors de la réplication.`,
      `Garantir toujours une réparation parfaite.`,
      `Transformer automatiquement l'ADN en protéine.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La mutagénicité résulte du risque d'erreur de lecture ou de réplication de l'information génétique.`,
    choiceExplanations: [
      `La géométrie et la distribution électronique peuvent changer.`,
      `Une base modifiée peut être mal reconnue.`,
      `Les systèmes de réparation ne sont pas infaillibles.`,
      `Ce n'est pas une conséquence chimique directe.`,
    ],
  },
  {
    order: 113,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pourquoi un dérivé halogéné peut-il être électrophile ?`,
    choices: [
      `La liaison $\\mathrm{C{-}X}$ est polarisée vers l'halogène.`,
      `Le carbone lié à $\\mathrm{X}$ peut porter un caractère partiellement positif.`,
      `L'halogène rend toujours le carbone chargé négativement.`,
      `La molécule ne possède aucune liaison chimique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le départ possible de l'halogénure et la polarisation expliquent les substitutions nucléophiles.`,
    choiceExplanations: [
      `L'halogène attire la densité électronique.`,
      `Il devient une cible pour un nucléophile.`,
      `La polarisation usuelle est inverse.`,
      `La réactivité dépend précisément de la liaison $\\mathrm{C{-}X}$.`,
    ],
  },
  {
    order: 114,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lorsqu'une base nucléique attaque un dérivé halogéné :`,
    choices: [
      `Elle joue le rôle de nucléophile.`,
      `Le dérivé halogéné joue le rôle d'électrophile.`,
      `Une nouvelle liaison covalente peut se former sur la base.`,
      `Le phosphate est obligatoirement éliminé sous forme de $\\mathrm{CO_2}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La toxicité découle d'une réaction organique classique se produisant sur une macromolécule biologique.`,
    choiceExplanations: [
      `Elle donne une paire d'électrons.`,
      `Son carbone accepte la paire.`,
      `La base est alors modifiée.`,
      `Cette réaction n'est pas une décarboxylation.`,
    ],
  },
  {
    order: 115,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une base de l'ADN est alkylée par un électrophile. Les conséquences possibles comprennent :`,
    choices: [
      `Une modification de la reconnaissance par les enzymes.`,
      `Une erreur d'appariement.`,
      `Une mutation si la lésion est mal réparée.`,
      `La certitude immédiate d'un cancer chez tout individu.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Il faut distinguer mécanisme mutagène potentiel et certitude clinique.`,
    choiceExplanations: [
      `La structure chimique de la base a changé.`,
      `Les liaisons hydrogène et la géométrie peuvent être perturbées.`,
      `L'erreur peut être fixée lors d'une réplication.`,
      `Le risque existe sans conséquence déterministe unique.`,
    ],
  },
  {
    order: 116,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le caractère cancérigène potentiel évoqué dans la fiche est lié :`,
    choices: [
      `�' la capacité de modifier les bases nucléiques.`,
      `�' la réactivité électrophile de certains dérivés halogénés.`,
      `�' la seule présence de carbone dans la molécule.`,
      `�' une transformation obligatoire en acide butyrique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le raisonnement chimique relie structure électrophile, adduit à l'ADN et risque biologique.`,
    choiceExplanations: [
      `Les lésions génétiques peuvent toucher des gènes contrôlant la cellule.`,
      `Elle permet l'attaque par les nucléophiles biologiques.`,
      `La réactivité fonctionnelle est déterminante.`,
      `Aucun tel métabolite n'est requis.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Toutes les bases nucléiques ne réagissent pas nécessairement au même site parce que :`,
    choices: [
      `Leurs hétéroatomes n'ont pas tous la même disponibilité électronique.`,
      `Leur accessibilité spatiale peut différer dans l'ADN.`,
      `Tous leurs atomes sont strictement équivalents.`,
      `Aucune ne contient d'azote.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La nucléophilie réelle dépend à la fois de l'électronique et de l'environnement moléculaire.`,
    choiceExplanations: [
      `La mésomérie et la protonation modifient les doublets.`,
      `La structure tridimensionnelle influence l'attaque.`,
      `Leurs environnements sont variés.`,
      `L'azote est caractéristique des bases nucléiques.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un composé est une base de Lewis mais aussi un constituant d'un nucléotide. Cela signifie :`,
    choices: [
      `Son hétérocycle peut donner une paire d'électrons.`,
      `Le nucléotide peut aussi porter des charges acides sur son phosphate.`,
      `La molécule ne peut être ni acide ni base selon le site considéré.`,
      `Le phosphate transforme tous les atomes d'azote en chlore.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les biomolécules sont polyfonctionnelles : base nucléique nucléophile et phosphate acide peuvent cohabiter.`,
    choiceExplanations: [
      `Il peut agir comme nucléophile.`,
      `Une même molécule peut combiner plusieurs propriétés.`,
      `Les comportements peuvent coexister sur des groupes différents.`,
      `Aucune telle transformation n'a lieu.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une molécule porte une base, un ribose et un phosphate. Après perte du phosphate :`,
    choices: [
      `Elle devient un nucléoside.`,
      `Son acidité liée au phosphate diminue.`,
      `Elle devient automatiquement un acide carboxylique.`,
      `Le ribose devient un 2-désoxyribose sans autre réaction.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Chaque modification doit être reliée au groupe effectivement ajouté ou retiré.`,
    choiceExplanations: [
      `Il reste base + sucre.`,
      `Le groupe ionisable principal a disparu.`,
      `Aucun $\\mathrm{COOH}$ n'est créé.`,
      `La déphosphorylation ne retire pas l'oxygène en 2'.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Bilan sur les acides nucléiques :`,
    choices: [
      `Les bases nucléiques peuvent être nucléophiles.`,
      `Le phosphate contribue à l'acidité des nucléotides.`,
      `Le nucléoside contient obligatoirement un phosphate.`,
      `Des électrophiles réactifs peuvent modifier les bases et devenir mutagènes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La section relie vocabulaire structural, acido-basicité de Lewis et conséquences biologiques de la réactivité.`,
    choiceExplanations: [
      `Leurs hétéroatomes portent des doublets.`,
      `Il peut porter plusieurs charges négatives.`,
      `Il n'en contient pas par définition.`,
      `C'est l'application toxicologique du chapitre.`,
    ],
  },
];
