/**
 * UE14 – Biologie cellulaire – Chapitre 3
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du cytosquelette :`,
    choices: [
      `Il constitue une matrice protéique fibreuse dans le cytoplasme.`,
      `Il contribue à structurer un volume cytoplasmique dynamique.`,
      `Il est rarement représenté sur les schémas simplifiés de cellule.`,
      `Il correspond uniquement à une structure rigide et immobile.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cytosquelette est une matrice protéique abondante qui structure le cytoplasme et participe aussi aux mouvements cellulaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le cytosquelette peut être révélé par :`,
    choices: [
      `Un traitement au bleu de Coomassie mettant en évidence les protéines.`,
      `Une coloration spécifique de l’ADN uniquement.`,
      `Une observation montrant qu’il occupe une part importante du cytoplasme.`,
      `Une méthode reposant exclusivement sur la détection des lipides.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Le cours cite le bleu de Coomassie, qui révèle les protéines et permet de visualiser l’abondance du cytosquelette.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le cytosquelette est constitué de trois grands types de polymères fibreux :`,
    choices: [
      `Les microtubules.`,
      `Les microfilaments d’actine.`,
      `Les filaments intermédiaires.`,
      `Les phospholipides membranaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois réseaux du cytosquelette sont les microtubules, les microfilaments d’actine et les filaments intermédiaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant les diamètres des trois réseaux :`,
    choices: [
      `Les microtubules mesurent environ 24 nm de diamètre.`,
      `Les microfilaments d’actine mesurent environ 5 nm.`,
      `Les filaments intermédiaires mesurent environ 8 à 10 nm.`,
      `Les filaments intermédiaires sont les plus larges des trois.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les microtubules sont les plus larges, les microfilaments d’actine les plus fins et les filaments intermédiaires ont un diamètre intermédiaire.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des monomères du cytosquelette :`,
    choices: [
      `Les microtubules sont formés à partir de tubulines globulaires.`,
      `Les microfilaments sont formés à partir d’actine globulaire.`,
      `Les filaments intermédiaires sont formés de protéines fibreuses allongées.`,
      `Les trois réseaux ont exactement le même monomère.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois réseaux sont des polymères protéiques mais leurs monomères sont différents.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Comparaison des réseaux du cytosquelette](/images/training/ue14/biologie-cellulaire/cytosquelette/comparaison-reseaux-cytosquelette.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les microtubules sont représentés comme des cylindres creux.`,
      `Les microfilaments d’actine sont plus fins que les filaments intermédiaires.`,
      `Les filaments intermédiaires sont décrits comme non polarisés.`,
      `Les trois réseaux sont décrits comme également dynamiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure compare les diamètres, les constituants et les propriétés dynamiques des trois réseaux.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules sont visualisés en microscopie optique :`,
    choices: [
      `Par immunomarquage de la tubuline.`,
      `Grâce à des anticorps couplés à des fluorochromes.`,
      `Par une coloration histologique standard qui les distingue toujours nettement.`,
      `En pouvant repérer le centrosome au centre du réseau.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les microtubules ne sont pas visibles par une coloration standard ; l’immunomarquage fluorescent de la tubuline permet de les révéler.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant la localisation des microtubules :`,
    choices: [
      `Ils sont présents dans le cytosol.`,
      `Ils sont absents du noyau.`,
      `Ils irradient du centrosome vers la périphérie cellulaire.`,
      `Ils sont exclusivement situés sous la membrane plasmique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les microtubules rayonnent depuis le centrosome, proche du noyau, vers la membrane plasmique.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Chez l’être humain, les microtubules :`,
    choices: [
      `Sont présents dans toutes les cellules eucaryotes nucléées.`,
      `Sont absents des hématies.`,
      `Sont absents des neurones.`,
      `Peuvent être très abondants dans certaines cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les hématies ont perdu leur noyau et ne possèdent pas le réseau cytosolique classique de microtubules ; les neurones sont au contraire très riches en microtubules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En microscopie électronique, un microtubule peut apparaître :`,
    choices: [
      `Rond en coupe transversale.`,
      `Allongé et fibreux en coupe longitudinale.`,
      `Comme un tubule creux après cryofracture.`,
      `Toujours comme une structure pleine et homogène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’aspect dépend du plan de coupe ; la cryofracture souligne le caractère creux du microtubule.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules :`,
    choices: [
      `Sont de longs cylindres creux.`,
      `Sont constitués de 13 protofilaments.`,
      `Présentent des stries liées à l’organisation des protofilaments.`,
      `Sont formés de deux chapelets d’actine torsadés.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La structure en 13 protofilaments explique l’aspect tubulaire et strié des microtubules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On distingue :`,
    choices: [
      `Des microtubules cytosoliques instables.`,
      `Des microtubules stabilisés dans certaines structures cellulaires.`,
      `Des microtubules instables subissant polymérisation et dépolymérisation.`,
      `Des microtubules stabilisés qui n’entrent dans aucune structure spécialisée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours oppose les microtubules cytosoliques instables aux microtubules stabilisés des centrioles, corpuscules basaux, cils et flagelles.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les centrioles :`,
    choices: [
      `Entrent dans la composition du centrosome.`,
      `Sont composés de 9 triplets de microtubules.`,
      `Sont présents par deux, disposés perpendiculairement.`,
      `Sont constitués de 9 doublets périphériques et d’un doublet central.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les centrioles comportent 9 triplets ; l’organisation en doublets périphériques avec un centre concerne l’axonème mobile.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les corpuscules basaux :`,
    choices: [
      `Sont situés à la base des cils et des flagelles.`,
      `Comportent 9 triplets de microtubules stabilisés.`,
      `Ont une organisation comparable à celle des centrioles.`,
      `Sont constitués exclusivement d’actine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les corpuscules basaux partagent l’organisation en 9 triplets des centrioles.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les cils et flagelles mobiles :`,
    choices: [
      `Possèdent un axonème.`,
      `Comportent 9 doublets périphériques et un doublet central selon le cours.`,
      `Sont soutenus par des microtubules stabilisés.`,
      `Sont constitués uniquement de filaments intermédiaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’axonème des cils et flagelles mobiles repose sur une organisation stable de microtubules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les cils primaires :`,
    choices: [
      `Sont généralement immobiles.`,
      `Sont souvent présents en un seul exemplaire par cellule.`,
      `Comportent 9 doublets périphériques sans doublet central selon le cours.`,
      `Sont absents de la plupart des cellules de l’organisme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cil primaire est généralement unique, immobile et largement répandu à la surface des cellules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Structures à microtubules stabilisés](/images/training/ue14/biologie-cellulaire/cytosquelette/structures-microtubules-stabilises.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Le centriole et le corpuscule basal sont organisés en 9 triplets.`,
      `Le cil ou flagelle mobile possède un axonème à doublets périphériques.`,
      `Le cil primaire est représenté sans structure centrale.`,
      `Toutes les structures représentées sont formées de microfilaments d’actine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure distingue les principales organisations de microtubules stabilisés décrites dans le cours.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le centrosome :`,
    choices: [
      `Est le centre organisateur des microtubules.`,
      `Régule la polymérisation des microtubules.`,
      `Contient deux centrioles perpendiculaires.`,
      `Est constitué uniquement des deux centrioles, sans matériel protéique environnant.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le centrosome comprend aussi un matériel protéique dense entourant les centrioles.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La polarité des microtubules dans la cellule signifie que :`,
    choices: [
      `Leurs deux extrémités ne sont pas équivalentes.`,
      `L’extrémité (−) est proximale et au contact du centrosome.`,
      `L’extrémité (+) est distale, tournée vers la périphérie.`,
      `Les deux extrémités ont toujours exactement la même dynamique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polarité structurale et fonctionnelle distingue une extrémité (−) proximale et une extrémité (+) distale.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La tubuline :`,
    choices: [
      `Est une protéine globulaire.`,
      `Est formée de sous-unités α et β.`,
      `La sous-unité α fixe le GTP sans l’hydrolyser.`,
      `La sous-unité β est incapable de fixer le GTP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La sous-unité β fixe et hydrolyse le GTP ; elle constitue la sous-unité active.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La polymérisation des microtubules comprend :`,
    choices: [
      `L’assemblage ordonné de tubulines en protofilaments.`,
      `La juxtaposition des protofilaments en feuille.`,
      `Le repliement de la feuille en un microtubule de 13 protofilaments.`,
      `Une synthèse directe d’un cylindre complet sans étape intermédiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours décrit successivement protofilaments, feuille puis fermeture en microtubule.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une forte concentration en GTP favorise :`,
    choices: [
      `L’association des molécules de tubuline.`,
      `La formation d’une cape de GTP à l’extrémité (+).`,
      `L’élongation du microtubule.`,
      `La disparition immédiate de tous les protofilaments.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cape de GTP stabilise l’extrémité (+) et favorise un bilan net d’association.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une faible concentration en GTP peut favoriser :`,
    choices: [
      `Une diminution de la cape de GTP.`,
      `Davantage de dissociations que d’associations.`,
      `Le raccourcissement du microtubule.`,
      `Une élongation nécessairement accélérée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La perte de la cape de GTP rend le microtubule moins stable et favorise sa dépolymérisation.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’instabilité dynamique des microtubules cytosoliques correspond :`,
    choices: [
      `À un renouvellement permanent de la population de microtubules.`,
      `À l’alternance de phases d’élongation et de raccourcissement.`,
      `À une propriété fortement régulée par des protéines associées.`,
      `À une immobilité complète des microtubules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’instabilité dynamique permet une adaptation rapide du réseau aux besoins cellulaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos de la demi-vie des microtubules :`,
    choices: [
      `Elle est d’environ 10 minutes dans un fibroblaste selon le cours.`,
      `Elle est d’environ 20 heures dans un neurone.`,
      `Elle illustre une dynamique différente selon le type cellulaire.`,
      `Elle est identique dans toutes les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La forte richesse en microtubules des neurones s’accompagne d’une stabilité bien plus importante que dans le fibroblaste.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Microtubules : dynamique et moteurs](/images/training/ue14/biologie-cellulaire/cytosquelette/microtubules-dynamique-moteurs.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `L’extrémité (−) est représentée près du centrosome.`,
      `La cape de GTP est associée à l’élongation.`,
      `La perte de cape est associée au raccourcissement.`,
      `La kinésine est représentée comme se déplaçant vers l’extrémité (−).`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure associe la kinésine au mouvement antérograde vers (+) et la dynéine au mouvement rétrograde vers (−).`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une hausse de la concentration intracellulaire en tubuline liée au GTP devrait :`,
    choices: [
      `Favoriser l’incorporation de tubuline dans les microtubules.`,
      `Favoriser la formation d’une cape de GTP.`,
      `Augmenter la probabilité d’élongation.`,
      `Empêcher toute association de tubuline.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le GTP disponible favorise l’assemblage et la stabilisation de l’extrémité (+).`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si la sous-unité β de la tubuline ne pouvait plus hydrolyser le GTP :`,
    choices: [
      `La dynamique normale du microtubule serait probablement perturbée.`,
      `Le rôle actif de la sous-unité β serait modifié.`,
      `Le couplage entre hydrolyse du GTP et stabilité du microtubule serait altéré.`,
      `La sous-unité α deviendrait automatiquement une molécule d’actine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette hypothèse perturberait la dynamique de la tubuline β sans transformer la nature des protéines.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos des microtubules cytosoliques et stabilisés :`,
    choices: [
      `Les premiers sont adaptés à des changements rapides de longueur.`,
      `Les seconds participent à des architectures durables.`,
      `Les centrioles sont un exemple de structure stabilisée.`,
      `Les deux catégories sont constituées de molécules totalement différentes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La différence porte sur leur stabilité et leur organisation, non sur la nature fondamentale de la tubuline.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte concernant les microtubules ?`,
    choices: [
      `Ils sont polarisés, dynamiques et organisés par le centrosome.`,
      `Leur polymérisation dépend de la tubuline et du GTP.`,
      `Ils peuvent être cytosoliques instables ou intégrés à des structures stabilisées.`,
      `Ils sont des polymères d’actine F.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les microtubules reposent sur la tubuline et le GTP, et non sur l’actine F.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `generalites-et-reseaux-du-cytosquelette`,
    title: `Généralités et réseaux du cytosquelette`,
    description: `Définition, composition et comparaison des trois réseaux.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `structure-et-organisations-des-microtubules`,
    title: `Structure et organisations des microtubules`,
    description: `Localisation, structure, centrioles, axonèmes et cils primaires.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `polymerisation-et-instabilite-des-microtubules`,
    title: `Polymérisation et instabilité des microtubules`,
    description: `Tubuline, GTP, cape, élongation et raccourcissement.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
