/**
 * UE14 – Biologie cellulaire – Chapitre 3
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules participent à la forme cellulaire en soutenant :`,
    choices: [
      `Les cils.`,
      `Les flagelles.`,
      `Des expansions cytoplasmiques spécialisées.`,
      `Exclusivement le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cils et flagelles sont des expansions cytoplasmiques reposant sur un cytosquelette de microtubules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans l’épithélium respiratoire :`,
    choices: [
      `Les cils battent de façon coordonnée.`,
      `Le mucus piège poussières et micro-organismes.`,
      `Le mouvement ciliaire permet la remontée du mucus vers le carrefour aérodigestif.`,
      `Les cils déplacent directement le noyau des cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cils déplacent le milieu péricellulaire, ici le mucus, et participent à l’épuration respiratoire.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le flagelle du spermatozoïde :`,
    choices: [
      `Est soutenu par des microtubules.`,
      `Permet le déplacement de la cellule entière.`,
      `Produit un mouvement ondulatoire.`,
      `Est constitué uniquement de filaments intermédiaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le flagelle est une structure motile à microtubules permettant le déplacement du spermatozoïde.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules forment des rails pour le déplacement :`,
    choices: [
      `Des vésicules.`,
      `Des mitochondries.`,
      `Du réticulum endoplasmique ou d’autres organites.`,
      `Uniquement des chromosomes en dehors de la mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le réseau microtubulaire assure une part importante du transport intracellulaire d’organites.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les protéines motrices associées aux microtubules :`,
    choices: [
      `Possèdent des têtes globulaires capables d’interagir avec le microtubule.`,
      `Utilisent l’hydrolyse de l’ATP.`,
      `Possèdent un site de liaison à l’organite transporté.`,
      `Se déplacent sans consommation d’énergie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le déplacement moteur est alimenté par l’hydrolyse de l’ATP.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `La kinésine assure principalement un transport :`,
    choices: [
      `Antérograde.`,
      `Rétrograde.`,
      `Nucléaire uniquement.`,
      `Indépendant des microtubules.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le cours associe la kinésine au sens antérograde.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `La dynéine assure principalement un transport :`,
    choices: [
      `Rétrograde.`,
      `Antérograde.`,
      `Exclusivement vers l’extrémité (+).`,
      `Indépendant de l’ATP.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le cours associe la dynéine au sens rétrograde.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le déplacement des protéines motrices le long des microtubules :`,
    choices: [
      `Peut être décrit comme saltatoire.`,
      `Résulte de mouvements répétés des têtes globulaires.`,
      `Entraîne l’organite auquel la protéine est liée.`,
      `Nécessite la disparition préalable du microtubule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les têtes motrices progressent par cycles d’attachement et de mouvement utilisant l’ATP.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules interviennent dans la division cellulaire en :`,
    choices: [
      `Constituant le fuseau mitotique.`,
      `Participant à la répartition des chromosomes.`,
      `Permettant l’alignement des chromosomes sur la plaque équatoriale.`,
      `Formant l’anneau contractile final à la place de l’actine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le fuseau mitotique est microtubulaire ; l’anneau contractile de cytocinèse dépend surtout de l’actine.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Microtubules : dynamique et moteurs](/images/training/ue14/biologie-cellulaire/cytosquelette/microtubules-dynamique-moteurs.png)

À propos des moteurs :`,
    choices: [
      `La kinésine est associée au transport vers l’extrémité (+).`,
      `La dynéine est associée au transport vers l’extrémité (−).`,
      `Les deux moteurs se déplacent sur des microtubules polarisés.`,
      `Les deux moteurs fonctionnent sans ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polarité du microtubule permet d’orienter le trafic intracellulaire.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La fonction des cils respiratoires dépend :`,
    choices: [
      `De microtubules stabilisés.`,
      `De protéines motrices associées à l’axonème.`,
      `D’un mouvement coordonné.`,
      `D’une absence totale de cytosquelette.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le battement ciliaire résulte d’une architecture microtubulaire et de protéines motrices.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une altération de l’axonème des cils respiratoires pourrait :`,
    choices: [
      `Diminuer le transport du mucus.`,
      `Favoriser l’accumulation de particules ou micro-organismes.`,
      `Perturber l’épuration mucociliaire.`,
      `Améliorer nécessairement le battement ciliaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Un défaut ciliaire compromettrait logiquement l’évacuation du mucus décrite dans le cours.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une altération des microtubules du flagelle pourrait :`,
    choices: [
      `Diminuer la motilité du spermatozoïde.`,
      `Perturber le mouvement ondulatoire.`,
      `Affecter le déplacement de la cellule.`,
      `Augmenter automatiquement la polymérisation de l’actine dans le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le flagelle repose sur un cytosquelette de microtubules stabilisés.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le transport antérograde correspond, dans la logique du réseau représenté :`,
    choices: [
      `À un déplacement vers la périphérie et l’extrémité (+).`,
      `À un transport typiquement assuré par la kinésine.`,
      `À un mouvement opposé au transport rétrograde.`,
      `À un transport obligatoirement assuré par la dynéine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La dynéine est associée au mouvement rétrograde vers le centrosome.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le transport rétrograde correspond :`,
    choices: [
      `À un déplacement vers le centrosome et l’extrémité (−).`,
      `À un transport typiquement assuré par la dynéine.`,
      `À une direction opposée au transport antérograde.`,
      `À un transport exclusivement extracellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le transport rétrograde ramène des cargaisons vers la région centrale de la cellule.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition de l’hydrolyse de l’ATP par les protéines motrices devrait :`,
    choices: [
      `Réduire leur progression le long des microtubules.`,
      `Perturber le transport des organites.`,
      `Affecter les mouvements saltatoires des têtes.`,
      `Transformer la kinésine en tubuline.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ATP fournit l’énergie nécessaire au mouvement moteur ; il ne change pas la nature des protéines.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un organite lié à une kinésine active a tendance à :`,
    choices: [
      `Se déplacer dans le sens antérograde.`,
      `Se rapprocher de l’extrémité (+).`,
      `Utiliser le microtubule comme rail.`,
      `Être transporté par diffusion simple à travers la membrane plasmique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le transport est intracellulaire et dirigé, non une diffusion à travers la membrane plasmique.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un organite lié à une dynéine active a tendance à :`,
    choices: [
      `Se déplacer dans le sens rétrograde.`,
      `Se rapprocher du centrosome.`,
      `Se diriger vers l’extrémité (−).`,
      `Quitter obligatoirement la cellule par exocytose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La dynéine assure un mouvement centripète sans impliquer nécessairement une exocytose.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules du fuseau mitotique :`,
    choices: [
      `Sont nécessaires à une répartition correcte des chromosomes.`,
      `S’organisent lors de la division cellulaire.`,
      `Illustrent la capacité du cytosquelette à se réorganiser.`,
      `Restent totalement indépendants de la dynamique microtubulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La formation et le fonctionnement du fuseau reposent sur une organisation dynamique des microtubules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure des structures stabilisées.

![Structures à microtubules stabilisés](/images/training/ue14/biologie-cellulaire/cytosquelette/structures-microtubules-stabilises.png)

Quelle(s) structure(s) est(sont) directement liée(s) à la motilité ?`,
    choices: [
      `Le cil mobile.`,
      `Le flagelle mobile.`,
      `L’axonème.`,
      `Le centriole isolé, à lui seul, comme moteur de déplacement extracellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’axonème constitue l’armature microtubulaire des cils et flagelles mobiles.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si le centrosome ne pouvait plus organiser les microtubules :`,
    choices: [
      `Le réseau radial cytosolique serait perturbé.`,
      `La polarité globale du réseau serait moins bien organisée.`,
      `Le transport dirigé des organites pourrait être affecté.`,
      `Les filaments intermédiaires deviendraient automatiquement des microtubules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le centrosome organise le réseau microtubulaire mais ne transforme pas les autres polymères du cytosquelette.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une perturbation sélective de la kinésine pourrait :`,
    choices: [
      `Réduire certains transports vers la périphérie.`,
      `Épargner potentiellement le transport rétrograde assuré par la dynéine.`,
      `Modifier la distribution de certaines vésicules et organites.`,
      `Supprimer directement la structure de tous les filaments intermédiaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les moteurs microtubulaires ont des directions et des cargos distincts.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une perturbation sélective de la dynéine pourrait :`,
    choices: [
      `Réduire certains transports vers le centrosome.`,
      `Affecter le retour rétrograde des organites.`,
      `Laisser certains transports antérogrades assurés par la kinésine.`,
      `Empêcher toute polymérisation d’actine G.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La dynéine agit sur les microtubules ; elle n’est pas le moteur direct de polymérisation de l’actine.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’organisation polarisée des microtubules permet :`,
    choices: [
      `De définir des directions de transport intracellulaire.`,
      `D’associer kinésine et dynéine à des sens opposés.`,
      `D’orienter le trafic entre centre et périphérie.`,
      `D’effacer toute distinction entre transport antérograde et rétrograde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polarité est la base de l’orientation du trafic microtubulaire.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut combiné de microtubules et de protéines motrices pourrait affecter :`,
    choices: [
      `Le transport de vésicules.`,
      `La localisation de mitochondries.`,
      `Le mouvement de certaines structures ciliées.`,
      `Uniquement la synthèse de l’ADN dans le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les fonctions microtubulaires concernent la morphologie, le trafic et la motilité.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les cils et flagelles diffèrent fonctionnellement car :`,
    choices: [
      `Les cils déplacent souvent le milieu péricellulaire.`,
      `Le flagelle peut déplacer une cellule isolée.`,
      `Les deux reposent néanmoins sur une architecture microtubulaire.`,
      `Les cils respiratoires sont constitués uniquement d’actine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours oppose déplacement du milieu par les cils et déplacement cellulaire par le flagelle.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une cellule en métaphase :`,
    choices: [
      `Les chromosomes sont alignés sur la plaque équatoriale.`,
      `Le fuseau mitotique est constitué de microtubules.`,
      `La répartition chromosomique dépend du cytosquelette.`,
      `Les microtubules sont absents car la cellule est en division.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitose requiert précisément un réseau microtubulaire spécialisé.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le terme « cytosquelette » est incomplet car :`,
    choices: [
      `Il suggère seulement un rôle de soutien.`,
      `Il masque le rôle moteur et dynamique de ces réseaux.`,
      `Les microtubules participent à des mouvements intracellulaires et cellulaires.`,
      `Le cytosquelette est en réalité constitué uniquement de cartilage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’analogie avec le squelette humain ne suffit pas à rendre compte des fonctions motrices.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle(s) fonction(s) des microtubules illustre(nt) leur polyvalence ?`,
    choices: [
      `Soutien des cils et flagelles.`,
      `Transport intracellulaire.`,
      `Formation du fuseau mitotique.`,
      `Production directe d’ATP mitochondrial.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les microtubules ne produisent pas l’ATP ; ils l’utilisent indirectement via les moteurs.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?`,
    choices: [
      `Les microtubules relient organisation, transport, motilité et division.`,
      `Leur polarité sert de repère directionnel aux moteurs.`,
      `Les structures stabilisées ont des fonctions spécialisées.`,
      `La dynéine et la kinésine sont des phospholipides.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Kinésine et dynéine sont des protéines motrices associées aux microtubules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `fonctions-et-motilite-des-microtubules`,
    title: `Fonctions et motilité des microtubules`,
    description: `Cils, flagelles, trafic intracellulaire et fuseau mitotique.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `proteines-motrices-et-transport-intracellulaire`,
    title: `Protéines motrices et transport intracellulaire`,
    description: `Kinésine, dynéine, polarité et organisation du trafic.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `microtubules-dans-la-cellule-integree`,
    title: `Microtubules dans la cellule intégrée`,
    description: `Applications fonctionnelles, pathologiques et mitotiques.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
