import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_ORDER = 3;

export const SECTION_C_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  61: ["Osamine se caractérise par"],
  62: ["Une osamine humaine classique, la fonction amine est habituell…"],
  63: ["Les osamines peuvent entrer dans la composition de"],
  64: ["Osamine N-acétylée"],
  65: ["Groupement acétyl ajouté à une osamine est"],
  66: ["Les osamines N-acétylées sont notamment associées"],
  67: ["Chitine"],
  68: ["NANA est aussi appelé"],
  69: ["La formation de l’acide neuraminique"],
  70: ["Cyclisation de l’acide neuraminique décrite dans la fiche s’ef…"],
  71: ["NANA comporte"],
  72: ["L’acide sialique est retrouvé"],
  73: ["Les rôles du NANA"],
  74: ["Répulsion entre groupements COO− de chaînes glycaniques tend à…"],
  75: ["Comparer une osamine et une osamine N-acétylée"],
  76: ["Osamine peut être modifiée par"],
  77: ["Les glycosaminoglycanes peuvent contenir"],
  78: ["Paroi bactérienne contenant une osamine N-acétylée"],
  79: ["Charge négative du NANA provient principalement"],
  80: ["À propos des osamines dans les tissus humains"],
  81: ["Figure résume la transformation d’un ose en dérivé aminé"],
  82: ["À partir de la figure de l’acide sialique"],
  83: ["Mutation modifie la présentation des acides sialiques à la sur…"],
  84: ["Chitine et la paroi bactérienne illustrent"],
  85: ["Motif β(1→4) cité pour la chitine décrit"],
  86: ["Pour distinguer glucosamine et N-acétylglucosamine"],
  87: ["NANA associe dans une même molécule"],
  88: ["Chaîne glycannique riche en acides sialiques"],
  89: ["Les associations correctes"],
  90: ["Synthèse des dérivés aminés"],
};

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "osamines-n-acetylees",
    title: "Osamines et dérivés N-acétylés",
    description: "Identifier les osamines, leur N-acétylation et leurs rôles structuraux.",
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 2,
    slug: "nana-acide-sialique",
    title: "NANA et acides sialiques",
    description: "Comprendre la formation, l’ionisation et les rôles cellulaires de l’acide sialique.",
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 3,
    slug: "derives-amines-glycoconjugues",
    title: "Dérivés aminés dans les glycoconjugués",
    description: "Interpréter les structures aminées dans les parois, polymères et surfaces cellulaires.",
    stage: 'MASTER',
    sectionOrder: 3,
    items: [
      {
        type: 'GROUP',
        title: "Transformations structurales",
        sharedStatement: "Les questions suivantes s’appuient sur les structures d’osamines et d’acide sialique.",
        questionOrders: [81, 82],
      },
      {
        type: 'GROUP',
        title: "Fonctions cellulaires",
        sharedStatement: "Les dérivés aminés contribuent à des enveloppes, polymères et surfaces cellulaires.",
        questionOrders: [83, 84, 85],
      },
      {
        type: 'GROUP',
        title: "Analyse fonctionnelle",
        sharedStatement: "Les questions suivantes demandent de relier structure, charge et fonction biologique.",
        questionOrders: [86, 87, 88, 89, 90],
      },
    ],
  },
];

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Une osamine se caractérise par :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osamine-n-acetyl-osamine',
    },
    choices: [
      "Le remplacement d’un OH en C2 par une amine primaire.",
      "La présence d’azote.",
      "La possibilité d’exister sous forme α ou β.",
      "La transformation obligatoire de C6 en COOH.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Une osamine est un ose aminé, typiquement substitué en C2.",
    choiceExplanations: [
      "Vrai. C’est la définition structurale.",
      "Vrai. La fonction amine apporte l’azote.",
      "Vrai. La molécule cyclique peut présenter deux anomères.",
      "Faux. Cette oxydation caractérise plutôt un acide uronique.",
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Dans une osamine humaine classique, la fonction amine est habituellement portée par :",
    choices: [
      "C1.",
      "C2.",
      "C5.",
      "C6.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Le remplacement de l’OH par NH2 concerne classiquement le carbone C2.",
    choiceExplanations: [
      "C1 est souvent anomérique.",
      "C’est la position à retenir.",
      "C5 intervient dans la structure du NANA mais pas dans la définition générale de l’osamine.",
      "C6 porte souvent un alcool primaire.",
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les osamines peuvent entrer dans la composition de :",
    choices: [
      "Glycosaminoglycanes.",
      "Glycoprotéines.",
      "Protéoglycanes.",
      "Glycolipides.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les osamines sont des briques fréquentes de nombreux glycoconjugués.",
    choiceExplanations: [
      "Vrai. Elles sont fréquentes dans les GAG.",
      "Vrai. Elles peuvent appartenir aux chaînes glycaniques.",
      "Vrai. Les protéoglycanes portent des GAG.",
      "Vrai. Elles sont présentes dans certains sphingoglycolipides.",
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Une osamine N-acétylée :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osamine-n-acetyl-osamine',
    },
    choices: [
      "Porte un groupement acétyl sur l’amine.",
      "Conserve un motif azoté.",
      "Peut être retrouvée dans la paroi bactérienne.",
      "Est nécessairement dépourvue de toute fonction alcool.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’acétylation de l’amine produit un groupement N-acétyl sans supprimer tous les OH de l’ose.",
    choiceExplanations: [
      "Vrai. N-acétyl signifie que l’acétyl est lié à l’azote.",
      "Vrai. L’azote reste présent dans une fonction amide.",
      "Vrai. La paroi bactérienne en contient.",
      "Faux. La charpente conserve plusieurs fonctions alcool.",
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Le groupement acétyl ajouté à une osamine est :",
    choices: [
      "CH3CO–.",
      "NH2–.",
      "SO4²− seul.",
      "PO4³− seul.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Un groupement acétyl correspond au motif CH3CO–.",
    choiceExplanations: [
      "C’est la formule du groupement.",
      "Il s’agit d’une fonction amine non acétylée.",
      "Il s’agit d’un sulfate.",
      "Il s’agit d’un phosphate.",
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les osamines N-acétylées sont notamment associées :",
    choices: [
      "À la paroi bactérienne.",
      "À certains polymères glucidiques.",
      "À la chitine.",
      "Exclusivement au noyau des cellules humaines.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Ces dérivés structuraux sont retrouvés dans plusieurs parois ou polymères.",
    choiceExplanations: [
      "Vrai. C’est un exemple biologique majeur.",
      "Vrai. Elles peuvent former des chaînes répétitives.",
      "Vrai. La chitine est un polymère de glucosamine N-acétylée.",
      "Faux. Leur distribution est beaucoup plus large.",
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La chitine :",
    choices: [
      "Est un polymère à liaisons β(1→4).",
      "Contient des unités dérivées de la glucosamine.",
      "Est présente dans la carapace d’insectes et de crustacés.",
      "Est un polyol du glucose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La chitine est un polymère structural de N-acétylglucosamine à liaisons β(1→4).",
    choiceExplanations: [
      "Vrai. Ce type de liaison est à retenir.",
      "Vrai. Les unités sont des osamines N-acétylées.",
      "Vrai. Ces structures animales sont citées.",
      "Faux. Un polyol est un produit de réduction d’un ose.",
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Le NANA est aussi appelé :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'nana-sialic-acid',
    },
    choices: [
      "Acide sialique.",
      "Sorbitol.",
      "Acide glucuronique.",
      "Fructose-1,6-bisphosphate.",
    ],
    correctChoiceIndexes: [0],
    explanation: "NANA, acide N-acétylneuraminique et acide sialique sont synonymes dans le cours.",
    choiceExplanations: [
      "C’est le synonyme demandé.",
      "Le sorbitol est un polyol.",
      "L’acide glucuronique est un acide uronique.",
      "Il s’agit d’un ester phosphorique.",
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant la formation de l’acide neuraminique :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'nana-sialic-acid',
    },
    choices: [
      "Une D-mannosamine intervient.",
      "Un acide pyruvique est ajouté.",
      "La molécule peut ensuite se cycliser.",
      "Elle provient directement de la réduction du ribose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’acide neuraminique dérive d’une D-mannosamine associée à un motif issu du pyruvate.",
    choiceExplanations: [
      "Vrai. C’est le précurseur aminé cité.",
      "Vrai. Il contribue à l’allongement de la chaîne.",
      "Vrai. Une cyclisation C2–C6 est décrite.",
      "Faux. Le ribose n’est pas le précurseur indiqué.",
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La cyclisation de l’acide neuraminique s’effectue entre :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'nana-sialic-acid',
    },
    choices: [
      "C1 et C4.",
      "C1 et C5.",
      "C2 et C6.",
      "C3 et C4.",
    ],
    correctChoiceIndexes: [2],
    explanation: "Le rapprochement concerne C2 et C6.",
    choiceExplanations: [
      "Cette liaison n’est pas celle décrite.",
      "Cette cyclisation est typique de certains aldoses, pas du NANA présenté.",
      "C’est la paire de carbones à retenir.",
      "Cette paire n’est pas indiquée.",
    ],
  },
  {
    order: 71,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le NANA comporte :",
    choices: [
      "Un groupement N-acétyl.",
      "Un groupement carboxyle susceptible de s’ioniser.",
      "Une charge négative possible sous forme COO−.",
      "Aucun atome d’azote.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’acide sialique est un dérivé N-acétylé et acide, souvent négativement chargé.",
    choiceExplanations: [
      "Vrai. NANA signifie N-acétylneuraminique.",
      "Vrai. Il porte un COOH.",
      "Vrai. La déprotonation donne COO−.",
      "Faux. Le groupement N-acétyl contient un azote.",
    ],
  },
  {
    order: 72,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’acide sialique est retrouvé :",
    choices: [
      "Dans des glycoprotéines de surface.",
      "Dans des glycolipides de surface.",
      "À la surface de cellules eucaryotes.",
      "Uniquement dans la paroi des végétaux.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le NANA est un motif terminal fréquent des glycoconjugués de cellules eucaryotes.",
    choiceExplanations: [
      "Vrai. Il peut terminer les chaînes glycaniques.",
      "Vrai. Certains glycolipides en contiennent.",
      "Vrai. C’est sa localisation mise en avant.",
      "Faux. Il est particulièrement associé aux cellules eucaryotes animales.",
    ],
  },
  {
    order: 73,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les rôles du NANA :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'nana-sialic-acid',
    },
    choices: [
      "Participation à la reconnaissance cellulaire.",
      "Contribution à une charge négative de surface.",
      "Répulsion électrostatique entre chaînes glycaniques.",
      "Transformation des glycoprotéines en ADN.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les carboxylates de l’acide sialique influencent la reconnaissance et l’organisation des glycoconjugués.",
    choiceExplanations: [
      "Vrai. C’est un marqueur de surface.",
      "Vrai. COO− confère une charge négative.",
      "Vrai. Des charges de même signe se repoussent.",
      "Faux. Aucun lien avec une conversion en ADN.",
    ],
  },
  {
    order: 74,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La répulsion entre groupements COO− de chaînes glycaniques tend à maintenir une structure :",
    choices: [
      "En bâtonnet.",
      "Toujours globulaire compacte.",
      "Cristalline métallique.",
      "Dépourvue d’eau.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La répulsion électrostatique maintient les chaînes étendues, décrites comme en bâtonnet.",
    choiceExplanations: [
      "C’est l’effet indiqué.",
      "La répulsion s’oppose à une compaction étroite.",
      "Aucun réseau métallique n’est impliqué.",
      "Les glycoconjugués sont en milieu biologique aqueux.",
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer une osamine et une osamine N-acétylée :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osamine-n-acetyl-osamine',
    },
    choices: [
      "La première porte typiquement NH2 en C2.",
      "La seconde porte un groupement acétyl sur cet azote.",
      "La seconde contient une fonction amide.",
      "L’acétylation élimine l’atome d’azote.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’acétylation transforme l’amine en fonction N-acétylée tout en conservant l’azote.",
    choiceExplanations: [
      "Vrai. C’est la structure de base.",
      "Vrai. CH3CO– est fixé sur N.",
      "Vrai. Le motif N–CO correspond à une amide.",
      "Faux. L’azote reste présent.",
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une osamine peut être modifiée par :",
    choices: [
      "N-acétylation.",
      "Sulfatation dans certains GAG.",
      "Incorporation à des glycoconjugués.",
      "Conversion obligatoire en triglycéride.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les osamines sont des motifs polyvalents, souvent acétylés ou sulfatés dans des structures complexes.",
    choiceExplanations: [
      "Vrai. C’est une modification majeure.",
      "Vrai. Le cours et l’auto-évaluation le signalent.",
      "Vrai. Elles entrent dans de nombreuses familles.",
      "Faux. Leur destin n’est pas limité aux triglycérides.",
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les glycosaminoglycanes peuvent contenir :",
    choices: [
      "Des osamines.",
      "Des osamines N-acétylées.",
      "Des osamines sulfatées.",
      "Uniquement des acides aminés reliés par liaisons peptidiques.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les GAG sont des polymères glucidiques riches en dérivés aminés et souvent sulfatés.",
    choiceExplanations: [
      "Vrai. C’est un constituant fréquent.",
      "Vrai. L’acétylation est courante.",
      "Vrai. La sulfatation contribue à la charge négative.",
      "Faux. Ce ne sont pas des protéines.",
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une paroi bactérienne contenant une osamine N-acétylée :",
    choices: [
      "Illustre un rôle structural de ces dérivés.",
      "Contient un motif azoté.",
      "Peut comporter une fonction amide issue de l’acétylation.",
      "Démontre que toutes les osamines sont des polyols sans azote.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les osamines N-acétylées sont des briques structurales azotées de certaines parois.",
    choiceExplanations: [
      "Vrai. Elles contribuent à l’architecture.",
      "Vrai. L’azote est conservé.",
      "Vrai. N-acétyl forme une amide.",
      "Faux. Une osamine est précisément azotée.",
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La charge négative du NANA provient principalement :",
    choices: [
      "De l’ionisation de son groupement carboxyle.",
      "De la formation de COO−.",
      "D’une perte de proton.",
      "D’un groupement ammonium quaternaire obligatoire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La déprotonation du COOH produit le carboxylate négatif.",
    choiceExplanations: [
      "Vrai. Le COOH est la fonction acide.",
      "Vrai. COO− porte la charge.",
      "Vrai. La déprotonation crée l’anion.",
      "Faux. Un ammonium quaternaire serait positivement chargé.",
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos des osamines dans les tissus humains :",
    choices: [
      "La fonction amine est habituellement en C2 de l’hexose.",
      "Elles peuvent être N-acétylées.",
      "Elles peuvent être sulfatées dans des GAG.",
      "Elles portent toujours leur amine en C6.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le repère structural principal est l’amine en C2, souvent modifiée.",
    choiceExplanations: [
      "Vrai. C’est la position classique.",
      "Vrai. L’acétylation est fréquente.",
      "Vrai. La sulfatation se rencontre dans les GAG.",
      "Faux. C6 n’est pas la position habituelle de l’amine.",
    ],
  },
  {
    order: 81,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La figure résume la transformation d’un ose en dérivé aminé :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osamine-n-acetyl-osamine',
    },
    choices: [
      "Le OH de C2 peut être remplacé par NH2.",
      "L’amine peut ensuite être N-acétylée.",
      "Le motif N-acétylé contient CH3CO–.",
      "L’étape d’acétylation supprime tous les OH.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La figure montre la succession ose, osamine puis osamine N-acétylée.",
    choiceExplanations: [
      "Vrai. C’est la substitution caractéristique.",
      "Vrai. L’acétyl est fixé sur l’azote.",
      "Vrai. C’est le groupement ajouté.",
      "Faux. Les autres fonctions alcool restent présentes.",
    ],
  },
  {
    order: 82,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À partir de la figure de l’acide sialique :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'nana-sialic-acid',
    },
    choices: [
      "Une D-mannosamine contribue à sa formation.",
      "Le pyruvate intervient.",
      "Le produit final est N-acétylé.",
      "Le produit final ne possède aucune fonction acide.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le NANA associe origine osaminée, ajout du pyruvate, cyclisation et N-acétylation.",
    choiceExplanations: [
      "Vrai. C’est le précurseur glucidique.",
      "Vrai. Il apporte un fragment carboné.",
      "Vrai. Le nom N-acétyl le précise.",
      "Faux. Le groupement carboxyle est central.",
    ],
  },
  {
    order: 83,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une mutation modifie la présentation des acides sialiques à la surface cellulaire. Les conséquences plausibles concernent :",
    choices: [
      "La reconnaissance cellulaire.",
      "La charge de surface.",
      "L’organisation spatiale des chaînes glycaniques.",
      "La formation directe de liaisons peptidiques dans l’ADN.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le NANA agit à l’interface cellulaire par ses motifs de reconnaissance et ses charges.",
    choiceExplanations: [
      "Vrai. Les glycannes de surface servent de signaux.",
      "Vrai. Les carboxylates sont négatifs.",
      "Vrai. La répulsion influence la conformation.",
      "Faux. Cette formulation mélange protéines et acides nucléiques.",
    ],
  },
  {
    order: 84,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La chitine et la paroi bactérienne illustrent :",
    choices: [
      "Des fonctions structurales de dérivés aminés des oses.",
      "La présence de motifs N-acétylés.",
      "Des structures différentes des polyols alimentaires.",
      "L’absence totale de glucides dans les enveloppes biologiques.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les osamines N-acétylées peuvent former des matériaux biologiques résistants.",
    choiceExplanations: [
      "Vrai. Elles jouent un rôle architectural.",
      "Vrai. C’est la modification mise en avant.",
      "Vrai. Un polyol isolé n’est pas un polymère structural équivalent.",
      "Faux. Ces exemples démontrent au contraire la présence de glucides.",
    ],
  },
  {
    order: 85,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: "Le motif β(1→4) cité pour la chitine décrit :",
    choices: [
      "Une liaison glycosidique entre unités de glucosamine N-acétylée.",
      "Une liaison peptidique entre deux acides aminés.",
      "Une liaison métallique.",
      "Une réduction du C1 en alcool.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La chitine est un polymère glucidique lié par des liaisons β(1→4).",
    choiceExplanations: [
      "C’est l’interprétation correcte.",
      "Une liaison peptidique ne relie pas ces oses.",
      "Aucun métal n’est nécessaire.",
      "Le symbole décrit une liaison osidique, non une réduction.",
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Pour distinguer glucosamine et N-acétylglucosamine :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osamine-n-acetyl-osamine',
    },
    choices: [
      "Rechercher NH2 libre pour la première.",
      "Rechercher NH–CO–CH3 pour la seconde.",
      "Les deux conservent une charpente d’ose.",
      "La seconde est dépourvue d’azote.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La N-acétylation modifie l’état fonctionnel de l’azote sans supprimer la charpente glucidique.",
    choiceExplanations: [
      "Vrai. C’est l’amine primaire.",
      "Vrai. C’est la fonction N-acétylée.",
      "Vrai. Elles restent des dérivés d’oses.",
      "Faux. L’azote est toujours présent.",
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Le NANA associe dans une même molécule :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'nana-sialic-acid',
    },
    choices: [
      "Un caractère osidique dérivé.",
      "Une fonction acide ionisable.",
      "Un groupement N-acétyl.",
      "Une absence totale de charges possibles.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’acide sialique est un dérivé glucidique complexe, acide et N-acétylé.",
    choiceExplanations: [
      "Vrai. Il dérive d’une osamine.",
      "Vrai. Son COOH peut devenir COO−.",
      "Vrai. Cela figure dans son nom.",
      "Faux. La forme carboxylate est chargée négativement.",
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une chaîne glycannique riche en acides sialiques :",
    choices: [
      "Peut porter plusieurs charges négatives.",
      "Peut être maintenue dans une conformation étendue par répulsion.",
      "Peut participer à des interactions de reconnaissance.",
      "Est nécessairement insoluble et apolaire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les carboxylates de NANA confèrent hydrophilie, charge et effets conformationnels.",
    choiceExplanations: [
      "Vrai. Chaque COO− apporte une charge.",
      "Vrai. Les charges de même signe se repoussent.",
      "Vrai. Les motifs terminaux sont biologiquement reconnus.",
      "Faux. Les nombreux groupes polaires s’opposent à un caractère apolaire.",
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Parmi les associations correctes :",
    choices: [
      "Osamine — NH2 en C2.",
      "Osamine N-acétylée — motif NHCOCH3.",
      "NANA — acide sialique.",
      "Chitine — polymère de sorbitol α(1→6).",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les trois premières associations résument les dérivés aminés ; la chitine est un polymère β(1→4) de N-acétylglucosamine.",
    choiceExplanations: [
      "Vrai. C’est le motif général.",
      "Vrai. L’acétylation porte sur l’azote.",
      "Vrai. Les deux noms sont synonymes.",
      "Faux. La composition et la liaison sont incorrectes.",
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Synthèse des dérivés aminés :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'nana-sialic-acid',
    },
    choices: [
      "Ils peuvent participer aux glycoconjugués.",
      "Leur acétylation peut produire des motifs structuraux.",
      "Le NANA intervient à la surface des cellules eucaryotes.",
      "Ils sont tous dépourvus de rôle de reconnaissance.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les dérivés aminés des oses ont des fonctions structurales et de reconnaissance.",
    choiceExplanations: [
      "Vrai. GAG, glycoprotéines et glycolipides en contiennent.",
      "Vrai. Parois et chitine l’illustrent.",
      "Vrai. Il est présent dans glycoprotéines et glycolipides.",
      "Faux. Le NANA participe précisément à la reconnaissance.",
    ],
  },
];
