import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SYNTHESIS_SECTION_ORDER = 5;

export const SYNTHESIS_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  121: ["Synthèse : formule et classification"],
  122: ["Synthèse : trioses"],
  123: ["Synthèse : aldohexoses"],
  124: ["Synthèse : épimères du glucose"],
  125: ["Synthèse : cyclisation du glucose"],
  126: ["Synthèse : anomères"],
  127: ["Synthèse : équilibre des formes"],
  128: ["Synthèse : pouvoir rotatoire"],
  129: ["Synthèse : activité optique"],
  130: ["Synthèse transversale"],
  131: ["Synthèse avancée : cétohexose"],
  132: ["Synthèse avancée : lecture de Fischer"],
  133: ["Synthèse avancée : galactose"],
  134: ["Synthèse clinique : galactosémie"],
  135: ["Synthèse expérimentale : mutarotation"],
  136: ["Synthèse calculatoire : mélange d'énantiomères"],
  137: ["Synthèse structurale : furanose et pyranose"],
  138: ["Synthèse : D-fructose"],
  139: ["Synthèse : formation du beta-D-glucopyranose"],
  140: ["Synthèse finale"],
};

export const SYNTHESIS_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "sentrainer-synthese-glucides-generalites-structure",
    title: "Révision transversale des glucides",
    description: "Consolidation transversale des notions structurales et stéréochimiques du chapitre.",
    stage: 'PRACTICE',
    sectionOrder: SYNTHESIS_SECTION_ORDER,
    questionOrders: [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
  },
  {
    order: 2,
    slug: "synthese-glucides-generalites-structure",
    title: "Examen blanc – Glucides : généralités et structure",
    description: "QCM de niveau examen combinant classification, Fischer, épimérie, cyclisation, mutarotation et calculs simples de pouvoir rotatoire.",
    stage: 'MASTER',
    sectionOrder: SYNTHESIS_SECTION_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 131 },
      {
        type: 'GROUP',
        title: "Comparaison de trois aldohexoses",
        sharedStatement: "On compare les motifs de Fischer du D-glucose, du D-mannose et du D-galactose, ainsi que leur reconnaissance par des enzymes stéréospécifiques.",
        questionOrders: [132, 133, 134],
      },
      {
        type: 'GROUP',
        title: "Mesures polarimétriques",
        sharedStatement: "Une solution d'oses chiraux peut évoluer par interconversion des anomères ou présenter une rotation résultante dépendant des proportions d'énantiomères.",
        questionOrders: [135, 136],
      },
      { type: 'QUESTION', questionOrder: 137 },
      { type: 'QUESTION', questionOrder: 138 },
      { type: 'QUESTION', questionOrder: 139 },
      { type: 'QUESTION', questionOrder: 140 },
    ],
  },
];

export const SYNTHESIS_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos d'un ose linéaire de formule $\\mathrm{C_5H_{10}O_5}$ :",
    choices: [
      "Il s'agit d'un pentose.",
      "Il peut être aldose ou cétose.",
      "Sa formule brute suffit à déterminer sa série D ou L.",
      "Il respecte la formule générale $\\mathrm{C_nH_{2n}O_n}$.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Cinq carbones définissent un pentose. La formule brute seule ne précise ni la fonction carbonyle ni la stéréochimie.",
    choiceExplanations: [
      "Classification correcte.",
      "Les deux familles sont possibles.",
      "Une projection spatiale est nécessaire.",
      "Le rapport 1:2:1 est respecté.",
    ],
  },
  {
    order: 122,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le glycéraldéhyde et la dihydroxyacétone permettent d'illustrer simultanément :",
    choices: [
      "L'isomérie de fonction.",
      "La différence entre aldose et cétose.",
      "La différence entre molécule chirale et achirale.",
      "Une paire d'énantiomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Ces deux trioses partagent une formule brute, mais diffèrent par leur fonction et par la présence d'un centre chiral.",
    choiceExplanations: [
      "Aldéhyde contre cétone.",
      "Aldotriose contre cétotriose.",
      "Le premier est chiral, le second achiral.",
      "Leur connectivité différente exclut l'énantiomérie.",
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un aldohexose de série D :",
    choices: [
      "Possède quatre carbones asymétriques dans sa forme linéaire usuelle.",
      "Appartient à un ensemble de 16 stéréoisomères.",
      "A le OH de C5 à droite en Fischer.",
      "Est nécessairement dextrogyre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Un aldohexose possède $6-2=4$ centres et $2^4=16$ stéréoisomères ; D se lit en C5, sans prédire le signe optique.",
    choiceExplanations: [
      "Décompte correct.",
      "Calcul correct.",
      "Critère correct.",
      "D et + sont indépendants.",
    ],
  },
  {
    order: 124,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le D-glucose, le D-mannose et le D-galactose :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "Sont des aldohexoses.",
      "Appartiennent tous à la série D.",
      "Le mannose est épimère du glucose en C2.",
      "Le galactose est épimère du glucose en C4.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Ces trois oses appartiennent à la même famille et se distinguent par des configurations précises.",
    choiceExplanations: [
      "Famille correcte.",
      "Leur dernier OH est à droite.",
      "Relation correcte.",
      "Relation correcte.",
    ],
  },
  {
    order: 125,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Après cyclisation du D-glucose :",
    choices: [
      "C1 devient le carbone anomérique.",
      "Des formes α et β apparaissent.",
      "La forme pyranique implique C1 et C5.",
      "La formule brute devient $\\mathrm{C_6H_{10}O_5}$.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La cyclisation est intramoléculaire et conserve $\\mathrm{C_6H_{12}O_6}$ ; elle crée le centre anomérique C1.",
    choiceExplanations: [
      "Conséquence exacte.",
      "Deux orientations possibles.",
      "Fermeture pyranique exacte.",
      "Aucune molécule d'eau n'est perdue dans le bilan de cette cyclisation.",
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparer α-D-glucopyranose et β-D-glucopyranose :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-cyclization-anomers',
    },
    choices: [
      "Ils ont la même formule brute.",
      "Ils diffèrent seulement en C1.",
      "Ils sont anomères et diastéréoisomères.",
      "Ils sont images miroir complètes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux formes diffèrent au seul carbone anomérique et ne sont donc pas énantiomères.",
    choiceExplanations: [
      "Composition identique.",
      "C1 est le carbone anomérique.",
      "Catégories correctes.",
      "Les autres centres restent identiques.",
    ],
  },
  {
    order: 127,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À pH 7, une solution de glucose à l'équilibre contient :",
    choices: [
      "Une très grande majorité de formes cycliques.",
      "Environ deux fois plus de forme β que de forme α.",
      "Une petite fraction linéaire.",
      "Uniquement l'anomère α.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La fiche retient environ 99 % de formes cycliques, réparties approximativement en 1/3 α et 2/3 β.",
    choiceExplanations: [
      "Proportion globale correcte.",
      "Rapport approximatif correct.",
      "Complément à 100 %.",
      "Les deux anomères coexistent.",
    ],
  },
  {
    order: 128,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La rotation optique d'un ose en solution dépend notamment :",
    choices: [
      "De sa configuration spatiale.",
      "De la composition du mélange en anomères.",
      "Du signe et de la proportion de ses énantiomères.",
      "Uniquement de la lettre D ou L.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le pouvoir rotatoire est une propriété expérimentale influencée par la composition stéréoisomérique.",
    choiceExplanations: [
      "La chiralité est déterminante.",
      "Les anomères ont des rotations différentes.",
      "La moyenne pondérée peut s'annuler.",
      "D/L ne prédit pas le signe.",
    ],
  },
  {
    order: 129,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un laboratoire observe une rotation nulle pour une solution contenant un ose chiral. Cette observation peut s'expliquer par :",
    choices: [
      "Un mélange racémique.",
      "Des proportions égales d'une paire d'énantiomères.",
      "L'annulation de rotations opposées.",
      "La certitude que chaque molécule est achirale.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Une solution peut être optiquement inactive par compensation externe alors que chaque molécule est chirale.",
    choiceExplanations: [
      "Explication possible.",
      "Condition du racémique.",
      "Mécanisme correct.",
      "L'inactivité globale ne prouve pas l'achiralité individuelle.",
    ],
  },
  {
    order: 130,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Concernant les glucides du chapitre :",
    choices: [
      "Leur structure explique des rôles biologiques et des reconnaissances enzymatiques.",
      "La stéréochimie peut avoir des conséquences pathologiques.",
      "La galactosémie illustre l'importance d'une épimérase.",
      "Tous les items précédents sont vrais.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Structure, stéréochimie et fonctionnement biologique sont étroitement liés ; l'item récapitulatif est vrai.",
    choiceExplanations: [
      "Principe général.",
      "Les enzymes peuvent être stéréospécifiques.",
      "Exemple médical du cours.",
      "A, B et C étant vraies, cet item l'est aussi.",
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "On étudie un ose linéaire à six carbones dont le carbonyle est une cétone en C2. Il possède trois carbones asymétriques. On peut conclure que :",
    choices: [
      "C'est un cétohexose.",
      "Il peut présenter $2^3=8$ stéréoisomères.",
      "Le fructose appartient à cette catégorie.",
      "Son carbone anomérique après cyclisation sera C1.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le cétohexose possède trois centres chiraux linéaires et un carbone anomérique dérivé du carbonyle C2.",
    choiceExplanations: [
      "Classification correcte.",
      "Calcul correct.",
      "Exemple classique.",
      "Le centre anomérique est C2.",
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une projection de Fischer d'un aldohexose donne le motif des OH C2→C5 : G-G-D-D. Le motif du D-glucose est D-G-D-D. On peut conclure que l'ose étudié :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "Diffère du D-glucose uniquement en C2.",
      "Est le D-mannose.",
      "Est épimère du D-glucose.",
      "Appartient à la série L.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le seul changement D→G en C2 correspond au D-mannose ; le dernier OH reste à droite.",
    choiceExplanations: [
      "Comparaison correcte.",
      "Identification correcte.",
      "Relation correcte.",
      "Le C5 à droite définit D.",
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une projection de Fischer d'un aldohexose donne D-G-G-D pour C2→C5. Comparée au D-glucose D-G-D-D :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "La différence porte sur C4.",
      "L'ose peut être le D-galactose.",
      "Les deux sont épimères.",
      "Les deux sont énantiomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le D-galactose est l'épimère en C4 du D-glucose.",
    choiceExplanations: [
      "Comparaison correcte.",
      "Identification correcte.",
      "Un seul centre varie.",
      "Une paire d'énantiomères inverserait tous les centres.",
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un déficit d'épimérase empêche une conversion métabolique du galactose. Dans ce contexte :",
    choices: [
      "Le galactose et le glucose diffèrent en C4.",
      "La reconnaissance du substrat est stéréospécifique.",
      "Une galactosémie peut en résulter.",
      "Le galactose est un cétose alors que le glucose est un aldose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'exemple associe une différence de configuration en C4 à une enzyme spécifique ; les deux oses sont des aldoses.",
    choiceExplanations: [
      "Relation structurale exacte.",
      "Principe enzymatique.",
      "Conséquence clinique citée.",
      "Les deux sont des aldohexoses.",
    ],
  },
  {
    order: 135,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "On part d'α-D-glucopyranose pur, de rotation $+113^\\circ$. Après mise en solution, la valeur mesurée se rapproche d'une valeur intermédiaire. Cela traduit :",
    choices: [
      "Une interconversion vers l'anomère β.",
      "Le passage transitoire par une forme linéaire.",
      "Une mutarotation.",
      "La transformation complète en L-glucose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La rotation évolue parce que les anomères α et β s'équilibrent par ouverture et fermeture du cycle.",
    choiceExplanations: [
      "Mécanisme correct.",
      "Intermédiaire correct.",
      "Nom du phénomène.",
      "Aucun renversement de tous les centres n'a lieu.",
    ],
  },
  {
    order: 136,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: "Une solution contient 60 % d'un énantiomère de rotation $+40^\\circ$ et 40 % de son énantiomère de rotation $-40^\\circ$. La rotation moyenne vaut :",
    choices: [
      "$0^\\circ$.",
      "$+8^\\circ$.",
      "$+16^\\circ$.",
      "$-8^\\circ$.",
    ],
    correctChoiceIndexes: [1],
    explanation: "La moyenne pondérée vaut $0{,}60\\times40+0{,}40\\times(-40)=8^\\circ$.",
    choiceExplanations: [
      "La solution n'est pas racémique.",
      "Calcul correct.",
      "Cette valeur double l'excès énantiomérique effectif.",
      "L'énantiomère positif est majoritaire.",
    ],
  },
  {
    order: 137,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "On compare une forme furanique du glucose et une forme pyranique du glucose :",
    choices: [
      "Les tailles de cycle diffèrent.",
      "La première peut résulter d'une fermeture C1–C4.",
      "La seconde peut résulter d'une fermeture C1–C5.",
      "Elles possèdent nécessairement des formules brutes différentes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux cycles résultent de fermetures intramoléculaires différentes, sans modification de la formule brute.",
    choiceExplanations: [
      "Cinq contre six sommets.",
      "Fermeture furanique correcte.",
      "Fermeture pyranique correcte.",
      "La composition atomique reste identique.",
    ],
  },
  {
    order: 138,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Le D-fructose peut être simultanément décrit comme :",
    choices: [
      "Un cétohexose dans sa forme linéaire.",
      "Un ose de série D.",
      "Un composé lévogyre dans l'exemple du cours.",
      "Une preuve que D signifie toujours dextrogyre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le D-fructose est le contre-exemple classique D(−), tout en étant un cétohexose.",
    choiceExplanations: [
      "Classification correcte.",
      "Série correcte.",
      "Signe optique cité.",
      "Il prouve précisément l'indépendance des notations.",
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour passer d'une forme linéaire de D-glucose à β-D-glucopyranose, il faut :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-cyclization-anomers',
    },
    choices: [
      "Former un cycle C1–C5.",
      "Créer un nouveau centre asymétrique en C1.",
      "Orienter le OH anomérique cis au groupe $\\mathrm{CH_2OH}$.",
      "Inverser tous les centres chiraux pour obtenir la série L.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La cyclisation pyranique crée C1 anomérique ; la disposition cis définit β dans la convention du D-ose.",
    choiceExplanations: [
      "Fermeture correcte.",
      "Conséquence correcte.",
      "Définition de β.",
      "Les centres préexistants et la série D sont conservés.",
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Bilan transversal du chapitre :",
    choices: [
      "La formule brute ne suffit pas à décrire la stéréochimie.",
      "La cyclisation ajoute un centre anomérique.",
      "Des enzymes peuvent distinguer des configurations très proches.",
      "Tous les items précédents sont vrais.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le chapitre relie composition, structure tridimensionnelle, cyclisation et reconnaissance biologique ; l'item récapitulatif est vrai.",
    choiceExplanations: [
      "Limite essentielle de la formule brute.",
      "Conséquence de la fermeture du carbonyle.",
      "Principe de stéréospécificité.",
      "A, B et C étant vraies, cet item l'est aussi.",
    ],
  },
];
