/**
 * Cartographie éditoriale V2
 * UE14 – Chimie organique – Chapitre 2.6
 * Les aldéhydes et les cétones
 */

export const UE14_CH10_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'section-a-discovery-aldehydes-cetones',
    title: `Aldéhydes et cétones : reconnaissance et préparation`,
    description: `Repères sur les fonctions aldéhyde et cétone, leur nomenclature et les premières voies de préparation.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'section-a-practice-preparation-oxydation',
    title: `Aldéhydes et cétones : reconnaissance et préparation`,
    description: `Applications sur l'oxydation des alcools et alcènes et la réduction contrôlée des dérivés d'acide vers les aldéhydes.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,21,22],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'section-b-discovery-polarite-carbonyle',
    title: `Polarité du carbonyle, hydrures et organomagnésiens`,
    description: `Repères sur le carbone carbonylé électrophile, les carbones voisins et les nucléophiles hydrure et organomagnésien.`,
    stage: 'DISCOVER' as const,
    questionOrders: [23,24,25,26,27,28,29,30,31,32],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'section-b-practice-reduction-hydrures',
    title: `Polarité du carbonyle, hydrures et organomagnésiens`,
    description: `Applications sur les réductions par NaBH4 et les additions d'organomagnésiens avec détermination de la classe d'alcool.`,
    stage: 'PRACTICE' as const,
    questionOrders: [33,34,35,36,37,38,39,40,41,42,43,44],
  },
  {
    sectionOrder: 2,
    order: 3,
    slug: 'section-b-master-addition-organomagnesiens',
    title: `Polarité du carbonyle, hydrures et organomagnésiens`,
    description: `Maîtrise de la polarité du carbonyle, du bilan carboné des nucléophiles et des produits de réduction ou d'addition.`,
    stage: 'MASTER' as const,
    questionOrders: [45,46,47,48,49,50,51,52,53,54,55,56],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'section-c-discovery-reactions-amines',
    title: `Amines, fonctionnalisation alpha et oxydabilité`,
    description: `Repères sur les réactions avec les amines, les imines/iminium, la position alpha et l'oxydabilité des carbonyles.`,
    stage: 'DISCOVER' as const,
    questionOrders: [57,58,59,60,61,62,63,64,65,66],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'section-c-practice-fonctionnalisation-alpha',
    title: `Amines, fonctionnalisation alpha et oxydabilité`,
    description: `Applications sur la classe de l'amine, la base forte suivie d'un électrophile et le contraste aldéhyde/cétone à l'oxydation.`,
    stage: 'PRACTICE' as const,
    questionOrders: [67,68,69,70,71,72,73,74,75,76,77,78],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'section-d-discovery-sucres-reducteurs',
    title: `Application aux sucres`,
    description: `Repères sur le caractère réducteur dans le modèle de la fiche et sur la lecture de la représentation linéaire du glucose.`,
    stage: 'DISCOVER' as const,
    questionOrders: [79,80,81,82,83,84,85,86,87,88],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'section-d-practice-representations-sucres',
    title: `Application aux sucres`,
    description: `Applications sur les représentations linéaires et tridimensionnelles et la cyclisation d'un sucre aldéhydique en hémiacétal.`,
    stage: 'PRACTICE' as const,
    questionOrders: [89,90,91,92,93,94,95,96,97,98,99,100],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'section-e-synthesis-practice-aldehydes-cetones',
    title: `Aldéhydes et cétones`,
    description: `Synthèse appliquée des préparations, propriétés électroniques, réactions nucléophiles, oxydabilité et application aux sucres.`,
    stage: 'PRACTICE' as const,
    questionOrders: [101,102,103,104,105,106,107,108,109,110],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'maitriser-synthese-aldehydes-cetones',
    title: `Aldéhydes et cétones`,
    description: `Maîtrise transversale des composés carbonylés et des applications aux sucres, dans des situations proches de l'examen.`,
    stage: 'MASTER' as const,
    questionOrders: [111,112,113,114,115,116,117,118,119,120,121,122],
  },
] as const;

export const UE14_CH10_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Aldéhydes et cétones : reconnaissance`],
  2: [`Méthanal, formaldéhyde et formol`],
  3: [`Aldéhydes et cétones : reconnaissance`],
  4: [`Aldéhydes et cétones : reconnaissance`],
  5: [`Propanone et acétone`],
  6: [`Aldéhydes et cétones : reconnaissance`],
  7: [`Aldéhydes et cétones : reconnaissance`],
  8: [`Aldéhydes et cétones : reconnaissance`],
  9: [`Aldéhydes et cétones : reconnaissance`],
  10: [`Aldéhydes et cétones : reconnaissance`],
  11: [`Aldéhydes et cétones : préparation`],
  12: [`Aldéhydes et cétones : préparation`],
  13: [`Aldéhydes et cétones : préparation`],
  14: [`Réduction des acides carboxyliques`],
  15: [`Aldéhydes et cétones : préparation`],
  16: [`Chlorure d'acyle vers aldéhyde`],
  17: [`Aldéhydes et cétones : préparation`],
  18: [`Aldéhydes et cétones : préparation`],
  19: [`Aldéhydes et cétones : préparation`],
  20: [`Aldéhydes et cétones : préparation`],
  21: [`Préparation : synthèse QRPL`],
  22: [`Aldéhydes et cétones : préparation`],
  23: [`Polarisation du carbonyle`],
  24: [`Carbonyle : polarité et nucléophiles`],
  25: [`Carbone alpha portant H`],
  26: [`Carbonyle : polarité et nucléophiles`],
  27: [`Carbonyle : polarité et nucléophiles`],
  28: [`Carbonyle : polarité et nucléophiles`],
  29: [`Aldéhyde + hydrure → alcool primaire`],
  30: [`Cétone + hydrure → alcool secondaire`],
  31: [`Carbonyle : polarité et nucléophiles`],
  32: [`Carbonyle : polarité et nucléophiles`],
  33: [`Hydrures et organomagnésiens : applications`],
  34: [`Hydrures et organomagnésiens : applications`],
  35: [`Aldéhyde + organomagnésien`],
  36: [`Cétone + organomagnésien`],
  37: [`Hydrures et organomagnésiens : applications`],
  38: [`Hydrures et organomagnésiens : applications`],
  39: [`Hydrures et organomagnésiens : applications`],
  40: [`Hydrures et organomagnésiens : applications`],
  41: [`Hydrures et organomagnésiens : applications`],
  42: [`Hydrures et organomagnésiens : applications`],
  43: [`Hydrures et organomagnésiens : applications`],
  44: [`Hydrures et organomagnésiens : applications`],
  45: [`Carbonyle et Grignard : maîtrise`],
  46: [`Carbonyle et Grignard : maîtrise`],
  47: [`Carbonyle et Grignard : maîtrise`],
  48: [`Carbonyle et Grignard : maîtrise`],
  49: [`Carbonyle et Grignard : maîtrise`],
  50: [`QZONE : carbone carbonylé électrophile`],
  51: [`Carbonyle et Grignard : maîtrise`],
  52: [`Carbonyle et Grignard : maîtrise`],
  53: [`Carbonyle et Grignard : maîtrise`],
  54: [`Carbonyle et Grignard : maîtrise`],
  55: [`Polarité, hydrures et Grignard : QRPL`],
  56: [`Carbonyle et Grignard : maîtrise`],
  57: [`Amines, position alpha et oxydabilité : repères`],
  58: [`Amine primaire + carbonyle → imine`],
  59: [`Amine secondaire + aldéhyde → iminium`],
  60: [`Amines, position alpha et oxydabilité : repères`],
  61: [`Amines, position alpha et oxydabilité : repères`],
  62: [`Amines, position alpha et oxydabilité : repères`],
  63: [`Amines, position alpha et oxydabilité : repères`],
  64: [`Fonctionnalisation alpha : base forte puis électrophile`],
  65: [`Amines, position alpha et oxydabilité : repères`],
  66: [`Oxydabilité aldéhyde/cétone`],
  67: [`Amines, position alpha et oxydabilité : applications`],
  68: [`Amines, position alpha et oxydabilité : applications`],
  69: [`Amines, position alpha et oxydabilité : applications`],
  70: [`Amines, position alpha et oxydabilité : applications`],
  71: [`Amines, position alpha et oxydabilité : applications`],
  72: [`Amines, position alpha et oxydabilité : applications`],
  73: [`Amines, position alpha et oxydabilité : applications`],
  74: [`Amines, position alpha et oxydabilité : applications`],
  75: [`Amines, position alpha et oxydabilité : applications`],
  76: [`Amines, position alpha et oxydabilité : applications`],
  77: [`Amines, position alpha et oxydabilité : applications`],
  78: [`Amines, alpha et oxydabilité : QRPL`],
  79: [`Sucres réducteurs : modèle de la fiche`],
  80: [`Sucres : caractère réducteur et représentation linéaire`],
  81: [`Sucres : caractère réducteur et représentation linéaire`],
  82: [`Sucres : caractère réducteur et représentation linéaire`],
  83: [`Glucose : lecture de la représentation linéaire`],
  84: [`Sucres : caractère réducteur et représentation linéaire`],
  85: [`Sucres : caractère réducteur et représentation linéaire`],
  86: [`Projection linéaire et géométrie 3D`],
  87: [`Sucres : caractère réducteur et représentation linéaire`],
  88: [`Cyclisation en hémiacétal`],
  89: [`Sucres : représentation et cyclisation`],
  90: [`Sucres : représentation et cyclisation`],
  91: [`Sucres : représentation et cyclisation`],
  92: [`Sucres : représentation et cyclisation`],
  93: [`Sucres : représentation et cyclisation`],
  94: [`Sucres : représentation et cyclisation`],
  95: [`Sucres : représentation et cyclisation`],
  96: [`Sucres : représentation et cyclisation`],
  97: [`Sucres : représentation et cyclisation`],
  98: [`Sucres : représentation et cyclisation`],
  99: [`Glucose/fructose : QRP selon la fiche`],
  100: [`Sucres : synthèse QRPL`],
  101: [`Synthèse appliquée des composés carbonylés`],
  102: [`Synthèse appliquée des composés carbonylés`],
  103: [`Synthèse appliquée des composés carbonylés`],
  104: [`Synthèse appliquée des composés carbonylés`],
  105: [`Synthèse appliquée des composés carbonylés`],
  106: [`Synthèse appliquée des composés carbonylés`],
  107: [`Synthèse appliquée des composés carbonylés`],
  108: [`Synthèse appliquée des composés carbonylés`],
  109: [`Création de liaisons C-C : QRP`],
  110: [`Synthèse PRACTICE QRPL`],
  111: [`Chlorure d'acyle → aldéhyde → alcool`],
  112: [`Maîtrise transversale aldéhydes/cétones`],
  113: [`Maîtrise transversale aldéhydes/cétones`],
  114: [`Maîtrise transversale aldéhydes/cétones`],
  115: [`Maîtrise transversale aldéhydes/cétones`],
  116: [`Maîtrise transversale aldéhydes/cétones`],
  117: [`Glucose : fonctions et représentation`],
  118: [`Maîtrise transversale aldéhydes/cétones`],
  119: [`Maîtrise transversale aldéhydes/cétones`],
  120: [`Maîtrise transversale aldéhydes/cétones`],
  121: [`Maîtrise transversale aldéhydes/cétones`],
  122: [`Synthèse générale QRPL`],
};
