import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_ORDER = 3;

export const SECTION_C_HYDROLYSIS_DISCOVERY_QUIZ_SLUG =
  `section-c-discovery-hydrolyse-amides-selectivite`;
export const SECTION_C_ENZYMES_PRACTICE_QUIZ_SLUG =
  `section-c-practice-enzymes-esterases-proteases`;
export const SECTION_C_RESONANCE_MASTER_QUIZ_SLUG =
  `section-c-master-amide-double-liaison-partielle`;

export const SECTION_C_HYDROLYSIS_DISCOVERY_QUESTION_ORDERS: number[] = [61, 62, 63, 64, 65, 66, 67, 68, 69, 70];
export const SECTION_C_ENZYMES_PRACTICE_QUESTION_ORDERS: number[] = [71, 72, 73, 74, 75, 76, 77, 78, 79, 80];
export const SECTION_C_RESONANCE_MASTER_QUESTION_ORDERS: number[] = [81, 82, 83, 84, 85, 86, 87, 88, 89, 90];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: SECTION_C_HYDROLYSIS_DISCOVERY_QUIZ_SLUG,
    title: `Hydrolyse des amides et sélectivité`,
    description: `Comprendre pourquoi l'hydrolyse d'une amide exige des conditions plus sévères que celle d'un ester et prévoir l'ordre de rupture des fonctions.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_C_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 61 },
      { type: 'QUESTION', questionOrder: 62 },
      { type: 'QUESTION', questionOrder: 63 },
      { type: 'QUESTION', questionOrder: 64 },
      { type: 'QUESTION', questionOrder: 65 },
      { type: 'QUESTION', questionOrder: 66 },
      { type: 'QUESTION', questionOrder: 67 },
      {
        type: 'GROUP',
        title: `Une molécule portant un ester et une amide`,
        sharedStatement: `Une molécule bifonctionnelle comporte une fonction ester et une fonction amide. Elle est soumise d'abord à des conditions d'hydrolyse douces, puis, dans une seconde expérience, à un milieu très acide avec chauffage.`,
        questionOrders: [68, 69, 70],
      },
    ],
  },
  {
    order: 8,
    slug: SECTION_C_ENZYMES_PRACTICE_QUIZ_SLUG,
    title: `Hydrolyses enzymatiques : estérases et protéases`,
    description: `Associer les estérases aux fonctions ester et les peptidases ou protéases aux liaisons amide des peptides.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_C_ORDER,
    questionOrders: SECTION_C_ENZYMES_PRACTICE_QUESTION_ORDERS,
  },
  {
    order: 9,
    slug: SECTION_C_RESONANCE_MASTER_QUIZ_SLUG,
    title: `Amide : double liaison partielle et rotation`,
    description: `Relier la délocalisation du doublet de l'azote au caractère partiel de double liaison, à la rotation limitée et à la faible disponibilité du doublet.`,
    stage: 'MASTER',
    sectionOrder: SECTION_C_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 81 },
      { type: 'QUESTION', questionOrder: 82 },
      { type: 'QUESTION', questionOrder: 83 },
      { type: 'QUESTION', questionOrder: 84 },
      { type: 'QUESTION', questionOrder: 85 },
      { type: 'QUESTION', questionOrder: 86 },
      { type: 'QUESTION', questionOrder: 87 },
      {
        type: 'GROUP',
        title: `Une liaison peptidique soumise à une rotation`,
        sharedStatement: `On étudie le motif peptidique $\mathrm{-C(=O){-}NH-}$. L'oxygène attire le doublet libre de l'azote, ce qui donne à la liaison $\mathrm{C{-}N}$ un caractère partiel de double liaison.`,
        questionOrders: [88, 89, 90],
      },
    ],
  },
];

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'hydrolyse d'une amide :`,
    choices: [
      `Elle est possible.`,
      `Elle nécessite des conditions plus sévères que pour un ester.`,
      `Elle est toujours instantanée à pH neutre et à froid.`,
      `Elle peut conduire à un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fonction amide est hydrolysable, mais sa rupture est nettement plus difficile que celle d'un ester.`,
    choiceExplanations: [
      `La fiche présente un bilan d'hydrolyse de l'amide.`,
      `L'amide est plus résistante.`,
      `Un milieu très acide et du chauffage sont indiqués.`,
      `Le fragment acyle devient $\mathrm{RCOOH}$ en milieu acide.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les conditions chimiques citées pour hydrolyser une amide comprennent :`,
    choices: [
      `Un milieu très acide.`,
      `Du chauffage.`,
      `Un milieu nécessairement très basique sans chauffage.`,
      `Des conditions plus dures que pour l'hydrolyse d'un ester.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche associe l'hydrolyse chimique de l'amide à un pH très faible et à un apport d'énergie par chauffage.`,
    choiceExplanations: [
      `Le pH doit être fortement abaissé.`,
      `L'énergie facilite la rupture de la liaison amide.`,
      `Ce n'est pas le schéma présenté dans la fiche.`,
      `L'amide est plus stable vis-à-vis de l'hydrolyse.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le bilan acide simplifié de l'hydrolyse d'une amide $\mathrm{RCONHR'}$ peut donner :`,
    choices: [
      `$\mathrm{RCOOH}$.`,
      `$\mathrm{R'NH_3^+}$ pour une amide issue d'une amine primaire.`,
      `Uniquement un ester.`,
      `Une rupture de la liaison entre le carbonyle et l'azote.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `En milieu fortement acide, on obtient l'acide carboxylique et la forme protonée de l'amine.`,
    choiceExplanations: [
      `Le groupe acyle devient acide carboxylique.`,
      `L'amine libérée est protonée dans le milieu acide.`,
      `La liaison $\mathrm{C{-}N}$ est rompue, elle ne devient pas automatiquement ester.`,
      `C'est l'événement central de l'hydrolyse.`,
    ],
  },
  {
    order: 64,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison de la sensibilité à l'hydrolyse :`,
    choices: [
      `L'ester peut être hydrolysé dans des conditions plus douces.`,
      `L'amide demande un milieu très acide et du chauffage.`,
      `L'amide est toujours hydrolysée avant l'ester.`,
      `La différence permet une hydrolyse sélective de l'ester.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'ester est plus fragile que l'amide dans les conditions chimiques générales décrites.`,
    choiceExplanations: [
      `Sa liaison est plus facilement rompue.`,
      `Ce sont les conditions sévères citées.`,
      `L'ordre est inverse en conditions non enzymatiques usuelles.`,
      `On peut choisir des conditions épargnant l'amide.`,
    ],
  },
  {
    order: 65,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans une molécule possédant à la fois un ester et une amide :`,
    choices: [
      `L'ester peut être hydrolysé sélectivement.`,
      `L'amide peut rester intacte dans ces conditions.`,
      `Il est impossible de distinguer les deux fonctions par leur hydrolyse.`,
      `La sélectivité dépend des conditions choisies.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Des conditions suffisamment douces peuvent hydrolyser l'ester tout en laissant l'amide intacte.`,
    choiceExplanations: [
      `Il est la fonction la plus fragile.`,
      `Sa rupture exige davantage d'énergie et d'acidité.`,
      `Leur différence de stabilité permet justement une sélectivité.`,
      `Des conditions douces favorisent la rupture de l'ester seulement.`,
    ],
  },
  {
    order: 66,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Si l'on applique des conditions suffisantes pour hydrolyser une amide dans une molécule contenant aussi un ester :`,
    choices: [
      `La fonction ester s'hydrolyse d'abord.`,
      `L'hydrolyse de l'amide exige des conditions sévères.`,
      `On peut conserver intact l'ester tout en hydrolysant chimiquement l'amide dans le schéma général du cours.`,
      `Les deux fonctions peuvent finalement être hydrolysées.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'ester, plus fragile, aura été hydrolysé avant que l'amide ne soit rompue.`,
    choiceExplanations: [
      `Elle résiste moins aux conditions hydrolytiques.`,
      `Le chauffage et la forte acidité sont cités.`,
      `L'ester est plus sensible et ne survivrait pas à ces conditions.`,
      `Les conditions fortes affectent l'ester puis l'amide.`,
    ],
  },
  {
    order: 67,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors de l'hydrolyse acide d'une amide N-substituée :`,
    choices: [
      `Le fragment carbonylé donne un acide carboxylique.`,
      `Le fragment azoté peut donner un ion ammonium.`,
      `Le milieu acide favorise une amine entièrement déprotonée.`,
      `La liaison amide est rompue.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le produit azoté est protoné dans le milieu acide, tandis que le fragment acyle devient acide carboxylique.`,
    choiceExplanations: [
      `Il devient $\mathrm{RCOOH}$.`,
      `L'amine formée capte un proton.`,
      `Il favorise au contraire la forme protonée.`,
      `La liaison $\mathrm{C(=O){-}N}$ disparaît.`,
    ],
  },
  {
    order: 68,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Après les conditions d'hydrolyse douces :`,
    choices: [
      `L'ester peut être hydrolysé.`,
      `L'amide peut rester intacte.`,
      `La fonction amide est nécessairement hydrolysée en premier.`,
      `Une sélectivité fonctionnelle est possible.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fonction ester est la cible privilégiée, tandis que l'amide peut être conservée.`,
    choiceExplanations: [
      `Il est plus fragile.`,
      `Les conditions ne sont pas assez sévères pour sa rupture.`,
      `Elle est plus résistante.`,
      `La différence de stabilité est exploitée.`,
    ],
  },
  {
    order: 69,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Après le milieu très acide avec chauffage :`,
    choices: [
      `L'amide peut être hydrolysée.`,
      `L'ester aura été hydrolysé auparavant.`,
      `L'ester est protégé par la présence de l'amide.`,
      `Les deux fonctions peuvent ne plus être présentes dans le produit final.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les conditions sont assez fortes pour atteindre l'amide, mais l'ester aura été hydrolysé avant elle.`,
    choiceExplanations: [
      `Les conditions correspondent à celles requises.`,
      `Il est plus sensible.`,
      `La présence de l'amide ne rend pas l'ester plus résistant.`,
      `Les deux liaisons peuvent avoir été rompues.`,
    ],
  },
  {
    order: 70,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La comparaison des deux expériences montre que :`,
    choices: [
      `La fonction ester est plus facilement hydrolysable.`,
      `La fonction amide est plus résistante.`,
      `Les conditions expérimentales contrôlent la sélectivité.`,
      `Ester et amide ont une stabilité strictement identique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La différence de stabilité hydrolytique permet de choisir des conditions ciblant l'ester seul ou les deux fonctions.`,
    choiceExplanations: [
      `Elle réagit dans les conditions douces.`,
      `Elle nécessite forte acidité et chauffage.`,
      `Leur intensité détermine les fonctions rompues.`,
      `Leur comportement est nettement différent.`,
    ],
  },
  {
    order: 71,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les estérases sont :`,
    choices: [
      `Des enzymes.`,
      `Capables d'hydrolyser des esters.`,
      `Nécessairement des acides minéraux très forts.`,
      `Impliquées dans certaines transformations physiologiques de molécules esterifiées.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les estérases sont des enzymes capables d'hydrolyser des fonctions ester dans l'organisme.`,
    choiceExplanations: [
      `Elles catalysent une réaction biologique.`,
      `Leur substrat porte une fonction ester.`,
      `Ce sont des protéines enzymatiques.`,
      `Elles permettent la rupture sélective de ces fonctions.`,
    ],
  },
  {
    order: 72,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les peptidases, également appelées protéases dans ce contexte :`,
    choices: [
      `Agissent sur les liaisons peptidiques.`,
      `Peuvent hydrolyser une fonction amide dans un peptide.`,
      `Sont des agents halogénants.`,
      `Comprennent des enzymes digestives.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Ces enzymes hydrolysent sélectivement les liaisons amide des peptides et protéines.`,
    choiceExplanations: [
      `La liaison peptidique est une amide.`,
      `Elles catalysent la rupture de la liaison $\mathrm{C{-}N}$.`,
      `Elles n'introduisent pas d'halogène.`,
      `La fiche cite plusieurs exemples digestifs.`,
    ],
  },
  {
    order: 73,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les enzymes suivantes, lesquelles sont citées comme peptidases digestives ?`,
    choices: [
      `La trypsine.`,
      `La chymotrypsine.`,
      `La pepsine.`,
      `La cellulose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La trypsine, la chymotrypsine et la pepsine sont les exemples indiqués.`,
    choiceExplanations: [
      `Elle fait partie des protéases digestives citées.`,
      `Elle hydrolyse des liaisons peptidiques.`,
      `Elle est également mentionnée.`,
      `La cellulose est un polysaccharide, pas une peptidase.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un médicament contient une fonction ester destinée à être hydrolysée dans l'organisme. L'enzyme la plus directement associée dans le cours est :`,
    choices: [
      `Une estérase.`,
      `Une protéase uniquement parce que toute molécule organique est une protéine.`,
      `Une enzyme pouvant libérer un acide carboxylique et un alcool.`,
      `Une enzyme qui transforme obligatoirement l'ester en amide.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Une estérase reconnaît et hydrolyse la fonction ester.`,
    choiceExplanations: [
      `Son nom et sa fonction correspondent au substrat ester.`,
      `La protéase cible surtout les liaisons peptidiques.`,
      `Ce sont les produits généraux de l'hydrolyse d'un ester.`,
      `L'hydrolyse rompt l'ester au lieu de le convertir en amide.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors de la digestion des protéines :`,
    choices: [
      `La trypsine peut intervenir.`,
      `La chymotrypsine peut intervenir.`,
      `La pepsine peut intervenir.`,
      `Aucune liaison amide n'est rompue.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Des protéases hydrolysent les liaisons peptidiques, donc des fonctions amide.`,
    choiceExplanations: [
      `Elle est une protéase digestive.`,
      `Elle est citée parmi les peptidases.`,
      `Elle participe à la digestion protéique.`,
      `Les liaisons peptidiques sont précisément des amides.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison entre hydrolyse chimique et hydrolyse enzymatique d'une amide :`,
    choices: [
      `Une protéase peut accélérer l'hydrolyse d'une liaison peptidique.`,
      `L'hydrolyse chimique générale demande forte acidité et chauffage.`,
      `Les enzymes rendent toute molécule totalement non sélective.`,
      `La nature du catalyseur modifie les conditions nécessaires.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Une enzyme peut catalyser sélectivement la rupture d'une liaison amide dans des conditions physiologiques, alors que la réaction chimique générale exige des conditions sévères.`,
    choiceExplanations: [
      `Elle abaisse la barrière de réaction de façon spécifique.`,
      `Ce sont les conditions du cours.`,
      `Elles se caractérisent au contraire par leur sélectivité.`,
      `La voie enzymatique permet la réaction dans l'organisme.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une molécule contient une fonction ester et une liaison peptidique. En milieu biologique :`,
    choices: [
      `Une estérase peut viser l'ester.`,
      `Une peptidase peut viser la liaison amide.`,
      `La fonction ester et la liaison peptidique sont chimiquement identiques.`,
      `La sélectivité enzymatique peut distinguer ces fonctions.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Des enzymes différentes peuvent cibler sélectivement les deux fonctions.`,
    choiceExplanations: [
      `C'est son type de substrat.`,
      `Elle hydrolyse les liaisons peptidiques.`,
      `L'une contient un oxygène, l'autre un azote après le carbonyle.`,
      `Chaque famille d'enzymes possède des substrats privilégiés.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La pepsine est citée dans le cours comme :`,
    choices: [
      `Une peptidase digestive.`,
      `Une enzyme agissant sur des liaisons amide de protéines.`,
      `Un chlorure d'acyle.`,
      `Une enzyme et non un milieu très acide à elle seule.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La pepsine est une protéase digestive capable de participer à l'hydrolyse de liaisons peptidiques.`,
    choiceExplanations: [
      `Elle appartient à la famille des protéases.`,
      `Les liaisons peptidiques sont des amides.`,
      `Ce n'est pas un réactif organique activé.`,
      `Il s'agit d'un catalyseur biologique.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'hydrolyse physiologique des esters :`,
    choices: [
      `Elle peut être catalysée par des enzymes.`,
      `Elle peut libérer un alcool.`,
      `Elle peut libérer un dérivé carboxylique.`,
      `Elle transforme obligatoirement l'ester en liaison peptidique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les estérases permettent la rupture de la fonction ester sans nécessiter les conditions chimiques extrêmes d'un laboratoire.`,
    choiceExplanations: [
      `Les estérases sont les enzymes correspondantes.`,
      `Le groupe alkoxy devient alcool après hydrolyse.`,
      `Le fragment acyle devient acide ou carboxylate selon le milieu.`,
      `L'hydrolyse rompt la liaison ester.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Synthèse sur les enzymes hydrolytiques :`,
    choices: [
      `Estérase → fonction ester.`,
      `Protéase → liaison peptidique.`,
      `Trypsine, chymotrypsine et pepsine sont des exemples de protéases.`,
      `Toutes les enzymes citées ont exactement le même substrat.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les estérases et les protéases illustrent une hydrolyse sélective selon la nature de la fonction organique.`,
    choiceExplanations: [
      `L'association est directe.`,
      `Elle hydrolyse une fonction amide de peptide.`,
      `Elles sont citées dans la fiche.`,
      `Les estérases et les protéases ciblent des fonctions différentes.`,
    ],
  },
  {
    order: 81,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la liaison $\mathrm{C{-}N}$ dans une amide :`,
    choices: [
      `Elle possède un caractère partiel de double liaison.`,
      `Sa rotation est fortement perturbée.`,
      `Elle se comporte exactement comme une liaison simple totalement libre.`,
      `La résonance avec le carbonyle explique ces propriétés.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La délocalisation du doublet de l'azote vers le carbonyle lui confère un caractère partiel de double liaison.`,
    choiceExplanations: [
      `La résonance renforce la liaison $\mathrm{C{-}N}$.`,
      `Une double liaison partielle limite la rotation.`,
      `La rotation nécessite un apport d'énergie.`,
      `Le doublet de l'azote est délocalisé.`,
    ],
  },
  {
    order: 82,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'oxygène de la fonction amide :`,
    choices: [
      `Est plus électroattracteur que le carbone.`,
      `Participe à l'attraction du doublet de l'azote.`,
      `Explique en partie le caractère partiel de double liaison $\mathrm{C{-}N}$.`,
      `Supprime l'atome d'azote de la molécule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Son caractère électroattracteur attire la densité électronique du doublet libre de l'azote.`,
    choiceExplanations: [
      `Il polarise le groupe carbonyle.`,
      `Cette interaction conduit à la délocalisation.`,
      `La résonance renforce cette liaison.`,
      `L'azote reste présent et lié au carbonyle.`,
    ],
  },
  {
    order: 83,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le doublet libre de l'azote d'une amide :`,
    choices: [
      `Participe à la résonance de la fonction amide.`,
      `Est moins disponible pour attaquer un électrophile.`,
      `Rend l'amide identique à une amine très basique.`,
      `Contribue à la rigidité de la liaison amide.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Il est délocalisé vers le carbonyle et est donc moins disponible que le doublet d'une amine simple.`,
    choiceExplanations: [
      `Il peut contribuer à une liaison $\mathrm{C{=}N}$ dans une forme limite.`,
      `La délocalisation réduit la nucléophilie de l'azote.`,
      `L'amide est moins basique et moins nucléophile qu'une amine.`,
      `La double liaison partielle limite la rotation.`,
    ],
  },
  {
    order: 84,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison entre une amine et une amide :`,
    choices: [
      `Une amine possède un doublet plus libre.`,
      `Une amide est généralement moins nucléophile sur l'azote.`,
      `Les deux ont obligatoirement exactement la même réactivité envers les électrophiles.`,
      `Le carbonyle de l'amide modifie les propriétés de l'azote.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le doublet de l'amine est plus disponible, tandis que celui de l'amide est délocalisé vers le carbonyle.`,
    choiceExplanations: [
      `Il n'est pas adjacent à un carbonyle dans une amine simple.`,
      `Son doublet participe à la résonance.`,
      `La disponibilité du doublet est différente.`,
      `Il attire et délocalise le doublet.`,
    ],
  },
  {
    order: 85,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La rotation autour de la liaison amide :`,
    choices: [
      `Est plus difficile que la rotation autour d'une liaison simple ordinaire.`,
      `Peut nécessiter un apport d'énergie ou du chauffage.`,
      `Est totalement impossible dans toutes les conditions.`,
      `Contribue à la rigidité des liaisons peptidiques.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Elle est limitée parce qu'une rotation détruirait partiellement la conjugaison entre l'azote et le carbonyle.`,
    choiceExplanations: [
      `Le caractère partiel de double liaison crée une barrière.`,
      `La fiche associe la rotation à un coût énergétique.`,
      `Elle est perturbée, mais peut avoir lieu avec suffisamment d'énergie.`,
      `La géométrie locale est contrainte.`,
    ],
  },
  {
    order: 86,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une forme limite de résonance d'une amide peut être représentée avec :`,
    choices: [
      `Une liaison $\mathrm{C{=}N}$.`,
      `Une charge négative portée par l'oxygène.`,
      `Une charge positive portée par l'azote.`,
      `La disparition complète du carbone carbonylé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le doublet de l'azote forme une liaison avec le carbone, tandis que la densité de la liaison carbonyle se déplace vers l'oxygène.`,
    choiceExplanations: [
      `Elle traduit la contribution du doublet de l'azote.`,
      `L'oxygène reçoit la densité électronique du carbonyle.`,
      `L'azote a donné son doublet à la liaison.`,
      `Le carbone reste au centre de la fonction.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La moindre réactivité nucléophile de l'azote d'une amide s'explique par :`,
    choices: [
      `La délocalisation du doublet vers le carbonyle.`,
      `Le caractère partiel de double liaison $\mathrm{C{-}N}$.`,
      `L'absence totale de doublet sur l'azote.`,
      `La présence du groupe carbonyle voisin.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le doublet est engagé dans la stabilisation par résonance et n'est donc pas aussi disponible que dans une amine.`,
    choiceExplanations: [
      `Elle réduit sa disponibilité locale.`,
      `Il est une conséquence de cette délocalisation.`,
      `Le doublet existe mais il est délocalisé.`,
      `C'est lui qui permet la conjugaison.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans le motif étudié, la liaison $\mathrm{C{-}N}$ :`,
    choices: [
      `A un caractère partiel de double liaison.`,
      `Est plus courte et plus rigide qu'une liaison simple pure dans le modèle qualitatif.`,
      `Tourne librement sans coût énergétique.`,
      `Participe à la rigidité du squelette peptidique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Elle est renforcée par la délocalisation électronique et n'est pas une simple liaison librement rotative.`,
    choiceExplanations: [
      `La forme limite $\mathrm{C{=}N}$ contribue à la structure.`,
      `Le renforcement de liaison accompagne la résonance.`,
      `La rotation perturbe la conjugaison.`,
      `La liaison peptidique est localement plane et contrainte dans ce modèle.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour effectuer une rotation importante autour de cette liaison :`,
    choices: [
      `Un chauffage peut être nécessaire.`,
      `Il faut perturber le recouvrement permettant la délocalisation.`,
      `La liaison doit conserver en permanence son caractère maximal de double liaison tout en tournant librement.`,
      `La barrière de rotation est liée à la résonance.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Il faut fournir de l'énergie afin de diminuer temporairement la conjugaison responsable de la double liaison partielle.`,
    choiceExplanations: [
      `Il apporte l'énergie mentionnée dans la fiche.`,
      `La rotation réduit la conjugaison.`,
      `Une double liaison empêche précisément la rotation libre.`,
      `C'est l'origine électronique de la rigidité.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Conséquences pour le peptide :`,
    choices: [
      `La liaison peptidique est localement contrainte.`,
      `Le doublet de l'azote est moins disponible pour une attaque électrophile.`,
      `Le motif devient un ester dès que la rotation est limitée.`,
      `La structure électronique influence la géométrie moléculaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La rigidité de la liaison amide réduit le nombre de conformations accessibles et participe à l'organisation du squelette peptidique.`,
    choiceExplanations: [
      `La rotation $\mathrm{C{-}N}$ est limitée.`,
      `Il est délocalisé dans le motif.`,
      `La nature de l'hétéroatome ne change pas.`,
      `La résonance a une conséquence conformationnelle directe.`,
    ],
  },
];
