/** Cartographie éditoriale V2 — auteur */

export const UE14_BIOCH_CH15_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-etat-stationnaire-vitesse",
    "title": "État stationnaire et vitesse initiale",
    "description": "Repères sur déroulement temporel, état stationnaire et définition de la vitesse initiale.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-beer-lambert-v0",
    "title": "Mesure spectrophotométrique de la vitesse initiale",
    "description": "Applications de Beer-Lambert et de la pente d’absorbance à la détermination de V0.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-ui-katal-kcat",
    "title": "UI, katal et Kcat",
    "description": "Repères sur UI, katal, Ccat, Kcat et saturation enzymatique.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-activites-specifiques",
    "title": "Paramètres d’activité enzymatique",
    "description": "Applications sur conversions et activités rapportées au volume, à la masse ou à la mole d’enzyme.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-michaelis-menten-km-vm",
    "title": "Michaelis-Menten, Km et Vm",
    "description": "Repères sur courbe de Michaelis-Menten, Km, Vm et affinité.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-lineweaver-ordres",
    "title": "Ordres de réaction et Lineweaver-Burk",
    "description": "Applications sur ordres de réaction, équation de Michaelis-Menten et représentation de Lineweaver-Burk.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-facteurs-activite",
    "title": "Facteurs modifiant l’activité enzymatique",
    "description": "Repères sur concentration en substrat/enzyme, pH et température.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-inhibiteurs-enzymatiques",
    "title": "Modes d’inhibition enzymatique",
    "description": "Applications comparant inhibitions compétitive, non compétitive, incompétitive et mixte.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-cinetique-inhibition",
    "title": "Cinétique et inhibition enzymatique",
    "description": "Maîtrise transversale de l’interprétation de données cinétiques et d’inhibition.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-mesure-activite",
    "title": "Synthèse : mesure d’une activité enzymatique",
    "description": "Consolidation de la mesure, des paramètres cinétiques et des inhibitions.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-mesure-activite-enzymatique",
    "title": "Synthèse : mesure d’une activité enzymatique",
    "description": "Maîtrise du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH15_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["la définition de la cinétique enzymatique"],
  2: ["la relation entre substrat et produit"],
  3: ["la condition [S] très supérieure à [E]"],
  4: ["la phase stationnaire"],
  5: ["la concentration totale en enzyme"],
  6: ["la vitesse initiale"],
  7: ["la pente ΔA/Δt"],
  8: ["la loi de Beer-Lambert appliquée à la cinétique"],
  9: ["la formule de la vitesse initiale par absorbance"],
  10: ["l’état préstationnaire et poststationnaire"],
  11: ["la condition [S] très supérieure à [E]"],
  12: ["la phase stationnaire"],
  13: ["la concentration totale en enzyme"],
  14: ["la vitesse initiale"],
  15: ["la pente ΔA/Δt"],
  16: ["la condition [S] très supérieure à [E]"],
  17: ["la formule de la vitesse initiale par absorbance"],
  18: ["l’état préstationnaire et poststationnaire"],
  19: ["la concentration totale en enzyme"],
  20: ["la relation entre substrat et produit"],
  21: ["la définition de la cinétique enzymatique", "la relation entre substrat et produit", "la condition [S] très supérieure à [E]"],
  22: ["la relation entre substrat et produit", "la condition [S] très supérieure à [E]", "la phase stationnaire", "la concentration totale en enzyme", "la vitesse initiale"],
  23: ["l’unité internationale UI"],
  24: ["le katal"],
  25: ["la conversion UI-nkat"],
  26: ["la concentration d’activité catalytique Ccat"],
  27: ["la constante catalytique Kcat"],
  28: ["les exemples de Kcat"],
  29: ["l’activité spécifique"],
  30: ["l’activité molaire spécifique"],
  31: ["la distinction Ccat, activité spécifique et AMS"],
  32: ["la saturation enzymatique et Kcat"],
  33: ["la conversion UI-nkat"],
  34: ["la concentration d’activité catalytique Ccat"],
  35: ["la constante catalytique Kcat"],
  36: ["les exemples de Kcat"],
  37: ["l’activité spécifique"],
  38: ["l’unité internationale UI"],
  39: ["la distinction Ccat, activité spécifique et AMS"],
  40: ["la saturation enzymatique et Kcat"],
  41: ["la conversion UI-nkat"],
  42: ["le katal"],
  43: ["l’unité internationale UI", "le katal", "la conversion UI-nkat"],
  44: ["le katal", "la conversion UI-nkat", "la concentration d’activité catalytique Ccat", "la constante catalytique Kcat", "les exemples de Kcat"],
  45: ["la courbe de Michaelis-Menten"],
  46: ["la définition de Km par Vmax/2"],
  47: ["l’affinité et Km"],
  48: ["les exemples de Km"],
  49: ["l’équation de Michaelis-Menten"],
  50: ["la réaction d’ordre zéro"],
  51: ["la réaction d’ordre un"],
  52: ["la réaction d’ordre deux"],
  53: ["la représentation de Lineweaver-Burk"],
  54: ["le repère d’abscisse de Lineweaver-Burk dans la fiche"],
  55: ["l’affinité et Km"],
  56: ["les exemples de Km"],
  57: ["l’équation de Michaelis-Menten"],
  58: ["la réaction d’ordre zéro"],
  59: ["la réaction d’ordre un"],
  60: ["la définition de Km par Vmax/2"],
  61: ["la représentation de Lineweaver-Burk"],
  62: ["le repère d’abscisse de Lineweaver-Burk dans la fiche"],
  63: ["la détermination pratique de Km et Vmax"],
  64: ["la courbe de Michaelis-Menten"],
  65: ["la détermination pratique de Km et Vmax", "la courbe de Michaelis-Menten", "la définition de Km par Vmax/2"],
  66: ["la courbe de Michaelis-Menten", "la définition de Km par Vmax/2", "l’affinité et Km", "les exemples de Km", "l’équation de Michaelis-Menten"],
  67: ["l’effet de la concentration en substrat"],
  68: ["l’effet de la concentration en enzyme"],
  69: ["l’effet du pH"],
  70: ["l’effet de la température"],
  71: ["les repères de température de la fiche"],
  72: ["la Taq polymérase"],
  73: ["l’inhibition compétitive"],
  74: ["l’inhibition non compétitive"],
  75: ["l’inhibition incompétitive"],
  76: ["l’inhibition mixte"],
  77: ["l’effet du pH"],
  78: ["l’effet de la température"],
  79: ["les repères de température de la fiche"],
  80: ["la Taq polymérase"],
  81: ["l’inhibition compétitive"],
  82: ["le pourcentage d’inhibition"],
  83: ["l’inhibition incompétitive"],
  84: ["l’inhibition mixte"],
  85: ["le pourcentage d’inhibition"],
  86: ["l’effet de la concentration en substrat"],
  87: ["le pourcentage d’inhibition", "l’effet de la concentration en substrat", "l’effet de la concentration en enzyme"],
  88: ["l’effet de la concentration en substrat", "l’effet de la concentration en enzyme", "l’effet du pH", "l’effet de la température", "les repères de température de la fiche"],
  89: ["l’inhibition compétitive"],
  90: ["l’effet de la concentration en enzyme", "les repères de température de la fiche"],
  91: ["l’effet du pH", "la Taq polymérase"],
  92: ["l’effet de la température", "l’inhibition compétitive"],
  93: ["les repères de température de la fiche", "l’inhibition non compétitive"],
  94: ["la Taq polymérase", "l’inhibition incompétitive"],
  95: ["l’inhibition compétitive", "l’inhibition mixte"],
  96: ["l’inhibition non compétitive", "le pourcentage d’inhibition"],
  97: ["l’inhibition incompétitive", "l’effet de la concentration en substrat"],
  98: ["l’inhibition mixte", "le pourcentage d’inhibition", "l’effet de la concentration en substrat"],
  99: ["le pourcentage d’inhibition", "l’effet du pH"],
  100: ["l’effet de la concentration en substrat", "l’effet de la concentration en enzyme", "l’effet du pH", "l’effet de la température", "les repères de température de la fiche"],
  101: ["la définition de la cinétique enzymatique", "le katal"],
  102: ["la concentration totale en enzyme", "les exemples de Kcat"],
  103: ["la formule de la vitesse initiale par absorbance", "la saturation enzymatique et Kcat"],
  104: ["la conversion UI-nkat", "les exemples de Km"],
  105: ["l’activité spécifique", "la réaction d’ordre deux"],
  106: ["la courbe de Michaelis-Menten", "l’effet de la concentration en substrat"],
  107: ["l’équation de Michaelis-Menten", "les repères de température de la fiche"],
  108: ["la représentation de Lineweaver-Burk", "l’inhibition incompétitive"],
  109: ["l’équation de Michaelis-Menten", "la réaction d’ordre zéro", "la réaction d’ordre un"],
  110: ["la réaction d’ordre deux", "la représentation de Lineweaver-Burk", "le repère d’abscisse de Lineweaver-Burk dans la fiche", "la détermination pratique de Km et Vmax", "l’effet de la concentration en substrat"],
  111: ["la relation entre substrat et produit", "la concentration d’activité catalytique Ccat", "les exemples de Km"],
  112: ["la pente ΔA/Δt", "la courbe de Michaelis-Menten", "l’effet de la température"],
  113: ["le katal", "la réaction d’ordre deux", "la phase stationnaire"],
  114: ["l’activité spécifique", "l’effet de la température", "la constante catalytique Kcat"],
  115: ["la définition de Km par Vmax/2", "le pourcentage d’inhibition", "la réaction d’ordre zéro"],
  116: ["la réaction d’ordre un", "la pente ΔA/Δt", "la Taq polymérase"],
  117: ["la loi de Beer-Lambert appliquée à la cinétique"],
  118: ["la Taq polymérase", "la courbe de Michaelis-Menten", "l’activité spécifique"],
  119: ["le pourcentage d’inhibition", "la réaction d’ordre deux", "la réaction d’ordre deux"],
  120: ["la concentration totale en enzyme", "l’effet de la température", "l’inhibition non compétitive"],
  121: ["la formule de la vitesse initiale par absorbance", "l’état préstationnaire et poststationnaire", "l’unité internationale UI"],
  122: ["la concentration d’activité catalytique Ccat", "la constante catalytique Kcat", "les exemples de Kcat", "l’activité spécifique", "l’activité molaire spécifique"],
};
