import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_ORDER = 4;

export const SECTION_D_STRUCTURE_DISCOVERY_QUIZ_SLUG =
  `section-d-discovery-thioesters-structure-preparation`;
export const SECTION_D_REACTIVITY_PRACTICE_QUIZ_SLUG =
  `section-d-practice-thioesters-hydrolyse-reactivite`;
export const SECTION_D_ACETYLCOA_MASTER_QUIZ_SLUG =
  `section-d-master-acetyl-coa-coenzyme-a`;

export const SECTION_D_STRUCTURE_DISCOVERY_QUESTION_ORDERS: number[] = [91, 92, 93, 94, 95, 96, 97, 98, 99, 100];
export const SECTION_D_REACTIVITY_PRACTICE_QUESTION_ORDERS: number[] = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110];
export const SECTION_D_ACETYLCOA_MASTER_QUESTION_ORDERS: number[] = [111, 112, 113, 114, 115, 116, 117, 118, 119, 120];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: SECTION_D_STRUCTURE_DISCOVERY_QUIZ_SLUG,
    title: `Thioesters : structure et préparation`,
    description: `Reconnaître le motif thioester et prévoir sa formation à partir d'un acide activé et d'un thiol.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_D_ORDER,
    questionOrders: SECTION_D_STRUCTURE_DISCOVERY_QUESTION_ORDERS,
  },
  {
    order: 11,
    slug: SECTION_D_REACTIVITY_PRACTICE_QUIZ_SLUG,
    title: `Hydrolyse et réactivité des thioesters`,
    description: `Identifier les centres électrophile et nucléophile d'un thioester et prévoir les produits de son hydrolyse.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_D_ORDER,
    questionOrders: SECTION_D_REACTIVITY_PRACTICE_QUESTION_ORDERS,
  },
  {
    order: 12,
    slug: SECTION_D_ACETYLCOA_MASTER_QUIZ_SLUG,
    title: `Acétyl-CoA et coenzyme A-SH`,
    description: `Relier la fonction thioester de l'acétyl-CoA à son hydrolyse, à sa formation enzymatique et à sa réactivité biologique.`,
    stage: 'MASTER',
    sectionOrder: SECTION_D_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 111 },
      { type: 'QUESTION', questionOrder: 112 },
      { type: 'QUESTION', questionOrder: 113 },
      { type: 'QUESTION', questionOrder: 114 },
      { type: 'QUESTION', questionOrder: 115 },
      { type: 'QUESTION', questionOrder: 116 },
      { type: 'QUESTION', questionOrder: 117 },
      {
        type: 'GROUP',
        title: `Interconversion acétyl-CoA / coenzyme A-SH`,
        sharedStatement: `L'acétyl-CoA est représenté par $\mathrm{CH_3CO{-}SCoA}$. Son hydrolyse produit la coenzyme A-SH $\mathrm{HSCoA}$ et l'acide éthanoïque. La réaction inverse est réalisée par des enzymes.`,
        questionOrders: [118, 119, 120],
      },
    ],
  },
];

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `�' propos d'un thioester :`,
    choices: [
      `Il contient le motif $\mathrm{R{-}C(=O){-}S{-}R'}$.`,
      `Il peut être décrit comme un ester soufré.`,
      `Il contient nécessairement un groupe $\mathrm{R{-}SH}$ intact.`,
      `Il contient un groupe carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Un thioester est un dérivé d'acide de formule générale $\mathrm{RCO{-}SR'}$, où le soufre remplace l'oxygène alkoxy d'un ester.`,
    choiceExplanations: [
      `Le soufre est directement lié au groupe acyle.`,
      `C'est le cas particulier indiqué dans la fiche.`,
      `Dans le thioester, le soufre est lié à deux groupes et ne porte plus d'hydrogène.`,
      `Le motif acyle $\mathrm{C{=}O}$ est conservé.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formule $\mathrm{CH_3COSCH_3}$ correspond :`,
    choices: [
      `�' un thioester.`,
      `�' un composé possédant un carbonyle.`,
      `�' un thiol libre $\mathrm{RSH}$.`,
      `�' un ester soufré.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le groupe $\mathrm{CH_3CO-}$ est lié au soufre, lui-même lié à un groupe méthyle : il s'agit d'un thioester.`,
    choiceExplanations: [
      `Le motif $\mathrm{-CO{-}S-}$ est présent.`,
      `La liaison $\mathrm{C{=}O}$ appartient au groupe acyle.`,
      `Le soufre ne porte aucun hydrogène.`,
      `C'est une autre manière de nommer cette fonction.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un thiol possède la formule générale :`,
    choices: [
      `$\mathrm{R{-}SH}$.`,
      `Il peut servir à préparer un thioester.`,
      `$\mathrm{R{-}OH}$ uniquement.`,
      `Il apporte le fragment $\mathrm{-SR}$ du thioester.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Un thiol est l'analogue soufré d'un alcool et s'écrit $\mathrm{R{-}SH}$.`,
    choiceExplanations: [
      `Le groupe sulfhydryle contient un soufre lié à un hydrogène.`,
      `Il réagit avec un acide activé.`,
      `Cette formule correspond à un alcool.`,
      `Le soufre et son radical sont conservés dans le produit.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le bilan de préparation d'un thioester est :`,
    choices: [
      `Acide activé + thiol '�� thioester.`,
      `Le thiol peut s'écrire $\mathrm{RSH}$.`,
      `Un chlorure d'acyle peut être l'acide activé.`,
      `La réaction donne nécessairement une amide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Un acide activé transfère son groupe acyle au soufre d'un thiol.`,
    choiceExplanations: [
      `C'est le bilan indiqué.`,
      `Il fournit le groupe soufré du produit.`,
      `Il fait partie des réactifs cités.`,
      `Aucune amine n'est impliquée.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les acides activés utilisables pour former un thioester, le cours cite :`,
    choices: [
      `Les chlorures d'acyle.`,
      `Les anhydrides d'acide.`,
      `Les alcanes.`,
      `Les ammoniums quaternaires uniquement.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les mêmes familles activées que pour esters et amides sont retenues : chlorures d'acyle et anhydrides.`,
    choiceExplanations: [
      `Ils transfèrent facilement le groupe acyle.`,
      `Ils peuvent également acyler un thiol.`,
      `Ils ne possèdent pas de groupe acyle activé.`,
      `Ils ne sont pas les acides activés cités.`,
    ],
  },
  {
    order: 96,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On fait réagir $\mathrm{CH_3COCl}$ avec le méthanethiol $\mathrm{CH_3SH}$. Le produit attendu :`,
    choices: [
      `Possède une fonction thioester.`,
      `Peut s'écrire $\mathrm{CH_3COSCH_3}$.`,
      `Conserve un groupe $\mathrm{S{-}H}$ dans le thioester final.`,
      `Résulte d'une acylation du thiol.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le groupe éthanoyle se lie au soufre du méthanethiol pour former $\mathrm{CH_3COSCH_3}$.`,
    choiceExplanations: [
      `Le motif $\mathrm{-CO{-}S-}$ est créé.`,
      `Les deux fragments sont réunis par le soufre.`,
      `L'hydrogène du thiol n'est plus porté par le soufre du produit.`,
      `Le groupe acyle est transféré au soufre.`,
    ],
  },
  {
    order: 97,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison entre un ester $\mathrm{RCOOR'}$ et un thioester $\mathrm{RCOSR'}$ :`,
    choices: [
      `Les deux possèdent un groupe carbonyle.`,
      `L'ester possède un oxygène après le carbonyle.`,
      `Le thioester possède un soufre après le carbonyle.`,
      `Le thioester ne contient jamais de carbone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le remplacement de l'oxygène simple par un soufre transforme l'ester en thioester sans supprimer le carbonyle.`,
    choiceExplanations: [
      `Le motif $\mathrm{RCO-}$ est commun.`,
      `Sa formule est $\mathrm{RCOOR'}$.`,
      `Sa formule est $\mathrm{RCOSR'}$.`,
      `Il est au contraire un composé organique carbonylé.`,
    ],
  },
  {
    order: 98,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une molécule de formule $\mathrm{RCO{-}SCoA}$ :`,
    choices: [
      `Contient une fonction thioester.`,
      `Peut être un dérivé acylé de la coenzyme A-SH.`,
      `Est nécessairement une amide.`,
      `Contient le motif caractéristique de l'acétyl-CoA si $\mathrm{R=CH_3}$.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le motif $\mathrm{-CO{-}S-}$ suffit à identifier une fonction thioester.`,
    choiceExplanations: [
      `Le groupe acyle est lié au soufre.`,
      `Le soufre de la coenzyme A porte le groupe acyle.`,
      `L'hétéroatome lié au carbonyle est le soufre.`,
      `Le groupe acétyle est $\mathrm{CH_3CO-}$.`,
    ],
  },
  {
    order: 99,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le soufre d'un thioester :`,
    choices: [
      `Remplace l'oxygène alkoxy d'un ester.`,
      `Est directement lié au groupe acyle.`,
      `Porte nécessairement une charge positive.`,
      `Peut provenir d'un thiol après acylation.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Il est lié au carbone carbonylé d'un côté et à un radical carboné ou à la coenzyme A de l'autre.`,
    choiceExplanations: [
      `C'est l'origine de l'expression ester soufré.`,
      `La liaison est $\mathrm{C(=O){-}S}$.`,
      `Un thioester usuel est neutre.`,
      `Le thiol fournit le soufre et son substituant.`,
    ],
  },
  {
    order: 100,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Synthèse sur la préparation des dérivés d'acide :`,
    choices: [
      `Alcool '�� ester.`,
      `Amine '�� amide.`,
      `Thiol '�� thioester.`,
      `Les trois nucléophiles conduisent obligatoirement à la même fonction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La nature du nucléophile détermine si l'acide activé forme un ester, une amide ou un thioester.`,
    choiceExplanations: [
      `L'oxygène de l'alcool reçoit le groupe acyle.`,
      `L'azote devient lié au carbonyle.`,
      `Le soufre reçoit le groupe acyle.`,
      `L'hétéroatome du nucléophile reste dans la fonction produite.`,
    ],
  },
  {
    order: 101,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La liaison thioester est :`,
    choices: [
      `Hydrolysable.`,
      `Rompue avec formation d'un acide carboxylique.`,
      `Rompue avec formation d'un thiol.`,
      `Absolument inerte à toute enzyme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fonction thioester peut être hydrolysée par l'eau dans des conditions adaptées ou par des enzymes.`,
    choiceExplanations: [
      `La fiche présente explicitement cette réaction.`,
      `Le groupe acyle devient $\mathrm{RCOOH}$.`,
      `Le groupe $\mathrm{SR'}$ devient $\mathrm{HSR'}$.`,
      `Une hydrolyse enzymatique est mentionnée.`,
    ],
  },
  {
    order: 102,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le bilan général de l'hydrolyse d'un thioester est :`,
    choices: [
      `$\mathrm{RCOSR' + H_2O ightarrow RCOOH + HSR'}$.`,
      `Un acide carboxylique est formé.`,
      `Un thiol est formé.`,
      `Le seul produit est un alcène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'eau rompt la liaison acyle''�soufre et redonne l'acide carboxylique et le thiol.`,
    choiceExplanations: [
      `Cette équation résume la réaction.`,
      `Le fragment acyle est protoné.`,
      `Le soufre récupère un hydrogène.`,
      `La réaction conserve les fonctions acide et thiol.`,
    ],
  },
  {
    order: 103,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les conditions d'hydrolyse d'un thioester peuvent inclure :`,
    choices: [
      `De l'eau.`,
      `Un pH approprié.`,
      `Une enzyme.`,
      `L'absence absolue de toute molécule d'eau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche mentionne l'eau dans des conditions de pH adaptées ou l'action d'enzymes.`,
    choiceExplanations: [
      `Elle fournit les éléments de l'hydrolyse.`,
      `L'acidité ou la basicité peut favoriser la réaction.`,
      `Une catalyse biologique est possible.`,
      `L'hydrolyse implique précisément l'eau.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comme dans un ester, le carbone carbonylé d'un thioester :`,
    choices: [
      `Possède un caractère électrophile.`,
      `Est polarisé par l'oxygène du carbonyle.`,
      `Est nécessairement un anion nucléophile.`,
      `Contribue à la réactivité du thioester.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'effet électroattracteur de l'oxygène du carbonyle confère un caractère électrophile au carbone qui le porte.`,
    choiceExplanations: [
      `Il peut être attaqué par une espèce nucléophile.`,
      `L'oxygène attire la densité électronique.`,
      `Le carbone du carbonyle est déficitaire en électrons.`,
      `Il constitue un centre de réaction important.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans un thioester de type $\mathrm{CH_3COSR}$, le carbone du groupe $\mathrm{CH_3}$ :`,
    choices: [
      `Est voisin du carbonyle.`,
      `Peut acquérir un caractère nucléophile.`,
      `Peut réagir avec un électrophile dans des conditions adaptées.`,
      `Est le carbone du groupe carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Comme pour l'ester, le carbone en alpha peut présenter un caractère nucléophile en raison de l'influence du carbonyle.`,
    choiceExplanations: [
      `Il se trouve en position alpha.`,
      `La fiche rapproche cette propriété de celle des esters.`,
      `Un centre riche en électrons attaque un électrophile.`,
      `Il est adjacent au carbone carbonylé, mais distinct de lui.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un thioester peut donc posséder :`,
    choices: [
      `Un centre électrophile au niveau du carbone carbonylé.`,
      `Un centre nucléophile potentiel au carbone en alpha.`,
      `Des comportements dépendant des conditions expérimentales.`,
      `Aucun centre réactif car le soufre annule toute polarisation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Comme l'ester, il associe un carbonyle électrophile et un carbone en alpha potentiellement nucléophile.`,
    choiceExplanations: [
      `L'oxygène polarise le carbonyle.`,
      `La densité électronique peut être mobilisée sur ce site.`,
      `La nature des réactifs choisit le centre exploité.`,
      `La fiche souligne au contraire sa réactivité.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On hydrolyse $\mathrm{CH_3COSCH_2CH_3}$. Les produits attendus sont :`,
    choices: [
      `$\mathrm{CH_3COOH}$.`,
      `$\mathrm{HSCH_2CH_3}$.`,
      `Un acide carboxylique et un thiol.`,
      `Uniquement de l'éthanol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le groupe acétyle donne l'acide éthanoïque et le groupe éthylthio donne l'éthanethiol.`,
    choiceExplanations: [
      `Le fragment acyle devient acide éthanoïque.`,
      `Le soufre récupère un hydrogène pour former le thiol.`,
      `Ce sont les familles générales de produits.`,
      `Le fragment soufré donne un thiol, non un alcool.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison de l'hydrolyse d'un ester et d'un thioester :`,
    choices: [
      `L'ester peut libérer un alcool.`,
      `Le thioester peut libérer un thiol.`,
      `Les deux peuvent libérer un acide carboxylique.`,
      `Les deux libèrent nécessairement une amine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les deux donnent un dérivé carboxylique ; le second produit est un alcool pour l'ester et un thiol pour le thioester.`,
    choiceExplanations: [
      `Le groupe $\mathrm{OR'}$ devient $\mathrm{R'OH}$.`,
      `Le groupe $\mathrm{SR'}$ devient $\mathrm{HSR'}$.`,
      `Le groupe acyle est hydrolysé.`,
      `Aucun azote n'est requis.`,
    ],
  },
  {
    order: 109,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La réactivité d'un thioester s'explique en partie par :`,
    choices: [
      `L'effet électroattracteur de l'oxygène du carbonyle.`,
      `Le caractère électrophile du carbone carbonylé.`,
      `Le caractère nucléophile possible du carbone en alpha.`,
      `L'absence de toute liaison polarisée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le carbonyle reste fortement polarisé et le motif en alpha peut également mobiliser des électrons, comme dans un ester.`,
    choiceExplanations: [
      `Il rend le carbone carbonylé électrophile.`,
      `Ce site peut recevoir une attaque nucléophile.`,
      `La densité électronique peut être localisée sur ce carbone.`,
      `La liaison carbonyle est précisément polarisée.`,
    ],
  },
  {
    order: 110,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `�' propos d'une transformation enzymatique d'un thioester :`,
    choices: [
      `L'hydrolyse peut redonner le thiol.`,
      `L'hydrolyse peut redonner l'acide carboxylique.`,
      `La réaction inverse peut reformer la liaison thioester.`,
      `Une enzyme détruit nécessairement le soufre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une enzyme peut catalyser soit son hydrolyse, soit sa formation à partir d'un thiol et d'un groupe acyle activé.`,
    choiceExplanations: [
      `Le soufre retrouve un hydrogène.`,
      `Le groupe acyle est converti en acide.`,
      `La fiche parle d'estérification enzymatique du thiol.`,
      `Le soufre est conservé entre thiol et thioester.`,
    ],
  },
  {
    order: 111,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'acétyl-CoA :`,
    choices: [
      `Contient une fonction thioester.`,
      `Est un dérivé acétylé de la coenzyme A-SH.`,
      `Ne contient aucun groupe carbonyle.`,
      `Illustre une application biologique des thioesters.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'acétyl-CoA est le thioester formé entre le groupe acétyle et le soufre de la coenzyme A-SH.`,
    choiceExplanations: [
      `Le motif est $\mathrm{CH_3CO{-}SCoA}$.`,
      `Le groupe acétyle est lié au soufre.`,
      `Le groupe acétyle contient $\mathrm{C{=}O}$.`,
      `C'est l'exemple central de la fiche.`,
    ],
  },
  {
    order: 112,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La coenzyme A-SH :`,
    choices: [
      `Porte un groupe thiol.`,
      `Peut être acylée pour donner un thioester.`,
      `Est la forme hydrolysée soufrée de l'acétyl-CoA.`,
      `Est nécessairement un ester oxygéné simple sans soufre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La notation -SH indique une fonction thiol disponible pour former une liaison thioester.`,
    choiceExplanations: [
      `Le soufre est lié à un hydrogène.`,
      `Le groupe acyle se fixe sur le soufre.`,
      `L'hydrolyse libère $\mathrm{HSCoA}$.`,
      `Le groupe fonctionnel mis en avant est le thiol.`,
    ],
  },
  {
    order: 113,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'hydrolyse de l'acétyl-CoA donne :`,
    choices: [
      `La coenzyme A-SH.`,
      `L'acide éthanoïque.`,
      `Un thiol et un acide carboxylique.`,
      `Uniquement une amide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La rupture du thioester libère la coenzyme A-SH et l'acide éthanoïque.`,
    choiceExplanations: [
      `Le fragment soufré récupère un hydrogène.`,
      `Le groupe acétyle devient $\mathrm{CH_3COOH}$.`,
      `Ce sont les produits généraux d'une hydrolyse de thioester.`,
      `Aucune liaison $\mathrm{C{-}N}$ n'est formée.`,
    ],
  },
  {
    order: 114,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La formation de l'acétyl-CoA à partir de la coenzyme A-SH :`,
    choices: [
      `Forme une liaison entre le groupe acétyle et le soufre.`,
      `Peut être catalysée par des enzymes.`,
      `Consomme la fonction thiol libre.`,
      `Transforme le soufre en azote.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Elle correspond à une acylation enzymatique du thiol formant le thioester $\mathrm{CH_3CO{-}SCoA}$.`,
    choiceExplanations: [
      `C'est la liaison thioester.`,
      `La fiche mentionne une estérification enzymatique.`,
      `Le groupe $\mathrm{S{-}H}$ devient $\mathrm{S{-}COCH_3}$.`,
      `L'atome de soufre est conservé.`,
    ],
  },
  {
    order: 115,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pourquoi la fonction thioester est-elle importante dans l'acétyl-CoA ?`,
    choices: [
      `Elle explique une part de la réactivité de l'acétyl-CoA.`,
      `Elle permet une interconversion avec la coenzyme A-SH.`,
      `Elle supprime toute possibilité d'hydrolyse.`,
      `Elle contient le groupe acétyle lié au soufre.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le thioester confère au groupe acétyle une réactivité permettant son transfert ou son hydrolyse dans les voies biologiques.`,
    choiceExplanations: [
      `Le carbonyle du thioester est un centre électrophile.`,
      `Formation et hydrolyse relient les deux formes.`,
      `La liaison thioester est hydrolysable.`,
      `C'est la définition structurale de l'acétyl-CoA.`,
    ],
  },
  {
    order: 116,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison entre acétyl-CoA et coenzyme A-SH :`,
    choices: [
      `Acétyl-CoA : $\mathrm{CH_3CO{-}SCoA}$.`,
      `Coenzyme A-SH : $\mathrm{HSCoA}$.`,
      `L'hydrolyse transforme la première en seconde.`,
      `Les deux structures sont strictement identiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La première porte un groupe acétyle sur le soufre ; la seconde possède un thiol libre.`,
    choiceExplanations: [
      `Le soufre est acylé.`,
      `Le soufre porte un hydrogène.`,
      `Elle libère aussi l'acide éthanoïque.`,
      `L'une est acylée, l'autre possède un thiol libre.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans l'acétyl-CoA, le carbone du carbonyle :`,
    choices: [
      `Peut être attaqué par un nucléophile.`,
      `Appartient au groupe acétyle.`,
      `Est lié au soufre de la coenzyme A.`,
      `Est nécessairement un carbanion.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Comme dans les autres thioesters, ce carbone est électrophile sous l'effet de l'oxygène carbonylé.`,
    choiceExplanations: [
      `Il est déficitaire en électrons.`,
      `Le motif est $\mathrm{CH_3CO-}$.`,
      `La liaison $\mathrm{C(=O){-}S}$ définit le thioester.`,
      `Le caractère électrophile domine au carbonyle.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'hydrolyse décrite :`,
    choices: [
      `La coenzyme A-SH est régénérée.`,
      `L'acide éthanoïque est formé.`,
      `La fonction thioester disparaît.`,
      `Le soufre est éliminé de la coenzyme A.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La liaison entre le carbone acyle et le soufre est rompue par l'eau.`,
    choiceExplanations: [
      `Le soufre récupère un hydrogène.`,
      `Le fragment acétyle devient acide carboxylique.`,
      `La liaison $\mathrm{CO{-}S}$ est rompue.`,
      `Il reste dans le groupe thiol $\mathrm{-SH}$.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la réaction inverse :`,
    choices: [
      `La fonction thiol est consommée.`,
      `La fonction thioester est formée.`,
      `L'acétyl-CoA est régénéré.`,
      `La réaction ne peut jamais être catalysée par une enzyme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une enzyme peut reformer le thioester en acylant le soufre de la coenzyme A-SH.`,
    choiceExplanations: [
      `Le lien $\mathrm{S{-}H}$ est remplacé par $\mathrm{S{-}COCH_3}$.`,
      `Le groupe acétyle est lié au soufre.`,
      `C'est le produit de l'acylation.`,
      `La fiche indique explicitement une voie enzymatique.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L'interconversion présentée illustre :`,
    choices: [
      `Une réaction réversible au sens biologique global entre forme thiol et forme thioester.`,
      `La conservation de l'atome de soufre.`,
      `Le rôle du thioester dans la réactivité du groupe acétyle.`,
      `La transformation de l'acide éthanoïque en peptide sans autre réactif.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les thioesters peuvent être formés et hydrolysés de manière contrôlée, ce qui rend l'acétyl-CoA utile au transfert de groupes acyles.`,
    choiceExplanations: [
      `Des enzymes différentes peuvent catalyser les directions selon le contexte.`,
      `Il reste dans la coenzyme A.`,
      `La liaison activée facilite des transformations.`,
      `Aucune liaison peptidique n'est décrite ici.`,
    ],
  },
];
