/**
 * UE14 – Biologie cellulaire – Chapitre 5
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les lysosomes :`,
    choices: [
      `Ont une morphologie hétérogène.`,
      `Mesurent environ 0,2 à 0,5 µm selon la fiche.`,
      `Peuvent être étudiés par cytoenzymologie.`,
      `Sont dépourvus de membrane.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le lysosome est un compartiment délimité par une membrane.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La phosphatase acide (PAC) :`,
    choices: [
      `Est un marqueur lysosomal.`,
      `Peut être mise en évidence en cytoenzymologie.`,
      `Est associée à la membrane lysosomale.`,
      `Maintient seule le pH acide en pompant des protons.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le maintien du pH dépend surtout de la pompe H+ ATPase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les hydrolases acides lysosomales :`,
    choices: [
      `Sont solubles dans la lumière.`,
      `Fonctionnent à pH voisin de 5.`,
      `Comprennent nucléases, protéases, lipases et glycosidases.`,
      `Sont actives uniquement à pH 7,4.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le milieu acide du lysosome permet leur fonctionnement optimal.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les protéines de la membrane lysosomale :`,
    choices: [
      `Pompe H+ ATPase.`,
      `Phosphatase acide.`,
      `Perméases.`,
      `LAMP.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La membrane lysosomale possède des protéines de transport, d’acidification, de marquage et de structure.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les LAMP :`,
    choices: [
      `Sont des glycoprotéines membranaires lysosomales.`,
      `Ont un rôle structural.`,
      `Ne sont pas présentées comme des enzymes hydrolytiques.`,
      `Sont des protéines motrices des microtubules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `LAMP signifie lysosome-associated membrane protein.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 66,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La pompe H+ ATPase lysosomale :`,
    choices: [
      `Utilise de l’ATP.`,
      `Fait entrer des protons.`,
      `Maintient un pH acide.`,
      `Produit directement toutes les hydrolases acides.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La pompe acidifie le lysosome mais ne synthétise pas les enzymes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 67,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les corps résiduels :`,
    choices: [
      `Sont de vieux lysosomes à faible activité enzymatique.`,
      `Peuvent s’accumuler dans les neurones.`,
      `Augmentent avec l’âge cellulaire.`,
      `Sont des mitochondries nouvellement synthétisées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ils représentent des compartiments lysosomaux vieillissants.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 68,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’adressage des enzymes lysosomales commence par :`,
    choices: [
      `Une synthèse dans le RE.`,
      `Un passage dans le Golgi.`,
      `L’ajout d’un M6P dans le Golgi cis.`,
      `Une traduction directe à l’intérieur du lysosome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les hydrolases lysosomales suivent la voie sécrétoire avant leur tri spécifique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 69,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’ajout du M6P dépend :`,
    choices: [
      `D’une N-acétylglucosamine-phosphotransférase.`,
      `Du Golgi cis.`,
      `D’un processus dont la mutation peut être pathologique.`,
      `De la pompe H+ ATPase lysosomale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La GlcNAc-phosphotransférase crée le signal d’adressage M6P.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 70,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le récepteur du M6P :`,
    choices: [
      `Reconnaît les hydrolases marquées au niveau trans/TGN.`,
      `Permet leur incorporation dans des vésicules à clathrine.`,
      `Est recyclé vers le TGN après dissociation.`,
      `Est dégradé avec toutes les hydrolases dans le lysosome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La baisse de pH dans les endosomes permet la dissociation et le recyclage du récepteur.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante :

![Adressage M6P](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-2/adressage-m6p-lysosome.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Le M6P est ajouté dans le Golgi cis.`,
      `Le R-M6P est reconnu au TGN.`,
      `L’acidification endosomale favorise la dissociation enzyme-récepteur.`,
      `Le récepteur reste définitivement dans le lysosome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le R-M6P est recyclé vers le TGN.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’adressage lysosomal n’est pas efficace à 100 % :`,
    choices: [
      `Environ 10 % des enzymes peuvent atteindre la membrane plasmique.`,
      `Certaines enzymes sont exocytées dans la MEC.`,
      `Elles peuvent participer temporairement au remodelage osseux.`,
      `Elles ne peuvent jamais être recaptées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les enzymes exocytées peuvent revenir vers le lysosome via le récepteur M6P.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 73,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les fonctions du lysosome comprennent :`,
    choices: [
      `Nutrition cellulaire.`,
      `Renouvellement de molécules et d’organites.`,
      `Défense contre des agents pathogènes.`,
      `Réplication du génome nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le lysosome est un compartiment catabolique, non un site de réplication de l’ADN.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les métabolites produits par les lysosomes peuvent :`,
    choices: [
      `Sortir vers le cytosol via des perméases.`,
      `Être exocytés vers la MEC.`,
      `Être réutilisés par la cellule.`,
      `Rester obligatoirement piégés sans transport possible.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les perméases permettent le recyclage des produits de dégradation.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 75,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les quatre voies d’entrée dans le lysosome comprennent :`,
    choices: [
      `Endocytose.`,
      `Phagocytose.`,
      `Autophagie.`,
      `Entrée directe depuis le cytosol.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La fiche distingue quatre voies majeures alimentant le lysosome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante :

![Voies d’entrée lysosomales](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-2/voies-entree-lysosome.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `La phagocytose peut former un phagolysosome.`,
      `L’autophagie peut dégrader des organites vieillissants.`,
      `L’endocytose est permanente hors mitose.`,
      `L’entrée directe du cytosol correspond à une exocytose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’entrée directe du cytosol alimente la dégradation lysosomale, elle ne correspond pas à une exocytose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La phagocytose vers le lysosome :`,
    choices: [
      `Est réalisée notamment par macrophages et polynucléaires.`,
      `Produit un phagosome.`,
      `Conduit à un phagolysosome.`,
      `Est la voie unique d’entrée dans tous les types cellulaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’endocytose est la voie permanente commune à tous les types cellulaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’autophagie lysosomale :`,
    choices: [
      `Dégrade des organites vieillissants.`,
      `Peut éliminer des mitochondries usées.`,
      `Peut corriger un excès de surface membranaire.`,
      `Repose sur la réplication de l’ADN lysosomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le lysosome ne possède pas de génome propre à répliquer.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 79,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’entrée directe depuis le cytosol peut concerner :`,
    choices: [
      `Des peptides partiellement ubiquitinylés.`,
      `Des produits d’une dégradation protéasomale.`,
      `Des substrats portant des signaux d’adressage lysosomal.`,
      `Des chromosomes entiers sortant du noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie directe concerne des substrats cytosoliques spécifiques, non des chromosomes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les maladies lysosomales congénitales sont aussi appelées :`,
    choices: [
      `Maladies de surcharge.`,
      `Thésaurismoses.`,
      `Maladies dues à une absence d’hydrolyse ou à une anomalie de perméase.`,
      `Maladies exclusivement infectieuses.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Il s’agit de maladies rares souvent génétiques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une enzyme lysosomale manquante peut entraîner :`,
    choices: [
      `Une accumulation du substrat non dégradé.`,
      `Une sphingolipidose.`,
      `Des troubles particulièrement graves dans le système nerveux.`,
      `Une augmentation générale de toutes les fonctions lysosomales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’absence d’une enzyme produit une surcharge, non une amélioration du catabolisme.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La maladie de Gaucher est citée comme exemple :`,
    choices: [
      `De maladie de surcharge.`,
      `De sphingolipidose liée à une enzyme anormale ou manquante.`,
      `Pouvant entraîner des troubles du système nerveux selon la fiche.`,
      `De maladie due à un excès de R-M6P recyclé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Elle illustre un défaut d’hydrolyse d’un substrat lysosomal.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation de la GlcNAc-phosphotransférase peut provoquer :`,
    choices: [
      `Un défaut d’adressage de nombreuses enzymes lysosomales.`,
      `Une mucolipidose de type II.`,
      `Une altération globale du système M6P.`,
      `Une synthèse accrue de toutes les hydrolases correctement adressées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette mutation compromet le marquage M6P de multiples enzymes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une anomalie de perméase lysosomale peut provoquer :`,
    choices: [
      `Une accumulation de métabolites déjà hydrolysés.`,
      `Une cystinose en cas de défaut de transport de la cystine.`,
      `Une accumulation d’acide sialique.`,
      `Une absence totale de pompe H+ ATPase dans tous les cas.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les défauts de perméases concernent la sortie de métabolites spécifiques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le blocage acquis de la pompe H+ ATPase peut :`,
    choices: [
      `Faire perdre l’acidité lysosomale.`,
      `Diminuer l’activité des hydrolases acides.`,
      `Être favorisé par certaines mycobactéries ou Listeria.`,
      `Augmenter automatiquement l’activité de toutes les hydrolases.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La perte d’acidité perturbe au contraire la digestion lysosomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les quinines sont citées dans la fiche comme pouvant :`,
    choices: [
      `Perturber l’acidification lysosomale.`,
      `Être utilisées contre le paludisme.`,
      `Bloquer le parasite dans les hématies.`,
      `Ajouter un M6P aux hydrolases lysosomales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ajout du M6P est une fonction golgienne, indépendante des quinines.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’hydrolyse de matériaux non biologiques est difficile, ce qui peut conduire à :`,
    choices: [
      `Une accumulation dans les macrophages pulmonaires.`,
      `Des pneumoconioses.`,
      `Une inflammation chronique.`,
      `Une digestion complète de toutes les particules minérales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les particules minérales ou métalliques peuvent résister à la dégradation lysosomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les exemples environnementaux cités :`,
    choices: [
      `Silice : silicose.`,
      `Fibres d’amiante : asbestose et risque de mésothéliome.`,
      `Cristaux d’acide urique : crise de goutte.`,
      `Collagène IV : pneumoconiose obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le collagène IV est une protéine de MEC, pas une particule inhalée responsable de pneumoconiose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule neuronale âgée peut accumuler :`,
    choices: [
      `Des corps résiduels.`,
      `Des lysosomes anciens à faible activité.`,
      `Des matériaux difficilement dégradables.`,
      `Uniquement des lysosomes nouvellement formés et très actifs.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cellules peu renouvelées accumulent plus facilement des résidus lysosomaux.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse du lysosome est correcte ?`,
    choices: [
      `Il contient des hydrolases acides fonctionnant à pH bas.`,
      `Il reçoit du matériel par plusieurs voies.`,
      `Ses maladies peuvent relever d’enzymes, d’adressage, de perméases ou d’acidification.`,
      `Il est un compartiment sans membrane directement ouvert sur le cytosol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le lysosome est une cavité membranaire fermée du système endomembranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: `structure-et-fonctions-des-lysosomes`,
    title: `Structure et fonctions des lysosomes`,
    description: `Hydrolases acides, pH, membrane lysosomale et corps résiduels.`,
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: `adressage-et-voies-lysosomales`,
    title: `Adressage et voies d’entrée lysosomales`,
    description: `M6P, endosomes, phagocytose, autophagie et recyclage.`,
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 9,
    slug: `pathologies-lysosomales`,
    title: `Pathologies lysosomales`,
    description: `Maladies de surcharge, défauts de perméases et pathologies acquises.`,
    stage: 'MASTER',
    sectionOrder: 3,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];
