import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_ORDER = 2;

export const SECTION_B_HYDROLYSIS_DISCOVERY_QUIZ_SLUG =
  `section-b-discovery-hydrolyse-esters`;
export const SECTION_B_POLARITY_PRACTICE_QUIZ_SLUG =
  `section-b-practice-polarisation-centres-reactifs-esters`;
export const SECTION_B_REACTIVITY_MASTER_QUIZ_SLUG =
  `section-b-master-reactivite-carbonyle-carbone-alpha`;

export const SECTION_B_HYDROLYSIS_DISCOVERY_QUESTION_ORDERS: number[] = [31, 32, 33, 34, 35, 36, 37, 38, 39, 40];
export const SECTION_B_POLARITY_PRACTICE_QUESTION_ORDERS: number[] = [41, 42, 43, 44, 45, 46, 47, 48, 49, 50];
export const SECTION_B_REACTIVITY_MASTER_QUESTION_ORDERS: number[] = [51, 52, 53, 54, 55, 56, 57, 58, 59, 60];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: SECTION_B_HYDROLYSIS_DISCOVERY_QUIZ_SLUG,
    title: `Hydrolyse acide et saponification des esters`,
    description: `Distinguer l'hydrolyse acide de l'hydrolyse basique et identifier les produits formés à partir d'un ester.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 31 },
      { type: 'QUESTION', questionOrder: 32 },
      { type: 'QUESTION', questionOrder: 33 },
      { type: 'QUESTION', questionOrder: 34 },
      { type: 'QUESTION', questionOrder: 35 },
      { type: 'QUESTION', questionOrder: 36 },
      { type: 'QUESTION', questionOrder: 37 },
      {
        type: 'GROUP',
        title: `Hydrolyse de l'''éthanoate d'''éthyle`,
        sharedStatement: `On étudie l'éthanoate d'éthyle $\mathrm{CH_3COOCH_2CH_3}$. Dans l'expérience **A**, il est chauffé avec de l'eau en milieu acide. Dans l'expérience **B**, il est traité en milieu basique.`,
        questionOrders: [38, 39, 40],
      },
    ],
  },
  {
    order: 5,
    slug: SECTION_B_POLARITY_PRACTICE_QUIZ_SLUG,
    title: `Polarisation et centres réactifs des esters`,
    description: `Identifier le carbone électrophile du carbonyle et comprendre l'effet électroattracteur de l'oxygène dans la fonction ester.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_B_ORDER,
    questionOrders: SECTION_B_POLARITY_PRACTICE_QUESTION_ORDERS,
  },
  {
    order: 6,
    slug: SECTION_B_REACTIVITY_MASTER_QUIZ_SLUG,
    title: `Réactivité du carbonyle et du carbone en alpha`,
    description: `Prévoir l'attaque d'un nucléophile sur le carbonyle et l'attaque d'un électrophile sur le carbone en alpha rendu nucléophile par une base forte.`,
    stage: 'MASTER',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 51 },
      { type: 'QUESTION', questionOrder: 52 },
      { type: 'QUESTION', questionOrder: 53 },
      { type: 'QUESTION', questionOrder: 54 },
      { type: 'QUESTION', questionOrder: 55 },
      { type: 'QUESTION', questionOrder: 56 },
      { type: 'QUESTION', questionOrder: 57 },
      {
        type: 'GROUP',
        title: `Deux voies de réactivité d'''un ester`,
        sharedStatement: `On considère l'ester $\mathrm{CH_3CH_2COOR}$. **Voie I** : réaction directe avec un nucléophile $\mathrm{Nu^-}$. **Voie II** : traitement préalable par une base forte, puis ajout d'un électrophile $\mathrm{E^+}$.`,
        questionOrders: [58, 59, 60],
      },
    ],
  },
];

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `�' propos de l'hydrolyse d'un ester :`,
    choices: [
      `La fonction ester est hydrolysable.`,
      `L'hydrolyse acide se déroule à pH acide.`,
      `L'hydrolyse basique est appelée saponification.`,
      `Un ester est absolument stable en présence d'eau quelles que soient les conditions.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La liaison ester peut être rompue par l'eau, en milieu acide ou basique selon les conditions.`,
    choiceExplanations: [
      `La fiche décrit explicitement sa rupture en présence d'eau.`,
      `Des ions oxonium participent au milieu réactionnel.`,
      `C'est le nom donné à l'hydrolyse alcaline.`,
      `Des conditions acides ou basiques permettent son hydrolyse.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le bilan d'une hydrolyse acide d'ester peut s'écrire :`,
    choices: [
      `$\mathrm{RCOOR' + H_2O ightarrow RCOOH + R'OH}$.`,
      `Un acide carboxylique est formé.`,
      `Un alcool est formé.`,
      `Le seul produit est un alcane.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `En milieu acide, l'ester redonne un acide carboxylique et un alcool.`,
    choiceExplanations: [
      `Ce bilan présente les deux produits attendus.`,
      `Le fragment acyle devient $\mathrm{RCOOH}$.`,
      `Le fragment $\mathrm{OR'}$ devient $\mathrm{R'OH}$.`,
      `L'hydrolyse conserve les fonctions oxygénées.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En milieu acide aqueux :`,
    choices: [
      `Des ions $\mathrm{H_3O^+}$ sont présents.`,
      `Le pH est inférieur à celui d'un milieu neutre.`,
      `L'hydrolyse d'un ester peut conduire à un acide carboxylique.`,
      `La réaction est appelée saponification.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'eau est protonée selon l'équilibre $\mathrm{H_2O + H^+ ightarrow H_3O^+}$, ce qui caractérise le milieu acide.`,
    choiceExplanations: [
      `Ils résultent de la protonation de l'eau.`,
      `La concentration en espèces acides est plus élevée.`,
      `C'est l'un des produits du bilan acide.`,
      `La saponification correspond au milieu basique.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La saponification d'un ester :`,
    choices: [
      `Est une hydrolyse alcaline.`,
      `Conduit à un ion carboxylate $\mathrm{RCOO^-}$.`,
      `Conduit aussi à un alcool $\mathrm{R'OH}$.`,
      `Conduit exclusivement à un aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `En milieu basique, l'ester donne un ion carboxylate et un alcool.`,
    choiceExplanations: [
      `Alcalin signifie basique.`,
      `Le produit acide est déprotoné dans le milieu basique.`,
      `Le fragment alkoxy est protoné pour donner l'alcool.`,
      `Le carbonyle de l'ester devient un carboxylate, non un aldéhyde.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Comparaison entre hydrolyse acide et saponification :`,
    choices: [
      `L'hydrolyse acide forme $\mathrm{RCOOH}$.`,
      `La saponification forme $\mathrm{RCOO^-}$.`,
      `Les deux peuvent former l'alcool $\mathrm{R'OH}$.`,
      `Les deux portent nécessairement le même nom.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les deux réactions rompent la liaison ester, mais l'état acido-basique du fragment carboxylique diffère.`,
    choiceExplanations: [
      `Le milieu acide favorise la forme protonée.`,
      `Le milieu basique favorise la forme carboxylate.`,
      `Le groupe lié à l'oxygène est libéré sous forme d'alcool.`,
      `Seule l'hydrolyse basique est appelée saponification.`,
    ],
  },
  {
    order: 36,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On hydrolyse le méthanoate de méthyle $\mathrm{HCOOCH_3}$ en milieu acide. Les produits attendus sont :`,
    choices: [
      `L'acide méthanoïque $\mathrm{HCOOH}$.`,
      `Le méthanol $\mathrm{CH_3OH}$.`,
      `L'ion méthanoate comme seul produit carboxylique.`,
      `Un alcool et un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le fragment acyle fournit l'acide méthanoïque et le fragment méthoxy fournit le méthanol.`,
    choiceExplanations: [
      `Il provient du fragment $\mathrm{HCO-}$.`,
      `Il provient du groupe $\mathrm{-OCH_3}$.`,
      `En milieu acide, la forme $\mathrm{HCOOH}$ est attendue.`,
      `Ce sont les deux familles de produits.`,
    ],
  },
  {
    order: 37,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On saponifie le propanoate de méthyle $\mathrm{CH_3CH_2COOCH_3}$. Les produits organiques attendus comprennent :`,
    choices: [
      `L'ion propanoate $\mathrm{CH_3CH_2COO^-}$.`,
      `Le méthanol $\mathrm{CH_3OH}$.`,
      `L'acide propanoïque comme forme majoritaire imposée par le milieu basique.`,
      `Un carboxylate et un alcool.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La partie acyle donne le propanoate et la partie méthoxy donne le méthanol.`,
    choiceExplanations: [
      `Le milieu basique déprotone l'acide carboxylique formé.`,
      `Le groupe $\mathrm{-OCH_3}$ devient méthanol.`,
      `La forme carboxylate domine en milieu basique.`,
      `C'est le bilan général de la saponification.`,
    ],
  },
  {
    order: 38,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'expérience **A** :`,
    choices: [
      `L'acide éthanoïque peut être formé.`,
      `L'éthanol peut être formé.`,
      `Le produit carboxylique principal est l'ion éthanoate imposé par le milieu acide.`,
      `Il s'agit d'une hydrolyse acide.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'hydrolyse acide de l'éthanoate d'éthyle donne l'acide éthanoïque et l'éthanol.`,
    choiceExplanations: [
      `Le fragment $\mathrm{CH_3CO-}$ devient $\mathrm{CH_3COOH}$.`,
      `Le fragment éthoxy devient $\mathrm{CH_3CH_2OH}$.`,
      `Le milieu acide favorise l'acide éthanoïque.`,
      `L'eau et l'acidité sont les conditions indiquées.`,
    ],
  },
  {
    order: 39,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'expérience **B** :`,
    choices: [
      `L'ion éthanoate $\mathrm{CH_3COO^-}$ peut être formé.`,
      `L'éthanol peut être formé.`,
      `La réaction est une saponification.`,
      `Elle ne rompt pas la fonction ester.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La saponification donne l'ion éthanoate et l'éthanol.`,
    choiceExplanations: [
      `Le milieu basique stabilise la forme carboxylate.`,
      `Le fragment éthoxy devient alcool.`,
      `C'est une hydrolyse en milieu basique.`,
      `La liaison acyle''�oxygène est rompue.`,
    ],
  },
  {
    order: 40,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison des expériences **A** et **B** :`,
    choices: [
      `Les deux libèrent de l'éthanol.`,
      `A forme préférentiellement $\mathrm{CH_3COOH}$.`,
      `B forme préférentiellement $\mathrm{CH_3COO^-}$.`,
      `A et B sont toutes deux appelées saponifications.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le même squelette ester est hydrolysé ; la différence principale porte sur la forme acide ou carboxylate du fragment acyle.`,
    choiceExplanations: [
      `Le groupe éthoxy est commun aux deux réactions.`,
      `Le milieu acide favorise la forme protonée.`,
      `Le milieu basique favorise le carboxylate.`,
      `Seule B est basique et porte ce nom.`,
    ],
  },
  {
    order: 41,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant la rotation dans une fonction ester selon la fiche :`,
    choices: [
      `La rotation autour de la liaison $\mathrm{C{-}O}$ est considérée libre.`,
      `Cette propriété distingue l'ester de l'amide décrite plus loin.`,
      `Toute liaison de l'ester est une liaison triple.`,
      `La molécule ne contient aucun hétéroatome.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La liaison simple $\mathrm{C{-}O}$ de l'ester est présentée comme permettant une libre rotation.`,
    choiceExplanations: [
      `C'est la propriété explicitement indiquée.`,
      `L'amide présente un caractère partiel de double liaison.`,
      `L'ester contient une liaison carbonyle double et des liaisons simples.`,
      `Elle contient deux atomes d'oxygène.`,
    ],
  },
  {
    order: 42,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La fonction ester contient :`,
    choices: [
      `Deux atomes d'oxygène.`,
      `Un oxygène engagé dans le groupe carbonyle.`,
      `Un oxygène lié au carbone carbonylé et au radical $\mathrm{R'}$.`,
      `Nécessairement un atome d'azote.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les deux oxygènes n'ont pas exactement le même environnement : l'un est carbonylé, l'autre est lié au radical $\mathrm{R'}$.`,
    choiceExplanations: [
      `C'est une caractéristique structurale de l'ester.`,
      `Il est lié par une double liaison au carbone.`,
      `C'est l'oxygène alkoxy de l'ester.`,
      `L'azote caractérise l'amide, pas l'ester simple.`,
    ],
  },
  {
    order: 43,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un ester, le carbone du groupe $\mathrm{C{=}O}$ :`,
    choices: [
      `Possède un caractère électrophile.`,
      `Est attiré par les espèces riches en électrons.`,
      `Est nécessairement un nucléophile très riche en électrons.`,
      `Peut constituer le centre attaqué lors d'une substitution acyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'effet électroattracteur de l'oxygène appauvrit le carbone carbonylé en électrons et lui confère un caractère électrophile.`,
    choiceExplanations: [
      `Il peut être attaqué par un nucléophile.`,
      `Les nucléophiles réagissent avec ce centre.`,
      `Le carbonyle est au contraire polarisé vers l'oxygène.`,
      `Le nucléophile se fixe sur ce carbone.`,
    ],
  },
  {
    order: 44,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le caractère électrophile du carbonyle d'un ester s'explique notamment par :`,
    choices: [
      `L'effet électroattracteur de l'oxygène.`,
      `Un déficit électronique relatif sur le carbone carbonylé.`,
      `L'absence totale d'oxygène dans la fonction.`,
      `La possibilité d'une attaque par un nucléophile.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'oxygène, plus électroattracteur, attire la densité électronique de la liaison carbonyle.`,
    choiceExplanations: [
      `Il polarise la liaison $\mathrm{C{=}O}$.`,
      `Ce déficit rend le carbone sensible aux nucléophiles.`,
      `Deux oxygènes sont présents.`,
      `C'est la conséquence réactive de cette polarisation.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On considère $\mathrm{RCH_2COOR'}$. Le carbone du groupe $\mathrm{CH_2}$ voisin du carbonyle :`,
    choices: [
      `Est situé en alpha du carbonyle.`,
      `Peut devenir nucléophile dans certaines conditions.`,
      `Est toujours le centre le plus électrophile de la molécule.`,
      `Peut réagir avec un électrophile après activation basique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le carbone en alpha peut acquérir un caractère nucléophile, surtout après traitement par une base forte.`,
    choiceExplanations: [
      `Il est directement adjacent au carbone carbonylé.`,
      `Une base forte peut conduire à une espèce riche en électrons sur ce carbone.`,
      `Le carbone carbonylé est le centre électrophile principal.`,
      `L'électrophile se fixe sur ce carbone en alpha.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La fonction ester peut donc présenter deux centres de réactivité différents :`,
    choices: [
      `Le carbone carbonylé peut être électrophile.`,
      `Le carbone en alpha peut devenir nucléophile.`,
      `Le choix du centre dépend des conditions expérimentales.`,
      `Les deux centres sont toujours totalement inertes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le carbonyle est électrophile, tandis que le carbone en alpha peut devenir nucléophile selon les conditions.`,
    choiceExplanations: [
      `Il est attaqué par les nucléophiles.`,
      `Une base forte favorise cette réactivité.`,
      `La présence d'une base ou d'un nucléophile oriente la réaction.`,
      `La fiche décrit précisément leur réactivité.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lorsqu'un nucléophile attaque directement un ester :`,
    choices: [
      `L'attaque a lieu sur le carbone carbonylé.`,
      `Le groupement $\mathrm{OR'}$ peut être remplacé.`,
      `Le produit peut contenir le motif $\mathrm{RCO{-}Nu}$.`,
      `Le nucléophile attaque obligatoirement l'oxygène du groupe $\mathrm{OR'}$ sans toucher au carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le nucléophile vise le carbone électrophile du carbonyle, puis peut remplacer le groupe $\mathrm{OR'}$.`,
    choiceExplanations: [
      `C'est le centre déficitaire en électrons.`,
      `Le bilan simplifié donne un dérivé $\mathrm{RCO{-}Nu}$.`,
      `Le nucléophile devient lié au groupe acyle.`,
      `Le centre électrophile indiqué est le carbone du carbonyle.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une base forte est ajoutée à un ester possédant un groupe $\mathrm{CH_2}$ en alpha. Selon la fiche :`,
    choices: [
      `Le carbone en alpha peut devenir riche en électrons.`,
      `Ce carbone peut ensuite attaquer un électrophile.`,
      `Le carbone carbonylé devient nécessairement un anion permanent.`,
      `Les conditions basiques peuvent orienter une réactivité différente de l'attaque directe du carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La base forte peut rendre le carbone en alpha nucléophile en créant un excès de densité électronique sur ce site.`,
    choiceExplanations: [
      `La base favorise la formation d'une espèce carbanionique ou apparentée.`,
      `L'électrophile se fixe sur le carbone en alpha.`,
      `La nucléophilie décrite concerne le carbone voisin du carbonyle.`,
      `On exploite alors le centre nucléophile en alpha.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `�' propos des représentations limite évoquées pour un ester possédant un hydrogène en alpha :`,
    choices: [
      `Une forme avec charge négative sur le carbone en alpha peut être envisagée.`,
      `Une forme présentant une liaison $\mathrm{C{=}C}$ et un groupe $\mathrm{OH}$ peut être dessinée.`,
      `Le groupe $\mathrm{OR'}$ disparaît nécessairement dans toutes les représentations.`,
      `Ces représentations expliquent la réactivité du carbone voisin du carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La densité électronique peut être représentée sur le carbone en alpha tout en conservant le carbonyle, ou dans une forme apparentée à un énol.`,
    choiceExplanations: [
      `Elle traduit le caractère nucléophile de ce carbone.`,
      `Elle ressemble à une forme énolique tout en conservant le groupe $\mathrm{OR'}$.`,
      `Il reste attaché à la fonction dans les formes décrites.`,
      `Elles rendent compte de sa possible nucléophilie.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors de la synthèse d'un intermédiaire, on veut faire réagir sélectivement le carbonyle d'un ester avec un nucléophile. Il faut retenir que :`,
    choices: [
      `Le centre visé est le carbone du $\mathrm{C{=}O}$.`,
      `Le nucléophile apporte une paire d'électrons pour former la nouvelle liaison.`,
      `Le groupe $\mathrm{OR'}$ peut jouer le rôle de groupe remplacé dans le bilan.`,
      `Le carbone carbonylé est choisi parce qu'il est fortement nucléophile.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le nucléophile est attiré par le carbone électrophile du carbonyle et peut conduire au remplacement du groupe alkoxy.`,
    choiceExplanations: [
      `C'est le centre électrophile de l'ester.`,
      `C'est la définition de son comportement nucléophile.`,
      `La fiche résume la réaction par $\mathrm{RCOOR' + Nu ightarrow RCO{-}Nu}$.`,
      `Il est choisi parce qu'il est électrophile.`,
    ],
  },
  {
    order: 51,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le bilan simplifié $\mathrm{RCOOR' + Nu^- ightarrow RCO{-}Nu}$ traduit :`,
    choices: [
      `Une attaque du nucléophile sur le carbone carbonylé.`,
      `Le remplacement du groupe $\mathrm{OR'}$.`,
      `La formation d'une nouvelle liaison entre le carbone acyle et $\mathrm{Nu}$.`,
      `Une réaction ne modifiant jamais la fonction ester.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le nucléophile attaque le groupe acyle de l'ester et remplace le groupe $\mathrm{OR'}$.`,
    choiceExplanations: [
      `C'est le centre électrophile.`,
      `Le nucléophile prend sa place dans le produit simplifié.`,
      `Le produit contient $\mathrm{RCO{-}Nu}$.`,
      `Le groupe alkoxy de l'ester est remplacé.`,
    ],
  },
  {
    order: 52,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On fait réagir un ester avec une espèce nucléophile portant une charge négative. �' propos de l'orientation de l'attaque :`,
    choices: [
      `Le nucléophile est attiré par un centre électrophile.`,
      `Le carbone du carbonyle constitue ce centre.`,
      `L'attaque se fait parce que le nucléophile manque d'électrons.`,
      `La polarisation de la liaison $\mathrm{C{=}O}$ explique cette réactivité.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'espèce riche en électrons se dirige vers le carbone carbonylé, appauvri en électrons.`,
    choiceExplanations: [
      `Les charges et polarités opposées favorisent l'interaction.`,
      `L'oxygène attire la densité électronique.`,
      `Un nucléophile est au contraire riche en électrons.`,
      `Elle crée un déficit relatif sur le carbone.`,
    ],
  },
  {
    order: 53,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour rendre nucléophile le carbone en alpha d'un ester :`,
    choices: [
      `Une base forte peut être utilisée.`,
      `Le carbone concerné est voisin du carbonyle.`,
      `L'espèce obtenue peut réagir avec un électrophile.`,
      `Il faut impérativement supprimer le groupe carbonyle avant toute réaction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours propose l'utilisation d'une base forte, puis la réaction avec un électrophile.`,
    choiceExplanations: [
      `Elle favorise l'apparition d'un excès de densité électronique sur le carbone en alpha.`,
      `Il s'agit du carbone en alpha.`,
      `Une nouvelle liaison peut se former sur ce carbone.`,
      `Le carbonyle reste présent dans le schéma du cours.`,
    ],
  },
  {
    order: 54,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un ester $\mathrm{RCH_2COOR'}$ est traité par une base forte puis par $\mathrm{E^+}$. Le produit attendu selon le schéma du cours :`,
    choices: [
      `Conserve la fonction ester.`,
      `Porte le nouvel électrophile sur le carbone initialement $\mathrm{CH_2}$.`,
      `Peut s'écrire $\mathrm{RCH(E)COOR'}$.`,
      `Résulte d'une attaque de $\mathrm{E^+}$ sur un autre électrophile.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'électrophile se fixe sur le carbone en alpha, donnant $\mathrm{RCH(E)COOR'}$.`,
    choiceExplanations: [
      `Le groupe $\mathrm{COOR'}$ reste présent.`,
      `C'est le site devenu nucléophile.`,
      `Cette formule traduit la substitution en alpha.`,
      `$\mathrm{E^+}$ réagit avec le centre nucléophile en alpha.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Comparaison des deux voies de réactivité d'un ester :`,
    choices: [
      `Nucléophile + ester : attaque privilégiée du carbonyle.`,
      `Base forte puis électrophile : réaction au carbone en alpha.`,
      `Les deux voies exploitent exactement le même centre réactif.`,
      `Les conditions expérimentales déterminent le site exploité.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Une attaque nucléophile vise le carbone carbonylé ; après base forte, un électrophile peut être fixé sur le carbone en alpha.`,
    choiceExplanations: [
      `Le carbonyle est électrophile.`,
      `Ce carbone est rendu nucléophile.`,
      `Elles concernent deux carbones différents.`,
      `La nature des réactifs oriente la réactivité.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On souhaite introduire un substituant carboné en alpha d'un ester sans supprimer la fonction ester. La stratégie cohérente est :`,
    choices: [
      `Employer d'abord une base forte.`,
      `Ajouter ensuite un électrophile approprié.`,
      `Attaquer directement le carbonyle avec un nucléophile si l'on veut conserver à coup sûr le groupe $\mathrm{OR'}$.`,
      `Conserver le carbonyle dans le produit final est compatible avec la réaction en alpha.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Une base forte active le carbone en alpha, puis un électrophile apporte le nouveau substituant.`,
    choiceExplanations: [
      `Elle rend le carbone en alpha nucléophile.`,
      `Il se fixe sur le centre nucléophile.`,
      `Cette voie peut remplacer le groupe $\mathrm{OR'}$.`,
      `Le schéma montre la fonction ester inchangée.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans $\mathrm{CH_3COOR}$, les hydrogènes du groupe $\mathrm{CH_3}$ sont en alpha du carbonyle. Après action d'une base forte :`,
    choices: [
      `Le groupe $\mathrm{CH_3}$ est directement voisin du carbonyle.`,
      `Le carbone correspondant peut acquérir un caractère nucléophile.`,
      `Un électrophile peut se fixer sur ce carbone.`,
      `Le carbone carbonylé devient nécessairement un alcool.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le carbone du méthyle peut devenir le centre nucléophile qui réagit ensuite avec un électrophile.`,
    choiceExplanations: [
      `Il occupe la position alpha.`,
      `La base forte favorise l'espèce riche en électrons.`,
      `La nouvelle liaison se forme en alpha.`,
      `La fonction ester peut rester intacte.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la **voie I** :`,
    choices: [
      `Le carbone carbonylé est le centre électrophile.`,
      `$\mathrm{Nu^-}$ est l'espèce riche en électrons.`,
      `Le produit simplifié peut contenir $\mathrm{CH_3CH_2CO{-}Nu}$.`,
      `Le nouvel atome se fixe obligatoirement sur le carbone terminal $\mathrm{CH_3}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le nucléophile attaque le carbone carbonylé et le groupe $\mathrm{OR}$ peut être remplacé.`,
    choiceExplanations: [
      `Il est polarisé par l'oxygène.`,
      `Elle apporte les électrons de la nouvelle liaison.`,
      `Le groupe $\mathrm{OR}$ est remplacé.`,
      `La voie I vise le carbone carbonylé.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la **voie II** :`,
    choices: [
      `Le carbone $\mathrm{CH_2}$ voisin du carbonyle est activé.`,
      `La fonction ester peut être conservée.`,
      `$\mathrm{E^+}$ se fixe sur le carbone en alpha.`,
      `La base forte transforme obligatoirement l'ester en amide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La base forte rend le carbone en alpha nucléophile ; l'électrophile se fixe ensuite sur ce carbone.`,
    choiceExplanations: [
      `Il s'agit du carbone en alpha.`,
      `Le schéma final garde $\mathrm{COOR}$.`,
      `Il réagit avec le centre devenu nucléophile.`,
      `Aucune amine n'est introduite.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Comparaison des voies **I** et **II** :`,
    choices: [
      `La voie I exploite le caractère électrophile du carbonyle.`,
      `La voie II exploite le caractère nucléophile du carbone en alpha.`,
      `La nature du réactif détermine le site de réaction.`,
      `Les deux voies donnent obligatoirement le même produit.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les deux voies illustrent la dualité réactive de l'ester : carbonyle électrophile et carbone en alpha potentiellement nucléophile.`,
    choiceExplanations: [
      `Le nucléophile l'attaque.`,
      `Ce caractère apparaît après traitement basique.`,
      `Nucléophile ou base puis électrophile conduisent à des sites distincts.`,
      `Elles forment des liaisons à des positions différentes.`,
    ],
  },
];
