/**
 * Cartographie éditoriale V2
 * UE14 – Biochimie – Chapitre 1.2
 * Les oses simples et dérivés
 */

export const UE14_BIOCH_CH2_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'section-a-discovery-principaux-oses-simples',
    title: `Principaux oses simples et propriétés`,
    description: `Repères sur glucose, galactose, mannose, fructose, ribose, trioses et leurs principaux rôles biologiques.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'section-a-practice-proprietes-fehling-oses',
    title: `Principaux oses simples et propriétés`,
    description: `Applications sur les propriétés physiques des oses, le pouvoir réducteur, la liqueur de Fehling et les épiméries de référence.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,21,22],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'section-b-discovery-acide-glucuronique-polyols',
    title: `Oxydation, réduction et polyols`,
    description: `Repères sur l'acide glucuronique, la glucuronoconjugaison et les polyols issus de la réduction des oses.`,
    stage: 'DISCOVER' as const,
    questionOrders: [23,24,25,26,27,28,29,30,31,32],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'section-b-practice-glucuronoconjugaison-polyols',
    title: `Oxydation, réduction et polyols`,
    description: `Applications sur glucuronate, glycérol, mannitol, sorbitol et les usages biologiques, alimentaires ou médicaux cités.`,
    stage: 'PRACTICE' as const,
    questionOrders: [33,34,35,36,37,38,39,40,41,42,43,44],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'section-c-discovery-osamines-n-acetylees',
    title: `Osamines et acides sialiques`,
    description: `Repères sur les osamines, leur N-acétylation, la chitine et la formation de l'acide neuraminique.`,
    stage: 'DISCOVER' as const,
    questionOrders: [45,46,47,48,49,50,51,52,53,54],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'section-c-practice-nana-acide-sialique',
    title: `Osamines et acides sialiques`,
    description: `Applications sur le NANA, sa fonction acide, ses charges et ses rôles dans les glycoconjugués de surface.`,
    stage: 'PRACTICE' as const,
    questionOrders: [55,56,57,58,59,60,61,62,63,64,65,66],
  },
  {
    sectionOrder: 3,
    order: 3,
    slug: 'section-c-master-osamines-nana-reconnaissance',
    title: `Osamines et acides sialiques`,
    description: `Maîtrise des transformations C2, de la N-acétylation, de la voie vers le NANA et de ses conséquences électrostatiques et biologiques.`,
    stage: 'MASTER' as const,
    questionOrders: [67,68,69,70,71,72,73,74,75,76,77,78],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'section-d-discovery-oses-phosphoryles-sulfates',
    title: `Oses estérifiés et autres dérivés`,
    description: `Repères sur les esters phosphoriques et sulfuriques, leurs positions de substitution et leurs contextes métaboliques.`,
    stage: 'DISCOVER' as const,
    questionOrders: [79,80,81,82,83,84,85,86,87,88],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'section-d-practice-phosphates-vitamine-c-streptomycine',
    title: `Oses estérifiés et autres dérivés`,
    description: `Applications sur les oses phosphorylés, les GAG sulfatés, l'acide ascorbique et la streptomycine.`,
    stage: 'PRACTICE' as const,
    questionOrders: [89,90,91,92,93,94,95,96,97,98,99,100],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'section-e-synthesis-practice-oses-derives',
    title: `Oses simples et dérivés`,
    description: `Synthèse appliquée des principaux oses, propriétés redox, dérivés oxydés, polyols, osamines et esters d'oses.`,
    stage: 'PRACTICE' as const,
    questionOrders: [101,102,103,104,105,106,107,108,109,110],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'maitriser-synthese-oses-simples-derives',
    title: `Oses simples et dérivés`,
    description: `Maîtrise transversale du chapitre dans des situations proches de l'examen, sans transformer le quiz en examen blanc.`,
    stage: 'MASTER' as const,
    questionOrders: [111,112,113,114,115,116,117,118,119,120,121,122],
  },
] as const;

export const UE14_BIOCH_CH2_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Oses simples : rôles et repères`],
  2: [`Oses simples : rôles et repères`],
  3: [`Oses simples : rôles et repères`],
  4: [`Oses simples : rôles et repères`],
  5: [`Glucose et glycémie`],
  6: [`Oses simples : rôles et repères`],
  7: [`Oses simples : rôles et repères`],
  8: [`Galactose : épimérie C4`],
  9: [`Oses simples : rôles et repères`],
  10: [`Mannose : épimérie C2`],
  11: [`Oses simples : propriétés et Fehling`],
  12: [`Oses simples : propriétés et Fehling`],
  13: [`Oses simples : propriétés et Fehling`],
  14: [`Oses simples : propriétés et Fehling`],
  15: [`Oses simples : propriétés et Fehling`],
  16: [`Oses simples : propriétés et Fehling`],
  17: [`Liqueur de Fehling : redox`],
  18: [`QROC : précipité de Fehling`],
  19: [`Oses simples : propriétés et Fehling`],
  20: [`Oses simples : propriétés et Fehling`],
  21: [`Épiméries du glucose : QRP`],
  22: [`Oses simples : QRPL`],
  23: [`Dérivés oxydés et polyols : repères`],
  24: [`Glucose → acide glucuronique`],
  25: [`Dérivés oxydés et polyols : repères`],
  26: [`Dérivés oxydés et polyols : repères`],
  27: [`Dérivés oxydés et polyols : repères`],
  28: [`Glucuronoconjugaison`],
  29: [`Dérivés oxydés et polyols : repères`],
  30: [`Dérivés oxydés et polyols : repères`],
  31: [`Dérivés oxydés et polyols : repères`],
  32: [`Glycéraldéhyde → glycérol`],
  33: [`Glucuronoconjugaison et polyols : applications`],
  34: [`Mannose → mannitol`],
  35: [`Glucuronoconjugaison et polyols : applications`],
  36: [`Glucose → sorbitol`],
  37: [`Glucuronoconjugaison et polyols : applications`],
  38: [`Glucuronoconjugaison et polyols : applications`],
  39: [`Glucuronoconjugaison : application`],
  40: [`Glucuronoconjugaison et polyols : applications`],
  41: [`Glucuronoconjugaison et polyols : applications`],
  42: [`Glucuronoconjugaison et polyols : applications`],
  43: [`Glucuronoconjugaison et polyols : applications`],
  44: [`Redox et polyols : QRPL`],
  45: [`Osamine : NH2 en C2`],
  46: [`Osamines et N-acétylation : repères`],
  47: [`Osamines et N-acétylation : repères`],
  48: [`Osamine N-acétylée`],
  49: [`Chitine`],
  50: [`Osamines et N-acétylation : repères`],
  51: [`D-mannosamine + pyruvate`],
  52: [`Osamines et N-acétylation : repères`],
  53: [`Acide neuraminique : cyclisation C2-C6`],
  54: [`Osamines et N-acétylation : repères`],
  55: [`NANA : N-acétylation`],
  56: [`NANA et acide sialique : applications`],
  57: [`NANA : glycoconjugués et reconnaissance`],
  58: [`NANA : ionisation COO−`],
  59: [`NANA et acide sialique : applications`],
  60: [`NANA et acide sialique : applications`],
  61: [`NANA et acide sialique : applications`],
  62: [`NANA et acide sialique : applications`],
  63: [`QROC : acide sialique`],
  64: [`NANA et acide sialique : applications`],
  65: [`NANA et acide sialique : applications`],
  66: [`NANA et acide sialique : applications`],
  67: [`QZONE : osamine C2`],
  68: [`Osamines et NANA : maîtrise`],
  69: [`Osamines et NANA : maîtrise`],
  70: [`Osamines et NANA : maîtrise`],
  71: [`Osamines et NANA : maîtrise`],
  72: [`Osamines et NANA : maîtrise`],
  73: [`Voie D-mannosamine → NANA`],
  74: [`Osamines et NANA : maîtrise`],
  75: [`Osamines et NANA : maîtrise`],
  76: [`Osamines et NANA : maîtrise`],
  77: [`Osamines et NANA : maîtrise`],
  78: [`Osamines/NANA : QRPL`],
  79: [`Oses estérifiés : repères`],
  80: [`Oses estérifiés : repères`],
  81: [`Oses estérifiés : repères`],
  82: [`Glucose-6-phosphate`],
  83: [`Oses estérifiés : repères`],
  84: [`Fructose-1,6-bisphosphate`],
  85: [`Pentoses phosphorylés C5`],
  86: [`Oses estérifiés : repères`],
  87: [`GAG sulfatés : charge`],
  88: [`Acide ascorbique`],
  89: [`Phosphates, sulfates et autres dérivés`],
  90: [`Streptomycine`],
  91: [`Phosphates, sulfates et autres dérivés`],
  92: [`Phosphates, sulfates et autres dérivés`],
  93: [`Phosphates, sulfates et autres dérivés`],
  94: [`Phosphates, sulfates et autres dérivés`],
  95: [`QROC : fructose-1,6-bisphosphate`],
  96: [`Phosphates, sulfates et autres dérivés`],
  97: [`Phosphates, sulfates et autres dérivés`],
  98: [`Phosphates, sulfates et autres dérivés`],
  99: [`Phosphates, sulfates et autres dérivés`],
  100: [`Oses estérifiés : QRPL`],
  101: [`Synthèse appliquée des oses et dérivés`],
  102: [`Synthèse appliquée des oses et dérivés`],
  103: [`Synthèse appliquée des oses et dérivés`],
  104: [`Synthèse appliquée des oses et dérivés`],
  105: [`Synthèse appliquée des oses et dérivés`],
  106: [`Synthèse appliquée des oses et dérivés`],
  107: [`Synthèse appliquée des oses et dérivés`],
  108: [`Synthèse appliquée des oses et dérivés`],
  109: [`Polyols d'hexoses : QRP`],
  110: [`Synthèse PRACTICE : QRPL`],
  111: [`Maîtrise transversale des oses et dérivés`],
  112: [`Maîtrise transversale des oses et dérivés`],
  113: [`Voie vers le NANA`],
  114: [`NANA : charge et reconnaissance`],
  115: [`Maîtrise transversale des oses et dérivés`],
  116: [`Maîtrise transversale des oses et dérivés`],
  117: [`Maîtrise transversale des oses et dérivés`],
  118: [`Fructose-1,6-bisphosphate : QROC`],
  119: [`Maîtrise transversale des oses et dérivés`],
  120: [`Maîtrise transversale des oses et dérivés`],
  121: [`Maîtrise transversale des oses et dérivés`],
  122: [`Synthèse MASTER : QRPL`],
};
