/**
 * Cartographie éditoriale V2
 * UE14 – Chimie organique – Chapitre 2.5
 * Les esters et les amides
 */

export const UE14_CH9_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'section-a-discovery-fonctions-ester-amide',
    title: `Fonctions ester et amide`,
    description: `Repères sur la reconnaissance des fonctions ester et amide, les acides activés et l'intérêt biologique de la liaison peptidique.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'section-a-practice-preparation-esters-amides',
    title: `Fonctions ester et amide`,
    description: `Applications sur la préparation des esters et des amides et la distinction entre acide activé et réaction acide-base.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,21,22],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'section-b-discovery-hydrolyse-esters',
    title: `Esters : hydrolyse, polarisation et réactivité`,
    description: `Repères sur hydrolyse acide, saponification, libre rotation et polarisation de la fonction ester.`,
    stage: 'DISCOVER' as const,
    questionOrders: [23,24,25,26,27,28,29,30,31,32],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'section-b-practice-polarisation-centres-reactifs-esters',
    title: `Esters : hydrolyse, polarisation et réactivité`,
    description: `Applications sur le carbone carbonylé électrophile, le carbone alpha potentiellement nucléophile et les produits d'hydrolyse.`,
    stage: 'PRACTICE' as const,
    questionOrders: [33,34,35,36,37,38,39,40,41,42,43,44],
  },
  {
    sectionOrder: 2,
    order: 3,
    slug: 'section-b-master-reactivite-carbonyle-carbone-alpha',
    title: `Esters : hydrolyse, polarisation et réactivité`,
    description: `Maîtrise des deux centres de réactivité de l'ester et du choix des conditions expérimentales.`,
    stage: 'MASTER' as const,
    questionOrders: [45,46,47,48,49,50,51,52,53,54,55,56],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'section-c-discovery-hydrolyse-amides-selectivite',
    title: `Amides : hydrolyse, sélectivité et propriétés électroniques`,
    description: `Repères sur préparation, hydrolyse chimique, sélectivité ester/amide et hydrolyses enzymatiques.`,
    stage: 'DISCOVER' as const,
    questionOrders: [57,58,59,60,61,62,63,64,65,66],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'section-c-practice-enzymes-esterases-proteases',
    title: `Amides : hydrolyse, sélectivité et propriétés électroniques`,
    description: `Applications sur la résistance à l'hydrolyse, les protéases et le caractère partiel de double liaison de la fonction amide.`,
    stage: 'PRACTICE' as const,
    questionOrders: [67,68,69,70,71,72,73,74,75,76,77,78],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'section-d-discovery-thioesters-structure-preparation',
    title: `Thioesters et acétyl-CoA`,
    description: `Repères sur structure, préparation, polarisation et hydrolyse des thioesters.`,
    stage: 'DISCOVER' as const,
    questionOrders: [79,80,81,82,83,84,85,86,87,88],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'section-d-practice-thioesters-hydrolyse-reactivite',
    title: `Thioesters et acétyl-CoA`,
    description: `Applications sur la réactivité des thioesters et l'interconversion acétyl-CoA / coenzyme A-SH.`,
    stage: 'PRACTICE' as const,
    questionOrders: [89,90,91,92,93,94,95,96,97,98,99,100],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'section-e-synthesis-practice-esters-amides-thioesters',
    title: `Esters, amides et thioesters`,
    description: `Synthèse appliquée des structures, préparations, hydrolyses, sélectivités et propriétés électroniques.`,
    stage: 'PRACTICE' as const,
    questionOrders: [101,102,103,104,105,106,107,108,109,110],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'maitriser-synthese-esters-amides-thioesters',
    title: `Esters, amides et thioesters`,
    description: `Maîtrise transversale du chapitre dans des situations proches de l'examen, sans transformer le quiz en examen blanc.`,
    stage: 'MASTER' as const,
    questionOrders: [111,112,113,114,115,116,117,118,119,120,121,122],
  },
] as const;

export const UE14_CH9_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Fonctions ester et amide : repères`],
  2: [`Fonctions ester et amide : repères`],
  3: [`Fonctions ester et amide : repères`],
  4: [`Fonctions ester et amide : repères`],
  5: [`Amide et liaison peptidique`],
  6: [`Proline et environnement de l'azote amide`],
  7: [`Fonctions ester et amide : repères`],
  8: [`Fonctions ester et amide : repères`],
  9: [`Fonctions ester et amide : repères`],
  10: [`Acide non activé + amine : sel`],
  11: [`Esters et amides : préparation et intérêt biologique`],
  12: [`Esters et amides : préparation et intérêt biologique`],
  13: [`Esters et amides : préparation et intérêt biologique`],
  14: [`Esters et amides : préparation et intérêt biologique`],
  15: [`Esters et amides : préparation et intérêt biologique`],
  16: [`Acide activé + O/N/S`],
  17: [`Esters et amides : préparation et intérêt biologique`],
  18: [`Esters et amides : préparation et intérêt biologique`],
  19: [`Esters et amides : préparation et intérêt biologique`],
  20: [`Esters et amides : préparation et intérêt biologique`],
  21: [`Fonctions et préparation : synthèse QRPL`],
  22: [`Esters et amides : préparation et intérêt biologique`],
  23: [`Esters : hydrolyse et polarisation`],
  24: [`Saponification : définition`],
  25: [`Esters : hydrolyse et polarisation`],
  26: [`Esters : hydrolyse et polarisation`],
  27: [`Esters : hydrolyse et polarisation`],
  28: [`Esters : hydrolyse et polarisation`],
  29: [`Esters : hydrolyse et polarisation`],
  30: [`Ester : carbone carbonylé électrophile`],
  31: [`Ester : carbone alpha potentiellement nucléophile`],
  32: [`Esters : hydrolyse et polarisation`],
  33: [`Esters : centres réactifs et applications`],
  34: [`Base forte puis électrophile : réactivité alpha`],
  35: [`Esters : centres réactifs et applications`],
  36: [`Esters : centres réactifs et applications`],
  37: [`Esters : centres réactifs et applications`],
  38: [`Esters : centres réactifs et applications`],
  39: [`Esters : centres réactifs et applications`],
  40: [`Esters : centres réactifs et applications`],
  41: [`Esters : centres réactifs et applications`],
  42: [`Représentations électroniques du carbone alpha`],
  43: [`Esters : centres réactifs et applications`],
  44: [`Esters : centres réactifs et applications`],
  45: [`Esters : maîtrise de la réactivité`],
  46: [`Esters : maîtrise de la réactivité`],
  47: [`Esters : maîtrise de la réactivité`],
  48: [`Esters : maîtrise de la réactivité`],
  49: [`Esters : maîtrise de la réactivité`],
  50: [`Esters : maîtrise de la réactivité`],
  51: [`Esters : maîtrise de la réactivité`],
  52: [`QZONE : carbone carbonylé électrophile`],
  53: [`Esters : maîtrise de la réactivité`],
  54: [`Esters : maîtrise de la réactivité`],
  55: [`Esters : synthèse MASTER QRPL`],
  56: [`Esters : maîtrise de la réactivité`],
  57: [`Amides : hydrolyse et propriétés`],
  58: [`Amides : hydrolyse et propriétés`],
  59: [`Amides : hydrolyse et propriétés`],
  60: [`Amides : hydrolyse et propriétés`],
  61: [`Sélectivité hydrolyse ester/amide`],
  62: [`Amides : hydrolyse et propriétés`],
  63: [`Peptidases digestives citées`],
  64: [`Amides : hydrolyse et propriétés`],
  65: [`Amide : caractère partiel de double liaison`],
  66: [`Délocalisation du doublet de N`],
  67: [`Amides : sélectivité, enzymes et délocalisation`],
  68: [`Amides : sélectivité, enzymes et délocalisation`],
  69: [`Amides : sélectivité, enzymes et délocalisation`],
  70: [`Amides : sélectivité, enzymes et délocalisation`],
  71: [`Amides : sélectivité, enzymes et délocalisation`],
  72: [`Amides : sélectivité, enzymes et délocalisation`],
  73: [`Hydrolyse enzymatique physiologique`],
  74: [`Amides : sélectivité, enzymes et délocalisation`],
  75: [`Amides : sélectivité, enzymes et délocalisation`],
  76: [`Amides : sélectivité, enzymes et délocalisation`],
  77: [`Amides : synthèse QRPL`],
  78: [`Amides : sélectivité, enzymes et délocalisation`],
  79: [`Thioesters : structure et acétyl-CoA`],
  80: [`Thioesters : structure et acétyl-CoA`],
  81: [`Thioesters : structure et acétyl-CoA`],
  82: [`Thioesters : structure et acétyl-CoA`],
  83: [`Thioesters : structure et acétyl-CoA`],
  84: [`Acétyl-CoA : thioester`],
  85: [`Hydrolyse de l'acétyl-CoA`],
  86: [`Thioesters : structure et acétyl-CoA`],
  87: [`Thioesters : structure et acétyl-CoA`],
  88: [`Thioesters : structure et acétyl-CoA`],
  89: [`Thioesters : hydrolyse et réactivité`],
  90: [`Thioesters : hydrolyse et réactivité`],
  91: [`Thioesters : hydrolyse et réactivité`],
  92: [`Acétyl-CoA / CoA-SH`],
  93: [`Thioesters : hydrolyse et réactivité`],
  94: [`Thioesters : hydrolyse et réactivité`],
  95: [`Thioesters : hydrolyse et réactivité`],
  96: [`Thioesters : hydrolyse et réactivité`],
  97: [`Thioesters : hydrolyse et réactivité`],
  98: [`Thioesters : hydrolyse et réactivité`],
  99: [`Thioesters : synthèse QRPL`],
  100: [`Thioesters : hydrolyse et réactivité`],
  101: [`Synthèse appliquée : esters, amides, thioesters`],
  102: [`Synthèse appliquée : esters, amides, thioesters`],
  103: [`Synthèse appliquée : esters, amides, thioesters`],
  104: [`Synthèse appliquée : esters, amides, thioesters`],
  105: [`Applications biologiques du chapitre`],
  106: [`Comparaison électronique ester/amide`],
  107: [`Synthèse appliquée : esters, amides, thioesters`],
  108: [`Synthèse appliquée : esters, amides, thioesters`],
  109: [`Synthèse appliquée : esters, amides, thioesters`],
  110: [`Synthèse appliquée : esters, amides, thioesters`],
  111: [`Hydrolyse sélective ester/amide`],
  112: [`Maîtrise transversale des dérivés d'acide`],
  113: [`Deux centres de réactivité de l'ester`],
  114: [`Maîtrise transversale des dérivés d'acide`],
  115: [`Maîtrise transversale des dérivés d'acide`],
  116: [`Rigidité de la liaison peptidique`],
  117: [`Cycle acétyl-CoA / CoA-SH`],
  118: [`Maîtrise transversale des dérivés d'acide`],
  119: [`Maîtrise transversale des dérivés d'acide`],
  120: [`Maîtrise transversale des dérivés d'acide`],
  121: [`Maîtrise transversale des dérivés d'acide`],
  122: [`Synthèse générale QRPL`],
};
