/**
 * UE14 – Biologie cellulaire – Chapitre 6
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La β-oxydation peroxysomale concerne préférentiellement :`,
    choices: [
      `Les acides gras à longues chaînes.`,
      `Les acides gras à très longues chaînes.`,
      `Le raccourcissement des chaînes carbonées.`,
      `Uniquement des molécules dépourvues de carbone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche attribue au peroxysome le raccourcissement des acides gras longs et surtout très longs.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Le raccourcissement peroxysomal se poursuit jusqu’à obtenir des acides gras :`,
    choices: [
      `De moins de 12 carbones selon la fiche.`,
      `De plus de 100 carbones.`,
      `Sans aucun carbone.`,
      `Toujours à 50 carbones.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La fiche donne le seuil d’acides gras raccourcis à moins de 12 carbones avant transfert.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des mitochondries et des acides gras :`,
    choices: [
      `Elles n’oxydent pas les acides gras à très longue chaîne selon la fiche.`,
      `Elles oxydent souvent les chaînes courtes, moyennes ou longues.`,
      `Elles reçoivent des produits issus du peroxysome.`,
      `Elles rendent les peroxysomes inutiles pour les très longues chaînes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La complémentarité repose sur le pré-raccourcissement peroxysomal avant utilisation mitochondriale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La coopération peroxysome–mitochondrie implique :`,
    choices: [
      `Le raccourcissement initial dans le peroxysome.`,
      `La sortie d’acides gras raccourcis et d’acétyl-CoA.`,
      `Leur transfert vers la mitochondrie.`,
      `La fusion permanente des deux organites.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les organites coopèrent par transfert de métabolites, sans fusion permanente.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![β-oxydation et coopération mitochondriale](/images/training/ue14/biologie-cellulaire/peroxysomes/beta-oxydation-cooperation-mitochondrie.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les acides gras à très longue chaîne sont raccourcis dans le peroxysome.`,
      `Des acides gras raccourcis peuvent rejoindre la mitochondrie.`,
      `L’acétyl-CoA peut rejoindre la mitochondrie.`,
      `La mitochondrie réalise seule le raccourcissement initial des très longues chaînes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure illustre le rôle initial du peroxysome puis le relais mitochondrial.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les produits de la β-oxydation peroxysomale cités sont :`,
    choices: [
      `Des acides gras raccourcis.`,
      `De l’acétyl-CoA.`,
      `Du H2O2 associé aux réactions oxydatives.`,
      `Un génome peroxysomal nouvellement synthétisé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie raccourcit les acides gras, produit de l’acétyl-CoA et s’inscrit dans les oxydations générant du H2O2.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les fibrates :`,
    choices: [
      `Sont des médicaments hypolipémiants.`,
      `Stimulent la synthèse de peroxysomes selon la fiche.`,
      `Contribuent à diminuer les acides gras à très longue chaîne.`,
      `Détruisent obligatoirement tous les peroxysomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie les fibrates à une prolifération peroxysomale et à une diminution des très longues chaînes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’effet des fibrates est cohérent avec :`,
    choices: [
      `Une augmentation de la capacité peroxysomale.`,
      `Une meilleure prise en charge des acides gras à très longue chaîne.`,
      `Une régulation possible du nombre d’organites.`,
      `Une disparition du réseau peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La stimulation de la synthèse peroxysomale augmente la capacité de métabolisme des très longues chaînes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’acide urique provient du catabolisme :`,
    choices: [
      `Des acides nucléiques puriques.`,
      `De l’adénine.`,
      `De la guanine.`,
      `Uniquement des acides gras saturés.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie l’acide urique aux bases puriques adénine et guanine.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Chez les animaux possédant l’urate oxydase :`,
    choices: [
      `L’acide urique peut être transformé en allantoïne.`,
      `La réaction a lieu dans les peroxysomes.`,
      `L’allantoïne soluble peut être éliminée dans les urines.`,
      `L’urate oxydase transforme l’allantoïne en ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’urate oxydase peroxysomale produit de l’allantoïne soluble et éliminable.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Chez l’Homme, selon la fiche :`,
    choices: [
      `Il n’existe pas d’urate oxydase.`,
      `L’acide urique n’est donc pas converti en allantoïne par cette voie.`,
      `Un excès d’acide urique peut s’accumuler.`,
      `Tous les peroxysomes sont absents.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’absence d’une enzyme particulière ne signifie pas absence de peroxysomes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un excès d’acide urique chez l’Homme est associé dans la fiche à :`,
    choices: [
      `Des crises de goutte.`,
      `Des lithiases uriques.`,
      `Une difficulté d’élimination de l’acide urique.`,
      `Une production d’allantoïne par l’urate oxydase humaine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie l’absence d’urate oxydase à l’accumulation d’acide urique et à ces manifestations.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Acide urique et pathologies peroxysomales](/images/training/ue14/biologie-cellulaire/peroxysomes/acide-urique-pathologies-peroxysomales.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Chez certains animaux, l’urate oxydase produit de l’allantoïne.`,
      `Chez l’Homme, l’absence d’urate oxydase favorise l’excès d’acide urique.`,
      `Les maladies peroxysomales peuvent provoquer une accumulation d’acides gras à très longue chaîne.`,
      `L’allantoïne est décrite comme insoluble et impossible à éliminer.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure oppose la voie animale de l’allantoïne à la situation humaine et rappelle l’accumulation lipidique des maladies peroxysomales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les maladies héréditaires du métabolisme peroxysomal :`,
    choices: [
      `Sont nombreuses.`,
      `Peuvent rendre les peroxysomes anormaux.`,
      `Peuvent s’accompagner d’une absence de peroxysomes.`,
      `Sont toujours acquises et jamais génétiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche décrit des maladies héréditaires où les organites sont anormaux ou absents.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La transmission des maladies peroxysomales peut être :`,
    choices: [
      `Autosomique récessive.`,
      `Liée au chromosome X.`,
      `Toujours mitochondriale.`,
      `Variable selon la maladie.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche cite des transmissions autosomiques récessives ou liées à l’X.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une mutation touchant une enzyme peroxysomale peut entraîner :`,
    choices: [
      `L’accumulation de métabolites non dégradés.`,
      `Une accumulation particulière de lipides.`,
      `Une augmentation des acides gras à très longue chaîne.`,
      `Une disparition obligatoire de tous les métabolites.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le défaut de dégradation conduit à l’accumulation de substrats, notamment les très longues chaînes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les leucodystrophies citées dans ce chapitre comprennent :`,
    choices: [
      `L’adrénoleucodystrophie liée à l’X.`,
      `Le syndrome de Zellweger.`,
      `Des atteintes de la substance blanche.`,
      `La goutte comme unique leucodystrophie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie les deux maladies peroxysomales à des lésions ou une démyélinisation de la substance blanche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’adrénoleucodystrophie liée à l’X est décrite comme :`,
    choices: [
      `Une maladie neurodégénérative sévère.`,
      `Une démyélinisation progressive centrale et périphérique.`,
      `Une maladie pouvant comporter une insuffisance surrénale.`,
      `Une affection limitée à une crise de goutte.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’adrénoleucodystrophie associe atteinte neurologique démyélinisante et insuffisance surrénale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le syndrome de Zellweger est décrit comme :`,
    choices: [
      `Un syndrome hépato-cérébro-rénal.`,
      `Une polymalformation.`,
      `Une affection pouvant associer épilepsie, hypotonie et dysfonctionnement rénal.`,
      `Une maladie limitée à une hyperglycémie isolée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche cite des anomalies faciales, une épilepsie, une hypotonie, une atteinte rénale et des lésions de substance blanche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparer adrénoleucodystrophie liée à l’X et syndrome de Zellweger permet de retenir que :`,
    choices: [
      `Les deux sont liées au dysfonctionnement peroxysomal.`,
      `Les deux peuvent comporter des atteintes neurologiques.`,
      `Leur tableau clinique n’est pas identique.`,
      `Les deux sont des formes de goutte.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces maladies partagent une origine peroxysomale mais diffèrent par leur transmission et leurs manifestations.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un patient présente une accumulation d’acides gras à très longue chaîne. Cette observation est cohérente avec :`,
    choices: [
      `Un défaut de β-oxydation peroxysomale.`,
      `Une maladie héréditaire du métabolisme peroxysomal.`,
      `Une accumulation de métabolites non dégradés.`,
      `Une activité excessive de l’urate oxydase humaine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les très longues chaînes constituent un marqueur fonctionnel des déficits peroxysomaux décrits.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une atteinte démyélinisante progressive associée à une insuffisance surrénale évoque, dans la fiche :`,
    choices: [
      `L’adrénoleucodystrophie liée à l’X.`,
      `Une leucodystrophie.`,
      `Une maladie peroxysomale.`,
      `Le syndrome de goutte isolée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ce tableau correspond à l’exemple d’adrénoleucodystrophie liée à l’X.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un nourrisson présentant dysmorphie faciale, épilepsie, hypotonie et atteinte rénale est compatible, selon la fiche, avec :`,
    choices: [
      `Le syndrome de Zellweger.`,
      `Un syndrome hépato-cérébro-rénal.`,
      `Une maladie peroxysomale avec polymalformations.`,
      `Une simple accumulation d’acide urique sans autre atteinte.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ce regroupement de manifestations correspond au syndrome de Zellweger présenté dans la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La goutte est reliée dans ce chapitre à :`,
    choices: [
      `L’excès d’acide urique.`,
      `L’absence d’urate oxydase chez l’Homme.`,
      `Une élimination insuffisante de l’acide urique.`,
      `Une absence complète de catalase dans tous les peroxysomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie de l’urate oxydase explique la différence entre animaux et Homme et le risque d’excès d’acide urique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Chez un animal possédant une urate oxydase fonctionnelle :`,
    choices: [
      `L’acide urique est converti en allantoïne.`,
      `L’allantoïne est soluble dans les urines.`,
      `Le peroxysome participe au catabolisme purique.`,
      `L’absence d’enzyme provoque nécessairement une synthèse de catalase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette voie peroxysomale facilite l’élimination de l’acide urique sous forme d’allantoïne.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un traitement par fibrates pourrait être associé, selon la fiche, à :`,
    choices: [
      `Une stimulation de la synthèse de peroxysomes.`,
      `Une diminution des acides gras à très longue chaîne.`,
      `Une augmentation de la capacité de β-oxydation peroxysomale.`,
      `Une suppression définitive des mitochondries.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La prolifération peroxysomale augmente la prise en charge des très longues chaînes sans supprimer les mitochondries.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À partir des deux figures suivantes :

![β-oxydation](/images/training/ue14/biologie-cellulaire/peroxysomes/beta-oxydation-cooperation-mitochondrie.png)

![Acide urique et pathologies](/images/training/ue14/biologie-cellulaire/peroxysomes/acide-urique-pathologies-peroxysomales.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Le peroxysome intervient dans plusieurs voies métaboliques distinctes.`,
      `Un défaut peroxysomal peut provoquer une accumulation lipidique.`,
      `Le peroxysome coopère avec la mitochondrie pour les acides gras.`,
      `Toutes les fonctions peroxysomales sont limitées au catabolisme de l’acide urique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les figures illustrent la diversité métabolique du peroxysome et les conséquences de ses déficits.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les modes de transmission cités expliquent que :`,
    choices: [
      `Certaines maladies touchent les deux sexes selon un mode autosomique récessif.`,
      `Certaines peuvent être liées au chromosome X.`,
      `La transmission dépend du gène concerné.`,
      `Toutes les maladies sont nécessairement dominantes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche cite deux grands modes de transmission, sans généraliser un mode dominant.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une maladie peroxysomale peut associer :`,
    choices: [
      `Un défaut enzymatique.`,
      `Une accumulation de métabolites.`,
      `Des anomalies ou une absence de peroxysomes.`,
      `Une protection systématique contre les leucodystrophies.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La perte de fonction peroxysomale favorise au contraire des atteintes neurologiques et métaboliques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte sur les rôles cliniques du peroxysome ?`,
    choices: [
      `Il participe au métabolisme des très longues chaînes.`,
      `Il intervient dans le catabolisme de l’acide urique chez les animaux possédant l’urate oxydase.`,
      `Ses déficits peuvent provoquer des leucodystrophies.`,
      `Ses maladies n’entraînent jamais d’accumulation de métabolites.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les pathologies peroxysomales illustrent les conséquences de la perte de fonctions métaboliques essentielles.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `beta-oxydation-cooperation-mitochondrie`,
    title: `β-oxydation et coopération mitochondriale`,
    description: `Raccourcissement des très longues chaînes, acétyl-CoA et fibrates.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `acide-urique-maladies-peroxysomales`,
    title: `Acide urique et maladies peroxysomales`,
    description: `Urate oxydase, goutte, transmission et accumulation de métabolites.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `pathologies-et-raisonnement-clinique`,
    title: `Pathologies et raisonnement clinique`,
    description: `Adrénoleucodystrophie liée à l’X, syndrome de Zellweger et applications.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
