/** UE14 – Biologie cellulaire – Chapitre 2 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La communication cellulaire :` ,
    choices: [
      `Est nécessaire chez les pluricellulaires.`,
      `Coordonne l’activité des tissus.`,
      `Implique des récepteurs.`,
      `Devient inutile après différenciation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cellules différenciées doivent toujours communiquer.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les informations reçues par une cellule peuvent être :` ,
    choices: [
      `Des éléments fixes de l’environnement.`,
      `Des molécules libres hydrosolubles ou liposolubles.`,
      `Des radicaux libres gazeux.`,
      `Uniquement des protéines de la même cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les signaux peuvent être fixes ou diffusibles.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La communication juxtacrine :` ,
    choices: [
      `Nécessite un contact direct.`,
      `Peut se faire entre deux cellules.`,
      `Peut mettre en jeu la MEC.`,
      `Correspond au transport d’une hormone par le sang.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le passage par le sang correspond à l’endocrinie.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La diapédèse :` ,
    choices: [
      `Implique leucocyte et endothélium.`,
      `Répond à des signaux inflammatoires.`,
      `Permet le passage du leucocyte à travers la paroi vasculaire.`,
      `Résulte d’une simple diffusion à travers une bicouche nue.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Il s’agit d’un processus d’adhérence et de communication, pas d’une diffusion simple.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un épithélium, les cellules sont en contact :` ,
    choices: [
      `Entre elles.`,
      `Avec la membrane basale.`,
      `Uniquement par des canaux ioniques.`,
      `Indirectement avec d’autres cellules via la MEC.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La MEC constitue un support d’interactions important.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de l’occludine :` ,
    choices: [
      `C’est un élément fixe d’adhérence.`,
      `Deux occludines forment une liaison homophile.`,
      `Elle participe aux jonctions serrées.`,
      `C’est une intégrine alpha/beta.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’occludine n’est pas une intégrine.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les intégrines :` ,
    choices: [
      `Sont formées de sous-unités alpha et beta.`,
      `Assurent l’adhérence à la MEC.`,
      `Interagissent de manière hétérophile avec la MEC.`,
      `Se reconnaissent uniquement entre elles pour former les jonctions serrées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les jonctions serrées relèvent surtout des occludines.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les grandes classes de molécules de MEC :` ,
    choices: [
      `Glycoprotéines de structure.`,
      `Collagènes.`,
      `Élastine.`,
      `Protéoglycanes.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Ces quatre grandes familles sont présentées dans le cours.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des collagènes I et IV :` ,
    choices: [
      `Le collagène I est fibrillaire.`,
      `Le collagène IV est majeur dans les lames basales.`,
      `Le collagène IV forme un réseau plan.`,
      `Le collagène I est le principal composant des synapses chimiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le collagène I n’est pas décrit comme composant majeur des synapses.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les glycoprotéines de structure citées dans la MEC sont :` ,
    choices: [
      `La fibronectine.`,
      `La laminine.`,
      `La spectrine.`,
      `Le dimère de bande 3.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La spectrine et la bande 3 concernent l’hématie.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure :

![Communication](/images/training/ue14/biologie-cellulaire/membrane-plasmique/communication-cellulaire-modes.png)

Quelles propositions sont correctes ?` ,
    choices: [
      `La juxtacrinie implique un contact direct.`,
      `L’autocrinie agit sur la cellule émettrice.`,
      `L’endocrinie passe par le sang.`,
      `La synapse chimique agit à longue distance via du collagène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La synapse chimique repose sur un neurotransmetteur libéré localement.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les récepteurs couplés aux protéines G (RCPG) :` ,
    choices: [
      `Lient un ligand extracellulaire.`,
      `Activent une protéine G trimérique.`,
      `Peuvent recruter une adénylate cyclase.`,
      `Sont des récepteurs nucléaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les RCPG sont des récepteurs membranaires.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La transduction du signal par un RCPG fait intervenir :` ,
    choices: [
      `Un récepteur membranaire.`,
      `Une protéine de transduction.`,
      `Une protéine effectrice.`,
      `Uniquement une diffusion simple à travers la bicouche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La signalisation met en jeu une cascade organisée.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les récepteurs enzymes comportent :` ,
    choices: [
      `Un domaine extracellulaire de reconnaissance.`,
      `Un domaine transmembranaire.`,
      `Un domaine enzymatique intracellulaire.`,
      `Une impossibilité de dimériser.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La dimérisation est fréquente lors de l’activation.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les exemples donnés pour les récepteurs enzymes :` ,
    choices: [
      `Récepteurs aux facteurs de croissance comme EGF.`,
      `Récepteur à l’insuline.`,
      `PDGF ou NGF.`,
      `Aquaporines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les aquaporines sont des canaux hydriques.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La communication autocrine :` ,
    choices: [
      `Correspond à une autostimulation.`,
      `Peut impliquer cytokines ou facteurs de croissance.`,
      `Fait de la cellule émettrice aussi la cellule cible.`,
      `Nécessite toujours le transport par le sang.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le passage par le sang caractérise l’endocrinie.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La communication paracrine :` ,
    choices: [
      `Agit entre cellules proches.`,
      `Fait intervenir une diffusion locale.`,
      `Peut intervenir dans l’inflammation ou la cicatrisation.`,
      `Correspond à un trajet sanguin généralisé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La paracrinie est locale, non sanguine.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La communication endocrine :` ,
    choices: [
      `Utilise des hormones.`,
      `Passe par le sang.`,
      `Peut agir sur des cellules éloignées.`,
      `Correspond au passage d’un leucocyte entre deux cellules endothéliales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La diapédèse est un exemple de juxtacrinie.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La communication synaptique chimique :` ,
    choices: [
      `Utilise un neurotransmetteur.`,
      `Agit au voisinage immédiat.`,
      `Est illustrée par la plaque motrice et l’acétylcholine.`,
      `Repose sur une diffusion de signal dans tout l’organisme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le signal reste très local, au niveau de la synapse.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À l’échelle d’un tissu normal :` ,
    choices: [
      `Les cellules reçoivent plusieurs signaux.`,
      `Leur intégration participe à l’homéostasie.`,
      `Les signaux peuvent orienter survie, division, différenciation ou apoptose.`,
      `Toutes les communications ont le même mécanisme moléculaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les mécanismes sont au contraire variés.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une liaison entre deux occludines portées par deux cellules est :` ,
    choices: [
      `Homophile.`,
      `Associée aux jonctions serrées.`,
      `Importante pour la séparation apical/baso-latéral.`,
      `Une interaction intégrine-collagène IV.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une interaction intégrine-collagène IV est hétérophile et cellule-MEC.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une intégrine se liant à la fibronectine implique :` ,
    choices: [
      `Une communication juxtacrine cellule-MEC.`,
      `Une interaction hétérophile.`,
      `Un rôle d’adhérence.`,
      `Une hormone endocrine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fibronectine est une glycoprotéine de structure de MEC.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cytokine diffusant sur quelques micromètres vers une cellule voisine correspond à :` ,
    choices: [
      `Une communication paracrine.`,
      `Une action locale.`,
      `Un mécanisme compatible avec l’inflammation.`,
      `Une synapse chimique obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La paracrinie agit localement sans nécessiter un neurone.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’insuline illustre une communication endocrine car :` ,
    choices: [
      `Elle est sécrétée par les cellules bêta.`,
      `Elle est libérée dans le sang.`,
      `Elle agit sur des cellules éloignées comme musculaires ou hépatiques.`,
      `Elle exige un contact direct entre les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’endocrinie n’exige pas de contact cellulaire direct.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le collagène IV des lames basales :` ,
    choices: [
      `Participe à une MEC spécialisée.`,
      `Peut s’associer à laminine et fibronectine.`,
      `Est le principal composant du cytosol des entérocytes.`,
      `Contribue à l’organisation de la membrane basale.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le collagène IV appartient à la MEC, pas au cytosol.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On peut associer correctement :` ,
    choices: [
      `Fibronectine — glycoprotéine de structure.`,
      `Laminine — glycoprotéine trimérique.`,
      `Élastine — réseau tridimensionnel lâche donnant l’élasticité.`,
      `Protéoglycanes — aquaporines du plasma.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les protéoglycanes n’ont rien à voir avec les aquaporines.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À partir de la figure sur les modes de communication :` ,
    choices: [
      `Autocrine = signal sur la même cellule.`,
      `Paracrine = action sur cellule voisine.`,
      `Synaptique chimique = neurotransmetteur dans une fente synaptique.`,
      `Juxtacrine = passage obligatoire par le sang.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le passage par le sang caractérise l’endocrinie.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les couples situation-type :` ,
    choices: [
      `Plaque motrice — synaptique chimique.`,
      `Facteur agissant sur sa propre cellule — autocrine.`,
      `Hormone circulante — endocrine.`,
      `Leucocyte traversant l’endothélium — purement endocrine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La diapédèse relève de la communication juxtacrine.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’activation d’un récepteur à l’EGF peut initier :` ,
    choices: [
      `Une cascade de signalisation intracellulaire.`,
      `Une réponse liée à la multiplication cellulaire.`,
      `Un mécanisme impliquant un récepteur enzyme.`,
      `Une diffusion directe simple vers le noyau sans récepteur.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’EGF agit via un récepteur enzyme membranaire.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?` ,
    choices: [
      `La communication peut reposer sur des contacts fixes ou sur des molécules diffusibles.`,
      `Elle met en jeu des récepteurs variés.`,
      `Elle participe à l’homéostasie tissulaire.`,
      `Elle devient inutile dans les cancers.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Sa dérégulation intervient au contraire dans certaines pathologies.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: `adhesion-et-matrice-extracellulaire`,
    title: `Adhérence et matrice extracellulaire`,
    description: `Juxtacrinie, occludines, intégrines et MEC.`,
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: `recepteurs-et-modes-de-communication`,
    title: `Récepteurs et modes de communication`,
    description: `RCPG, récepteurs enzymes et grands modes de communication.`,
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 9,
    slug: `integration-des-signaux-cellulaires`,
    title: `Intégration des signaux cellulaires`,
    description: `Applications et comparaison des différentes voies de signalisation.`,
    stage: 'MASTER',
    sectionOrder: 3,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];
