/**
 * UE14 – Biologie cellulaire – Chapitre 1
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la culture cellulaire :`,
    choices: [
      `Elle permet le maintien de cellules dans un milieu nutritif artificiel.`,
      `Elle peut permettre leur multiplication hors de leur environnement naturel.`,
      `Elle impose que les cellules restent dans l'organisme entier.`,
      `Elle facilite l'étude séparée de processus cellulaires.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La culture cellulaire maintient et multiplie des cellules isolées dans un milieu artificiel adapté, ce qui permet d'étudier des processus de façon contrôlée.`,
    choiceExplanations: [
      `Le maintien fait partie de sa définition.`,
      `La multiplication in vitro est explicitement citée.`,
      `Les cellules sont isolées de leur environnement naturel.`,
      `C'est l'un des intérêts généraux de l'approche in vitro.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant les cellules adhérentes cultivées :`,
    choices: [
      `Certaines ont besoin d'un support pour se développer.`,
      `Le verre peut constituer un support de culture.`,
      `Le polycarbonate peut constituer un support de culture.`,
      `Toute cellule cultivée doit flotter librement sans contact avec aucun support.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cellules adhérentes peuvent être cultivées sur des surfaces adaptées, par exemple en verre ou en polycarbonate.`,
    choiceExplanations: [
      `La fiche cite notamment des supports en verre ou polycarbonate.`,
      `Il est explicitement mentionné.`,
      `Il est également cité.`,
      `Les cellules adhérentes se développent sur un support.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Quel instrument est cité pour observer les cellules en culture ?`,
    choices: [
      `Un microscope optique inversé.`,
      `Un télescope optique.`,
      `Un spectromètre de masse uniquement.`,
      `Un microscope électronique obligatoire pour toute observation courante.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Les cellules cultivées dans des boîtes ou flacons sont observées au microscope optique inversé.`,
    choiceExplanations: [
      `C'est l'instrument indiqué dans la fiche.`,
      `Il n'est pas utilisé pour observer une culture cellulaire.`,
      `Ce n'est pas l'instrument d'observation mentionné.`,
      `La fiche indique le microscope optique inversé.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans les conditions de culture indiquées :`,
    choices: [
      `La température est de 37 °C.`,
      `La teneur en CO2 est de 5 %.`,
      `L'humidité est de l'ordre de 80 à 85 %.`,
      `Les cellules sont maintenues à -80 °C pendant leur utilisation courante.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'incubateur reproduit des conditions favorables : 37 °C, 5 % de CO2 et environ 80 à 85 % d'humidité selon la fiche.`,
    choiceExplanations: [
      `C'est la température donnée.`,
      `La fiche indique 5 % de CO2.`,
      `Cette plage est explicitement citée.`,
      `La culture active se déroule dans l'incubateur à 37 °C.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du poste de sécurité microbiologique (PSM) :`,
    choices: [
      `Il est utilisé lors de la manipulation des cellules.`,
      `Son flux d'air contribue à protéger le manipulateur de contaminations éventuelles.`,
      `Il remplace l'incubateur pour la croissance prolongée des cellules.`,
      `Il appartient au dispositif de travail en culture cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le PSM est un poste de manipulation utilisant un flux d'air protecteur ; il ne se confond pas avec l'incubateur.`,
    choiceExplanations: [
      `La fiche place les manipulations sous PSM.`,
      `C'est le rôle indiqué dans le document.`,
      `Le PSM sert à manipuler, l'incubateur à maintenir les conditions de culture.`,
      `Il fait partie de l'environnement technique décrit.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Selon le cours, des cellules non utilisées peuvent être conservées en cryothèque :`,
    choices: [
      `Par congélation.`,
      `Sans altération attendue de leur potentiel de multiplication dans le cadre présenté.`,
      `Sans altération attendue de leur patrimoine génétique dans le cadre présenté.`,
      `Uniquement après destruction de toutes les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cryoconservation permet de stocker des cellules pour une utilisation ultérieure en préservant, selon la fiche, leur potentiel de multiplication et leur patrimoine génétique.`,
    choiceExplanations: [
      `La cryothèque repose sur la congélation.`,
      `La fiche l'indique explicitement.`,
      `Ce point est également mentionné.`,
      `L'objectif est précisément de conserver des cellules viables.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les avantages de la culture cellulaire :`,
    choices: [
      `Fournir une source continue de cellules utilisables.`,
      `Fournir une population plus homogène que de nombreux prélèvements in vivo.`,
      `Faciliter différentes manipulations expérimentales.`,
      `Reproduire automatiquement et parfaitement tout l'organisme humain.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La culture fournit une source continue et homogène, plus facilement manipulable que des cellules étudiées directement in vivo.`,
    choiceExplanations: [
      `Cet avantage est cité.`,
      `La fiche parle d'une source continue et homogène.`,
      `La facilité de manipulation est mise en avant.`,
      `Un modèle in vitro reste une simplification.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des cellules libres ou circulantes :`,
    choices: [
      `Elles peuvent être obtenues par prélèvement sanguin.`,
      `Une centrifugation peut permettre de les récupérer.`,
      `Elles doivent obligatoirement être disséquées à partir d'un tissu solide.`,
      `Elles représentent l'une des deux grandes catégories de cellules de mammifères distinguées dans cette partie.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les cellules circulantes sont notamment récupérées à partir du sang, souvent après centrifugation.`,
    choiceExplanations: [
      `C'est la méthode présentée.`,
      `Cette étape est explicitement mentionnée.`,
      `La dissection concerne les cellules organisées en tissus.`,
      `L'autre catégorie correspond aux cellules en cohésion dans des tissus.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Pour isoler des cellules organisées en tissu :`,
    choices: [
      `Une dissection peut être utilisée.`,
      `Une méthode enzymatique peut être utilisée.`,
      `Des enzymes protéolytiques peuvent participer à la dissociation.`,
      `Une simple centrifugation sanguine est nécessairement la seule méthode possible.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les tissus peuvent être dissociés mécaniquement par dissection ou enzymatiquement, notamment grâce à des enzymes protéolytiques.`,
    choiceExplanations: [
      `C'est l'une des méthodes citées.`,
      `La fiche mentionne une dissociation enzymatique.`,
      `Elles sont données en exemple.`,
      `Elle concerne surtout la récupération de cellules circulantes.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos d'une culture primaire :`,
    choices: [
      `Elle est obtenue après mise en culture de cellules issues d'une dissociation ou de cellules circulantes.`,
      `Elle peut être d'origine humaine.`,
      `Elle peut provenir d'un autre mammifère.`,
      `Elle désigne nécessairement une culture ayant subi vingt passages.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La culture primaire correspond à la première mise en culture des cellules isolées avant le premier repiquage.`,
    choiceExplanations: [
      `C'est la définition fonctionnelle donnée.`,
      `La fiche le précise.`,
      `Cette possibilité est également indiquée.`,
      `Une culture primaire précède le premier passage.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lorsque des cellules adhérentes atteignent la confluence :`,
    choices: [
      `Elles se touchent.`,
      `Un passage peut devenir nécessaire.`,
      `Leur nombre a augmenté par prolifération avant cette étape.`,
      `Elles deviennent instantanément des cellules tumorales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La confluence correspond à l'occupation du support par des cellules qui se touchent ; elle conduit à effectuer un passage pour éviter leur mort.`,
    choiceExplanations: [
      `La confluence est définie ainsi dans la fiche.`,
      `Il faut les séparer et les repiquer pour poursuivre la culture.`,
      `La confluence résulte de la multiplication sur le support.`,
      `La confluence n'est pas une transformation tumorale.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le passage cellulaire consiste à :`,
    choices: [
      `Décoller les cellules de leur support.`,
      `Repiquer une partie des cellules dans une autre boîte.`,
      `Utiliser un traitement enzymatique pour détacher les cellules adhérentes.`,
      `Fixer définitivement les cellules pour empêcher toute prolifération.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le passage cellulaire associe décollement et repiquage dans un nouveau récipient avec un milieu adapté.`,
    choiceExplanations: [
      `C'est la première étape de la définition.`,
      `C'est la seconde étape.`,
      `La fiche le précise.`,
      `Le but est au contraire de relancer leur croissance.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Après le premier passage d'une culture primaire, on obtient :`,
    choices: [
      `Une culture secondaire.`,
      `Un explant initial.`,
      `Une cellule nécessairement morte.`,
      `Une culture obligatoirement immortelle.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le premier passage transforme la culture primaire en culture secondaire.`,
    choiceExplanations: [
      `C'est le terme employé dans le cours.`,
      `L'explant est un fragment de tissu déposé directement.`,
      `Le passage vise à poursuivre la prolifération.`,
      `Une culture secondaire normale reste de durée de vie limitée.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des passages successifs :`,
    choices: [
      `Les cellules prolifèrent à nouveau dans chaque nouveau récipient.`,
      `Elles peuvent atteindre à nouveau la confluence.`,
      `Un nouveau décollement et un nouveau repiquage peuvent alors être réalisés.`,
      `Ils garantissent une durée de vie infinie à toutes les cellules normales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les passages successifs répètent le cycle décollement, repiquage, prolifération et confluence.`,
    choiceExplanations: [
      `Chaque passage relance la culture.`,
      `Le cycle prolifération-confluence se répète.`,
      `C'est la répétition du passage.`,
      `Les cellules normales meurent après plusieurs passages.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour des cellules provenant de tissus normaux :`,
    choices: [
      `La durée de vie de la culture est relativement courte.`,
      `Elles finissent par mourir après plusieurs passages.`,
      `Leur capacité de division n'est pas illimitée dans ce modèle.`,
      `Elles sont forcément tumorales dès le premier passage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cultures normales ont une capacité de prolifération limitée et une durée de vie de quelques semaines selon la fiche.`,
    choiceExplanations: [
      `La fiche parle de quelques semaines.`,
      `C'est le devenir décrit.`,
      `Elles ne forment pas spontanément une lignée immortelle.`,
      `Une cellule normale reste distincte d'une cellule tumorale.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des lignées cellulaires :`,
    choices: [
      `Elles peuvent provenir de tissus tumoraux.`,
      `Elles ont une capacité de division considérée comme illimitée.`,
      `Une cellule normale transformée par un oncogène peut aussi être à leur origine.`,
      `Elles meurent nécessairement après le tout premier passage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une lignée cellulaire est dite immortelle parce qu'elle peut se diviser sans la limite observée pour les cultures normales, notamment lorsqu'elle dérive d'une tumeur ou d'une transformation oncogénique.`,
    choiceExplanations: [
      `C'est l'origine principale présentée.`,
      `Elles sont dites immortelles.`,
      `Cette possibilité est donnée en remarque.`,
      `Ce comportement correspond à l'opposé d'une lignée immortelle.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La figure suivante résume les passages cellulaires.

![Culture cellulaire : de la culture primaire à la lignée cellulaire](/images/training/ue14/biologie-cellulaire/organisation-methodes-etude-cellule/culture-primaire-lignee-cellulaire.png)

À propos de cette figure :`,
    choices: [
      `La confluence précède le passage cellulaire.`,
      `Le passage comporte un décollement puis un transfert.`,
      `Les cellules normales et tumorales ont nécessairement le même devenir après de nombreux passages.`,
      `La culture secondaire apparaît après un passage.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le schéma met en évidence la succession culture primaire, prolifération, confluence, passage, culture secondaire et passages successifs, avec des devenirs différents selon l'origine cellulaire.`,
    choiceExplanations: [
      `Le schéma suit cet ordre.`,
      `C'est le mécanisme illustré.`,
      `Le schéma distingue sénescence/mort et lignée immortelle.`,
      `C'est l'étape 6 du schéma.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Associer correctement le matériel à sa fonction en culture :`,
    choices: [
      `Incubateur — maintien des conditions de température, CO2 et humidité.`,
      `PSM — manipulation sous flux d'air protecteur.`,
      `Microscope optique inversé — observation des cellules en culture.`,
      `Cryothèque — réalisation du passage cellulaire à 37 °C.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Chaque équipement répond à une fonction différente : cultiver, manipuler, observer ou conserver.`,
    choiceExplanations: [
      `C'est la fonction de l'incubateur.`,
      `C'est le rôle décrit.`,
      `Il est utilisé pour visualiser les cellules sur leur support.`,
      `La cryothèque sert à conserver les cellules congelées.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les tissus utilisés pour établir une culture peuvent :`,
    choices: [
      `Provenir d'une exérèse chirurgicale.`,
      `Être normaux.`,
      `Être tumoraux.`,
      `Ne jamais être dissociés avant la mise en culture.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Des tissus normaux ou tumoraux provenant notamment d'une exérèse peuvent être dissociés pour établir une culture primaire.`,
    choiceExplanations: [
      `C'est l'origine générale indiquée.`,
      `La fiche envisage des tissus normaux.`,
      `Elle envisage aussi des tissus tumoraux.`,
      `La dissociation est une voie majeure d'obtention de cellules.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des relations entre culture primaire et lignée cellulaire :`,
    choices: [
      `Une culture primaire peut provenir de cellules tumorales isolées.`,
      `Une lignée peut provenir de cellules tumorales isolées.`,
      `Une lignée peut provenir de cellules normales transformées par un oncogène.`,
      `Une culture primaire ne peut jamais provenir de cellules normales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'origine normale ou tumorale n'empêche pas d'établir une culture primaire ; l'immortalisation caractérise ensuite la lignée.`,
    choiceExplanations: [
      `Le cours l'admet explicitement dans son QCM.`,
      `C'est une origine classique donnée.`,
      `Cette possibilité figure dans la remarque.`,
      `Elle peut provenir de tissus normaux.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `Une culture adhérente devient confluente. Quelle conduite correspond au cours pour poursuivre la culture ?`,
    choices: [
      `Décoller les cellules puis en repiquer une partie dans un nouveau récipient.`,
      `Ajouter uniquement de l'eau distillée et ne rien changer.`,
      `Fixer les cellules avant de les remettre en culture.`,
      `Les laisser indéfiniment sans intervention malgré la confluence.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La poursuite de la culture impose un passage : traitement de décollement, prélèvement d'une fraction et repiquage dans un milieu frais.`,
    choiceExplanations: [
      `C'est la définition du passage cellulaire.`,
      `Cela ne constitue pas un passage et ne fournit pas un milieu adapté.`,
      `La fixation tue ou immobilise les cellules et empêche la poursuite de la culture.`,
      `Le cours indique qu'elles meurent si elles ne sont pas séparées.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une manipulation est effectuée hors PSM puis les boîtes sont placées dans un incubateur mal réglé. À partir du cours :`,
    choices: [
      `L'absence de PSM augmente le risque de contamination pendant la manipulation.`,
      `Un mauvais réglage de température peut compromettre les conditions de culture.`,
      `Le microscope inversé peut être utilisé pour observer l'état des cellules.`,
      `La cryothèque corrige automatiquement toutes les erreurs de manipulation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La qualité d'une culture dépend à la fois de l'asepsie des manipulations et du maintien de conditions physicochimiques adaptées.`,
    choiceExplanations: [
      `Le flux d'air du PSM est destiné à protéger lors de cette étape.`,
      `La température de référence est 37 °C.`,
      `Il permet l'observation des cultures.`,
      `La cryoconservation n'annule pas une contamination ou un mauvais protocole.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une culture augmente en densité jusqu'à ce que les cellules recouvrent le support et se touchent. Cette situation :`,
    choices: [
      `Correspond à l'atteinte de la confluence.`,
      `Peut nécessiter un passage.`,
      `Survient après une phase de prolifération.`,
      `Prouve à elle seule que les cellules sont immortelles.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La confluence est un état de densité, non une preuve d'immortalité. Le devenir à long terme dépend de la nature des cellules.`,
    choiceExplanations: [
      `C'est la définition du phénomène.`,
      `Le passage évite l'arrêt ou la mort liés au surpeuplement.`,
      `La densité augmente par division cellulaire.`,
      `Des cellules normales atteignent également la confluence.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Après de nombreux passages, on compare deux cultures A et B. A cesse progressivement de proliférer ; B continue à se diviser. Selon le cours :`,
    choices: [
      `A est compatible avec une culture de cellules normales.`,
      `B est compatible avec une lignée tumorale immortelle.`,
      `La différence peut être liée à une transformation oncogénique.`,
      `A et B ont nécessairement exactement la même origine et le même statut.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La persistance de la prolifération au fil des passages distingue une lignée immortelle d'une culture normale à durée de vie limitée.`,
    choiceExplanations: [
      `Les cellules normales ont une durée de vie limitée.`,
      `La prolifération illimitée caractérise une lignée.`,
      `Une telle transformation peut immortaliser une cellule normale.`,
      `Leur comportement suggère au contraire des statuts différents.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `Une culture primaire subit un premier passage, puis deux passages supplémentaires. Comment qualifier la culture juste après le premier passage ?`,
    choices: [
      `Culture secondaire.`,
      `Culture primaire inchangée.`,
      `Explant obligatoire.`,
      `Culture nécessairement immortelle.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le premier repiquage produit une culture secondaire ; les repiquages suivants sont des passages successifs.`,
    choiceExplanations: [
      `Le terme s'applique dès le premier passage.`,
      `Le premier passage marque le passage à la culture secondaire.`,
      `Une culture secondaire peut provenir de cellules dissociées.`,
      `Le nombre de passages ne suffit pas à définir l'immortalité.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour obtenir des cellules circulantes et des cellules issues d'un tissu solide :`,
    choices: [
      `Un prélèvement sanguin suivi d'une centrifugation convient aux cellules circulantes.`,
      `Une dissection peut contribuer à isoler des cellules d'un tissu.`,
      `Une dissociation par enzymes protéolytiques peut être utilisée pour un tissu.`,
      `La même étape unique et obligatoire suffit toujours quelle que soit la source.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'origine du matériel biologique détermine la méthode d'isolement : centrifugation du sang ou dissociation tissulaire.`,
    choiceExplanations: [
      `C'est la stratégie donnée.`,
      `Elle est mentionnée pour les tissus.`,
      `C'est l'autre méthode présentée.`,
      `La méthode dépend du type de prélèvement.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un protocole annonce : « Les cellules sont observées au microscope inversé, manipulées sous PSM et incubées à 37 °C avec 5 % de CO2 ».`,
    choices: [
      `L'observation au microscope inversé est cohérente avec la fiche.`,
      `La manipulation sous PSM est cohérente.`,
      `Les paramètres d'incubation cités sont cohérents.`,
      `Le protocole prouve que toutes les cellules utilisées sont tumorales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les paramètres techniques sont conformes au cours, mais ils ne renseignent pas à eux seuls sur le statut normal ou tumoral des cellules.`,
    choiceExplanations: [
      `C'est l'instrument indiqué.`,
      `Elle limite les contaminations.`,
      `Ils reprennent les conditions de référence.`,
      `Le matériel et les conditions ne déterminent pas l'origine tumorale.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Des cellules sont sorties d'une cryothèque pour reprendre une culture :`,
    choices: [
      `La cryothèque avait pour fonction de les conserver congelées.`,
      `Le cours considère que leur potentiel de multiplication peut être préservé.`,
      `Leur patrimoine génétique est considéré comme préservé dans le cadre présenté.`,
      `Elles sont nécessairement fixées et donc incapables de reprendre toute activité.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cryoconservation permet de constituer un stock de cellules réutilisables, contrairement à la fixation qui sert à immobiliser les structures pour l'observation.`,
    choiceExplanations: [
      `C'est le principe de la conservation.`,
      `Ce point justifie leur remise en culture.`,
      `La fiche le précise.`,
      `Cryoconservation et fixation sont deux procédures différentes.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `En vous aidant de la figure :

![Culture cellulaire : de la culture primaire à la lignée cellulaire](/images/training/ue14/biologie-cellulaire/organisation-methodes-etude-cellule/culture-primaire-lignee-cellulaire.png)`,
    choices: [
      `Une cellule normale peut perdre progressivement sa capacité de prolifération.`,
      `Une lignée tumorale peut être maintenue par des passages successifs.`,
      `Le milieu de culture doit apporter des nutriments et facteurs adaptés.`,
      `Le passage consiste uniquement à observer la boîte sans déplacer les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure synthétise le cycle technique de culture et la différence de potentiel prolifératif entre cellules normales et lignées tumorales.`,
    choiceExplanations: [
      `La branche verte illustre ce devenir.`,
      `La branche violette illustre ce maintien.`,
      `La légende du schéma rappelle cette fonction.`,
      `Il comprend un décollement et un transfert.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos de la culture cellulaire :`,
    choices: [
      `Elle nécessite un environnement nutritif et des conditions contrôlées.`,
      `Elle peut commencer à partir de cellules circulantes ou de cellules dissociées d'un tissu.`,
      `Le passage permet de prolonger la culture après confluence.`,
      `Toutes les cultures deviennent spontanément immortelles.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une culture repose sur l'isolement, le maintien dans des conditions adaptées et, si nécessaire, des passages ; l'immortalité dépend du type cellulaire et non de la technique seule.`,
    choiceExplanations: [
      `Le milieu et l'incubateur sont indispensables.`,
      `Les deux sources sont présentées.`,
      `Il relance la prolifération dans un nouveau récipient.`,
      `Les cellules normales ont une durée de vie limitée.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `conditions-culture-cellulaire`,
    title: `Conditions de culture cellulaire`,
    description: `Milieu nutritif, support, incubateur, poste de sécurité microbiologique et cryoconservation.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `cultures-primaires-passages`,
    title: `Cultures primaires et passages`,
    description: `Origine des cellules, confluence, détachement, repiquage et culture secondaire.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `lignees-cellulaires-raisonnement-experimental`,
    title: `Lignées cellulaires et raisonnement expérimental`,
    description: `Passages successifs, durée de vie des cellules normales et immortalité des lignées tumorales.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
