import type { HealthTrainingAuthorQuestion } from './health-training-ue14.shared';

/**
 * UE14 – Chimie générale
 * Chapitre 3 – Orbitales moléculaires
 * Section B – Hybridation et géométrie des molécules simples
 */

export const UE14_CH3_HYBRIDATION_DISCOVER_V2_QUESTIONS: HealthTrainingAuthorQuestion[] = [
  {
    order: 21,
    difficulty: 'EASY',
    format: 'QRM',
    question: `À propos du modèle d'hybridation des orbitales atomiques, quelles propositions sont exactes ?`,
    choices: [
      { content: `Il combine des orbitales atomiques de valence d'un même atome.`, correct: true, explanation: `Vrai.` },
      { content: `Il produit des orbitales hybrides équivalentes orientées dans l'espace.`, correct: true, explanation: `Vrai.` },
      { content: `Le nombre d'orbitales hybrides obtenues est égal au nombre d'orbitales atomiques combinées.`, correct: true, explanation: `Le nombre d'orbitales est conservé.` },
      { content: `Il transforme les orbitales en trajectoires précises suivies par les électrons.`, correct: false, explanation: `Une orbitale reste une région de probabilité de présence.` },
    ],
    explanation: `L'hybridation est un modèle qui permet de relier les orbitales de valence à l'orientation et à l'équivalence des liaisons.`,
  },
  {
    order: 22,
    difficulty: 'EASY',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Sélectionnez exactement les deux caractéristiques d'une hybridation $\\mathrm{sp}$.`,
    choices: [
      { content: `Elle combine une orbitale $\\mathrm{s}$ et une orbitale $\\mathrm{p}$.`, correct: true, explanation: `Vrai.` },
      { content: `Elle produit deux orbitales hybrides orientées à $180^\\circ$.`, correct: true, explanation: `Vrai.` },
      { content: `Elle produit trois orbitales hybrides coplanaires à $120^\\circ$.`, correct: false, explanation: `Cela correspond à sp2.` },
      { content: `Elle ne laisse aucune orbitale $\\mathrm{p}$ non hybridée sur le carbone.`, correct: false, explanation: `Sur le carbone, deux orbitales p restent non hybridées après une hybridation sp.` },
    ],
    explanation: `Une hybridation sp donne deux orbitales hybrides opposées à 180° et laisse deux orbitales p non hybridées sur un carbone.`,
  },
  {
    order: 23,
    difficulty: 'EASY',
    format: 'QRM',
    question: `L'hydrure de béryllium $\\ce{BeH2}$ illustre l'hybridation $\\mathrm{sp}$. Quelles propositions sont exactes ?`,
    choices: [
      { content: `À l'état atomique fondamental, le béryllium a la configuration $1\\mathrm{s}^2\,2\\mathrm{s}^2$.`, correct: true, explanation: `Vrai pour Z=4.` },
      { content: `Le modèle moléculaire fait intervenir une redistribution permettant deux électrons célibataires.`, correct: true, explanation: `Le cours présente une redistribution 2s/2p avant hybridation.` },
      { content: `Deux orbitales $\\mathrm{sp}$ expliquent deux liaisons équivalentes et une géométrie linéaire.`, correct: true, explanation: `Les deux directions sont opposées.` },
      { content: `L'angle H–Be–H est voisin de $109{,}5^\\circ$.`, correct: false, explanation: `Il vaut 180° dans le modèle présenté.` },
    ],
    explanation: `$\\ce{BeH2}$ est l'exemple de référence d'une hybridation sp conduisant à une géométrie linéaire.`,
  },
  {
    order: 24,
    difficulty: 'EASY',
    format: 'QRU',
    question: `Quelle association décrit correctement l'hybridation $\\mathrm{sp}^2$ ?`,
    choices: [
      { content: `Une orbitale s + deux orbitales p → trois orbitales hybrides coplanaires à environ $120^\\circ$.`, correct: true, explanation: `C'est l'hybridation sp2.` },
      { content: `Une orbitale s + une orbitale p → deux orbitales à $180^\\circ$.`, correct: false, explanation: `Cela correspond à sp.` },
      { content: `Une orbitale s + trois orbitales p → quatre orbitales tétraédriques.`, correct: false, explanation: `Cela correspond à sp3.` },
      { content: `Deux orbitales s + deux orbitales p → quatre orbitales carrées planes.`, correct: false, explanation: `Ce n'est pas le modèle présenté dans ce chapitre.` },
    ],
    explanation: `L'hybridation sp2 produit trois orbitales équivalentes dans un même plan, séparées par des angles proches de 120°.`,
  },
  {
    order: 25,
    difficulty: 'EASY',
    format: 'QRU',
    question: `Quelle association décrit correctement l'hybridation $\\mathrm{sp}^3$ ?`,
    choices: [
      { content: `Une orbitale s + trois orbitales p → quatre orbitales hybrides orientées selon un tétraèdre.`, correct: true, explanation: `C'est l'hybridation sp3.` },
      { content: `Une orbitale s + deux orbitales p → trois orbitales coplanaires.`, correct: false, explanation: `C'est sp2.` },
      { content: `Une orbitale s + une orbitale p → deux orbitales opposées.`, correct: false, explanation: `C'est sp.` },
      { content: `Quatre orbitales p → quatre orbitales hybrides planes.`, correct: false, explanation: `Ce modèle n'est pas celui du cours.` },
    ],
    explanation: `Une hybridation sp3 donne quatre directions orbitalaires orientées vers les sommets d'un tétraèdre.`,
  },
  {
    order: 26,
    difficulty: 'EASY',
    format: 'QROC',
    question: `Dans le méthane $\\ce{CH4}$, combien d'orbitales hybrides $\\mathrm{sp}^3$ équivalentes sont portées par le carbone ?`,
    answer: { type: 'number', value: 4, tolerance: 0 },
    explanation: `Le carbone du méthane est décrit par quatre orbitales sp3 équivalentes, chacune engagée dans une liaison C–H.`,
  },
  {
    order: 27,
    difficulty: 'EASY',
    format: 'QRM',
    question: `À propos de l'ammoniac $\\ce{NH3}$ dans le modèle d'hybridation du cours, quelles propositions sont exactes ?`,
    choices: [
      { content: `L'azote est décrit par quatre orbitales $\\mathrm{sp}^3$.`, correct: true, explanation: `Vrai.` },
      { content: `Trois orbitales participent aux liaisons N–H.`, correct: true, explanation: `Il existe trois liaisons N–H.` },
      { content: `Une orbitale contient un doublet non liant.`, correct: true, explanation: `Ce doublet influence la géométrie.` },
      { content: `La molécule est parfaitement tétraédrique avec quatre hydrogènes.`, correct: false, explanation: `La géométrie moléculaire est pyramidale et ne comporte que trois hydrogènes.` },
    ],
    explanation: `L'organisation électronique autour de l'azote est sp3 ; la présence d'un doublet non liant conduit à une géométrie pyramidale.`,
  },
  {
    order: 28,
    difficulty: 'EASY',
    format: 'QROC',
    question: `Combien de doublets non liants sont portés par l'oxygène central dans la représentation $\\mathrm{sp}^3$ de l'eau ?`,
    answer: { type: 'number', value: 2, tolerance: 0 },
    explanation: `L'oxygène de l'eau forme deux liaisons O–H et conserve deux doublets non liants dans quatre orbitales sp3.`,
  },
  {
    order: 29,
    difficulty: 'EASY',
    format: 'QRM',
    question: `On compare $\\ce{CH4}$, $\\ce{NH3}$ et $\\ce{H2O}$. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Les trois atomes centraux sont décrits avec quatre directions électroniques compatibles avec $\\mathrm{sp}^3$.`, correct: true, explanation: `Vrai.` },
      { content: `Le nombre de doublets non liants augmente de $\\ce{CH4}$ à $\\ce{NH3}$ puis $\\ce{H2O}$.`, correct: true, explanation: `0, puis 1, puis 2.` },
      { content: `L'angle caractéristique diminue approximativement de $109{,}5^\\circ$ à $107{,}5^\\circ$ puis $104{,}5^\\circ$.`, correct: true, explanation: `C'est la tendance donnée dans la fiche.` },
      { content: `Les trois molécules possèdent exactement la même géométrie moléculaire visible.`, correct: false, explanation: `Tétraédrique, pyramidale puis coudée.` },
    ],
    explanation: `Les doublets non liants modifient la géométrie visible et compriment progressivement les angles de liaison.`,
  },
  {
    order: 30,
    difficulty: 'EASY',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Sélectionnez exactement les deux associations correctes hybridation → organisation.`,
    choices: [
      { content: `$\\mathrm{sp}$ → linéaire, $180^\\circ$.`, correct: true, explanation: `Deux directions opposées.` },
      { content: `$\\mathrm{sp}^2$ → trigonale plane, environ $120^\\circ$.`, correct: true, explanation: `Trois directions coplanaires.` },
      { content: `$\\mathrm{sp}^3$ → linéaire, $180^\\circ$.`, correct: false, explanation: `sp3 donne quatre directions tétraédriques.` },
      { content: `$\\mathrm{sp}^2$ → tétraédrique, environ $109{,}5^\\circ$.`, correct: false, explanation: `La géométrie tétraédrique correspond à sp3.` },
    ],
    explanation: `Le nombre d'orbitales hybrides permet de relier directement sp, sp2 et sp3 aux organisations linéaire, trigonale plane et tétraédrique.`,
  },
];

export const UE14_CH3_HYBRIDATION_PRACTICE_V2_QUESTIONS: HealthTrainingAuthorQuestion[] = [
  {
    order: 31,
    difficulty: 'MEDIUM',
    format: 'QRU',
    question: `En cas d'acidocétose diabétique, l'acétone peut donner une odeur fruitée à l'haleine. Le carbone du groupe carbonyle de $\\ce{CH3-C(=O)-CH3}$ est hybridé $\\mathrm{sp}^2$. Quelle représentation en cases quantiques lui correspond après hybridation ?`,
    choices: [
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{s}', boxes: ['pair'] }, { label: '2\\mathrm{p}', boxes: ['up', 'up', 'empty'] }] },
        correct: false,
        explanation: `État atomique avant hybridation.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{sp}^{2}', boxes: ['up', 'up', 'up'] }, { label: '2\\mathrm{p}', boxes: ['up'] }] },
        correct: true,
        explanation: `Trois orbitales sp2 et une orbitale p non hybridée, toutes simplement occupées.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{sp}^{3}', boxes: ['up', 'up', 'up', 'up'] }] },
        correct: false,
        explanation: `Cette représentation correspond à sp3.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{sp}', boxes: ['up', 'up'] }, { label: '2\\mathrm{p}', boxes: ['up', 'up'] }] },
        correct: false,
        explanation: `Cette représentation correspond à sp.`,
      },
    ],
    explanation: `Un carbone sp2 possède trois orbitales hybrides sp2 pour les liaisons sigma et une orbitale p non hybridée pour la composante pi.`,
  },
  {
    order: 32,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `Le dioxyde de carbone $\\ce{O=C=O}$ est produit par le métabolisme puis éliminé par les poumons. Quelles propositions sont exactes pour son carbone central ?`,
    choices: [
      { content: `Il est hybridé $\\mathrm{sp}$.`, correct: true, explanation: `Deux directions de liaison.` },
      { content: `Deux orbitales $\\mathrm{sp}$ participent aux deux liaisons $\\sigma$.`, correct: true, explanation: `Une vers chaque oxygène.` },
      { content: `Deux orbitales $\\mathrm{p}$ non hybridées participent aux deux liaisons $\\pi$.`, correct: true, explanation: `Une pi pour chaque C=O.` },
      { content: `Il utilise quatre orbitales $\\mathrm{sp}^3$ équivalentes.`, correct: false, explanation: `Ce serait incompatible avec les deux composantes pi.` },
    ],
    explanation: `L'hybridation sp du carbone explique à la fois la linéarité du CO2 et la présence de deux orbitales p pour les deux liaisons pi.`,
  },
  {
    order: 33,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `L'ion ammonium $\\ce{NH4+}$ participe à l'élimination rénale de la charge acide. Quelles propositions sont exactes ?`,
    choices: [
      { content: `L'azote est décrit comme $\\mathrm{sp}^3$ dans $\\ce{NH3}$ comme dans $\\ce{NH4+}$.`, correct: true, explanation: `Quatre directions orbitalaires dans les deux espèces.` },
      { content: `La protonation utilise le doublet non liant de $\\ce{NH3}$ pour former une quatrième liaison N–H.`, correct: true, explanation: `Le proton ne fournit pas d'électron.` },
      { content: `$\\ce{NH4+}$ présente une géométrie tétraédrique.`, correct: true, explanation: `Quatre liaisons sans doublet non liant.` },
      { content: `$\\ce{NH4+}$ reste pyramidal car $\\ce{NH3}$ l'était avant protonation.`, correct: false, explanation: `Le doublet est désormais engagé dans une liaison.` },
    ],
    explanation: `La protonation transforme le doublet non liant de NH3 en quatrième liaison sans changer le caractère sp3 de l'azote.`,
  },
  {
    order: 34,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `On compare les occupations des orbitales $\\mathrm{sp}^3$ de $\\ce{NH3}$ et de $\\ce{H2O}$. Sélectionnez exactement les deux propositions correctes.`,
    choices: [
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '\\ce{NH3}', boxes: ['pair', 'up', 'up', 'up'] }] },
        correct: true,
        explanation: `Un doublet non liant et trois électrons engagés dans des liaisons.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '\\ce{H2O}', boxes: ['pair', 'pair', 'up', 'up'] }] },
        correct: true,
        explanation: `Deux doublets non liants et deux électrons engagés dans des liaisons.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '\\ce{NH3}', boxes: ['pair', 'pair', 'up', 'up'] }] },
        correct: false,
        explanation: `Cela correspond plutôt au schéma électronique de l'eau.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '\\ce{H2O}', boxes: ['pair', 'up', 'up', 'up'] }] },
        correct: false,
        explanation: `Cela correspond plutôt au schéma électronique de NH3.`,
      },
    ],
    explanation: `NH3 et H2O utilisent quatre orbitales sp3, mais leur occupation diffère par le nombre de doublets non liants.`,
  },
  {
    order: 35,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `La figure représente trois organisations d'orbitales hybrides.\n\n![Orientations des hybridations sp, sp2 et sp3](/images/training/ue14/orbitales-moleculaires/geometries-hybridation-sp-sp2-sp3.png)`,
    choices: [
      { content: `Le schéma A correspond à $\\mathrm{sp}$ et $180^\\circ$.`, correct: true, explanation: `Deux directions opposées.` },
      { content: `Le schéma B correspond à $\\mathrm{sp}^2$ et environ $120^\\circ$.`, correct: true, explanation: `Trois directions coplanaires.` },
      { content: `Le schéma C correspond à $\\mathrm{sp}^3$ et à une organisation tétraédrique.`, correct: true, explanation: `Quatre directions tridimensionnelles.` },
      { content: `Le schéma C est strictement plan avec des angles de $90^\\circ$.`, correct: false, explanation: `Une organisation sp3 est tétraédrique.` },
    ],
    explanation: `Les représentations spatiales permettent d'associer directement le nombre d'orbitales hybrides à la géométrie correspondante.`,
  },
  {
    order: 36,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `L'éthanol $\\ce{CH3-CH2-OH}$ est utilisé dans les solutions hydroalcooliques. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Les deux carbones sont hybridés $\\mathrm{sp}^3$.`, correct: true, explanation: `Ils ne participent qu'à des liaisons simples.` },
      { content: `L'oxygène peut être décrit avec quatre orbitales $\\mathrm{sp}^3$, dont deux contiennent des doublets non liants.`, correct: true, explanation: `Deux liaisons et deux doublets.` },
      { content: `Toutes les liaisons de cette formule sont de type $\\sigma$.`, correct: true, explanation: `Il n'y a aucune liaison multiple.` },
      { content: `La liaison C–O comporte une liaison $\\pi$.`, correct: false, explanation: `C'est une liaison simple sigma.` },
    ],
    explanation: `Dans l'éthanol, les atomes de carbone et l'oxygène sont décrits localement par des environnements sp3.`,
  },
  {
    order: 37,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Le lactate est dosé dans certaines situations d'hypoperfusion. Dans l'acide lactique $\\ce{CH3-CH(OH)-C(=O)-OH}$, combien des trois atomes de carbone sont hybridés $\\mathrm{sp}^3$ ?`,
    answer: { type: 'number', value: 2, tolerance: 0 },
    explanation: `Le carbone du méthyle et le carbone portant OH sont sp3 ; le carbone du carboxyle est sp2.`,
  },
  {
    order: 38,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `L'ion hydrogénocarbonate $\\ce{HCO3-}$ participe au système tampon du sang. Autour de son carbone central, on considère trois directions C–O. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Le carbone est décrit comme hybridé $\\mathrm{sp}^2$.`, correct: true, explanation: `Trois directions sigma.` },
      { content: `Les trois orbitales hybrides sont approximativement coplanaires à $120^\\circ$.`, correct: true, explanation: `Organisation trigonale plane.` },
      { content: `Une orbitale $\\mathrm{p}$ non hybridée reste disponible.`, correct: true, explanation: `L'hybridation sp2 laisse une p non hybridée.` },
      { content: `Le carbone est $\\mathrm{sp}^3$ parce que l'ion contient plusieurs oxygènes.`, correct: false, explanation: `Il faut compter les directions autour du carbone, pas les atomes de la formule brute.` },
    ],
    explanation: `Le carbone de l'hydrogénocarbonate est un exemple biologique d'environnement tricoordonné compatible avec sp2.`,
  },
  {
    order: 39,
    difficulty: 'MEDIUM',
    format: 'QRU',
    question: `Quel est l'intérêt principal du modèle d'hybridation pour expliquer le méthane $\\ce{CH4}$ ?`,
    choices: [
      { content: `Rendre compte de quatre liaisons C–H équivalentes orientées tétraédriquement.`, correct: true, explanation: `Quatre orbitales sp3 équivalentes expliquent les quatre liaisons.` },
      { content: `Déterminer la trajectoire exacte de chacun des quatre électrons.`, correct: false, explanation: `Une orbitale ne définit pas une trajectoire précise.` },
      { content: `Transformer les atomes d'hydrogène en orbitales moléculaires.`, correct: false, explanation: `L'hybridation concerne ici les orbitales de valence du carbone.` },
      { content: `Montrer que le méthane est plan.`, correct: false, explanation: `Le méthane est tétraédrique.` },
    ],
    explanation: `L'hybridation sp3 relie la structure électronique de valence du carbone à quatre liaisons équivalentes orientées dans l'espace.`,
  },
  {
    order: 40,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `Dans l'ion oxonium $\\ce{H3O+}$, quelles propositions sont exactes ?`,
    choices: [
      { content: `L'oxygène est décrit comme $\\mathrm{sp}^3$.`, correct: true, explanation: `Trois liaisons et un doublet non liant.` },
      { content: `Trois orbitales participent aux liaisons O–H et la quatrième contient un doublet non liant.`, correct: true, explanation: `Quatre domaines électroniques.` },
      { content: `La géométrie moléculaire est pyramidale.`, correct: true, explanation: `Type AX3E1.` },
      { content: `La géométrie est trigonale plane parce qu'il y a trois hydrogènes visibles.`, correct: false, explanation: `Le doublet non liant doit être pris en compte.` },
    ],
    explanation: `H3O+ est un exemple de centre sp3 dont un domaine électronique est occupé par un doublet non liant.`,
  },
  {
    order: 83,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Un carbone hybridé $\\mathrm{sp}^2$ possède combien d'orbitales $\\mathrm{p}$ non hybridées restantes ?`,
    answer: { type: 'number', value: 1, tolerance: 0 },
    explanation: `Deux orbitales p sont combinées avec une s pour former trois sp2 ; une orbitale p reste non hybridée.`,
  },
  {
    order: 84,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Sélectionnez exactement les deux espèces dont l'atome central est décrit comme $\\mathrm{sp}$ dans le modèle du chapitre.`,
    choices: [
      { content: `$\\ce{BeH2}$`, correct: true, explanation: `Deux directions de liaison, géométrie linéaire.` },
      { content: `$\\ce{CO2}$`, correct: true, explanation: `Deux directions autour du carbone central.` },
      { content: `$\\ce{NH3}$`, correct: false, explanation: `L'azote est sp3.` },
      { content: `$\\ce{H2O}$`, correct: false, explanation: `L'oxygène est sp3.` },
    ],
    explanation: `BeH2 et CO2 possèdent un centre décrit par deux directions orbitalaires opposées, donc une hybridation sp.`,
  },
];
