/**
 * UE14 – Biologie cellulaire – Chapitre 7
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’ATP synthase :`,
    choices: [
      `Utilise le gradient de protons.`,
      `Produit de l’ATP dans la matrice.`,
      `Transforme ADP et phosphate inorganique en ATP.`,
      `Se situe dans la membrane externe.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ATP synthase est implantée dans la membrane interne mitochondriale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les deux parties de l’ATP synthase sont :`,
    choices: [
      `F0, canal protonique.`,
      `F1, partie catalytique.`,
      `F0, ADN mitochondrial.`,
      `F1, activité ATP synthase.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `F0 conduit les protons et F1 catalyse la synthèse d’ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le retour des H+ par l’ATP synthase :`,
    choices: [
      `Se fait de l’espace intermembranaire vers la matrice.`,
      `Fournit l’énergie de la synthèse d’ATP.`,
      `Exploite la force motrice protonique.`,
      `Se produit exclusivement par le complexe II.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le complexe II ne constitue pas le canal de retour des protons.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le fonctionnement inverse de l’ATP synthase mentionné dans la fiche :`,
    choices: [
      `Peut hydrolyser l’ATP en ADP.`,
      `Peut contribuer à augmenter les H+ dans l’espace intermembranaire.`,
      `Peut être utile si le gradient protonique est insuffisant.`,
      `Produit alors davantage d’ATP sans consommation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le fonctionnement inverse consomme de l’ATP au lieu d’en produire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le rendement énergétique indiqué est :`,
    choices: [
      `2,5 ATP par NADH oxydé.`,
      `1,5 ATP par FADH2 oxydé.`,
      `30 ATP au total par glucose dans l’exemple musculaire.`,
      `100 ATP par NADH.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche donne des valeurs précises pour les coenzymes et le glucose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans l’exemple musculaire de la fiche, un glucose fournit :`,
    choices: [
      `2 ATP dans le cytosol.`,
      `28 ATP dans la mitochondrie.`,
      `30 ATP au total.`,
      `Uniquement 2 ATP au total.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le bilan total présenté est de 30 ATP par glucose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les 28 ATP mitochondriaux indiqués comprennent :`,
    choices: [
      `2 ATP issus de deux GTP du cycle de Krebs.`,
      `26 ATP issus de la phosphorylation oxydative.`,
      `Un total mitochondrial supérieur au bilan total.`,
      `Une composante de phosphorylation oxydative.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le bilan mitochondrial est décomposé en 2 ATP équivalents du cycle de Krebs et 26 par phosphorylation oxydative.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante :

![Inhibiteurs et rendement](/images/training/ue14/biologie-cellulaire/mitochondrie/inhibiteurs-rendement-atp.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Le NADH a un rendement supérieur au FADH2.`,
      `La mitochondrie fournit 28 ATP dans le bilan présenté.`,
      `Le cytosol fournit 2 ATP.`,
      `Le complexe II est inhibé par la roténone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure associe le complexe II au malonate, et le complexe I à la roténone.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les inhibiteurs du complexe I cités sont :`,
    choices: [
      `La roténone.`,
      `Les barbituriques.`,
      `Le malonate.`,
      `Des composés pouvant réduire la respiration mitochondriale.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le malonate est associé au complexe II.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Quel inhibiteur est associé au complexe II ?`,
    choices: [
      `Le malonate.`,
      `L’antimycine A.`,
      `Le cyanure.`,
      `L’oligomycine.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La fiche associe le malonate au complexe II.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Quel inhibiteur est associé au complexe III ?`,
    choices: [
      `L’antimycine A.`,
      `La roténone.`,
      `Le malonate.`,
      `L’oligomycine.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L’antimycine A est l’inhibiteur cité du complexe III.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les inhibiteurs du complexe IV cités sont :`,
    choices: [
      `Le cyanure.`,
      `L’oxyde de carbone.`,
      `Le malonate.`,
      `Des poisons pouvant entraîner un décès rapide.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche présente le cyanure et l’oxyde de carbone comme inhibiteurs du complexe IV.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `L’oligomycine inhibe :`,
    choices: [
      `L’ATP synthase.`,
      `Le complexe I.`,
      `Le complexe II.`,
      `Le transporteur TOM.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L’oligomycine est associée à l’ATP synthase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le blocage de l’ATP synthase par l’oligomycine peut :`,
    choices: [
      `Empêcher l’utilisation normale du gradient protonique pour former l’ATP.`,
      `Réduire la production d’ATP mitochondrial.`,
      `Perturber le retour des protons par F0.`,
      `Stimuler directement la translocation TOM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’oligomycine cible l’ATP synthase, non les complexes d’import protéique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le cyanure est particulièrement dangereux car :`,
    choices: [
      `Il bloque le complexe IV.`,
      `Il empêche le transfert final des électrons à l’oxygène.`,
      `Il compromet rapidement la respiration cellulaire.`,
      `Il augmente la phosphorylation oxydative.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le blocage du complexe IV interrompt la chaîne respiratoire et la production énergétique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un calcul fondé sur la fiche donne pour 2 NADH :`,
    choices: [
      `5 ATP.`,
      `Un rendement supérieur à celui de 2 FADH2.`,
      `2,5 ATP par NADH.`,
      `3 ATP au total.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Deux NADH correspondent à 2 × 2,5 = 5 ATP ; deux FADH2 donneraient 3 ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour 4 FADH2, le rendement théorique indiqué est :`,
    choices: [
      `6 ATP.`,
      `4 × 1,5 ATP.`,
      `Inférieur au rendement de 4 NADH.`,
      `10 ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Quatre FADH2 donnent 6 ATP selon la valeur de 1,5 ATP par FADH2.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour 3 NADH et 2 FADH2, le rendement théorique indiqué est :`,
    choices: [
      `10,5 ATP.`,
      `7,5 ATP issus des NADH.`,
      `3 ATP issus des FADH2.`,
      `15 ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le calcul est 3 × 2,5 + 2 × 1,5 = 10,5 ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le rendement plus élevé du NADH que du FADH2 est cohérent avec :`,
    choices: [
      `Une entrée des électrons du NADH au complexe I.`,
      `Une entrée des électrons du FADH2 au complexe II.`,
      `Le pompage de protons par le complexe I mais pas par le complexe II.`,
      `Une synthèse directe d’ATP par le FADH2.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’entrée au complexe I permet de bénéficier d’une étape de pompage supplémentaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le bilan de 30 ATP par glucose présenté :`,
    choices: [
      `Est un exemple donné pour une cellule musculaire.`,
      `Inclut une part cytosolique et une part mitochondriale.`,
      `Comprend la phosphorylation oxydative.`,
      `Signifie que toutes les cellules produisent toujours exactement 30 ATP dans toutes les conditions.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche présente un bilan contextualisé, non une valeur universelle indépendante des conditions.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition du complexe I par la roténone pourrait réduire :`,
    choices: [
      `L’oxydation du NADH entrant par le complexe I.`,
      `Le pompage protonique au complexe I.`,
      `Le rendement énergétique lié à cette voie.`,
      `L’effet du malonate sur le complexe II.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La roténone cible le complexe I, tandis que le malonate cible le complexe II.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition du complexe II par le malonate :`,
    choices: [
      `Perturbe la voie d’entrée des électrons par le complexe II.`,
      `N’annule pas directement le pompage du complexe II puisqu’il n’en assure pas.`,
      `Peut diminuer le flux électronique global.`,
      `Cible l’ATP synthase F1.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le malonate agit sur le complexe II, distinct de l’ATP synthase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition du complexe III par l’antimycine A :`,
    choices: [
      `Bloque le transfert en aval vers le cytochrome c.`,
      `Réduit un site de pompage protonique.`,
      `Peut diminuer la force motrice protonique.`,
      `Augmente automatiquement le rendement du NADH.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le blocage de III diminue le flux d’électrons et le gradient protonique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut de F0 affecterait surtout :`,
    choices: [
      `Le canal protonique de l’ATP synthase.`,
      `Le retour des protons vers la matrice.`,
      `Le couplage entre gradient et synthèse d’ATP.`,
      `L’insertion des protéines par SAM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `F0 est le canal protonique de l’ATP synthase, sans lien avec SAM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut de F1 affecterait surtout :`,
    choices: [
      `L’activité catalytique de synthèse d’ATP.`,
      `La conversion ADP + Pi en ATP.`,
      `Le fonctionnement de l’ATP synthase.`,
      `Le passage des petites molécules par les porines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `F1 correspond à la partie enzymatique de l’ATP synthase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si le gradient de protons s’effondre alors que F1 reste intacte :`,
    choices: [
      `La force motrice protonique diminue.`,
      `La synthèse d’ATP devient moins efficace.`,
      `La partie catalytique manque de l’énergie fournie par le retour des protons.`,
      `Le rendement du NADH augmente automatiquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La présence de F1 ne suffit pas sans gradient protonique exploitable.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un patient exposé à l’oxyde de carbone peut présenter une défaillance énergétique car :`,
    choices: [
      `Le complexe IV est inhibé selon la fiche.`,
      `La respiration mitochondriale est compromise.`,
      `La production d’ATP par phosphorylation oxydative diminue.`,
      `Le cycle de Krebs devient une pompe à protons.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le blocage du complexe IV perturbe la chaîne respiratoire et le gradient.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour 6 NADH et 2 FADH2, le rendement théorique indiqué est :`,
    choices: [
      `18 ATP.`,
      `15 ATP issus des NADH.`,
      `3 ATP issus des FADH2.`,
      `21 ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le calcul est 6 × 2,5 + 2 × 1,5 = 18 ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La comparaison entre NADH et FADH2 montre que :`,
    choices: [
      `Le rendement dépend du point d’entrée des électrons.`,
      `Le complexe II ne pompe pas de protons.`,
      `Le NADH fournit 1 ATP de plus par molécule dans les valeurs indiquées.`,
      `Le FADH2 fournit toujours plus d’ATP que le NADH.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les valeurs données sont 2,5 ATP pour NADH et 1,5 ATP pour FADH2.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?`,
    choices: [
      `L’ATP synthase exploite le gradient construit par la chaîne respiratoire.`,
      `Les inhibiteurs peuvent cibler chaque complexe ou l’ATP synthase.`,
      `Le rendement énergétique peut être calculé à partir de NADH et FADH2.`,
      `L’ATP est synthétisé exclusivement dans le cytosol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitochondrie assure la majorité du bilan énergétique présenté dans la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: `atp-synthase-et-phosphorylation-oxydative`,
    title: `ATP synthase et phosphorylation oxydative`,
    description: `Force motrice protonique, sous-unités F0 et F1 et synthèse d’ATP.`,
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: `inhibiteurs-chaine-respiratoire`,
    title: `Inhibiteurs de la chaîne respiratoire`,
    description: `Roténone, malonate, antimycine A, cyanure, CO et oligomycine.`,
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 9,
    slug: `rendement-et-calculs-atp`,
    title: `Rendement et calculs de production d’ATP`,
    description: `Rendements du NADH et du FADH2 et bilan énergétique du glucose.`,
    stage: 'MASTER',
    sectionOrder: 3,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];
