import type { SeedQuestion, SeedQuiz } from './health-training-ue13.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos de l’histologie :",
    choices: [
      "Elle analyse et décrit les tissus à l’aide d’un microscope.",
      "Elle constitue une science fondamentale.",
      "Elle étudie exclusivement les organes à l’œil nu.",
      "Elle se confond avec l’étude de l’échelle moléculaire.",
    ],
    correctChoiceIndexes: [0, 1],
    explanation: "L’histologie est une science fondamentale consacrée à l’analyse et à la description microscopique des tissus.",
    choiceExplanations: [
      "Cette proposition reprend la définition du cours.",
      "Le cours présente explicitement l’histologie comme une science fondamentale.",
      "L’observation des organes à l’œil nu relève surtout de l’approche macroscopique.",
      "L’échelle moléculaire est étudiée par la biochimie.",
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Un tissu peut être défini comme :",
    choices: [
      "Un assemblage de cellules et de matrice extracellulaire.",
      "Une organisation assurant une même fonction dans l’organisme.",
      "Un ensemble nécessairement formé uniquement de cellules jointives.",
      "Une structure dont l’organisation topographique contribue à la fonction.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Un tissu associe des cellules et une matrice extracellulaire, organisées dans l’espace pour assurer une fonction.",
    choiceExplanations: [
      "Le cours inclut bien les cellules et la matrice extracellulaire dans la définition.",
      "La communauté de fonction est un élément central de la définition.",
      "Les cellules jointives caractérisent surtout le tissu épithélial, pas tous les tissus.",
      "L’organisation topographique participe à l’exercice de la fonction.",
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant les échelles d’observation :",
    choices: [
      "La chimie étudie notamment l’échelle atomique.",
      "La biochimie étudie notamment l’échelle moléculaire.",
      "La biologie cellulaire étudie notamment l’échelle cellulaire.",
      "L’histologie se situe entre l’échelle cellulaire et celle des organes.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le cours situe l’histologie à l’échelle des tissus, entre la cellule et l’organe.",
    choiceExplanations: [
      "L’association entre chimie et échelle atomique est celle du cours.",
      "L’association entre biochimie et échelle moléculaire est celle du cours.",
      "L’association entre biologie cellulaire et échelle cellulaire est celle du cours.",
      "L’échelle tissulaire est intermédiaire entre cellule et organe.",
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’observation macroscopique et l’observation microscopique se distinguent notamment par le fait que :",
    choices: [
      "L’observation macroscopique est réalisée à l’œil nu.",
      "L’observation macroscopique concerne surtout l’analyse des organes.",
      "L’observation microscopique étudie l’organisation des cellules dans un tissu.",
      "L’observation microscopique ne nécessite jamais de microscope.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La macroscopie observe surtout les organes à l’œil nu, alors que la microscopie analyse l’organisation cellulaire au sein des tissus.",
    choiceExplanations: [
      "C’est le principe de l’observation macroscopique.",
      "Le cours rattache surtout la macroscopie à l’analyse des organes.",
      "C’est précisément l’objectif de l’observation microscopique en histologie.",
      "Un microscope est au contraire indispensable à cette observation.",
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les familles suivantes, lesquelles appartiennent aux quatre tissus fondamentaux ?",
    choices: [
      "Les tissus épithéliaux.",
      "Les tissus conjonctifs.",
      "Les tissus musculaires.",
      "Le tissu nerveux.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le cours distingue quatre grandes familles : épithéliale, conjonctive, musculaire et nerveuse.",
    choiceExplanations: [
      "Le tissu épithélial est l’une des quatre familles.",
      "Les tissus conjonctifs constituent une deuxième famille.",
      "Les tissus musculaires constituent une troisième famille.",
      "Le tissu nerveux complète cette classification.",
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "D’après les ordres de grandeur indiqués dans le cours :",
    choices: [
      "Le tissu épithélial représente environ 3 % du volume du corps.",
      "Le tissu nerveux représente environ 2 % du volume du corps.",
      "Les tissus musculaires et conjonctifs composent la majeure partie du corps.",
      "Le tissu nerveux constitue à lui seul la majorité du volume corporel.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le cours insiste sur la faible proportion volumique des tissus épithélial et nerveux, malgré leurs fonctions majeures.",
    choiceExplanations: [
      "La valeur de 3 % est celle indiquée pour le tissu épithélial.",
      "La valeur de 2 % est celle indiquée pour le tissu nerveux.",
      "La majorité du volume est attribuée aux tissus musculaires et conjonctifs.",
      "Cette proposition est incompatible avec la valeur de 2 %.",
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le tissu épithélial :",
    choices: [
      "Est formé de cellules jointives.",
      "Peut séparer deux environnements distincts.",
      "Peut assurer des fonctions de barrière, de sécrétion ou d’absorption.",
      "Est exclusivement spécialisé dans la contraction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les épithéliums associent des cellules jointives et des fonctions de séparation, de protection, de sécrétion ou d’échange.",
    choiceExplanations: [
      "La jointivité cellulaire est une caractéristique présentée dans le cours.",
      "La séparation de deux environnements est une fonction majeure.",
      "La peau, l’estomac et l’intestin illustrent ces rôles.",
      "La contraction caractérise le tissu musculaire.",
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le tissu musculaire :",
    choices: [
      "Est constitué de cellules capables de se contracter.",
      "Participe au mouvement de l’organisme.",
      "Comprend des muscles volontaires et involontaires.",
      "Est le tissu principalement dédié à la réception et à la transmission d’informations.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La contraction des cellules musculaires permet le mouvement, qu’il soit volontaire ou involontaire.",
    choiceExplanations: [
      "La contractilité définit la cellule musculaire dans ce chapitre introductif.",
      "Le mouvement est la fonction générale mise en avant.",
      "Le cours distingue ces deux grands modes de contrôle.",
      "La communication constitue la fonction centrale du tissu nerveux.",
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos du tissu nerveux :",
    choices: [
      "Il est dédié à la communication.",
      "Il reçoit des informations venant de l’extérieur ou de l’intérieur du corps.",
      "Les neurones transmettent l’information à des cellules effectrices ou à d’autres neurones.",
      "Il ne comporte aucune cellule spécialisée dans la transmission de l’information.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le tissu nerveux reçoit, traite et fait circuler des informations grâce notamment aux neurones.",
    choiceExplanations: [
      "La communication est sa fonction générale.",
      "Les deux origines de l’information sont mentionnées dans le cours.",
      "Ce sont les deux grandes destinations indiquées pour l’information neuronale.",
      "Les neurones sont précisément spécialisés dans cette transmission.",
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les analyses histologiques ont, selon le cours, des finalités :",
    choices: [
      "D’enseignement.",
      "De recherche.",
      "De diagnostic.",
      "Uniquement décoratives.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’histologie contribue à l’enseignement, à la recherche biomédicale et au diagnostic.",
    choiceExplanations: [
      "L’enseignement vise à connaître les tissus et le fonctionnement microscopique du corps.",
      "La recherche étudie notamment le développement, les maladies et les thérapeutiques.",
      "L’analyse de prélèvements participe au diagnostic.",
      "Cette proposition n’a aucun rapport avec les objectifs du cours.",
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un étudiant souhaite relier chaque discipline à son échelle principale d’étude. Quelles associations sont conformes au cours ?",
    choices: [
      "Atome — chimie.",
      "Molécule — biochimie.",
      "Cellule — biologie cellulaire.",
      "Organe — histologie exclusivement.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’anatomie étudie notamment les organes, tandis que l’histologie s’intéresse aux tissus.",
    choiceExplanations: [
      "Cette association est correcte.",
      "Cette association est correcte.",
      "Cette association est correcte.",
      "L’organe relève surtout de l’anatomie dans le repérage proposé.",
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une coupe permet d’observer comment plusieurs types cellulaires s’organisent entre eux dans la paroi d’un organe. Cette étude :",
    choices: [
      "Se place à l’échelle tissulaire.",
      "Relève de l’histologie.",
      "Est plus proche de l’échelle des tissus que de l’échelle atomique.",
      "Correspond nécessairement à une analyse macroscopique à l’œil nu.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’organisation de cellules au sein d’un tissu constitue l’objet même de l’histologie microscopique.",
    choiceExplanations: [
      "L’objet observé est un tissu organisé.",
      "La discipline adaptée est l’histologie.",
      "L’échelle atomique est beaucoup plus petite.",
      "Une coupe observée pour son organisation cellulaire relève de la microscopie.",
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’organisation topographique d’un tissu signifie notamment que :",
    choices: [
      "La position relative de ses constituants participe à sa fonction.",
      "Deux tissus contenant les mêmes types de cellules peuvent différer par leur organisation.",
      "La fonction d’un tissu est indépendante de toute organisation spatiale.",
      "L’histologie étudie aussi la manière dont les cellules s’agencent.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La fonction tissulaire dépend non seulement des constituants présents, mais aussi de leur disposition dans l’espace.",
    choiceExplanations: [
      "Cette idée est explicitement portée par la définition du cours.",
      "Une organisation différente peut modifier la fonction assurée.",
      "Cette proposition nie le rôle de l’organisation topographique.",
      "L’agencement cellulaire est au cœur de l’observation histologique.",
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos de la formation des organes :",
    choices: [
      "Les tissus s’assemblent pour former les organes.",
      "Un organe peut associer plusieurs familles de tissus fondamentaux.",
      "Chaque organe est nécessairement constitué d’un seul tissu.",
      "L’étude d’un organe peut comporter une étape macroscopique puis une étape microscopique.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les organes résultent de l’association organisée de plusieurs tissus, observables à différentes échelles.",
    choiceExplanations: [
      "Cette relation tissu-organe est donnée dans le cours.",
      "Les quatre familles peuvent contribuer à la constitution d’un organe.",
      "Un organe n’est pas limité à une seule famille tissulaire.",
      "Les deux types d’observation peuvent être complémentaires.",
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Associer correctement un rôle épithélial à un exemple :",
    choices: [
      "Barrière — peau.",
      "Sécrétion — estomac.",
      "Absorption — intestin.",
      "Purification — trachée ou bronches.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les quatre associations correspondent aux exemples introductifs du cours.",
    choiceExplanations: [
      "La peau illustre une fonction de barrière.",
      "L’estomac illustre une fonction de sécrétion.",
      "L’intestin illustre une fonction d’absorption.",
      "La trachée et les bronches illustrent une fonction de purification.",
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Parmi les fonctions suivantes, lesquelles sont rattachées dans le cours à l’activité musculaire ?",
    choices: [
      "Déplacements.",
      "Maintien de la posture.",
      "Respiration.",
      "Battements.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le cours cite des activités volontaires et involontaires, toutes fondées sur la contraction musculaire.",
    choiceExplanations: [
      "Les déplacements sont associés aux muscles volontaires.",
      "La posture est également associée aux muscles volontaires.",
      "La respiration est citée parmi les activités involontaires.",
      "Les battements sont cités parmi les activités involontaires.",
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un neurone transmet une information. D’après le cours introductif, cette information peut être destinée :",
    choices: [
      "À une cellule effectrice.",
      "À un autre neurone.",
      "Uniquement à une cellule épithéliale.",
      "À aucun autre type cellulaire.",
    ],
    correctChoiceIndexes: [0, 1],
    explanation: "Le neurone communique soit avec d’autres neurones, soit avec des cellules effectrices.",
    choiceExplanations: [
      "Cette destination est explicitement citée.",
      "La communication entre neurones est également citée.",
      "Le cours ne limite pas la transmission aux cellules épithéliales.",
      "La transmission constitue précisément la fonction du neurone.",
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Parmi les objectifs de recherche en histologie figurent :",
    choices: [
      "Comprendre le développement de l’organisme.",
      "Comprendre des processus pathologiques.",
      "Identifier de nouveaux marqueurs.",
      "Mettre au point de nouvelles thérapeutiques.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le cours associe l’histologie à plusieurs objectifs de recherche, de la compréhension des mécanismes à l’innovation thérapeutique.",
    choiceExplanations: [
      "Cet objectif est mentionné.",
      "Cet objectif est mentionné.",
      "Cet objectif est mentionné.",
      "Cet objectif est mentionné, notamment dans le domaine du cancer.",
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Parmi les prélèvements cités comme pouvant être analysés en histologie :",
    choices: [
      "Une biopsie.",
      "Une pièce opératoire.",
      "Un organisme entier dans le cadre d’une autopsie.",
      "Uniquement une goutte de sang non préparée.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le cours cite les biopsies, les pièces opératoires et les autopsies parmi les supports de l’analyse histologique.",
    choiceExplanations: [
      "La biopsie est un prélèvement histologique classique cité.",
      "La pièce opératoire est également citée.",
      "L’autopsie peut comporter des analyses histologiques.",
      "Cette proposition ne correspond pas à la liste donnée.",
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une analyse histologique réalisée en anatomopathologie peut :",
    choices: [
      "S’intégrer au parcours de prise en charge d’un patient.",
      "Contribuer à établir un diagnostic.",
      "Être effectuée par un médecin anatomopathologiste.",
      "Se limiter nécessairement à une observation sans microscope.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Dans le cadre décrit par le cours, l’analyse histologique participe au diagnostic en laboratoire d’anatomopathologie.",
    choiceExplanations: [
      "Elle s’inscrit dans le chemin de prise en charge.",
      "La finalité diagnostique est explicitement mentionnée.",
      "Le médecin anatomopathologiste est le professionnel cité.",
      "L’observation microscopique est au contraire centrale.",
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "reperes-fondamentaux-histologie",
    title: "Repères fondamentaux de l’histologie",
    description: "Définitions, échelles d’observation et premières caractéristiques des quatre tissus fondamentaux.",
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: "tissus-finalites-analyse-histologique",
    title: "Tissus et finalités de l’analyse histologique",
    description: "Applications sur l’organisation tissulaire, les fonctions des tissus et les usages diagnostiques ou scientifiques de l’histologie.",
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
];
