/**
 * UE14 – Biologie cellulaire – Chapitre 3
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La migration cellulaire intervient notamment lors :`,
    choices: [
      `De l’embryogenèse.`,
      `De l’inflammation.`,
      `De la cicatrisation.`,
      `Uniquement de la mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `De nombreuses cellules migrent dans des contextes physiologiques et pathologiques variés.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une cellule migrante :`,
    choices: [
      `Interagit avec la matrice extracellulaire par des plaques d’adhérence.`,
      `Émet des lamellipodes et des filopodes vers l’avant.`,
      `Crée de nouvelles adhérences à l’avant.`,
      `Conserve toutes ses adhérences arrière sans rétraction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La progression nécessite la formation d’adhérences à l’avant et leur rétraction à l’arrière.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la zone avant d’une cellule migrante :`,
    choices: [
      `Les filaments d’actine se polymérisent.`,
      `La membrane plasmique est poussée vers l’avant.`,
      `Les filopodes et lamellipodes se forment.`,
      `L’actine est totalement absente.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polymérisation d’actine produit une poussée membranaire à l’avant.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la zone intermédiaire de la cellule migrante :`,
    choices: [
      `Les filaments d’actine sont organisés en réseaux.`,
      `La filamine participe à cette organisation.`,
      `Cette zone se situe derrière le front de migration.`,
      `Elle ne contient aucun microfilament.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La filamine organise des réseaux d’actine dans la zone intermédiaire.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la zone de rétraction :`,
    choices: [
      `La gelsoline clive les filaments d’actine.`,
      `La thymosine limite la repolymérisation locale.`,
      `L’actine G peut être recyclée vers l’avant.`,
      `L’α-actinine ne joue jamais aucun rôle dans les forces de rétraction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le recyclage de l’actine soutient la poursuite de la migration ; l’α-actinine participe aux fibres contractiles.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Au niveau des plaques d’adhérence :`,
    choices: [
      `L’α-actinine peut participer à des fibres contractiles.`,
      `Les forces contribuent à la rétraction de l’arrière.`,
      `Les microfilaments s’associent à la matrice par des structures d’adhérence.`,
      `Les microfilaments sont remplacés par des chromosomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les plaques d’adhérence couplent le cytosquelette d’actine à la matrice extracellulaire.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Actine : tapis roulant et migration](/images/training/ue14/biologie-cellulaire/cytosquelette/actine-tapis-roulant-migration.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les faisceaux parallèles sont représentés vers l’avant.`,
      `Un réseau d’actine est représenté dans la zone intermédiaire.`,
      `Des fibres contractiles sont représentées à l’arrière.`,
      `Le sens du déplacement est représenté vers la zone de rétraction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure montre une polarité fonctionnelle de la cellule migrante, avec un front protrusif et un arrière contractile.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les filaments intermédiaires se localisent :`,
    choices: [
      `Autour du noyau dans une corbeille périnucléaire.`,
      `Dans les desmosomes et hémidesmosomes.`,
      `Dans le noyau sous forme de lamina.`,
      `Uniquement dans les cils mobiles.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les filaments intermédiaires forment des réseaux cytoplasmiques et nucléaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans le noyau, les filaments intermédiaires :`,
    choices: [
      `Forment un maillage régulier sous l’enveloppe nucléaire.`,
      `Contribuent à la résistance et à la forme du noyau.`,
      `Peuvent interagir avec la chromatine.`,
      `Sont constitués de tubuline β.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La lamina nucléaire est constituée de lamines, appartenant aux filaments intermédiaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La structure des filaments intermédiaires est caractérisée par :`,
    choices: [
      `Des extrémités équivalentes.`,
      `Une absence de polarité.`,
      `Des polymères stabilisés.`,
      `Une instabilité dynamique identique à celle des microtubules cytosoliques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les filaments intermédiaires sont surtout associés à la résistance mécanique et à la stabilité.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les filaments intermédiaires sont formés :`,
    choices: [
      `De monomères protéiques fibreux.`,
      `De plus de 70 protéines différentes classées en familles.`,
      `De protéines variables selon le type cellulaire.`,
      `D’un unique type de tubuline.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La grande hétérogénéité des protéines de filaments intermédiaires est une propriété essentielle.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les cytokératines sont associées :`,
    choices: [
      `Aux cellules épithéliales.`,
      `À la résistance mécanique des tissus comme l’épiderme.`,
      `À une famille de filaments intermédiaires cytoplasmiques.`,
      `Exclusivement aux neurones.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les neurofilaments caractérisent plutôt les neurones.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La vimentine est associée :`,
    choices: [
      `Aux fibroblastes.`,
      `À des cellules apparentées du tissu conjonctif.`,
      `À une famille de filaments intermédiaires cytoplasmiques.`,
      `À l’axonème des cils mobiles.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La vimentine est un marqueur de cellules mésenchymateuses comme les fibroblastes.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les neurofilaments :`,
    choices: [
      `Sont présents dans les neurones.`,
      `Participent au calibre des axones.`,
      `Sont des filaments intermédiaires.`,
      `Sont des protéines motrices de type kinésine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les neurofilaments sont des éléments structuraux, non des moteurs moléculaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La desmine :`,
    choices: [
      `Est présente dans les cellules musculaires squelettiques.`,
      `Participe à transmettre à la membrane les forces générées par l’appareil contractile.`,
      `Est un filament intermédiaire.`,
      `Est un canal hydrique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La desmine assure une continuité mécanique dans les cellules musculaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les lamines :`,
    choices: [
      `Sont des filaments intermédiaires nucléaires.`,
      `Participent à la lamina.`,
      `Contribuent à la forme et à la résistance du noyau.`,
      `Sont les moteurs antérogrades des microtubules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les lamines sont structurales et nucléaires ; la kinésine est le moteur antérograde.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Filaments intermédiaires](/images/training/ue14/biologie-cellulaire/cytosquelette/filaments-intermediaires.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Les filaments intermédiaires sont représentés comme très stabilisés.`,
      `La lamina est représentée sous l’enveloppe nucléaire.`,
      `Plusieurs familles de protéines sont associées à des types cellulaires distincts.`,
      `Les filaments intermédiaires sont présentés comme les plus dynamiques des trois réseaux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure résume la diversité et la fonction structurale des filaments intermédiaires.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les filaments intermédiaires résistent :`,
    choices: [
      `Aux forces d’étirement.`,
      `Aux déformations mécaniques.`,
      `Mieux que les microtubules et microfilaments selon le cours.`,
      `Uniquement aux gradients de GTP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Leur rôle principal est mécanique, sans dépendre d’une cape de GTP.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’hétérogénéité des filaments intermédiaires peut être utilisée en pathologie :`,
    choices: [
      `Pour aider à identifier la nature d’une cellule tumorale.`,
      `Parce que les familles varient selon le type cellulaire.`,
      `Comme outil d’orientation diagnostique.`,
      `Parce que toutes les tumeurs expriment exactement le même filament intermédiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le profil de filaments intermédiaires peut renseigner sur l’origine cellulaire d’une tumeur.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparés aux microtubules et à l’actine, les filaments intermédiaires :`,
    choices: [
      `Sont non polarisés.`,
      `Sont moins impliqués dans les phénomènes dynamiques rapides.`,
      `Sont spécialisés dans la résistance structurale.`,
      `Utilisent kinésine et dynéine pour leur polymérisation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les filaments intermédiaires sont des structures stabilisées sans moteurs associés de ce type dans le cours.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule épithéliale soumise à des forces mécaniques importantes dépend notamment :`,
    choices: [
      `Des cytokératines.`,
      `De l’ancrage des filaments intermédiaires aux desmosomes et hémidesmosomes.`,
      `D’un réseau permettant de distribuer les contraintes.`,
      `Uniquement de la cape de GTP des microtubules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La résistance mécanique épithéliale repose en grande partie sur le réseau de cytokératines.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une altération des neurofilaments pourrait :`,
    choices: [
      `Modifier le calibre des axones.`,
      `Affecter l’architecture du neurone.`,
      `Perturber une fonction structurale des filaments intermédiaires.`,
      `Transformer les neurones en hématies.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les neurofilaments influencent le calibre axonal sans déterminer l’identité cellulaire de cette façon.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une altération de la desmine pourrait :`,
    choices: [
      `Perturber la transmission des forces dans le muscle squelettique.`,
      `Affecter le couplage entre appareil contractile et membrane.`,
      `Fragiliser l’organisation mécanique cellulaire.`,
      `Supprimer directement la tubuline α des centrioles.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La desmine agit dans le réseau mécanique musculaire, indépendamment de la tubuline centriolaire.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une altération des lamines pourrait :`,
    choices: [
      `Modifier la forme du noyau.`,
      `Diminuer sa résistance mécanique.`,
      `Perturber les interactions avec la chromatine.`,
      `Affecter uniquement les cils respiratoires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La lamina est une structure nucléaire, non un composant direct des cils.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Lors de la migration cellulaire, le renouvellement de l’actine est spatialement organisé car :`,
    choices: [
      `La polymérisation se concentre à l’avant.`,
      `La dépolymérisation et le recyclage se produisent à l’arrière.`,
      `L’actine G est réutilisée pour de nouveaux filaments.`,
      `Toute l’actine est immobilisée définitivement dans les plaques d’adhérence.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La migration repose sur un flux dynamique de monomères et une organisation régionale.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le rôle de la thymosine dans la zone de rétraction est de :`,
    choices: [
      `Limiter la repolymérisation locale.`,
      `Favoriser le recyclage de l’actine G vers l’avant.`,
      `Contribuer indirectement au renouvellement du front de migration.`,
      `Former les 13 protofilaments du microtubule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La thymosine agit sur l’actine, non sur les microtubules.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le rôle de la gelsoline est de :`,
    choices: [
      `Cliver des filaments d’actine.`,
      `Favoriser leur dissociation dans la zone de rétraction.`,
      `Contribuer au remodelage du cytosquelette pendant la migration.`,
      `Hydrolyser le GTP de la tubuline β.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La gelsoline est une protéine de remodelage de l’actine.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une cellule migrante, l’avant et l’arrière diffèrent par :`,
    choices: [
      `La nature de l’organisation des microfilaments.`,
      `Le type de forces produites.`,
      `La dynamique d’adhérence à la matrice.`,
      `L’absence totale de cytosquelette à l’avant.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le front est protrusif et l’arrière contractile, mais les deux reposent sur le cytosquelette.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle(s) comparaison(s) est(sont) correcte(s) ?`,
    choices: [
      `Microtubules et actine sont polarisés.`,
      `Les filaments intermédiaires sont non polarisés.`,
      `Les microtubules et l’actine sont plus dynamiques que les filaments intermédiaires.`,
      `Les trois réseaux ont le même diamètre et la même protéine monomérique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois réseaux diffèrent par leurs protéines, leurs diamètres et leurs propriétés.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?`,
    choices: [
      `L’actine permet la protrusion, l’adhérence et la rétraction pendant la migration.`,
      `Les filaments intermédiaires assurent surtout la résistance mécanique.`,
      `Les trois réseaux coopèrent pour organiser la cellule.`,
      `Les filaments intermédiaires sont les principaux moteurs ATPasiques des vésicules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les moteurs vésiculaires étudiés sont surtout kinésine, dynéine et myosine I.`,
    choiceExplanations: [
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Exact : cette proposition correspond aux éléments présentés dans le cours.`,
      `Faux : cette proposition contredit ou dépasse les éléments présentés dans le cours.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `migration-cellulaire-et-remodelage-de-actine`,
    title: `Migration cellulaire et remodelage de l’actine`,
    description: `Front de migration, adhérences, rétraction et recyclage.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `filaments-intermediaires-et-resistance-cellulaire`,
    title: `Filaments intermédiaires et résistance cellulaire`,
    description: `Localisation, familles, structure et fonctions mécaniques.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `integration-des-reseaux-du-cytosquelette`,
    title: `Intégration des réseaux du cytosquelette`,
    description: `Applications à la migration, aux tissus et à la pathologie.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
