import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_ORDER = 3;

export const SECTION_C_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  61: ["Définition des isomères"],
  62: ["Isomérie de fonction"],
  63: ["Stéréoisomérie"],
  64: ["Énantiomères"],
  65: ["Propriétés des énantiomères"],
  66: ["Stéréospécificité enzymatique"],
  67: ["Diastéréoisomères"],
  68: ["Épimères"],
  69: ["Épimérie glucose-galactose"],
  70: ["Épimérie glucose-mannose"],
  71: ["Relation galactose-mannose"],
  72: ["Épimérisation"],
  73: ["Épimérases"],
  74: ["Contexte médical : galactosémie"],
  75: ["D-ribose et L-ribose"],
  76: ["D-glucose et L-glucose"],
  77: ["Hiérarchie des stéréoisomères"],
  78: ["Anomérie et épimérie"],
  79: ["Limites de la formule brute en isomérie"],
  80: ["Reconnaissance d'une paire d'énantiomères"],
  81: ["Comparaison de projections de Fischer"],
  82: ["Épimérie en C4"],
  83: ["Reconnaissance des énantiomères"],
  84: ["Classification d'une relation stéréochimique"],
  85: ["Identification d'épimères"],
  86: ["Application enzymatique"],
  87: ["Cas clinique : déficit d'épimérase"],
  88: ["Démarche de classification"],
  89: ["Méthode d'identification"],
  90: ["Synthèse de la section C"],
};

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "decouvrir-isomerie-enantiomerie-epimerie",
    title: "Isomérie et épimérie",
    description: "Définir les principales relations d'isomérie et mémoriser les épimères usuels du glucose.",
    stage: 'DISCOVER',
    sectionOrder: SECTION_C_ORDER,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 2,
    slug: "sentrainer-diastereoisomeres-epimerases",
    title: "Diastéréoisomères et épimérases",
    description: "Comparer les relations stéréochimiques et relier l'épimérisation à la stéréospécificité enzymatique.",
    stage: 'PRACTICE',
    sectionOrder: SECTION_C_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 71 },
      { type: 'QUESTION', questionOrder: 72 },
      {
        type: 'GROUP',
        title: "Épimérase et galactosémie",
        sharedStatement: "Une épimérase catalyse l'interconversion de deux épimères. Un déficit de cette activité peut perturber le métabolisme du galactose.",
        questionOrders: [73, 74],
      },
      { type: 'QUESTION', questionOrder: 75 },
      { type: 'QUESTION', questionOrder: 76 },
      { type: 'QUESTION', questionOrder: 77 },
      { type: 'QUESTION', questionOrder: 78 },
      { type: 'QUESTION', questionOrder: 79 },
      { type: 'QUESTION', questionOrder: 80 },
    ],
  },
  {
    order: 3,
    slug: "maitriser-comparaison-projections-fischer",
    title: "Comparaison de projections de Fischer",
    description: "Identifier énantiomères, diastéréoisomères et épimères à partir de motifs de positions des groupes hydroxyle.",
    stage: 'MASTER',
    sectionOrder: SECTION_C_ORDER,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Deux isomères :",
    choices: [
      "Possèdent la même formule brute.",
      "Peuvent avoir des formules développées différentes.",
      "Sont nécessairement superposables.",
      "Peuvent appartenir à des familles fonctionnelles différentes.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les isomères partagent une formule brute mais diffèrent par leur structure ou leur organisation spatiale.",
    choiceExplanations: [
      "C'est la condition commune.",
      "L'isomérie de constitution l'illustre.",
      "Des isomères sont précisément des espèces distinctes.",
      "Glycéraldéhyde et dihydroxyacétone en sont un exemple.",
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le glycéraldéhyde et la dihydroxyacétone :",
    choices: [
      "Ont la même formule brute $\\mathrm{C_3H_6O_3}$.",
      "Diffèrent par la nature de leur fonction carbonyle.",
      "Sont des isomères de fonction.",
      "Sont deux énantiomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'un est un aldose, l'autre un cétose : ils sont isomères de constitution ou de fonction, et non énantiomères.",
    choiceExplanations: [
      "Formule commune correcte.",
      "Aldéhyde contre cétone.",
      "Cette différence définit l'isomérie de fonction.",
      "Leur connectivité n'est pas la même.",
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Des stéréoisomères :",
    choices: [
      "Ont la même connectivité atomique.",
      "Diffèrent par l'organisation de leurs atomes dans l'espace.",
      "Peuvent être des énantiomères ou des diastéréoisomères.",
      "Ont toujours des formules brutes différentes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les stéréoisomères conservent la formule brute et l'enchaînement des atomes, mais diffèrent spatialement.",
    choiceExplanations: [
      "La connectivité est conservée.",
      "C'est le principe de la stéréoisomérie.",
      "Ce sont les deux grandes relations étudiées.",
      "La formule brute reste identique.",
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Deux énantiomères :",
    choices: [
      "Sont images l'un de l'autre dans un miroir.",
      "Ne sont pas superposables.",
      "Ont tous leurs centres chiraux inversés.",
      "Sont toujours des isomères de fonction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les énantiomères sont des images miroir non superposables avec inversion de tous les centres chiraux.",
    choiceExplanations: [
      "Définition correcte.",
      "Définition correcte.",
      "Condition correcte pour plusieurs centres.",
      "Leur connectivité est identique.",
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Deux énantiomères :",
    choices: [
      "Ont les mêmes propriétés physico-chimiques usuelles.",
      "Diffèrent par leur pouvoir rotatoire.",
      "Peuvent être distingués par une enzyme stéréospécifique.",
      "Ont nécessairement des masses molaires différentes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Dans un milieu achiral, les propriétés usuelles sont identiques sauf le signe du pouvoir rotatoire ; les systèmes biologiques peuvent les distinguer.",
    choiceExplanations: [
      "Repère du cours.",
      "Leur rotation est opposée.",
      "Les enzymes sont elles-mêmes chirales.",
      "La formule brute et donc la masse molaire sont identiques.",
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La stéréospécificité enzymatique signifie qu'une enzyme :",
    choices: [
      "Peut reconnaître préférentiellement une configuration.",
      "Peut métaboliser une forme D mais pas la forme L correspondante.",
      "Est indifférente à toute organisation spatiale.",
      "Peut expliquer des différences biologiques entre énantiomères.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Une enzyme possède un site actif tridimensionnel et peut distinguer des stéréoisomères.",
    choiceExplanations: [
      "Définition correcte.",
      "Exemple possible.",
      "La géométrie est au contraire déterminante.",
      "Cette reconnaissance crée des effets biologiques différents.",
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Deux diastéréoisomères :",
    choices: [
      "Sont des stéréoisomères.",
      "Ne sont pas images miroir l'un de l'autre.",
      "Ne sont pas superposables.",
      "Ont obligatoirement tous leurs centres chiraux inversés.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les diastéréoisomères sont des stéréoisomères non superposables qui ne forment pas une paire d'images miroir.",
    choiceExplanations: [
      "Ils conservent la connectivité.",
      "C'est ce qui les distingue des énantiomères.",
      "Ce sont deux molécules différentes.",
      "Cette inversion totale définirait des énantiomères.",
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Deux épimères :",
    choices: [
      "Sont des diastéréoisomères.",
      "Ne diffèrent que par un seul carbone asymétrique.",
      "Ont la même formule brute.",
      "Ont tous leurs centres chiraux inversés.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les épimères forment un cas particulier de diastéréoisomérie : un seul centre chiral diffère.",
    choiceExplanations: [
      "Relation générale correcte.",
      "Définition précise.",
      "Toute stéréoisomérie conserve la formule brute.",
      "Une inversion totale correspondrait à l'énantiomérie.",
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Le D-galactose est l'épimère du D-glucose en :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "C1.",
      "C2.",
      "C4.",
      "C6.",
    ],
    correctChoiceIndexes: [2],
    explanation: "Le D-galactose et le D-glucose diffèrent par la configuration du carbone 4.",
    choiceExplanations: [
      "C1 n'est pas le centre de différence dans la forme linéaire.",
      "C2 distingue glucose et mannose.",
      "C4 est la position à retenir.",
      "C6 est un groupe $\\mathrm{CH_2OH}$ non chiral.",
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Le D-mannose est l'épimère du D-glucose en :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "C1.",
      "C2.",
      "C4.",
      "C5.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Le D-mannose et le D-glucose diffèrent uniquement par la configuration du carbone 2.",
    choiceExplanations: [
      "Le carbonyle C1 n'est pas la différence.",
      "C2 est la position à retenir.",
      "C4 distingue glucose et galactose.",
      "C5 fixe leur série D commune.",
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer le D-galactose et le D-mannose :",
    choices: [
      "Ils appartiennent tous deux à la série D.",
      "Ils diffèrent notamment en C2 et en C4.",
      "Ils sont diastéréoisomères.",
      "Ils sont épimères l'un de l'autre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Ils ont le même dernier centre D mais diffèrent à deux centres ; ce sont des diastéréoisomères, pas des épimères.",
    choiceExplanations: [
      "Leur OH de C5 est à droite.",
      "Deux configurations diffèrent.",
      "Ils ne sont ni identiques ni images miroir.",
      "Un épimère ne diffère qu'à un centre.",
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L'épimérisation :",
    choices: [
      "Correspond au passage d'un épimère à un autre.",
      "Peut être réalisée chimiquement en milieu alcalin.",
      "Peut être catalysée par une épimérase.",
      "Inverse nécessairement tous les centres chiraux.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'épimérisation modifie la configuration d'un centre donné, par voie chimique ou enzymatique.",
    choiceExplanations: [
      "Définition correcte.",
      "Moyen cité dans la fiche.",
      "Une épimérase catalyse cette transformation.",
      "Une inversion totale produirait un énantiomère.",
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une épimérase :",
    choices: [
      "Est une enzyme.",
      "Catalyse l'interconversion de deux épimères.",
      "Peut intervenir dans le métabolisme des oses.",
      "Transforme toujours un aldose en acide gras.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les épimérases modifient la configuration d'un centre chiral sans changer la famille en acide gras.",
    choiceExplanations: [
      "Nature correcte.",
      "Fonction correcte.",
      "Application biologique directe.",
      "Cette transformation n'a aucun rapport avec un acide gras.",
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L'absence d'une épimérase dans le métabolisme du galactose :",
    choices: [
      "Empêche une conversion normale du galactose vers le métabolisme du glucose.",
      "Peut conduire à une galactosémie congénitale.",
      "Illustre l'importance de la stéréochimie enzymatique.",
      "Provoque nécessairement une allergie au lait.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le déficit enzymatique perturbe le métabolisme du galactose et illustre la reconnaissance stéréospécifique.",
    choiceExplanations: [
      "Conséquence métabolique décrite.",
      "Pathologie citée.",
      "La configuration du substrat est essentielle.",
      "Une allergie est une réaction immunitaire distincte.",
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le D-ribose et le L-ribose :",
    choices: [
      "Sont énantiomères.",
      "Sont images miroir non superposables.",
      "Ont des pouvoirs rotatoires de signes opposés en conditions identiques.",
      "Sont épimères en un seul centre seulement.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les formes D et L d'une même molécule inversent tous leurs centres chiraux : elles sont énantiomères.",
    choiceExplanations: [
      "Relation correcte.",
      "Définition correcte.",
      "Propriété optique des énantiomères.",
      "Le ribose possède plusieurs centres ; ils sont tous inversés.",
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le D-glucose et le L-glucose :",
    choices: [
      "Ont la même formule brute.",
      "Ont la même connectivité.",
      "Sont énantiomères.",
      "Sont deux isomères de fonction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux glucoses diffèrent uniquement par l'inversion spatiale de tous leurs centres.",
    choiceExplanations: [
      "L'énantiomérie conserve la composition.",
      "L'enchaînement des atomes est le même.",
      "Relation correcte.",
      "La fonction reste un aldose.",
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos des relations entre stéréoisomères :",
    choices: [
      "Tous les épimères sont des diastéréoisomères.",
      "Tous les diastéréoisomères sont des épimères.",
      "Deux énantiomères ne sont pas des diastéréoisomères.",
      "Deux molécules identiques ne sont pas des isomères distincts.",
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: "L'épimérie est un sous-ensemble de la diastéréoisomérie, mais l'inverse n'est pas vrai.",
    choiceExplanations: [
      "Relation d'inclusion correcte.",
      "Des diastéréoisomères peuvent différer à plusieurs centres.",
      "Les deux catégories sont distinctes.",
      "Une molécule superposable à elle-même n'est pas un autre isomère.",
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Après cyclisation, les formes α et β d'un même ose :",
    choices: [
      "Diffèrent à un seul centre appelé carbone anomérique.",
      "Sont des diastéréoisomères.",
      "Peuvent être considérées comme des épimères particuliers.",
      "Sont toujours des énantiomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les anomères diffèrent uniquement au nouveau centre anomérique ; ce sont des diastéréoisomères et des épimères particuliers.",
    choiceExplanations: [
      "Différence structurale exacte.",
      "Ils ne sont pas images miroir totales.",
      "Un seul centre varie.",
      "Les autres centres conservent leur configuration.",
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La seule connaissance d'une formule brute :",
    choices: [
      "Permet d'identifier la composition atomique.",
      "Ne suffit pas à distinguer isomérie de fonction et stéréoisomérie.",
      "Ne permet pas toujours d'identifier un ose précis.",
      "Détermine automatiquement la configuration D ou L.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La formule brute ne donne ni la connectivité détaillée ni l'organisation spatiale.",
    choiceExplanations: [
      "Information réellement fournie.",
      "Des formules structurales sont nécessaires.",
      "Plusieurs oses partagent une formule.",
      "D/L exige une projection ou une configuration.",
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans une paire d'énantiomères possédant plusieurs centres chiraux :",
    choices: [
      "Tous les centres sont inversés.",
      "Le dernier centre passe de D à L ou inversement.",
      "La formule brute reste identique.",
      "Un seul centre seulement est inversé.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'énantiomère est l'image miroir complète : tous les centres changent et la série s'inverse.",
    choiceExplanations: [
      "Condition exacte.",
      "Conséquence sur le dernier centre.",
      "Composition inchangée.",
      "Un seul centre définirait plutôt une paire d'épimères.",
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On code les positions des OH de C2 à C5 d'un aldohexose par D pour droite et G pour gauche. Le D-glucose a le motif D-G-D-D et le D-mannose G-G-D-D. On peut conclure que :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "Ils diffèrent uniquement en C2.",
      "Ils sont épimères en C2.",
      "Ils sont énantiomères.",
      "Ils appartiennent tous deux à la série D.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les deux motifs ne diffèrent qu'au premier centre, C2, tandis que C5 reste à droite.",
    choiceExplanations: [
      "Comparaison directe.",
      "Définition de l'épimérie.",
      "Tous les centres ne sont pas inversés.",
      "Le dernier symbole D définit la série D.",
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Le D-glucose a le motif D-G-D-D et le D-galactose D-G-G-D. On peut conclure que :",
    choices: [
      "Ils diffèrent uniquement en C4.",
      "Ils sont épimères en C4.",
      "Ils appartiennent à des séries opposées.",
      "Ils sont diastéréoisomères.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La seule variation porte sur C4 ; les deux molécules restent de série D.",
    choiceExplanations: [
      "Comparaison directe.",
      "Relation précise.",
      "Le dernier OH est à droite dans les deux cas.",
      "Tout épimère est un diastéréoisomère.",
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Le D-glucose a le motif D-G-D-D et le L-glucose G-D-G-G. On peut conclure que :",
    choices: [
      "Tous les centres sont inversés.",
      "Les deux molécules sont énantiomères.",
      "Elles possèdent des formules brutes différentes.",
      "Le dernier OH est à gauche dans le L-glucose.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le motif du L-glucose est l'inversion complète de celui du D-glucose.",
    choiceExplanations: [
      "Condition exacte.",
      "Relation exacte.",
      "La formule brute reste la même.",
      "Le dernier symbole G définit la série L.",
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Deux aldohexoses de série D diffèrent en C2 et C3 mais sont identiques en C4 et C5. Ils sont :",
    choices: [
      "Des stéréoisomères.",
      "Des diastéréoisomères.",
      "Des épimères.",
      "Des énantiomères.",
    ],
    correctChoiceIndexes: [0, 1],
    explanation: "Ils diffèrent à plusieurs centres sans inversion complète : ce sont des diastéréoisomères non épimères.",
    choiceExplanations: [
      "Même connectivité et différence spatiale.",
      "Catégorie correcte.",
      "Deux centres diffèrent.",
      "Leurs autres centres ne sont pas inversés.",
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: "Deux oses diffèrent uniquement par le passage d'un OH de droite à gauche en C3, tous les autres centres étant identiques. Ils sont :",
    choices: [
      "Des énantiomères.",
      "Des épimères en C3.",
      "Des isomères de fonction.",
      "La même molécule.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Une différence à un seul carbone asymétrique définit une paire d'épimères.",
    choiceExplanations: [
      "Il faudrait inverser tous les centres.",
      "Relation exacte.",
      "La connectivité et la fonction sont conservées.",
      "La configuration de C3 est différente.",
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une enzyme transforme un D-ose en un autre D-ose en inversant seulement la configuration de C4. Cette enzyme peut être qualifiée :",
    choices: [
      "D'épimérase.",
      "De catalyseur d'une épimérisation.",
      "D'enzyme stéréospécifique.",
      "De polymérase d'ADN par définition.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La réaction modifie un seul centre chiral et relève d'une épimérase.",
    choiceExplanations: [
      "Nom fonctionnel adapté.",
      "Description correcte.",
      "Le site actif distingue les configurations.",
      "Aucun lien nécessaire avec la réplication de l'ADN.",
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un nouveau-né présente une accumulation de galactose liée à un déficit enzymatique d'épimérisation. On peut retenir que :",
    choices: [
      "Le défaut concerne une transformation stéréochimique.",
      "La structure spatiale du substrat compte pour l'enzyme.",
      "La pathologie citée est une galactosémie congénitale.",
      "Le déficit prouve que galactose et glucose sont des énantiomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'exemple médical relie déficit d'épimérase et galactosémie ; glucose et galactose sont épimères en C4, pas énantiomères.",
    choiceExplanations: [
      "Nature de la réaction.",
      "Principe de stéréospécificité.",
      "Nom cité dans la fiche.",
      "Ils ne diffèrent qu'en C4.",
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Deux molécules ont même formule brute et même fonction aldéhyde, mais leurs OH diffèrent dans l'espace. Elles peuvent être :",
    choices: [
      "Des stéréoisomères.",
      "Des énantiomères si tous les centres sont inversés.",
      "Des épimères si un seul centre est inversé.",
      "Nécessairement des isomères de fonction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La fonction et la connectivité étant conservées, la différence relève de la stéréoisomérie.",
    choiceExplanations: [
      "Catégorie générale possible.",
      "Condition correcte.",
      "Condition correcte.",
      "Une isomérie de fonction supposerait une fonction différente.",
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Pour décider si deux oses sont énantiomères, il faut :",
    choices: [
      "Comparer tous leurs centres chiraux.",
      "Vérifier qu'ils sont images miroir.",
      "Constater l'inversion de chaque configuration.",
      "Se limiter au signe D ou L sans examiner les autres centres.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Des séries opposées ne suffisent pas à elles seules : l'ensemble des centres doit être comparé.",
    choiceExplanations: [
      "Étape nécessaire.",
      "Définition géométrique.",
      "Critère pratique.",
      "Deux oses D et L différents ne sont pas forcément la même paire énantiomère.",
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Concernant isomérie et épimérie :",
    choices: [
      "Le glucose et le fructose illustrent une isomérie de fonction.",
      "Le glucose et le galactose illustrent une épimérie en C4.",
      "Le glucose et le mannose illustrent une épimérie en C2.",
      "Tous les items précédents sont vrais.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les trois exemples sont ceux à retenir ; l'item récapitulatif est donc vrai.",
    choiceExplanations: [
      "Aldose contre cétose.",
      "Différence unique en C4.",
      "Différence unique en C2.",
      "A, B et C étant vraies, cet item l'est aussi.",
    ],
  },
];
