/**
 * Cartographie éditoriale V2
 * UE14 – Chimie organique – Chapitre 2.7
 * Les acides et divers
 */

export const UE14_CH11_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'section-a-discovery-acides-nomenclature',
    title: `Acides carboxyliques : acidité et nomenclature`,
    description: `Repères sur les définitions de l'acide, les premiers acides carboxyliques, le carboxylate et la hiérarchie d'acidité.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'section-a-practice-acidite-derives-actives',
    title: `Acides carboxyliques : acidité et dérivés activés`,
    description: `Applications sur la faible électrophilie des acides, les halogénures et anhydrides d'acide et l'intérêt de l'activation pour les couplages.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,21,22],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'section-b-discovery-preparation-oxydation-hydrolyse',
    title: `Préparation des acides`,
    description: `Repères sur l'oxydation d'un alcool primaire et les hydrolyses des esters, amides et nitriles.`,
    stage: 'DISCOVER' as const,
    questionOrders: [23,24,25,26,27,28,29,30,31,32],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'section-b-practice-hydrolyse-nitriles',
    title: `Préparation des acides`,
    description: `Applications sur les bilans fonctionnels, l'intermédiaire amide des nitriles et le comptage des carbones.`,
    stage: 'PRACTICE' as const,
    questionOrders: [33,34,35,36,37,38,39,40,41,42,43,44],
  },
  {
    sectionOrder: 2,
    order: 3,
    slug: 'section-b-master-carboxylation-organomagnesiens',
    title: `Préparation des acides`,
    description: `Maîtrise des différentes voies de synthèse et de la carboxylation des organomagnésiens par CO2 avec bilan carbone.`,
    stage: 'MASTER' as const,
    questionOrders: [45,46,47,48,49,50,51,52,53,54,55,56],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'section-c-discovery-decarboxylation',
    title: `Décarboxylation`,
    description: `Repères sur la perte de CO2, les voies chimiques ou enzymatiques et les structures carbonylées favorables.`,
    stage: 'DISCOVER' as const,
    questionOrders: [57,58,59,60,61,62,63,64,65,66],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'section-c-practice-decarboxylation-carbonyles',
    title: `Décarboxylation`,
    description: `Applications sur le bilan carbone, les structures favorables et l'opposition carboxylation/décarboxylation.`,
    stage: 'PRACTICE' as const,
    questionOrders: [67,68,69,70,71,72,73,74,75,76,77,78],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'section-d-discovery-bases-nucleiques-nucleophilie',
    title: `Acides, bases et acides nucléiques`,
    description: `Repères sur les définitions électroniques, la nucléophilie des bases nucléiques, les nucléosides et les nucléotides.`,
    stage: 'DISCOVER' as const,
    questionOrders: [79,80,81,82,83,84,85,86,87,88],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'section-d-practice-nucleosides-nucleotides-toxicologie',
    title: `Acides, bases et acides nucléiques`,
    description: `Applications sur ribose et 2-désoxyribose, acidité portée par le phosphate et réactivité des dérivés halogénés avec les bases nucléiques.`,
    stage: 'PRACTICE' as const,
    questionOrders: [89,90,91,92,93,94,95,96,97,98,99,100],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'section-e-synthesis-practice-acides-divers',
    title: `Les acides et divers`,
    description: `Synthèse appliquée sur acidité, activation, préparation des acides, décarboxylation et acides nucléiques.`,
    stage: 'PRACTICE' as const,
    questionOrders: [101,102,103,104,105,106,107,108,109,110],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'maitriser-synthese-acides-divers',
    title: `Les acides et divers`,
    description: `Maîtrise transversale du chapitre dans des situations proches de l'examen, sans transformer le quiz en examen blanc.`,
    stage: 'MASTER' as const,
    questionOrders: [111,112,113,114,115,116,117,118,119,120,121,122],
  },
] as const;

export const UE14_CH11_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Acides carboxyliques : définitions, nomenclature et acidité`],
  2: [`Acides carboxyliques : définitions, nomenclature et acidité`],
  3: [`Nomenclature : acides méthanoïque et éthanoïque`],
  4: [`Nomenclature : acides éthanoïque à butanoïque`],
  5: [`Acides carboxyliques : définitions, nomenclature et acidité`],
  6: [`Carboxylate et délocalisation`],
  7: [`Hiérarchie d'acidité`],
  8: [`Acides carboxyliques : définitions, nomenclature et acidité`],
  9: [`Acides carboxyliques : définitions, nomenclature et acidité`],
  10: [`Acides carboxyliques : définitions, nomenclature et acidité`],
  11: [`Acides carboxyliques : dérivés activés`],
  12: [`Dérivés activés selon la fiche`],
  13: [`Acides carboxyliques : dérivés activés`],
  14: [`Acides carboxyliques : dérivés activés`],
  15: [`Activation et réactions de couplage`],
  16: [`Acides carboxyliques : dérivés activés`],
  17: [`Acides carboxyliques : dérivés activés`],
  18: [`Acides carboxyliques : dérivés activés`],
  19: [`Acides carboxyliques : dérivés activés`],
  20: [`Acides carboxyliques : dérivés activés`],
  21: [`Acidité et activation : synthèse QRPL`],
  22: [`Acides carboxyliques : dérivés activés`],
  23: [`Préparation des acides : repères`],
  24: [`Préparation des acides : repères`],
  25: [`Préparation des acides : repères`],
  26: [`Préparation des acides : repères`],
  27: [`Préparation des acides : repères`],
  28: [`Nitrile → amide → acide`],
  29: [`Préparation des acides : repères`],
  30: [`Organomagnésien + CO2`],
  31: [`Préparation des acides : repères`],
  32: [`Préparation des acides : repères`],
  33: [`Préparation des acides : hydrolyses et bilan carbone`],
  34: [`Préparation des acides : hydrolyses et bilan carbone`],
  35: [`Préparation des acides : hydrolyses et bilan carbone`],
  36: [`Préparation des acides : hydrolyses et bilan carbone`],
  37: [`Préparation des acides : hydrolyses et bilan carbone`],
  38: [`Carboxylation : QROC bilan carbone`],
  39: [`Préparation des acides : hydrolyses et bilan carbone`],
  40: [`Préparation des acides : hydrolyses et bilan carbone`],
  41: [`Préparation des acides : hydrolyses et bilan carbone`],
  42: [`Préparation des acides : hydrolyses et bilan carbone`],
  43: [`Préparation des acides : hydrolyses et bilan carbone`],
  44: [`Hydrolyse des nitriles : QROC`],
  45: [`Préparation des acides : maîtrise et carboxylation`],
  46: [`Préparation des acides : maîtrise et carboxylation`],
  47: [`Préparation des acides : maîtrise et carboxylation`],
  48: [`Préparation des acides : maîtrise et carboxylation`],
  49: [`Préparation des acides : maîtrise et carboxylation`],
  50: [`QZONE : carbone apporté par CO2`],
  51: [`Préparation des acides : maîtrise et carboxylation`],
  52: [`Préparation des acides : maîtrise et carboxylation`],
  53: [`Préparation des acides : maîtrise et carboxylation`],
  54: [`Préparation des acides : maîtrise et carboxylation`],
  55: [`Préparation des acides : synthèse QRPL`],
  56: [`Préparation des acides : maîtrise et carboxylation`],
  57: [`Décarboxylation : définition`],
  58: [`Décarboxylation : définition et structures favorables`],
  59: [`Décarboxylation : définition et structures favorables`],
  60: [`Structures favorables à la décarboxylation`],
  61: [`Décarboxylation : définition et structures favorables`],
  62: [`Décarboxylation : définition et structures favorables`],
  63: [`Décarboxylation : définition et structures favorables`],
  64: [`Décarboxylation : définition et structures favorables`],
  65: [`Décarboxylation : définition et structures favorables`],
  66: [`Décarboxylation : définition et structures favorables`],
  67: [`Décarboxylation : applications et bilan carbone`],
  68: [`Décarboxylation : QROC bilan carbone`],
  69: [`Carboxylation versus décarboxylation`],
  70: [`Décarboxylation : applications et bilan carbone`],
  71: [`Décarboxylation : applications et bilan carbone`],
  72: [`Décarboxylation : applications et bilan carbone`],
  73: [`Décarboxylation : applications et bilan carbone`],
  74: [`Décarboxylation : applications et bilan carbone`],
  75: [`Décarboxylation : applications et bilan carbone`],
  76: [`Décarboxylation : applications et bilan carbone`],
  77: [`Décarboxylation : applications et bilan carbone`],
  78: [`Décarboxylation : synthèse QRPL`],
  79: [`Acides nucléiques : bases, nucléosides et nucléotides`],
  80: [`Acides nucléiques : bases, nucléosides et nucléotides`],
  81: [`Bases nucléiques : nucléophilie`],
  82: [`Acides nucléiques : bases, nucléosides et nucléotides`],
  83: [`Dérivés halogénés : électrophilie et toxicité`],
  84: [`Acides nucléiques : bases, nucléosides et nucléotides`],
  85: [`Nucléosides : ribose et 2-désoxyribose`],
  86: [`Acides nucléiques : bases, nucléosides et nucléotides`],
  87: [`Acides nucléiques : bases, nucléosides et nucléotides`],
  88: [`Nucléotides : acidité du phosphate`],
  89: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  90: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  91: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  92: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  93: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  94: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  95: [`Bases nucléiques et mutagénicité selon la fiche`],
  96: [`Nucléotides : QROC phosphate`],
  97: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  98: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  99: [`Acides nucléiques : nucléophilie, phosphate et toxicologie`],
  100: [`Acides nucléiques : synthèse QRPL`],
  101: [`Synthèse appliquée : acides et acides nucléiques`],
  102: [`Synthèse appliquée : acides et acides nucléiques`],
  103: [`Synthèse appliquée : acides et acides nucléiques`],
  104: [`Synthèse appliquée : acides et acides nucléiques`],
  105: [`Carboxylation versus décarboxylation`],
  106: [`Synthèse appliquée : acides et acides nucléiques`],
  107: [`Synthèse appliquée : acides et acides nucléiques`],
  108: [`Synthèse appliquée : acides et acides nucléiques`],
  109: [`Bilan carbone : QRP`],
  110: [`Synthèse PRACTICE QRPL`],
  111: [`Maîtrise transversale : acides et divers`],
  112: [`Maîtrise transversale : acides et divers`],
  113: [`Maîtrise transversale : acides et divers`],
  114: [`Électrophile, nucléophile et bases nucléiques`],
  115: [`Nucléotide : phosphate et acidité`],
  116: [`Maîtrise transversale : acides et divers`],
  117: [`Maîtrise transversale : acides et divers`],
  118: [`Maîtrise transversale : acides et divers`],
  119: [`Maîtrise transversale : acides et divers`],
  120: [`Maîtrise transversale : acides et divers`],
  121: [`Maîtrise transversale : acides et divers`],
  122: [`Synthèse générale QRPL`],
};
