/**
 * UE14 – Biologie cellulaire – Chapitre 7
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les cytopathies mitochondriales sont :`,
    choices: [
      `Des maladies génétiques mitochondriales.`,
      `Susceptibles d’atteindre des tissus très consommateurs d’énergie.`,
      `Illustrées dans la fiche par des maladies musculaires ou une cécité liée au nerf optique.`,
      `Des maladies exclusivement dues au glycocalyx.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le déficit en ATP peut toucher notamment le muscle ou le nerf optique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La synthèse d’hormones stéroïdiennes implique :`,
    choices: [
      `Une coopération entre mitochondrie et REL.`,
      `L’entrée de cholestérol dans la mitochondrie.`,
      `Des cytochromes P450.`,
      `Une synthèse exclusive dans le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie alterne des étapes mitochondriales et réticulaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la voie stéroïdienne décrite :`,
    choices: [
      `Le cholestérol est transformé en prégnénolone dans la mitochondrie.`,
      `La prégnénolone rejoint le REL.`,
      `D’autres hydroxylations peuvent avoir lieu dans le REL.`,
      `Le complexe II produit directement les œstrogènes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cytochromes P450 mitochondriaux et du REL coopèrent dans cette biosynthèse.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les hormones citées comme produits de ces voies comprennent :`,
    choices: [
      `Œstrogènes et progestérone.`,
      `Androgènes.`,
      `Cortisol et aldostérone.`,
      `Insuline synthétisée par l’ATP synthase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie ces hormones stéroïdes aux gonades et aux glandes corticosurrénales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La mitochondrie coopère aussi avec le RE pour :`,
    choices: [
      `La biosynthèse de phospholipides membranaires.`,
      `La synthèse d’hormones stéroïdiennes.`,
      `Des échanges métaboliques spécialisés.`,
      `Former le système ABO.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les coopérations mitochondrie–RE concernent notamment les lipides et les stéroïdes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans la voie intrinsèque de l’apoptose :`,
    choices: [
      `Le potentiel de membrane mitochondrial chute.`,
      `La perméabilité de la membrane interne est modifiée.`,
      `La chaîne respiratoire et la synthèse d’ATP peuvent s’arrêter.`,
      `La mitochondrie augmente indéfiniment son ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’apoptose mitochondriale s’accompagne d’une défaillance énergétique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La rupture mitochondriale peut libérer dans le cytosol :`,
    choices: [
      `Du cytochrome c.`,
      `Des ions Ca2+ et H+.`,
      `Des molécules apoptogènes et des procaspases selon la fiche.`,
      `Des antigènes ABO.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La libération de facteurs mitochondriaux active la cascade apoptotique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’apoptosome :`,
    choices: [
      `Participe à l’activation des caspases.`,
      `S’inscrit dans la voie intrinsèque de l’apoptose.`,
      `Peut conduire à l’activation d’endonucléases nucléaires.`,
      `Est une porine de la membrane externe.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’apoptosome est un complexe d’activation de la cascade apoptotique, non une porine.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La graisse brune :`,
    choices: [
      `Est spécialisée dans la production de chaleur.`,
      `Est riche en mitochondries.`,
      `Doit sa couleur en partie à cette abondance mitochondriale.`,
      `Est dépourvue de membrane interne mitochondriale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les mitochondries de la graisse brune portent une protéine de découplage spécialisée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La thermogénine :`,
    choices: [
      `Est une protéine de découplage UCP.`,
      `Se trouve dans la membrane interne mitochondriale.`,
      `Dissipe la force motrice protonique en chaleur.`,
      `Augmente directement la synthèse d’ATP maximale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La thermogénine découple l’oxydation de la synthèse d’ATP et favorise la chaleur.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La thermogenèse mitochondriale est particulièrement utile :`,
    choices: [
      `Chez le nouveau-né.`,
      `Chez les animaux en hibernation.`,
      `Pour maintenir la température corporelle.`,
      `Pour empêcher toute oxydation du NADH.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La thermogénine convertit en chaleur une part de l’énergie issue de l’oxydation des coenzymes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les radicaux libres superoxydes sont produits principalement, selon la fiche, par :`,
    choices: [
      `Le complexe I.`,
      `Le complexe III.`,
      `La chaîne respiratoire.`,
      `Le complexe TOM uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les complexes I et III sont cités comme sources de superoxydes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les superoxydes peuvent léser :`,
    choices: [
      `L’ADN.`,
      `Les protéines.`,
      `Les lipides membranaires.`,
      `Uniquement l’eau cytosolique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les espèces réactives de l’oxygène peuvent endommager plusieurs familles de macromolécules.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les conséquences associées aux radicaux libres comprennent :`,
    choices: [
      `Le vieillissement.`,
      `Des maladies dégénératives.`,
      `Des lésions cellulaires.`,
      `Une protection absolue de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les superoxydes sont associés à des dommages et non à une protection absolue.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les enzymes antioxydantes citées sont :`,
    choices: [
      `La superoxyde dismutase.`,
      `La glutathion peroxydase.`,
      `La peroxyrédoxine.`,
      `La succinate-déshydrogénase uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces enzymes limitent l’accumulation d’espèces réactives de l’oxygène.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante :

![Autres fonctions mitochondriales](/images/training/ue14/biologie-cellulaire/mitochondrie/autres-fonctions-mitochondrie.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `La mitochondrie participe à la synthèse stéroïdienne.`,
      `Le cytochrome c peut participer à l’apoptose.`,
      `Les UCP favorisent la production de chaleur.`,
      `Les complexes I et III ne produisent jamais de radicaux libres.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure rassemble quatre fonctions non limitées à la synthèse d’ATP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une activation excessive de la voie intrinsèque d’apoptose peut impliquer :`,
    choices: [
      `Une chute du potentiel mitochondrial.`,
      `Une libération de cytochrome c.`,
      `Une activation des caspases.`,
      `Une augmentation durable du gradient protonique et de l’ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie apoptotique est associée à une défaillance mitochondriale et à l’activation des caspases.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La production de chaleur par découplage signifie que :`,
    choices: [
      `Les protons peuvent retourner vers la matrice sans produire autant d’ATP.`,
      `La force motrice protonique est dissipée.`,
      `L’énergie d’oxydation est convertie en chaleur.`,
      `La chaîne respiratoire est transformée en noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le découplage sépare en partie l’oxydation de la phosphorylation.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une cytopathie mitochondriale affectant le nerf optique peut être reliée dans la fiche à :`,
    choices: [
      `Un manque d’ATP.`,
      `Une atteinte d’un tissu très dépendant de l’énergie.`,
      `Une possible cécité.`,
      `Une disparition du glycocalyx des hématies.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche cite la cécité par déficit énergétique du nerf optique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une maladie musculaire mitochondriale est cohérente avec :`,
    choices: [
      `Les besoins énergétiques élevés du muscle.`,
      `La proximité habituelle des mitochondries avec les myofibrilles.`,
      `Une insuffisance de production d’ATP.`,
      `Une absence de chaîne respiratoire dans toutes les cellules saines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le muscle est particulièrement sensible aux déficits de production énergétique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation d’une UCP dans la graisse brune pourrait perturber :`,
    choices: [
      `La dissipation du gradient protonique.`,
      `La conversion d’énergie en chaleur.`,
      `La thermorégulation du nouveau-né.`,
      `L’import de protéines par TOM uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les UCP sont des protéines de découplage, distinctes des translocases.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une libération de cytochrome c dans le cytosol peut :`,
    choices: [
      `Signaler une rupture de l’intégrité mitochondriale.`,
      `Favoriser la formation d’un apoptosome.`,
      `Activer une cascade de caspases.`,
      `Stimuler la synthèse d’ATP par le complexe II.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cytochrome c cytosolique est un facteur majeur de la voie apoptotique intrinsèque.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une surproduction de superoxydes au niveau du complexe I pourrait :`,
    choices: [
      `Endommager des lipides membranaires.`,
      `Altérer l’ADN ou des protéines.`,
      `Être combattue par des enzymes antioxydantes.`,
      `Améliorer systématiquement la longévité cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’excès de radicaux libres est délétère, pas systématiquement bénéfique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une déficience en superoxyde dismutase pourrait :`,
    choices: [
      `Réduire une défense antioxydante endogène.`,
      `Favoriser l’accumulation de superoxydes.`,
      `Augmenter les dommages oxydatifs.`,
      `Bloquer spécifiquement le complexe TOM sans autre effet.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La SOD participe à la limitation des espèces réactives de l’oxygène.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La coopération mitochondrie–REL dans la stéroïdogenèse repose sur :`,
    choices: [
      `Un premier traitement du cholestérol dans la mitochondrie.`,
      `La formation de prégnénolone.`,
      `Des hydroxylations complémentaires dans le REL.`,
      `Une synthèse exclusive par l’ADNmt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La stéroïdogenèse mobilise plusieurs compartiments et enzymes P450.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une chute du potentiel de membrane mitochondrial peut provoquer :`,
    choices: [
      `Un arrêt de la chaîne respiratoire.`,
      `Un arrêt de la synthèse d’ATP.`,
      `Une perméabilisation et une libération de facteurs apoptogènes.`,
      `Une augmentation immédiate du rendement du NADH.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La chute du potentiel est un événement central de la voie intrinsèque d’apoptose.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les autres fonctions de la mitochondrie montrent qu’elle :`,
    choices: [
      `Participe au métabolisme lipidique et hormonal.`,
      `Intervient dans la mort cellulaire programmée.`,
      `Contribue à la thermogenèse et à la gestion du stress oxydant.`,
      `Se limite à produire de l’ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitochondrie remplit plusieurs fonctions au-delà de la phosphorylation oxydative.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une atteinte des complexes I ou III peut combiner :`,
    choices: [
      `Un défaut de production énergétique.`,
      `Une modification de la production de radicaux libres.`,
      `Des conséquences sur des tissus énergétiquement exigeants.`,
      `Une augmentation garantie de toutes les hormones stéroïdes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les complexes I et III relient bioénergétique et stress oxydant.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le rôle de la mitochondrie dans l’apoptose et la thermogenèse illustre :`,
    choices: [
      `L’utilisation contrôlée ou la dissipation du gradient protonique.`,
      `La capacité de la mitochondrie à orienter le destin cellulaire.`,
      `La diversité de ses fonctions physiologiques.`,
      `L’absence totale de relation entre membrane interne et fonction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane interne et son potentiel jouent un rôle central dans ces fonctions.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?`,
    choices: [
      `La mitochondrie coopère avec le REL pour les stéroïdes et les phospholipides.`,
      `Elle peut déclencher la voie intrinsèque d’apoptose.`,
      `Elle produit chaleur et radicaux libres dans certains contextes.`,
      `Elle ne participe à aucune pathologie génétique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les cytopathies mitochondriales font partie des pathologies citées.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `cytopathies-steroides-phospholipides`,
    title: `Cytopathies, stéroïdes et phospholipides`,
    description: `Pathologies énergétiques et coopération avec le réticulum endoplasmique lisse.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `apoptose-et-thermogenese`,
    title: `Apoptose et thermogenèse`,
    description: `Voie intrinsèque, cytochrome c, UCP et graisse brune.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `stress-oxydant-et-fonctions-integrees`,
    title: `Stress oxydant et fonctions intégrées`,
    description: `Superoxydes, défenses antioxydantes et raisonnement physiopathologique.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
