import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_ORDER = 1;

export const SECTION_A_FUNCTIONS_DISCOVERY_QUIZ_SLUG =
  `section-a-discovery-fonctions-ester-amide`;
export const SECTION_A_PREPARATION_PRACTICE_QUIZ_SLUG =
  `section-a-practice-preparation-esters-amides`;
export const SECTION_A_PEPTIDE_MASTER_QUIZ_SLUG =
  `section-a-master-amides-liaison-peptidique-proline`;

export const SECTION_A_FUNCTIONS_DISCOVERY_QUESTION_ORDERS: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
export const SECTION_A_PREPARATION_PRACTICE_QUESTION_ORDERS: number[] = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
export const SECTION_A_PEPTIDE_MASTER_QUESTION_ORDERS: number[] = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: SECTION_A_FUNCTIONS_DISCOVERY_QUIZ_SLUG,
    title: `Fonctions ester et amide : les reconnaître`,
    description: `Identifier les motifs caractéristiques des esters et des amides et distinguer ces fonctions des acides carboxyliques, amines et éthers.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_A_ORDER,
    questionOrders: SECTION_A_FUNCTIONS_DISCOVERY_QUESTION_ORDERS,
  },
  {
    order: 2,
    slug: SECTION_A_PREPARATION_PRACTICE_QUIZ_SLUG,
    title: `Préparation des esters et des amides`,
    description: `Choisir l'acide activé et le partenaire nucléophile permettant de former un ester ou un amide.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_A_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 11 },
      { type: 'QUESTION', questionOrder: 12 },
      { type: 'QUESTION', questionOrder: 13 },
      { type: 'QUESTION', questionOrder: 14 },
      { type: 'QUESTION', questionOrder: 15 },
      { type: 'QUESTION', questionOrder: 16 },
      { type: 'QUESTION', questionOrder: 17 },
      {
        type: 'GROUP',
        title: `Un chlorure d'''acyle, deux nucléophiles`,
        sharedStatement: `On dispose du chlorure d'éthanoyle $\mathrm{CH_3COCl}$. Dans l'expérience **I**, il réagit avec l'éthanol $\mathrm{CH_3CH_2OH}$. Dans l'expérience **II**, il réagit avec la méthylamine $\mathrm{CH_3NH_2}$.`,
        questionOrders: [18, 19, 20],
      },
    ],
  },
  {
    order: 3,
    slug: SECTION_A_PEPTIDE_MASTER_QUIZ_SLUG,
    title: `Amides, liaison peptidique et résidu proline`,
    description: `Relier la fonction amide aux peptides et distinguer les différents environnements de l'azote, notamment au voisinage d'un résidu proline.`,
    stage: 'MASTER',
    sectionOrder: SECTION_A_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 21 },
      { type: 'QUESTION', questionOrder: 22 },
      { type: 'QUESTION', questionOrder: 23 },
      { type: 'QUESTION', questionOrder: 24 },
      { type: 'QUESTION', questionOrder: 25 },
      { type: 'QUESTION', questionOrder: 26 },
      { type: 'QUESTION', questionOrder: 27 },
      {
        type: 'GROUP',
        title: `Lecture d'''un fragment peptidique contenant une proline`,
        sharedStatement: `Un fragment peptidique contient deux liaisons amide. Le premier azote porte un hydrogène ; le second appartient au cycle d'un résidu proline et est lié à trois atomes de carbone dans le fragment.`,
        questionOrders: [28, 29, 30],
      },
    ],
  },
];

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `�' propos de la fonction ester :`,
    choices: [
      `Elle contient un groupe carbonyle $\mathrm{C{=}O}$.`,
      `Elle comporte un oxygène lié au carbone carbonylé et à un radical carboné.`,
      `Sa formule générale est uniquement $\mathrm{R{-}OH}$.`,
      `Le substituant porté par l'oxygène peut être noté $\mathrm{R'}$.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Un ester possède le motif $\mathrm{R{-}C(=O){-}OR'}$, avec un groupement carboné du côté $\mathrm{R'}$.`,
    choiceExplanations: [
      `Le carbonyle appartient au groupe acyle de l'ester.`,
      `Le motif $\mathrm{-C(=O){-}O{-}R'}$ caractérise l'ester.`,
      `Cette écriture correspond à un alcool.`,
      `$\mathrm{R'}$ représente le groupement carboné lié à l'oxygène.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La structure $\mathrm{CH_3{-}C(=O){-}O{-}CH_2CH_3}$ :`,
    choices: [
      `Possède une fonction ester.`,
      `Possède deux atomes d'oxygène.`,
      `Est un acide carboxylique car l'oxygène porte un hydrogène.`,
      `Peut s'écrire sous la forme générale $\mathrm{RCOOR'}$.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Cette molécule contient le motif carbonyle''�oxygène''�radical caractéristique d'un ester.`,
    choiceExplanations: [
      `Le motif $\mathrm{C(=O){-}O}$ est présent.`,
      `Un oxygène est carbonylé et l'autre est lié au radical éthyle.`,
      `L'oxygène est lié à un groupe éthyle, pas à un hydrogène.`,
      `Cette formule condensée correspond bien à un ester.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Pour distinguer un ester d'un acide carboxylique :`,
    choices: [
      `Un ester possède le motif $\mathrm{-COOR'}$ avec $\mathrm{R'}$ carboné.`,
      `Un acide carboxylique possède le motif $\mathrm{-COOH}$.`,
      `Si $\mathrm{R'}$ est un hydrogène dans $\mathrm{RCOOR'}$, on décrit un acide carboxylique.`,
      `Un ester ne contient jamais de groupe carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Dans un ester, l'oxygène simple est lié à un radical carboné ; dans un acide carboxylique, il est lié à un hydrogène.`,
    choiceExplanations: [
      `Le radical lié à l'oxygène permet d'identifier l'ester.`,
      `Le groupe hydroxyle est directement lié au carbone carbonylé.`,
      `La formule devient $\mathrm{RCOOH}$.`,
      `Le carbonyle est une partie essentielle de la fonction ester.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `�' propos de la fonction amide :`,
    choices: [
      `Elle contient un atome d'azote directement lié au carbone carbonylé.`,
      `L'azote peut porter deux hydrogènes.`,
      `L'azote peut porter un hydrogène et un radical.`,
      `Elle ne contient jamais d'oxygène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une amide associe un groupe carbonyle à un atome d'azote : $\mathrm{R{-}C(=O){-}NR'R''}$.`,
    choiceExplanations: [
      `La liaison $\mathrm{C(=O){-}N}$ définit la fonction amide.`,
      `On obtient alors une amide non substituée de type $\mathrm{RCONH_2}$.`,
      `Cette possibilité donne un motif $\mathrm{RCONHR'}$.`,
      `L'oxygène du carbonyle est toujours présent.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formule $\mathrm{CH_3CONH_2}$ correspond :`,
    choices: [
      `�' une amide.`,
      `�' une molécule contenant un groupe carbonyle.`,
      `�' une amine dépourvue de carbonyle.`,
      `�' une fonction pouvant être retrouvée dans une liaison peptidique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le motif $\mathrm{-C(=O){-}NH_2}$ est celui d'une fonction amide.`,
    choiceExplanations: [
      `L'azote est directement lié au carbone carbonylé.`,
      `La liaison $\mathrm{C{=}O}$ est visible.`,
      `La présence du carbonyle distingue l'amide d'une amine simple.`,
      `La liaison peptidique est une liaison de type amide.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `On considère $\mathrm{RCONHCH_3}$. Concernant l'azote :`,
    choices: [
      `Il est directement lié au groupe carbonyle.`,
      `Il porte un radical méthyle.`,
      `Il porte encore un hydrogène.`,
      `Il s'agit d'un ammonium quaternaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Dans cette amide, l'azote porte un hydrogène et un radical méthyle en plus de sa liaison au carbonyle.`,
    choiceExplanations: [
      `La liaison $\mathrm{C(=O){-}N}$ est caractéristique.`,
      `Le groupe $\mathrm{CH_3}$ est lié à l'azote.`,
      `La notation $\mathrm{NH}$ l'indique.`,
      `L'azote n'a pas quatre substituants ni de charge positive.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La structure $\mathrm{RCON(CH_3)_2}$ :`,
    choices: [
      `Contient une fonction amide.`,
      `L'azote ne porte aucun hydrogène.`,
      `L'azote est lié à deux radicaux carbonés.`,
      `La molécule est nécessairement un ester.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Il s'agit d'une amide dont l'azote est disubstitué par deux groupes méthyle.`,
    choiceExplanations: [
      `Le motif $\mathrm{C(=O){-}N}$ est présent.`,
      `Ses deux substituants hors carbonyle sont des groupes méthyle.`,
      `Les deux groupes $\mathrm{CH_3}$ sont attachés à l'azote.`,
      `Un ester possède un oxygène, et non un azote, après le carbonyle.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les motifs suivants, lesquels contiennent une fonction ester ou amide ?`,
    choices: [
      `$\mathrm{R{-}C(=O){-}OR'}$ contient une fonction ester.`,
      `$\mathrm{R{-}C(=O){-}NHR'}$ contient une fonction amide.`,
      `$\mathrm{R{-}O{-}R'}$ est nécessairement un ester.`,
      `$\mathrm{R{-}NH_2}$ est nécessairement une amide.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Il faut rechercher respectivement les motifs $\mathrm{-COO-}$ et $\mathrm{-CON-}$.`,
    choiceExplanations: [
      `Le carbonyle est suivi d'un oxygène lié à un radical.`,
      `Le carbonyle est suivi d'un azote.`,
      `Sans carbonyle, il s'agit d'un éther.`,
      `Sans carbonyle adjacent, il s'agit d'une amine.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une molécule utilisée comme principe actif comporte le motif $\mathrm{-C(=O){-}NH-}$. Ce motif :`,
    choices: [
      `Est une fonction amide.`,
      `Peut être rencontré dans des peptides.`,
      `Est identique à une fonction alcool.`,
      `Contient à la fois un atome d'oxygène et un atome d'azote.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le motif $\mathrm{-CONH-}$ correspond à une amide et peut participer à une liaison peptidique.`,
    choiceExplanations: [
      `L'azote est directement lié au carbone carbonylé.`,
      `Les liaisons entre résidus d'acides aminés sont des amides.`,
      `Un alcool possède le groupe $\mathrm{-OH}$ sans carbonyle adjacent.`,
      `L'oxygène appartient au carbonyle et l'azote lui est lié.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Comparaison des fonctions ester et amide :`,
    choices: [
      `Toutes deux contiennent un groupe carbonyle.`,
      `Dans l'ester, le carbonyle est lié à un oxygène.`,
      `Dans l'amide, le carbonyle est lié à un azote.`,
      `Ester et amide ont toujours exactement la même réactivité.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les deux fonctions sont des dérivés carbonylés ; elles se distinguent par l'hétéroatome directement lié au carbone carbonylé.`,
    choiceExplanations: [
      `Le motif $\mathrm{C{=}O}$ est commun.`,
      `On retrouve le motif $\mathrm{-C(=O){-}O-}$.`,
      `On retrouve le motif $\mathrm{-C(=O){-}N-}$.`,
      `La nature de l'hétéroatome modifie fortement leurs propriétés et leur hydrolyse.`,
    ],
  },
  {
    order: 11,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans le cours, un acide carboxylique activé peut être :`,
    choices: [
      `Un chlorure d'acyle $\mathrm{RCOCl}$.`,
      `Un anhydride d'acide $\mathrm{RCO{-}O{-}COR'}$.`,
      `Un alcane $\mathrm{RH}$.`,
      `Un éther $\mathrm{ROR'}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les chlorures d'acyle et les anhydrides d'acide sont les deux formes activées citées.`,
    choiceExplanations: [
      `Le chlore constitue un groupe partant dans les réactions d'acylation.`,
      `Ce dérivé est également utilisé pour transférer un groupe acyle.`,
      `Un alcane ne comporte pas de fonction acide activée.`,
      `Un éther ne possède pas de groupe carbonyle activé.`,
    ],
  },
  {
    order: 12,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La préparation d'un ester selon la fiche repose sur le bilan :`,
    choices: [
      `Acide activé + alcool '�� ester.`,
      `Acide activé + amine '�� ester.`,
      `Le terme activation concerne la fonction acide carboxylique.`,
      `Le partenaire alcool apporte l'oxygène lié au radical $\mathrm{R'}$.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `L'acylation d'un alcool par un dérivé activé d'acide conduit à un ester.`,
    choiceExplanations: [
      `C'est le bilan de synthèse présenté.`,
      `Avec une amine, le produit attendu est une amide.`,
      `On rend le groupe acyle plus réactif.`,
      `Le fragment $\mathrm{-OR'}$ du produit provient de l'alcool.`,
    ],
  },
  {
    order: 13,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La préparation d'une amide selon la fiche repose sur le bilan :`,
    choices: [
      `Acide activé + amine '�� amide.`,
      `L'azote de l'amine se retrouve lié au carbone carbonylé.`,
      `Un alcool est indispensable à cette réaction.`,
      `Un chlorure d'acyle peut servir de réactif acylant.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Une amine réagit avec un acide activé pour former une amide.`,
    choiceExplanations: [
      `C'est la réaction d'amidification étudiée.`,
      `La nouvelle liaison $\mathrm{C(=O){-}N}$ définit l'amide.`,
      `Le nucléophile azoté est l'amine.`,
      `Il fait partie des acides activés cités.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On fait réagir $\mathrm{RCOCl}$ avec le méthanol $\mathrm{CH_3OH}$. Le produit organique attendu :`,
    choices: [
      `Possède une fonction ester.`,
      `Peut s'écrire $\mathrm{RCOOCH_3}$.`,
      `Possède nécessairement une fonction amide.`,
      `Résulte de la réaction d'un acide activé avec un alcool.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le méthanol fournit le groupe méthoxy et le chlorure d'acyle fournit le groupe acyle : le produit est $\mathrm{RCOOCH_3}$.`,
    choiceExplanations: [
      `Le motif final est $\mathrm{-COOCH_3}$.`,
      `Cette formule conserve le groupe acyle et le fragment méthoxy.`,
      `Aucun atome d'azote n'est introduit.`,
      `Le schéma correspond à l'estérification du cours.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On fait réagir $\mathrm{RCOCl}$ avec l'éthylamine $\mathrm{CH_3CH_2NH_2}$. Le produit organique attendu :`,
    choices: [
      `Possède une fonction amide.`,
      `Peut s'écrire $\mathrm{RCONHCH_2CH_3}$.`,
      `Est nécessairement un ester.`,
      `Contient une nouvelle liaison entre le carbone acyle et l'azote.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'éthylamine fournit l'azote et son groupe éthyle ; elle forme l'amide $\mathrm{RCONHCH_2CH_3}$.`,
    choiceExplanations: [
      `Le groupe carbonyle est directement lié à l'azote.`,
      `L'azote conserve un hydrogène et le radical éthyle.`,
      `Le partenaire nucléophile est une amine, pas un alcool.`,
      `Cette liaison constitue le motif amide.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un anhydride d'acide réagit avec un alcool dans une étape de synthèse pharmaceutique. �' propos de cette transformation :`,
    choices: [
      `L'anhydride joue le rôle d'acide activé.`,
      `L'alcool est converti en ester.`,
      `La réaction impose la formation d'une liaison $\mathrm{C{-}N}$.`,
      `Le produit contient le motif $\mathrm{-C(=O){-}O-}$.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'anhydride transfère un groupe acyle à l'oxygène de l'alcool et forme une fonction ester.`,
    choiceExplanations: [
      `Il est l'un des dérivés activés cités.`,
      `Son oxygène devient lié au groupe acyle.`,
      `Aucune amine n'est impliquée.`,
      `Ce motif est celui de l'ester.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un anhydride d'acide réagit avec une amine primaire. �' propos du produit recherché :`,
    choices: [
      `Il possède une fonction amide.`,
      `L'azote de l'amine est incorporé dans le produit.`,
      `Il possède obligatoirement deux fonctions ester.`,
      `L'anhydride constitue un acide activé.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'acylation d'une amine primaire par un anhydride conduit à une amide portant encore un hydrogène sur l'azote.`,
    choiceExplanations: [
      `Le motif $\mathrm{-CONH-}$ est formé.`,
      `Il devient directement lié au carbone carbonylé.`,
      `Le produit principal recherché est une amide.`,
      `Il permet la réaction d'amidification.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'expérience **I** :`,
    choices: [
      `Le produit possède une fonction ester.`,
      `Le produit peut s'écrire $\mathrm{CH_3COOCH_2CH_3}$.`,
      `L'éthanol apporte le fragment $\mathrm{-OCH_2CH_3}$.`,
      `Le produit est une amide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chlorure d'éthanoyle réagit avec l'éthanol pour donner l'éthanoate d'éthyle, qui est un ester.`,
    choiceExplanations: [
      `L'alcool est acylé par le chlorure d'acyle.`,
      `Le groupe éthanoyle et le groupe éthoxy sont réunis.`,
      `L'oxygène de l'alcool est conservé dans l'ester.`,
      `Aucun azote n'est présent.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'expérience **II** :`,
    choices: [
      `Le produit possède une fonction amide.`,
      `Le produit peut s'écrire $\mathrm{CH_3CONHCH_3}$.`,
      `La méthylamine apporte l'atome d'azote du produit.`,
      `Le produit est l'éthanoate de méthyle.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chlorure d'éthanoyle acyle la méthylamine pour former la N-méthyléthanamide.`,
    choiceExplanations: [
      `La nouvelle liaison unit le carbonyle à l'azote.`,
      `L'azote conserve un hydrogène et le groupe méthyle.`,
      `Cet azote devient celui de la fonction amide.`,
      `Ce dernier serait obtenu avec du méthanol, non avec la méthylamine.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison des expériences **I** et **II** :`,
    choices: [
      `Le chlorure d'éthanoyle est l'acide activé dans les deux cas.`,
      `L'expérience I forme une liaison acyle''�oxygène.`,
      `L'expérience II forme une liaison acyle''�azote.`,
      `Les deux expériences conduisent nécessairement au même produit.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le même groupe acyle est transféré ; la nature du nucléophile, alcool ou amine, détermine la fonction obtenue.`,
    choiceExplanations: [
      `Le réactif acylant est identique.`,
      `Cette liaison appartient à la fonction ester.`,
      `Cette liaison appartient à la fonction amide.`,
      `Les fonctions finales diffèrent selon le nucléophile.`,
    ],
  },
  {
    order: 21,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `�' propos de la liaison peptidique :`,
    choices: [
      `Elle comporte le motif $\mathrm{-C(=O){-}N-}$.`,
      `Elle est rencontrée dans les peptides et les protéines.`,
      `Elle correspond à une fonction ester.`,
      `Elle contient un groupe carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La liaison peptidique est une fonction amide reliant le carbonyle d'un résidu à l'azote du résidu suivant.`,
    choiceExplanations: [
      `Ce motif est celui d'une amide.`,
      `Elle assure l'enchaînement des résidus d'acides aminés.`,
      `L'hétéroatome lié au carbonyle est un azote, non un oxygène.`,
      `Le carbone de la liaison peptidique est carbonylé.`,
    ],
  },
  {
    order: 22,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans une amide de formule $\mathrm{RCONH_2}$ :`,
    choices: [
      `L'azote porte deux hydrogènes.`,
      `L'azote est directement lié au carbone du groupe $\mathrm{C{=}O}$.`,
      `La fonction est identique à une amine libre $\mathrm{RNH_2}$.`,
      `La molécule contient au moins un oxygène.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'azote est lié au carbone carbonylé et porte deux hydrogènes.`,
    choiceExplanations: [
      `La notation $\mathrm{NH_2}$ l'indique.`,
      `C'est la liaison caractéristique de l'amide.`,
      `Dans l'amide, l'azote est adjacent au carbonyle.`,
      `L'oxygène appartient au carbonyle.`,
    ],
  },
  {
    order: 23,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans une liaison peptidique usuelle de motif $\mathrm{-CONH-}$ :`,
    choices: [
      `L'azote peut porter un hydrogène.`,
      `L'azote est lié au carbone carbonylé.`,
      `Le motif ne contient aucun oxygène.`,
      `Le motif est de nature amide.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'azote porte un hydrogène et deux substituants lourds : le carbone carbonylé et le carbone du résidu suivant.`,
    choiceExplanations: [
      `Le motif $\mathrm{NH}$ est fréquent dans les peptides.`,
      `Cette liaison forme la fonction amide.`,
      `Le carbonyle fournit un oxygène.`,
      `Il s'agit de la fonction constitutive de la liaison peptidique.`,
    ],
  },
  {
    order: 24,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le résidu proline constitue un cas particulier dans un peptide parce que :`,
    choices: [
      `Son azote peut être intégré à un cycle.`,
      `L'azote peptidique correspondant peut être lié à trois atomes de carbone.`,
      `La proline peut provoquer une déformation de la chaîne.`,
      `La proline supprime toutes les fonctions amide du peptide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La chaîne latérale de la proline revient sur l'azote, ce qui peut rendre cet azote trisubstitué et influencer la géométrie locale.`,
    choiceExplanations: [
      `La chaîne latérale de la proline ferme un cycle avec l'azote.`,
      `Le carbonyle précédent, le carbone alpha et le cycle contribuent à cette substitution.`,
      `La fiche souligne son influence sur la structure secondaire.`,
      `Elle participe elle-même à une liaison peptidique de type amide.`,
    ],
  },
  {
    order: 25,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `�' propos des substituants portés par l'azote d'une amide :`,
    choices: [
      `Deux hydrogènes sont possibles.`,
      `Un hydrogène et un radical sont possibles.`,
      `Deux radicaux sont possibles.`,
      `L'azote doit toujours porter exactement deux hydrogènes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'azote peut porter deux hydrogènes, un hydrogène et un radical, ou deux radicaux, en plus de sa liaison au carbonyle.`,
    choiceExplanations: [
      `C'est le cas de $\mathrm{RCONH_2}$.`,
      `C'est le cas de $\mathrm{RCONHR'}$.`,
      `C'est le cas de $\mathrm{RCONR'R''}$.`,
      `Le degré de substitution de l'azote peut varier.`,
    ],
  },
  {
    order: 26,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une amide N,N-disubstituée $\mathrm{RCONR'R''}$ :`,
    choices: [
      `Possède une fonction amide.`,
      `Son azote porte deux radicaux $\mathrm{R'}$ et $\mathrm{R''}$.`,
      `Son azote ne porte pas d'hydrogène.`,
      `Elle est nécessairement un ammonium quaternaire chargé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Son azote porte deux radicaux en plus de sa liaison au carbone carbonylé et ne porte donc pas d'hydrogène.`,
    choiceExplanations: [
      `La liaison $\mathrm{C(=O){-}N}$ est présente.`,
      `La notation l'indique explicitement.`,
      `Les deux valences restantes sont occupées par les radicaux.`,
      `Une amide neutre n'a pas quatre substituants carbonés ni charge obligatoire.`,
    ],
  },
  {
    order: 27,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lorsqu'on repère un motif $\mathrm{-CO{-}NH-}$ dans une protéine :`,
    choices: [
      `Il s'agit d'une liaison peptidique.`,
      `Le carbone appartient à un groupe carbonyle.`,
      `L'azote est directement lié au carbonyle.`,
      `Le motif correspond à un simple éther.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ce motif correspond à une liaison amide, appelée liaison peptidique dans ce contexte biologique.`,
    choiceExplanations: [
      `Elle relie deux résidus d'acides aminés.`,
      `La notation $\mathrm{CO}$ représente $\mathrm{C{=}O}$.`,
      `C'est la signature d'une amide.`,
      `Un éther ne contient ni carbonyle ni azote.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant le premier azote du fragment :`,
    choices: [
      `Il appartient à une fonction amide.`,
      `Il porte un hydrogène.`,
      `Il est nécessairement lié à quatre carbones.`,
      `Il participe à une liaison peptidique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le premier azote est celui d'une liaison peptidique classique de motif $\mathrm{-CONH-}$.`,
    choiceExplanations: [
      `Il est relié au carbonyle du résidu précédent.`,
      `Cette donnée est précisée dans l'énoncé commun.`,
      `Il porte un hydrogène et n'est pas un ammonium quaternaire.`,
      `Le motif amide du peptide l'inclut.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'azote du résidu proline :`,
    choices: [
      `Il appartient au cycle de la proline.`,
      `Il est lié à trois atomes de carbone.`,
      `Il porte nécessairement un hydrogène.`,
      `Il participe néanmoins à une fonction amide.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Dans ce fragment, l'azote prolinique est trisubstitué par des atomes de carbone et ne porte pas d'hydrogène.`,
    choiceExplanations: [
      `La chaîne latérale cyclique revient sur l'azote.`,
      `Cette donnée figure dans l'énoncé.`,
      `Ses trois liaisons carbonées complètent sa substitution dans l'amide.`,
      `Il reste directement lié au carbone carbonylé précédent.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `�' propos de l'effet structural de la proline dans ce fragment :`,
    choices: [
      `Le cycle rigidifie localement le squelette.`,
      `La proline peut influencer la structure secondaire.`,
      `La présence de proline transforme toutes les amides en esters.`,
      `L'environnement de l'azote prolinique diffère de celui d'un motif $\mathrm{-CONH-}$ classique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La structure cyclique de la proline limite les conformations locales et peut déformer la chaîne peptidique.`,
    choiceExplanations: [
      `La fermeture du cycle réduit la liberté conformationnelle.`,
      `C'est le point biologique souligné dans la fiche.`,
      `La nature des liaisons peptidiques reste amide.`,
      `Il peut être trisubstitué et dépourvu d'hydrogène.`,
    ],
  },
];
