/** UE14 – Biologie cellulaire – Chapitre 5 — V2 active */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-2.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-2.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-2.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-2.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-2.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';
const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'systeme-endomembranaire-reticulum-endoplasmique-golgi-lysosomes';
const sections: SeedSection[] = [
  { order: 1, title: `Réticulum endoplasmique`, description: `Adressage au RE, translocation, maturation, contrôle qualité et fonctions spécialisées.`, kind: 'THEME' },
  { order: 2, title: `Appareil de Golgi`, description: `Organisation cis-trans, maturation, tri et exportation depuis le TGN.`, kind: 'THEME' },
  { order: 3, title: `Lysosomes`, description: `Hydrolases acides, adressage M6P, voies d’entrée, recyclage et pathologies lysosomales.`, kind: 'THEME' },
  { order: 4, title: `Flux et adressage`, description: `Transport vésiculaire, rétention, recyclage et signaux KDEL, KKXX et M6P.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Révision transversale du RE, du Golgi, des lysosomes et de leurs flux.`, kind: 'SYNTHESIS' },
];
const questions: SeedQuestion[] = [...SECTION_A_QUESTIONS, ...SECTION_B_QUESTIONS, ...SECTION_C_QUESTIONS, ...SECTION_D_QUESTIONS, ...SYNTHESIS_QUESTIONS];
const quizSeeds: SeedQuiz[] = [...SECTION_A_QUIZZES, ...SECTION_B_QUIZZES, ...SECTION_C_QUIZZES, ...SECTION_D_QUIZZES, ...SYNTHESIS_QUIZZES];
const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Réticulum endoplasmique`],
  2: [`Réticulum endoplasmique`],
  3: [`Réticulum endoplasmique`],
  4: [`Réticulum endoplasmique`],
  5: [`Réticulum endoplasmique`],
  6: [`Réticulum endoplasmique`],
  7: [`Réticulum endoplasmique`],
  8: [`Réticulum endoplasmique`],
  9: [`Réticulum endoplasmique`],
  10: [`Réticulum endoplasmique`],
  11: [`Réticulum endoplasmique`],
  12: [`Réticulum endoplasmique`],
  13: [`Réticulum endoplasmique`],
  14: [`Réticulum endoplasmique`],
  15: [`Réticulum endoplasmique`],
  16: [`Réticulum endoplasmique`],
  17: [`Réticulum endoplasmique`],
  18: [`Réticulum endoplasmique`],
  19: [`Réticulum endoplasmique`],
  20: [`Réticulum endoplasmique`],
  21: [`Réticulum endoplasmique`],
  22: [`Réticulum endoplasmique`],
  23: [`Appareil de Golgi`],
  24: [`Appareil de Golgi`],
  25: [`Appareil de Golgi`],
  26: [`Appareil de Golgi`],
  27: [`Appareil de Golgi`],
  28: [`Appareil de Golgi`],
  29: [`Appareil de Golgi`],
  30: [`Appareil de Golgi`],
  31: [`Appareil de Golgi`],
  32: [`Appareil de Golgi`],
  33: [`Appareil de Golgi`],
  34: [`Appareil de Golgi`],
  35: [`Appareil de Golgi`],
  36: [`Appareil de Golgi`],
  37: [`Appareil de Golgi`],
  38: [`Appareil de Golgi`],
  39: [`Appareil de Golgi`],
  40: [`Appareil de Golgi`],
  41: [`Appareil de Golgi`],
  42: [`Appareil de Golgi`],
  43: [`Appareil de Golgi`],
  44: [`Appareil de Golgi`],
  45: [`Lysosomes`],
  46: [`Lysosomes`],
  47: [`Lysosomes`],
  48: [`Lysosomes`],
  49: [`Lysosomes`],
  50: [`Lysosomes`],
  51: [`Lysosomes`],
  52: [`Lysosomes`],
  53: [`Lysosomes`],
  54: [`Lysosomes`],
  55: [`Lysosomes`],
  56: [`Lysosomes`],
  57: [`Lysosomes`],
  58: [`Lysosomes`],
  59: [`Lysosomes`],
  60: [`Lysosomes`],
  61: [`Lysosomes`],
  62: [`Lysosomes`],
  63: [`Lysosomes`],
  64: [`Lysosomes`],
  65: [`Lysosomes`],
  66: [`Lysosomes`],
  67: [`Flux et adressage`],
  68: [`Flux et adressage`],
  69: [`Flux et adressage`],
  70: [`Flux et adressage`],
  71: [`Flux et adressage`],
  72: [`Flux et adressage`],
  73: [`Flux et adressage`],
  74: [`Flux et adressage`],
  75: [`Flux et adressage`],
  76: [`Flux et adressage`],
  77: [`Flux et adressage`],
  78: [`Flux et adressage`],
  79: [`Flux et adressage`],
  80: [`Flux et adressage`],
  81: [`Flux et adressage`],
  82: [`Flux et adressage`],
  83: [`Flux et adressage`],
  84: [`Flux et adressage`],
  85: [`Flux et adressage`],
  86: [`Flux et adressage`],
  87: [`Flux et adressage`],
  88: [`Flux et adressage`],
  89: [`Flux et adressage`],
  90: [`Flux et adressage`],
  91: [`Flux et adressage`],
  92: [`Flux et adressage`],
  93: [`Flux et adressage`],
  94: [`Flux et adressage`],
  95: [`Flux et adressage`],
  96: [`Flux et adressage`],
  97: [`Flux et adressage`],
  98: [`Flux et adressage`],
  99: [`Flux et adressage`],
  100: [`Flux et adressage`],
  101: [`Synthèse du SEM`],
  102: [`Synthèse du SEM`],
  103: [`Synthèse du SEM`],
  104: [`Synthèse du SEM`],
  105: [`Synthèse du SEM`],
  106: [`Synthèse du SEM`],
  107: [`Synthèse du SEM`],
  108: [`Synthèse du SEM`],
  109: [`Synthèse du SEM`],
  110: [`Synthèse du SEM`],
  111: [`Synthèse du SEM`],
  112: [`Synthèse du SEM`],
  113: [`Synthèse du SEM`],
  114: [`Synthèse du SEM`],
  115: [`Synthèse du SEM`],
  116: [`Synthèse du SEM`],
  117: [`Synthèse du SEM`],
  118: [`Synthèse du SEM`],
  119: [`Synthèse du SEM`],
  120: [`Synthèse du SEM`],
  121: [`Synthèse du SEM`],
  122: [`Synthèse du SEM`],
};
export async function seedHealthTrainingUe14BiologieCellulaireSystemeEndomembranaire2(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 5',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
    purgeObsoleteQuestions: true,
  });
}
