import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_ORDER = 2;

export const SECTION_B_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  31: ["Définition des polyosides"],
  32: ["Homoglycanes et hétéroglycanes"],
  33: ["Composition de l’amidon"],
  34: ["Structure de l’amylose"],
  35: ["Conformation de l’amylose"],
  36: ["Structure de l’amylopectine"],
  37: ["Ramification de l’amylopectine"],
  38: ["Rôle végétal de l’amidon"],
  39: ["Importance alimentaire de l’amidon"],
  40: ["Propriétés physiques de l’amidon"],
  41: ["Gélification de l’amidon"],
  42: ["Hydrolyse digestive de l’amidon"],
  43: ["Produits de digestion de l’amidon"],
  44: ["Rôle du glycogène"],
  45: ["Glycogène neuronal"],
  46: ["Glycogénine"],
  47: ["Comparaison glycogène-amylopectine"],
  48: ["Granules et branches du glycogène"],
  49: ["Fréquence des embranchements du glycogène"],
  50: ["Architecture comparée des réserves"],
  51: ["Réserves végétale et animale"],
  52: ["Réserve musculaire"],
  53: ["Réserve hépatique"],
  54: ["Origine biologique des glucanes"],
  55: ["Liaison de branchement"],
  56: ["Liaison des chaînes principales"],
  57: ["Amylose et ramifications"],
  58: ["Chauffage de l’amidon"],
  59: ["Enzyme débranchante"],
  60: ["Synthèse sur les glucanes de réserve"],
};

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "polyosides-et-amidon",
    title: "Polyosides et amidon",
    description: "Distinguer homoglycanes et hétéroglycanes puis décrire l’amidon.",
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 2,
    slug: "digestion-et-glycogene",
    title: "Digestion de l’amidon et glycogène",
    description: "Relier les liaisons, les enzymes et la structure du glycogène.",
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 3,
    slug: "comparaison-des-glucanes-de-reserve",
    title: "Comparaison des glucanes de réserve",
    description: "Comparer les réserves végétales et animales et raisonner sur leurs liaisons.",
    stage: 'MASTER',
    sectionOrder: 2,
    items: [
      {
        type: 'GROUP',
        title: "Réserves et tissus",
        sharedStatement: "Les questions suivantes comparent les formes de réserve et leur localisation.",
        questionOrders: [51, 52, 53, 54],
      },
      {
        type: 'GROUP',
        title: "Liaisons et architecture",
        sharedStatement: "Les questions suivantes portent sur les chaînes principales et les embranchements.",
        questionOrders: [55, 56, 57],
      },
      {
        type: 'GROUP',
        title: "Propriétés et digestion",
        sharedStatement: "Les questions suivantes mobilisent gélification, enzymes et synthèse.",
        questionOrders: [58, 59, 60],
      },
    ],
  },
];

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les polyosides ou glycanes :",
    choices: [
      "Résultent de la polymérisation d’un grand nombre d’oses ou de dérivés d’oses.",
      "Peuvent avoir un rôle structural.",
      "Peuvent avoir un rôle de réserve.",
      "Sont toujours constitués d’un seul type d’ose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les polyosides sont de longues chaînes glucidiques dont les rôles peuvent être structuraux ou de réserve.",
    choiceExplanations: [
      "Vrai. C’est leur définition générale.",
      "Vrai. La cellulose en est un exemple.",
      "Vrai. L’amidon et le glycogène en sont des exemples.",
      "Faux. Les hétéroglycanes contiennent plusieurs types de résidus.",
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant les polyosides :",
    choices: [
      "Un homoglycane répète le même type d’ose.",
      "Un hétéroglycane contient plusieurs types d’oses ou de dérivés.",
      "Un polyholoside homogène est synonyme d’homoglycane.",
      "Un hétéroglycane ne peut jamais contenir d’acide uronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La distinction repose sur l’homogénéité ou l’hétérogénéité des résidus répétés.",
    choiceExplanations: [
      "Vrai. Un seul type d’unité est répété.",
      "Vrai. Plusieurs types de résidus sont présents.",
      "Vrai. Les deux termes sont rapprochés dans la fiche.",
      "Faux. Les GAG contiennent fréquemment un acide uronique.",
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’amidon est constitué approximativement de :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "20 % d’amylose.",
      "80 % d’amylopectine.",
      "80 % de cellulose.",
      "Deux fractions glucidiques aux structures différentes.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La fiche présente l’amidon comme un mélange d’environ 20 % d’amylose et 80 % d’amylopectine.",
    choiceExplanations: [
      "Vrai. C’est la proportion indiquée.",
      "Vrai. C’est la fraction majoritaire.",
      "Faux. La cellulose est un autre homoglycane végétal.",
      "Vrai. L’une est linéaire, l’autre ramifiée.",
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos de l’amylose :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "Elle forme une très longue chaîne linéaire de glucose.",
      "Elle contient habituellement 200 à 600 résidus, parfois jusqu’à 20 000.",
      "Elle est fortement ramifiée tous les six glucoses.",
      "Ses résidus sont unis par des liaisons α(1→4).",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’amylose est la fraction linéaire de l’amidon, faite de glucoses liés en α(1→4).",
    choiceExplanations: [
      "Vrai. C’est sa caractéristique principale.",
      "Vrai. Ces ordres de grandeur figurent dans la fiche.",
      "Faux. Cette description concerne l’amylopectine.",
      "Vrai. La chaîne est α1,4.",
    ],
  },
  {
    order: 35,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans l’espace, l’amylose :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "Adopte un enroulement hélicoïdal.",
      "Présente environ 6 à 8 glucoses par tour de spirale.",
      "Est décrite comme un réseau β(1→4) rectiligne.",
      "Reste une chaîne non ramifiée.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La chaîne α(1→4) de l’amylose s’enroule en hélice sans ramifications.",
    choiceExplanations: [
      "Vrai. C’est la conformation indiquée.",
      "Vrai. Cet ordre de grandeur est précisé.",
      "Faux. La liaison β1,4 caractérise la cellulose.",
      "Vrai. L’amylose est linéaire.",
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’amylopectine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "Possède des chaînes principales liées en α(1→4).",
      "Présente des embranchements en α(1→6).",
      "Est totalement linéaire.",
      "Comporte des segments d’environ 20 à 25 résidus dans la description donnée.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’amylopectine est une structure ramifiée combinant liaisons α1,4 et α1,6.",
    choiceExplanations: [
      "Vrai. Les segments linéaires sont α1,4.",
      "Vrai. Les points de branchement sont α1,6.",
      "Faux. Elle est ramifiée.",
      "Vrai. La fiche donne cette longueur pour les chaînes.",
    ],
  },
  {
    order: 37,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Selon la fiche, l’amylopectine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "A un aspect buissonnant.",
      "Est très ramifiée et dense.",
      "Présente environ un embranchement tous les six glucoses.",
      "Ne possède aucune liaison α(1→6).",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La forte ramification en α1,6 donne à l’amylopectine son aspect dense et buissonnant.",
    choiceExplanations: [
      "Vrai. C’est le terme utilisé.",
      "Vrai. La densité résulte des branches.",
      "Vrai. Cette fréquence est indiquée.",
      "Faux. Les liaisons α1,6 constituent les embranchements.",
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’amidon :",
    choices: [
      "Est un polyoside de réserve des végétaux.",
      "Peut représenter jusqu’à 60 % de la masse sèche végétale.",
      "Est synthétisé dans les amyloplastes.",
      "Est la principale réserve animale.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’amidon est la réserve glucidique végétale, synthétisée dans les amyloplastes.",
    choiceExplanations: [
      "Vrai. C’est son rôle majeur.",
      "Vrai. Cette valeur est donnée.",
      "Vrai. Ce compartiment végétal est cité.",
      "Faux. La réserve animale est le glycogène.",
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos de l’amidon alimentaire :",
    choices: [
      "Il représente environ 50 % de l’apport glucidique chez l’Homme selon la fiche.",
      "Il est retrouvé dans les céréales.",
      "Il est retrouvé dans les féculents.",
      "Il est absent du riz et du blé.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’amidon constitue une part importante des apports glucidiques et se trouve notamment dans les céréales et féculents.",
    choiceExplanations: [
      "Vrai. Cette proportion est indiquée.",
      "Vrai. Le blé et le riz sont cités.",
      "Vrai. Les féculents en sont riches.",
      "Faux. Ces céréales sont des exemples donnés.",
    ],
  },
  {
    order: 40,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’amidon est décrit comme :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "Hydrophile.",
      "Insoluble dans l’eau froide.",
      "Toujours très soluble à froid.",
      "Capable de former un gel épais lorsqu’il est chauffé.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’amidon attire l’eau mais ne se dissout pas à froid ; la chaleur favorise la gélification.",
    choiceExplanations: [
      "Vrai. Il interagit avec l’eau.",
      "Vrai. Cette propriété est explicitement indiquée.",
      "Faux. Elle contredit le cours.",
      "Vrai. Les chaînes se déroulent et piègent l’eau.",
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Lors du chauffage de l’amidon dans l’eau :",
    choices: [
      "Les chaînes se déroulent.",
      "Un réseau réticulé peut piéger l’eau.",
      "Un gel épais peut se former.",
      "Les chaînes deviennent obligatoirement des protéines.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La chaleur déploie les chaînes et permet la formation d’un réseau qui retient l’eau.",
    choiceExplanations: [
      "Vrai. C’est la première étape décrite.",
      "Vrai. Ce réseau explique la texture.",
      "Vrai. C’est la conséquence macroscopique.",
      "Faux. La nature glucidique ne change pas.",
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La digestion de l’amidon fait intervenir :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "Des α-amylases.",
      "Une activité α(1→4)-glucosidase.",
      "Une enzyme débranchante α(1→6)-glucosidase.",
      "Exclusivement une β-glucosidase.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les liaisons α1,4 et les embranchements α1,6 nécessitent des activités enzymatiques adaptées.",
    choiceExplanations: [
      "Vrai. Les amylases salivaire et pancréatique sont citées.",
      "Vrai. Cette activité hydrolyse la chaîne.",
      "Vrai. Elle traite les points de branchement.",
      "Faux. La β-glucosidase concerne notamment la cellulose.",
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans le schéma digestif donné :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "L’amidon peut être hydrolysé en maltose.",
      "Le maltose peut ensuite donner deux glucoses.",
      "La maltase intervient après l’amylase.",
      "L’amidon donne directement du galactose uniquement.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La digestion progresse de l’amidon vers le maltose puis vers le glucose.",
    choiceExplanations: [
      "Vrai. C’est l’intermédiaire représenté.",
      "Vrai. Le maltose est un diglucoside.",
      "Vrai. Elle hydrolyse le maltose.",
      "Faux. Le galactose n’est pas le monomère de l’amidon.",
    ],
  },
  {
    order: 44,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le glycogène :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycogen-branching',
    },
    choices: [
      "Est un polyoside de réserve des cellules animales.",
      "Est présent dans toutes les cellules selon la fiche.",
      "Est particulièrement abondant dans les cellules musculaires et hépatiques.",
      "Est la réserve glucidique spécifique des végétaux.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glycogène est la réserve animale, largement distribuée mais enrichie dans le muscle et le foie.",
    choiceExplanations: [
      "Vrai. C’est son rôle.",
      "Vrai. La fiche emploie cette formulation.",
      "Vrai. Ces deux tissus sont mis en avant.",
      "Faux. La réserve végétale est l’amidon.",
    ],
  },
  {
    order: 45,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant la distribution du glycogène :",
    choices: [
      "Il est très peu abondant dans les neurones.",
      "Il est plus abondant dans le muscle et le foie.",
      "Il est totalement absent de toutes les cellules animales.",
      "Sa distribution est identique dans tous les tissus.",
    ],
    correctChoiceIndexes: [0, 1],
    explanation: "La quantité de glycogène varie selon les tissus ; les neurones en contiennent très peu.",
    choiceExplanations: [
      "Vrai. C’est précisé dans la fiche.",
      "Vrai. Ce sont les principaux sites mentionnés.",
      "Faux. Il est présent dans les cellules animales.",
      "Faux. Les abondances diffèrent.",
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La glycogénine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycogen-branching',
    },
    choices: [
      "Est une protéine à laquelle les chaînes de glycogène sont fixées.",
      "Participe à l’organisation du glycogène.",
      "Est un diholoside constitué de fructose.",
      "Est citée dans la structure du glycogène.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le glycogène est construit autour d’une protéine appelée glycogénine.",
    choiceExplanations: [
      "Vrai. C’est la relation indiquée.",
      "Vrai. Elle sert de support à la structure.",
      "Faux. Il s’agit d’une protéine.",
      "Vrai. La fiche la nomme explicitement.",
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le glycogène et l’amylopectine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycogen-branching',
    },
    choices: [
      "Ont tous deux une structure ramifiée.",
      "Associent des liaisons α(1→4) et des embranchements α(1→6).",
      "Sont identiques par leur degré de ramification.",
      "Sont des réserves glucidiques dans des règnes différents.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Leurs architectures sont proches, mais le glycogène présente une ramification particulière et appartient aux animaux.",
    choiceExplanations: [
      "Vrai. Les deux sont ramifiés.",
      "Vrai. Ils partagent ces types de liaisons.",
      "Faux. Le glycogène est décrit avec des branches plus courtes et une organisation différente.",
      "Vrai. Amylopectine végétale, glycogène animal.",
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Selon la fiche, le glycogène :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycogen-branching',
    },
    choices: [
      "Possède des ramifications plus courtes que l’amylopectine.",
      "Est stocké dans des grains plus petits.",
      "Forme des grains d’environ 0,1 µm.",
      "Est une longue chaîne strictement linéaire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glycogène est une structure compacte faite de branches courtes et de petits grains.",
    choiceExplanations: [
      "Vrai. La comparaison est explicite.",
      "Vrai. C’est indiqué.",
      "Vrai. Cet ordre de grandeur est donné.",
      "Faux. Il est fortement ramifié.",
    ],
  },
  {
    order: 49,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Les embranchements du glycogène sont décrits :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycogen-branching',
    },
    choices: [
      "En moyenne tous les 8 à 12 glucoses.",
      "Tous les 3 à 5 glucoses au centre de la molécule.",
      "Uniquement tous les 1000 glucoses.",
      "Comme des liaisons α(1→6).",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le glycogène présente des embranchements fréquents, particulièrement au centre.",
    choiceExplanations: [
      "Vrai. C’est la fréquence générale indiquée.",
      "Vrai. Le centre est encore plus dense.",
      "Faux. Cette valeur est incompatible avec la fiche.",
      "Vrai. Les points de branchement des glucanes de réserve sont α1,6.",
    ],
  },
  {
    order: 50,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Comparer amylose, amylopectine et glycogène permet d’affirmer que :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "L’amylose est linéaire.",
      "L’amylopectine est ramifiée.",
      "Le glycogène est ramifié et associé à la glycogénine.",
      "Les trois sont liés exclusivement par des liaisons β(1→4).",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les trois glucanes diffèrent par leur degré de ramification mais reposent sur des liaisons α.",
    choiceExplanations: [
      "Vrai. Elle ne comporte pas de branches.",
      "Vrai. Elle contient des points α1,6.",
      "Vrai. Cette protéine est spécifique au glycogène décrit.",
      "Faux. Les liaisons sont principalement α1,4 et α1,6.",
    ],
  },
  {
    order: 51,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les associations correctes :",
    choices: [
      "Amidon — réserve végétale.",
      "Glycogène — réserve animale.",
      "Cellulose — réserve animale majeure.",
      "Amylopectine — fraction ramifiée de l’amidon.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’amidon et le glycogène sont des réserves ; la cellulose a un rôle structural.",
    choiceExplanations: [
      "Vrai. C’est le stockage glucidique des végétaux.",
      "Vrai. C’est le stockage glucidique animal.",
      "Faux. La cellulose est un polyoside structural végétal.",
      "Vrai. Elle représente environ 80 % de l’amidon.",
    ],
  },
  {
    order: 52,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Dans une cellule musculaire, la forme de réserve glucidique citée dans la fiche est principalement :",
    choices: [
      "Le glycogène.",
      "L’amidon.",
      "La cellulose.",
      "Le saccharose cristallisé.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Le muscle est l’un des tissus où le glycogène est particulièrement abondant.",
    choiceExplanations: [
      "C’est la réponse attendue.",
      "L’amidon est végétal.",
      "La cellulose est structurale et végétale.",
      "Le saccharose n’est pas la réserve cellulaire décrite.",
    ],
  },
  {
    order: 53,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos du foie dans ce chapitre :",
    choices: [
      "Les cellules hépatiques sont riches en glycogène.",
      "Le glycogène y constitue une forme de réserve.",
      "La fiche le présente comme un site majeur de cellulose.",
      "Le foie est associé à une réserve glucidique animale.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le foie figure avec le muscle parmi les tissus riches en glycogène.",
    choiceExplanations: [
      "Vrai. Les hépatocytes sont cités parmi les cellules abondantes en glycogène.",
      "Vrai. C’est le rôle du glycogène.",
      "Faux. La cellulose est végétale.",
      "Vrai. Le glycogène est le polyoside animal.",
    ],
  },
  {
    order: 54,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les propositions suivantes :",
    choices: [
      "L’amidon est d’origine végétale.",
      "Le glycogène est associé aux cellules animales.",
      "L’amylose est une fraction de l’amidon.",
      "La glycogénine est une fraction majoritaire de l’amidon.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux grandes réserves se distinguent par leur origine biologique et leur organisation.",
    choiceExplanations: [
      "Vrai. Il est synthétisé dans les amyloplastes.",
      "Vrai. C’est le polyoside de réserve animal.",
      "Vrai. Elle représente environ 20 %.",
      "Faux. La glycogénine est une protéine associée au glycogène.",
    ],
  },
  {
    order: 55,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans l’amylopectine et le glycogène, les points de branchement correspondent à des liaisons :",
    choices: [
      "α(1→6).",
      "α(1→4) uniquement.",
      "β(1→4).",
      "Différentes des liaisons principales α(1→4).",
    ],
    correctChoiceIndexes: [0, 3],
    explanation: "Les chaînes principales sont α1,4 et les embranchements sont α1,6.",
    choiceExplanations: [
      "Vrai. C’est la liaison de branchement.",
      "Faux. α1,4 forme les segments linéaires.",
      "Faux. β1,4 caractérise la cellulose.",
      "Vrai. Les deux types de liaison ont des fonctions structurales différentes.",
    ],
  },
  {
    order: 56,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les segments linéaires de l’amylose, de l’amylopectine et du glycogène reposent principalement sur :",
    choices: [
      "Des liaisons α(1→4).",
      "Des liaisons β(1→4).",
      "Des résidus de glucose.",
      "Des liaisons peptidiques.",
    ],
    correctChoiceIndexes: [0, 2],
    explanation: "Ces glucanes sont des polymères de glucose à chaîne principale α1,4.",
    choiceExplanations: [
      "Vrai. C’est la liaison principale.",
      "Faux. Elle caractérise la cellulose.",
      "Vrai. Le glucose est leur monomère.",
      "Faux. Une liaison peptidique unit des acides aminés.",
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une chaîne composée uniquement de glucoses liés en α(1→4), sans embranchement, évoque :",
    choices: [
      "L’amylose.",
      "Une fraction de l’amidon.",
      "La cellulose.",
      "Une chaîne hélicoïdale possible.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’amylose est le glucane linéaire α1,4 de l’amidon et adopte une hélice.",
    choiceExplanations: [
      "Vrai. C’est sa définition.",
      "Vrai. Elle représente environ 20 % de l’amidon.",
      "Faux. La cellulose est β1,4.",
      "Vrai. La fiche décrit cet enroulement.",
    ],
  },
  {
    order: 58,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le chauffage d’une suspension d’amidon peut :",
    choices: [
      "Favoriser le déroulement des chaînes.",
      "Permettre la formation d’un réseau retenant l’eau.",
      "Épaissir le milieu.",
      "Transformer obligatoirement le glucose en galactose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La gélification explique l’épaississement de l’amidon chauffé en présence d’eau.",
    choiceExplanations: [
      "Vrai. La chaleur modifie la conformation des chaînes.",
      "Vrai. Le réseau piège l’eau.",
      "Vrai. Le gel devient épais.",
      "Faux. Il ne s’agit pas d’une épimérisation.",
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une enzyme débranchante de l’amidon doit reconnaître principalement :",
    choices: [
      "Les liaisons α(1→6).",
      "Les points de ramification de l’amylopectine.",
      "Les liaisons β(1→4) de la cellulose.",
      "Une structure différente des segments α(1→4).",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les branches de l’amylopectine nécessitent une activité α1,6-glucosidase.",
    choiceExplanations: [
      "Vrai. C’est la liaison ciblée.",
      "Vrai. Ces points empêchent une hydrolyse complète par la seule amylase.",
      "Faux. Cette liaison relève de la cellulose.",
      "Vrai. Les points α1,6 sont distincts des chaînes principales.",
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une synthèse correcte des glucanes de réserve comprend :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycogen-branching',
    },
    choices: [
      "L’amidon contient amylose et amylopectine.",
      "Le glycogène est une réserve animale ramifiée.",
      "Les points de branchement sont de type α(1→6).",
      "L’amylose est plus ramifiée que le glycogène.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Amidon et glycogène partagent une charpente α1,4, avec des branches α1,6 pour l’amylopectine et le glycogène.",
    choiceExplanations: [
      "Vrai. Ce sont ses deux fractions.",
      "Vrai. Il est particulièrement abondant dans le foie et le muscle.",
      "Vrai. C’est la liaison de branchement.",
      "Faux. L’amylose est linéaire.",
    ],
  },
];
