/**
 * UE14 – Biologie cellulaire – Chapitre 9 : Le cycle cellulaire
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le contrôle moléculaire du cycle repose notamment sur :`,
    choices: [
      `Les cyclines.`,
      `Les CDK.`,
      `Des complexes cycline/CDK.`,
      `Une activité cyclique identique de toutes les protéines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les transitions résultent de complexes spécifiques dont l’activité varie au cours du cycle.`,
    choiceExplanations: [
      `Exact. Les transitions résultent de complexes spécifiques dont l’activité varie au cours du cycle.`,
      `Exact. Les transitions résultent de complexes spécifiques dont l’activité varie au cours du cycle.`,
      `Exact. Les transitions résultent de complexes spécifiques dont l’activité varie au cours du cycle.`,
      `Faux. Les transitions résultent de complexes spécifiques dont l’activité varie au cours du cycle.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les cyclines :`,
    choices: [
      `Sont synthétisées puis dégradées au cours du cycle.`,
      `Ont une expression variable selon les phases.`,
      `Restent toujours à concentration constante.`,
      `Comprennent notamment les cyclines A, B, D et E.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La variation d’expression des cyclines contraste avec la relative stabilité des CDK.`,
    choiceExplanations: [
      `Exact. La variation d’expression des cyclines contraste avec la relative stabilité des CDK.`,
      `Exact. La variation d’expression des cyclines contraste avec la relative stabilité des CDK.`,
      `Faux. La variation d’expression des cyclines contraste avec la relative stabilité des CDK.`,
      `Exact. La variation d’expression des cyclines contraste avec la relative stabilité des CDK.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les CDK :`,
    choices: [
      `Sont des kinases dépendantes des cyclines.`,
      `Sont globalement présentes de façon stable.`,
      `Ne deviennent actives qu’après association à leur cycline spécifique.`,
      `Sont toutes détruites à chaque transition.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les CDK restent présentes mais leur activité dépend de leur association et de leur état de phosphorylation.`,
    choiceExplanations: [
      `Exact. Les CDK restent présentes mais leur activité dépend de leur association et de leur état de phosphorylation.`,
      `Exact. Les CDK restent présentes mais leur activité dépend de leur association et de leur état de phosphorylation.`,
      `Exact. Les CDK restent présentes mais leur activité dépend de leur association et de leur état de phosphorylation.`,
      `Faux. Les CDK restent présentes mais leur activité dépend de leur association et de leur état de phosphorylation.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une kinase :`,
    choices: [
      `Catalyse le transfert d’un groupe phosphoryle.`,
      `Peut modifier l’activité de protéines cibles.`,
      `Est toujours une phosphatase.`,
      `Intervient dans la cascade du cycle cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les CDK sont des kinases, distinctes des phosphatases comme cdc25.`,
    choiceExplanations: [
      `Exact. Les CDK sont des kinases, distinctes des phosphatases comme cdc25.`,
      `Exact. Les CDK sont des kinases, distinctes des phosphatases comme cdc25.`,
      `Faux. Les CDK sont des kinases, distinctes des phosphatases comme cdc25.`,
      `Exact. Les CDK sont des kinases, distinctes des phosphatases comme cdc25.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La synthèse de la cycline D :`,
    choices: [
      `Répond à un stimulus extracellulaire.`,
      `Peut être déclenchée par un facteur de croissance.`,
      `Implique le facteur de transcription Myc.`,
      `Est indépendante de tout récepteur membranaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le facteur de croissance active une signalisation conduisant à l’expression du gène de la cycline D.`,
    choiceExplanations: [
      `Exact. Le facteur de croissance active une signalisation conduisant à l’expression du gène de la cycline D.`,
      `Exact. Le facteur de croissance active une signalisation conduisant à l’expression du gène de la cycline D.`,
      `Exact. Le facteur de croissance active une signalisation conduisant à l’expression du gène de la cycline D.`,
      `Faux. Le facteur de croissance active une signalisation conduisant à l’expression du gène de la cycline D.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Myc, dans le mécanisme présenté :`,
    choices: [
      `Est activé par une transduction du signal.`,
      `Entre dans le noyau par les pores nucléaires.`,
      `Se fixe sur le promoteur du gène de la cycline D.`,
      `Dégrade directement la cycline D.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Myc agit comme facteur de transcription favorisant la production de cycline D.`,
    choiceExplanations: [
      `Exact. Myc agit comme facteur de transcription favorisant la production de cycline D.`,
      `Exact. Myc agit comme facteur de transcription favorisant la production de cycline D.`,
      `Exact. Myc agit comme facteur de transcription favorisant la production de cycline D.`,
      `Faux. Myc agit comme facteur de transcription favorisant la production de cycline D.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le complexe cycline D/CDK4-6 :`,
    choices: [
      `Favorise l’entrée et la progression en G1.`,
      `Est induit par les facteurs de croissance.`,
      `Est le MPF.`,
      `Phosphoryle des protéines favorisant l’expression de cycline E et E2F.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le MPF correspond au complexe cycline B/CDK1.`,
    choiceExplanations: [
      `Exact. Le MPF correspond au complexe cycline B/CDK1.`,
      `Exact. Le MPF correspond au complexe cycline B/CDK1.`,
      `Faux. Le MPF correspond au complexe cycline B/CDK1.`,
      `Exact. Le MPF correspond au complexe cycline B/CDK1.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La transition G1-S dépend notamment :`,
    choices: [
      `Du complexe cycline E/CDK2.`,
      `De la dégradation de la cycline D.`,
      `Du complexe cycline B/CDK1.`,
      `De l’activation de facteurs permettant l’entrée en S.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le complexe cycline B/CDK1 intervient à la transition G2-M.`,
    choiceExplanations: [
      `Exact. Le complexe cycline B/CDK1 intervient à la transition G2-M.`,
      `Exact. Le complexe cycline B/CDK1 intervient à la transition G2-M.`,
      `Faux. Le complexe cycline B/CDK1 intervient à la transition G2-M.`,
      `Exact. Le complexe cycline B/CDK1 intervient à la transition G2-M.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En phase S :`,
    choices: [
      `La cycline A s’associe à CDK2.`,
      `Le complexe A/CDK2 favorise la réplication de l’ADN.`,
      `Le centrosome peut être dupliqué.`,
      `La cycline E est maintenue à son maximum jusqu’à la fin de M.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cycline E est dégradée pendant la phase S.`,
    choiceExplanations: [
      `Exact. La cycline E est dégradée pendant la phase S.`,
      `Exact. La cycline E est dégradée pendant la phase S.`,
      `Exact. La cycline E est dégradée pendant la phase S.`,
      `Faux. La cycline E est dégradée pendant la phase S.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En phase G2 :`,
    choices: [
      `La cycline B s’associe à CDK1.`,
      `Le complexe cycline B/CDK1 forme le MPF.`,
      `La cycline A est dégradée.`,
      `Le complexe cycline D/CDK4-6 déclenche directement la destruction de l’enveloppe nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La transition G2-M dépend du MPF, non du complexe D/CDK4-6.`,
    choiceExplanations: [
      `Exact. La transition G2-M dépend du MPF, non du complexe D/CDK4-6.`,
      `Exact. La transition G2-M dépend du MPF, non du complexe D/CDK4-6.`,
      `Exact. La transition G2-M dépend du MPF, non du complexe D/CDK4-6.`,
      `Faux. La transition G2-M dépend du MPF, non du complexe D/CDK4-6.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Cyclines et CDK](/images/training/ue14/biologie-cellulaire/cycle-cellulaire/cyclines-cdk.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `La cycline D prédomine en G1.`,
      `La cycline E est liée à la transition G1-S.`,
      `La cycline B culmine à l’entrée en mitose.`,
      `Les CDK disparaissent complètement entre chaque phase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les CDK sont relativement stables ; ce sont les cyclines qui oscillent fortement.`,
    choiceExplanations: [
      `Exact. Les CDK sont relativement stables ; ce sont les cyclines qui oscillent fortement.`,
      `Exact. Les CDK sont relativement stables ; ce sont les cyclines qui oscillent fortement.`,
      `Exact. Les CDK sont relativement stables ; ce sont les cyclines qui oscillent fortement.`,
      `Faux. Les CDK sont relativement stables ; ce sont les cyclines qui oscillent fortement.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le complexe cycline A/CDK2 permet :`,
    choices: [
      `La réplication de l’ADN.`,
      `La duplication du centrosome.`,
      `La transition métaphase-anaphase par destruction de la sécurine.`,
      `La progression de la phase S.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La destruction de la sécurine dépend du complexe APC/cdc20.`,
    choiceExplanations: [
      `Exact. La destruction de la sécurine dépend du complexe APC/cdc20.`,
      `Exact. La destruction de la sécurine dépend du complexe APC/cdc20.`,
      `Faux. La destruction de la sécurine dépend du complexe APC/cdc20.`,
      `Exact. La destruction de la sécurine dépend du complexe APC/cdc20.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En fin de phase S, le complexe cycline A/CDK1 :`,
    choices: [
      `Empêche une nouvelle réplication de l’ADN.`,
      `Contribue à assurer l’unicité de la phase S.`,
      `Est identique au complexe cycline E/CDK2.`,
      `Précède l’accumulation du complexe B/CDK1.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La cycline A change de partenaire CDK au cours de la progression S-G2.`,
    choiceExplanations: [
      `Exact. La cycline A change de partenaire CDK au cours de la progression S-G2.`,
      `Exact. La cycline A change de partenaire CDK au cours de la progression S-G2.`,
      `Faux. La cycline A change de partenaire CDK au cours de la progression S-G2.`,
      `Exact. La cycline A change de partenaire CDK au cours de la progression S-G2.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le MPF activé initie notamment :`,
    choices: [
      `L’assemblage du fuseau mitotique.`,
      `La destruction de l’enveloppe nucléaire.`,
      `La condensation des chromosomes.`,
      `La réplication de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réplication a lieu avant l’activation du MPF, pendant S.`,
    choiceExplanations: [
      `Exact. La réplication a lieu avant l’activation du MPF, pendant S.`,
      `Exact. La réplication a lieu avant l’activation du MPF, pendant S.`,
      `Exact. La réplication a lieu avant l’activation du MPF, pendant S.`,
      `Faux. La réplication a lieu avant l’activation du MPF, pendant S.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Quel complexe correspond au M-phase promoting factor ?`,
    choices: [
      `Cycline D/CDK4.`,
      `Cycline E/CDK2.`,
      `Cycline A/CDK2.`,
      `Cycline B/CDK1.`,
    ],
    correctChoiceIndexes: [3],
    explanation: `Le complexe B/CDK1 permet la transition G2-M.`,
    choiceExplanations: [
      `Faux. Le complexe B/CDK1 permet la transition G2-M.`,
      `Faux. Le complexe B/CDK1 permet la transition G2-M.`,
      `Faux. Le complexe B/CDK1 permet la transition G2-M.`,
      `Exact. Le complexe B/CDK1 permet la transition G2-M.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La succession correcte des complexes comprend :`,
    choices: [
      `D/CDK4-6 en G1.`,
      `E/CDK2 à G1-S.`,
      `A/CDK2 pendant S.`,
      `B/CDK1 à G2-M.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Chaque transition mobilise un couple cycline/CDK spécifique.`,
    choiceExplanations: [
      `Exact. Chaque transition mobilise un couple cycline/CDK spécifique.`,
      `Exact. Chaque transition mobilise un couple cycline/CDK spécifique.`,
      `Exact. Chaque transition mobilise un couple cycline/CDK spécifique.`,
      `Exact. Chaque transition mobilise un couple cycline/CDK spécifique.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La dégradation programmée des cyclines :`,
    choices: [
      `Permet de limiter dans le temps l’activité des complexes.`,
      `Contribue au caractère ordonné du cycle.`,
      `Rend les CDK définitivement inactives dans toutes les phases suivantes.`,
      `Est indispensable à certaines sorties de phase.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les CDK peuvent être réutilisées avec d’autres cyclines ; elles ne sont pas définitivement inactivées.`,
    choiceExplanations: [
      `Exact. Les CDK peuvent être réutilisées avec d’autres cyclines ; elles ne sont pas définitivement inactivées.`,
      `Exact. Les CDK peuvent être réutilisées avec d’autres cyclines ; elles ne sont pas définitivement inactivées.`,
      `Faux. Les CDK peuvent être réutilisées avec d’autres cyclines ; elles ne sont pas définitivement inactivées.`,
      `Exact. Les CDK peuvent être réutilisées avec d’autres cyclines ; elles ne sont pas définitivement inactivées.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un facteur de croissance stimule l’entrée en G1 par :`,
    choices: [
      `Activation d’un récepteur transmembranaire.`,
      `Transduction du signal.`,
      `Activation de Myc.`,
      `Production de cycline D.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La fiche décrit cette cascade complète du signal extracellulaire au complexe D/CDK4-6.`,
    choiceExplanations: [
      `Exact. La fiche décrit cette cascade complète du signal extracellulaire au complexe D/CDK4-6.`,
      `Exact. La fiche décrit cette cascade complète du signal extracellulaire au complexe D/CDK4-6.`,
      `Exact. La fiche décrit cette cascade complète du signal extracellulaire au complexe D/CDK4-6.`,
      `Exact. La fiche décrit cette cascade complète du signal extracellulaire au complexe D/CDK4-6.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la cycline A :`,
    choices: [
      `Elle s’associe d’abord à CDK2.`,
      `Elle peut ensuite s’associer à CDK1.`,
      `Elle participe à la réplication et à sa non-réinitiation.`,
      `Elle constitue avec CDK1 le MPF selon la fiche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le MPF est le complexe cycline B/CDK1.`,
    choiceExplanations: [
      `Exact. Le MPF est le complexe cycline B/CDK1.`,
      `Exact. Le MPF est le complexe cycline B/CDK1.`,
      `Exact. Le MPF est le complexe cycline B/CDK1.`,
      `Faux. Le MPF est le complexe cycline B/CDK1.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les phosphorylations induites par les complexes cycline/CDK :`,
    choices: [
      `Modifient de nombreuses protéines intracellulaires.`,
      `Permettent les transitions de phase.`,
      `Sont toutes irréversibles et non régulées.`,
      `Participent à la mise en place des événements de mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les phosphorylations sont régulées par kinases et phosphatases.`,
    choiceExplanations: [
      `Exact. Les phosphorylations sont régulées par kinases et phosphatases.`,
      `Exact. Les phosphorylations sont régulées par kinases et phosphatases.`,
      `Faux. Les phosphorylations sont régulées par kinases et phosphatases.`,
      `Exact. Les phosphorylations sont régulées par kinases et phosphatases.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition de Myc en réponse à un facteur de croissance pourrait :`,
    choices: [
      `Réduire l’expression de la cycline D.`,
      `Limiter la formation du complexe D/CDK4-6.`,
      `Accélérer nécessairement l’entrée en S.`,
      `Freiner la progression en G1.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Myc favorise l’expression du gène de la cycline D et donc l’entrée en cycle.`,
    choiceExplanations: [
      `Exact. Myc favorise l’expression du gène de la cycline D et donc l’entrée en cycle.`,
      `Exact. Myc favorise l’expression du gène de la cycline D et donc l’entrée en cycle.`,
      `Faux. Myc favorise l’expression du gène de la cycline D et donc l’entrée en cycle.`,
      `Exact. Myc favorise l’expression du gène de la cycline D et donc l’entrée en cycle.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule synthétise normalement la cycline E mais ne peut pas l’associer à CDK2 :`,
    choices: [
      `La transition G1-S peut être perturbée.`,
      `La phase S peut être retardée.`,
      `Le MPF est directement activé.`,
      `La cascade cycline/CDK est interrompue à un point clé.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le complexe E/CDK2 est nécessaire à la transition G1-S.`,
    choiceExplanations: [
      `Exact. Le complexe E/CDK2 est nécessaire à la transition G1-S.`,
      `Exact. Le complexe E/CDK2 est nécessaire à la transition G1-S.`,
      `Faux. Le complexe E/CDK2 est nécessaire à la transition G1-S.`,
      `Exact. Le complexe E/CDK2 est nécessaire à la transition G1-S.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cycline B non dégradable pourrait théoriquement :`,
    choices: [
      `Maintenir une activité MPF anormalement prolongée.`,
      `Perturber la sortie de mitose.`,
      `Accélérer directement la réplication en G1.`,
      `Empêcher le retour normal vers l’interphase.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La sortie de mitose nécessite la dégradation de la cycline B.`,
    choiceExplanations: [
      `Exact. La sortie de mitose nécessite la dégradation de la cycline B.`,
      `Exact. La sortie de mitose nécessite la dégradation de la cycline B.`,
      `Faux. La sortie de mitose nécessite la dégradation de la cycline B.`,
      `Exact. La sortie de mitose nécessite la dégradation de la cycline B.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La figure suivante présente le profil des cyclines D, E, A et B et les complexes CDK associés.

![Cyclines et CDK](/images/training/ue14/biologie-cellulaire/cycle-cellulaire/cyclines-cdk.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Une succession temporelle d’activités.`,
      `Un chevauchement partiel des cyclines.`,
      `Une concentration constante de toutes les cyclines.`,
      `Une organisation séquentielle du cycle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les cyclines oscillent et leurs fenêtres d’expression peuvent se chevaucher.`,
    choiceExplanations: [
      `Exact. Les cyclines oscillent et leurs fenêtres d’expression peuvent se chevaucher.`,
      `Exact. Les cyclines oscillent et leurs fenêtres d’expression peuvent se chevaucher.`,
      `Faux. Les cyclines oscillent et leurs fenêtres d’expression peuvent se chevaucher.`,
      `Exact. Les cyclines oscillent et leurs fenêtres d’expression peuvent se chevaucher.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si le complexe A/CDK1 n’empêche plus une nouvelle réplication en fin de S :`,
    choices: [
      `L’unicité de la réplication peut être compromise.`,
      `Une nouvelle duplication inappropriée de l’ADN peut devenir possible.`,
      `La cellule devient automatiquement haploïde.`,
      `La stabilité du génome peut être menacée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le verrouillage de la réplication empêche la duplication répétée de l’ADN dans un même cycle.`,
    choiceExplanations: [
      `Exact. Le verrouillage de la réplication empêche la duplication répétée de l’ADN dans un même cycle.`,
      `Exact. Le verrouillage de la réplication empêche la duplication répétée de l’ADN dans un même cycle.`,
      `Faux. Le verrouillage de la réplication empêche la duplication répétée de l’ADN dans un même cycle.`,
      `Exact. Le verrouillage de la réplication empêche la duplication répétée de l’ADN dans un même cycle.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’activité d’une CDK dépend :`,
    choices: [
      `De son association à une cycline.`,
      `De son état de phosphorylation.`,
      `De régulateurs comme cdc25, CAK ou Wee1.`,
      `Uniquement de sa concentration totale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La concentration des CDK est relativement stable ; leur activation est fortement régulée.`,
    choiceExplanations: [
      `Exact. La concentration des CDK est relativement stable ; leur activation est fortement régulée.`,
      `Exact. La concentration des CDK est relativement stable ; leur activation est fortement régulée.`,
      `Exact. La concentration des CDK est relativement stable ; leur activation est fortement régulée.`,
      `Faux. La concentration des CDK est relativement stable ; leur activation est fortement régulée.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La destruction de l’enveloppe nucléaire à l’entrée en mitose est reliée :`,
    choices: [
      `À l’activation du MPF.`,
      `À des phosphorylations multiples.`,
      `À la cycline B/CDK1.`,
      `À la cycline E seule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cycline E intervient à G1-S, non dans le déclenchement direct de la mitose.`,
    choiceExplanations: [
      `Exact. La cycline E intervient à G1-S, non dans le déclenchement direct de la mitose.`,
      `Exact. La cycline E intervient à G1-S, non dans le déclenchement direct de la mitose.`,
      `Exact. La cycline E intervient à G1-S, non dans le déclenchement direct de la mitose.`,
      `Faux. La cycline E intervient à G1-S, non dans le déclenchement direct de la mitose.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La duplication du centrosome :`,
    choices: [
      `Est favorisée pendant S par A/CDK2.`,
      `Prépare la formation des deux COMT.`,
      `Est inutile pour le fuseau mitotique.`,
      `S’intègre à la préparation de la division.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le fuseau mitotique s’organise à partir des deux centres organisateurs des microtubules.`,
    choiceExplanations: [
      `Exact. Le fuseau mitotique s’organise à partir des deux centres organisateurs des microtubules.`,
      `Exact. Le fuseau mitotique s’organise à partir des deux centres organisateurs des microtubules.`,
      `Faux. Le fuseau mitotique s’organise à partir des deux centres organisateurs des microtubules.`,
      `Exact. Le fuseau mitotique s’organise à partir des deux centres organisateurs des microtubules.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule présentant des CDK stables mais aucune synthèse cyclique des cyclines :`,
    choices: [
      `Ne formera pas correctement les complexes actifs successifs.`,
      `Aura des transitions de phase perturbées.`,
      `Progressera normalement car les CDK suffisent seules.`,
      `Perdra l’organisation temporelle de la cascade.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les CDK nécessitent leurs cyclines spécifiques pour être actives au bon moment.`,
    choiceExplanations: [
      `Exact. Les CDK nécessitent leurs cyclines spécifiques pour être actives au bon moment.`,
      `Exact. Les CDK nécessitent leurs cyclines spécifiques pour être actives au bon moment.`,
      `Faux. Les CDK nécessitent leurs cyclines spécifiques pour être actives au bon moment.`,
      `Exact. Les CDK nécessitent leurs cyclines spécifiques pour être actives au bon moment.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `Les cyclines fournissent une horloge d’expression variable.`,
      `Les CDK constituent des partenaires catalytiques relativement stables.`,
      `Les complexes cycline/CDK organisent les transitions.`,
      `Le cycle dépend d’un seul complexe identique du début à la fin.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Plusieurs complexes spécifiques se succèdent au cours du cycle.`,
    choiceExplanations: [
      `Exact. Plusieurs complexes spécifiques se succèdent au cours du cycle.`,
      `Exact. Plusieurs complexes spécifiques se succèdent au cours du cycle.`,
      `Exact. Plusieurs complexes spécifiques se succèdent au cours du cycle.`,
      `Faux. Plusieurs complexes spécifiques se succèdent au cours du cycle.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `cyclines-et-cdk`,
    title: `Cyclines et kinases dépendantes des cyclines`,
    description: `Principes du contrôle moléculaire et complexes de G1 à M.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `succession-des-complexes-cycline-cdk`,
    title: `Succession des complexes cycline-CDK`,
    description: `Transitions G1-S, S-G2 et G2-M, MPF et dégradation des cyclines.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `regulation-moleculaire-du-cycle`,
    title: `Régulation moléculaire du cycle`,
    description: `Applications sur Myc, les cyclines, les CDK et la stabilité du génome.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
