/**
 * UE14 – Biologie cellulaire – Chapitre 6
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La composition chimique des peroxysomes peut être étudiée par :`,
    choices: [
      `Des méthodes de fractionnement cellulaire.`,
      `L’isolement de fractions contenant les organites.`,
      `La seule observation à l’œil nu.`,
      `Une approche permettant d’analyser membrane et matrice.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche cite le fractionnement cellulaire pour étudier la composition chimique des peroxysomes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La membrane peroxysomale :`,
    choices: [
      `Est différente de celle du RE.`,
      `Contient des protéines de la famille ABC.`,
      `Contient des complexes d’importation.`,
      `Est une simple extension continue de la membrane du Golgi.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane peroxysomale possède une composition spécifique avec perméases ABC et complexes d’import.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les protéines ABC de la membrane peroxysomale :`,
    choices: [
      `Signifient ATP Binding Cassette.`,
      `Fonctionnent avec de l’ATP.`,
      `Agissent comme des perméases.`,
      `Constituent le génome peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les ABC sont des protéines membranaires ATP-dépendantes assurant des fonctions de perméase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les complexes membranaires d’importation :`,
    choices: [
      `Permettent l’import de protéines membranaires.`,
      `Permettent l’import de protéines matricielles.`,
      `Fonctionnent avec des récepteurs et des signaux d’adressage.`,
      `Importent l’ADN nucléaire dans le peroxysome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’import peroxysomal concerne les protéines et dépend d’un système récepteur-signal, non d’un import d’ADN.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La matrice peroxysomale :`,
    choices: [
      `Utilise de l’oxygène.`,
      `Contient des oxydases.`,
      `Contient des catalases.`,
      `Est dépourvue de toute enzyme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La matrice est le siège de réactions oxydatives utilisant l’oxygène et impliquant oxydases et catalases.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les familles enzymatiques majeures du peroxysome :`,
    choices: [
      `Les oxydases.`,
      `Les catalases.`,
      `Les aminoacides oxydases.`,
      `Les histones nucléaires comme enzymes principales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche décrit plusieurs oxydases et une catalase très abondante ; les histones ne sont pas des enzymes peroxysomales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Quelle enzyme est indiquée comme la plus abondante dans la matrice peroxysomale ?`,
    choices: [
      `La catalase.`,
      `L’urate oxydase chez l’Homme.`,
      `Une ADN polymérase peroxysomale.`,
      `La SRP.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La catalase est présentée comme l’enzyme la plus abondante du peroxysome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Adressage et régulation peroxysomale](/images/training/ue14/biologie-cellulaire/peroxysomes/adressage-regulation-peroxysome.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les protéines peroxysomales sont synthétisées dans le cytosol.`,
      `Les phospholipides membranaires peuvent provenir du RE.`,
      `Les PPAR agissent au niveau nucléaire.`,
      `Le peroxysome synthétise lui-même toutes ses protéines à partir de son ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure montre la dépendance envers le cytosol et le RE, ainsi que la régulation transcriptionnelle par les PPAR.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une protéine soluble de la matrice peroxysomale :`,
    choices: [
      `Est synthétisée dans le cytosol.`,
      `Doit être reconnue par un système d’adressage.`,
      `Peut être importée par un complexe membranaire.`,
      `Est traduite dans la région paracristalline.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La région paracristalline contient des enzymes mais n’est pas un site de traduction.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une protéine membranaire peroxysomale :`,
    choices: [
      `Est également synthétisée dans le cytosol.`,
      `Peut être importée grâce à un complexe membranaire.`,
      `Dépend d’un signal d’adressage.`,
      `Est nécessairement produite dans le Golgi.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les protéines membranaires comme matricielles sont synthétisées dans le cytosol puis adressées au peroxysome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le système d’adressage peroxysomal associe :`,
    choices: [
      `Un signal porté par la protéine.`,
      `Un récepteur.`,
      `Un complexe d’importation membranaire.`,
      `Une vésicule obligatoire issue du lysosome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’import repose sur des signaux et des récepteurs au niveau de la membrane peroxysomale, sans vésicule lysosomale obligatoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les perméases ABC et les complexes d’importation diffèrent notamment par :`,
    choices: [
      `Le type de molécules transportées.`,
      `Leur fonction dans la membrane.`,
      `Le recours à l’ATP explicitement indiqué pour les ABC.`,
      `Le fait que les deux constituent des chromosomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les ABC transportent des solutés avec l’ATP tandis que les complexes d’import prennent en charge des protéines adressées.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l’origine des constituants peroxysomaux :`,
    choices: [
      `Les protéines sont synthétisées dans le cytosol.`,
      `Les phospholipides sont apportés depuis le RE.`,
      `Le génome peroxysomal code la catalase.`,
      `Des systèmes d’import permettent l’assemblage de l’organite.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L’organite sans génome dépend de l’import de protéines et de lipides provenant d’autres compartiments.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La régulation par les PPAR :`,
    choices: [
      `Est déclenchée par des lipides.`,
      `S’effectue au niveau de récepteurs nucléaires.`,
      `Contrôle la transcription de gènes peroxysomaux.`,
      `Détruit directement les peroxysomes dans les lysosomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les PPAR régulent l’expression des constituants ; la destruction relève de l’autophagie lysosomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le cytosquelette intervient dans :`,
    choices: [
      `Le déplacement des peroxysomes.`,
      `La répartition intracellulaire des peroxysomes.`,
      `La synthèse de leur génome.`,
      `La dynamique de ces organites.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le peroxysome est mobile via le cytosquelette, mais ne possède pas de génome à synthétiser.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La durée de vie d’environ 3,5 jours dans l’hépatocyte illustre :`,
    choices: [
      `Un renouvellement relativement rapide.`,
      `La nécessité d’une biogenèse permanente.`,
      `La possibilité d’une destruction par autophagie.`,
      `Une persistance définitive de chaque peroxysome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le renouvellement permanent associe formation et élimination des organites.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Si un complexe d’importation des protéines matricielles est déficient :`,
    choices: [
      `L’entrée d’enzymes dans la matrice peut être perturbée.`,
      `La composition enzymatique du peroxysome peut être altérée.`,
      `La présence de signaux d’adressage ne suffit plus à assurer un import normal.`,
      `Le peroxysome acquiert automatiquement un génome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le signal doit être reconnu et relayé par un complexe fonctionnel ; sa défaillance perturbe la matrice.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’absence de génome peroxysomal est compatible avec :`,
    choices: [
      `Une matrice riche en enzymes.`,
      `Une membrane contenant des transporteurs.`,
      `Un import de protéines synthétisées dans le cytosol.`,
      `Une traduction locale obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les protéines de l’organite sont importées ; aucune traduction locale n’est nécessaire dans la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À partir de la figure suivante :

![Adressage et régulation peroxysomale](/images/training/ue14/biologie-cellulaire/peroxysomes/adressage-regulation-peroxysome.png)

Quelle(s) relation(s) est(sont) correctement représentée(s) ?`,
    choices: [
      `PPAR → expression de protéines peroxysomales.`,
      `Cytosol → synthèse des protéines peroxysomales.`,
      `RE → apport de phospholipides.`,
      `Peroxysome → production d’un génome exporté vers le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure met en relation régulation nucléaire, synthèse cytosolique et apport lipidique depuis le RE.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La spécificité de la membrane peroxysomale repose notamment sur :`,
    choices: [
      `Des protéines ABC.`,
      `Des complexes d’importation.`,
      `Une composition différente de celle du RE.`,
      `L’absence totale de protéines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane est fonctionnellement spécialisée et porte plusieurs classes de protéines.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une activation lipidique des PPAR peut aboutir à :`,
    choices: [
      `Une augmentation de transcription de certains gènes peroxysomaux.`,
      `Une modification de la quantité de constituants peroxysomaux.`,
      `Une réponse passant par le noyau.`,
      `Une conversion directe d’acide urique en allantoïne chez l’Homme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les PPAR agissent sur l’expression génique ; l’Homme ne possède pas d’urate oxydase dans la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le fractionnement cellulaire permet, dans ce chapitre :`,
    choices: [
      `D’isoler des fractions enrichies en organites.`,
      `D’étudier la composition de la membrane peroxysomale.`,
      `D’identifier des enzymes de la matrice.`,
      `De transformer les peroxysomes en mitochondries.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le fractionnement est une méthode analytique, non un mécanisme de transformation cellulaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut d’ATP pourrait affecter directement, selon la fiche :`,
    choices: [
      `Le fonctionnement des perméases ABC.`,
      `Le transport de certains substrats à travers la membrane peroxysomale.`,
      `La définition ATP Binding Cassette.`,
      `La présence d’un génome peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les ABC utilisent l’ATP ; leur activité peut donc être touchée par un manque d’énergie disponible.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine possède un signal d’adressage peroxysomal intact mais le récepteur correspondant est absent. On s’attend à :`,
    choices: [
      `Une perturbation de sa reconnaissance.`,
      `Un défaut possible d’import.`,
      `Une accumulation possible de la protéine hors du peroxysome.`,
      `Une entrée normale garantie par le seul signal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le signal et le récepteur sont tous deux nécessaires au système d’adressage présenté.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La mobilité et le renouvellement peroxysomaux montrent que :`,
    choices: [
      `Le peroxysome est un organite dynamique.`,
      `Sa position dans le cytosol n’est pas forcément fixe.`,
      `Son nombre peut être régulé.`,
      `Chaque peroxysome reste inchangé pendant toute la vie cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Déplacement, bourgeonnement, renouvellement et autophagie témoignent d’une forte dynamique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La destruction autophagique dans les lysosomes :`,
    choices: [
      `Participe au renouvellement des peroxysomes.`,
      `Élimine des organites vieillissants.`,
      `Est également citée pour les mitochondries.`,
      `Transforme les lysosomes en peroxysomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’autophagie est une voie d’élimination et de recyclage, non une conversion en nouvel organite.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le RE contribue aux peroxysomes en fournissant :`,
    choices: [
      `Des phospholipides membranaires.`,
      `Un transport à travers le cytosol.`,
      `La preuve que les peroxysomes appartiennent au SEM.`,
      `Un apport comparable à celui mentionné pour la mitochondrie.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L’apport lipidique du RE n’implique pas l’appartenance du peroxysome au SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quel trajet correspond à une protéine matricielle peroxysomale ?`,
    choices: [
      `Synthèse dans le cytosol.`,
      `Présence d’un signal d’adressage.`,
      `Reconnaissance par un récepteur et un complexe d’import.`,
      `Traduction par un ribosome intraperoxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La protéine est synthétisée dans le cytosol puis importée ; la fiche ne décrit pas de ribosome peroxysomal.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La membrane peroxysomale assure à la fois :`,
    choices: [
      `Le transport de solutés grâce à des perméases ABC.`,
      `L’import de protéines grâce à des complexes spécifiques.`,
      `La séparation de la matrice et du cytosol.`,
      `La transcription des gènes peroxysomaux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La transcription a lieu dans le noyau sous contrôle des PPAR, pas dans la membrane peroxysomale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte sur la composition et la régulation du peroxysome ?`,
    choices: [
      `La membrane contient des systèmes de transport et d’import.`,
      `La matrice contient des enzymes oxydatives.`,
      `Les PPAR régulent l’expression de constituants peroxysomaux.`,
      `L’organite produit localement toutes ses protéines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le peroxysome dépend d’apports externes et d’une régulation nucléaire, malgré sa richesse enzymatique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `composition-membrane-matrice`,
    title: `Composition de la membrane et de la matrice`,
    description: `Fractionnement, protéines ABC, complexes d’import et enzymes matricielles.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `adressage-constituants-peroxysomaux`,
    title: `Adressage des constituants peroxysomaux`,
    description: `Signaux, récepteurs, import des protéines et apport des phospholipides.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `regulation-mobilite-renouvellement`,
    title: `Régulation, mobilité et renouvellement`,
    description: `PPAR, cytosquelette, autophagie et intégration des apports cellulaires.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
