/**
 * UE14 – Biologie cellulaire – Chapitre 1
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les marquages moléculaires permettent :`,
    choices: [
      `D'identifier des molécules dans les cellules.`,
      `De localiser des molécules dans les cellules.`,
      `De travailler selon la méthode sur des cellules fixées ou vivantes.`,
      `De remplacer systématiquement toute observation microscopique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les marquages associent une molécule cible à un signal détectable pour fournir une information d'identité et de localisation.`,
    choiceExplanations: [
      `C'est leur première finalité.`,
      `C'est leur seconde finalité.`,
      `La fiche distingue les méthodes compatibles avec chaque état.`,
      `La visualisation repose au contraire sur la microscopie adaptée au marqueur.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les quatre grandes méthodes présentées :`,
    choices: [
      `L'immunomarquage.`,
      `L'hybridation in situ.`,
      `Les protéines auto-fluorescentes.`,
      `La distillation fractionnée de la cellule entière.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chapitre distingue immunomarquage, hybridation in situ, protéines auto-fluorescentes et micro-injection de protéines marquées.`,
    choiceExplanations: [
      `Il fait partie des méthodes citées.`,
      `Elle est également citée.`,
      `Elles permettent notamment le suivi sur cellules vivantes.`,
      `Ce n'est pas une méthode de localisation moléculaire présentée.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Selon le tableau comparatif du cours :`,
    choices: [
      `L'immunomarquage est réalisé sur cellules fixées.`,
      `L'hybridation in situ est réalisée sur cellules fixées.`,
      `Les protéines auto-fluorescentes peuvent être observées sur cellules vivantes ou fixées.`,
      `Les protéines marquées micro-injectées sont limitées aux cellules fixées avant l'injection.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le choix de la stratégie dépend notamment de la nécessité de figer l'état cellulaire ou de suivre une dynamique dans une cellule vivante.`,
    choiceExplanations: [
      `Le tableau indique non sur cellules vivantes et oui sur cellules fixées.`,
      `Elle nécessite également la fixation.`,
      `Les deux colonnes sont indiquées oui.`,
      `La micro-injection est effectuée dans une cellule vivante.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'immunomarquage repose sur :`,
    choices: [
      `L'affinité d'un anticorps pour un antigène.`,
      `La reconnaissance d'un épitope de l'antigène.`,
      `Des sites de reconnaissance situés sur les fragments Fab.`,
      `Une complémentarité obligatoire entre deux séquences d'ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'anticorps reconnaît spécifiquement un épitope de l'antigène par ses fragments Fab.`,
    choiceExplanations: [
      `C'est le principe central.`,
      `L'anticorps anti-X se lie à une petite partie de X.`,
      `La fiche localise les deux sites sur les Fab.`,
      `Cette propriété correspond à l'hybridation in situ.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Pour obtenir des anticorps dirigés contre une protéine humaine, la fiche décrit :`,
    choices: [
      `L'injection répétée de la protéine ou de ses antigènes dans une autre espèce.`,
      `Une immunisation de l'animal.`,
      `La récupération du plasma puis la purification des anticorps.`,
      `La récupération exclusive de l'ADN de la protéine sans réponse immunitaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'immunisation d'une autre espèce permet de récupérer dans le plasma des anticorps spécifiques, ensuite purifiés.`,
    choiceExplanations: [
      `L'exemple donné est le lapin.`,
      `Elle déclenche la production d'anticorps.`,
      `Ce sont les étapes suivantes.`,
      `Le protocole décrit repose sur l'immunisation et le plasma.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos d'un fluorochrome :`,
    choices: [
      `Il est excité par une longueur d'onde spécifique.`,
      `Il émet en réponse une autre longueur d'onde spécifique.`,
      `Il peut être observé au microscope optique à fluorescence.`,
      `Il est nécessairement visible sans aucune excitation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Un fluorochrome convertit une excitation lumineuse donnée en une émission détectable, ce qui permet de localiser la cible.`,
    choiceExplanations: [
      `C'est la première propriété donnée.`,
      `L'émission est différente de l'excitation.`,
      `C'est la méthode d'observation indiquée.`,
      `La fluorescence nécessite une excitation adaptée.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans l'exemple de l'Alexa 488 :`,
    choices: [
      `Il est couplé chimiquement au fragment Fc de l'anticorps.`,
      `Il est excité à 488 nm dans le bleu.`,
      `Il émet autour de 520 nm dans le vert.`,
      `Il est observé uniquement au microscope électronique à transmission.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'Alexa 488 illustre la différence entre longueur d'onde d'excitation et longueur d'onde d'émission.`,
    choiceExplanations: [
      `C'est la localisation indiquée dans la fiche.`,
      `Cette valeur est donnée.`,
      `C'est la réponse fluorescente décrite.`,
      `Il est observé en microscopie optique à fluorescence.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'or colloïdal utilisé comme marqueur :`,
    choices: [
      `Il se présente sous forme de billes de taille homogène.`,
      `Des tailles de 2, 5 ou 12 nm sont citées.`,
      `Les parties Fc des anticorps peuvent être adsorbées sur les billes.`,
      `Son observation de référence se fait au microscope optique inversé sans préparation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les billes d'or, denses aux électrons, servent de marqueurs visibles en MET lorsqu'elles sont associées aux anticorps.`,
    choiceExplanations: [
      `La fiche parle d'une suspension de billes.`,
      `Ce sont les valeurs données.`,
      `C'est le mode de couplage présenté.`,
      `La fiche indique la microscopie électronique à transmission.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un immunomarquage intracellulaire :`,
    choices: [
      `La fixation immobilise les molécules in situ.`,
      `La fixation cherche à préserver l'aspect structural de la cellule.`,
      `Une perméabilisation partielle permet l'entrée des anticorps.`,
      `Les anticorps traversent librement la membrane de toute cellule vivante.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fixation fige l'état cellulaire, puis la perméabilisation ouvre un accès aux antigènes intracellulaires.`,
    choiceExplanations: [
      `C'est l'objectif principal.`,
      `La fiche le précise.`,
      `Les anticorps ne diffusent pas spontanément à travers une membrane intacte.`,
      `Le cours indique explicitement l'inverse.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après incubation avec les anticorps :`,
    choices: [
      `Les anticorps spécifiques peuvent se lier aux antigènes correspondants.`,
      `Les anticorps en excès non liés sont éliminés par lavage.`,
      `Le fluorochrome peut ensuite être excité pour observer la cible.`,
      `Le lavage doit retirer tous les anticorps liés à la protéine d'intérêt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le lavage améliore la lisibilité du signal en éliminant les anticorps qui ne sont pas retenus par la cible.`,
    choiceExplanations: [
      `C'est la réaction recherchée.`,
      `Cette étape réduit le signal non spécifique.`,
      `L'observation suit le marquage et les lavages.`,
      `Il vise surtout les anticorps non liés.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'hybridation in situ repose sur :`,
    choices: [
      `La complémentarité de séquences nucléotidiques.`,
      `Une séquence cible dans la cellule.`,
      `Une sonde nucléotidique complémentaire.`,
      `La reconnaissance d'un épitope par un fragment Fab.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une sonde marquée s'apparie à une séquence d'ADN ou d'ARN complémentaire présente dans la cellule fixée.`,
    choiceExplanations: [
      `C'est son principe moléculaire.`,
      `La technique cherche à la mettre en évidence.`,
      `La sonde s'hybride à la cible.`,
      `Cette relation appartient à l'immunomarquage.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la sonde utilisée en hybridation in situ :`,
    choices: [
      `Elle est couplée à un marqueur.`,
      `Le marqueur peut être fluorescent.`,
      `Le marqueur peut être colorimétrique.`,
      `Elle doit être une protéine anticorps anti-X.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La nature du marqueur porté par la sonde détermine ensuite le mode d'observation.`,
    choiceExplanations: [
      `Ce couplage rend l'hybridation visible.`,
      `Cette possibilité est citée.`,
      `C'est l'autre possibilité donnée.`,
      `Il s'agit d'une séquence nucléotidique.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'hybridation in situ peut localiser :`,
    choices: [
      `Une séquence d'ADN, par exemple un gène.`,
      `Un ARN d'intérêt.`,
      `Une séquence cible dans une cellule fixée.`,
      `N'importe quelle protéine uniquement grâce à sa forme tridimensionnelle.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La méthode fournit une localisation spatiale de séquences d'ADN ou d'ARN au sein d'une cellule fixée.`,
    choiceExplanations: [
      `C'est l'une des cibles mentionnées.`,
      `La fiche cite également l'ARN.`,
      `La fixation est nécessaire dans le cadre du cours.`,
      `La technique cible des séquences nucléotidiques.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Selon le marqueur de la sonde, l'hybridation in situ peut être observée :`,
    choices: [
      `En microscopie optique à fluorescence.`,
      `En microscopie optique à transmission.`,
      `Sur des cellules fixées.`,
      `Uniquement sur des cellules vivantes en division.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La méthode d'observation dépend du marqueur fluorescent ou colorimétrique porté par la sonde.`,
    choiceExplanations: [
      `C'est le cas d'une sonde fluorescente.`,
      `La fiche le prévoit selon le marqueur.`,
      `C'est une condition de la méthode présentée.`,
      `Le tableau indique non pour les cellules vivantes.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des protéines auto-fluorescentes :`,
    choices: [
      `La GFP est citée comme exemple.`,
      `La DsRed est citée comme autre molécule fluorescente.`,
      `Elles peuvent permettre l'observation de protéines dans des cellules vivantes.`,
      `Elles nécessitent toujours un anticorps pénétrant une cellule vivante intacte.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les protéines auto-fluorescentes servent de tags génétiques permettant le suivi d'une protéine, notamment dans une cellule vivante.`,
    choiceExplanations: [
      `Green Fluorescence Protein est l'exemple principal.`,
      `La fiche la mentionne en remarque.`,
      `C'est leur intérêt majeur.`,
      `La fluorescence est produite par une protéine chimérique synthétisée par la cellule.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La construction utilisée pour produire une protéine fluorescente chimérique associe :`,
    choices: [
      `Un fragment d'ADN codant la protéine à étudier.`,
      `Le gène codant la protéine fluorescente.`,
      `Une expression de la protéine chimérique par la cellule.`,
      `Une destruction préalable du génome de toutes les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'ingénierie génétique relie les séquences codantes de la protéine d'intérêt et du tag fluorescent.`,
    choiceExplanations: [
      `C'est le premier élément.`,
      `C'est le tag fluorescent.`,
      `La cellule synthétise le produit fusionné.`,
      `Cette étape n'est pas décrite.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans la transfection décrite :`,
    choices: [
      `L'ADN recombinant est encapsidé dans une structure de type liposome.`,
      `Cette structure fusionne avec la membrane plasmique.`,
      `La cellule peut ensuite synthétiser la protéine chimérique.`,
      `La protéine d'intérêt purifiée est nécessairement injectée directement par micropipette.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La transfection introduit une construction d'ADN dans la cellule afin qu'elle produise elle-même la protéine taguée.`,
    choiceExplanations: [
      `La fiche décrit cette encapsidation.`,
      `La fusion permet l'entrée du matériel génétique.`,
      `C'est l'objectif de l'introduction de l'ADN.`,
      `Cela correspond à la stratégie de micro-injection de protéines marquées.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `L'électroporation est définie dans la fiche comme :`,
    choices: [
      `Une perméabilisation de la membrane par un choc électrique.`,
      `Une fixation chimique irréversible de la cellule.`,
      `Une centrifugation du sang.`,
      `Une hybridation entre un anticorps et un épitope.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L'électroporation crée transitoirement une perméabilité membranaire permettant l'introduction de la construction génétique.`,
    choiceExplanations: [
      `C'est la définition exacte donnée.`,
      `Elle sert à faire entrer du matériel dans une cellule vivante.`,
      `Cette étape concerne la récupération de cellules circulantes.`,
      `Cela correspond à l'immunomarquage.`,
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une protéine chimérique auto-fluorescente peut être observée :`,
    choices: [
      `Au microscope optique à fluorescence.`,
      `Dans une cellule vivante.`,
      `Dans une cellule fixée.`,
      `Uniquement après couplage à des billes d'or de 12 nm.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le tag fluorescent permet d'observer la localisation d'une protéine aussi bien avant qu'après fixation, selon le protocole.`,
    choiceExplanations: [
      `C'est la méthode de visualisation indiquée.`,
      `Le suivi dynamique est un intérêt majeur.`,
      `Le tableau comparatif l'autorise également.`,
      `La protéine porte elle-même le tag fluorescent.`,
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La stratégie de micro-injection de protéines marquées :`,
    choices: [
      `Utilise une protéine purifiée couplée à un marqueur.`,
      `Peut employer un fluorochrome ou de l'or colloïdal.`,
      `Injecte la protéine dans le cytoplasme ou le noyau d'une cellule vivante.`,
      `Repose nécessairement sur l'expression d'un gène chimérique par la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La micro-injection permet de suivre directement le devenir d'une protéine exogène marquée dans une cellule vivante.`,
    choiceExplanations: [
      `C'est le matériel injecté.`,
      `Les deux marqueurs sont cités.`,
      `Les deux compartiments sont envisagés.`,
      `Elle introduit directement une protéine déjà purifiée et marquée.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une équipe veut localiser une protéine P et l'ARN qui la code dans des cellules fixées. Elle peut choisir :`,
    choices: [
      `Un immunomarquage pour la protéine P.`,
      `Une hybridation in situ pour l'ARN.`,
      `Deux marqueurs adaptés et des méthodes d'observation correspondantes.`,
      `Une seule sonde protéique supposée reconnaître indifféremment l'ARN et l'épitope.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le type de cible détermine la méthode : anticorps pour une protéine, sonde nucléotidique pour un ADN ou un ARN.`,
    choiceExplanations: [
      `L'anticorps reconnaît un épitope protéique.`,
      `Une sonde complémentaire cible la séquence d'ARN.`,
      `Les cibles ne sont pas de même nature.`,
      `Les principes moléculaires sont distincts.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On souhaite suivre au cours du temps la redistribution d'une protéine dans une cellule vivante. Selon le cours :`,
    choices: [
      `Une protéine auto-fluorescente peut être utilisée.`,
      `Une protéine purifiée marquée peut être micro-injectée.`,
      `Un immunomarquage classique sur cellule fixée ne permet pas à lui seul un suivi continu de la même cellule vivante.`,
      `L'hybridation in situ sur cellule fixée est la seule méthode possible.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Pour un suivi temporel, il faut une stratégie compatible avec la vie cellulaire, comme un tag fluorescent exprimé ou une protéine marquée micro-injectée.`,
    choiceExplanations: [
      `Cette stratégie autorise le suivi vivant.`,
      `Cette autre stratégie est compatible avec la cellule vivante.`,
      `La fixation fige la cellule à un temps donné.`,
      `Elle ne répond pas au suivi dynamique d'une protéine vivante.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un anticorps couplé à l'Alexa 488 est excité à 488 nm et émet à 520 nm :`,
    choices: [
      `L'excitation et l'émission ont des longueurs d'onde différentes.`,
      `Le signal vert localise les anticorps liés à la cible.`,
      `Une excitation adaptée est nécessaire avant la détection.`,
      `L'émission à 520 nm signifie que l'échantillon est observé uniquement en MET.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La séparation spectrale entre excitation et émission permet de détecter le fluorochrome et donc de cartographier la protéine d'intérêt.`,
    choiceExplanations: [
      `C'est une propriété du fluorochrome.`,
      `Après lavage, le signal retenu correspond aux complexes marqués.`,
      `Le fluorochrome doit être excité.`,
      `La méthode est une microscopie optique à fluorescence.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans un immunomarquage, un lavage insuffisant après incubation peut :`,
    choices: [
      `Laisser des anticorps non liés dans la préparation.`,
      `Augmenter un signal de fond non spécifique.`,
      `Rendre l'interprétation de la localisation plus difficile.`,
      `Améliorer nécessairement la spécificité du marquage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La spécificité biologique de l'anticorps doit être accompagnée d'étapes techniques, dont les lavages, pour obtenir une image interprétable.`,
    choiceExplanations: [
      `Ils auraient dû être éliminés.`,
      `Des fluorochromes libres ou non retenus peuvent être détectés.`,
      `Le contraste cible/fond diminue.`,
      `Un lavage insuffisant dégrade plutôt la spécificité apparente.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Associer le marqueur à l'observation :`,
    choices: [
      `Fluorochrome — microscope optique à fluorescence.`,
      `Or colloïdal — microscope électronique à transmission.`,
      `Sonde colorimétrique — microscopie optique à transmission possible.`,
      `Alexa 488 — observation obligatoire au télescope.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le mode de détection doit être compatible avec les propriétés physiques du marqueur.`,
    choiceExplanations: [
      `C'est l'association de référence.`,
      `Les billes d'or sont détectées en MET.`,
      `La fiche le prévoit selon le marqueur.`,
      `Il s'observe en microscopie à fluorescence.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Comparer transfection et micro-injection de protéines marquées :`,
    choices: [
      `La transfection introduit une construction d'ADN.`,
      `La micro-injection introduit directement une protéine purifiée marquée.`,
      `Les deux stratégies peuvent contribuer à une observation dans une cellule vivante.`,
      `Les deux termes désignent exactement la fixation chimique d'une cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La transfection agit au niveau du gène exprimé, tandis que la micro-injection apporte directement la protéine marquée.`,
    choiceExplanations: [
      `La cellule exprime ensuite le produit chimérique.`,
      `Elle ne nécessite pas son expression par la cellule.`,
      `Elles sont compatibles avec ce type d'étude.`,
      `Aucune des deux n'est une fixation.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un protocole prévoit d'ajouter un anticorps dirigé contre une protéine cytoplasmique à une cellule vivante non perméabilisée. Selon le cours :`,
    choices: [
      `L'anticorps ne diffuse pas spontanément à travers la membrane intacte.`,
      `Une fixation puis une perméabilisation sont prévues dans l'immunomarquage décrit.`,
      `La cible intracellulaire risque de ne pas être accessible dans le protocole proposé.`,
      `Le protocole est nécessairement optimal sans aucune modification.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Pour une cible intracellulaire, l'immunomarquage du cours exige de fixer puis de perméabiliser la cellule.`,
    choiceExplanations: [
      `C'est la justification de la perméabilisation.`,
      `Ce sont les étapes adaptées.`,
      `La membrane constitue une barrière.`,
      `Il ne respecte pas la condition d'accès à la cible.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour localiser un ARN précis par hybridation in situ :`,
    choices: [
      `La sonde doit comporter une séquence complémentaire de l'ARN cible.`,
      `La sonde doit porter un marqueur détectable.`,
      `La cellule est fixée dans le cadre de la méthode présentée.`,
      `Le fragment Fab d'un anticorps remplace nécessairement la sonde nucléotidique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La spécificité de l'hybridation vient de la complémentarité des bases, tandis que le marqueur rend la sonde visible.`,
    choiceExplanations: [
      `C'est la base de l'hybridation.`,
      `Sinon sa localisation ne serait pas visualisée.`,
      `Le tableau comparatif le précise.`,
      `Les deux méthodes reposent sur des reconnaissances différentes.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À partir du tableau comparatif du cours :`,
    choices: [
      `Immunomarquage et hybridation in situ figent la cellule au temps de l'exploration.`,
      `Les protéines auto-fluorescentes permettent une observation sur cellule vivante.`,
      `Les protéines marquées peuvent être étudiées après micro-injection dans une cellule vivante.`,
      `Toutes les méthodes nécessitent exactement le même marqueur et le même microscope.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La comparaison doit porter sur la nature de la cible, l'état vivant ou fixé de la cellule et le système de détection.`,
    choiceExplanations: [
      `Ils sont réalisés sur cellules fixées.`,
      `C'est l'un de leurs principaux intérêts.`,
      `C'est la procédure décrite.`,
      `Les marqueurs et modes d'observation diffèrent.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les propositions suivantes :`,
    choices: [
      `Un anticorps reconnaît un épitope d'une protéine antigénique.`,
      `Une sonde d'hybridation reconnaît une séquence nucléotidique complémentaire.`,
      `Une protéine chimérique GFP peut être synthétisée par une cellule transfectée.`,
      `Tous les items précédents sont faux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les méthodes se distinguent par leur objet moléculaire et leur mode d'introduction ou de détection, mais elles partagent un objectif de localisation.`,
    choiceExplanations: [
      `C'est le principe de l'immunomarquage.`,
      `C'est le principe de l'hybridation in situ.`,
      `C'est la stratégie auto-fluorescente décrite.`,
      `Les trois premiers items sont exacts.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `principes-marquages-moleculaires`,
    title: `Principes des marquages moléculaires`,
    description: `Objectifs, cellules fixées ou vivantes et panorama des quatre méthodes du chapitre.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `immunomarquage-hybridation-in-situ`,
    title: `Immunomarquage et hybridation in situ`,
    description: `Anticorps, épitopes, fluorochromes, or colloïdal et sondes nucléotidiques complémentaires.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `proteines-fluorescentes-microinjection`,
    title: `Protéines fluorescentes et micro-injection`,
    description: `GFP, protéines chimériques, transfection, électroporation et protéines purifiées marquées.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
