/**
 * UE14 – Biologie cellulaire – Chapitre 8
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des caractéristiques générales du noyau :`,
    choices: [
      `Il est délimité par une enveloppe nucléaire.`,
      `Le volume interne est appelé nucléoplasme.`,
      `Il contient la totalité absolue de l’information génétique cellulaire.`,
      `Il contient de la chromatine et des nucléoles.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cette enveloppe définit le compartiment nucléaire.`,
      `Exact. Le nucléoplasme correspond au contenu délimité par l’enveloppe.`,
      `Faux. Une fraction de l’information génétique est mitochondriale.`,
      `Exact. Ces éléments participent à l’organisation du nucléoplasme.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les grandes fonctions du noyau comprennent :`,
    choices: [
      `La synthèse et la réparation de l’ADN.`,
      `La synthèse et la maturation des ARN.`,
      `Le contrôle des échanges nucléocytoplasmiques.`,
      `La sortie régulière de l’ADN vers le cytoplasme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ces activités appartiennent au métabolisme de l’ADN.`,
      `Exact. Ces étapes se déroulent dans le noyau.`,
      `Exact. L’enveloppe et ses pores régulent les entrées et sorties.`,
      `Faux. Le cours précise que l’ADN ne sort jamais du noyau.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant les échanges assurés par le noyau :`,
    choices: [
      `Des nucléotides, protéines et ions peuvent entrer.`,
      `Des ARN associés à des protéines peuvent sortir.`,
      `L’ADN est exporté vers le cytoplasme pour être traduit.`,
      `Les pores nucléaires interrompent l’enveloppe.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ils sont nécessaires au métabolisme des acides nucléiques.`,
      `Exact. Ils sont exportés sous forme de complexes.`,
      `Faux. L’ADN reste protégé dans le noyau.`,
      `Exact. Ils constituent les ouvertures d’échange.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Au début de la mitose :`,
    choices: [
      `Le matériel génétique se condense en chromosomes.`,
      `Les nucléoles se désorganisent et disparaissent.`,
      `L’enveloppe nucléaire se fragmente.`,
      `Le noyau conserve strictement son organisation interphasique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La chromatine devient fortement condensée.`,
      `Exact. Le cours décrit leur disparition au début de la mitose.`,
      `Exact. Ses fragments se fondent dans le réticulum endoplasmique.`,
      `Faux. L’organisation nucléaire disparaît transitoirement.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À la fin de la mitose :`,
    choices: [
      `L’enveloppe nucléaire se reconstitue.`,
      `Le réticulum endoplasmique participe à cette reconstitution.`,
      `L’ADN sort du noyau nouvellement formé.`,
      `Deux noyaux peuvent être individualisés dans les cellules filles.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle se reforme autour des lots chromosomiques.`,
      `Exact. L’enveloppe est reformée à partir du RE.`,
      `Faux. L’ADN reste nucléaire.`,
      `Exact. La reconstitution accompagne la fin de la division nucléaire.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’analyse anatomopathologique du noyau tumoral peut rechercher :`,
    choices: [
      `Une augmentation du rapport nucléocytoplasmique.`,
      `Une anisocaryose.`,
      `Des encoches ou des formes nucléaires irrégulières.`,
      `Une uniformité parfaite de la chromatine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le noyau est relativement plus volumineux.`,
      `Exact. La taille des noyaux devient irrégulière.`,
      `Exact. La morphologie nucléaire est un critère diagnostique.`,
      `Faux. Une chromatine grossière ou irrégulière est au contraire recherchée.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la forme du noyau :`,
    choices: [
      `Elle peut être caractéristique du type cellulaire.`,
      `Le noyau du lymphocyte est plutôt sphérique.`,
      `Le noyau du granulocyte peut être polylobé.`,
      `Un noyau polylobé correspond nécessairement à plusieurs noyaux distincts.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le lymphocyte et le granulocyte en fournissent des exemples.`,
      `Exact. C’est la morphologie décrite dans la fiche.`,
      `Exact. Il s’agit d’un seul noyau dont les lobes sont reliés.`,
      `Faux. Les lobes appartiennent à un même noyau.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Pendant la spermatogenèse :`,
    choices: [
      `La forme du noyau évolue avec la différenciation.`,
      `La spermatogonie possède un gros noyau.`,
      `Le spermatozoïde possède un petit noyau très allongé.`,
      `Le noyau devient de plus en plus volumineux au cours de la différenciation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le noyau se réduit et s’allonge progressivement.`,
      `Exact. Elle est la cellule la moins différenciée de la série décrite.`,
      `Exact. La chromatine y est fortement condensée.`,
      `Faux. Il devient au contraire plus petit et plus condensé.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’enveloppe nucléaire :`,
    choices: [
      `Est une expansion du réticulum endoplasmique rugueux.`,
      `Comporte deux membranes.`,
      `Les deux membranes sont séparées par un espace périnucléaire.`,
      `Est une membrane unique dépourvue de pores.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La continuité structurale avec le RER est soulignée.`,
      `Exact. Une membrane interne et une membrane externe sont distinguées.`,
      `Exact. Cet espace se situe entre les deux membranes.`,
      `Faux. Elle comporte deux membranes interrompues par des pores.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant la membrane externe de l’enveloppe nucléaire :`,
    choices: [
      `Elle peut porter des ribosomes.`,
      `Elle contribue au lien structural avec le RER.`,
      `Elle est séparée du RER par une barrière définitive.`,
      `Sa présence aide à comprendre la disparition et la reformation de l’enveloppe en mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cela rappelle sa continuité avec le RER.`,
      `Exact. L’enveloppe nucléaire est une expansion du RER.`,
      `Faux. La continuité avec le RE est un point majeur du cours.`,
      `Exact. Les membranes nucléaires fusionnent avec le RE puis en dérivent à nouveau.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l’espace périnucléaire :`,
    choices: [
      `Il est compris entre les membranes interne et externe.`,
      `Il correspond au nucléoplasme.`,
      `Il est appelé espace péri-cytoplasmique dans la fiche.`,
      `Il appartient à l’organisation de l’enveloppe nucléaire.`,
    ],
    correctChoiceIndexes: [0, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est sa définition.`,
      `Faux. Le nucléoplasme est le volume situé à l’intérieur de l’enveloppe.`,
      `Faux. Le terme retenu est espace périnucléaire.`,
      `Exact. Il sépare ses deux membranes.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un noyau contenant une chromatine grossière, des nucléoles irréguliers et un rapport nucléocytoplasmique augmenté :`,
    choices: [
      `Peut présenter des critères morphologiques évocateurs de malignité.`,
      `Est obligatoirement un noyau normal.`,
      `Doit être comparé aux cellules du tissu environnant.`,
      `Peut présenter une anisocaryose.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ces critères sont utilisés en anatomopathologie.`,
      `Faux. Ces anomalies motivent au contraire une comparaison avec le tissu normal.`,
      `Exact. Le diagnostic morphologique repose sur cette comparaison.`,
      `Exact. L’irrégularité de taille des noyaux est un critère cité.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Dans un prélèvement tumoral, l’anisocaryose désigne :`,
    choices: [
      `Une irrégularité de taille des noyaux.`,
      `Une absence totale de nucléole.`,
      `Une augmentation uniforme de la taille cytoplasmique.`,
      `La présence de plusieurs membranes nucléaires.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le terme correspond à la variabilité de taille nucléaire.`,
      `Faux. Ce n’est pas la définition de l’anisocaryose.`,
      `Faux. Le phénomène concerne les noyaux.`,
      `Faux. Le nombre de membranes n’est pas en cause.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En observant la figure suivante :

![Structure du noyau](/images/training/ue14/biologie-cellulaire/noyau/structure-noyau-enveloppe.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `La membrane externe est en continuité avec le RER.`,
      `Les pores interrompent localement les deux membranes.`,
      `Le nucléole se trouve dans le nucléoplasme.`,
      `La chromatine se trouve exclusivement dans l’espace périnucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La figure montre la prolongation vers les citernes portant des ribosomes.`,
      `Exact. Ils constituent les points de passage à travers l’enveloppe.`,
      `Exact. Il est représenté à l’intérieur du noyau.`,
      `Faux. Elle se trouve dans le nucléoplasme.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la relation noyau–réticulum endoplasmique :`,
    choices: [
      `L’enveloppe nucléaire est structurellement liée au RER.`,
      `La fragmentation de l’enveloppe peut alimenter le réseau du RE en mitose.`,
      `La reformation nucléaire utilise des membranes issues du RE.`,
      `Le noyau et le RE sont toujours totalement indépendants.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La membrane externe porte des ribosomes et se prolonge dans le RE.`,
      `Exact. Les vésicules se fondent dans le réticulum.`,
      `Exact. Le noyau se reconstitue à partir du réticulum.`,
      `Faux. Le cours insiste au contraire sur leur continuité.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quelle(s) association(s) est(sont) correcte(s) ?`,
    choices: [
      `Lymphocyte — noyau sphérique.`,
      `Granulocyte — noyau polylobé.`,
      `Spermatozoïde — petit noyau allongé et très condensé.`,
      `Spermatogonie — noyau minuscule et très allongé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est l’exemple morphologique donné.`,
      `Exact. Les lobes appartiennent à un seul noyau.`,
      `Exact. Cette forme est liée à la différenciation.`,
      `Faux. La spermatogonie possède au contraire un gros noyau.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le nucléoplasme :`,
    choices: [
      `Est le volume interne défini par l’enveloppe nucléaire.`,
      `Est organisé par le nucléosquelette.`,
      `Peut contenir plusieurs nucléoles.`,
      `Est synonyme de cytosol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il correspond au compartiment nucléaire.`,
      `Exact. Le cours souligne cette organisation.`,
      `Exact. Les nucléoles compartimentent le nucléoplasme.`,
      `Faux. Le cytosol est le compartiment cytoplasmique.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La quasi-totalité de l’information génétique eucaryote se trouve :`,
    choices: [
      `Dans la chromatine nucléaire.`,
      `Exclusivement dans les mitochondries.`,
      `Avec une fraction complémentaire dans l’ADN mitochondrial.`,
      `Dans le nucléole uniquement.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est la localisation principale de l’ADN cellulaire.`,
      `Faux. Les mitochondries n’en contiennent qu’une petite fraction.`,
      `Exact. Le cours mentionne explicitement cet ADN extranucléaire.`,
      `Faux. Le nucléole est surtout impliqué dans les ARNr et la biogenèse ribosomale.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La disparition du noyau au début de la mitose comprend :`,
    choices: [
      `La fragmentation de l’enveloppe.`,
      `La disparition des nucléoles.`,
      `La condensation de la chromatine.`,
      `La destruction définitive de toute l’information génétique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle perd son intégrité.`,
      `Exact. Ils se désorganisent.`,
      `Exact. Elle devient chromosome mitotique.`,
      `Faux. L’ADN est conservé et réparti dans les cellules filles.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des nucléoles observés en anatomopathologie :`,
    choices: [
      `Leur taille peut être irrégulière.`,
      `Leur forme peut être irrégulière.`,
      `Leur nombre peut être analysé.`,
      `Ils ne présentent jamais d’intérêt diagnostique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est un critère morphologique cité.`,
      `Exact. La morphologie nucléolaire est évaluée.`,
      `Exact. Le nombre fait partie des critères.`,
      `Faux. Le cours les inclut explicitement dans l’analyse morphologique.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule différenciée présente un noyau très allongé et une chromatine très condensée. L’interprétation la plus cohérente est :`,
    choices: [
      `La forme nucléaire peut traduire un état physiologique de différenciation.`,
      `Toute condensation nucléaire prouve un cancer.`,
      `La morphologie doit être interprétée selon le type cellulaire.`,
      `La cellule possède nécessairement plusieurs noyaux.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La spermatogenèse en est l’exemple détaillé.`,
      `Faux. La condensation peut être physiologique.`,
      `Exact. La forme du noyau dépend du contexte.`,
      `Faux. Un noyau allongé reste un noyau unique.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une observation en microscopie électronique montre deux membranes séparées par un espace et percées d’ouvertures. Il s’agit probablement :`,
    choices: [
      `De l’enveloppe nucléaire.`,
      `D’une membrane plasmique simple.`,
      `D’une structure pouvant être continue avec le RER.`,
      `D’un nucléole.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cette organisation correspond exactement à sa structure.`,
      `Faux. La membrane plasmique ne comporte pas deux membranes séparées par un espace périnucléaire.`,
      `Exact. La membrane externe est liée au RER.`,
      `Faux. Le nucléole n’est pas limité par deux membranes.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule en début de mitose présente encore une enveloppe nucléaire intacte et des nucléoles bien visibles. On peut en déduire que :`,
    choices: [
      `La désorganisation nucléaire est déjà complète.`,
      `La cellule se situe probablement avant la fragmentation complète de l’enveloppe.`,
      `La chromatine peut être en cours de condensation.`,
      `Le RER ne participera jamais à la reformation du noyau.`,
    ],
    correctChoiceIndexes: [1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Faux. Ces structures devraient avoir disparu si elle était complète.`,
      `Exact. La disparition est progressive au début de la mitose.`,
      `Exact. La condensation accompagne les premières étapes mitotiques.`,
      `Faux. Le RE est au contraire impliqué à la fin de la mitose.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos du rapport nucléocytoplasmique :`,
    choices: [
      `Il compare la taille du noyau à celle du cytoplasme.`,
      `Il peut être augmenté dans des cellules tumorales.`,
      `Il est nécessairement diminué lorsque le noyau grossit.`,
      `Il s’interprète par comparaison avec les cellules normales du prélèvement.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il s’agit d’un critère morphologique relatif.`,
      `Exact. Le cours le cite parmi les anomalies observables.`,
      `Faux. Un noyau relativement plus volumineux augmente ce rapport.`,
      `Exact. La comparaison au tissu environnant est essentielle.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le noyau d’un granulocyte polynucléaire :`,
    choices: [
      `Est un seul noyau composé de plusieurs lobes reliés.`,
      `Est toujours sphérique.`,
      `Illustre la relation entre morphologie et type cellulaire.`,
      `Ne contient aucune chromatine.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le terme polynucléaire ne signifie pas ici plusieurs noyaux indépendants.`,
      `Faux. La forme décrite est polylobée.`,
      `Exact. La forme nucléaire est caractéristique.`,
      `Faux. Il contient bien de la chromatine nucléaire.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La protection de l’ADN nucléaire repose notamment sur :`,
    choices: [
      `Son maintien à l’intérieur de l’enveloppe nucléaire.`,
      `Le contrôle des échanges par les pores.`,
      `Son export régulier vers le cytoplasme.`,
      `L’organisation de la chromatine.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le cours précise que l’ADN ne sort jamais du noyau.`,
      `Exact. Le trafic est sélectif.`,
      `Faux. L’ADN reste nucléaire.`,
      `Exact. L’ADN est structuré et compacté avec des histones.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule dont l’enveloppe nucléaire se reforme autour de deux lots chromosomiques se trouve vraisemblablement :`,
    choices: [
      `À la fin de la mitose.`,
      `Au début de la phase G1 avant toute mitose.`,
      `Dans une étape où le RER contribue à reformer l’enveloppe.`,
      `Dans une situation où les pores nucléaires sont définitivement absents.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La reconstitution de l’enveloppe est un événement tardif.`,
      `Faux. L’observation décrit spécifiquement la fin de la division nucléaire.`,
      `Exact. Le cours relie la reformation au réticulum.`,
      `Faux. Les pores seront réintégrés à l’enveloppe reformée.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les éléments suivants, lesquels appartiennent au noyau interphasique ?`,
    choices: [
      `La chromatine.`,
      `Le nucléole.`,
      `La matrice nucléaire.`,
      `Le fuseau mitotique complet.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle contient l’ADN associé aux protéines.`,
      `Exact. Il est un compartiment du nucléoplasme.`,
      `Exact. Elle constitue le nucléosquelette.`,
      `Faux. Le fuseau est une structure de la division et n’appartient pas au noyau interphasique.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un noyau tumoral peut être qualifié d’irrégulier en raison :`,
    choices: [
      `D’encoches de son contour.`,
      `D’une chromatine grossière.`,
      `D’une variabilité de taille entre noyaux.`,
      `D’une disparition obligatoire de toute enveloppe nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les encoches sont un critère morphologique cité.`,
      `Exact. La texture chromatinienne est évaluée.`,
      `Exact. C’est l’anisocaryose.`,
      `Faux. Une cellule tumorale interphasique conserve une enveloppe nucléaire.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `Le noyau est un compartiment organisé et dynamique.`,
      `Sa morphologie varie selon le type et l’état cellulaire.`,
      `Son enveloppe est liée au RER.`,
      `Il est totalement isolé du cytoplasme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il disparaît transitoirement en mitose et se reconstitue ensuite.`,
      `Exact. Les exemples lymphocyte, granulocyte et spermatogenèse l’illustrent.`,
      `Exact. Cette continuité explique sa dynamique mitotique.`,
      `Faux. Les pores assurent des échanges contrôlés.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `organisation-generale-noyau`,
    title: `Organisation générale du noyau`,
    description: `Caractéristiques, fonctions et dynamique mitotique du noyau.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `enveloppe-nucleaire-et-morphologie`,
    title: `Enveloppe nucléaire et morphologie`,
    description: `Structure de l’enveloppe, formes nucléaires et applications cytologiques.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `dynamique-et-pathologie-nucleaires`,
    title: `Dynamique et pathologie nucléaires`,
    description: `Applications intégrées sur la mitose et l’analyse anatomopathologique.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
