/**
 * Cartographie éditoriale V2
 * UE14 – Chimie générale – Chapitre 3 – Orbitales moléculaires
 */

export const UE14_CH3_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'decouvrir-orbitales-moleculaires-liaisons-sigma-pi',
    title: `Orbitales moléculaires et liaisons σ/π`,
    description: `Repères fondamentaux sur les orbitales moléculaires, les recouvrements axiaux et latéraux et les liaisons $\\sigma$ et $\\pi$.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'sentrainer-orbitales-moleculaires-liaisons-sigma-pi',
    title: `Orbitales moléculaires et liaisons σ/π`,
    description: `Applications sur les décomptes $\\sigma/\\pi$, les orbitales liantes et antiliantes, les profils de densité et les recouvrements orbitaux.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,81,82],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'decouvrir-hybridation-geometrie-molecules-simples',
    title: `Hybridation et géométrie des molécules simples`,
    description: `Repères fondamentaux sur les hybridations $\\mathrm{sp}$, $\\mathrm{sp}^2$ et $\\mathrm{sp}^3$ et leurs géométries caractéristiques.`,
    stage: 'DISCOVER' as const,
    questionOrders: [21,22,23,24,25,26,27,28,29,30],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'sentrainer-hybridation-geometrie-molecules-simples',
    title: `Hybridation et géométrie des molécules simples`,
    description: `Applications sur les cases quantiques, les orbitales non hybridées et l'hybridation d'espèces biologiques ou usuelles.`,
    stage: 'PRACTICE' as const,
    questionOrders: [31,32,33,34,35,36,37,38,39,40,83,84],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'decouvrir-liaisons-multiples-carbone-aromaticite',
    title: `Liaisons multiples, carbone et aromaticité`,
    description: `Repères sur les doubles et triples liaisons, les hybridations du carbone et le système $\\pi$ délocalisé du benzène.`,
    stage: 'DISCOVER' as const,
    questionOrders: [41,42,43,44,45,46,47,48,49,50],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'decouvrir-regle-gillespie-geometrie-moleculaire',
    title: `Règle de Gillespie et géométrie moléculaire`,
    description: `Repères sur la nomenclature $\\mathrm{AX}_m\\mathrm{E}_n$, la répulsion des doublets et les principales géométries moléculaires.`,
    stage: 'DISCOVER' as const,
    questionOrders: [51,52,53,54,55,56,57,58,59,60],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'sentrainer-synthese-orbitales-moleculaires',
    title: `Orbitales moléculaires et géométrie`,
    description: `Synthèse appliquée reliant liaisons $\\sigma/\\pi$, hybridation, aromaticité et géométrie moléculaire dans des exemples biologiques et médicaux.`,
    stage: 'PRACTICE' as const,
    items: [
      { type: 'QUESTION' as const, questionOrder: 61 },
      { type: 'QUESTION' as const, questionOrder: 62 },
      {
        type: 'GROUP' as const,
        title: `Dioxyde de carbone et hydrogénocarbonate`,
        sharedStatement: `Le dioxyde de carbone produit par le métabolisme est transporté vers les poumons ; l'ion hydrogénocarbonate $\\ce{HCO3-}$ participe au principal système tampon du sang. On compare leur carbone central.`,
        questionOrders: [63,64],
      },
      { type: 'QUESTION' as const, questionOrder: 65 },
      { type: 'QUESTION' as const, questionOrder: 66 },
      { type: 'QUESTION' as const, questionOrder: 67 },
      { type: 'QUESTION' as const, questionOrder: 68 },
      { type: 'QUESTION' as const, questionOrder: 69 },
      { type: 'QUESTION' as const, questionOrder: 70 },
    ],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'maitriser-synthese-orbitales-moleculaires',
    title: `Orbitales moléculaires et géométrie`,
    description: `Maîtrise transversale des orbitales moléculaires, des hybridations du carbone, des liaisons multiples et du modèle de Gillespie.`,
    stage: 'MASTER' as const,
    questionOrders: [71,72,73,74,75,76,77,78,79,80,85,86],
  },
] as const;

export const UE14_CH3_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Définition d'une orbitale moléculaire`],
  2: [`Liaison sigma : recouvrement axial et symétrie`],
  3: [`Recouvrements s-s, s-p et p-p`],
  4: [`Orbitales moléculaires liantes et antiliantes`],
  5: [`Liaison pi : recouvrement latéral`],
  6: [`Comparaison des liaisons sigma et pi`],
  7: [`Dioxygène : composition d'une double liaison`],
  8: [`Peroxyde d'hydrogène : décompte des liaisons sigma`],
  9: [`Chlorure d'hydrogène : liaison sigma s-p`],
  10: [`Triple liaison : nombre de composantes pi`],
  11: [`Cyanure d'hydrogène : décompte sigma`],
  12: [`Urée : décompte sigma/pi et quantité de matière`],
  13: [`Méthanamide : carbonyle et rotation`],
  14: [`Énergie des orbitales liante et antiliante`],
  15: [`Profils de densité électronique liante et antiliante`],
  16: [`Orientation des orbitales p et nature du recouvrement`],
  17: [`Dioxygène : liaison pi et limitation de rotation`],
  18: [`Diazote : composantes de la triple liaison`],
  19: [`Dioxyde de carbone : nombre de liaisons pi`],
  20: [`Comparaison HCN, urée et méthanamide`],
  21: [`Principe de l'hybridation`],
  22: [`Hybridation sp`],
  23: [`BeH2 : hybridation sp et géométrie`],
  24: [`Hybridation sp2`],
  25: [`Hybridation sp3`],
  26: [`Méthane : nombre d'orbitales sp3`],
  27: [`Ammoniac : orbitales sp3 et doublet non liant`],
  28: [`Eau : doublets non liants`],
  29: [`Comparaison CH4, NH3 et H2O`],
  30: [`Correspondances hybridation-géométrie`],
  31: [`Acétone : cases quantiques du carbone sp2`],
  32: [`CO2 : carbone sp et orbitales p`],
  33: [`Ion ammonium : protonation et hybridation`],
  34: [`NH3 et H2O : occupations des orbitales sp3`],
  35: [`Lecture des géométries sp, sp2 et sp3`],
  36: [`Éthanol : hybridation des carbones et de l'oxygène`],
  37: [`Acide lactique : carbones sp3`],
  38: [`Hydrogénocarbonate : carbone sp2`],
  39: [`Intérêt du modèle d'hybridation`],
  40: [`Ion oxonium : sp3 et géométrie pyramidale`],
  41: [`Composition des doubles et triples liaisons`],
  42: [`Éthylène : carbones sp2`],
  43: [`Éthylène : décompte sigma`],
  44: [`Éthylène : liaison pi et rotation`],
  45: [`Acétylène : hybridation sp`],
  46: [`Carbone sp : orbitales p restantes`],
  47: [`Carbone caméléon : sp3, sp2 et sp`],
  48: [`Benzène : carbones sp2 et système pi`],
  49: [`Reconnaissance des carbones sp2`],
  50: [`Éthane, éthylène, acétylène : hybridations comparées`],
  51: [`Règle de Gillespie et répulsion des doublets`],
  52: [`Nomenclature AXmEn`],
  53: [`Repérage d'une géométrie pyramidale AX3E1`],
  54: [`CO2 : type AX2 et géométrie linéaire`],
  55: [`BH3 et SO2 : types VSEPR`],
  56: [`Ion ammonium : nombre de directions de liaison`],
  57: [`NH3 et H2O : doublets non liants et géométries`],
  58: [`Espèces AX3E1`],
  59: [`PCl5 et SF6 : géométries à cinq et six directions`],
  60: [`Correspondances molécules-types de Gillespie`],
  61: [`Aspirine : nombre de carbones sp2`],
  62: [`Aspirine : hybridations locales`],
  63: [`CO2 : nombre de liaisons pi`],
  64: [`CO2 et HCO3- : hybridation et géométrie`],
  65: [`HCN : hybridation et liaisons pi`],
  66: [`Diazote : triple liaison et liaisons pi`],
  67: [`Benzène : aromaticité et délocalisation`],
  68: [`Espèces acido-basiques : VSEPR et sp3`],
  69: [`Hémoglobine : coordination AX6 du fer`],
  70: [`Acétone : carbone carbonylé sp2`],
  71: [`Aspirine : hybridations des neuf carbones`],
  72: [`Protoxyde d'azote : squelette linéaire et hybridation`],
  73: [`CO2/HCO3- : hybridation et liaisons multiples`],
  74: [`Méthanal : carbone carbonylé`],
  75: [`Éthylène : planéité et rotation`],
  76: [`HCN : cases quantiques du carbone sp`],
  77: [`Combinaison de deux orbitales p : sigma et sigma*`],
  78: [`NH3, NH4+, H2O et H3O+ : VSEPR`],
  79: [`PCl5 et SF6 : géométries hypervalentes`],
  80: [`Comparaison HCN, C2H4 et C6H6`],
  81: [`Espèces à deux liaisons pi`],
  82: [`Décompte de liaisons pi dans plusieurs doubles liaisons`],
  83: [`Nombre d'orbitales p restantes après hybridation sp2`],
  84: [`Reconnaissance de centres sp`],
  85: [`Synthèse des correspondances hybridation-géométrie`],
  86: [`Acide lactique : hybridations locales`],
};
