/** Cartographie éditoriale V2 — auteur */

export const UE14_BIOCH_CH10_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-liaison-peptidique-classification",
    "title": "Liaison peptidique, nomenclature et classification",
    "description": "Définitions, extrémités, taille, dénaturation et classification des peptides et protéines.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-nomenclature-denaturation",
    "title": "Liaison peptidique, nomenclature et classification",
    "description": "Applications sur nomenclature N/C-terminale, dénaturation, zymogènes et classification.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-structure-primaire",
    "title": "Structure primaire et modifications post-traductionnelles",
    "description": "Séquence, liaison peptidique, rigidité et angles φ/ψ.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-modifications-post-traductionnelles",
    "title": "Structure primaire et modifications post-traductionnelles",
    "description": "Hydroxylation, carboxylation, protéolyse et ponts disulfure.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-structures-secondaires",
    "title": "Structures secondaire et tertiaire",
    "description": "Hélices α, feuillets β, coudes et repères structuraux.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-structure-tertiaire-domaines",
    "title": "Structures secondaire et tertiaire",
    "description": "Applications sur stabilité tertiaire, domaines et relation hydrophobie–repliement.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-structure-quaternaire",
    "title": "Structure quaternaire et complexes protéiques",
    "description": "Sous-unités, homopolymères, hétéropolymères et premiers exemples.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-complexes-proteiques",
    "title": "Structure quaternaire et complexes protéiques",
    "description": "Applications sur CK-MM, CK-MB, protéines G et hémoglobine.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-structures-complexes-proteines",
    "title": "Structures et complexes protéiques",
    "description": "Maîtrise transversale de la relation séquence, conformation, domaines et assemblages.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-structure-proteines",
    "title": "Synthèse du chapitre",
    "description": "Consolidation transversale des quatre niveaux de structure.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-structure-peptides-proteines",
    "title": "Synthèse du chapitre",
    "description": "Maîtrise du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH10_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["la liaison peptidique"],
  2: ["la liaison peptidique"],
  3: ["le seuil conventionnel entre peptide et protéine"],
  4: ["le seuil conventionnel entre peptide et protéine"],
  5: ["l’extrémité N-terminale"],
  6: ["l’extrémité N-terminale"],
  7: ["l’extrémité C-terminale"],
  8: ["l’extrémité C-terminale"],
  9: ["la disposition des chaînes latérales dans un peptide"],
  10: ["la disposition des chaînes latérales dans un peptide"],
  11: ["la proline dans une chaîne peptidique"],
  12: ["la proline dans une chaîne peptidique"],
  13: ["les rôles généraux des peptides et protéines"],
  14: ["les rôles généraux des peptides et protéines"],
  15: ["la dénaturation"],
  16: ["la dénaturation"],
  17: ["les facteurs de dénaturation"],
  18: ["les facteurs de dénaturation"],
  19: ["les zymogènes"],
  20: ["les zymogènes"],
  21: ["la classification selon la composition"],
  22: ["la classification selon la composition"],
  23: ["la structure primaire"],
  24: ["la structure primaire"],
  25: ["la liaison peptidique dans la structure primaire"],
  26: ["la liaison peptidique dans la structure primaire"],
  27: ["les angles du squelette peptidique"],
  28: ["les angles du squelette peptidique"],
  29: ["l’hydroxylation post-traductionnelle"],
  30: ["l’hydroxylation post-traductionnelle"],
  31: ["la carboxylation post-traductionnelle"],
  32: ["la carboxylation post-traductionnelle"],
  33: ["le clivage protéolytique"],
  34: ["le clivage protéolytique"],
  35: ["les ponts disulfure"],
  36: ["les ponts disulfure"],
  37: ["les ponts disulfure intra-chaîne"],
  38: ["les ponts disulfure intra-chaîne"],
  39: ["le domaine Kringle"],
  40: ["le domaine Kringle"],
  41: ["l’insuline et les ponts disulfure"],
  42: ["la liaison peptidique C–N"],
  43: ["les modifications post-traductionnelles"],
  44: ["les modifications post-traductionnelles"],
  45: ["la structure secondaire"],
  46: ["la structure secondaire"],
  47: ["l’hélice α"],
  48: ["l’hélice α"],
  49: ["les repères géométriques de l’hélice α"],
  50: ["les repères géométriques de l’hélice α"],
  51: ["la stabilité de l’hélice α"],
  52: ["la stabilité de l’hélice α"],
  53: ["la myoglobine et les hélices α"],
  54: ["la myoglobine et les hélices α"],
  55: ["les feuillets β"],
  56: ["les feuillets β"],
  57: ["les chaînes latérales des feuillets β"],
  58: ["les chaînes latérales des feuillets β"],
  59: ["les immunoglobulines et feuillets β"],
  60: ["les immunoglobulines et feuillets β"],
  61: ["les coudes et boucles"],
  62: ["les coudes et boucles"],
  63: ["la structure tertiaire"],
  64: ["la structure tertiaire"],
  65: ["les forces stabilisant la structure tertiaire"],
  66: ["les forces stabilisant la structure tertiaire"],
  67: ["les domaines protéiques"],
  68: ["les domaines protéiques"],
  69: ["le domaine de fermeture éclair à leucine"],
  70: ["le domaine de fermeture éclair à leucine"],
  71: ["le domaine de fixation des nucléotides"],
  72: ["le domaine de fixation des nucléotides"],
  73: ["les zones charnières"],
  74: ["les zones charnières"],
  75: ["l’organisation des protéines globulaires"],
  76: ["l’organisation des protéines globulaires"],
  77: ["la structure quaternaire"],
  78: ["la structure quaternaire"],
  79: ["les homopolymères et hétéropolymères"],
  80: ["les homopolymères et hétéropolymères"],
  81: ["la créatine kinase CK-MM"],
  82: ["la créatine kinase CK-MM"],
  83: ["la créatine kinase CK-MB"],
  84: ["la créatine kinase CK-MB"],
  85: ["les protéines G hétérotrimériques"],
  86: ["les protéines G hétérotrimériques"],
  87: ["l’hémoglobine"],
  88: ["l’hémoglobine"],
  89: ["la hiérarchie des niveaux de structure"],
  90: ["la hiérarchie des niveaux de structure"],
  91: ["la rigidité et la flexibilité du squelette"],
  92: ["la rigidité et la flexibilité du squelette"],
  93: ["les modifications post-traductionnelles et la fonction"],
  94: ["les modifications post-traductionnelles et la fonction"],
  95: ["la stabilité tertiaire d’une protéine globulaire"],
  96: ["la stabilité tertiaire d’une protéine globulaire"],
  97: ["les complexes CK-MM, CK-MB et hémoglobine"],
  98: ["les complexes CK-MM, CK-MB et hémoglobine"],
  99: ["la dynamique moléculaire"],
  100: ["la dynamique moléculaire"],
  101: ["la liaison peptidique"],
  102: ["la liaison peptidique"],
  103: ["la dénaturation"],
  104: ["la dénaturation"],
  105: ["la liaison peptidique dans la structure primaire"],
  106: ["la liaison peptidique dans la structure primaire"],
  107: ["la carboxylation post-traductionnelle"],
  108: ["la carboxylation post-traductionnelle"],
  109: ["les ponts disulfure"],
  110: ["les ponts disulfure"],
  111: ["les repères géométriques de l’hélice α"],
  112: ["les repères géométriques de l’hélice α"],
  113: ["les feuillets β"],
  114: ["les feuillets β"],
  115: ["la structure tertiaire"],
  116: ["la structure tertiaire"],
  117: ["l’organisation des protéines globulaires"],
  118: ["l’organisation des protéines globulaires"],
  119: ["la structure quaternaire"],
  120: ["la structure quaternaire"],
  121: ["l’hémoglobine"],
  122: ["l’hémoglobine"],
};
