import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_ORDER = 2;

export const SECTION_B_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  31: ["Oxydation peut correspondre à"],
  32: ["Lors de l’oxydation du glucose en acide glucuronique"],
  33: ["En solution, la forme ionisée de l’acide glucuronique est appelée"],
  34: ["Acide glucuronique et glucuronate"],
  35: ["Glucuronoconjugaison"],
  36: ["Les substances pouvant subir une glucuronoconjugaison selon la…"],
  37: ["L’acide glucuronique entre dans la constitution de"],
  38: ["Polyol est obtenu par"],
  39: ["Réduction d’un aldose en polyol"],
  40: ["Réduction du glycéraldéhyde donne"],
  41: ["Glycérol"],
  42: ["Réduction du mannose conduit principalement au"],
  43: ["Mannitol est cité comme"],
  44: ["Réduction du glucose donne"],
  45: ["Sorbitol est utilisé notamment"],
  46: ["Comparer l’oxydation et la réduction du glucose"],
  47: ["Le test de Fehling, le sucre dit « réducteur »"],
  48: ["Dérivé du glucose porte COOH en C6 et conserve la charpente gl…"],
  49: ["Chez un patient présentant une accumulation d’une molécule lip…"],
  50: ["Bilirubine glucuronoconjuguée est plus facilement"],
  51: ["Figure illustre une transformation du glucose"],
  52: ["À partir du schéma des réductions"],
  53: ["Médicament lipophile est métabolisé par le foie puis retrouvé …"],
  54: ["Augmentation de bilirubine non conjuguée peut rappeler que"],
  55: ["Groupement carboxyle de l’acide glucuronique"],
  56: ["Pour reconnaître une réduction d’ose en polyol"],
  57: ["Molécule obtenue par réduction du mannose et utilisée comme éd…"],
  58: ["Un contexte hospitalier, une solution de mannitol peut être re…"],
  59: ["Dentifrice contient du sorbitol. On peut en déduire dans le ca…"],
  60: ["Synthèse des dérivés oxydo-réduits"],
};

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "oxydation-acide-glucuronique",
    title: "Oxydation et acide glucuronique",
    description: "Comprendre l’oxydation en C6, le glucuronate et la glucuronoconjugaison.",
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 2,
    slug: "reduction-polyols",
    title: "Réduction des oses et polyols",
    description: "Associer glycéraldéhyde, mannose et glucose à leurs polyols et à leurs usages.",
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 3,
    slug: "transformations-redox-applications",
    title: "Transformations rédox et applications",
    description: "Analyser les conséquences structurales et médicales des transformations rédox.",
    stage: 'MASTER',
    sectionOrder: 2,
    items: [
      {
        type: 'GROUP',
        title: "Lecture des transformations",
        sharedStatement: "Les questions suivantes comparent visuellement oxydation et réduction des oses.",
        questionOrders: [51, 52],
      },
      {
        type: 'GROUP',
        title: "Glucuronoconjugaison clinique",
        sharedStatement: "Un foie fonctionnel conjugue certains métabolites et médicaments à l’acide glucuronique afin de faciliter leur élimination.",
        questionOrders: [53, 54, 55],
      },
      {
        type: 'GROUP',
        title: "Polyols et usages",
        sharedStatement: "Les polyols sont obtenus par réduction des fonctions carbonyle des oses et possèdent divers usages.",
        questionOrders: [56, 57, 58, 59],
      },
      { type: 'QUESTION', questionOrder: 60 },
    ],
  },
];

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Une oxydation peut correspondre à :",
    choices: [
      "Une perte d’électrons.",
      "Une perte d’hydrogène.",
      "Un gain d’oxygène.",
      "Un gain systématique d’hydrogène.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les trois formulations usuelles d’une oxydation sont rappelées dans la fiche.",
    choiceExplanations: [
      "Vrai. C’est la définition électronique.",
      "Vrai. Une déshydrogénation est souvent une oxydation.",
      "Vrai. L’addition d’oxygène traduit souvent une oxydation.",
      "Faux. Un gain d’hydrogène correspond plutôt à une réduction.",
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Lors de l’oxydation du glucose en acide glucuronique :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-to-glucuronic-acid',
    },
    choices: [
      "Le carbone C6 est concerné.",
      "Le groupement CH2OH de C6 devient COOH.",
      "La fonction aldéhyde de C1 est nécessairement supprimée dans le schéma du cours.",
      "Un dérivé acide est formé.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’acide glucuronique résulte de l’oxydation de l’alcool primaire porté par C6.",
    choiceExplanations: [
      "Vrai. C’est la position oxydée.",
      "Vrai. L’alcool primaire devient acide carboxylique.",
      "Faux. La transformation mise en avant porte sur C6.",
      "Vrai. Le produit est un acide uronique.",
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "En solution, la forme ionisée de l’acide glucuronique est appelée :",
    choices: [
      "Glucuronate.",
      "Glucosamine.",
      "Sorbitol.",
      "Fructose-6-phosphate.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La déprotonation du COOH donne l’ion glucuronate.",
    choiceExplanations: [
      "C’est la forme carboxylate.",
      "La glucosamine est un dérivé aminé.",
      "Le sorbitol est un polyol.",
      "Le fructose-6-phosphate est un ester phosphorique.",
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Acide glucuronique et glucuronate :",
    choices: [
      "Constituent un couple acide/base.",
      "Diffèrent par l’état d’ionisation du groupement carboxyle.",
      "Peuvent être présents en solution.",
      "Sont deux épimères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glucuronate est la base conjuguée de l’acide glucuronique.",
    choiceExplanations: [
      "Vrai. Le passage implique la perte ou le gain d’un proton.",
      "Vrai. COOH devient COO−.",
      "Vrai. Leur proportion dépend notamment du pH.",
      "Faux. Il ne s’agit pas d’une différence de configuration d’un carbone asymétrique.",
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La glucuronoconjugaison :",
    choices: [
      "Contribue à solubiliser certaines substances.",
      "Facilite leur présence dans le sang et les urines.",
      "Peut favoriser leur élimination.",
      "Rend systématiquement les molécules plus hydrophobes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La conjugaison à l’acide glucuronique augmente généralement l’hydrosolubilité et facilite l’élimination.",
    choiceExplanations: [
      "Vrai. C’est son intérêt central.",
      "Vrai. Les produits deviennent plus compatibles avec les milieux aqueux.",
      "Vrai. L’excrétion urinaire ou biliaire est facilitée.",
      "Faux. L’effet recherché est généralement une augmentation de l’hydrophilie.",
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les substances pouvant subir une glucuronoconjugaison :",
    choices: [
      "La bilirubine.",
      "Certains médicaments.",
      "Des substances initialement peu solubles.",
      "Uniquement le glucose alimentaire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La bilirubine et divers médicaments sont des exemples classiques de molécules glucuronoconjuguées.",
    choiceExplanations: [
      "Vrai. Elle dérive de l’hémoglobine et doit être éliminée.",
      "Vrai. Cette voie limite leur accumulation.",
      "Vrai. La conjugaison vise notamment à les solubiliser.",
      "Faux. La voie concerne de nombreux xénobiotiques et métabolites.",
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’acide glucuronique entre dans la constitution de :",
    choices: [
      "Glycosaminoglycanes.",
      "Glycoprotéines.",
      "Protéoglycanes.",
      "Glycolipides.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les quatre familles sont citées comme structures pouvant contenir des dérivés glucuroniques.",
    choiceExplanations: [
      "Vrai. Les GAG contiennent souvent un acide uronique.",
      "Vrai. Certains glycannes de glycoprotéines en contiennent.",
      "Vrai. Les protéoglycanes portent des GAG.",
      "Vrai. Des glycolipides peuvent également contenir ce motif.",
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Un polyol est obtenu par :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'polyol-reductions',
    },
    choices: [
      "Réduction d’une fonction carbonyle d’un ose en fonction alcool.",
      "Oxydation d’un alcool en acide carboxylique.",
      "Formation d’une liaison peptidique.",
      "Estérification d’un stérol.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La réduction d’un aldéhyde ou d’une cétone de l’ose donne un alcool supplémentaire.",
    choiceExplanations: [
      "C’est la définition donnée.",
      "Cette transformation produit plutôt un dérivé oxydé.",
      "Elle concerne les acides aminés.",
      "Elle concerne les stérides.",
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La réduction d’un aldose en polyol :",
    choices: [
      "Transforme la fonction aldéhyde de C1 en alcool primaire.",
      "Augmente le nombre de fonctions alcool.",
      "Supprime le caractère carbonylé de cette fonction.",
      "Produit nécessairement un acide uronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La réduction convertit le carbonyle en alcool sans former d’acide.",
    choiceExplanations: [
      "Vrai. C’est le cas du glycéraldéhyde vers le glycérol.",
      "Vrai. Une fonction alcool est créée.",
      "Vrai. Le groupe C=O est réduit.",
      "Faux. L’acide uronique résulte d’une oxydation.",
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La réduction du glycéraldéhyde donne :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'polyol-reductions',
    },
    choices: [
      "Du glycérol.",
      "Du glucuronate.",
      "De la glucosamine.",
      "Du ribose-5-phosphate.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Le glycéraldéhyde réduit conduit au triol glycérol.",
    choiceExplanations: [
      "C’est le produit à retenir.",
      "Le glucuronate vient de l’oxydation du glucose.",
      "La glucosamine est un dérivé aminé.",
      "Le ribose-5-phosphate est un ester phosphorique.",
    ],
  },
  {
    order: 41,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le glycérol :",
    choices: [
      "Constitue la charpente des triglycérides.",
      "Est utilisé sous forme de glycérine dans des produits pharmaceutiques.",
      "Est un polyol à trois carbones.",
      "Est obtenu par oxydation du glycéraldéhyde selon la fiche.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glycérol est un triol important, produit de réduction du glycéraldéhyde et squelette des triglycérides.",
    choiceExplanations: [
      "Vrai. Les acides gras estérifient ses OH.",
      "Vrai. La glycérine est un usage cité.",
      "Vrai. Il porte trois fonctions alcool.",
      "Faux. Il est obtenu par réduction.",
    ],
  },
  {
    order: 42,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La réduction du mannose conduit principalement au :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'polyol-reductions',
    },
    choices: [
      "Mannitol.",
      "Sorbitol.",
      "Glucuronate.",
      "NANA.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Le polyol correspondant au mannose est le mannitol.",
    choiceExplanations: [
      "C’est le produit à retenir.",
      "Le sorbitol dérive ici du glucose.",
      "Le glucuronate est un produit d’oxydation.",
      "Le NANA est un dérivé aminé complexe.",
    ],
  },
  {
    order: 43,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le mannitol est cité comme :",
    choices: [
      "Édulcorant.",
      "Produit pouvant être utilisé en solution intraveineuse dans certaines situations.",
      "Dérivé de réduction du mannose.",
      "Acide uronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le mannitol est un polyol utilisé notamment comme édulcorant et dans certaines solutions intraveineuses.",
    choiceExplanations: [
      "Vrai. Son goût sucré permet cet usage.",
      "Vrai. L’usage médical est mentionné.",
      "Vrai. C’est son origine structurale.",
      "Faux. Il ne porte pas de fonction acide carboxylique.",
    ],
  },
  {
    order: 44,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La réduction du glucose donne :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'polyol-reductions',
    },
    choices: [
      "Le sorbitol.",
      "Le mannitol exclusivement.",
      "L’acide glucuronique.",
      "La glucosamine.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Le sorbitol est le polyol issu de la réduction du glucose.",
    choiceExplanations: [
      "C’est le produit attendu.",
      "Le mannitol est relié au mannose dans la fiche.",
      "L’acide glucuronique vient d’une oxydation.",
      "La glucosamine implique une substitution par NH2.",
    ],
  },
  {
    order: 45,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le sorbitol est utilisé notamment :",
    choices: [
      "Comme édulcorant.",
      "Comme agent humectant dans des préparations alimentaires.",
      "Dans des dentifrices pour le goût et la sensation de fraîcheur.",
      "Comme antibiotique aminoglycoside.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le sorbitol a des usages alimentaires et bucco-dentaires liés à ses propriétés physiques et gustatives.",
    choiceExplanations: [
      "Vrai. Il peut remplacer le saccharose.",
      "Vrai. Son pouvoir humidifiant est cité.",
      "Vrai. Cet usage figure dans la fiche.",
      "Faux. La streptomycine est un antibiotique, pas le sorbitol.",
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer l’oxydation et la réduction du glucose :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-to-glucuronic-acid',
    },
    choices: [
      "L’oxydation de C6 peut donner l’acide glucuronique.",
      "La réduction de la fonction carbonyle peut donner le sorbitol.",
      "Les deux transformations donnent le même produit.",
      "L’une produit un dérivé acide, l’autre un polyol.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’orientation redox détermine deux familles de dérivés distinctes.",
    choiceExplanations: [
      "Vrai. C6 passe de CH2OH à COOH.",
      "Vrai. Le carbonyle est converti en alcool.",
      "Faux. Les produits et fonctions obtenus diffèrent.",
      "Vrai. C’est la distinction fondamentale.",
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans le test de Fehling, le sucre dit « réducteur » :",
    choices: [
      "Réduit les ions cuivre(II).",
      "Est lui-même oxydé.",
      "Peut conduire à un carboxylate.",
      "Est obligatoirement transformé en polyol.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le qualificatif « réducteur » décrit l’action sur le cuivre, tandis que le sucre s’oxyde.",
    choiceExplanations: [
      "Vrai. Cu2+ est réduit.",
      "Vrai. Le donneur d’électrons s’oxyde.",
      "Vrai. L’aldéhyde peut devenir carboxylate.",
      "Faux. Une réduction en polyol est une autre réaction.",
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un dérivé du glucose porte COOH en C6 et conserve la charpente glucidique :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-to-glucuronic-acid',
    },
    choices: [
      "Il peut s’agir d’acide glucuronique.",
      "Il résulte d’une oxydation.",
      "Sa forme ionisée est le glucuronate.",
      "Il s’agit nécessairement de sorbitol.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La signature structurale correspond à l’acide glucuronique et à sa base conjuguée.",
    choiceExplanations: [
      "Vrai. C’est la définition structurale.",
      "Vrai. L’alcool primaire a été oxydé.",
      "Vrai. COOH peut perdre H+.",
      "Faux. Le sorbitol ne possède pas ce COOH.",
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Chez un patient présentant une accumulation d’une molécule lipophile, une glucuronoconjugaison efficace peut :",
    choices: [
      "Augmenter sa solubilité aqueuse.",
      "Faciliter son excrétion.",
      "Limiter son accumulation.",
      "La transformer obligatoirement en protéine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La glucuronoconjugaison est une voie de détoxication et d’élimination de nombreux composés.",
    choiceExplanations: [
      "Vrai. Le groupement glucuronique est hydrophile.",
      "Vrai. L’élimination urinaire ou biliaire est favorisée.",
      "Vrai. C’est un bénéfice métabolique attendu.",
      "Faux. Aucune synthèse protéique n’est impliquée.",
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: "La bilirubine glucuronoconjuguée est plus facilement :",
    choices: [
      "Éliminée.",
      "Stockée dans le tissu adipeux.",
      "Transformée en acide aminé.",
      "Incorporée à l’ADN.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La conjugaison rend la bilirubine plus soluble et favorise son élimination.",
    choiceExplanations: [
      "C’est l’intérêt de la réaction.",
      "La glucuronoconjugaison ne vise pas le stockage lipidique.",
      "Elle ne produit pas un acide aminé.",
      "Elle n’insère pas la bilirubine dans l’ADN.",
    ],
  },
  {
    order: 51,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La figure illustre une transformation du glucose :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-to-glucuronic-acid',
    },
    choices: [
      "Le groupement terminal C6 est oxydé.",
      "Un groupement COOH apparaît.",
      "Le produit est un acide uronique.",
      "Le produit est le mannitol.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le passage de CH2OH à COOH en C6 produit l’acide glucuronique.",
    choiceExplanations: [
      "Vrai. C6 est la position indiquée.",
      "Vrai. C’est la nouvelle fonction.",
      "Vrai. Les acides uroniques portent cette oxydation terminale.",
      "Faux. Le mannitol est un polyol.",
    ],
  },
  {
    order: 52,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À partir du schéma des réductions :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'polyol-reductions',
    },
    choices: [
      "Glycéraldéhyde et glycérol forment un couple ose/polyol.",
      "Mannose et mannitol forment un couple ose/polyol.",
      "Glucose et sorbitol forment un couple ose/polyol.",
      "Toutes les flèches représentent des oxydations.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les trois couples illustrent la réduction d’une fonction carbonyle en alcool.",
    choiceExplanations: [
      "Vrai. Le glycéraldéhyde donne le glycérol.",
      "Vrai. Le mannose donne le mannitol.",
      "Vrai. Le glucose donne le sorbitol.",
      "Faux. Il s’agit de réductions.",
    ],
  },
  {
    order: 53,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un médicament lipophile est métabolisé par le foie puis retrouvé sous forme glucuronoconjuguée :",
    choices: [
      "La transformation favorise généralement son hydrosolubilité.",
      "Elle peut faciliter son élimination urinaire.",
      "L’acide glucuronique participe au conjugué.",
      "Cette transformation correspond à la réduction du médicament en polyol.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La glucuronoconjugaison ajoute un motif hydrophile et facilite l’élimination de nombreux médicaments.",
    choiceExplanations: [
      "Vrai. C’est le but principal.",
      "Vrai. Un conjugué soluble est plus facilement excrété.",
      "Vrai. Il fournit le motif glucuronique.",
      "Faux. Il s’agit d’une conjugaison, non d’une simple réduction en polyol.",
    ],
  },
  {
    order: 54,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une augmentation de bilirubine non conjuguée peut rappeler que :",
    choices: [
      "La bilirubine est un exemple de substrat de glucuronoconjugaison.",
      "La conjugaison intervient notamment au foie.",
      "La forme conjuguée est plus facilement éliminable.",
      "La bilirubine est un polyol issu du mannose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La bilirubine illustre l’importance clinique de la glucuronoconjugaison hépatique.",
    choiceExplanations: [
      "Vrai. C’est l’exemple majeur de la fiche.",
      "Vrai. Le foie joue un rôle central.",
      "Vrai. La solubilité et l’excrétion sont améliorées.",
      "Faux. Elle dérive de l’hémoglobine.",
    ],
  },
  {
    order: 55,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos du groupement carboxyle de l’acide glucuronique :",
    choices: [
      "Il peut être protoné sous forme COOH.",
      "Il peut être déprotoné sous forme COO−.",
      "Sa déprotonation produit le glucuronate.",
      "Il est identique à une fonction amine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le groupement carboxyle explique le couple acide glucuronique/glucuronate.",
    choiceExplanations: [
      "Vrai. C’est la forme acide.",
      "Vrai. C’est la forme ionisée.",
      "Vrai. Le nom de l’anion est glucuronate.",
      "Faux. Une amine contient de l’azote.",
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Pour reconnaître une réduction d’ose en polyol :",
    choices: [
      "La fonction carbonyle disparaît au profit d’un alcool.",
      "Le nombre de fonctions alcool augmente.",
      "Aucun COOH n’est nécessairement créé.",
      "Le produit devient obligatoirement un ose phosphorylé.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La réduction traite le carbonyle et aboutit à un composé polyhydroxylé.",
    choiceExplanations: [
      "Vrai. C=O devient C–OH.",
      "Vrai. L’alcool créé s’ajoute aux autres OH.",
      "Vrai. Une fonction acide n’est pas le résultat de cette réduction.",
      "Faux. La phosphorylation est une estérification distincte.",
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: "Une molécule obtenue par réduction du mannose et utilisée comme édulcorant est :",
    choices: [
      "Le mannitol.",
      "Le glucuronate.",
      "La N-acétylglucosamine.",
      "L’acide ascorbique.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La réduction du mannose produit le mannitol.",
    choiceExplanations: [
      "C’est le dérivé et l’usage attendus.",
      "Le glucuronate est oxydé et acide.",
      "La N-acétylglucosamine est aminée et acétylée.",
      "L’acide ascorbique dérive du L-gulose après plusieurs transformations.",
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Dans un contexte hospitalier, une solution de mannitol peut être reliée aux notions suivantes :",
    choices: [
      "Polyol.",
      "Dérivé de réduction d’un ose.",
      "Dérivé du mannose dans la fiche.",
      "Acide carboxylique fortement ionisé.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le mannitol est un polyol issu de la réduction du mannose et possède des usages médicaux.",
    choiceExplanations: [
      "Vrai. Il ne porte plus de carbonyle.",
      "Vrai. C’est sa famille de transformation.",
      "Vrai. C’est le précurseur indiqué.",
      "Faux. Le mannitol ne porte pas de COOH.",
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un dentifrice contient du sorbitol. On peut en déduire :",
    choices: [
      "Qu’il s’agit d’un polyol.",
      "Qu’il peut contribuer au goût sucré.",
      "Qu’il dérive de la réduction du glucose.",
      "Qu’il est un acide uronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le sorbitol est un polyol du glucose utilisé notamment pour ses propriétés gustatives et humectantes.",
    choiceExplanations: [
      "Vrai. Sa fonction carbonyle a été réduite.",
      "Vrai. Cet usage est cité.",
      "Vrai. Le glucose est son ose de départ.",
      "Faux. Il ne porte pas de COOH terminal.",
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Synthèse des dérivés oxydo-réduits :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'polyol-reductions',
    },
    choices: [
      "Glucose oxydé en C6 peut donner l’acide glucuronique.",
      "Glucose réduit peut donner le sorbitol.",
      "Mannose réduit peut donner le mannitol.",
      "Glycéraldéhyde oxydé donne nécessairement le glycérol.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Oxydation et réduction conduisent à des familles distinctes : acides uroniques ou polyols.",
    choiceExplanations: [
      "Vrai. CH2OH devient COOH.",
      "Vrai. Le carbonyle devient alcool.",
      "Vrai. C’est le couple à retenir.",
      "Faux. Le glycérol résulte d’une réduction.",
    ],
  },
];
