import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SYNTHESIS_SECTION_ORDER = 5;

export const SYNTHESIS_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  121: ["Synthèse liaison et pouvoir réducteur"],
  122: ["Synthèse diholosides"],
  123: ["Synthèse hydrolyse enzymatique"],
  124: ["Synthèse glucanes de réserve"],
  125: ["Synthèse amidon et digestion"],
  126: ["Synthèse glycogène"],
  127: ["Synthèse cellulose"],
  128: ["Synthèse GAG"],
  129: ["Synthèse acide hyaluronique"],
  130: ["Synthèse chondroïtine et dermatane"],
  131: ["Synthèse kératane"],
  132: ["Synthèse héparane et héparine"],
  133: ["Synthèse protéoglycanes"],
  134: ["Synthèse glycoprotéines"],
  135: ["Synthèse charges négatives"],
  136: ["Synthèse clinique héparine"],
  137: ["Synthèse fécondation"],
  138: ["Synthèse groupes sanguins"],
  139: ["Synthèse classification"],
  140: ["Synthèse générale des osides"],
};

export const SYNTHESIS_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "synthese-structures-et-liaisons",
    title: "Structures, liaisons et digestion",
    description: "Croiser diholosides, glucanes, cellulose et GAG.",
    stage: 'PRACTICE',
    sectionOrder: 5,
    items: [
      {
        type: 'GROUP',
        title: "Diholosides et hydrolyse",
        sharedStatement: "Les questions suivantes portent sur le pouvoir réducteur, les liaisons et les enzymes.",
        questionOrders: [121, 122, 123],
      },
      {
        type: 'GROUP',
        title: "Glucanes de réserve et cellulose",
        sharedStatement: "Les questions suivantes comparent amidon, glycogène et cellulose.",
        questionOrders: [124, 125, 126, 127],
      },
      {
        type: 'GROUP',
        title: "Premiers GAG",
        sharedStatement: "Les questions suivantes mobilisent la structure générale, l’acide hyaluronique et la chondroïtine.",
        questionOrders: [128, 129, 130],
      },
    ],
  },
  {
    order: 2,
    slug: "synthese-fonctions-biologiques",
    title: "Fonctions biologiques et applications",
    description: "Mobiliser les GAG sulfatés, les glycoconjugués et les applications biologiques ou cliniques.",
    stage: 'MASTER',
    sectionOrder: 5,
    items: [
      {
        type: 'GROUP',
        title: "GAG sulfatés",
        sharedStatement: "Les questions suivantes comparent kératane, héparane et héparine.",
        questionOrders: [131, 132],
      },
      {
        type: 'GROUP',
        title: "Glycoconjugués et charges",
        sharedStatement: "Les questions suivantes portent sur protéoglycanes, glycoprotéines et charges négatives.",
        questionOrders: [133, 134, 135],
      },
      {
        type: 'GROUP',
        title: "Applications biologiques et cliniques",
        sharedStatement: "Les questions suivantes mobilisent anticoagulation, fécondation et reconnaissance cellulaire.",
        questionOrders: [136, 137, 138],
      },
      {
        type: 'GROUP',
        title: "Classification et synthèse générale",
        sharedStatement: "Les questions suivantes concluent le chapitre de façon transversale.",
        questionOrders: [139, 140],
      },
    ],
  },
];

export const SYNTHESIS_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un diholoside est non réducteur lorsque :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycosidic-condensation',
    },
    choices: [
      "Ses deux fonctions hémiacétaliques sont engagées dans la liaison.",
      "Il ne conserve aucun carbone anomérique libre.",
      "Il correspond au modèle du saccharose.",
      "Il possède nécessairement une liaison β(1→4) libre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le caractère non réducteur découle de l’engagement des deux centres anomériques.",
    choiceExplanations: [
      "Vrai. Aucun centre ne peut s’ouvrir.",
      "Vrai. C’est la conséquence structurale.",
      "Vrai. Le saccharose est l’exemple du cours.",
      "Faux. Une liaison β1,4 comme dans le lactose laisse un centre libre.",
    ],
  },
  {
    order: 122,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Parmi les associations correctes :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Lactose — galactose + glucose — β(1→4).",
      "Saccharose — glucose + fructose — liaison (1→2).",
      "Maltose — glucose + glucose — α(1→4).",
      "Cellobiose — galactose + fructose — α(1→6).",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les trois diholosides principaux se distinguent par leur composition et leur liaison.",
    choiceExplanations: [
      "Vrai. C’est la structure du lactose.",
      "Vrai. Les deux centres anomériques sont engagés.",
      "Vrai. C’est la structure du maltose.",
      "Faux. La cellobiose contient deux β-D-glucoses en β1,4.",
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une enzyme qui hydrolyse spécifiquement une liaison β-galactosidique du lactose :",
    choices: [
      "Peut être appelée lactase.",
      "Peut être appelée β-galactosidase.",
      "Libère glucose et galactose.",
      "Hydrolyse nécessairement l’amidon en maltose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La lactase est une β-galactosidase spécifique du lactose.",
    choiceExplanations: [
      "Vrai. C’est son nom usuel.",
      "Vrai. C’est son nom fonctionnel.",
      "Vrai. Ce sont les produits attendus.",
      "Faux. L’amidon nécessite des amylases.",
    ],
  },
  {
    order: 124,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un polymère de glucose ramifié comportant des liaisons α(1→4) et α(1→6) peut correspondre :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'starch-amylose-amylopectin',
    },
    choices: [
      "À l’amylopectine.",
      "Au glycogène.",
      "À l’amylose strictement linéaire.",
      "À une réserve glucidique.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Amylopectine et glycogène sont des glucanes ramifiés de réserve.",
    choiceExplanations: [
      "Vrai. C’est la fraction ramifiée de l’amidon.",
      "Vrai. C’est la réserve animale.",
      "Faux. L’amylose ne comporte pas de branches.",
      "Vrai. Les deux stockent du glucose.",
    ],
  },
  {
    order: 125,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "À propos de l’amidon :",
    choices: [
      "Il contient amylose et amylopectine.",
      "Les α-amylases hydrolysent les segments α(1→4).",
      "Une activité débranchante agit sur les liaisons α(1→6).",
      "Il est entièrement constitué de liaisons β(1→4).",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La digestion de l’amidon nécessite de traiter les chaînes et les embranchements.",
    choiceExplanations: [
      "Vrai. Ce sont ses deux fractions.",
      "Vrai. Elles coupent les chaînes principales.",
      "Vrai. Elle élimine les branches.",
      "Faux. β1,4 correspond à la cellulose.",
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le glycogène :",
    choices: [
      "Est associé à une protéine appelée glycogénine.",
      "Est particulièrement abondant dans le muscle et le foie.",
      "Est plus compact que l’amylose linéaire.",
      "Est la réserve végétale des amyloplastes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glycogène est une réserve animale compacte et ramifiée construite autour de la glycogénine.",
    choiceExplanations: [
      "Vrai. La chaîne y est fixée.",
      "Vrai. Ces tissus sont cités.",
      "Vrai. Sa forte ramification favorise une structure compacte.",
      "Faux. Cette description appartient à l’amidon.",
    ],
  },
  {
    order: 127,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "La cellulose et le maltose se distinguent notamment par :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'cellulose-cellobiose',
    },
    choices: [
      "La configuration β(1→4) pour la cellobiose.",
      "La configuration α(1→4) pour le maltose.",
      "La digestibilité humaine différente de leurs polymères associés.",
      "La présence de glucose dans un seul des deux.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La seule différence α/β de la liaison modifie fortement les propriétés et la digestion.",
    choiceExplanations: [
      "Vrai. C’est le motif de la cellulose.",
      "Vrai. C’est le maltose.",
      "Vrai. L’Homme ne digère pas la cellulose.",
      "Faux. Les deux sont composés de glucose.",
    ],
  },
  {
    order: 128,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un GAG typique du cours :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'gag-basic-repeat',
    },
    choices: [
      "Comporte des motifs glucidiques répétés.",
      "Peut associer une osamine et un acide uronique.",
      "Peut porter des charges négatives.",
      "Est obligatoirement une protéine pure.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les GAG sont des hétéroglycanes chargés formant de longues chaînes.",
    choiceExplanations: [
      "Vrai. La répétition est fondamentale.",
      "Vrai. C’est le motif général.",
      "Vrai. COO⁻ et sulfates y contribuent.",
      "Faux. Ils sont glucidiques.",
    ],
  },
  {
    order: 129,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "L’acide hyaluronique :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'hyaluronic-chondroitin',
    },
    choices: [
      "N’est pas sulfaté.",
      "N’est pas lié à une protéine dans la forme décrite.",
      "Peut comporter plusieurs milliers de résidus.",
      "Est l’anticoagulant puissant des mastocytes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’acide hyaluronique est un très long GAG simple et non sulfaté.",
    choiceExplanations: [
      "Vrai. C’est sa particularité.",
      "Vrai. Il peut rester libre.",
      "Vrai. n peut atteindre 5 000.",
      "Faux. Cette description correspond à l’héparine.",
    ],
  },
  {
    order: 130,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Comparer chondroïtine et dermatane sulfate :",
    choices: [
      "Les deux contiennent de la N-acétylgalactosamine.",
      "La chondroïtine contient de l’acide D-glucuronique.",
      "Le dermatane contient de l’acide L-iduronique.",
      "Les deux sont non sulfatés.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux GAG partagent l’osamine mais diffèrent par l’acide uronique et restent sulfatés.",
    choiceExplanations: [
      "Vrai. C’est le résidu commun.",
      "Vrai. C’est l’acide de la chondroïtine.",
      "Vrai. C’est l’acide du dermatane.",
      "Faux. Ils portent des sulfates.",
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Le kératane sulfate se singularise car :",
    choices: [
      "Il associe galactose et N-acétylglucosamine.",
      "Il ne comporte pas d’acide uronique dans le motif donné.",
      "Il peut être sulfaté en C6 sur les deux types de résidus.",
      "Il est constitué d’acide hyaluronique uniquement.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le kératane est le GAG du cours dont le motif associe un ose simple et une osamine.",
    choiceExplanations: [
      "Vrai. C’est sa composition.",
      "Vrai. Cela le distingue des GAG à acide uronique.",
      "Vrai. Les deux positions C6 sont indiquées.",
      "Faux. Ce sont deux GAG distincts.",
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "L’héparine est distinguée de l’héparane sulfate par :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "Des chaînes plus courtes dans la fiche.",
      "Une sulfatation beaucoup plus importante.",
      "Une activité anticoagulante utilisée en thérapeutique.",
      "Une absence totale de glucosamine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’héparine est une forme courte, très sulfatée et anticoagulante.",
    choiceExplanations: [
      "Vrai. Environ 10 résidus.",
      "Vrai. La fiche note une forte sulfatation.",
      "Vrai. C’est son usage clinique.",
      "Faux. La glucosamine appartient à cette famille structurale.",
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un agrégat de protéoglycanes :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'proteoglycan-aggregate',
    },
    choices: [
      "Peut s’organiser autour d’un filament d’acide hyaluronique.",
      "Comporte plusieurs protéines cœur portant des GAG.",
      "Contribue à l’hydratation et à l’amortissement.",
      "Est un simple diholoside non lié à une protéine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les agrégats de protéoglycanes forment de grandes structures hydratées de la matrice.",
    choiceExplanations: [
      "Vrai. C’est l’axe de l’agrégat.",
      "Vrai. Chaque unité comporte une protéine cœur.",
      "Vrai. Ce sont des rôles cités.",
      "Faux. La structure est macromoléculaire et protéique.",
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une glycoprotéine peut :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycoprotein-linkages',
    },
    choices: [
      "Porter des chaînes glucidiques ramifiées.",
      "Être O-glycosylée sur une sérine ou une thréonine.",
      "Être N-glycosylée sur une fonction amide citée dans la fiche.",
      "Être dépourvue de toute fraction protéique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les glycoprotéines associent une protéine à des oligosaccharides liés par O ou N.",
    choiceExplanations: [
      "Vrai. C’est une caractéristique structurale.",
      "Vrai. Les fonctions alcool servent d’ancrage.",
      "Vrai. L’asparagine est notamment citée.",
      "Faux. La protéine est une fraction essentielle.",
    ],
  },
  {
    order: 135,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les charges négatives des GAG peuvent provenir :",
    choices: [
      "Des groupements carboxylates COO⁻.",
      "Des groupements sulfates.",
      "De la répétition de ces groupes le long de la chaîne.",
      "D’une absence complète de fonctions ionisables.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les carboxylates et sulfates confèrent un caractère polyanionique aux GAG.",
    choiceExplanations: [
      "Vrai. Les acides uroniques y contribuent.",
      "Vrai. Les GAG sulfatés en portent de nombreux.",
      "Vrai. La répétition amplifie la charge globale.",
      "Faux. Ces fonctions sont précisément ionisables.",
    ],
  },
  {
    order: 136,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Dans un contexte de risque thrombotique, le composé du chapitre ayant une utilisation médicamenteuse anticoagulante est :",
    choices: [
      "L’héparine.",
      "L’amylose.",
      "La cellulose.",
      "Le saccharose.",
    ],
    correctChoiceIndexes: [0],
    explanation: "L’héparine est le GAG fortement sulfaté utilisé comme anticoagulant.",
    choiceExplanations: [
      "C’est la réponse attendue.",
      "L’amylose est un glucane alimentaire.",
      "La cellulose est une fibre structurale.",
      "Le saccharose est un diholoside alimentaire.",
    ],
  },
  {
    order: 137,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La dégradation de l’acide hyaluronique par une enzyme du sperme illustre :",
    choices: [
      "L’action d’une hyaluronidase.",
      "Une étape facilitant la pénétration du spermatozoïde.",
      "Un rôle biologique d’un GAG dans la matrice.",
      "La synthèse de glycogène par la glycogénine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Cet exemple relie un GAG extracellulaire, son enzyme et la fécondation.",
    choiceExplanations: [
      "Vrai. C’est l’enzyme citée.",
      "Vrai. C’est la conséquence indiquée.",
      "Vrai. L’acide hyaluronique est un composant de la MEC.",
      "Faux. Ce mécanisme est sans rapport.",
    ],
  },
  {
    order: 138,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La spécificité des groupes sanguins est reliée dans la fiche :",
    choices: [
      "À la fraction glucidique de glycoprotéines.",
      "À des phénomènes de reconnaissance spécifique.",
      "À des motifs de surface cellulaire.",
      "À l’absence de tout glucide membranaire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les motifs glucidiques de surface participent à la reconnaissance et aux groupes sanguins.",
    choiceExplanations: [
      "Vrai. Ce rôle est cité.",
      "Vrai. Les déterminants sont reconnus spécifiquement.",
      "Vrai. Les glycoprotéines se trouvent notamment à la surface.",
      "Faux. Les glucides de surface sont au contraire essentiels.",
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Parmi les classifications correctes :",
    choices: [
      "Amidon — homoglycane.",
      "GAG — hétéroglycane.",
      "Glycoprotéine — hétéroside.",
      "Saccharose — protéoglycane.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les catégories reposent sur la nature des résidus et la présence éventuelle d’un aglycone.",
    choiceExplanations: [
      "Vrai. Il répète du glucose.",
      "Vrai. Il associe plusieurs dérivés d’oses.",
      "Vrai. Il associe glucides et protéine.",
      "Faux. Le saccharose est un diholoside.",
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une synthèse globale du chapitre comprend :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osides-classification',
    },
    choices: [
      "Les liaisons osidiques déterminent en partie le pouvoir réducteur et la digestibilité.",
      "Les ramifications distinguent amylose, amylopectine et glycogène.",
      "Les charges des GAG contribuent à leurs propriétés tissulaires.",
      "Tous les osides sont des molécules identiques ayant le même rôle.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La structure, la liaison et la composition expliquent les propriétés très diverses des osides.",
    choiceExplanations: [
      "Vrai. Les exemples du saccharose et de la cellulose l’illustrent.",
      "Vrai. Le degré de branchement est déterminant.",
      "Vrai. Les COO⁻ et sulfates favorisent hydratation et interactions.",
      "Faux. Le chapitre montre une grande diversité structurale et fonctionnelle.",
    ],
  },
];
