/** Cartographie éditoriale V2 — auteur */

export const UE14_BIOCH_CH14_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-catalyseurs-specificite",
    "title": "Catalyseurs et spécificité enzymatique",
    "description": "Repères sur nature des catalyseurs, pouvoir catalytique, affinité et spécificité.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-affinite-proteases",
    "title": "Affinité et spécificité des enzymes",
    "description": "Applications comparant subtilisine, trypsine, thrombine et interactions enzyme-substrat.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-cofacteurs-coenzymes",
    "title": "Cofacteurs et coenzymes",
    "description": "Repères sur apoenzyme, holoenzyme, cofacteurs, vitamines et exemples de coenzymes.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-nomenclature-isoenzymes",
    "title": "Nomenclature EC et isoenzymes",
    "description": "Applications sur code EC, six classes enzymatiques, terminologie locale et isoenzymes.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-fisher-koshland-energie",
    "title": "Interaction enzyme-substrat et énergie d’activation",
    "description": "Repères sur Fisher, Koshland, énergie d’activation et complexes ES/EP.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-site-actif-chymotrypsine",
    "title": "Site actif et chymotrypsine",
    "description": "Applications sur site actif, triade Ser-His-Asp et mécanisme de la chymotrypsine.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-regulation-allosterie",
    "title": "Régulation enzymatique et allostérie",
    "description": "Repères sur les cinq stratégies de régulation et le site allostérique.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-pka-proteolyse",
    "title": "PKA et protéolyse limitée",
    "description": "Applications sur PKA, sous-unités régulatrices, modifications et protéolyse limitée.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-regulation-enzymatique",
    "title": "Maîtrise de la régulation enzymatique",
    "description": "Maîtrise transversale des différents niveaux de régulation d’une activité enzymatique.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-enzymes-proprietes-regulation",
    "title": "Synthèse : propriétés et régulation enzymatique",
    "description": "Consolidation des propriétés, cofacteurs, mécanismes et régulations.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-enzymes-proprietes-regulation",
    "title": "Synthèse : propriétés et régulation enzymatique",
    "description": "Maîtrise du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH14_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["la définition d’un catalyseur"],
  2: ["la catalyse hétérogène et homogène"],
  3: ["les enzymes protéiques et les ribozymes"],
  4: ["le pouvoir catalytique des enzymes"],
  5: ["la spécificité enzymatique"],
  6: ["la subtilisine"],
  7: ["la trypsine"],
  8: ["la thrombine"],
  9: ["les interactions enzyme-substrat"],
  10: ["la forte affinité enzyme-substrat"],
  11: ["les enzymes protéiques et les ribozymes"],
  12: ["le pouvoir catalytique des enzymes"],
  13: ["la spécificité enzymatique"],
  14: ["la subtilisine"],
  15: ["la trypsine"],
  16: ["le pouvoir catalytique des enzymes"],
  17: ["les interactions enzyme-substrat"],
  18: ["la forte affinité enzyme-substrat"],
  19: ["la définition d’un catalyseur"],
  20: ["la catalyse hétérogène et homogène"],
  21: ["la définition d’un catalyseur", "la catalyse hétérogène et homogène", "les enzymes protéiques et les ribozymes"],
  22: ["la catalyse hétérogène et homogène", "les enzymes protéiques et les ribozymes", "le pouvoir catalytique des enzymes", "la spécificité enzymatique", "la subtilisine"],
  23: ["l’apoenzyme, le cofacteur et l’holoenzyme"],
  24: ["les coenzymes"],
  25: ["les groupements prosthétiques et les cofacteurs labiles"],
  26: ["les exemples de cofacteurs métalliques et organiques"],
  27: ["le PLP et la vitamine B6"],
  28: ["l’ALAT"],
  29: ["les vitamines B2 et B3 comme précurseurs de coenzymes"],
  30: ["la nomenclature EC"],
  31: ["les six classes enzymatiques de la fiche"],
  32: ["la distinction lyases-ligases selon la fiche"],
  33: ["les groupements prosthétiques et les cofacteurs labiles"],
  34: ["les exemples de cofacteurs métalliques et organiques"],
  35: ["le PLP et la vitamine B6"],
  36: ["l’ALAT"],
  37: ["les vitamines B2 et B3 comme précurseurs de coenzymes"],
  38: ["l’apoenzyme, le cofacteur et l’holoenzyme"],
  39: ["les six classes enzymatiques de la fiche"],
  40: ["la distinction lyases-ligases selon la fiche"],
  41: ["la nomenclature EC"],
  42: ["l’apoenzyme, le cofacteur et l’holoenzyme"],
  43: ["les isoenzymes", "l’apoenzyme, le cofacteur et l’holoenzyme", "les coenzymes"],
  44: ["l’apoenzyme, le cofacteur et l’holoenzyme", "les coenzymes", "les groupements prosthétiques et les cofacteurs labiles", "les exemples de cofacteurs métalliques et organiques", "le PLP et la vitamine B6"],
  45: ["le modèle clé-serrure de Fisher"],
  46: ["le modèle d’ajustement induit de Koshland"],
  47: ["l’énergie d’activation sans enzyme"],
  48: ["l’effet d’une enzyme sur l’énergie d’activation"],
  49: ["les complexes ES et EP"],
  50: ["les effets entropiques et interactions lors de la fixation"],
  51: ["le site de fixation et le site catalytique"],
  52: ["la spécificité de la chymotrypsine dans la fiche"],
  53: ["la triade catalytique de la chymotrypsine"],
  54: ["les intermédiaires de la chymotrypsine"],
  55: ["l’énergie d’activation sans enzyme"],
  56: ["l’effet d’une enzyme sur l’énergie d’activation"],
  57: ["les complexes ES et EP"],
  58: ["les effets entropiques et interactions lors de la fixation"],
  59: ["le site de fixation et le site catalytique"],
  60: ["le site de fixation et le site catalytique"],
  61: ["la triade catalytique de la chymotrypsine"],
  62: ["les intermédiaires de la chymotrypsine"],
  63: ["la triade catalytique de la chymotrypsine"],
  64: ["le modèle clé-serrure de Fisher"],
  65: ["la régénération de la triade catalytique", "le modèle clé-serrure de Fisher", "le modèle d’ajustement induit de Koshland"],
  66: ["le modèle clé-serrure de Fisher", "le modèle d’ajustement induit de Koshland", "l’énergie d’activation sans enzyme", "l’effet d’une enzyme sur l’énergie d’activation", "les complexes ES et EP"],
  67: ["les stratégies de régulation enzymatique"],
  68: ["le site allostérique"],
  69: ["les conformations active et inactive"],
  70: ["l’enzyme allostérique monomérique"],
  71: ["l’enzyme allostérique dimérique"],
  72: ["la régulation de la PKA par l’AMPc"],
  73: ["la sous-unité régulatrice de la PKA"],
  74: ["la modification covalente comme stratégie de régulation"],
  75: ["la dégradation enzymatique comme régulation"],
  76: ["la protéolyse limitée"],
  77: ["les conformations active et inactive"],
  78: ["l’enzyme allostérique monomérique"],
  79: ["l’enzyme allostérique dimérique"],
  80: ["la régulation de la PKA par l’AMPc"],
  81: ["la sous-unité régulatrice de la PKA"],
  82: ["les stratégies de régulation enzymatique"],
  83: ["la dégradation enzymatique comme régulation"],
  84: ["la protéolyse limitée"],
  85: ["la régulation de la PKA par l’AMPc"],
  86: ["les stratégies de régulation enzymatique"],
  87: ["la cascade d’activation des enzymes digestives", "les stratégies de régulation enzymatique", "le site allostérique"],
  88: ["les stratégies de régulation enzymatique", "le site allostérique", "les conformations active et inactive", "l’enzyme allostérique monomérique", "l’enzyme allostérique dimérique"],
  89: ["le site allostérique"],
  90: ["le site allostérique", "l’enzyme allostérique dimérique"],
  91: ["les conformations active et inactive", "la régulation de la PKA par l’AMPc"],
  92: ["l’enzyme allostérique monomérique", "la sous-unité régulatrice de la PKA"],
  93: ["l’enzyme allostérique dimérique", "la modification covalente comme stratégie de régulation"],
  94: ["la régulation de la PKA par l’AMPc", "la dégradation enzymatique comme régulation"],
  95: ["la sous-unité régulatrice de la PKA", "la protéolyse limitée"],
  96: ["la modification covalente comme stratégie de régulation", "la cascade d’activation des enzymes digestives"],
  97: ["la dégradation enzymatique comme régulation", "les stratégies de régulation enzymatique"],
  98: ["la protéolyse limitée", "la cascade d’activation des enzymes digestives", "les stratégies de régulation enzymatique"],
  99: ["la cascade d’activation des enzymes digestives", "les conformations active et inactive"],
  100: ["les stratégies de régulation enzymatique", "le site allostérique", "les conformations active et inactive", "l’enzyme allostérique monomérique", "l’enzyme allostérique dimérique"],
  101: ["la définition d’un catalyseur", "les coenzymes"],
  102: ["la spécificité enzymatique", "l’ALAT"],
  103: ["les interactions enzyme-substrat", "la distinction lyases-ligases selon la fiche"],
  104: ["les groupements prosthétiques et les cofacteurs labiles", "l’énergie d’activation sans enzyme"],
  105: ["les vitamines B2 et B3 comme précurseurs de coenzymes", "le site de fixation et le site catalytique"],
  106: ["les isoenzymes", "la régénération de la triade catalytique"],
  107: ["l’effet d’une enzyme sur l’énergie d’activation", "l’enzyme allostérique monomérique"],
  108: ["la spécificité de la chymotrypsine dans la fiche", "la modification covalente comme stratégie de régulation"],
  109: ["l’effet d’une enzyme sur l’énergie d’activation", "les complexes ES et EP", "les effets entropiques et interactions lors de la fixation"],
  110: ["le site de fixation et le site catalytique", "la spécificité de la chymotrypsine dans la fiche", "la triade catalytique de la chymotrypsine", "les intermédiaires de la chymotrypsine", "la régénération de la triade catalytique"],
  111: ["la catalyse hétérogène et homogène", "les exemples de cofacteurs métalliques et organiques", "l’énergie d’activation sans enzyme"],
  112: ["la trypsine", "les isoenzymes", "les conformations active et inactive"],
  113: ["les coenzymes", "le site de fixation et le site catalytique", "les enzymes protéiques et les ribozymes"],
  114: ["les vitamines B2 et B3 comme précurseurs de coenzymes", "les conformations active et inactive", "les exemples de cofacteurs métalliques et organiques"],
  115: ["le modèle clé-serrure de Fisher", "la protéolyse limitée", "l’effet d’une enzyme sur l’énergie d’activation"],
  116: ["les effets entropiques et interactions lors de la fixation", "la subtilisine", "l’enzyme allostérique monomérique"],
  117: ["l’apoenzyme, le cofacteur et l’holoenzyme"],
  118: ["l’enzyme allostérique dimérique", "la distinction lyases-ligases selon la fiche", "le PLP et la vitamine B6"],
  119: ["la protéolyse limitée", "les effets entropiques et interactions lors de la fixation", "les complexes ES et EP"],
  120: ["le pouvoir catalytique des enzymes", "le site allostérique", "l’enzyme allostérique dimérique"],
  121: ["la thrombine", "les interactions enzyme-substrat", "la forte affinité enzyme-substrat"],
  122: ["les groupements prosthétiques et les cofacteurs labiles", "les exemples de cofacteurs métalliques et organiques", "le PLP et la vitamine B6", "l’ALAT", "les vitamines B2 et B3 comme précurseurs de coenzymes"],
};
