/**
 * UE14 – Biologie cellulaire – Chapitre 8
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’hétérochromatine :`,
    choices: [
      `Est condensée.`,
      `Est peu accessible aux polymérases.`,
      `Est globalement inactive dans le cadre présenté.`,
      `Correspond à la forme la plus décondensée de la chromatine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle est organisée en mottes denses.`,
      `Exact. La condensation limite l’accès.`,
      `Exact. Transcription et duplication y sont limitées.`,
      `Faux. Cette description correspond à l’euchromatine.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’euchromatine :`,
    choices: [
      `Est décondensée.`,
      `Est accessible aux ARN et ADN polymérases.`,
      `Peut contenir des ARN en cours de synthèse.`,
      `Est inaccessible par définition.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle apparaît plus claire.`,
      `Exact. Elle peut être active en transcription ou duplication.`,
      `Exact. La transcription y est observable.`,
      `Faux. L’accessibilité est sa caractéristique fonctionnelle.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La relation compaction–activité implique que :`,
    choices: [
      `Une chromatine condensée est moins active.`,
      `Une chromatine décondensée peut être active.`,
      `La transcription exige un chromosome mitotique.`,
      `La cellule module localement le degré de condensation.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les polymérases y accèdent difficilement.`,
      `Exact. Elle permet transcription et duplication.`,
      `Faux. Le chromosome mitotique est extrêmement condensé.`,
      `Exact. Cela permet une régulation régionale.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le nucléole :`,
    choices: [
      `Est le site de synthèse et de maturation des ARNr.`,
      `Produit les sous-unités ribosomales.`,
      `Est limité par une double membrane.`,
      `Se construit autour de gènes d’ADNr.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il participe à la biogenèse ribosomale.`,
      `Exact. Elles seront exportées vers le cytoplasme.`,
      `Faux. Le nucléole n’est pas un organite membranaire.`,
      `Exact. Ces gènes sont présents en nombreux exemplaires.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La fiche attribue aux nucléoles environ :`,
    choices: [
      `60 % de la synthèse totale des ARN.`,
      `0,6 % de la synthèse totale des ARN.`,
      `Une activité majeure de synthèse d’ARNr.`,
      `La totalité de la synthèse d’ARNm.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cette proportion souligne l’importance de la production d’ARNr.`,
      `Faux. La valeur indiquée est bien plus élevée.`,
      `Exact. La majorité de l’activité nucléolaire concerne ces ARN.`,
      `Faux. Le nucléole est spécialisé dans les ARNr.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les nucléoles se construisent autour d’environ :`,
    choices: [
      `200 exemplaires d’un gène d’ADNr amplifié.`,
      `Deux exemplaires seulement.`,
      `Des gènes localisés sur plusieurs chromosomes.`,
      `Un unique pore nucléaire.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cette valeur est donnée dans la fiche.`,
      `Faux. Le nombre est beaucoup plus élevé.`,
      `Exact. Les foyers d’ADNr proviennent de chromosomes différents.`,
      `Faux. Les pores ne constituent pas le centre de construction du nucléole.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans le nucléole :`,
    choices: [
      `Des zones claires contiennent les gènes d’ADNr.`,
      `D’autres zones participent à la maturation des sous-unités ribosomales.`,
      `Les sous-unités matures sont exportées par les pores nucléaires.`,
      `Les ribosomes cytoplasmiques restent définitivement dans le nucléole.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La transcription de ces gènes s’y déroule.`,
      `Exact. La fiche décrit une zone foncée et une zone plus claire.`,
      `Exact. Elles rejoignent le cytoplasme.`,
      `Faux. Les sous-unités quittent le noyau après maturation.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les sous-unités ribosomales produites dans le nucléole :`,
    choices: [
      `S’associent ultérieurement dans le cytoplasme.`,
      `Sortent par les pores nucléaires.`,
      `Sont des chromosomes.`,
      `Participent à la traduction protéique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elles forment les ribosomes responsables de la traduction.`,
      `Exact. Leur export est contrôlé.`,
      `Faux. Elles sont constituées d’ARNr et de protéines.`,
      `Exact. Les ribosomes cytoplasmiques assurent cette fonction.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des territoires chromosomiques :`,
    choices: [
      `Ils concernent les chromosomes interphasiques.`,
      `Ils limitent le mélange aléatoire des molécules d’ADN.`,
      `Ils correspondent aux nucléoles.`,
      `Ils traduisent une organisation nucléaire non aléatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La FISH multicouleur les révèle dans un noyau interphasique.`,
      `Exact. Chaque chromosome occupe un volume restreint.`,
      `Faux. Les nucléoles sont des compartiments distincts.`,
      `Exact. Le génome possède une topologie spatiale.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une zone nucléaire claire en MET peut correspondre :`,
    choices: [
      `À de l’euchromatine.`,
      `À une région potentiellement active.`,
      `À de l’hétérochromatine fortement condensée.`,
      `À une région où l’on peut observer des ARN en synthèse.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La chromatine décondensée est plus claire.`,
      `Exact. Elle est accessible aux polymérases.`,
      `Faux. Cette dernière apparaît foncée.`,
      `Exact. La transcription se déroule dans l’euchromatine.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En observant la figure :

![Territoires et nucléole](/images/training/ue14/biologie-cellulaire/noyau/territoires-nucleole.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les chromosomes occupent des territoires distincts.`,
      `Le nucléole s’organise autour de foyers d’ADNr.`,
      `Les sous-unités ribosomales sont exportées.`,
      `Le nucléole est représenté comme un organite à double membrane.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La partie gauche représente des volumes séparés.`,
      `Exact. Les points rouges symbolisent les copies de gènes ribosomaux.`,
      `Exact. La flèche les conduit vers l’extérieur du noyau.`,
      `Faux. Il n’est pas limité par une enveloppe.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une région de chromatine accessible aux ARN polymérases est :`,
    choices: [
      `De l’euchromatine.`,
      `De l’hétérochromatine compacte.`,
      `Potentiellement transcriptionnellement active.`,
      `Nécessairement un nucléole.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La décondensation permet la transcription.`,
      `Faux. Elle est inaccessible et inactive.`,
      `Exact. L’accessibilité autorise l’initiation et l’élongation.`,
      `Faux. Toute euchromatine n’appartient pas au nucléole.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une région sombre et compacte à la périphérie d’un noyau peut correspondre :`,
    choices: [
      `À de l’hétérochromatine.`,
      `À une région peu accessible aux polymérases.`,
      `À une fibre nucléosomique totalement décondensée.`,
      `À une région potentiellement associée à la lamina.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La chromatine condensée apparaît foncée.`,
      `Exact. La compaction limite l’activité.`,
      `Faux. Elle serait plus claire.`,
      `Exact. Certaines LAD sont périphériques.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans une boucle chromatinienne, plusieurs gènes peuvent être :`,
    choices: [
      `Actifs ou inactifs.`,
      `Régulés localement par le degré de condensation.`,
      `Tous obligatoirement transcrits simultanément.`,
      `Organisés autour d’une origine de réplication unique dans le modèle présenté.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La fiche prévoit plusieurs origines de transcription.`,
      `Exact. La compaction peut varier selon les régions.`,
      `Faux. Les gènes peuvent être actifs ou non.`,
      `Exact. Chaque boucle n’en contient qu’une selon la fiche.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un nucléole volumineux et irrégulier dans une cellule tumorale :`,
    choices: [
      `Peut constituer un critère morphologique.`,
      `Prouve à lui seul et sans contexte la nature tumorale.`,
      `Peut refléter une activité ribosomale importante.`,
      `Doit être interprété avec les autres caractéristiques nucléaires.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Taille, forme et nombre des nucléoles sont examinés.`,
      `Faux. Le diagnostic repose sur une comparaison et un ensemble de critères.`,
      `Exact. Le nucléole est le siège de la synthèse d’ARNr.`,
      `Exact. Rapport nucléocytoplasmique et chromatine sont également évalués.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La disparition du nucléole en mitose est cohérente avec :`,
    choices: [
      `La réorganisation générale du noyau.`,
      `La condensation du matériel génétique.`,
      `La destruction définitive des gènes d’ADNr.`,
      `La reformation ultérieure du nucléole en fin de division.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. L’enveloppe et la chromatine changent profondément.`,
      `Exact. Les chromosomes mitotiques se forment.`,
      `Faux. Les gènes sont conservés et réutilisés après mitose.`,
      `Exact. Le noyau se reconstitue après la mitose.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une forte activité de synthèse d’ARNr se localise :`,
    choices: [
      `Dans le nucléole.`,
      `Autour des copies d’ADNr.`,
      `Dans l’espace périnucléaire.`,
      `Dans un compartiment nucléaire sans membrane propre.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est son rôle principal.`,
      `Exact. Le nucléole se construit autour de ces gènes.`,
      `Faux. Cet espace se trouve entre les deux membranes.`,
      `Exact. Le nucléole n’est pas limité par une membrane.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La chromatine condensée en mottes :`,
    choices: [
      `Correspond à l’hétérochromatine.`,
      `Est inaccessible aux ARN et ADN polymérases.`,
      `Permet une transcription maximale.`,
      `Peut apparaître foncée en microscopie électronique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le cours emploie ce terme.`,
      `Exact. Elle est inactive dans le cadre présenté.`,
      `Faux. La compaction inhibe l’accès.`,
      `Exact. La densité est plus élevée.`,
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La chromatine décondensée :`,
    choices: [
      `Correspond à l’euchromatine.`,
      `Peut contenir des ARN en cours de synthèse.`,
      `Est accessible aux polymérases.`,
      `Est toujours silencieuse.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle est diffuse et accessible.`,
      `Exact. La transcription y est active.`,
      `Exact. La décondensation autorise leur action.`,
      `Faux. Elle peut être active en transcription ou duplication.`,
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des sous-unités ribosomales :`,
    choices: [
      `Leur maturation se déroule dans le nucléole.`,
      `Elles sont exportées vers le cytoplasme.`,
      `Elles participent à la formation des ribosomes.`,
      `Elles sont constituées uniquement d’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Plusieurs zones nucléolaires participent au processus.`,
      `Exact. Les pores nucléaires assurent cette sortie.`,
      `Exact. Les ribosomes cytoplasmiques assurent la traduction.`,
      `Faux. Elles reposent notamment sur les ARNr et des protéines.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule possède beaucoup d’euchromatine et un nucléole développé. On peut raisonnablement envisager :`,
    choices: [
      `Une activité transcriptionnelle élevée.`,
      `Une importante production d’ARNr.`,
      `Une condensation mitotique maximale de tout le génome.`,
      `Une forte demande de synthèse protéique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. L’euchromatine est accessible.`,
      `Exact. Le nucléole développé est cohérent avec cette activité.`,
      `Faux. La présence d’euchromatine indique un état interphasique actif.`,
      `Exact. La production de ribosomes accompagne souvent une activité cellulaire soutenue.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule présente essentiellement de l’hétérochromatine compacte :`,
    choices: [
      `Son activité transcriptionnelle globale peut être réduite.`,
      `Les polymérases accèdent difficilement à l’ADN.`,
      `La synthèse d’ARN est nécessairement maximale.`,
      `Cette situation peut être associée à une forte différenciation.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. L’ADN est moins accessible.`,
      `Exact. La condensation constitue une barrière.`,
      `Faux. L’hétérochromatine est inactive.`,
      `Exact. La spermatide tardive montre une chromatine très condensée.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La FISH multicouleur montre des zones chromosomiques distinctes. Cette observation :`,
    choices: [
      `Appuie la notion de territoires chromosomiques.`,
      `Montre une organisation spatiale du génome.`,
      `Prouve que tous les chromosomes sont fusionnés.`,
      `Concerne un noyau interphasique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Chaque chromosome occupe un volume restreint.`,
      `Exact. Le noyau n’est pas un mélange aléatoire.`,
      `Faux. Les signaux distincts montrent l’inverse.`,
      `Exact. La fiche montre cette organisation en interphase.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut d’export des sous-unités ribosomales par les pores nucléaires pourrait :`,
    choices: [
      `Réduire la formation de ribosomes cytoplasmiques.`,
      `Perturber la traduction protéique.`,
      `Augmenter directement la sortie de l’ADN.`,
      `Provoquer une accumulation de sous-unités dans le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les sous-unités doivent rejoindre le cytoplasme.`,
      `Exact. Les ribosomes sont nécessaires à la traduction.`,
      `Faux. L’ADN ne sort pas du noyau.`,
      `Exact. L’export étant bloqué, elles peuvent s’y accumuler.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une région contenant une seule origine de réplication mais plusieurs gènes correspond :`,
    choices: [
      `À une boucle nucléosomique dans le modèle du cours.`,
      `À une structure ancrée par des MAR.`,
      `À un pore nucléaire.`,
      `À une organisation pouvant contenir plusieurs origines de transcription.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est l’unité structurale décrite.`,
      `Exact. Les extrémités sont fixées à la matrice.`,
      `Faux. Le pore est un complexe protéique de transport.`,
      `Exact. Plusieurs gènes peuvent y être actifs ou inactifs.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une région chromatinienne passe d’un état foncé à un état plus clair. On peut envisager :`,
    choices: [
      `Une décondensation locale.`,
      `Une augmentation possible de l’accessibilité aux polymérases.`,
      `Une transformation en pore nucléaire.`,
      `Une activation transcriptionnelle potentielle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La diminution de densité traduit une ouverture de la chromatine.`,
      `Exact. L’euchromatine est plus accessible.`,
      `Faux. La chromatine ne devient pas un pore.`,
      `Exact. La décondensation autorise la transcription.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une altération des copies d’ADNr pourrait affecter directement :`,
    choices: [
      `La synthèse des ARNr.`,
      `La biogenèse des sous-unités ribosomales.`,
      `La structure de la membrane plasmique.`,
      `L’activité du nucléole.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ces gènes codent les ARN ribosomaux.`,
      `Exact. Le nucléole se construit autour de ces gènes.`,
      `Faux. Ce lien n’est pas direct.`,
      `Exact. Il dépend des gènes d’ADNr.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le nucléole est un exemple de compartimentation nucléaire car :`,
    choices: [
      `Il constitue une zone fonctionnelle distincte du nucléoplasme.`,
      `Il est entouré d’une double membrane.`,
      `Il regroupe des gènes d’ADNr de chromosomes différents.`,
      `Il organise plusieurs étapes de la biogenèse ribosomale.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il concentre la synthèse et la maturation des ARNr.`,
      `Faux. Il n’est pas un organite membranaire.`,
      `Exact. Ces foyers participent à sa construction.`,
      `Exact. Transcription et maturation y sont spatialement coordonnées.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une analyse anatomopathologique met en évidence de gros nucléoles nombreux et irréguliers. Cette donnée :`,
    choices: [
      `Fait partie des critères nucléaires évalués.`,
      `Doit être interprétée avec le rapport nucléocytoplasmique.`,
      `Doit être comparée aux cellules normales environnantes.`,
      `Suffit toujours à elle seule pour poser un diagnostic définitif.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Taille, forme et nombre sont observés.`,
      `Exact. L’analyse repose sur plusieurs critères.`,
      `Exact. La comparaison au tissu de référence est essentielle.`,
      `Faux. Le cours décrit une analyse morphologique globale.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `L’état de compaction détermine l’accessibilité de l’ADN.`,
      `Les chromosomes occupent des territoires dans le noyau.`,
      `Le nucléole coordonne la biogenèse ribosomale.`,
      `Le nucléole assure l’export de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Euchromatine et hétérochromatine ont des activités différentes.`,
      `Exact. L’organisation spatiale est non aléatoire.`,
      `Exact. Il synthétise les ARNr et mature les sous-unités.`,
      `Faux. L’ADN reste protégé dans le noyau.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `euchromatine-heterochromatine`,
    title: `Euchromatine et hétérochromatine`,
    description: `Compaction, accessibilité et activité des polymérases.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `nucleole-et-ribosomes`,
    title: `Nucléole et biogenèse ribosomale`,
    description: `ADNr, synthèse des ARNr, maturation et export des sous-unités.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `activite-nucleaire-et-applications`,
    title: `Activité nucléaire et applications`,
    description: `Raisonnement intégré sur chromatine, nucléole et pathologie.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
