import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_ORDER = 2;

export const SECTION_B_POLARITY_DISCOVERY_QUIZ_SLUG =
  `section-b-discovery-polarite-carbonyle`;
export const SECTION_B_HYDRIDE_PRACTICE_QUIZ_SLUG =
  `section-b-practice-reduction-hydrures`;
export const SECTION_B_GRIGNARD_MASTER_QUIZ_SLUG =
  `section-b-master-addition-organomagnesiens`;

export const SECTION_B_POLARITY_DISCOVERY_QUESTION_ORDERS: number[] = [31, 32, 33, 34, 35, 36, 37, 38, 39, 40];
export const SECTION_B_HYDRIDE_PRACTICE_QUESTION_ORDERS: number[] = [41, 42, 43, 44, 45, 46, 47, 48, 49, 50];
export const SECTION_B_GRIGNARD_MASTER_QUESTION_ORDERS: number[] = [51, 52, 53, 54, 55, 56, 57, 58, 59, 60];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: SECTION_B_POLARITY_DISCOVERY_QUIZ_SLUG,
    title: `Polarité du carbonyle et carbones voisins`,
    description: `Comprendre le caractère électrophile du carbone carbonylé et le caractère nucléophile potentiel des carbones voisins portant un hydrogène.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_B_ORDER,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: SECTION_B_HYDRIDE_PRACTICE_QUIZ_SLUG,
    title: `Réduction par les hydrures`,
    description: `Prévoir la classe d’alcool obtenue lors de la réduction d’un aldéhyde ou d’une cétone par un hydrure tel que le borohydrure de sodium.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 41 },
      { type: 'QUESTION', questionOrder: 42 },
      { type: 'QUESTION', questionOrder: 43 },
      { type: 'QUESTION', questionOrder: 44 },
      { type: 'QUESTION', questionOrder: 45 },
      { type: 'QUESTION', questionOrder: 46 },
      { type: 'QUESTION', questionOrder: 47 },
      {
        type: 'GROUP',
        title: `Réduction d’un intermédiaire pharmaceutique`,
        sharedStatement: `Un intermédiaire de synthèse contient une cétone de type $\\mathrm{Ar{-}CO{-}CH_3}$. Il est traité par $\\mathrm{NaBH_4}$, puis le milieu est hydrolysé.`,
        questionOrders: [48, 49, 50],
      },
    ],
  },
  {
    order: 6,
    slug: SECTION_B_GRIGNARD_MASTER_QUIZ_SLUG,
    title: `Addition des organomagnésiens`,
    description: `Construire une liaison carbone–carbone et déterminer la classe de l’alcool obtenu après addition d’un organomagnésien et hydrolyse.`,
    stage: 'MASTER',
    sectionOrder: SECTION_B_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 51 },
      { type: 'QUESTION', questionOrder: 52 },
      { type: 'QUESTION', questionOrder: 53 },
      { type: 'QUESTION', questionOrder: 54 },
      { type: 'QUESTION', questionOrder: 55 },
      { type: 'QUESTION', questionOrder: 56 },
      { type: 'QUESTION', questionOrder: 57 },
      {
        type: 'GROUP',
        title: `Un même organomagnésien, deux carbonyles`,
        sharedStatement: `Le bromure d’éthylmagnésium $\\mathrm{CH_3CH_2MgBr}$ réagit séparément avec **I**, le propanal, et **II**, la butan-2-one. Chaque milieu est ensuite hydrolysé.`,
        questionOrders: [58, 59, 60],
      },
    ],
  },
];

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans une liaison carbonyle $\\mathrm{C{=}O}$ :`,
    choices: [
      `L'oxygène exerce un effet électroattracteur.`,
      `Le carbone carbonylé présente un caractère électrophile.`,
      `L'oxygène rend le carbone carbonylé riche en électrons.`,
      `Un nucléophile peut attaquer le carbone carbonylé.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La polarisation de la liaison $\\mathrm{C{=}O}$ appauvrit le carbone en densité électronique et favorise l'attaque nucléophile.`,
    choiceExplanations: [
      `L'oxygène attire les électrons.`,
      `Le carbone devient déficitaire en électrons.`,
      `C'est l'inverse : il devient électrophile.`,
      `Il constitue le centre d'attaque.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un aldéhyde de type $\\mathrm{RCH_2CHO}$ :`,
    choices: [
      `Le carbone du carbonyle est électrophile.`,
      `Le carbone voisin peut présenter un caractère nucléophile.`,
      `Le carbone voisin doit porter au moins un hydrogène pour le comportement décrit.`,
      `Tous les carbones sont nécessairement électrophiles.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fonction carbonyle présente deux polarités utiles : un centre carbonylé électrophile et, sous conditions adaptées, un carbone voisin nucléophile.`,
    choiceExplanations: [
      `Il est appauvri en électrons.`,
      `Il peut être activé en position alpha.`,
      `Le cours conditionne ce caractère à la présence d'un hydrogène.`,
      `Les centres n'ont pas tous la même réactivité.`,
    ],
  },
  {
    order: 33,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans une cétone $\\mathrm{RCH_2COCH_2R'}$ :`,
    choices: [
      `Le carbone carbonylé est électrophile.`,
      `Les deux carbones voisins peuvent présenter un caractère nucléophile.`,
      `Les deux positions voisines sont appelées positions alpha du carbonyle.`,
      `L'oxygène du carbonyle est le centre électrophile principal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une cétone peut posséder deux côtés énolisables lorsque chacun des carbones alpha porte au moins un hydrogène.`,
    choiceExplanations: [
      `Le centre $\\mathrm{C{=}O}$ est attaqué par les nucléophiles.`,
      `Les deux côtés peuvent être activés.`,
      `Ils sont directement adjacents au carbonyle.`,
      `L'oxygène est plutôt riche en électrons.`,
    ],
  },
  {
    order: 34,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour qu'un carbone voisin d'un carbonyle acquière le caractère nucléophile décrit dans le cours :`,
    choices: [
      `Il doit porter au moins un hydrogène.`,
      `Une base forte peut être utilisée pour créer le centre nucléophile.`,
      `Il doit être le carbone de l'oxygène.`,
      `La présence du carbonyle contribue à stabiliser la réactivité voisine.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'arrachement d'un hydrogène en alpha par une base forte révèle un centre nucléophile adjacent au carbonyle.`,
    choiceExplanations: [
      `C'est la condition structurale indiquée.`,
      `La base génère l'espèce riche en électrons.`,
      `L'oxygène n'est pas un carbone.`,
      `La polarisation du carbonyle est essentielle.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le terme « électrophile » désigne ici un centre :`,
    choices: [
      `Pauvre en électrons.`,
      `Susceptible d'être attaqué par un nucléophile.`,
      `Nécessairement chargé négativement.`,
      `Comme le carbone du groupe carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le carbone carbonylé est un électrophile parce qu'il est déficitaire en électrons.`,
    choiceExplanations: [
      `Il recherche de la densité électronique.`,
      `Un nucléophile lui apporte un doublet.`,
      `Une charge négative caractérise plutôt un nucléophile.`,
      `C'est l'exemple central du chapitre.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le terme « nucléophile » désigne ici une espèce ou un centre :`,
    choices: [
      `Riche en électrons.`,
      `Capable d'apporter un doublet au carbone carbonylé.`,
      `Toujours dépourvu d'électrons.`,
      `Comme l'hydrure $\\mathrm{H^-}$ ou le fragment carboné d'un organomagnésien.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les nucléophiles réagissent avec le carbone électrophile du carbonyle en apportant de la densité électronique.`,
    choiceExplanations: [
      `C'est leur propriété essentielle.`,
      `Ils forment une nouvelle liaison.`,
      `Cette description correspond à un électrophile.`,
      `Ces deux exemples sont donnés dans le cours.`,
    ],
  },
  {
    order: 37,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On considère $\\mathrm{CH_3COC(CH_3)_3}$. À propos des carbones voisins du carbonyle :`,
    choices: [
      `Le groupe $\\mathrm{CH_3}$ possède des hydrogènes en alpha.`,
      `Le carbone du groupe $\\mathrm{C(CH_3)_3}$ directement voisin ne porte aucun hydrogène.`,
      `Les deux côtés ont nécessairement la même aptitude à devenir nucléophiles.`,
      `Le carbone carbonylé reste électrophile.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La présence ou non d'un hydrogène sur le carbone alpha distingue les deux côtés de cette cétone.`,
    choiceExplanations: [
      `Le méthyle peut être déprotoné.`,
      `Ce carbone quaternaire n'a aucun hydrogène.`,
      `Leur réactivité alpha diffère.`,
      `La polarisation du carbonyle demeure.`,
    ],
  },
  {
    order: 38,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'effet électroattracteur de l'oxygène :`,
    choices: [
      `Il polarise la liaison $\\mathrm{C{=}O}$.`,
      `Il explique le caractère électrophile du carbone carbonylé.`,
      `Il participe au caractère particulier des carbones voisins portant un hydrogène.`,
      `Il rend toute la molécule uniformément nucléophile.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'effet de l'oxygène crée des centres de réactivité différenciés au niveau du carbonyle et en position voisine.`,
    choiceExplanations: [
      `La densité électronique est déplacée vers l'oxygène.`,
      `Le carbone est appauvri.`,
      `La position alpha peut être activée.`,
      `La réactivité n'est pas uniforme.`,
    ],
  },
  {
    order: 39,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans une cétone possédant des hydrogènes des deux côtés du carbonyle :`,
    choices: [
      `Deux positions voisines peuvent être activées.`,
      `Une base forte peut former un centre nucléophile sur l'un des côtés.`,
      `Le carbone du carbonyle devient alors nécessairement nucléophile.`,
      `Le choix des conditions peut influencer le site réactif.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les deux carbones alpha peuvent potentiellement être déprotonés ; les conditions expérimentales peuvent orienter la réaction.`,
    choiceExplanations: [
      `Chaque côté possède des hydrogènes alpha.`,
      `La base arrache un proton.`,
      `Le carbonyle reste le centre électrophile vis-à-vis des nucléophiles.`,
      `La régiosélectivité dépend des conditions.`,
    ],
  },
  {
    order: 40,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une même molécule carbonylée peut présenter :`,
    choices: [
      `Un centre électrophile au niveau du carbone $\\mathrm{C{=}O}$.`,
      `Un centre nucléophile en position alpha après action d'une base forte.`,
      `Des réactivités différentes selon le réactif utilisé.`,
      `Uniquement un comportement acido-basique sans formation de liaison.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chapitre insiste sur la dualité de réactivité : attaque du carbonyle par un nucléophile ou réaction du carbone alpha avec un électrophile.`,
    choiceExplanations: [
      `Le carbonyle reçoit les nucléophiles.`,
      `La position alpha peut attaquer un électrophile.`,
      `Le partenaire réactionnel détermine le site mobilisé.`,
      `De nouvelles liaisons peuvent bien être formées.`,
    ],
  },
  {
    order: 41,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un hydrure utilisé pour réduire un composé carbonylé :`,
    choices: [
      `Peut être représenté par $\\mathrm{H^-}$.`,
      `Est riche en électrons.`,
      `Se comporte comme un nucléophile.`,
      `Est un électrophile pauvre en électrons.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'hydrure apporte une densité électronique au carbone carbonylé et réduit la fonction.`,
    choiceExplanations: [
      `C'est sa représentation formelle.`,
      `La charge négative traduit sa richesse électronique.`,
      `Il attaque le carbonyle.`,
      `Cette description est opposée.`,
    ],
  },
  {
    order: 42,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le borohydrure de sodium $\\mathrm{NaBH_4}$ :`,
    choices: [
      `Est un réducteur doux cité dans le cours.`,
      `Peut réduire un aldéhyde.`,
      `Peut réduire une cétone.`,
      `Oxyde systématiquement un alcool en acide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le $\\mathrm{NaBH_4}$ fournit un hydrure capable de réduire les aldéhydes et les cétones.`,
    choiceExplanations: [
      `Il est présenté comme doux.`,
      `Le produit est un alcool primaire.`,
      `Le produit est un alcool secondaire.`,
      `Il réalise une réduction, pas cette oxydation.`,
    ],
  },
  {
    order: 43,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La réduction d'un aldéhyde par $\\mathrm{NaBH_4}$ conduit :`,
    choices: [
      `À un alcool primaire.`,
      `À la transformation $\\mathrm{RCHO ightarrow RCH_2OH}$.`,
      `À un alcool secondaire.`,
      `À un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le carbone terminal de l'aldéhyde devient le carbone d'un groupe $\\mathrm{CH_2OH}$.`,
    choiceExplanations: [
      `Le produit porte un alcool primaire.`,
      `C'est le bilan de réduction.`,
      `Une cétone donnerait un alcool secondaire.`,
      `Un acide résulterait d'une oxydation.`,
    ],
  },
  {
    order: 44,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La réduction d'une cétone par $\\mathrm{NaBH_4}$ conduit :`,
    choices: [
      `À un alcool secondaire.`,
      `À la transformation $\\mathrm{RCOR' ightarrow RCH(OH)R'}$.`,
      `À un alcool primaire.`,
      `À un aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le carbone carbonylé reste lié à deux groupes carbonés et devient porteur du groupe hydroxyle.`,
    choiceExplanations: [
      `Il est lié à deux carbones.`,
      `C'est le bilan attendu.`,
      `Un alcool primaire viendrait d'un aldéhyde.`,
      `La réduction ne s'arrête pas à un aldéhyde.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors de la réduction d'un carbonyle par un hydrure :`,
    choices: [
      `L'hydrure attaque le carbone électrophile.`,
      `La liaison $\\mathrm{C{=}O}$ est transformée au cours de la réaction.`,
      `Une liaison $\\mathrm{C{-}H}$ est formée au carbone carbonylé.`,
      `L'oxygène est éliminé de la molécule sous forme de dioxygène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'addition nucléophile d'un hydrure transforme le carbonyle en fonction alcool après protonation.`,
    choiceExplanations: [
      `Le carbone est le centre d'attaque.`,
      `La double liaison disparaît au profit d'un alcool.`,
      `L'hydrure devient lié au carbone.`,
      `L'oxygène est conservé dans le groupe $\\mathrm{OH}$.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On traite l'éthanal $\\mathrm{CH_3CHO}$ par $\\mathrm{NaBH_4}$. Le produit :`,
    choices: [
      `Est l'éthanol.`,
      `Est un alcool primaire.`,
      `Possède deux carbones.`,
      `Est l'acétone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réduction conserve le squelette carboné et transforme $\\mathrm{-CHO}$ en $\\mathrm{-CH_2OH}$.`,
    choiceExplanations: [
      `Le produit est $\\mathrm{CH_3CH_2OH}$.`,
      `Le groupe hydroxyle est terminal.`,
      `Aucun carbone n'est ajouté.`,
      `L'acétone est une cétone à trois carbones.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On traite la butan-2-one par $\\mathrm{NaBH_4}$. Le produit :`,
    choices: [
      `Est le butan-2-ol.`,
      `Est un alcool secondaire.`,
      `Résulte d'une réduction.`,
      `Est le butanal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cétone interne devient un alcool secondaire au même emplacement.`,
    choiceExplanations: [
      `Le carbonyle en C2 devient $\\mathrm{CHOH}$.`,
      `Le carbone alcoolique est lié à deux carbones.`,
      `Le nombre d'oxydation diminue.`,
      `Le butanal est un aldéhyde.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quelle fonction est réduite dans cette étape ?`,
    choices: [
      `Une cétone.`,
      `Un aldéhyde.`,
      `Un acide carboxylique.`,
      `Un alcène.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le substrat est explicitement une cétone aromatique.`,
    choiceExplanations: [
      `Le motif $\\mathrm{Ar{-}CO{-}CH_3}$ est une cétone.`,
      `Le carbonyle n'est pas terminal.`,
      `Aucun groupe $\\mathrm{COOH}$ n'est présent.`,
      `La fonction visée est $\\mathrm{C{=}O}$.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quelle classe d'alcool est attendue ?`,
    choices: [
      `Un alcool secondaire.`,
      `Un alcool primaire.`,
      `Un alcool tertiaire.`,
      `Aucun alcool ne peut être formé.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La réduction d'une cétone donne un alcool secondaire.`,
    choiceExplanations: [
      `Le carbone portant $\\mathrm{OH}$ reste lié à deux groupes carbonés.`,
      `Ce serait le produit d'un aldéhyde.`,
      `Un troisième groupe carboné n'est pas ajouté.`,
      `Le $\\mathrm{NaBH_4}$ réduit bien la cétone.`,
    ],
  },
  {
    order: 50,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos du rôle du $\\mathrm{NaBH_4}$ :`,
    choices: [
      `Il fournit un hydrure nucléophile.`,
      `Il attaque le carbone carbonylé électrophile.`,
      `Il augmente le degré d'oxydation du substrat.`,
      `Il conserve l'atome d'oxygène dans la fonction alcool.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le réducteur apporte un hydrure ; le carbonyle est converti en alcool sans perte de l'oxygène.`,
    choiceExplanations: [
      `L'hydrure est riche en électrons.`,
      `Le carbone du carbonyle est la cible.`,
      `Une réduction diminue le degré d'oxydation.`,
      `L'oxygène devient celui du groupe $\\mathrm{OH}$.`,
    ],
  },
  {
    order: 51,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un organomagnésien $\\mathrm{R{-}MgX}$ :`,
    choices: [
      `Le fragment carboné $\\mathrm{R^-}$ présente un caractère nucléophile.`,
      `Le carbone est riche en électrons.`,
      `Le fragment carboné attaque le carbone carbonylé.`,
      `Le magnésium transforme toujours le carbonyle en acide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le caractère polarisé de la liaison carbone–magnésium rend le fragment carboné nucléophile.`,
    choiceExplanations: [
      `C'est l'équivalent réactif utile.`,
      `Il peut former une nouvelle liaison $\\mathrm{C{-}C}$.`,
      `Le carbonyle est électrophile.`,
      `Le produit final est un alcool après hydrolyse.`,
    ],
  },
  {
    order: 52,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après réaction d'un organomagnésien avec un aldéhyde ou une cétone :`,
    choices: [
      `Une hydrolyse est nécessaire.`,
      `L'hydrolyse permet d'obtenir la fonction alcool.`,
      `Aucune nouvelle liaison carbone–carbone n'est formée.`,
      `Le fragment $\\mathrm{R}$ de l'organomagnésien est incorporé au produit.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'addition du fragment carboné forme une liaison $\\mathrm{C{-}C}$ ; l'hydrolyse protonne ensuite l'alcoolate.`,
    choiceExplanations: [
      `Elle constitue l'étape finale.`,
      `Le groupe $\\mathrm{O^-}$ devient $\\mathrm{OH}$.`,
      `Une liaison carbone–carbone est précisément créée.`,
      `Le nucléophile carboné devient un substituant.`,
    ],
  },
  {
    order: 53,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un organomagnésien réagit avec un aldéhyde $\\mathrm{RCHO}$. Le produit final est généralement :`,
    choices: [
      `Un alcool secondaire.`,
      `Un alcool tertiaire.`,
      `Un alcool portant un nouveau substituant carboné.`,
      `Un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `L'aldéhyde possède un hydrogène et un groupe carboné ; l'ajout d'un second groupe carboné conduit à un alcool secondaire.`,
    choiceExplanations: [
      `Le carbone alcoolique est lié à deux carbones.`,
      `Une cétone donnerait l'alcool tertiaire.`,
      `Le groupe de l'organomagnésien est ajouté.`,
      `La transformation est une addition suivie d'hydrolyse.`,
    ],
  },
  {
    order: 54,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un organomagnésien réagit avec une cétone $\\mathrm{RCOR'}$. Le produit final est généralement :`,
    choices: [
      `Un alcool tertiaire.`,
      `Un alcool secondaire.`,
      `Un alcool dont le carbone fonctionnel porte trois groupes carbonés.`,
      `Un aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `La cétone possède déjà deux substituants carbonés ; l'organomagnésien en ajoute un troisième.`,
    choiceExplanations: [
      `C'est la classe obtenue.`,
      `Un aldéhyde donnerait plutôt un alcool secondaire.`,
      `Les trois groupes restent liés au carbone alcoolique.`,
      `Le carbonyle est consommé.`,
    ],
  },
  {
    order: 55,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La réaction d'un organomagnésien sur un composé carbonylé :`,
    choices: [
      `Permet d'allonger ou de ramifier le squelette carboné.`,
      `Crée une liaison carbone–carbone.`,
      `Est une réaction d'un nucléophile sur un électrophile.`,
      `Détruit obligatoirement tout le squelette carboné initial.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette réaction est une méthode de construction de squelette carboné grâce à l'addition nucléophile sur le carbonyle.`,
    choiceExplanations: [
      `Le groupe $\\mathrm{R}$ est ajouté.`,
      `La nouvelle liaison relie les deux partenaires.`,
      `Le fragment organomagnésien attaque le carbonyle.`,
      `Le squelette initial est conservé.`,
    ],
  },
  {
    order: 56,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le méthylmagnésium bromure $\\mathrm{CH_3MgBr}$ réagit avec l'éthanal, puis le milieu est hydrolysé. Le produit :`,
    choices: [
      `Possède trois carbones.`,
      `Est un alcool secondaire.`,
      `Peut correspondre au propan-2-ol.`,
      `Est nécessairement un alcool tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le groupe méthyle est ajouté au carbone de l'éthanal, donnant après hydrolyse le propan-2-ol.`,
    choiceExplanations: [
      `Deux carbones du substrat plus un carbone ajouté.`,
      `Le carbone alcoolique est lié à deux groupes méthyle.`,
      `C'est la structure obtenue.`,
      `L'aldéhyde ne conduit pas à un alcool tertiaire.`,
    ],
  },
  {
    order: 57,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le méthylmagnésium bromure réagit avec la propanone, puis le milieu est hydrolysé. Le produit :`,
    choices: [
      `Est un alcool tertiaire.`,
      `Possède quatre carbones.`,
      `Peut correspondre au 2-méthylpropan-2-ol.`,
      `Est un alcool primaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La propanone porte déjà deux méthyles ; l'ajout d'un troisième méthyle donne un alcool tertiaire à quatre carbones.`,
    choiceExplanations: [
      `Le carbone alcoolique porte trois groupes carbonés.`,
      `Un carbone est ajouté aux trois du substrat.`,
      `La structure est tert-butanol.`,
      `Le groupe hydroxyle n'est pas terminal.`,
    ],
  },
  {
    order: 58,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quel est le rôle du fragment éthyle de $\\mathrm{CH_3CH_2MgBr}$ ?`,
    choices: [
      `Il agit comme nucléophile carboné.`,
      `Il attaque le carbone du groupe $\\mathrm{C{=}O}$.`,
      `Il est éliminé avant la formation du produit.`,
      `Il forme une nouvelle liaison carbone–carbone.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le fragment éthyle est transféré sur le carbone carbonylé.`,
    choiceExplanations: [
      `La liaison carbone–magnésium est fortement polarisée.`,
      `Le carbonyle est électrophile.`,
      `Il est au contraire incorporé.`,
      `C'est l'intérêt synthétique.`,
    ],
  },
  {
    order: 59,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Après l'addition, pourquoi réalise-t-on une hydrolyse ?`,
    choices: [
      `Pour protoner l'oxygène et former l'alcool.`,
      `Pour achever la transformation de l'alcoolate intermédiaire.`,
      `Pour oxyder l'alcool en acide.`,
      `Pour retirer le groupe carboné nouvellement ajouté.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'intermédiaire magnésien porte un oxygène sous forme alcoolate ; l'eau fournit le proton du groupe $\\mathrm{OH}$.`,
    choiceExplanations: [
      `Le groupe hydroxyle apparaît alors.`,
      `C'est l'étape de traitement final.`,
      `Aucune oxydation n'est visée.`,
      `La nouvelle liaison $\\mathrm{C{-}C}$ est conservée.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle classe d'alcool obtient-on dans chaque expérience ?`,
    choices: [
      `Expérience I : alcool secondaire.`,
      `Expérience II : alcool tertiaire.`,
      `Expérience I : alcool primaire.`,
      `Dans les deux cas, le carbone alcoolique reçoit le groupe éthyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'aldéhyde conduit à un alcool secondaire, la cétone à un alcool tertiaire ; dans les deux cas, le groupe éthyle est incorporé.`,
    choiceExplanations: [
      `Le carbone alcoolique est lié à deux groupes carbonés.`,
      `Il est lié à trois groupes carbonés.`,
      `L'aldéhyde simple utilisé ici n'est pas le méthanal.`,
      `Le nucléophile est le même dans les deux expériences.`,
    ],
  },
];
