import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_ORDER = 3;

export const SECTION_C_DECARBOXYLATION_DISCOVERY_QUIZ_SLUG =
  `section-c-discovery-decarboxylation`;
export const SECTION_C_FAVORED_STRUCTURES_PRACTICE_QUIZ_SLUG =
  `section-c-practice-decarboxylation-carbonyles`;
export const SECTION_C_BIOCHEMISTRY_MASTER_QUIZ_SLUG =
  `section-c-master-decarboxylations-biochimiques`;

export const SECTION_C_DECARBOXYLATION_DISCOVERY_QUESTION_ORDERS: number[] = [61, 62, 63, 64, 65, 66, 67, 68, 69, 70];
export const SECTION_C_FAVORED_STRUCTURES_PRACTICE_QUESTION_ORDERS: number[] = [71, 72, 73, 74, 75, 76, 77, 78, 79, 80];
export const SECTION_C_BIOCHEMISTRY_MASTER_QUESTION_ORDERS: number[] = [81, 82, 83, 84, 85, 86, 87, 88, 89, 90];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: SECTION_C_DECARBOXYLATION_DISCOVERY_QUIZ_SLUG,
    title: `Décarboxylation : définition et bilan carbone`,
    description: `Reconnaître la perte de dioxyde de carbone et suivre la diminution d’un carbone du squelette organique.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_C_ORDER,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: SECTION_C_FAVORED_STRUCTURES_PRACTICE_QUIZ_SLUG,
    title: `Structures favorables à la décarboxylation`,
    description: `Comprendre pourquoi un carbonyle voisin facilite la réaction et prévoir les fonctions conservées.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_C_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 71 },
      { type: 'QUESTION', questionOrder: 72 },
      { type: 'QUESTION', questionOrder: 73 },
      { type: 'QUESTION', questionOrder: 74 },
      { type: 'QUESTION', questionOrder: 75 },
      { type: 'QUESTION', questionOrder: 76 },
      { type: 'QUESTION', questionOrder: 77 },
      {
        type: 'GROUP',
        title: `Décarboxylation d’un composé carbonylé`,
        sharedStatement: `Un composé comporte une fonction acide carboxylique et une fonction cétone favorablement disposée. Il est chauffé dans des conditions permettant la perte de $\\mathrm{CO_2}$.`,
        questionOrders: [78, 79, 80],
      },
    ],
  },
  {
    order: 9,
    slug: SECTION_C_BIOCHEMISTRY_MASTER_QUIZ_SLUG,
    title: `Décarboxylations chimiques et enzymatiques`,
    description: `Réinvestir la réaction dans des contextes métaboliques et dans des enchaînements de synthèse.`,
    stage: 'MASTER',
    sectionOrder: SECTION_C_ORDER,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Une décarboxylation correspond :`,
    choices: [
      `À la perte de $\\mathrm{CO_2}$.`,
      `À une diminution d'un carbone de la molécule organique.`,
      `À l'addition de $\\mathrm{CO_2}$ sur un organomagnésien.`,
      `À une hydrolyse d'ester.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La décarboxylation est l'opération inverse d'une carboxylation sur le plan du bilan carbone.`,
    choiceExplanations: [
      `C'est sa définition.`,
      `Le carbone du carboxyle part avec le dioxyde de carbone.`,
      `Cette réaction est une carboxylation.`,
      `L'hydrolyse ne libère pas nécessairement de $\\mathrm{CO_2}$.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La décarboxylation peut être réalisée :`,
    choices: [
      `Par voie chimique.`,
      `Par voie enzymatique.`,
      `Uniquement dans le vide spatial.`,
      `Seulement sur les alcools.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le cours insiste sur la possibilité de mécanismes chimiques ou enzymatiques.`,
    choiceExplanations: [
      `Des conditions de chauffage ou des réactifs peuvent la provoquer.`,
      `De nombreuses décarboxylases existent en biochimie.`,
      `Aucune condition de ce type n'est requise.`,
      `Elle concerne des composés carboxyliques.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans le schéma $\\mathrm{RCH_2COOH \\rightarrow RCH_3 + CO_2}$ :`,
    choices: [
      `Le groupe carboxyle est perdu.`,
      `La chaîne organique résiduelle possède un carbone de moins.`,
      `Un carbone est ajouté à $\\mathrm{R}$.`,
      `La réaction est une estérification.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le produit organique est obtenu après remplacement fonctionnel du groupe carboxyle par un hydrogène dans ce bilan simplifié.`,
    choiceExplanations: [
      `Son carbone forme le $\\mathrm{CO_2}$.`,
      `Le carbone carboxylique n'est plus dans le produit organique.`,
      `Il est retiré.`,
      `Aucun ester n'est formé.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le gaz libéré lors d'une décarboxylation est :`,
    choices: [
      `Le dioxyde de carbone.`,
      `Le monoxyde de carbone uniquement.`,
      `Le diazote.`,
      `Le dichlore.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L'identification du $\\mathrm{CO_2}$ est centrale dans le bilan et dans les applications biochimiques.`,
    choiceExplanations: [
      `Sa formule est $\\mathrm{CO_2}$.`,
      `Le cours indique $\\mathrm{CO_2}$.`,
      `Aucun azote n'est nécessaire.`,
      `Aucun chlore n'est impliqué.`,
    ],
  },
  {
    order: 65,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une molécule à six carbones subit une seule décarboxylation sans autre rupture. Le produit organique principal :`,
    choices: [
      `Possède généralement cinq carbones.`,
      `Possède nécessairement sept carbones.`,
      `A perdu le carbone du groupe carboxyle.`,
      `Est obligatoirement un ester.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Le comptage du carbone permet de reconnaître immédiatement une décarboxylation.`,
    choiceExplanations: [
      `Un carbone est libéré dans $\\mathrm{CO_2}$.`,
      `Aucun carbone n'est ajouté.`,
      `C'est l'origine du gaz.`,
      `La fonction finale dépend du substrat.`,
    ],
  },
  {
    order: 66,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour qu'une décarboxylation soit particulièrement facile selon la fiche, il est favorable que :`,
    choices: [
      `La molécule possède une fonction acide carboxylique.`,
      `Un autre carbonyle soit situé de manière à stabiliser la transformation.`,
      `La molécule soit un alcane dépourvu d'oxygène.`,
      `Aucun groupe carbonylé ne soit présent.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les composés carboxyliques activés par un carbonyle voisin se décarboxylent plus aisément.`,
    choiceExplanations: [
      `Le groupe carboxyle est celui qui part.`,
      `Cétone, aldéhyde, autre acide ou ester sont cités.`,
      `Il n'y aurait pas de carboxyle à perdre.`,
      `La proximité d'un carbonyle est au contraire favorable dans les cas étudiés.`,
    ],
  },
  {
    order: 67,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les fonctions citées comme pouvant apporter le carbonyle facilitateur :`,
    choices: [
      `Une cétone.`,
      `Un aldéhyde.`,
      `Un ester.`,
      `Un alcane pur.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche énumère plusieurs fonctions carbonylées pouvant stabiliser la décarboxylation.`,
    choiceExplanations: [
      `Elle possède un carbonyle.`,
      `Il possède aussi un carbonyle.`,
      `Son groupe acyle contient $\\mathrm{C{=}O}$.`,
      `Il ne possède pas de carbonyle.`,
    ],
  },
  {
    order: 68,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos du chauffage lors d'une décarboxylation :`,
    choices: [
      `Il peut fournir l'énergie nécessaire à la réaction.`,
      `Il ne change pas le bilan de perte de $\\mathrm{CO_2}$.`,
      `Il ajoute toujours un carbone au substrat.`,
      `Il transforme nécessairement l'acide en amide.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les conditions exactes dépendent de la structure, mais le bilan reste la perte du groupe carboxyle.`,
    choiceExplanations: [
      `Le schéma du cours mentionne une température modérée pour un cas favorable.`,
      `Il agit sur la cinétique, pas sur l'identité du gaz.`,
      `La réaction en retire un.`,
      `Aucune amine n'est ajoutée.`,
    ],
  },
  {
    order: 69,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparer carboxylation et décarboxylation :`,
    choices: [
      `La carboxylation par $\\mathrm{CO_2}$ augmente le nombre de carbones d'une unité.`,
      `La décarboxylation diminue le nombre de carbones d'une unité.`,
      `Les deux réactions libèrent obligatoirement $\\mathrm{CO_2}$.`,
      `Elles ont le même bilan carbone.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Ces transformations doivent être distinguées malgré leurs noms proches.`,
    choiceExplanations: [
      `Le carbone du gaz est incorporé.`,
      `Le carbone carboxylique est libéré.`,
      `La carboxylation le consomme.`,
      `Leurs bilans sont opposés.`,
    ],
  },
  {
    order: 70,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une voie de synthèse comporte d'abord $\\mathrm{RMgX + CO_2 \\rightarrow RCOOH}$, puis une décarboxylation. Au total :`,
    choices: [
      `Le carbone ajouté par le $\\mathrm{CO_2}$ peut être ensuite reperdu.`,
      `Le squelette final peut retrouver le nombre de carbones initial de $\\mathrm{R}$.`,
      `Deux carbones sont nécessairement ajoutés.`,
      `Aucun $\\mathrm{CO_2}$ n'intervient.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le suivi atomique du carbone permet de comprendre l'enchaînement sans mémoriser mécaniquement les produits.`,
    choiceExplanations: [
      `Il devient le carbone carboxylique éliminé.`,
      `Une addition puis une perte d'un carbone s'annulent dans le bilan global.`,
      `Un seul est ajouté puis potentiellement retiré.`,
      `Il est consommé puis libéré.`,
    ],
  },
  {
    order: 71,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un acide portant un carbonyle voisin est souvent :`,
    choices: [
      `Plus apte à se décarboxyler qu'un acide simple.`,
      `Totalement dépourvu de carbone.`,
      `Un dérivé halogéné par définition.`,
      `Incapable de perdre $\\mathrm{CO_2}$.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La proximité d'une seconde fonction carbonylée rend la perte de $\\mathrm{CO_2}$ plus accessible.`,
    choiceExplanations: [
      `Le carbonyle favorise la stabilisation de l'intermédiaire ou de l'état de transition.`,
      `Il possède au moins les carbones des deux fonctions.`,
      `Aucun halogène n'est requis.`,
      `C'est précisément le cas favorable décrit.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans un motif comportant une fonction acide et une fonction cétone :`,
    choices: [
      `La cétone peut contribuer à stabiliser les électrons lors de la décarboxylation.`,
      `La perte de $\\mathrm{CO_2}$ laisse un produit carbonylé.`,
      `Le carbonyle de la cétone est obligatoirement éliminé avec le gaz.`,
      `La réaction ajoute une fonction amine.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le second carbonyle demeure dans le produit tout en facilitant la transformation.`,
    choiceExplanations: [
      `Son carbonyle permet une délocalisation.`,
      `Le schéma du cours conserve le groupe cétone.`,
      `C'est le carboxyle qui fournit le $\\mathrm{CO_2}$.`,
      `Aucun azote n'est impliqué.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Après décarboxylation d'un composé à deux fonctions acides, il est possible :`,
    choices: [
      `De perdre une molécule de $\\mathrm{CO_2}$.`,
      `De conserver une fonction acide dans le produit.`,
      `De gagner un groupe nitrile.`,
      `De former obligatoirement un thioester.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La présence de plusieurs fonctions acides permet une décarboxylation sélective sans supprimer toute acidité.`,
    choiceExplanations: [
      `L'une des fonctions carboxyliques peut être éliminée.`,
      `L'autre carboxyle peut rester.`,
      `Aucun azote n'est introduit.`,
      `Aucun soufre n'est requis.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une fonction ester voisine d'un carboxyle :`,
    choices: [
      `Contient un groupe carbonyle.`,
      `Peut participer à la stabilisation favorisant une décarboxylation.`,
      `Est dépourvue d'oxygène.`,
      `Libère nécessairement du diazote.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La nature exacte du carbonyle voisin peut varier sans changer le principe général.`,
    choiceExplanations: [
      `Le motif ester est $\\mathrm{RCOOR'}$.`,
      `Les esters sont cités parmi les fonctions carbonylées favorables.`,
      `Elle en contient deux.`,
      `Aucun azote n'est présent.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le produit organique d'une décarboxylation favorable :`,
    choices: [
      `Peut conserver une fonction cétone.`,
      `Possède un carbone de moins que le substrat.`,
      `Contient nécessairement le même groupe $\\mathrm{COOH}$ qui a réagi.`,
      `Est toujours un nucléotide.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Il faut identifier séparément la fonction éliminée et la fonction stabilisatrice conservée.`,
    choiceExplanations: [
      `Le carbonyle facilitateur reste souvent présent.`,
      `Le carbone du carboxyle a été éliminé.`,
      `Ce groupe est précisément perdu.`,
      `La réaction concerne de nombreuses molécules organiques.`,
    ],
  },
  {
    order: 76,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On chauffe un composé comportant cinq carbones, une fonction acide et une cétone favorablement disposée. Après une décarboxylation :`,
    choices: [
      `Le produit organique principal peut compter quatre carbones.`,
      `La cétone peut être conservée.`,
      `Le produit doit compter six carbones.`,
      `Le gaz formé est nécessairement $\\mathrm{H_2}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le comptage de carbones et le repérage des fonctions suffisent à prévoir le bilan qualitatif.`,
    choiceExplanations: [
      `Un carbone est parti sous forme de $\\mathrm{CO_2}$.`,
      `Le second carbonyle ne constitue pas le groupe partant.`,
      `Aucun carbone n'est ajouté.`,
      `Le gaz caractéristique est $\\mathrm{CO_2}$.`,
    ],
  },
  {
    order: 77,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pourquoi un carbonyle voisin facilite-t-il la décarboxylation ?`,
    choices: [
      `Il permet une délocalisation de la charge ou des électrons dans l'intermédiaire.`,
      `Il augmente la stabilité du produit ou de l'intermédiaire réactionnel.`,
      `Il supprime toute possibilité de mésomérie.`,
      `Il transforme le $\\mathrm{CO_2}$ en chlore.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La décarboxylation favorable est un nouvel exemple du rôle de la délocalisation électronique en chimie organique.`,
    choiceExplanations: [
      `La stabilisation rend la réaction moins coûteuse en énergie.`,
      `C'est l'origine de la facilité observée.`,
      `Il en crée au contraire.`,
      `Aucun chlore n'intervient.`,
    ],
  },
  {
    order: 78,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les substrats suivants, lequel est a priori le plus favorable à une décarboxylation selon le cours ?`,
    choices: [
      `Un acide carboxylique portant un autre carbonyle à proximité.`,
      `Un alcane sans groupe fonctionnel.`,
      `Un alcool simple sans fonction acide.`,
      `Un éther dépourvu de carbonyle et de carboxyle.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le critère structural essentiel est la coexistence du carboxyle partant et d'un carbonyle stabilisateur.`,
    choiceExplanations: [
      `C'est le motif mis en avant.`,
      `Il ne possède pas de carboxyle.`,
      `Il ne peut pas perdre un carboxyle absent.`,
      `Aucun groupe $\\mathrm{COOH}$ n'est présent.`,
    ],
  },
  {
    order: 79,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une décarboxylation enzymatique :`,
    choices: [
      `Respecte le même bilan de perte de $\\mathrm{CO_2}$ qu'une voie chimique.`,
      `Peut se produire dans un contexte biologique.`,
      `Ajoute nécessairement un phosphate au substrat.`,
      `Ne peut concerner aucune molécule carbonée.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La catalyse enzymatique permet des transformations sélectives dans des conditions physiologiques.`,
    choiceExplanations: [
      `L'enzyme change la cinétique et la sélectivité, pas la conservation des atomes.`,
      `Le cours mentionne explicitement la voie enzymatique.`,
      `Ce n'est pas la définition de la réaction.`,
      `Elle concerne précisément des molécules organiques.`,
    ],
  },
  {
    order: 80,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une expérience, l'apparition de bulles n'établit pas à elle seule une décarboxylation. Pour la confirmer, il faut notamment :`,
    choices: [
      `Identifier le gaz comme $\\mathrm{CO_2}$.`,
      `Vérifier que le produit organique a perdu un carbone.`,
      `Montrer qu'un groupe carboxyle a été consommé.`,
      `Observer obligatoirement la formation d'un alcool tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une conclusion fiable associe observation du gaz, analyse structurale du substrat et comptage des carbones.`,
    choiceExplanations: [
      `C'est le produit gazeux attendu.`,
      `Le bilan carbone doit être cohérent.`,
      `Il est la source du gaz.`,
      `Ce produit n'est pas caractéristique.`,
    ],
  },
  {
    order: 81,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En biochimie, une décarboxylase :`,
    choices: [
      `Catalyse la perte de $\\mathrm{CO_2}$ d'un substrat.`,
      `Peut accélérer une réaction thermodynamiquement possible.`,
      `Change le $\\mathrm{CO_2}$ en $\\mathrm{O_2}$.`,
      `Ajoute un carbone au substrat.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Il faut distinguer décarboxylase et carboxylase par le sens du transfert de $\\mathrm{CO_2}$.`,
    choiceExplanations: [
      `Le nom de l'enzyme reflète la réaction.`,
      `L'enzyme abaisse l'énergie d'activation.`,
      `Aucune telle conversion n'est décrite.`,
      `Ce serait une carboxylase.`,
    ],
  },
  {
    order: 82,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une réaction cellulaire libère une molécule de $\\mathrm{CO_2}$ à partir d'un acide organique. Il est plausible qu'il s'agisse :`,
    choices: [
      `D'une décarboxylation.`,
      `D'une réaction enzymatique.`,
      `D'une carboxylation.`,
      `D'une simple protonation sans changement de squelette.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le contexte biologique ne modifie pas le bilan chimique fondamental.`,
    choiceExplanations: [
      `La perte de dioxyde de carbone en est la signature.`,
      `De telles réactions sont fréquentes en métabolisme.`,
      `Une carboxylation consomme le $\\mathrm{CO_2}$.`,
      `Le nombre de carbones change.`,
    ],
  },
  {
    order: 83,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La perte de $\\mathrm{CO_2}$ lors d'une décarboxylation :`,
    choices: [
      `Peut contribuer à rendre la réaction favorable.`,
      `Est irréversible dans de nombreuses conditions pratiques.`,
      `Augmente le nombre de carbones du produit.`,
      `Transforme toujours une base en nucléotide.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La formation d'un produit gazeux est souvent un moteur pratique de la transformation.`,
    choiceExplanations: [
      `Le dégagement d'un gaz peut déplacer l'équilibre.`,
      `Le gaz s'échappe du milieu.`,
      `Elle le diminue.`,
      `Les notions sont indépendantes.`,
    ],
  },
  {
    order: 84,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une molécule médicale est métabolisée par décarboxylation. Le métabolite :`,
    choices: [
      `Possède un carbone de moins que la molécule initiale.`,
      `Peut avoir des propriétés différentes en raison de la disparition du groupe acide.`,
      `Contient obligatoirement davantage de groupes $\\mathrm{COOH}$.`,
      `Est nécessairement identique au précurseur.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La décarboxylation peut modifier fortement les propriétés physicochimiques d'une molécule biologique.`,
    choiceExplanations: [
      `Le carbone du carboxyle est perdu.`,
      `La charge, la polarité et la réactivité peuvent changer.`,
      `Au moins un carboxyle disparaît.`,
      `La structure a changé.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un composé dicarboxylique perd une seule molécule de $\\mathrm{CO_2}$. Après réaction :`,
    choices: [
      `Une fonction carboxylique peut subsister.`,
      `Le produit peut encore être acide.`,
      `Les deux fonctions acides sont obligatoirement perdues.`,
      `Le produit gagne deux carbones.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le nombre de décarboxylations doit être distingué du nombre initial de fonctions acides.`,
    choiceExplanations: [
      `Seul un des deux carboxyles a été perdu.`,
      `Le second groupe $\\mathrm{COOH}$ peut libérer un proton.`,
      `Une seule décarboxylation est indiquée.`,
      `Il en perd un.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une molécule contient un acide carboxylique mais aucun carbonyle voisin. D'après le cours :`,
    choices: [
      `Une décarboxylation peut être moins facile.`,
      `Elle n'est pas déclarée absolument impossible.`,
      `Elle doit nécessairement se produire à température ambiante.`,
      `Elle est automatiquement une hydrolyse.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Il faut interpréter le motif carbonylé voisin comme un facteur favorisant, non comme une définition universelle.`,
    choiceExplanations: [
      `Elle bénéficie de moins de stabilisation.`,
      `La fiche parle de facilité particulière, pas d'exclusivité.`,
      `Aucune garantie n'est donnée.`,
      `Les mécanismes sont différents.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Décarboxylation et acidité :`,
    choices: [
      `La réaction consomme une fonction capable de libérer un proton.`,
      `Le produit peut être moins acide si aucun autre groupe acide ne subsiste.`,
      `La réaction crée toujours un phosphate.`,
      `L'acidité ne peut jamais changer.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La transformation fonctionnelle a des conséquences sur la charge et la solubilité du produit.`,
    choiceExplanations: [
      `Le groupe $\\mathrm{COOH}$ disparaît.`,
      `La source principale de proton a été supprimée.`,
      `Aucun phosphore n'est introduit.`,
      `La disparition du carboxyle peut la modifier fortement.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un composé $\\mathrm{R{-}CH(COOH){-}CO{-}R'}$ se décarboxyle. Le bilan simplifié suggère :`,
    choices: [
      `La perte du groupe $\\mathrm{COOH}$ sous forme de $\\mathrm{CO_2}$.`,
      `La conservation du groupe cétone $\\mathrm{CO{-}R'}$.`,
      `L'ajout d'un groupe cyano.`,
      `Une augmentation du nombre de carbones.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le schéma de la fiche illustre précisément la décarboxylation facilitée par une fonction cétone voisine.`,
    choiceExplanations: [
      `Le carbone carboxylique quitte la molécule.`,
      `Il joue le rôle de carbonyle stabilisateur.`,
      `Aucun nitrile n'est formé.`,
      `La chaîne diminue d'une unité.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une succession « hydrolyse d'un nitrile puis décarboxylation » :`,
    choices: [
      `L'hydrolyse crée d'abord un acide carboxylique.`,
      `La décarboxylation peut ensuite retirer le carbone issu du nitrile.`,
      `Le nombre final de carbones peut redevenir celui du radical initial $\\mathrm{R}$.`,
      `Aucune fonction acide n'apparaît à aucun moment.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le suivi du carbone cyano met en évidence la cohérence de l'enchaînement.`,
    choiceExplanations: [
      `Le nitrile devient $\\mathrm{COOH}$.`,
      `Ce carbone est devenu le carbone carboxylique.`,
      `Le carbone cyano est transformé puis éliminé.`,
      `Elle est l'intermédiaire indispensable.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Bilan de la section sur la décarboxylation :`,
    choices: [
      `Le $\\mathrm{CO_2}$ est un produit, non un réactif.`,
      `Un carbonyle voisin peut faciliter la réaction.`,
      `La voie peut être chimique ou enzymatique.`,
      `Le squelette organique gagne systématiquement un carbone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La maîtrise de la réaction repose sur trois repères : perte de $\\mathrm{CO_2}$, diminution du squelette et stabilisation par un carbonyle voisin.`,
    choiceExplanations: [
      `C'est le sens décarboxylation.`,
      `Il stabilise les électrons lors de la transformation.`,
      `Les deux sont citées.`,
      `Il en perd un.`,
    ],
  },
];
