/**
 * UE14 – Biologie cellulaire – Chapitre 9 : Le cycle cellulaire
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La mitose comprend :`,
    choices: [
      `Cinq phases nucléaires de caryodiérèse.`,
      `Une cytodiérèse cytoplasmique.`,
      `Prophase, prométaphase, métaphase, anaphase et télophase.`,
      `Une nouvelle phase S entre métaphase et anaphase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réplication de l’ADN précède la mitose et n’a pas lieu au milieu de celle-ci.`,
    choiceExplanations: [
      `Exact. La réplication de l’ADN précède la mitose et n’a pas lieu au milieu de celle-ci.`,
      `Exact. La réplication de l’ADN précède la mitose et n’a pas lieu au milieu de celle-ci.`,
      `Exact. La réplication de l’ADN précède la mitose et n’a pas lieu au milieu de celle-ci.`,
      `Faux. La réplication de l’ADN précède la mitose et n’a pas lieu au milieu de celle-ci.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Pendant la mitose :`,
    choices: [
      `L’ADN est extrêmement condensé.`,
      `Il n’y a pas de réplication de l’ADN.`,
      `Il n’y a pas de transcription ni de réparation selon la fiche.`,
      `La synthèse protéique est totalement impossible.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche mentionne la persistance de faibles synthèses protéiques.`,
    choiceExplanations: [
      `Exact. La fiche mentionne la persistance de faibles synthèses protéiques.`,
      `Exact. La fiche mentionne la persistance de faibles synthèses protéiques.`,
      `Exact. La fiche mentionne la persistance de faibles synthèses protéiques.`,
      `Faux. La fiche mentionne la persistance de faibles synthèses protéiques.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En prophase :`,
    choices: [
      `La chromatine continue à se condenser.`,
      `Les centrosomes s’éloignent.`,
      `Le fuseau mitotique se forme.`,
      `Les chromatides sœurs sont déjà séparées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La séparation des chromatides a lieu en anaphase.`,
    choiceExplanations: [
      `Exact. La séparation des chromatides a lieu en anaphase.`,
      `Exact. La séparation des chromatides a lieu en anaphase.`,
      `Exact. La séparation des chromatides a lieu en anaphase.`,
      `Faux. La séparation des chromatides a lieu en anaphase.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En prométaphase :`,
    choices: [
      `L’enveloppe nucléaire est désorganisée.`,
      `Les chromatides sœurs sont capturées par des microtubules de pôles opposés.`,
      `Les chromosomes commencent à être orientés vers la plaque équatoriale.`,
      `Les enveloppes nucléaires sont déjà reformées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La reformation des enveloppes nucléaires intervient en télophase.`,
    choiceExplanations: [
      `Exact. La reformation des enveloppes nucléaires intervient en télophase.`,
      `Exact. La reformation des enveloppes nucléaires intervient en télophase.`,
      `Exact. La reformation des enveloppes nucléaires intervient en télophase.`,
      `Faux. La reformation des enveloppes nucléaires intervient en télophase.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En métaphase :`,
    choices: [
      `L’attachement bipolaire est achevé.`,
      `Les chromosomes forment la plaque équatoriale.`,
      `Les chromatides sœurs sont encore liées.`,
      `Les noyaux fils sont déjà reformés.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les noyaux fils se reforment en télophase.`,
    choiceExplanations: [
      `Exact. Les noyaux fils se reforment en télophase.`,
      `Exact. Les noyaux fils se reforment en télophase.`,
      `Exact. Les noyaux fils se reforment en télophase.`,
      `Faux. Les noyaux fils se reforment en télophase.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En anaphase :`,
    choices: [
      `Les chromatides sœurs se séparent.`,
      `Chaque chromatide devient un chromosome.`,
      `Les lots migrent vers des pôles opposés.`,
      `La réplication recommence immédiatement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’anaphase est une phase de séparation, non de réplication.`,
    choiceExplanations: [
      `Exact. L’anaphase est une phase de séparation, non de réplication.`,
      `Exact. L’anaphase est une phase de séparation, non de réplication.`,
      `Exact. L’anaphase est une phase de séparation, non de réplication.`,
      `Faux. L’anaphase est une phase de séparation, non de réplication.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En télophase :`,
    choices: [
      `Les enveloppes nucléaires se reforment.`,
      `Le fuseau mitotique se dépolymérise.`,
      `Les chromosomes se décondensent.`,
      `Les chromatides sœurs se condensent davantage sur la plaque équatoriale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La plaque équatoriale appartient à la métaphase.`,
    choiceExplanations: [
      `Exact. La plaque équatoriale appartient à la métaphase.`,
      `Exact. La plaque équatoriale appartient à la métaphase.`,
      `Exact. La plaque équatoriale appartient à la métaphase.`,
      `Faux. La plaque équatoriale appartient à la métaphase.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La cytodiérèse :`,
    choices: [
      `Commence avant la fin de l’anaphase.`,
      `Utilise un anneau contractile d’actine et de myosine.`,
      `Sépare les deux cellules filles.`,
      `Est une phase nucléaire de la caryodiérèse.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cytodiérèse est la composante cytoplasmique de la division.`,
    choiceExplanations: [
      `Exact. La cytodiérèse est la composante cytoplasmique de la division.`,
      `Exact. La cytodiérèse est la composante cytoplasmique de la division.`,
      `Exact. La cytodiérèse est la composante cytoplasmique de la division.`,
      `Faux. La cytodiérèse est la composante cytoplasmique de la division.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les structures essentielles de la mitose comprennent :`,
    choices: [
      `Les chromosomes et leurs centromères.`,
      `Les cohésines.`,
      `Le kinétochore.`,
      `Le fuseau mitotique.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Toutes ces structures participent à l’attachement et à la séparation des chromatides.`,
    choiceExplanations: [
      `Exact. Toutes ces structures participent à l’attachement et à la séparation des chromatides.`,
      `Exact. Toutes ces structures participent à l’attachement et à la séparation des chromatides.`,
      `Exact. Toutes ces structures participent à l’attachement et à la séparation des chromatides.`,
      `Exact. Toutes ces structures participent à l’attachement et à la séparation des chromatides.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le centrosome :`,
    choices: [
      `Est un centre organisateur des microtubules.`,
      `Se duplique en préparation de la mitose.`,
      `Donne deux COMT en G2.`,
      `Est absent de toute organisation du fuseau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le fuseau s’organise à partir des deux COMT.`,
    choiceExplanations: [
      `Exact. Le fuseau s’organise à partir des deux COMT.`,
      `Exact. Le fuseau s’organise à partir des deux COMT.`,
      `Exact. Le fuseau s’organise à partir des deux COMT.`,
      `Faux. Le fuseau s’organise à partir des deux COMT.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Étapes de la mitose](/images/training/ue14/biologie-cellulaire/cycle-cellulaire/etapes-mitose.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `La métaphase précède l’anaphase.`,
      `La télophase précède la cytodiérèse finale.`,
      `La prométaphase suit la prophase.`,
      `La phase S est incluse entre prométaphase et métaphase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La phase S appartient à l’interphase, avant G2 et la mitose.`,
    choiceExplanations: [
      `Exact. La phase S appartient à l’interphase, avant G2 et la mitose.`,
      `Exact. La phase S appartient à l’interphase, avant G2 et la mitose.`,
      `Exact. La phase S appartient à l’interphase, avant G2 et la mitose.`,
      `Faux. La phase S appartient à l’interphase, avant G2 et la mitose.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le fuseau mitotique contient :`,
    choices: [
      `Des microtubules astraux.`,
      `Des microtubules polaires.`,
      `Des microtubules kinétochoriens.`,
      `Des filaments intermédiaires responsables de la plaque métaphasique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La plaque métaphasique est organisée par les microtubules du fuseau.`,
    choiceExplanations: [
      `Exact. La plaque métaphasique est organisée par les microtubules du fuseau.`,
      `Exact. La plaque métaphasique est organisée par les microtubules du fuseau.`,
      `Exact. La plaque métaphasique est organisée par les microtubules du fuseau.`,
      `Faux. La plaque métaphasique est organisée par les microtubules du fuseau.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules astraux :`,
    choices: [
      `Rayonnent autour du COMT.`,
      `Sont indirectement en contact avec la membrane plasmique.`,
      `Relient directement chaque kinétochore au pôle opposé.`,
      `Participent à l’organisation spatiale du fuseau.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les microtubules kinétochoriens relient kinétochores et COMT.`,
    choiceExplanations: [
      `Exact. Les microtubules kinétochoriens relient kinétochores et COMT.`,
      `Exact. Les microtubules kinétochoriens relient kinétochores et COMT.`,
      `Faux. Les microtubules kinétochoriens relient kinétochores et COMT.`,
      `Exact. Les microtubules kinétochoriens relient kinétochores et COMT.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules polaires :`,
    choices: [
      `S’ancrent aux COMT.`,
      `Se rencontrent vers le plan équatorial.`,
      `Sont stabilisés par des MAP.`,
      `Relient directement les kinétochores à un seul COMT.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les microtubules kinétochoriens assurent la liaison aux chromosomes.`,
    choiceExplanations: [
      `Exact. Les microtubules kinétochoriens assurent la liaison aux chromosomes.`,
      `Exact. Les microtubules kinétochoriens assurent la liaison aux chromosomes.`,
      `Exact. Les microtubules kinétochoriens assurent la liaison aux chromosomes.`,
      `Faux. Les microtubules kinétochoriens assurent la liaison aux chromosomes.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les microtubules kinétochoriens :`,
    choices: [
      `Relient les kinétochores aux COMT.`,
      `Participent à l’alignement équatorial.`,
      `Sont dynamiques en métaphase.`,
      `Sont absents de l’anaphase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ils raccourcissent pendant l’anaphase pour rapprocher les chromatides des pôles.`,
    choiceExplanations: [
      `Exact. Ils raccourcissent pendant l’anaphase pour rapprocher les chromatides des pôles.`,
      `Exact. Ils raccourcissent pendant l’anaphase pour rapprocher les chromatides des pôles.`,
      `Exact. Ils raccourcissent pendant l’anaphase pour rapprocher les chromatides des pôles.`,
      `Faux. Ils raccourcissent pendant l’anaphase pour rapprocher les chromatides des pôles.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un chromosome mono-orienté :`,
    choices: [
      `Est capturé par des microtubules d’un seul pôle.`,
      `N’est pas encore en équilibre entre les deux pôles.`,
      `Peut devenir bi-orienté après capture par l’autre pôle.`,
      `Peut déclencher normalement l’anaphase si tous les autres chromosomes sont alignés.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le point métaphasique exige que tous les chromosomes soient correctement bi-orientés.`,
    choiceExplanations: [
      `Exact. Le point métaphasique exige que tous les chromosomes soient correctement bi-orientés.`,
      `Exact. Le point métaphasique exige que tous les chromosomes soient correctement bi-orientés.`,
      `Exact. Le point métaphasique exige que tous les chromosomes soient correctement bi-orientés.`,
      `Faux. Le point métaphasique exige que tous les chromosomes soient correctement bi-orientés.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En anaphase :`,
    choices: [
      `La séparase clive les cohésines.`,
      `Les microtubules kinétochoriens se raccourcissent.`,
      `Les microtubules polaires se polymérisent.`,
      `Les microtubules astraux se stabilisent tous définitivement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche indique une dépolymérisation des microtubules astraux pendant l’anaphase.`,
    choiceExplanations: [
      `Exact. La fiche indique une dépolymérisation des microtubules astraux pendant l’anaphase.`,
      `Exact. La fiche indique une dépolymérisation des microtubules astraux pendant l’anaphase.`,
      `Exact. La fiche indique une dépolymérisation des microtubules astraux pendant l’anaphase.`,
      `Faux. La fiche indique une dépolymérisation des microtubules astraux pendant l’anaphase.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le sillon de clivage :`,
    choices: [
      `Se place à égale distance des deux pôles.`,
      `Est perpendiculaire à l’axe longitudinal du fuseau.`,
      `Se situe dans le plan de l’ancienne plaque équatoriale.`,
      `Dépend uniquement de filaments intermédiaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’anneau contractile est constitué d’actine associée à la myosine II.`,
    choiceExplanations: [
      `Exact. L’anneau contractile est constitué d’actine associée à la myosine II.`,
      `Exact. L’anneau contractile est constitué d’actine associée à la myosine II.`,
      `Exact. L’anneau contractile est constitué d’actine associée à la myosine II.`,
      `Faux. L’anneau contractile est constitué d’actine associée à la myosine II.`,
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le corps intermédiaire :`,
    choices: [
      `Résulte de la contraction de l’anneau.`,
      `S’affine progressivement.`,
      `Se rompt pour achever la division.`,
      `Se forme pendant la phase S.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le corps intermédiaire appartient à la fin de la cytodiérèse.`,
    choiceExplanations: [
      `Exact. Le corps intermédiaire appartient à la fin de la cytodiérèse.`,
      `Exact. Le corps intermédiaire appartient à la fin de la cytodiérèse.`,
      `Exact. Le corps intermédiaire appartient à la fin de la cytodiérèse.`,
      `Faux. Le corps intermédiaire appartient à la fin de la cytodiérèse.`,
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Fuseau et APC](/images/training/ue14/biologie-cellulaire/cycle-cellulaire/fuseau-apc-anaphase.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Les trois catégories de microtubules ont des fonctions distinctes.`,
      `APC/cdc20 favorise la destruction de la sécurine.`,
      `La séparase active clive les cohésines.`,
      `La sécurine active directement la séparase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La sécurine maintient la séparase inactive tant qu’elle n’est pas dégradée.`,
    choiceExplanations: [
      `Exact. La sécurine maintient la séparase inactive tant qu’elle n’est pas dégradée.`,
      `Exact. La sécurine maintient la séparase inactive tant qu’elle n’est pas dégradée.`,
      `Exact. La sécurine maintient la séparase inactive tant qu’elle n’est pas dégradée.`,
      `Faux. La sécurine maintient la séparase inactive tant qu’elle n’est pas dégradée.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le complexe APC/cdc20 :`,
    choices: [
      `Contient une E3 ubiquitine ligase.`,
      `Ubiquitine la sécurine.`,
      `Permet sa dégradation par le protéasome.`,
      `Clive directement les cohésines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le clivage des cohésines est réalisé par la séparase libérée après destruction de la sécurine.`,
    choiceExplanations: [
      `Exact. Le clivage des cohésines est réalisé par la séparase libérée après destruction de la sécurine.`,
      `Exact. Le clivage des cohésines est réalisé par la séparase libérée après destruction de la sécurine.`,
      `Exact. Le clivage des cohésines est réalisé par la séparase libérée après destruction de la sécurine.`,
      `Faux. Le clivage des cohésines est réalisé par la séparase libérée après destruction de la sécurine.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Lorsque tous les chromosomes sont bi-orientés :`,
    choices: [
      `APC/cdc20 peut être activé.`,
      `La sécurine est détruite.`,
      `La séparase devient active.`,
      `Les cohésines sont maintenues intactes pour empêcher l’anaphase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’entrée en anaphase exige la destruction des cohésines.`,
    choiceExplanations: [
      `Exact. L’entrée en anaphase exige la destruction des cohésines.`,
      `Exact. L’entrée en anaphase exige la destruction des cohésines.`,
      `Exact. L’entrée en anaphase exige la destruction des cohésines.`,
      `Faux. L’entrée en anaphase exige la destruction des cohésines.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `En cas de défaut d’attachement d’un chromosome :`,
    choices: [
      `APC/cdc20 est inhibé.`,
      `La sécurine reste présente.`,
      `La séparase reste inactive.`,
      `Les chromatides se séparent malgré tout.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le checkpoint métaphasique empêche la séparation prématurée des chromatides.`,
    choiceExplanations: [
      `Exact. Le checkpoint métaphasique empêche la séparation prématurée des chromatides.`,
      `Exact. Le checkpoint métaphasique empêche la séparation prématurée des chromatides.`,
      `Exact. Le checkpoint métaphasique empêche la séparation prématurée des chromatides.`,
      `Faux. Le checkpoint métaphasique empêche la séparation prématurée des chromatides.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La sortie de mitose dépend :`,
    choices: [
      `De la destruction du MPF.`,
      `De l’activation d’APC/cdh1.`,
      `De l’ubiquitination de la cycline B.`,
      `De la dégradation de CDK1 par le protéasome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cycline B est dégradée ; CDK1 est libérée inactive dans le cytoplasme.`,
    choiceExplanations: [
      `Exact. La cycline B est dégradée ; CDK1 est libérée inactive dans le cytoplasme.`,
      `Exact. La cycline B est dégradée ; CDK1 est libérée inactive dans le cytoplasme.`,
      `Exact. La cycline B est dégradée ; CDK1 est libérée inactive dans le cytoplasme.`,
      `Faux. La cycline B est dégradée ; CDK1 est libérée inactive dans le cytoplasme.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le passage d’APC/cdc20 à APC/cdh1 illustre :`,
    choices: [
      `Un changement de coactivateur.`,
      `Une régulation temporelle du complexe APC.`,
      `La succession entre entrée en anaphase et sortie de mitose.`,
      `La disparition définitive de toute activité ubiquitine ligase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `APC reste une E3 ligase mais change de cible et de coactivateur selon l’étape.`,
    choiceExplanations: [
      `Exact. APC reste une E3 ligase mais change de cible et de coactivateur selon l’étape.`,
      `Exact. APC reste une E3 ligase mais change de cible et de coactivateur selon l’étape.`,
      `Exact. APC reste une E3 ligase mais change de cible et de coactivateur selon l’étape.`,
      `Faux. APC reste une E3 ligase mais change de cible et de coactivateur selon l’étape.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le MPF en prophase favorise :`,
    choices: [
      `La condensation de la chromatine.`,
      `La formation et l’allongement du fuseau.`,
      `La disparition de l’enveloppe nucléaire.`,
      `La reformation immédiate des noyaux fils.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La reformation des noyaux fils suit la diminution de l’activité MPF en fin de mitose.`,
    choiceExplanations: [
      `Exact. La reformation des noyaux fils suit la diminution de l’activité MPF en fin de mitose.`,
      `Exact. La reformation des noyaux fils suit la diminution de l’activité MPF en fin de mitose.`,
      `Exact. La reformation des noyaux fils suit la diminution de l’activité MPF en fin de mitose.`,
      `Faux. La reformation des noyaux fils suit la diminution de l’activité MPF en fin de mitose.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition de la séparase :`,
    choices: [
      `Empêche le clivage des cohésines.`,
      `Bloque la séparation des chromatides.`,
      `Peut empêcher l’entrée correcte en anaphase.`,
      `Accélère la cytodiérèse malgré des chromatides encore liées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La séparase est indispensable à la dissociation des chromatides sœurs.`,
    choiceExplanations: [
      `Exact. La séparase est indispensable à la dissociation des chromatides sœurs.`,
      `Exact. La séparase est indispensable à la dissociation des chromatides sœurs.`,
      `Exact. La séparase est indispensable à la dissociation des chromatides sœurs.`,
      `Faux. La séparase est indispensable à la dissociation des chromatides sœurs.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation empêchant l’ubiquitination de la sécurine :`,
    choices: [
      `Maintient la séparase inactive.`,
      `Peut bloquer la cellule en métaphase.`,
      `Empêche le clivage des cohésines.`,
      `Active directement APC/cdh1 et la sortie de mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La sécurine doit être détruite pour libérer la séparase.`,
    choiceExplanations: [
      `Exact. La sécurine doit être détruite pour libérer la séparase.`,
      `Exact. La sécurine doit être détruite pour libérer la séparase.`,
      `Exact. La sécurine doit être détruite pour libérer la séparase.`,
      `Faux. La sécurine doit être détruite pour libérer la séparase.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les forces de séparation en anaphase résultent :`,
    choices: [
      `Du raccourcissement des microtubules kinétochoriens.`,
      `De l’allongement des microtubules polaires.`,
      `De moteurs moléculaires générant traction et répulsion.`,
      `D’une nouvelle réplication des chromatides.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’anaphase est un mouvement mécanique de chromatides déjà répliquées.`,
    choiceExplanations: [
      `Exact. L’anaphase est un mouvement mécanique de chromatides déjà répliquées.`,
      `Exact. L’anaphase est un mouvement mécanique de chromatides déjà répliquées.`,
      `Exact. L’anaphase est un mouvement mécanique de chromatides déjà répliquées.`,
      `Faux. L’anaphase est un mouvement mécanique de chromatides déjà répliquées.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `La mitose répartit les chromatides en deux lots identiques.`,
      `Le fuseau est organisé par les COMT et trois types de microtubules.`,
      `APC/cdc20 déclenche l’anaphase via la sécurine et la séparase.`,
      `APC/cdh1 contribue à la sortie de mitose en dégradant la cycline B.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La mécanique du fuseau et les contrôles protéolytiques assurent une division fidèle.`,
    choiceExplanations: [
      `Exact. La mécanique du fuseau et les contrôles protéolytiques assurent une division fidèle.`,
      `Exact. La mécanique du fuseau et les contrôles protéolytiques assurent une division fidèle.`,
      `Exact. La mécanique du fuseau et les contrôles protéolytiques assurent une division fidèle.`,
      `Exact. La mécanique du fuseau et les contrôles protéolytiques assurent une division fidèle.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `deroulement-de-la-mitose`,
    title: `Déroulement de la mitose`,
    description: `Caryodiérèse, cytodiérèse et structures essentielles.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `fuseau-mitotique-et-cytodierese`,
    title: `Fuseau mitotique et cytodiérèse`,
    description: `Microtubules astraux, polaires, kinétochoriens et anneau contractile.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `controle-de-la-sortie-de-mitose`,
    title: `Contrôle de l’anaphase et de la sortie de mitose`,
    description: `APC/cdc20, sécurine, séparase, cohésines et APC/cdh1.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
