/**
 * UE14 – Biologie cellulaire – Chapitre 5
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le fonctionnement des flux membranaires repose sur :`,
    choices: [
      `Quatre flux.`,
      `Des compartiments pouvant être donneurs ou receveurs.`,
      `Des vésicules dont le revêtement varie selon la destination.`,
      `Un seul flux unidirectionnel sans retour.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le SEM combine un flux principal et plusieurs flux rétrogrades.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les quatre étapes générales d’un flux vésiculaire comprennent :`,
    choices: [
      `Bourgeonnement.`,
      `Perte du revêtement.`,
      `Transport orienté.`,
      `Amarrage et fusion.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Ces étapes organisent le transfert entre compartiments donneur et receveur.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 93,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les revêtements de bourgeonnement peuvent être :`,
    choices: [
      `Clathrine.`,
      `Coatomères.`,
      `Cavéoline.`,
      `Hydrolases acides libres.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les hydrolases sont des cargaisons ou enzymes luminales, non des revêtements cytosoliques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 94,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le transport orienté dans le cytosol fait intervenir :`,
    choices: [
      `Les microtubules.`,
      `Les kinésines et dynéines.`,
      `Le cytosquelette cortical d’actine près de la membrane.`,
      `Uniquement la diffusion brownienne sans protéines motrices.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les moteurs et le cytosquelette guident les vésicules jusqu’à leur destination.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 95,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Près de la membrane plasmique, le relais peut impliquer :`,
    choices: [
      `L’actine corticale.`,
      `La gelsoline.`,
      `Des myosines courtes.`,
      `Les lamines nucléaires uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cytosquelette d’actine et ses protéines associées participent aux étapes terminales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 96,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’amarrage d’une vésicule :`,
    choices: [
      `Précède la fusion.`,
      `Peut faire intervenir une petite protéine G Rab.`,
      `Utilise du GTP.`,
      `Déverse immédiatement le contenu sans reconnaissance du compartiment receveur.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’amarrage assure la reconnaissance et le rapprochement avant fusion.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 97,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La protéine Rab :`,
    choices: [
      `Est une petite protéine G monomérique.`,
      `Recrute un complexe d’amarrage cytosolique.`,
      `Participe au rapprochement de la vésicule et de sa cible.`,
      `Est une hydrolase lysosomale luminale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Rab est un régulateur cytosolique associé aux membranes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 98,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La fusion membranaire :`,
    choices: [
      `Intervient après l’amarrage.`,
      `Fait intervenir des facteurs cytosoliques de fusion.`,
      `Transfère le contenu dans le compartiment receveur.`,
      `Est propre aux lysosomes et absente des autres compartiments.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le principe amarrage-fusion est commun aux compartiments du SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 99,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les neurotoxines botulique ou tétanique peuvent :`,
    choices: [
      `Cliver des protéines d’accrochage ou des récepteurs vésiculaires.`,
      `Bloquer la libération de neurotransmetteurs.`,
      `Perturber la fusion des vésicules synaptiques.`,
      `Accélérer systématiquement l’exocytose synaptique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces toxines empêchent la fusion normale des vésicules synaptiques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 100,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La bréfeldine A :`,
    choices: [
      `Est utilisée in vitro pour étudier les flux.`,
      `Peut bloquer de façon réversible des protéines G monomériques.`,
      `Perturbe le bourgeonnement vésiculaire.`,
      `Est le seul blocage physiologique in vivo pendant la mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le blocage physiologique in vivo mentionné est celui de la mitose, non l’administration de bréfeldine A.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pendant la mitose :`,
    choices: [
      `Le trafic membranaire est temporairement modifié.`,
      `Le Golgi se fragmente en vésicules.`,
      `L’enveloppe nucléaire se fond dans le RE.`,
      `Les flux restent strictement identiques à l’interphase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réorganisation du RE, du Golgi et de l’enveloppe nucléaire perturbe temporairement les flux.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les signaux d’adressage ou de rétention :`,
    choices: [
      `Peuvent être portés par la séquence peptidique.`,
      `Peuvent dépendre du premier segment transmembranaire.`,
      `Peuvent se trouver dans un domaine cytosolique.`,
      `Sont inutiles pour le trafic vésiculaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces signaux orientent le tri et le retour des protéines dans le SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le motif KKXX :`,
    choices: [
      `Se situe dans un domaine cytosolique.`,
      `Concerne certaines protéines transmembranaires.`,
      `Peut favoriser le retour vers le RE via les coatomères.`,
      `Est un sucre ajouté dans le Golgi cis.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `KKXX est une séquence peptidique, non une modification glucidique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le motif KDEL :`,
    choices: [
      `Se trouve aux quatre derniers acides aminés de certaines protéines solubles du RE.`,
      `Est reconnu dans le Golgi.`,
      `Permet un retour vers le RE via le récepteur ERD.`,
      `Est le signal d’adressage des hydrolases lysosomales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le M6P, et non KDEL, adresse les hydrolases lysosomales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les protéines solubles portant KDEL :`,
    choices: [
      `BiP.`,
      `PDI.`,
      `Elles peuvent s’échapper du RE par le flux principal puis être récupérées.`,
      `La clathrine est l’exemple principal de protéine soluble KDEL.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `BiP et PDI sont des protéines résidentes du RE récupérées par le système KDEL/ERD.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le récepteur ERD :`,
    choices: [
      `Reconnaît le signal KDEL dans le Golgi.`,
      `Assure la récupération de protéines solubles du RE.`,
      `Est lui-même une protéine transmembranaire.`,
      `Ajoute le mannose-6-phosphate aux hydrolases.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ajout du M6P dépend de la GlcNAc-phosphotransférase, non du récepteur ERD.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 107,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante :

![Signaux d’adressage](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-2/signaux-adressage-retention.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `KDEL récupère des protéines solubles du RE.`,
      `KKXX concerne des protéines transmembranaires du RE.`,
      `M6P adresse des hydrolases vers les lysosomes.`,
      `Tous les signaux conduisent à la même destination.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les signaux diffèrent selon la nature de la protéine et sa destination.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 108,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine soluble du RE dépourvue de KDEL risque :`,
    choices: [
      `De ne pas être récupérée efficacement après passage au Golgi.`,
      `De progresser vers d’autres compartiments du flux principal.`,
      `D’être sécrétée de façon inappropriée.`,
      `D’être automatiquement transformée en protéine transmembranaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’absence du signal de rétention peut conduire à une mauvaise localisation.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 109,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine transmembranaire du RE portant KKXX :`,
    choices: [
      `Peut interagir avec les coatomères.`,
      `Peut être ramenée vers le RE si elle s’échappe.`,
      `Porte le signal sur son domaine cytosolique.`,
      `Est nécessairement une hydrolase acide soluble.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `KKXX est un signal de récupération de protéines transmembranaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 110,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le premier segment transmembranaire peut :`,
    choices: [
      `Participer à l’adressage golgien de certaines protéines.`,
      `Constituer un signal dans la séquence peptidique.`,
      `Être distingué du motif cytosolique KKXX.`,
      `Remplacer le M6P pour toutes les hydrolases lysosomales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les hydrolases solubles utilisent le système M6P et un récepteur transmembranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les protéines solubles nécessitent souvent :`,
    choices: [
      `Un récepteur transmembranaire pour leur tri.`,
      `Un signal peptidique ou glucidique.`,
      `Un système de récupération lorsque leur destination est le RE.`,
      `Aucun mécanisme d’adressage car elles diffusent librement entre compartiments.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La lumière des compartiments n’est pas un continuum permettant une diffusion libre non contrôlée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le même compartiment membranaire peut :`,
    choices: [
      `Produire des vésicules à revêtements différents.`,
      `Être donneur ou receveur selon le flux.`,
      `Participer à plusieurs destinations.`,
      `Fonctionner sans aucun signal d’adressage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le tri dépend de signaux et de machineries distinctes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut de Rab ou de son GTP pourrait :`,
    choices: [
      `Perturber l’amarrage vésiculaire.`,
      `Empêcher le recrutement du complexe d’amarrage.`,
      `Réduire la spécificité du rapprochement avec le compartiment receveur.`,
      `Augmenter obligatoirement la N-glycosylation dans le RE.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Rab intervient dans l’amarrage, pas directement dans la N-glycosylation.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un blocage des microtubules peut :`,
    choices: [
      `Perturber le transport à longue distance des vésicules.`,
      `Affecter les flux entre RE, Golgi et périphérie.`,
      `Réduire l’efficacité des moteurs kinésines et dynéines.`,
      `N’avoir aucun effet sur le trafic intracellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les microtubules forment des rails majeurs du transport vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un blocage de l’actine corticale peut surtout perturber :`,
    choices: [
      `Les étapes proches de la membrane plasmique.`,
      `Les mouvements locaux de vésicules.`,
      `L’exocytose et l’endocytose.`,
      `La réplication de l’ADN mitochondrial uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’actine participe aux étapes terminales du trafic membranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le flux principal :`,
    choices: [
      `Conduit du RE vers le Golgi.`,
      `Poursuit vers le TGN et différentes destinations.`,
      `Est associé au sens de l’exocytose.`,
      `Ramène exclusivement les protéines KDEL vers le RE.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le retour KDEL correspond à un flux rétrograde de récupération.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les flux rétrogrades :`,
    choices: [
      `Participent au recyclage.`,
      `Peuvent ramener des protéines du Golgi vers le RE.`,
      `Peuvent être détournés par certaines toxines.`,
      `Sont inutiles à l’homéostasie du SEM.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les flux rétrogrades maintiennent la composition des compartiments et récupèrent des protéines résidentes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le SEM est en interface constante avec :`,
    choices: [
      `Le cytosol.`,
      `Le cytosquelette.`,
      `La matrice extracellulaire.`,
      `Uniquement le noyau, sans contact avec le reste de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le SEM communique avec de multiples compartiments cellulaires et avec l’extérieur.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Des perturbations des flux ou de l’adressage peuvent entraîner :`,
    choices: [
      `Des pathologies congénitales.`,
      `Des pathologies acquises.`,
      `Des défauts de biosynthèse, d’échange ou de catabolisme.`,
      `Toujours une amélioration du fonctionnement cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La bonne orientation des transports est indispensable à l’homéostasie cellulaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse des flux membranaires est correcte ?`,
    choices: [
      `Ils exigent revêtements, cytosquelette, moteurs et signaux d’adressage.`,
      `L’amarrage précède la fusion.`,
      `KDEL, KKXX et M6P orientent des protéines différentes.`,
      `Le trafic est aléatoire et indépendant de la nature des protéines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le trafic du SEM est hautement organisé et sélectif.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `etapes-et-acteurs-des-flux`,
    title: `Étapes et acteurs des flux membranaires`,
    description: `Revêtements, cytosquelette, moteurs, amarrage et fusion.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `adressage-et-retention-dans-le-sem`,
    title: `Adressage et rétention dans le SEM`,
    description: `Rab, KDEL, KKXX, M6P et récepteur ERD.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `regulation-et-dysfonctionnements-des-flux`,
    title: `Régulation et dysfonctionnements des flux`,
    description: `Bréfeldine A, mitose, toxines et conséquences des défauts de trafic.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
