import type { HealthTrainingAuthorQuestion } from "@/core/questions/health-authoring";

export const healthTrainingDemoAuthorQuestions: HealthTrainingAuthorQuestion[] = [
  {
    order: 1,
    difficulty: "EASY",
    format: "QRU",
    question: "Quel est le principal organite responsable de la synthèse d'ATP lors de la respiration cellulaire ?",
    choices: [
      {
        content: "Appareil de Golgi",
        correct: false,
        explanation: "L'appareil de Golgi est impliqué dans la maturation et le tri des protéines.",
      },
      {
        content: "Mitochondrie",
        correct: true,
        explanation: "La mitochondrie est la centrale énergétique cellulaire produisant l'ATP par phosphorylation oxydative.",
      },
      {
        content: "Lysosome",
        correct: false,
        explanation: "Le lysosome est le compartiment de dégradation hydrolytique.",
      },
      {
        content: "Réticulum endoplasmique lisse",
        correct: false,
        explanation: "Le REL intervient principalement dans la synthèse des lipides et le stockage du calcium.",
      },
    ],
    explanation: "La mitochondrie possède une membrane interne repliée en crêtes contenant la chaîne de transport des électrons et l'ATP synthétase.",
    points: 1,
    tags: ["cytologie", "bioénergétique"],
    source: "Banque d'entraînement UE14",
  },
  {
    order: 2,
    difficulty: "EASY",
    format: "QRM",
    question: "Parmi les propositions suivantes concernant les acides gras insaturés, lesquelles sont exactes ?",
    choices: [
      {
        content: "Ils possèdent au moins une double liaison carbone-carbone.",
        correct: true,
        explanation: "La présence d'au moins une double liaison C=C définit un acide gras insaturé.",
      },
      {
        content: "La conformation cis induit un coude dans la chaîne hydrocarbonée.",
        correct: true,
        explanation: "La double liaison cis naturelle crée une rigidité et une courbure spatiale.",
      },
      {
        content: "Ils ont une température de fusion plus élevée que leurs homologues saturés de même longueur.",
        correct: false,
        explanation: "Leur température de fusion est plus basse en raison de la diminution des interactions de Van der Waals.",
      },
      {
        content: "L'acide oléique est un acide gras mono-insaturé en omega-9.",
        correct: true,
        explanation: "L'acide oléique (18:1 cis-9) est un acide gras mono-insaturé n-9.",
      },
    ],
    explanation: "Les doubles liaisons des acides gras naturels sont majoritairement de configuration cis, abaissant le point de fusion.",
    points: 2,
    tags: ["biochimie", "lipides"],
    source: "Annales Reims 2023",
  },
  {
    order: 3,
    difficulty: "MEDIUM",
    format: "QRP",
    requiredSelectionCount: 2,
    question: "Parmi les acides aminés suivants, sélectionnez les deux acides aminés possédant une chaîne latérale dicarboxylique (acides).",
    choices: [
      {
        content: "Acide aspartique (Aspartate)",
        correct: true,
        explanation: "L'aspartate possède un groupement β-carboxyle (pKa ~ 3,9).",
      },
      {
        content: "Lysine",
        correct: false,
        explanation: "La lysine possède une chaîne latérale aliphatique basique.",
      },
      {
        content: "Acide glutamique (Glutamate)",
        correct: true,
        explanation: "Le glutamate possède un groupement γ-carboxyle (pKa ~ 4,3).",
      },
      {
        content: "Alanine",
        correct: false,
        explanation: "L'alanine possède un groupement méthyle neutre.",
      },
    ],
    explanation: "L'aspartate et le glutamate sont les deux seuls acides aminés dicarboxyliques chargés négativement à pH physiologique.",
    points: 2,
    tags: ["biochimie", "acides-amines"],
    source: "Annales Reims 2024",
  },
  {
    order: 4,
    difficulty: "MEDIUM",
    format: "QRPL",
    requiredSelectionCount: 3,
    question: "Parmi la liste suivante d'acides aminés, sélectionnez les trois acides aminés à chaîne latérale strictement aromatique.",
    choices: [
      {
        content: "Phénylalanine",
        correct: true,
        explanation: "La phénylalanine possède un noyau benzénique aromatique.",
      },
      {
        content: "Tyrosine",
        correct: true,
        explanation: "La tyrosine possède un noyau phénol aromatique.",
      },
      {
        content: "Tryptophane",
        correct: true,
        explanation: "Le tryptophane possède un noyau indole aromatique.",
      },
      {
        content: "Alanine",
        correct: false,
        explanation: "L'alanine possède un groupement méthyle aliphatique.",
      },
      {
        content: "Leucine",
        correct: false,
        explanation: "La leucine est un acide aminé ramifié aliphatique.",
      },
      {
        content: "Lysine",
        correct: false,
        explanation: "La lysine est un acide aminé basique aliphatique.",
      },
      {
        content: "Sérine",
        correct: false,
        explanation: "La sérine possède une fonction alcool aliphatique.",
      },
      {
        content: "Proline",
        correct: false,
        explanation: "La proline est un iminoacide cyclique aliphatique.",
      },
      {
        content: "Valine",
        correct: false,
        explanation: "La valine est un acide aminé ramifié aliphatique.",
      },
      {
        content: "Glutamate",
        correct: false,
        explanation: "Le glutamate est un acide aminé dicarboxylique acide.",
      },
    ],
    explanation: "Les 3 acides aminés aromatiques sont la Phénylalanine, la Tyrosine et le Tryptophane. Ils absorbent les UV à 280 nm.",
    points: 3,
    tags: ["biochimie", "acides-amines"],
  },
  {
    order: 5,
    difficulty: "MEDIUM",
    format: "QROC",
    question: "Quel organite membranaire est le siège principal de la N-glycosylation initiale des protéines ?",
    answer: {
      type: "text",
      acceptedAnswers: [
        "réticulum endoplasmique rugueux",
        "réticulum endoplasmique granuleux",
        "RER",
        "REG",
      ],
      normalization: {
        trim: true,
        collapseWhitespace: true,
        caseSensitive: false,
        ignoreAccents: true,
      },
    },
    explanation: "La N-glycosylation débute dans le RER/REG par le transfert d'un oligosaccharide précurseur à 14 oses.",
    points: 1,
    tags: ["biologie-cellulaire"],
  },
  {
    order: 6,
    difficulty: "MEDIUM",
    format: "QROC",
    question: "Quelle est la valeur physiologique moyenne du pH sanguin artériel chez l'humain ?",
    answer: {
      type: "number",
      value: 7.4,
      tolerance: 0.05,
      unit: "pH",
    },
    explanation: "Le pH du sang artériel est strictement régulé entre 7,35 et 7,45.",
    points: 1,
    tags: ["physiologie"],
  },
  {
    order: 7,
    difficulty: "HARD",
    format: "QZONE",
    question: "Cliquez sur la mitochondrie dans le schéma de la cellule ci-dessous.",
    image: {
      src: "/images/training/histologie/cellule-animale.png",
      alt: "Schéma d'organisation d'une cellule animale",
      width: 800,
      height: 600,
    },
    expectedZones: [
      {
        id: "target-mitochondrie",
        label: "Mitochondrie",
        x: 0.45,
        y: 0.6,
        tolerance: 0.08,
      },
    ],
    explanation: "La mitochondrie se reconnaît notamment à sa double membrane et à ses crêtes membranaires internes.",
    points: 2,
    tags: ["histologie", "biologie-cellulaire"],
  },
];
