import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_ORDER = 1;

export const SECTION_A_NAMES_DISCOVERY_QUIZ_SLUG =
  `section-a-discovery-acides-nomenclature`;
export const SECTION_A_ACIDITY_PRACTICE_QUIZ_SLUG =
  `section-a-practice-acidite-carboxylate`;
export const SECTION_A_DERIVATIVES_MASTER_QUIZ_SLUG =
  `section-a-master-derives-acides-activation`;

export const SECTION_A_NAMES_DISCOVERY_QUESTION_ORDERS: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
export const SECTION_A_ACIDITY_PRACTICE_QUESTION_ORDERS: number[] = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
export const SECTION_A_DERIVATIVES_MASTER_QUESTION_ORDERS: number[] = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: SECTION_A_NAMES_DISCOVERY_QUIZ_SLUG,
    title: `Acides carboxyliques : structure et nomenclature`,
    description: `Reconnaître la fonction carboxylique et mémoriser les noms systématiques et usuels des premiers acides.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_A_ORDER,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: SECTION_A_ACIDITY_PRACTICE_QUIZ_SLUG,
    title: `Acidité, carboxylate et mésomérie`,
    description: `Relier la perte du proton à la stabilisation du carboxylate et comparer l’acidité des fonctions du cours.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_A_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 11 },
      { type: 'QUESTION', questionOrder: 12 },
      { type: 'QUESTION', questionOrder: 13 },
      { type: 'QUESTION', questionOrder: 14 },
      { type: 'QUESTION', questionOrder: 15 },
      { type: 'QUESTION', questionOrder: 16 },
      { type: 'QUESTION', questionOrder: 17 },
      {
        type: 'GROUP',
        title: `Comparer trois hydrogènes acides`,
        sharedStatement: `On compare l’acide acétique, l’éthanol et l’acétone afin d’ordonner qualitativement la mobilité de leurs hydrogènes acides.`,
        questionOrders: [18, 19, 20],
      },
    ],
  },
  {
    order: 3,
    slug: SECTION_A_DERIVATIVES_MASTER_QUIZ_SLUG,
    title: `Dérivés d’acides et activation`,
    description: `Identifier chlorures d’acyle, anhydrides et esters, puis comprendre l’intérêt de l’activation pour les couplages.`,
    stage: 'MASTER',
    sectionOrder: SECTION_A_ORDER,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la fonction acide carboxylique :`,
    choices: [
      `Elle contient le motif $\\mathrm{-COOH}$.`,
      `Sa déprotonation conduit à un ion carboxylate.`,
      `Sa formule générale est $\\mathrm{R{-}NH_2}$.`,
      `Elle ne contient aucun atome d'oxygène.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Un acide carboxylique peut céder le proton du groupe $\\mathrm{-OH}$ pour former un carboxylate stabilisé.`,
    choiceExplanations: [
      `Le motif carboxyle associe un carbonyle et un hydroxyle sur le même carbone.`,
      `Le départ de $\\mathrm{H^+}$ forme $\\mathrm{RCOO^-}$.`,
      `Cette formule correspond à une amine primaire.`,
      `Elle en contient deux.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le bilan $\\mathrm{RCOOH \\rightarrow RCOO^- + H^+}$ traduit :`,
    choices: [
      `Une déprotonation.`,
      `Le comportement de $\\mathrm{RCOOH}$ comme acide de Brønsted.`,
      `Une réduction du carbone carbonylé.`,
      `La formation d'un alcool.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La définition protonique de l'acide est illustrée par la formation du couple $\\mathrm{RCOOH/RCOO^-}$.`,
    choiceExplanations: [
      `Le proton est libéré par l'acide.`,
      `Un acide de Brønsted donne un proton.`,
      `Aucun transfert d'hydrure ni changement d'oxydation n'est décrit.`,
      `Le produit organique est un carboxylate.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formule $\\mathrm{HCOOH}$ correspond :`,
    choices: [
      `À l'acide méthanoïque.`,
      `À l'acide formique.`,
      `À l'acide éthanoïque.`,
      `À une cétone.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'acide méthanoïque, ou formique, est le plus petit acide carboxylique.`,
    choiceExplanations: [
      `La chaîne comporte un seul carbone.`,
      `C'est son nom usuel.`,
      `L'acide éthanoïque est $\\mathrm{CH_3COOH}$.`,
      `Le motif est carboxylique.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formule $\\mathrm{CH_3COOH}$ correspond :`,
    choices: [
      `À l'acide éthanoïque.`,
      `À l'acide acétique.`,
      `À l'acide propionique.`,
      `À un ester.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'acide éthanoïque est couramment appelé acide acétique.`,
    choiceExplanations: [
      `La chaîne principale compte deux carbones.`,
      `C'est son nom usuel.`,
      `L'acide propionique possède trois carbones.`,
      `Un ester aurait un substituant carboné après l'oxygène : $\\mathrm{RCOOR'}$.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formule $\\mathrm{CH_3CH_2COOH}$ :`,
    choices: [
      `Est celle de l'acide propanoïque.`,
      `Correspond aussi à l'acide propionique.`,
      `Est celle de l'acide butanoïque.`,
      `Ne possède pas de groupe carbonyle.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le carbone du groupe carboxyle est inclus dans le comptage de la chaîne principale.`,
    choiceExplanations: [
      `La chaîne totale compte trois carbones.`,
      `Propionique est le nom usuel.`,
      `L'acide butanoïque contient quatre carbones.`,
      `Le groupe $\\mathrm{C{=}O}$ appartient au carboxyle.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de $\\mathrm{CH_3CH_2CH_2COOH}$ :`,
    choices: [
      `Son nom systématique est acide butanoïque.`,
      `Son nom usuel est acide butyrique.`,
      `Il s'agit de l'acide méthanoïque.`,
      `Le carbone carboxylique n'est pas compté dans la chaîne.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les noms des quatre premiers acides sont méthanoïque, éthanoïque, propanoïque et butanoïque.`,
    choiceExplanations: [
      `La chaîne compte quatre carbones.`,
      `C'est le nom usuel donné dans la fiche.`,
      `L'acide méthanoïque n'a qu'un carbone.`,
      `Il fait partie de la chaîne principale.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les formules suivantes, lesquelles représentent un acide carboxylique ?`,
    choices: [
      `$\\mathrm{CH_3COOH}$.`,
      `$\\mathrm{HCO_2H}$.`,
      `$\\mathrm{CH_3CHO}$.`,
      `$\\mathrm{CH_3COOCH_3}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La présence du motif $\\mathrm{-C(=O)OH}$ distingue l'acide de l'aldéhyde et de l'ester.`,
    choiceExplanations: [
      `Elle contient le motif $\\mathrm{-COOH}$.`,
      `C'est une autre écriture de $\\mathrm{HCOOH}$.`,
      `Il s'agit d'un aldéhyde.`,
      `Il s'agit d'un ester.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans le nom « acide propanoïque » :`,
    choices: [
      `Le préfixe indique une chaîne de trois carbones.`,
      `Le carbone du groupe $\\mathrm{COOH}$ est inclus dans ces trois carbones.`,
      `Le suffixe « -one » est celui de la fonction acide.`,
      `La molécule ne peut pas libérer de proton.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La nomenclature combine « acide », le radical de la chaîne et le suffixe « -oïque ».`,
    choiceExplanations: [
      `« prop- » correspond à trois carbones.`,
      `Il appartient à la chaîne principale.`,
      `« -one » désigne une cétone.`,
      `Le proton du groupe carboxyle est acide.`,
    ],
  },
  {
    order: 9,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un flacon porte l'étiquette « acide acétique ». À propos de l'espèce indiquée :`,
    choices: [
      `Sa formule est $\\mathrm{CH_3COOH}$.`,
      `Elle peut former l'ion acétate $\\mathrm{CH_3COO^-}$.`,
      `Elle est un alcool secondaire.`,
      `Elle contient trois atomes de carbone.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le couple acide acétique/acétate illustre la perte réversible du proton carboxylique.`,
    choiceExplanations: [
      `Acide acétique et acide éthanoïque sont synonymes.`,
      `La déprotonation donne la base conjuguée.`,
      `Elle appartient aux acides carboxyliques.`,
      `Elle en contient deux.`,
    ],
  },
  {
    order: 10,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison des quatre acides cités dans le cours :`,
    choices: [
      `L'acide formique est l'acide méthanoïque.`,
      `L'acide butyrique possède plus de carbones que l'acide propionique.`,
      `L'acide acétique est l'acide propanoïque.`,
      `Tous sont des amides.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les noms usuels doivent être associés sans modifier le nombre de carbones de la chaîne.`,
    choiceExplanations: [
      `Les deux noms désignent $\\mathrm{HCOOH}$.`,
      `Ils en ont respectivement quatre et trois.`,
      `Il s'agit de l'acide éthanoïque.`,
      `Tous sont des acides carboxyliques.`,
    ],
  },
  {
    order: 11,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Selon la définition de Lewis utilisée dans le chapitre :`,
    choices: [
      `Un acide peut capter une paire d'électrons.`,
      `Une base peut donner une paire d'électrons.`,
      `Un acide est nécessairement chargé négativement.`,
      `Une base ne possède jamais de doublet libre.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le chapitre mobilise à la fois la définition protonique et la définition électronique des acides et des bases.`,
    choiceExplanations: [
      `C'est la définition d'un acide de Lewis.`,
      `C'est la définition d'une base de Lewis.`,
      `La charge ne définit pas à elle seule l'acidité de Lewis.`,
      `Le doublet libre est souvent à l'origine de son caractère donneur.`,
    ],
  },
  {
    order: 12,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du proton du groupe carboxyle :`,
    choices: [
      `Il peut être libéré sous forme $\\mathrm{H^+}$.`,
      `Sa perte forme un ion carboxylate.`,
      `Il est directement lié au carbone carbonylé.`,
      `Sa mobilité est sans lien avec l'acidité.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le proton acide est celui de la liaison $\\mathrm{O{-}H}$, et non un hydrogène porté par le carbone.`,
    choiceExplanations: [
      `C'est le comportement acide du groupe.`,
      `Le produit est $\\mathrm{RCOO^-}$.`,
      `Il est lié à l'oxygène du groupe hydroxyle.`,
      `Cette mobilité explique précisément le caractère acide.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'ion carboxylate $\\mathrm{RCOO^-}$ :`,
    choices: [
      `Présente une charge négative délocalisée sur deux oxygènes.`,
      `Est stabilisé par mésomérie.`,
      `Localise obligatoirement toute la charge sur un seul oxygène réel.`,
      `Est obtenu par protonation de $\\mathrm{RCOOH}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La stabilité de la base conjuguée contribue à l'acidité des acides carboxyliques.`,
    choiceExplanations: [
      `Les deux formes mésomères répartissent la charge.`,
      `La délocalisation abaisse son énergie.`,
      `Les formes limites ne correspondent pas à une localisation permanente.`,
      `Il est obtenu par déprotonation.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les deux liaisons carbone–oxygène d'un carboxylate :`,
    choices: [
      `Sont décrites par deux formes mésomères équivalentes.`,
      `Ont dans l'hybride réel un caractère intermédiaire entre simple et double.`,
      `Correspondent à une liaison triple et une liaison absente.`,
      `Empêchent toute stabilité de l'anion.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Il faut distinguer les formes limites dessinées de l'hybride mésomère réel.`,
    choiceExplanations: [
      `La double liaison peut être dessinée vers l'un ou l'autre oxygène.`,
      `La délocalisation rend les liaisons équivalentes.`,
      `Aucune forme de ce type n'est pertinente.`,
      `Elles le stabilisent au contraire.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pourquoi un acide carboxylique est-il plus acide qu'un alcool dans la hiérarchie du cours ?`,
    choices: [
      `Sa base conjuguée est stabilisée par délocalisation.`,
      `L'alcoolate localise davantage sa charge sur un seul oxygène.`,
      `L'acide carboxylique ne possède aucun oxygène.`,
      `L'alcool libère toujours plus facilement son proton.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La stabilité relative des bases conjuguées permet de comprendre l'ordre d'acidité.`,
    choiceExplanations: [
      `Le carboxylate répartit la charge sur deux oxygènes.`,
      `Il bénéficie de moins de stabilisation mésomère.`,
      `Il en possède deux.`,
      `La hiérarchie donnée est l'inverse.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La hiérarchie indiquée dans la fiche est :`,
    choices: [
      `Acide carboxylique $>$ alcool $>$ hydrogène porté par un carbone voisin d'un carbonyle.`,
      `L'acide carboxylique est le plus acide des trois.`,
      `Le groupe $\\mathrm{CH_2}$ voisin d'un carbonyle est le plus acide.`,
      `Ces trois acidités sont strictement identiques.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La comparaison est qualitative : acidité forte, moyenne puis faible au sein des fonctions étudiées.`,
    choiceExplanations: [
      `C'est l'ordre présenté.`,
      `Son proton est le plus mobile dans cette comparaison.`,
      `Il est placé en dernier.`,
      `Le cours établit une hiérarchie.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'hydrogène d'un alcool :`,
    choices: [
      `Il possède un certain caractère acide.`,
      `Il est moins acide que celui d'un acide carboxylique.`,
      `Il est porté par le carbone dans le groupe $\\mathrm{OH}$.`,
      `Un alcool ne peut jamais subir de déprotonation.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'acidité ne se limite pas aux molécules portant le mot « acide » dans leur nom.`,
    choiceExplanations: [
      `L'alcool peut perdre le proton de $\\mathrm{OH}$, plus difficilement qu'un acide carboxylique.`,
      `C'est l'ordre du cours.`,
      `Il est lié à l'oxygène.`,
      `Elle est possible avec une base suffisamment forte.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le carbone du groupe carboxyle d'un acide non activé est décrit comme peu électrophile parce que :`,
    choices: [
      `Les électrons peuvent être délocalisés entre les deux oxygènes.`,
      `La fonction est stabilisée par mésomérie.`,
      `Le carbone porte une charge négative entière permanente.`,
      `La molécule ne contient pas de liaison $\\mathrm{C{=}O}$.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La faible électrophilie explique la nécessité fréquente d'activer l'acide avant un couplage.`,
    choiceExplanations: [
      `Cette délocalisation diminue la déficience électronique du carbone.`,
      `La conjugaison des oxygènes réduit sa réactivité envers les nucléophiles.`,
      `Ce n'est pas la description du carbone carboxylique neutre.`,
      `Le carbonyle est bien présent.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la réactivité d'un acide carboxylique non activé :`,
    choices: [
      `Il réagit moins facilement avec un nucléophile qu'un chlorure d'acyle.`,
      `Son groupe $\\mathrm{OH}$ est un mauvais groupe partant dans de nombreuses conditions.`,
      `Il est toujours plus électrophile qu'un dérivé activé.`,
      `Il ne peut participer à aucune réaction chimique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'activation améliore à la fois l'électrophilie du carbonyle et l'aptitude du groupe partant.`,
    choiceExplanations: [
      `Le chlorure d'acyle possède un carbonyle plus électrophile.`,
      `Cela limite les substitutions acyles directes.`,
      `L'activation vise précisément à augmenter l'électrophilie.`,
      `Sa réactivité est faible, pas nulle.`,
    ],
  },
  {
    order: 20,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On compare acide acétique, éthanol et hydrogènes du groupe méthyle de l'acétone. D'après la hiérarchie du chapitre :`,
    choices: [
      `Le proton de l'acide acétique est le plus acide.`,
      `Le proton hydroxyle de l'éthanol occupe une position intermédiaire.`,
      `Les hydrogènes alpha de l'acétone sont présentés comme les plus faiblement acides.`,
      `L'ordre est exactement inverse.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La hiérarchie qualitative permet de choisir quelle fonction sera déprotonée en priorité par une base.`,
    choiceExplanations: [
      `Il appartient à un acide carboxylique.`,
      `L'alcool est classé entre acide carboxylique et carbone alpha.`,
      `Ils sont placés en dernier dans la hiérarchie.`,
      `Il contredit la fiche.`,
    ],
  },
  {
    order: 21,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un dérivé d'acide carboxylique est obtenu lorsque :`,
    choices: [
      `Le groupe $\\mathrm{OH}$ de $\\mathrm{RCOOH}$ est remplacé par un autre groupement.`,
      `Le groupe carbonyle est nécessairement supprimé.`,
      `Le squelette carboné doit perdre tous ses carbones.`,
      `La fonction devient obligatoirement un alcane.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Les halogénures d'acyle, anhydrides et esters partagent le motif $\\mathrm{RCO{-}}$.`,
    choiceExplanations: [
      `C'est le principe structural commun.`,
      `Le motif acyle $\\mathrm{RCO{-}}$ est conservé.`,
      `Le radical $\\mathrm{R}$ est conservé.`,
      `Elle reste un dérivé carbonylé.`,
    ],
  },
  {
    order: 22,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formule générale d'un chlorure d'acyle est :`,
    choices: [
      `$\\mathrm{RCOCl}$.`,
      `$\\mathrm{RCl}$.`,
      `$\\mathrm{RCOOH}$.`,
      `$\\mathrm{RNH_2}$.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Le chlorure d'acyle est un dérivé activé particulièrement électrophile.`,
    choiceExplanations: [
      `Le chlore remplace le groupe $\\mathrm{OH}$ de l'acide.`,
      `C'est un dérivé halogéné sans carbonyle.`,
      `C'est l'acide carboxylique de départ.`,
      `C'est une amine.`,
    ],
  },
  {
    order: 23,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un anhydride d'acide possède le motif :`,
    choices: [
      `$\\mathrm{RCO{-}O{-}COR'}$.`,
      `$\\mathrm{R{-}O{-}R'}$.`,
      `$\\mathrm{RCOCl}$.`,
      `$\\mathrm{RCHO}$.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L'anhydride contient deux carbonyles et un oxygène pontant.`,
    choiceExplanations: [
      `Deux groupes acyle sont reliés par un oxygène.`,
      `C'est un éther.`,
      `C'est un chlorure d'acyle.`,
      `C'est un aldéhyde.`,
    ],
  },
  {
    order: 24,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Un ester possède le motif :`,
    choices: [
      `$\\mathrm{RCOOR'}$.`,
      `$\\mathrm{RCOOH}$.`,
      `$\\mathrm{RCONH_2}$.`,
      `$\\mathrm{RCH_2OH}$.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L'ester fait partie des dérivés de l'acide carboxylique étudiés dans les chapitres précédents.`,
    choiceExplanations: [
      `Le groupe $\\mathrm{OR'}$ remplace le $\\mathrm{OH}$ de l'acide.`,
      `C'est un acide carboxylique.`,
      `C'est un amide.`,
      `C'est un alcool primaire.`,
    ],
  },
  {
    order: 25,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'activation d'un acide carboxylique vise notamment à :`,
    choices: [
      `Augmenter le caractère électrophile du carbone carbonylé.`,
      `Améliorer le rendement de réactions de couplage.`,
      `Supprimer définitivement tout atome d'oxygène de la molécule.`,
      `Rendre le carbone carbonylé nucléophile.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les dérivés activés transforment une fonction carboxylique peu réactive en meilleur accepteur de nucléophile.`,
    choiceExplanations: [
      `Le nucléophile peut alors l'attaquer plus facilement.`,
      `La fiche relie l'activation à une liaison plus réactive.`,
      `Le carbonyle reste présent.`,
      `L'effet recherché est une électrophilie accrue.`,
    ],
  },
  {
    order: 26,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans un chlorure d'acyle :`,
    choices: [
      `Le chlore est plus électronégatif que le carbone.`,
      `La liaison acyle–chlore est plus facile à rompre lors d'une substitution que la liaison acide–OH non activée.`,
      `Le carbone carbonylé devient moins électrophile qu'un alcane.`,
      `Aucun nucléophile ne peut réagir.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'effet inductif et la qualité du groupe partant expliquent la grande réactivité des chlorures d'acyle.`,
    choiceExplanations: [
      `Il contribue à polariser la liaison.`,
      `Le chlorure est un meilleur groupe partant dans ce contexte.`,
      `Il devient au contraire très électrophile.`,
      `Ces dérivés réagissent justement facilement avec les nucléophiles.`,
    ],
  },
  {
    order: 27,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les espèces suivantes, lesquelles sont des dérivés d'acide ?`,
    choices: [
      `$\\mathrm{CH_3COCl}$.`,
      `$\\mathrm{CH_3COOCOCH_3}$.`,
      `$\\mathrm{CH_3COOCH_3}$.`,
      `$\\mathrm{CH_3CH_3}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois premières structures conservent le motif acyle $\\mathrm{CH_3CO{-}}$.`,
    choiceExplanations: [
      `C'est le chlorure d'éthanoyle.`,
      `C'est un anhydride d'acide.`,
      `C'est un ester.`,
      `C'est un alcane.`,
    ],
  },
  {
    order: 28,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors d'une réaction de couplage sur un dérivé d'acide activé :`,
    choices: [
      `Un nucléophile attaque généralement le carbone du carbonyle.`,
      `Un groupe partant peut être remplacé.`,
      `Le carbonyle est toujours absent du produit.`,
      `La réaction ne forme jamais de liaison avec un hétéroatome.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L'activation facilite les couplages avec alcools, amines ou autres nucléophiles.`,
    choiceExplanations: [
      `C'est le centre électrophile.`,
      `La réaction est une substitution nucléophile d'acyle.`,
      `Il est souvent conservé dans l'ester ou l'amide formé.`,
      `Les esters et amides créent des liaisons C–O ou C–N.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On souhaite former un amide à partir d'une amine. Le choix d'un acide activé plutôt que de l'acide libre :`,
    choices: [
      `Augmente la probabilité d'une attaque nucléophile de l'amine.`,
      `Évite que la seule réaction dominante soit un simple équilibre acide–base.`,
      `Transforme l'amine en hydrocarbure.`,
      `Supprime le carbone carbonylé du produit.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le cours relie l'activation des acides à la formation efficace d'esters et d'amides.`,
    choiceExplanations: [
      `Le carbonyle activé est plus électrophile.`,
      `L'acide libre peut protoner l'amine sans former efficacement l'amide.`,
      `La fonction azotée est conservée dans l'amide.`,
      `Il devient le carbone de la fonction amide.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Bilan sur l'acide libre et ses dérivés :`,
    choices: [
      `Le carboxylate est stabilisé par délocalisation.`,
      `Un chlorure d'acyle est plus électrophile que l'acide correspondant.`,
      `Un anhydride d'acide contient deux motifs carbonylés.`,
      `Un ester est identique à un alcool.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La structure du substituant lié au groupe acyle détermine fortement la réactivité du dérivé.`,
    choiceExplanations: [
      `Cette stabilité explique en partie l'acidité et la faible électrophilie.`,
      `Il est activé.`,
      `Chaque groupe acyle porte un carbonyle.`,
      `Il contient le motif $\\mathrm{RCOOR'}$, absent d'un alcool simple.`,
    ],
  },
];
