/**
 * Cartographie éditoriale V2 — auteur.
 * Les stages décrivent la progression pédagogique, jamais un chronométrage.
 */

export const UE14_BIOCH_CH5_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-eicosanoides-arachidonique",
    "title": "Eicosanoïdes et acide arachidonique",
    "description": "Définitions, familles, acide arachidonique et grandes voies de synthèse.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-voies-cox-lipoxygenases",
    "title": "Voies COX et lipoxygénases",
    "description": "Applications sur le précurseur 20:4 n-6 et l’orientation vers prostanoïdes, leucotriènes ou lipoxines.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-prostanoides-structure-series",
    "title": "Structure et séries des prostanoïdes",
    "description": "Repères sur squelette prostanoïde, groupes de prostaglandines et séries 1, 2 et 3.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-nomenclature-prostaglandines",
    "title": "Nomenclature des prostaglandines",
    "description": "Applications sur lettres de groupe, indices de série, prostacyclines et lecture structurale.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-prostanoides-effets",
    "title": "Effets biologiques des prostanoïdes",
    "description": "Repères sur médiateurs locaux, misoprostol, TXA₂, PGI₂ et inhibition de COX.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-equilibre-vasculaire-therapeutique",
    "title": "Équilibre vasculaire et thérapeutique",
    "description": "Applications sur plaquettes, endothélium, demi-vies, aspirine et déclenchement de l’accouchement.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 3,
    "order": 3,
    "slug": "section-c-master-prostanoides-clinique",
    "title": "Prostanoïdes : intégration biologique et thérapeutique",
    "description": "Maîtrise de l’antagonisme TXA₂/PGI₂, de COX et des exemples thérapeutiques du support.",
    "stage": "MASTER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76,
      77,
      78
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-leucotrienes-lipoxines",
    "title": "Leucotriènes et lipoxines",
    "description": "Repères sur structure triénique, cellules productrices, LTA₄ et branches de synthèse.",
    "stage": "DISCOVER",
    "questionOrders": [
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-lta4-glutathion-effets",
    "title": "Voies et effets des leucotriènes",
    "description": "Applications sur bronchoconstriction, chimiotactisme, 5-lipoxygénase, LTA₄ et glutathion.",
    "stage": "PRACTICE",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-eicosanoides",
    "title": "Les eicosanoïdes",
    "description": "Synthèse appliquée des voies, prostanoïdes, leucotriènes et exemples thérapeutiques.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-eicosanoides",
    "title": "Les eicosanoïdes",
    "description": "Maîtrise transversale du chapitre dans l’esprit de l’examen, sans constituer un examen blanc.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH5_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Eicosanoïdes et acide arachidonique : repères"],
  2: ["Eicosanoïdes et acide arachidonique : repères"],
  3: ["Eicosanoïdes et acide arachidonique : repères"],
  4: ["Eicosanoïdes et acide arachidonique : repères"],
  5: ["Eicosanoïdes et acide arachidonique : repères"],
  6: ["Eicosanoïdes et acide arachidonique : repères"],
  7: ["Eicosanoïdes et acide arachidonique : repères"],
  8: ["Eicosanoïdes et acide arachidonique : repères"],
  9: ["Eicosanoïdes et acide arachidonique : repères"],
  10: ["Eicosanoïdes et acide arachidonique : repères"],
  11: ["Voies COX/lipoxygénases : applications"],
  12: ["Voies COX/lipoxygénases : applications"],
  13: ["Voies COX/lipoxygénases : applications"],
  14: ["Voies COX/lipoxygénases : applications"],
  15: ["Voies COX/lipoxygénases : applications"],
  16: ["Voies COX/lipoxygénases : applications"],
  17: ["Voies COX/lipoxygénases : applications"],
  18: ["Voies COX/lipoxygénases : applications"],
  19: ["Voies COX/lipoxygénases : applications"],
  20: ["COX et pharmacologie : raisonnement de voie"],
  21: ["Voies COX/lipoxygénases : applications"],
  22: ["Voies COX/lipoxygénases : applications"],
  23: ["Prostanoïdes : structure et séries"],
  24: ["Prostanoïdes : structure et séries"],
  25: ["Prostanoïdes : structure et séries"],
  26: ["Prostanoïdes : structure et séries"],
  27: ["Prostanoïdes : structure et séries"],
  28: ["Prostanoïdes : structure et séries"],
  29: ["Prostanoïdes : structure et séries"],
  30: ["Prostanoïdes : structure et séries"],
  31: ["PGI : lettre I et prostacyclines"],
  32: ["Prostanoïdes : structure et séries"],
  33: ["Nomenclature des prostaglandines : applications"],
  34: ["Nomenclature des prostaglandines : applications"],
  35: ["Nomenclature des prostaglandines : applications"],
  36: ["Nomenclature des prostaglandines : applications"],
  37: ["Nomenclature des prostaglandines : applications"],
  38: ["Nomenclature des prostaglandines : applications"],
  39: ["Nomenclature des prostaglandines : applications"],
  40: ["Nomenclature des prostaglandines : applications"],
  41: ["Nomenclature des prostaglandines : applications"],
  42: ["Nomenclature des prostaglandines : applications"],
  43: ["Nomenclature des prostaglandines : applications"],
  44: ["Nomenclature des prostaglandines : applications"],
  45: ["Prostanoïdes : effets biologiques"],
  46: ["Prostanoïdes : effets biologiques"],
  47: ["Prostanoïdes : effets biologiques"],
  48: ["Misoprostol et déclenchement de l’accouchement"],
  49: ["TXA₂ : plaquettes"],
  50: ["PGI₂ : endothélium"],
  51: ["Prostanoïdes : effets biologiques"],
  52: ["Prostanoïdes : effets biologiques"],
  53: ["Prostanoïdes : effets biologiques"],
  54: ["Prostanoïdes : effets biologiques"],
  55: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  56: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  57: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  58: ["Aspirine faible dose : antiagrégation"],
  59: ["Misoprostol : contexte obstétrical"],
  60: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  61: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  62: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  63: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  64: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  65: ["QZONE : endothélium source de PGI₂"],
  66: ["Équilibre TXA₂/PGI₂ et thérapeutique"],
  67: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  68: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  69: ["Misoprostol : intégration thérapeutique"],
  70: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  71: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  72: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  73: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  74: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  75: ["Aspirine : COX et thromboxanes"],
  76: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  77: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  78: ["Prostanoïdes : maîtrise biologique et thérapeutique"],
  79: ["Leucotriènes et lipoxines : repères"],
  80: ["Leucotriènes et lipoxines : repères"],
  81: ["Leucotriènes : bronchoconstriction"],
  82: ["Leucotriènes : immunité et chimiotactisme"],
  83: ["Leucotriènes et lipoxines : repères"],
  84: ["Leucotriènes et lipoxines : repères"],
  85: ["Leucotriènes et lipoxines : repères"],
  86: ["Leucotriènes et lipoxines : repères"],
  87: ["Leucotriènes et lipoxines : repères"],
  88: ["Leucotriènes et lipoxines : repères"],
  89: ["Leucotriènes : contexte respiratoire"],
  90: ["Leucotriènes : voies et effets"],
  91: ["Leucotriènes : voies et effets"],
  92: ["Leucotriènes : voies et effets"],
  93: ["Leucotriènes : voies et effets"],
  94: ["Leucotriènes : voies et effets"],
  95: ["Leucotriènes : voies et effets"],
  96: ["Leucotriènes : voies et effets"],
  97: ["Leucotriènes : voies et effets"],
  98: ["Leucotriènes : voies et effets"],
  99: ["Leucotriènes : voies et effets"],
  100: ["Leucotriènes : voies et effets"],
  101: ["Synthèse eicosanoïdes"],
  102: ["Synthèse eicosanoïdes"],
  103: ["Synthèse eicosanoïdes"],
  104: ["Synthèse eicosanoïdes"],
  105: ["Synthèse eicosanoïdes"],
  106: ["Synthèse eicosanoïdes"],
  107: ["Synthèse eicosanoïdes"],
  108: ["Synthèse eicosanoïdes"],
  109: ["Synthèse eicosanoïdes"],
  110: ["Synthèse eicosanoïdes"],
  111: ["Maîtrise transversale eicosanoïdes"],
  112: ["Maîtrise transversale eicosanoïdes"],
  113: ["Misoprostol : contexte clinique du support"],
  114: ["Maîtrise transversale eicosanoïdes"],
  115: ["Maîtrise transversale eicosanoïdes"],
  116: ["Maîtrise transversale eicosanoïdes"],
  117: ["Maîtrise transversale eicosanoïdes"],
  118: ["Maîtrise transversale eicosanoïdes"],
  119: ["Maîtrise transversale eicosanoïdes"],
  120: ["Maîtrise transversale eicosanoïdes"],
  121: ["Applications thérapeutiques et physiopathologiques"],
  122: ["Maîtrise transversale eicosanoïdes"],
};
