/** UE14 – Biologie cellulaire – Chapitre 2 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le chapitre distingue comme grands types de transport membranaire :` ,
    choices: [
      `Les mouvements microscopiques de membrane.`,
      `Le passage de solutés à travers la membrane.`,
      `La seule diffusion des gaz.`,
      `Les échanges de solutés.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le cours oppose mouvements de membrane et passage de molécules.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la bicouche pure :` ,
    choices: [
      `O2 et CO2 la traversent librement.`,
      `Les ions ne diffusent pas librement.`,
      `La plupart des métabolites ont besoin de protéines transmembranaires.`,
      `Toutes les molécules hydrophiles passent plus facilement que les gaz.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les gaz diffusent plus facilement que les solutés hydrophiles.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les protéines de transport peuvent être :` ,
    choices: [
      `Des canaux.`,
      `Des perméases.`,
      `Des pompes.`,
      `Uniquement des glycoprotéines du glycocalyx.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les protéines de transport ne se réduisent pas au glycocalyx.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le transport passif correspond :` ,
    choices: [
      `À une diffusion simple.`,
      `À un passage via canal ou perméase selon le gradient.`,
      `À un passage contre le gradient nécessitant l’ATP.`,
      `À un déplacement spontané selon le gradient.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le transport passif se fait dans le sens du gradient.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Les aquaporines sont :` ,
    choices: [
      `Des canaux hydriques.`,
      `Des récepteurs tyrosine kinase.`,
      `Des hormones pancréatiques.`,
      `Des protéines de MEC.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Les aquaporines assurent le passage rapide et spécifique de l’eau.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le transport actif :` ,
    choices: [
      `Nécessite de l’énergie.`,
      `Peut se faire contre le gradient.`,
      `Implique une pompe ou un transporteur.`,
      `Est identique à une diffusion simple.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le transport actif s’oppose à la diffusion simple.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les transporteurs ABC :` ,
    choices: [
      `Utilisent l’hydrolyse de l’ATP.`,
      `Peuvent importer ou exporter de façon unidirectionnelle.`,
      `Peuvent participer à la chimiorésistance.`,
      `Correspondent à des mouvements de rotation des phospholipides.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ce sont des transporteurs actifs, pas des mouvements de lipides.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le transport actif secondaire :` ,
    choices: [
      `Peut coupler deux solutés.`,
      `Peut se faire en symport ou en antiport.`,
      `Utilise l’énergie du gradient d’un autre soluté.`,
      `Ne nécessite jamais de gradient préalable.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Il dépend au contraire d’un gradient préexistant.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du transport intestinal du glucose :` ,
    choices: [
      `Le glucose de la lumière doit rejoindre le sang.`,
      `Les pôles apical et baso-latéral n’ont pas le même rôle.`,
      `Le modèle illustre la polarité de l’entérocyte.`,
      `Le glucose diffuse librement partout sans transporteur.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le transport du glucose nécessite des systèmes spécialisés.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Au pôle apical de l’entérocyte, l’entrée du glucose est assurée par :` ,
    choices: [
      `Un symport sodium/glucose.`,
      `L’entrée d’un glucose et de deux Na+.`,
      `Un transport actif secondaire.`,
      `Une diffusion simple du glucose seul.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le glucose ne diffuse pas librement à travers la bicouche apicale.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’énergie qui permet l’entrée apicale du glucose provient :` ,
    choices: [
      `Du gradient de sodium.`,
      `D’une forte concentration extracellulaire en sodium.`,
      `Du maintien de ce gradient par la pompe Na+/K+.`,
      `D’une synthèse de glucose dans la lumière.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le symport exploite le gradient sodé entretenu par la pompe Na+/K+.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Au pôle baso-latéral de l’entérocyte :` ,
    choices: [
      `GLUT1 assure la sortie du glucose.`,
      `Le mécanisme est un transport passif facilité.`,
      `Le transporteur change de conformation.`,
      `Le glucose sort grâce à une pompe ATP-dépendante spécifique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `GLUT1 est une perméase, pas une pompe.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les jonctions serrées sont importantes pour le transport du glucose car :` ,
    choices: [
      `Elles séparent les domaines membranaires.`,
      `Elles maintiennent la polarité.`,
      `Elles permettent une répartition différente des transporteurs.`,
      `Elles remplacent les transporteurs.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Elles organisent la polarité mais ne transportent pas le glucose.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans la cellule musculaire au repos :` ,
    choices: [
      `Il existe un récepteur à l’insuline.`,
      `La membrane possède de la GLUT1.`,
      `Des vésicules contiennent d’autres perméases.`,
      `L’entrée de glucose est totalement impossible.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une entrée basale de glucose reste possible au repos.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quand l’insuline se fixe sur son récepteur dans la cellule musculaire :` ,
    choices: [
      `Des vésicules fusionnent avec la membrane.`,
      `Des transporteurs supplémentaires sont insérés.`,
      `GLUT1 et GLUT4 favorisent alors une entrée accrue du glucose.`,
      `Le glucose est expulsé hors de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’insuline augmente l’entrée cellulaire du glucose.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure :

![Glucose](/images/training/ue14/biologie-cellulaire/membrane-plasmique/transport-glucose-enterocyte.png)

Quelles propositions sont correctes ?` ,
    choices: [
      `Le pôle apical fait face à la lumière intestinale.`,
      `Le symport Na+/glucose est apical.`,
      `GLUT1 est baso-latérale.`,
      `La pompe Na+/K+ est un canal passif à eau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La pompe Na+/K+ est un transporteur actif, non un canal à eau.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Toujours à partir du schéma du glucose :` ,
    choices: [
      `Le symport fait entrer sodium et glucose.`,
      `GLUT1 facilite la sortie vers le sang.`,
      `La pompe Na+/K+ contribue indirectement au transport apical.`,
      `Les jonctions serrées n’ont aucun lien avec la polarité.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polarité dépend notamment des jonctions serrées.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 108,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le transport du glucose peut être :` ,
    choices: [
      `Contre son gradient lors de l’entrée apicale.`,
      `Selon son gradient lors de la sortie baso-latérale.`,
      `Toujours passif quel que soit le contexte.`,
      `Dépendant de transporteurs distincts.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le cours montre qu’il peut être selon ou contre le gradient.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 109,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos du symport et de l’antiport :` ,
    choices: [
      `Le symport transporte deux solutés dans le même sens.`,
      `L’antiport transporte deux solutés en sens opposés.`,
      `Ils sont des modalités du transport actif secondaire.`,
      `Un antiport est obligatoirement une diffusion simple.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Un antiport n’est pas assimilable à une diffusion simple.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 110,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le rôle des protéines transmembranaires dans les échanges est important car :` ,
    choices: [
      `La bicouche pure est peu perméable à beaucoup de molécules hydrophiles.`,
      `Les ions diffusent mal dans le cœur hydrophobe.`,
      `Ces protéines peuvent former canaux, perméases ou pompes.`,
      `Sans elles, seuls les phospholipides pourraient traverser la membrane comme solutés.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane requiert des protéines spécialisées pour les échanges sélectifs.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’endocytose et l’exocytose sont :` ,
    choices: [
      `Des mouvements microscopiques de membrane.`,
      `Une autre catégorie que le simple passage de solutés.`,
      `Distinctes des canaux et perméases.`,
      `Des exemples de diffusion simple du CO2.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ce sont des mouvements de membrane, pas une diffusion des gaz.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule tumorale surexprime un transporteur MDR de type ABC :` ,
    choices: [
      `L’efflux de certains médicaments peut augmenter.`,
      `La chimiorésistance peut être favorisée.`,
      `Le transport utilise l’ATP.`,
      `La cellule devient incapable de transporter quoi que ce soit.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’efflux médicamenteux par les ABC peut contribuer à la résistance tumorale.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si la pompe Na+/K+ ne maintient plus correctement le gradient sodé dans l’entérocyte :` ,
    choices: [
      `Le symport Na+/glucose devient moins efficace.`,
      `L’entrée apicale du glucose contre son gradient est perturbée.`,
      `L’énergie disponible pour ce transport actif secondaire diminue.`,
      `Le glucose se met à diffuser librement à travers la bicouche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le glucose ne se met pas à diffuser librement pour autant.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une cellule musculaire stimulée par l’insuline :` ,
    choices: [
      `La membrane reçoit davantage de perméases.`,
      `La présence de GLUT4 augmente à la membrane.`,
      `L’entrée de glucose peut devenir bien plus importante.`,
      `Le récepteur à l’insuline disparaît aussitôt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’effet principal est l’insertion de transporteurs facilitant l’entrée du glucose.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le transport passif facilité par GLUT1 :` ,
    choices: [
      `Nécessite une reconnaissance spécifique du glucose.`,
      `Implique un changement de conformation du transporteur.`,
      `Permet un passage selon le gradient.`,
      `Consomme directement une molécule d’ATP à chaque passage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `GLUT1 n’est pas une pompe ATP-dépendante.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le trajet du glucose de la lumière intestinale au sang implique successivement :` ,
    choices: [
      `Une entrée apicale couplée au sodium.`,
      `Une diffusion intracellulaire.`,
      `Une sortie via GLUT1.`,
      `Une traversée directe des jonctions serrées.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le trajet décrit dans le cours est transcellulaire.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une molécule très hydrophile et chargée négativement aura tendance à :` ,
    choices: [
      `Traverser difficilement une bicouche pure.`,
      `Avoir souvent besoin d’un transporteur.`,
      `Être défavorisée par le cœur hydrophobe.`,
      `Diffuser plus librement que l’oxygène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’oxygène diffuse bien plus facilement dans la bicouche.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une synthèse correcte du transport membranaire est :` ,
    choices: [
      `Certaines molécules diffusent librement, d’autres non.`,
      `Le transport actif secondaire utilise le gradient d’un ion.`,
      `Le transport du glucose illustre l’importance de la polarité.`,
      `La membrane n’intervient ni dans les échanges ni dans la signalisation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane est centrale dans les échanges comme dans la communication.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une fois dans le sang, le glucose peut entrer dans une cellule musculaire :` ,
    choices: [
      `En partie grâce à la GLUT1 déjà présente.`,
      `De façon accrue après stimulation insulinique.`,
      `Après insertion supplémentaire de transporteurs.`,
      `Seulement s’il traverse d’abord une jonction serrée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cellule musculaire augmente ses transporteurs sous l’effet de l’insuline.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Conclusion de la section transport :` ,
    choices: [
      `Les transports combinent diffusion, transporteurs passifs, pompes et systèmes couplés.`,
      `Le glucose peut être transporté selon ou contre son gradient selon le transporteur.`,
      `La membrane est à la fois support de signalisation et de transport.`,
      `Le glucose traverse toujours les membranes comme le CO2.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le glucose ne diffuse pas comme le CO2.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: `principes-du-transport-membranaire`,
    title: `Principes du transport membranaire`,
    description: `Diffusion, canaux, pompes et transport actif secondaire.`,
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 11,
    slug: `transport-du-glucose-dans-l-enterocyte`,
    title: `Transport du glucose dans l’entérocyte`,
    description: `Symport apical, GLUT1 et gradient de sodium.`,
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 12,
    slug: `transport-du-glucose-et-regulation-cellulaire`,
    title: `Transport du glucose et régulation cellulaire`,
    description: `Cellule musculaire, transporteurs ABC et synthèse des transports.`,
    stage: 'MASTER',
    sectionOrder: 4,
    questionOrders: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
];
