/**
 * UE14 – Biologie cellulaire – Chapitre 1
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SYNTHESIS_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une cellule épithéliale intestinale est étudiée en culture. À propos des éléments généraux du chapitre :`,
    choices: [
      `Elle est limitée par une membrane plasmique.`,
      `Son cytosquelette peut participer à sa forme.`,
      `Ses microvillosités apicales peuvent favoriser l'absorption.`,
      `Elle est obligatoirement dépourvue de cytoplasme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette question relie organisation générale et spécialisation : l'entérocyte conserve les structures communes tout en présentant des microvillosités fonctionnelles.`,
    choiceExplanations: [
      `Toute cellule est délimitée par une membrane.`,
      `Ce rôle est attribué au cytosquelette.`,
      `C'est la spécialisation de l'entérocyte.`,
      `Le cytoplasme est un compartiment fondamental de la cellule.`,
    ],
  },
  {
    order: 122,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la composition chimique simplifiée d'une cellule :`,
    choices: [
      `L'eau constitue la fraction majoritaire.`,
      `Les protéines représentent environ 15 %.`,
      `Le carbone, l'hydrogène, l'oxygène et l'azote sont les quatre éléments principaux cités.`,
      `L'ADN représente environ 70 %.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les valeurs du cours sont des repères : 70 % d'eau, puis une fraction macromoléculaire où les protéines occupent une place importante.`,
    choiceExplanations: [
      `Elle représente environ 70 % dans la fiche.`,
      `C'est la valeur indicative donnée.`,
      `Le quatuor CHON est présenté.`,
      `L'ADN est indiqué autour de 1 %.`,
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un laboratoire établit une culture primaire à partir d'un tissu chirurgical :`,
    choices: [
      `Une dissociation enzymatique peut être utilisée.`,
      `Les cellules peuvent être placées sur un support adapté.`,
      `L'incubation peut se faire à 37 °C avec 5 % de CO2.`,
      `La culture est dite secondaire avant même le premier passage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'établissement d'une culture primaire associe isolement, mise en milieu adapté, support éventuel et incubation contrôlée.`,
    choiceExplanations: [
      `Les enzymes protéolytiques sont citées.`,
      `Certaines cellules adhérentes nécessitent un support.`,
      `Ce sont les conditions de référence.`,
      `Elle reste primaire jusqu'au premier passage.`,
    ],
  },
  {
    order: 124,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une culture primaire devient confluente :`,
    choices: [
      `Les cellules se touchent.`,
      `Un traitement enzymatique peut les décoller.`,
      `Le repiquage dans une nouvelle boîte produit une culture secondaire.`,
      `La fixation est indispensable avant de poursuivre leur prolifération.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le passage cellulaire est une opération sur cellules vivantes : décollement, transfert et reprise de prolifération.`,
    choiceExplanations: [
      `C'est le critère de confluence.`,
      `La fiche le prévoit pour le passage.`,
      `C'est la conséquence du premier passage.`,
      `La fixation empêcherait la poursuite de la culture.`,
    ],
  },
  {
    order: 125,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparer explant, 2D et 3D :`,
    choices: [
      `L'explant conserve un fragment de tissu.`,
      `La 2D organise des cellules dissociées en monocouche.`,
      `La 3D peut former des sphéroïdes.`,
      `Ces trois modèles imposent exactement la même architecture cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les modèles se distinguent par le niveau d'organisation spatiale et le degré de conservation de l'architecture tissulaire.`,
    choiceExplanations: [
      `Il est déposé directement dans la boîte.`,
      `C'est le modèle plan.`,
      `C'est l'exemple donné.`,
      `Ils diffèrent précisément par l'organisation conservée ou reconstruite.`,
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour choisir une méthode de localisation moléculaire :`,
    choices: [
      `La nature de la cible, protéine ou acide nucléique, doit être prise en compte.`,
      `La nécessité de suivre une cellule vivante doit être prise en compte.`,
      `Le type de marqueur détermine le microscope adapté.`,
      `Toutes les méthodes sont interchangeables sans adaptation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La stratégie expérimentale dépend de la cible, de l'état cellulaire et du système de détection.`,
    choiceExplanations: [
      `Elle oriente vers anticorps ou sonde nucléotidique.`,
      `Toutes les méthodes ne sont pas compatibles.`,
      `Fluorochrome, or ou colorimétrie n'ont pas la même détection.`,
      `Elles reposent sur des principes distincts.`,
    ],
  },
  {
    order: 127,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors d'un immunomarquage d'une protéine cytoplasmique :`,
    choices: [
      `La cellule est fixée.`,
      `La membrane est partiellement perméabilisée.`,
      `Les anticorps en excès sont éliminés par lavage.`,
      `L'antigène est remplacé par une séquence d'ADN complémentaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les étapes clés sont fixation, perméabilisation, incubation avec l'anticorps, lavage et observation du marqueur.`,
    choiceExplanations: [
      `La méthode du cours est réalisée sur cellules fixées.`,
      `Cela permet l'entrée des anticorps.`,
      `Le lavage réduit le bruit de fond.`,
      `Cela décrirait une hybridation, non un immunomarquage.`,
    ],
  },
  {
    order: 128,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour suivre une protéine au cours du temps dans une cellule vivante :`,
    choices: [
      `Une construction GFP peut être introduite par transfection.`,
      `Une électroporation peut servir à introduire la construction.`,
      `Une protéine purifiée marquée peut être micro-injectée.`,
      `Une fixation préalable est indispensable pour conserver le mouvement cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les stratégies vivantes reposent soit sur l'expression d'un tag fluorescent, soit sur l'introduction directe d'une protéine marquée.`,
    choiceExplanations: [
      `La cellule exprime alors une protéine chimérique fluorescente.`,
      `C'est une autre méthode donnée.`,
      `Cette stratégie est également compatible avec une cellule vivante.`,
      `La fixation supprime la dynamique vivante.`,
    ],
  },
  {
    order: 129,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les applications médicales ou biologiques du chapitre :`,
    choices: [
      `Observer les battements ciliaires dans une suspicion de dyskinésie.`,
      `Tester une drogue sur un fragment de vaisseau.`,
      `Localiser un ARN d'intérêt par hybridation in situ.`,
      `Affirmer que la culture cellulaire ne peut jamais être utilisée en santé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chapitre relie les techniques fondamentales à des questions cliniques, pharmacologiques et diagnostiques.`,
    choiceExplanations: [
      `L'explant nasal est cité.`,
      `L'explant vasculaire est cité.`,
      `La méthode peut cibler l'ARN.`,
      `Le cours insiste au contraire sur son utilité.`,
    ],
  },
  {
    order: 130,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'organisation et de l'étude des cellules :`,
    choices: [
      `Une cellule peut être étudiée en culture hors de l'organisme.`,
      `Un marquage peut localiser une molécule dans la cellule.`,
      `Le modèle expérimental doit être choisi en fonction de la question posée.`,
      `Tous les items précédents sont faux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La qualité d'une étude repose sur l'adéquation entre le modèle cellulaire et la méthode de détection.`,
    choiceExplanations: [
      `C'est la définition de l'approche in vitro.`,
      `C'est la finalité commune des méthodes.`,
      `Le choix entre explant, 2D, 3D et marquages dépend de l'objectif.`,
      `Les trois premiers sont vrais.`,
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Des cellules respiratoires dissociées sont d'abord cultivées à plat, puis transférées sur insert à l'interface air-liquide. On observe ensuite un épithélium différencié. À propos de ce protocole :`,
    choices: [
      `La première étape correspond à une culture 2D.`,
      `L'interface air-liquide favorise une polarité apico-basale.`,
      `La différenciation observée est cohérente avec le modèle présenté dans le cours.`,
      `La face basale est nécessairement privée de tout nutriment.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le protocole illustre le passage d'un modèle simple de prolifération à un modèle spécialisé de différenciation épithéliale.`,
    choiceExplanations: [
      `Les cellules sont initialement en monocouche.`,
      `La face apicale est exposée à l'air et la face basale au milieu.`,
      `C'est le résultat attendu.`,
      `Elle reste en contact avec le milieu.`,
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Deux cultures subissent des passages successifs. La culture A cesse de se diviser après quelques semaines ; la culture B continue indéfiniment dans les conditions de laboratoire. On peut proposer que :`,
    choices: [
      `A correspond à des cellules normales de durée de vie limitée.`,
      `B correspond à une lignée immortelle.`,
      `B peut provenir d'un tissu tumoral ou d'une transformation oncogénique.`,
      `Le nombre de passages n'a aucun intérêt pour distinguer ces comportements.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le potentiel prolifératif à long terme permet de distinguer culture normale et lignée immortelle.`,
    choiceExplanations: [
      `Ce devenir est décrit pour les cultures normales.`,
      `La prolifération illimitée définit une lignée.`,
      `Les deux origines sont mentionnées.`,
      `Le devenir au fil des passages est précisément discriminant.`,
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans le même échantillon fixé, une équipe souhaite localiser une protéine membranaire et l'ARN correspondant :`,
    choices: [
      `Un anticorps spécifique peut localiser la protéine.`,
      `Une sonde complémentaire peut localiser l'ARN.`,
      `Les deux méthodes nécessitent une détection adaptée à leurs marqueurs.`,
      `L'ARN est localisé grâce au fragment Fc de l'anticorps sans sonde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La combinaison de méthodes permet une information complémentaire sur l'expression d'un gène et la localisation de son produit protéique.`,
    choiceExplanations: [
      `L'immunomarquage cible la protéine.`,
      `L'hybridation in situ cible la séquence.`,
      `Le choix du fluorochrome ou du marqueur colorimétrique est important.`,
      `Le fragment Fc n'apporte pas de complémentarité nucléotidique.`,
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Après immunomarquage à l'Alexa 488, un signal vert diffus persiste dans toute la préparation. Une cause technique possible est :`,
    choices: [
      `Un lavage insuffisant des anticorps non liés.`,
      `Une quantité importante de marqueur libre ou non spécifiquement retenu.`,
      `Une difficulté à distinguer la cible du fond.`,
      `La certitude que toutes les molécules cellulaires portent l'épitope recherché.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'interprétation d'une image dépend de contrôles et de lavages permettant de séparer signal spécifique et bruit de fond.`,
    choiceExplanations: [
      `Cela laisse un bruit de fond fluorescent.`,
      `Elle augmente le signal diffus.`,
      `C'est la conséquence attendue.`,
      `Un signal diffus peut être artefactuel.`,
    ],
  },
  {
    order: 135,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine est marquée soit par Alexa 488, soit par des billes d'or colloïdal :`,
    choices: [
      `Alexa 488 est adapté à la microscopie optique à fluorescence.`,
      `L'or colloïdal est adapté à la MET.`,
      `Les deux marqueurs peuvent fournir une information de localisation.`,
      `Le choix du microscope est indépendant de la nature du marqueur.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le même objectif de localisation peut être atteint à différentes échelles en choisissant un marqueur et un microscope cohérents.`,
    choiceExplanations: [
      `Il émet un signal fluorescent vert.`,
      `Les billes d'or sont denses aux électrons.`,
      `Ils rendent visible la position de la cible.`,
      `Le système de détection doit être compatible.`,
    ],
  },
  {
    order: 136,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une construction code une protéine P fusionnée à la GFP. Après transfection, la fluorescence change de compartiment au cours du temps :`,
    choices: [
      `La cellule a synthétisé une protéine chimérique.`,
      `Le suivi temporel est possible sur cellule vivante.`,
      `La transfection a introduit l'ADN recombinant via un dispositif de type liposome selon la fiche.`,
      `L'expérience impose un immunomarquage préalable sur cellule fixée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le tag GFP transforme la protéine en traceur fluorescent produit par la cellule, particulièrement utile pour suivre sa dynamique.`,
    choiceExplanations: [
      `La construction associe P et GFP.`,
      `C'est l'intérêt de la stratégie.`,
      `C'est la méthode décrite.`,
      `La GFP permet une observation directe de la protéine exprimée.`,
    ],
  },
  {
    order: 137,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une équipe hésite entre un explant et un sphéroïde 3D :`,
    choices: [
      `L'explant conserve directement un fragment du tissu d'origine.`,
      `Le sphéroïde est reconstruit à partir de cellules dissociées.`,
      `Les deux modèles peuvent fournir des interactions cellule-cellule.`,
      `Ils sont strictement identiques quant à leur origine et leur architecture.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le choix dépend de l'intérêt à préserver l'architecture native ou à construire un modèle 3D contrôlé.`,
    choiceExplanations: [
      `C'est sa caractéristique.`,
      `Il résulte d'une réorganisation en 3D.`,
      `L'explant les conserve, le sphéroïde les recrée.`,
      `Leur préparation et leur organisation diffèrent.`,
    ],
  },
  {
    order: 138,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une culture atteint la confluence. L'équipe veut d'abord poursuivre la culture, puis fixer un échantillon pour un immunomarquage :`,
    choices: [
      `Elle peut réaliser un passage pour poursuivre la culture.`,
      `Elle peut fixer seulement l'échantillon destiné à l'immunomarquage.`,
      `La fixation immobilise les molécules au temps choisi.`,
      `Toutes les cellules doivent être fixées avant le passage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le protocole distingue une branche vivante destinée à la poursuite de la culture et une branche fixée destinée à l'analyse.`,
    choiceExplanations: [
      `Le passage évite le surpeuplement.`,
      `Les autres cellules doivent rester vivantes pour être repiquées.`,
      `Elle fige l'état de l'échantillon.`,
      `Des cellules fixées ne peuvent plus être cultivées.`,
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les deux figures suivantes présentent, d’une part, le déroulement des passages cellulaires et le devenir des cellules normales ou tumorales et, d’autre part, différents modèles de culture cellulaire.

![Culture cellulaire : de la culture primaire à la lignée cellulaire](/images/training/ue14/biologie-cellulaire/organisation-methodes-etude-cellule/culture-primaire-lignee-cellulaire.png)

![Comparaison des modèles de culture cellulaire](/images/training/ue14/biologie-cellulaire/organisation-methodes-etude-cellule/modeles-culture-cellulaire.png)

En croisant les informations apportées par ces deux figures, quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Le schéma des passages illustre le devenir différent des cellules normales et tumorales.`,
      `La comparaison des modèles distingue notamment explant, monocouche 2D, sphéroïde 3D et interface air-liquide.`,
      `Les deux figures mettent en évidence que le choix du modèle dépend de l'objectif expérimental.`,
      `Les deux figures montrent que toutes les cultures ont une organisation et un devenir identiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les figures complètent le cours en représentant la dynamique des passages et la diversité des modèles de culture.`,
    choiceExplanations: [
      `La première figure oppose la sénescence des cellules normales à l'immortalité des lignées tumorales.`,
      `La seconde figure compare quatre organisations expérimentales distinctes.`,
      `Passages, architecture et différenciation orientent le choix du modèle.`,
      `Les figures soulignent au contraire la diversité des cultures et de leurs devenirs.`,
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos du chapitre « Organisation et méthodes d'étude de la cellule » :`,
    choices: [
      `Il relie structures cellulaires, fonctions et spécialisations.`,
      `Il présente plusieurs modèles de culture permettant d'étudier la vie cellulaire.`,
      `Il distingue plusieurs stratégies de localisation moléculaire.`,
      `Tous les items précédents sont faux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chapitre articule trois niveaux : comprendre l'organisation cellulaire, construire un modèle expérimental et choisir une méthode de localisation adaptée.`,
    choiceExplanations: [
      `C'est le contenu de la première partie.`,
      `C'est le contenu de la seconde partie.`,
      `C'est le contenu de la troisième partie.`,
      `Les trois premiers résument correctement le chapitre.`,
    ],
  },
];

export const SYNTHESIS_QUIZZES: SeedQuiz[] = [
  {
    order: 13,
    slug: `organisation-methodes-etude-cellule`,
    title: `Organisation et méthodes d'étude de la cellule`,
    description: `Révision transversale des structures, de la culture cellulaire et des marquages moléculaires.`,
    stage: 'PRACTICE',
    sectionOrder: 5,
    questionOrders: [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
  },
  {
    order: 14,
    slug: `synthese-experimentale-organisation-methodes-etude-cellule`,
    title: `Synthèse expérimentale du chapitre`,
    description: `Situations intégratives proches de l'examen : choix du modèle, interprétation de protocole et contrôles.`,
    stage: 'MASTER',
    sectionOrder: 5,
    items: [
      {
        type: 'GROUP',
        title: `Modèles de culture et différenciation`,
        sharedStatement: `Une équipe compare plusieurs modèles de culture afin d'étudier la prolifération, la différenciation et la durée de vie de cellules humaines.`,
        questionOrders: [131, 132],
      },
      {
        type: 'GROUP',
        title: `Localisation moléculaire`,
        sharedStatement: `Une seconde équipe cherche à localiser des ARN et des protéines dans des cellules fixées ou vivantes.`,
        questionOrders: [133, 134, 135, 136],
      },
      { type: 'QUESTION', questionOrder: 137 },
      { type: 'QUESTION', questionOrder: 138 },
      { type: 'QUESTION', questionOrder: 139 },
      { type: 'QUESTION', questionOrder: 140 },
    ],
  },
];
