import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_ORDER = 3;

export const SECTION_C_AMINES_ALKYLATION_DISCOVERY_QUIZ_SLUG =
  `section-c-discovery-amines-classes-alkylation`;
export const SECTION_C_AMIDIFICATION_PRACTICE_QUIZ_SLUG =
  `section-c-practice-amidification-amines`;
export const SECTION_C_IMINES_IMINIUM_MASTER_QUIZ_SLUG =
  `section-c-master-imines-iminium-carbonyles`;

export const SECTION_C_AMINES_ALKYLATION_DISCOVERY_QUESTION_ORDERS: number[] = [61, 62, 63, 64, 65, 66, 67, 68, 69, 70];
export const SECTION_C_AMIDIFICATION_PRACTICE_QUESTION_ORDERS: number[] = [71, 72, 73, 74, 75, 76, 77, 78, 79, 80];
export const SECTION_C_IMINES_IMINIUM_MASTER_QUESTION_ORDERS: number[] = [81, 82, 83, 84, 85, 86, 87, 88, 89, 90];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: SECTION_C_AMINES_ALKYLATION_DISCOVERY_QUIZ_SLUG,
    title: `Amines : classes, nucléophilie et alkylation`,
    description: `Distinguer les amines primaires, secondaires et tertiaires, relier le doublet libre de l'azote à sa nucléophilie et suivre les alkylations successives par un dérivé halogéné.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_C_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 61 },
      { type: 'QUESTION', questionOrder: 62 },
      { type: 'QUESTION', questionOrder: 63 },
      { type: 'QUESTION', questionOrder: 64 },
      { type: 'QUESTION', questionOrder: 65 },
      { type: 'QUESTION', questionOrder: 66 },
      { type: 'QUESTION', questionOrder: 67 },
      {
        type: 'GROUP',
        title: `Alkylations successives par le bromoéthane`,
        sharedStatement: `On fait réagir progressivement l'ammoniac $\mathrm{NH_3}$ avec le bromoéthane $\mathrm{CH_3CH_2Br}$. Selon le nombre d'alkylations, on peut obtenir une amine primaire, une amine secondaire, une amine tertiaire puis un ammonium quaternaire.`,
        questionOrders: [68, 69, 70],
      },
    ],
  },
  {
    order: 8,
    slug: SECTION_C_AMIDIFICATION_PRACTICE_QUIZ_SLUG,
    title: `Amidification des amines`,
    description: `Identifier les amines capables de réagir avec un acide activé, reconnaître la fonction amide et relier cette réaction à la formation des liaisons peptidiques.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_C_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 71 },
      { type: 'QUESTION', questionOrder: 72 },
      { type: 'QUESTION', questionOrder: 73 },
      { type: 'QUESTION', questionOrder: 74 },
      { type: 'QUESTION', questionOrder: 75 },
      { type: 'QUESTION', questionOrder: 76 },
      { type: 'QUESTION', questionOrder: 77 },
      {
        type: 'GROUP',
        title: `Trois amines face à un chlorure d'acyle`,
        sharedStatement: `On compare **A**, la méthylamine $\mathrm{CH_3NH_2}$ ; **B**, la diméthylamine $\mathrm{(CH_3)_2NH}$ ; **C**, la triméthylamine $\mathrm{(CH_3)_3N}$. Chacune est mise en présence d'un chlorure d'acyle dans les conditions du cours.`,
        questionOrders: [78, 79, 80],
      },
    ],
  },
  {
    order: 9,
    slug: SECTION_C_IMINES_IMINIUM_MASTER_QUIZ_SLUG,
    title: `Réactions des amines avec les composés carbonylés`,
    description: `Prévoir la formation d'une imine ou d'un ion iminium selon la classe de l'amine et comprendre la réversibilité de ces transformations.`,
    stage: 'MASTER',
    sectionOrder: SECTION_C_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 81 },
      { type: 'QUESTION', questionOrder: 82 },
      { type: 'QUESTION', questionOrder: 83 },
      { type: 'QUESTION', questionOrder: 84 },
      { type: 'QUESTION', questionOrder: 85 },
      { type: 'QUESTION', questionOrder: 86 },
      { type: 'QUESTION', questionOrder: 87 },
      {
        type: 'GROUP',
        title: `Réactions de la propanone avec deux amines`,
        sharedStatement: `La propanone $\mathrm{CH_3{-}CO{-}CH_3}$ réagit séparément avec **A**, la méthylamine $\mathrm{CH_3NH_2}$, et **B**, la diméthylamine $\mathrm{(CH_3)_2NH}$. Les réactions sont envisagées dans le sens de la condensation puis dans le sens de l'hydrolyse.`,
        questionOrders: [88, 89, 90],
      },
    ],
  },
];

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `�' propos des amines :`,
    choices: [
      `Une amine primaire peut s'écrire $\mathrm{RNH_2}$.`,
      `Une amine secondaire peut s'écrire $\mathrm{RR'NH}$.`,
      `Une amine tertiaire peut s'écrire $\mathrm{RR'R''N}$.`,
      `La classe d'une amine dépend du nombre de groupes carbonés liés à l'azote.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La classification des amines repose sur le nombre de substituants carbonés portés par l'atome d'azote.`,
    choiceExplanations: [
      `Un seul groupe carboné est lié à l'azote.`,
      `Deux groupes carbonés sont liés à l'azote.`,
      `Trois groupes carbonés sont liés à l'azote.`,
      `Il faut compter les substituants de l'azote, non ceux d'un carbone voisin.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La méthylamine $\mathrm{CH_3NH_2}$ :`,
    choices: [
      `Est une amine primaire.`,
      `Possède un seul groupe carboné lié à l'azote.`,
      `Possède un doublet libre sur l'azote.`,
      `Est un ammonium quaternaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La méthylamine est une amine primaire dont l'azote porte un groupe méthyle, deux hydrogènes et un doublet non liant.`,
    choiceExplanations: [
      `Un seul substituant carboné définit la classe primaire.`,
      `Il s'agit du groupe $\mathrm{CH_3}$. `,
      `Ce doublet explique le caractère nucléophile de l'azote.`,
      `Un ammonium quaternaire porterait quatre groupes carbonés et une charge positive.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La diméthylamine $\mathrm{(CH_3)_2NH}$ :`,
    choices: [
      `Est une amine secondaire.`,
      `Possède deux groupes méthyle liés à l'azote.`,
      `Possède encore un hydrogène lié à l'azote.`,
      `Est une amine tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Deux groupes carbonés et un hydrogène sont liés à l'azote : la diméthylamine est secondaire.`,
    choiceExplanations: [
      `Deux substituants carbonés définissent la classe secondaire.`,
      `La formule l'indique explicitement.`,
      `Le symbole $\mathrm{NH}$ montre cet hydrogène.`,
      `Une amine tertiaire ne porterait plus d'hydrogène sur l'azote.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La triméthylamine $\mathrm{(CH_3)_3N}$ :`,
    choices: [
      `Est une amine tertiaire.`,
      `Possède trois groupes carbonés liés à l'azote.`,
      `Ne porte aucun hydrogène sur l'azote.`,
      `Est nécessairement un ammonium quaternaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La triméthylamine est neutre et possède trois substituants carbonés ; son azote conserve un doublet libre.`,
    choiceExplanations: [
      `Trois substituants caractérisent une amine tertiaire.`,
      `Ce sont trois groupes méthyle.`,
      `La formule ne comporte pas de liaison $\mathrm{N{-}H}$.`,
      `Un ammonium quaternaire possède quatre substituants et une charge positive.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le caractère nucléophile d'une amine est principalement lié :`,
    choices: [
      `Au doublet d'électrons libre porté par l'azote.`,
      `�' la possibilité pour l'azote de former une nouvelle liaison.`,
      `�' l'absence totale d'électrons autour de l'azote.`,
      `�' la présence obligatoire d'un halogène dans toute amine.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le doublet non liant de l'azote peut être donné à un centre électrophile pour former une liaison.`,
    choiceExplanations: [
      `C'est la source électronique de la nucléophilie.`,
      `Le doublet peut être engagé dans cette liaison nouvelle.`,
      `L'azote possède au contraire des électrons de valence.`,
      `Un halogène n'est pas nécessaire à la fonction amine.`,
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `�' propos d'un ammonium quaternaire $\mathrm{R_4N^+}$ :`,
    choices: [
      `L'azote est lié à quatre substituants carbonés.`,
      `L'espèce porte une charge positive.`,
      `Il ne s'agit plus d'une amine selon la distinction du cours.`,
      `L'azote possède encore le doublet libre caractéristique d'une amine neutre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Après quatre alkylations, l'azote est tétracoordonné et chargé positivement ; le doublet libre a été engagé dans la quatrième liaison.`,
    choiceExplanations: [
      `Quatre groupes $\mathrm{R}$ entourent l'azote.`,
      `La charge est indiquée par le symbole $\mathrm{N^+}$.`,
      `La fiche insiste sur cette distinction.`,
      `Le doublet libre n'est plus disponible.`,
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La réaction d'une amine avec un dérivé halogéné peut être décrite comme :`,
    choices: [
      `Une substitution nucléophile.`,
      `Une réaction dans laquelle l'azote nucléophile attaque un carbone électrophile.`,
      `Une voie permettant d'ajouter un substituant carboné sur l'azote.`,
      `Une oxydation forte d'un alcool primaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le doublet de l'azote attaque le carbone lié à l'halogène, ce qui remplace l'halogène par le groupe amine et alkyle l'azote.`,
    choiceExplanations: [
      `Le nucléophile remplace le groupe partant halogéné.`,
      `Le carbone de $\mathrm{R{-}X}$ est le centre attaqué.`,
      `Chaque réaction ajoute un groupe $\mathrm{R}$.`,
      `Cette transformation ne concerne pas l'oxydation des alcools.`,
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après une première alkylation de l'ammoniac par le bromoéthane :`,
    choices: [
      `Une amine primaire peut être obtenue.`,
      `Le produit organique peut être l'éthylamine $\mathrm{CH_3CH_2NH_2}$.`,
      `Un groupe éthyle est désormais lié à l'azote.`,
      `Un ammonium quaternaire est nécessairement obtenu dès cette étape.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La première substitution remplace un hydrogène de l'ammoniac par un groupe éthyle et conduit à une amine primaire.`,
    choiceExplanations: [
      `Un seul substituant carboné est présent.`,
      `Cette structure correspond au produit attendu.`,
      `Le fragment carboné provient du dérivé halogéné.`,
      `Quatre substituants seraient nécessaires.`,
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après deux puis trois alkylations par le même dérivé halogéné :`,
    choices: [
      `Une amine secondaire peut être formée après deux alkylations.`,
      `Une amine tertiaire peut être formée après trois alkylations.`,
      `Le nombre de groupes éthyle liés à l'azote augmente à chaque étape.`,
      `L'azote perd définitivement tous ses électrons dès la deuxième étape.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les alkylations successives remplacent progressivement les hydrogènes liés à l'azote par des groupes éthyle.`,
    choiceExplanations: [
      `Deux substituants carbonés définissent une amine secondaire.`,
      `Trois substituants définissent une amine tertiaire.`,
      `Chaque substitution ajoute un fragment $\mathrm{CH_3CH_2}$. `,
      `L'azote conserve son doublet libre tant qu'il reste une amine neutre.`,
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après une quatrième alkylation de l'amine tertiaire :`,
    choices: [
      `Un ammonium quaternaire est formé.`,
      `L'azote porte quatre groupes éthyle dans cet exemple.`,
      `Le produit est chargé positivement.`,
      `Le produit reste une amine primaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La quatrième liaison carbone-azote donne l'ion tétraéthylammonium, qui est un ammonium quaternaire.`,
    choiceExplanations: [
      `C'est l'aboutissement de la suite d'alkylations.`,
      `Le même dérivé halogéné a fourni les quatre substituants.`,
      `L'azote tétracoordonné porte une charge positive.`,
      `La classe primaire correspond à un seul substituant carboné.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L'amidification présentée dans le cours met en jeu :`,
    choices: [
      `Une amine primaire ou secondaire.`,
      `Un acide activé.`,
      `La formation d'une fonction amide.`,
      `Nécessairement un alcène et de l'eau comme seuls réactifs.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une amine portant au moins un hydrogène sur l'azote peut être acylée par un chlorure d'acyle ou un anhydride d'acide pour donner un amide.`,
    choiceExplanations: [
      `Ce sont les classes explicitement citées.`,
      `Le groupe acyle provient du dérivé activé.`,
      `C'est le produit fonctionnel recherché.`,
      `Un alcène n'intervient pas dans ce bilan.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les acides activés utilisables pour l'amidification selon la fiche figurent :`,
    choices: [
      `Les chlorures d'acyle $\mathrm{RCOCl}$.`,
      `Les anhydrides d'acide $\mathrm{RCOOCOR'}$.`,
      `Les alcanes simples.`,
      `Les organomagnésiens exclusivement.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les mêmes familles d'acides activés sont citées pour l'estérification des alcools et l'amidification des amines.`,
    choiceExplanations: [
      `Ils possèdent un groupe acyle très réactif.`,
      `Ils peuvent transférer un groupe acyle à l'azote.`,
      `Un alcane n'est pas un agent acylant.`,
      `Un organomagnésien est un nucléophile carboné, non l'acide activé recherché.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une fonction amide peut être représentée par le motif :`,
    choices: [
      `$\mathrm{R{-}CO{-}NH{-}R'}$.`,
      `Un groupe carbonyle directement lié à un azote.`,
      `$\mathrm{R{-}OH}$ uniquement.`,
      `$\mathrm{R{-}X}$ uniquement.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La fonction amide associe un groupe carbonyle et un atome d'azote directement lié au carbone carbonylé.`,
    choiceExplanations: [
      `Cette formule représente un amide substitué.`,
      `La liaison $\mathrm{C(O){-}N}$ est caractéristique.`,
      `Cette formule correspond à un alcool.`,
      `Cette formule correspond à un dérivé halogéné.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On compare une amine et un amide. �' propos de leur azote :`,
    choices: [
      `Dans un amide, l'azote est directement lié à un groupe carbonyle.`,
      `Une amine ne possède pas nécessairement de groupe carbonyle voisin.`,
      `Toute amine est automatiquement un amide.`,
      `Les deux fonctions doivent être distinguées lors de l'identification d'une molécule.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La présence d'un carbonyle directement attaché à l'azote transforme la fonction en amide et modifie son comportement chimique.`,
    choiceExplanations: [
      `C'est le critère structural essentiel.`,
      `Une amine simple peut ne contenir aucun oxygène.`,
      `Une amine et un amide sont deux fonctions distinctes.`,
      `La position relative de $\mathrm{C{=}O}$ et de $\mathrm{N}$ est déterminante.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La fonction amide est particulièrement importante en biologie car :`,
    choices: [
      `Elle est présente dans les liaisons reliant les acides aminés des peptides.`,
      `Elle se retrouve dans les protéines.`,
      `Une amidification constitue un modèle de formation d'une liaison de type peptidique.`,
      `Elle correspond toujours à un ammonium quaternaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les liaisons peptidiques sont des fonctions amide reliant les résidus d'acides aminés dans les peptides et les protéines.`,
    choiceExplanations: [
      `La liaison $\mathrm{CO{-}NH}$ relie les résidus.`,
      `Les protéines sont des chaînes peptidiques.`,
      `Le cours souligne ce lien avec leur synthèse.`,
      `Un amide est neutre dans la représentation générale et n'est pas un ammonium quaternaire.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lorsqu'une amine primaire $\mathrm{RNH_2}$ est acylée une fois :`,
    choices: [
      `Un amide portant encore une liaison $\mathrm{N{-}H}$ peut être obtenu.`,
      `Une nouvelle liaison entre l'azote et un carbone acyle est formée.`,
      `Le produit est nécessairement une amine tertiaire sans carbonyle.`,
      `Le groupe acyle provient de l'acide activé.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'azote de l'amine attaque le groupe acyle et devient directement lié au carbone carbonylé dans l'amide.`,
    choiceExplanations: [
      `L'amine primaire possédait deux hydrogènes ; l'un reste généralement sur l'azote dans le produit monoacylé.`,
      `C'est la liaison caractéristique de l'amide.`,
      `Le carbonyle est présent dans le produit.`,
      `Le dérivé activé fournit ce fragment.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lorsqu'une amine secondaire $\mathrm{RR'NH}$ est amidifiée :`,
    choices: [
      `Un amide N,N-disubstitué peut être formé.`,
      `L'unique hydrogène porté par l'azote est remplacé par un groupe acyle.`,
      `Le produit contient un motif $\mathrm{CO{-}N}$. `,
      `Une amine tertiaire est le seul réactif autorisé par le cours.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'amine secondaire possède un hydrogène sur l'azote, ce qui permet son acylation en amide sans liaison $\mathrm{N{-}H}$ résiduelle.`,
    choiceExplanations: [
      `Deux groupes carbonés restent liés à l'azote.`,
      `Le groupe acyle prend la place fonctionnelle de cet hydrogène.`,
      `C'est le motif amide.`,
      `Le cours cite les amines primaires et secondaires, non tertiaires, pour cette réaction.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant le composé **A** :`,
    choices: [
      `Il s'agit d'une amine primaire.`,
      `Il peut former un amide avec le chlorure d'acyle.`,
      `Son azote possède deux hydrogènes avant réaction.`,
      `Il s'agit d'un ammonium quaternaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La méthylamine est primaire et peut être acylée pour donner un amide comportant encore une liaison $\mathrm{N{-}H}$.`,
    choiceExplanations: [
      `Un seul groupe méthyle est lié à l'azote.`,
      `Elle appartient aux classes réactives indiquées.`,
      `La formule est $\mathrm{CH_3NH_2}$. `,
      `L'espèce est neutre et ne possède qu'un substituant carboné.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant le composé **B** :`,
    choices: [
      `Il s'agit d'une amine secondaire.`,
      `Il peut former un amide N,N-disubstitué.`,
      `Son azote possède un hydrogène avant réaction.`,
      `Il est incapable de toute amidification selon le cours.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La diméthylamine est secondaire et son unique liaison $\mathrm{N{-}H}$ permet l'acylation.`,
    choiceExplanations: [
      `Deux groupes méthyle sont liés à l'azote.`,
      `Après acylation, l'azote reste lié aux deux méthyles et au groupe acyle.`,
      `Le symbole $\mathrm{NH}$ le montre.`,
      `Les amines secondaires sont explicitement admises.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant le composé **C** dans le cadre précis de l'amidification décrite :`,
    choices: [
      `Il s'agit d'une amine tertiaire.`,
      `Il ne porte aucun hydrogène sur l'azote.`,
      `Il n'appartient pas aux amines primaires ou secondaires citées comme réactifs d'amidification.`,
      `Il forme nécessairement le même amide que la méthylamine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La triméthylamine ne possède aucune liaison $\mathrm{N{-}H}$ et n'est pas incluse dans le bilan d'amidification de la fiche.`,
    choiceExplanations: [
      `Trois groupes méthyle sont liés à l'azote.`,
      `La formule est $\mathrm{(CH_3)_3N}$. `,
      `Le cours limite cette transformation aux amines primaires et secondaires.`,
      `Les structures et les classes des deux amines sont différentes.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La réaction d'une amine primaire avec un aldéhyde ou une cétone :`,
    choices: [
      `Peut conduire à une imine.`,
      `S'accompagne de la formation d'eau dans le bilan.`,
      `Est présentée comme réversible.`,
      `Conduit nécessairement à un ammonium quaternaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La condensation d'une amine primaire sur un composé carbonylé forme une imine et de l'eau ; l'hydrolyse peut régénérer les réactifs.`,
    choiceExplanations: [
      `C'est le produit azoté attendu.`,
      `L'eau est éliminée lors de la condensation.`,
      `La flèche réversible traduit l'hydrolyse possible.`,
      `Aucune quatrième alkylation de l'azote n'est impliquée.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La réaction d'une amine secondaire avec un aldéhyde ou une cétone :`,
    choices: [
      `Peut conduire à un ion iminium.`,
      `S'accompagne de la formation d'eau.`,
      `Est réversible par hydrolyse.`,
      `Conduit au même type de produit neutre qu'une amine primaire dans tous les cas.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une amine secondaire forme un iminium, espèce portant une charge positive sur l'azote dans la représentation du cours.`,
    choiceExplanations: [
      `C'est le produit caractéristique de cette classe d'amine.`,
      `La condensation élimine de l'eau.`,
      `L'eau permet le retour vers l'amine et le carbonyle.`,
      `L'amine primaire forme une imine, non un iminium dans ce cadre.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les aldéhydes et les cétones sont regroupés sous le terme de composés carbonylés car :`,
    choices: [
      `Ils possèdent une liaison $\mathrm{C{=}O}$.`,
      `Le carbone du carbonyle peut réagir avec le doublet d'une amine.`,
      `Ils possèdent tous nécessairement une fonction alcool.`,
      `Ils peuvent intervenir dans la formation d'imines ou d'iminiums.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le groupe carbonyle constitue le site électrophile attaqué par l'azote nucléophile.`,
    choiceExplanations: [
      `C'est leur motif commun.`,
      `Le carbone carbonylé est le centre réactif.`,
      `Une fonction carbonyle est distincte d'une fonction alcool.`,
      `Le produit dépend de la classe de l'amine.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `�' propos d'une imine formée à partir d'une amine primaire :`,
    choices: [
      `Elle comporte une liaison carbone-azote multiple dans la représentation simplifiée.`,
      `Elle provient d'une condensation avec un composé carbonylé.`,
      `Son hydrolyse peut redonner l'amine et l'aldéhyde ou la cétone.`,
      `Elle est nécessairement un ester.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'imine résulte du remplacement fonctionnel du groupe carbonyle par un motif carboné lié à l'azote, avec élimination d'eau.`,
    choiceExplanations: [
      `Le motif $\mathrm{C{=}N}$ est caractéristique dans la représentation usuelle.`,
      `Le carbone provient de l'aldéhyde ou de la cétone.`,
      `La réaction est réversible.`,
      `Une fonction ester contient un motif $\mathrm{COO}$, absent ici.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `�' propos d'un ion iminium formé à partir d'une amine secondaire :`,
    choices: [
      `L'azote porte une charge positive dans la représentation du cours.`,
      `Le produit résulte d'une réaction avec un composé carbonylé.`,
      `Une hydrolyse est possible.`,
      `Le produit est une amine primaire non chargée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'amine secondaire se condense avec le carbonyle pour donner un iminium chargé positivement, susceptible d'être hydrolysé.`,
    choiceExplanations: [
      `La charge distingue notamment l'iminium de l'imine neutre.`,
      `Le carbone réactif vient de l'aldéhyde ou de la cétone.`,
      `Le sens inverse est indiqué dans la fiche.`,
      `Le produit n'est ni primaire ni neutre dans cette représentation.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On souhaite prévoir le produit azoté obtenu avec une cétone. Le critère déterminant est notamment :`,
    choices: [
      `La classe primaire ou secondaire de l'amine.`,
      `La présence d'un hydrogène ou de deux hydrogènes sur l'azote avant réaction.`,
      `La nature carbonylée du partenaire.`,
      `Le nombre de groupes hydroxyle d'un alcool absent de la réaction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une amine primaire conduit à une imine et une amine secondaire à un iminium ; le partenaire doit être un aldéhyde ou une cétone.`,
    choiceExplanations: [
      `C'est le critère qui sépare les deux bilans.`,
      `Il reflète la substitution de l'azote.`,
      `Le groupe $\mathrm{C{=}O}$ est le site réactif.`,
      `Ce paramètre n'est pas pertinent ici.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la réversibilité de la formation des imines et iminiums :`,
    choices: [
      `La condensation forme de l'eau.`,
      `L'hydrolyse consomme de l'eau.`,
      `L'hydrolyse peut régénérer le composé carbonylé.`,
      `Une fois formé, le produit ne peut jamais revenir aux réactifs.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le bilan est réversible : la condensation élimine de l'eau, tandis que l'hydrolyse utilise l'eau pour reformer l'amine et le carbonyle.`,
    choiceExplanations: [
      `C'est le petit produit de la réaction directe.`,
      `Elle intervient dans le sens inverse.`,
      `Le groupe $\mathrm{C{=}O}$ peut être restauré.`,
      `La fiche indique explicitement une hydrolyse possible.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la réaction de la propanone avec l'amine **A** :`,
    choices: [
      `Une imine peut être obtenue.`,
      `Une molécule d'eau est formée dans le sens de la condensation.`,
      `La méthylamine est une amine primaire.`,
      `Le produit attendu est obligatoirement un iminium.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La méthylamine est primaire ; avec une cétone, elle conduit à une imine et à de l'eau.`,
    choiceExplanations: [
      `C'est le produit associé aux amines primaires.`,
      `Le bilan de condensation l'indique.`,
      `Un seul groupe carboné est lié à son azote.`,
      `L'iminium est associé à une amine secondaire.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la réaction de la propanone avec l'amine **B** :`,
    choices: [
      `Un ion iminium peut être obtenu.`,
      `La diméthylamine est une amine secondaire.`,
      `Une molécule d'eau est formée dans le sens direct.`,
      `Une imine neutre est nécessairement le seul produit possible selon le cours.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La diméthylamine est secondaire ; sa condensation avec la propanone donne un iminium.`,
    choiceExplanations: [
      `C'est le produit associé à cette classe.`,
      `Deux groupes méthyle sont liés à l'azote.`,
      `La condensation élimine de l'eau.`,
      `L'imine neutre correspond au bilan d'une amine primaire.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si l'on ajoute de l'eau aux produits formés dans les deux expériences :`,
    choices: [
      `Une hydrolyse peut se produire.`,
      `La propanone peut être régénérée.`,
      `Les amines initiales peuvent être régénérées.`,
      `L'eau rend les transformations irréversibles dans le sens de la condensation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'eau favorise le sens hydrolytique et permet le retour vers le composé carbonylé et l'amine correspondante.`,
    choiceExplanations: [
      `C'est la réaction inverse prévue.`,
      `Le groupe carbonyle est reformé.`,
      `La liaison carbone-azote issue de la condensation peut être rompue.`,
      `La fiche présente au contraire une réversibilité.`,
    ],
  },
];
