/**
 * Cartographie éditoriale V2
 * UE14 – Chimie organique – Chapitre 2.3
 * Hydrocarbures : alcanes, alcènes, alcynes
 */

export const UE14_CH7_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'section-a-discovery-alcanes-cyclanes',
    title: `Alcanes et cyclanes`,
    description: `Repères sur les hydrocarbures saturés, leurs formules générales, leur nomenclature et la stabilité des cyclanes.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'section-a-practice-alcanes-cyclanes',
    title: `Alcanes et cyclanes`,
    description: `Applications sur les formules brutes, les séries homologues, la stabilité cyclique et les ambiguïtés alcène/cyclane.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,121,122],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'section-b-discovery-alcenes-structure-nomenclature',
    title: `Alcènes : structure, nomenclature et préparation`,
    description: `Repères sur la double liaison, la formule générale, les diènes/triènes, l'isomérie E/Z et les principales voies de préparation.`,
    stage: 'DISCOVER' as const,
    questionOrders: [21,22,23,24,25,26,27,28,29,30],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'section-b-practice-preparation-alcenes',
    title: `Alcènes : structure, nomenclature et préparation`,
    description: `Applications sur déshydratation, déshydrohalogénation, hydrogénation partielle et nomenclature des alcènes.`,
    stage: 'PRACTICE' as const,
    questionOrders: [31,32,33,34,35,36,37,38,39,40,123,124],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'section-c-discovery-additions-alcenes',
    title: `Réactions d'addition sur les alcènes`,
    description: `Repères sur hydrogénation, halogénation, hydrohalogénation, hydratation et règle de Markovnikov.`,
    stage: 'DISCOVER' as const,
    questionOrders: [41,42,43,44,45,46,47,48,49,50],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'section-c-practice-markovnikov-hydratation',
    title: `Réactions d'addition sur les alcènes`,
    description: `Applications de régiosélectivité et comparaison des principales additions sur une double liaison.`,
    stage: 'PRACTICE' as const,
    questionOrders: [51,52,53,54,55,56,57,58,59,60,125,126],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'section-d-discovery-oxydation-alcenes',
    title: `Oxydation des alcènes`,
    description: `Repères sur les oxydations douce, modérée et forte et sur les motifs époxyde, 1,2-diol et carbonyles.`,
    stage: 'DISCOVER' as const,
    questionOrders: [61,62,63,64,65,66,67,68,69,70],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'section-d-practice-produits-oxydation-alcenes',
    title: `Oxydation des alcènes`,
    description: `Applications sur la prévision des produits et l'interprétation structurale d'une coupure oxydante.`,
    stage: 'PRACTICE' as const,
    questionOrders: [71,72,73,74,75,76,77,78,79,80,127,128],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'section-e-discovery-alcynes-structure-nomenclature-hydrogenation',
    title: `Alcynes : structure, nomenclature et réactivité`,
    description: `Repères sur la triple liaison, la formule générale, les alcynes terminaux et l'hydrogénation catalytique.`,
    stage: 'DISCOVER' as const,
    questionOrders: [81,82,83,84,85,86,87,88,89,90],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'section-e-practice-alcynes-additions-hydratation',
    title: `Alcynes : structure, nomenclature et réactivité`,
    description: `Applications sur les additions successives, l'hydratation, la tautomérie énol/cétone et les méthylcétones.`,
    stage: 'PRACTICE' as const,
    questionOrders: [91,92,93,94,95,96,97,98,99,100,129,130],
  },
  {
    sectionOrder: 6,
    order: 1,
    slug: 'synthese-consolidation-hydrocarbures',
    title: `Alcanes, alcènes et alcynes`,
    description: `Synthèse appliquée reliant formules générales, préparation, additions, oxydations et hydratation des hydrocarbures insaturés.`,
    stage: 'PRACTICE' as const,
    questionOrders: [101,102,103,104,105,106,107,108,109,110],
  },
  {
    sectionOrder: 6,
    order: 2,
    slug: 'maitriser-synthese-hydrocarbures',
    title: `Alcanes, alcènes et alcynes`,
    description: `Maîtrise transversale des familles d'hydrocarbures et de leurs transformations dans des situations proches de l'examen.`,
    stage: 'MASTER' as const,
    questionOrders: [111,112,113,114,115,116,117,118,119,120,131,132],
  },
] as const;

export const UE14_CH7_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Alcanes et cyclanes : repères`],
  2: [`Alcanes et cyclanes : repères`],
  3: [`Alcanes et cyclanes : repères`],
  4: [`Alcanes et cyclanes : repères`],
  5: [`Alcanes et cyclanes : repères`],
  6: [`Alcanes et cyclanes : repères`],
  7: [`Stabilité des cyclanes`],
  8: [`Alcanes et cyclanes : repères`],
  9: [`Alcanes et cyclanes : repères`],
  10: [`Alcanes et cyclanes : repères`],
  11: [`Alcanes et cyclanes : applications`],
  12: [`Alcanes et cyclanes : applications`],
  13: [`Alcanes et cyclanes : applications`],
  14: [`Alcanes et cyclanes : applications`],
  15: [`Alcanes et cyclanes : applications`],
  16: [`Alcanes et cyclanes : applications`],
  17: [`Formule CnH2n : alcène ou cyclane`],
  18: [`Alcanes et cyclanes : applications`],
  19: [`Alcanes et cyclanes : applications`],
  20: [`Alcanes et cyclanes : applications`],
  21: [`Alcènes : structure, nomenclature et préparation`],
  22: [`Alcènes : structure, nomenclature et préparation`],
  23: [`Alcènes : structure, nomenclature et préparation`],
  24: [`Alcènes : structure, nomenclature et préparation`],
  25: [`Isomérie géométrique des alcènes`],
  26: [`Alcènes : structure, nomenclature et préparation`],
  27: [`Alcènes : structure, nomenclature et préparation`],
  28: [`Hydrogénation partielle d'un alcyne`],
  29: [`Alcènes : structure, nomenclature et préparation`],
  30: [`Alcènes : structure, nomenclature et préparation`],
  31: [`Préparation et nomenclature des alcènes`],
  32: [`Préparation et nomenclature des alcènes`],
  33: [`Préparation et nomenclature des alcènes`],
  34: [`Préparation et nomenclature des alcènes`],
  35: [`Préparation et nomenclature des alcènes`],
  36: [`But-1-ène / but-2-ène : isomérie de position`],
  37: [`Préparation et nomenclature des alcènes`],
  38: [`Préparation et nomenclature des alcènes`],
  39: [`Préparation et nomenclature des alcènes`],
  40: [`Préparation et nomenclature des alcènes`],
  41: [`Additions sur les alcènes : repères`],
  42: [`Additions sur les alcènes : repères`],
  43: [`Additions sur les alcènes : repères`],
  44: [`Additions sur les alcènes : repères`],
  45: [`Hydrohalogénation et règle de Markovnikov`],
  46: [`Propène + HCl : Markovnikov`],
  47: [`Additions sur les alcènes : repères`],
  48: [`Hydratation du propène`],
  49: [`Additions sur les alcènes : repères`],
  50: [`Additions sur les alcènes : repères`],
  51: [`Additions sur les alcènes : applications`],
  52: [`Additions sur les alcènes : applications`],
  53: [`Propène + HBr : produit Markovnikov`],
  54: [`Additions sur les alcènes : applications`],
  55: [`Additions sur les alcènes : applications`],
  56: [`Hydratation du but-1-ène`],
  57: [`Additions sur les alcènes : applications`],
  58: [`Additions sur les alcènes : applications`],
  59: [`Additions sur les alcènes : applications`],
  60: [`Additions sur les alcènes : applications`],
  61: [`Oxydation douce : époxyde`],
  62: [`Oxydation modérée : 1,2-diol`],
  63: [`Oxydation forte : coupure carbonylée`],
  64: [`Oxydation des alcènes : repères`],
  65: [`Oxydation des alcènes : repères`],
  66: [`Oxydation des alcènes : repères`],
  67: [`Oxydation des alcènes : repères`],
  68: [`Oxydation des alcènes : repères`],
  69: [`Oxydation des alcènes : repères`],
  70: [`Oxydation des alcènes : repères`],
  71: [`But-2-ène : coupure forte`],
  72: [`Alcène tétrasubstitué : cétones`],
  73: [`Oxydation des alcènes : produits et coupures`],
  74: [`Oxydation des alcènes : produits et coupures`],
  75: [`Oxydation des alcènes : produits et coupures`],
  76: [`Oxydation des alcènes : produits et coupures`],
  77: [`Oxydation des alcènes : produits et coupures`],
  78: [`Oxydation des alcènes : produits et coupures`],
  79: [`Oxydation des alcènes : produits et coupures`],
  80: [`Oxydation des alcènes : produits et coupures`],
  81: [`Alcynes : structure et réactivité`],
  82: [`Alcynes : structure et réactivité`],
  83: [`Alcynes : structure et réactivité`],
  84: [`Alcyne vrai : définition`],
  85: [`Alcynes : structure et réactivité`],
  86: [`Hydrogénation catalytique des alcynes`],
  87: [`Alcynes : structure et réactivité`],
  88: [`Alcynes : structure et réactivité`],
  89: [`Hydratation d'un alcyne et tautomérie`],
  90: [`Alcyne vrai : méthylcétone`],
  91: [`Alcynes : additions, hydratation et tautomérie`],
  92: [`Alcynes : additions, hydratation et tautomérie`],
  93: [`Alcynes : additions, hydratation et tautomérie`],
  94: [`Alcynes : additions, hydratation et tautomérie`],
  95: [`Alcyne interne : deux cétones possibles`],
  96: [`Alcynes : additions, hydratation et tautomérie`],
  97: [`Propyne : hydratation vers propanone`],
  98: [`Alcynes : additions, hydratation et tautomérie`],
  99: [`Alcynes : additions, hydratation et tautomérie`],
  100: [`Alcynes : additions, hydratation et tautomérie`],
  101: [`Synthèse appliquée des hydrocarbures`],
  102: [`Synthèse appliquée des hydrocarbures`],
  103: [`Synthèse appliquée des hydrocarbures`],
  104: [`Synthèse appliquée des hydrocarbures`],
  105: [`Synthèse appliquée des hydrocarbures`],
  106: [`Synthèse appliquée des hydrocarbures`],
  107: [`Synthèse appliquée des hydrocarbures`],
  108: [`Synthèse appliquée des hydrocarbures`],
  109: [`Alcyne vrai : Markovnikov et tautomérie`],
  110: [`Synthèse appliquée des hydrocarbures`],
  111: [`Maîtrise transversale des hydrocarbures`],
  112: [`Maîtrise transversale des hydrocarbures`],
  113: [`Maîtrise transversale des hydrocarbures`],
  114: [`Maîtrise transversale des hydrocarbures`],
  115: [`Coupure oxydante et reconstruction structurale`],
  116: [`Maîtrise transversale des hydrocarbures`],
  117: [`Diène et alcyne : même formule possible`],
  118: [`Maîtrise transversale des hydrocarbures`],
  119: [`Maîtrise transversale des hydrocarbures`],
  120: [`Maîtrise transversale des hydrocarbures`],
  121: [`Alcanes et cyclanes : consolidation`],
  122: [`Alcanes et cyclanes : consolidation`],
  123: [`Alcènes : consolidation`],
  124: [`Alcènes : consolidation`],
  125: [`Additions et Markovnikov : consolidation`],
  126: [`QZONE Markovnikov sur le propène`],
  127: [`Oxydation des alcènes : consolidation`],
  128: [`Oxydation des alcènes : consolidation`],
  129: [`Alcynes : consolidation`],
  130: [`Alcynes : consolidation`],
  131: [`Synthèse générale des hydrocarbures`],
  132: [`Synthèse générale : familles et réactivité`],
};
