/**
 * Cartographie éditoriale V2 — auteur.
 * Les stages décrivent la progression pédagogique, jamais un chronométrage.
 */

export const UE14_BIOCH_CH3_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-liaisons-diholosides",
    "title": "Définitions, liaisons et diholosides",
    "description": "Repères sur les osides, condensation, hydrolyse, lactose, saccharose et maltose.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-lactose-saccharose-maltose",
    "title": "Diholosides et hydrolyse",
    "description": "Applications structurales, digestives et biologiques sur les diholosides étudiés.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-amidon-glycogene",
    "title": "Amidon et glycogène",
    "description": "Repères sur amylose, amylopectine, amidon, glycogène et leurs architectures.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-digestion-reserves-glucidiques",
    "title": "Réserves glucidiques et digestion",
    "description": "Applications sur gélification, digestion enzymatique, localisation et ramification des réserves.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-cellulose-fibres-gag",
    "title": "Cellulose, fibres et premiers GAG",
    "description": "Repères sur cellulose, fibres, acide hyaluronique et chondroïtine sulfate.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-hyaluronique-chondroitine",
    "title": "Acide hyaluronique et chondroïtine",
    "description": "Applications physiologiques et structurales sur les GAG de matrice.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-gag-sulfates",
    "title": "GAG sulfatés et glycoconjugués",
    "description": "Repères sur dermatane, kératane, héparane, héparine, protéoglycanes et glycoprotéines.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-heparine-proteoglycanes",
    "title": "Héparine, protéoglycanes et glycoprotéines",
    "description": "Applications sur anticoagulation, matrice extracellulaire, glycoconjugués et reconnaissance.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-gag-glycoconjugues",
    "title": "GAG et glycoconjugués",
    "description": "Maîtrise structurale et biologique des GAG sulfatés et des glycoconjugués.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-osides",
    "title": "Les osides",
    "description": "Synthèse appliquée des diholosides, glucanes, fibres, GAG et glycoconjugués.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-osides",
    "title": "Les osides",
    "description": "Maîtrise transversale du chapitre dans l’esprit de l’examen, sans constituer un examen blanc.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH3_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Osides et diholosides : repères"],
  2: ["Osides et diholosides : repères"],
  3: ["Osides et diholosides : repères"],
  4: ["Osides et diholosides : repères"],
  5: ["Osides et diholosides : repères"],
  6: ["Osides et diholosides : repères"],
  7: ["Osides et diholosides : repères"],
  8: ["Osides et diholosides : repères"],
  9: ["Osides et diholosides : repères"],
  10: ["Osides et diholosides : repères"],
  11: ["Lactose : digestion et contexte clinique"],
  12: ["Diholosides : applications"],
  13: ["Diholosides : applications"],
  14: ["Diholosides : applications"],
  15: ["Diholosides : applications"],
  16: ["Diholosides : applications"],
  17: ["Diholosides : applications"],
  18: ["Diholosides : applications"],
  19: ["Diholosides : applications"],
  20: ["Diholosides : applications"],
  21: ["Diholosides : applications"],
  22: ["Diholosides : applications"],
  23: ["Amidon et glycogène : repères"],
  24: ["Amidon et glycogène : repères"],
  25: ["Amidon et glycogène : repères"],
  26: ["Amidon et glycogène : repères"],
  27: ["Amidon et glycogène : repères"],
  28: ["Amidon et glycogène : repères"],
  29: ["Amidon et glycogène : repères"],
  30: ["Amidon et glycogène : repères"],
  31: ["Amidon et glycogène : repères"],
  32: ["Amidon et glycogène : repères"],
  33: ["Réserves glucidiques : applications"],
  34: ["Réserves glucidiques : applications"],
  35: ["Réserves glucidiques : applications"],
  36: ["Réserves glucidiques : applications"],
  37: ["Réserves glucidiques : applications"],
  38: ["Réserves glucidiques : applications"],
  39: ["Réserves glucidiques : applications"],
  40: ["Réserves glucidiques : applications"],
  41: ["Réserves glucidiques : applications"],
  42: ["Réserves glucidiques : applications"],
  43: ["Réserves glucidiques : applications"],
  44: ["Réserves glucidiques : applications"],
  45: ["Cellulose et GAG : repères"],
  46: ["Cellulose et GAG : repères"],
  47: ["Cellulose et GAG : repères"],
  48: ["Cellulose et GAG : repères"],
  49: ["Fibres végétales : facteurs de risque"],
  50: ["Cellulose et GAG : repères"],
  51: ["Cellulose et GAG : repères"],
  52: ["Cellulose et GAG : repères"],
  53: ["Cellulose et GAG : repères"],
  54: ["Cellulose et GAG : repères"],
  55: ["Hyaluronique et chondroïtine : applications"],
  56: ["Hyaluronidase et fécondation"],
  57: ["Hyaluronique et chondroïtine : applications"],
  58: ["Hyaluronique et chondroïtine : applications"],
  59: ["Hyaluronique et chondroïtine : applications"],
  60: ["Hyaluronique et chondroïtine : applications"],
  61: ["Hyaluronique et chondroïtine : applications"],
  62: ["Hyaluronique et chondroïtine : applications"],
  63: ["Hyaluronique et chondroïtine : applications"],
  64: ["Hyaluronique et chondroïtine : applications"],
  65: ["Hyaluronique et chondroïtine : applications"],
  66: ["Hyaluronique et chondroïtine : applications"],
  67: ["GAG sulfatés et glycoconjugués : repères"],
  68: ["GAG sulfatés et glycoconjugués : repères"],
  69: ["GAG sulfatés et glycoconjugués : repères"],
  70: ["GAG sulfatés et glycoconjugués : repères"],
  71: ["GAG sulfatés et glycoconjugués : repères"],
  72: ["GAG sulfatés et glycoconjugués : repères"],
  73: ["GAG sulfatés et glycoconjugués : repères"],
  74: ["GAG sulfatés et glycoconjugués : repères"],
  75: ["GAG sulfatés et glycoconjugués : repères"],
  76: ["GAG sulfatés et glycoconjugués : repères"],
  77: ["Héparine et thrombose"],
  78: ["GAG et glycoconjugués : applications"],
  79: ["GAG et glycoconjugués : applications"],
  80: ["GAG et glycoconjugués : applications"],
  81: ["GAG et glycoconjugués : applications"],
  82: ["Glycoprotéines et groupes sanguins"],
  83: ["GAG et glycoconjugués : applications"],
  84: ["GAG et glycoconjugués : applications"],
  85: ["GAG et glycoconjugués : applications"],
  86: ["GAG et glycoconjugués : applications"],
  87: ["GAG et glycoconjugués : applications"],
  88: ["GAG et glycoconjugués : applications"],
  89: ["QZONE : protéine cœur du protéoglycane"],
  90: ["GAG et glycoconjugués : maîtrise"],
  91: ["GAG et glycoconjugués : maîtrise"],
  92: ["GAG et glycoconjugués : maîtrise"],
  93: ["GAG et glycoconjugués : maîtrise"],
  94: ["GAG et glycoconjugués : maîtrise"],
  95: ["GAG et glycoconjugués : maîtrise"],
  96: ["GAG et glycoconjugués : maîtrise"],
  97: ["GAG et glycoconjugués : maîtrise"],
  98: ["GAG et glycoconjugués : maîtrise"],
  99: ["GAG et glycoconjugués : maîtrise"],
  100: ["GAG et glycoconjugués : maîtrise"],
  101: ["Synthèse des osides"],
  102: ["Synthèse des osides"],
  103: ["Synthèse des osides"],
  104: ["Synthèse des osides"],
  105: ["Héparine : anticoagulation"],
  106: ["Hyaluronidase : fécondation"],
  107: ["Synthèse des osides"],
  108: ["Synthèse des osides"],
  109: ["Synthèse des osides"],
  110: ["Synthèse des osides"],
  111: ["Maîtrise transversale des osides"],
  112: ["Maîtrise transversale des osides"],
  113: ["Maîtrise transversale des osides"],
  114: ["Maîtrise transversale des osides"],
  115: ["Maîtrise transversale des osides"],
  116: ["Maîtrise transversale des osides"],
  117: ["Maîtrise transversale des osides"],
  118: ["Maîtrise transversale des osides"],
  119: ["Maîtrise transversale des osides"],
  120: ["Maîtrise transversale des osides"],
  121: ["Applications biologiques et médicales"],
  122: ["Maîtrise transversale des osides"],
};
