import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_ORDER = 1;

export const SECTION_A_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Généralités sur les glucides"],
  2: ["Glucides dans le monde végétal"],
  3: ["Répartition de la ration calorique"],
  4: ["Rôles énergétiques et structuraux"],
  5: ["Glucides de surface"],
  6: ["Glucides dans les biomolécules"],
  7: ["Pathologies liées aux glucides"],
  8: ["Contexte médical : intolérance au lactose"],
  9: ["Structure générale des oses"],
  10: ["Formule générale des oses"],
  11: ["Chaîne et numérotation des oses"],
  12: ["Aldoses"],
  13: ["Cétoses"],
  14: ["Formule générale des aldoses"],
  15: ["Formule générale des cétoses"],
  16: ["Fonctions alcool des oses"],
  17: ["Nomenclature des oses"],
  18: ["Classification par nombre de carbones"],
  19: ["Noms composés des oses"],
  20: ["Classification du glucose"],
  21: ["Application : glycéraldéhyde et dihydroxyacétone"],
  22: ["Classification du fructose"],
  23: ["Application de la formule générale"],
  24: ["Nomenclature appliquée"],
  25: ["Lecture d'une formule semi-développée"],
  26: ["Lecture d'un cétose"],
  27: ["Limites de la formule brute"],
  28: ["Démarche de classification"],
  29: ["Contexte médical : glycémie"],
  30: ["Synthèse de la section A"],
};

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "decouvrir-generalites-structure-oses",
    title: "Généralités et structure des oses",
    description: "Repères fondamentaux sur les rôles des glucides, leur composition et la structure générale des oses.",
    stage: 'DISCOVER',
    sectionOrder: SECTION_A_ORDER,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: "sentrainer-classification-nomenclature-oses",
    title: "Classification et nomenclature des oses",
    description: "Distinguer aldoses et cétoses, lire les fonctions et nommer les oses selon la longueur de chaîne.",
    stage: 'PRACTICE',
    sectionOrder: SECTION_A_ORDER,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: "maitriser-structure-formules-oses",
    title: "Structure et formules des oses",
    description: "Applications transversales sur les formules, la lecture de chaînes et la classification de glucides d'intérêt biologique.",
    stage: 'MASTER',
    sectionOrder: SECTION_A_ORDER,
    items: [
      {
        type: 'GROUP',
        title: "Deux trioses de même formule brute",
        sharedStatement: "On compare le glycéraldéhyde et la dihydroxyacétone, deux trioses de formule brute $\\mathrm{C_3H_6O_3}$, mais de fonctions carbonyle différentes.",
        questionOrders: [21, 22],
      },
      { type: 'QUESTION', questionOrder: 23 },
      { type: 'QUESTION', questionOrder: 24 },
      { type: 'QUESTION', questionOrder: 25 },
      { type: 'QUESTION', questionOrder: 26 },
      { type: 'QUESTION', questionOrder: 27 },
      { type: 'QUESTION', questionOrder: 28 },
      { type: 'QUESTION', questionOrder: 29 },
      { type: 'QUESTION', questionOrder: 30 },
    ],
  },
];

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos des glucides :",
    choices: [
      "Ce sont des composés organiques largement rencontrés dans le monde vivant.",
      "Ils sont produits dans le monde végétal notamment par la photosynthèse.",
      "Ils sont absents du monde animal.",
      "Ils ne jouent qu'un rôle énergétique.",
    ],
    correctChoiceIndexes: [0, 1],
    explanation: "Les glucides sont présents dans les mondes végétal et animal. Ils assurent des fonctions énergétiques, structurales et de reconnaissance, entre autres.",
    choiceExplanations: [
      "La présence d'une charpente carbonée les classe parmi les composés organiques.",
      "La photosynthèse produit des glucides dans les végétaux.",
      "Les animaux contiennent et métabolisent de nombreux glucides.",
      "Leurs rôles dépassent largement la seule fourniture d'énergie.",
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Les glucides représentent approximativement quelle part du poids sec des plantes ?",
    choices: [
      "7 %.",
      "30 %.",
      "70 %.",
      "95 %.",
    ],
    correctChoiceIndexes: [2],
    explanation: "La fiche indique qu'environ 70 % du poids sec des plantes est constitué de glucides.",
    choiceExplanations: [
      "Cette valeur est dix fois trop faible.",
      "Cette proportion est inférieure à celle donnée dans la fiche.",
      "Il s'agit de la valeur à retenir dans le cadre du cours.",
      "La fiche ne donne pas une proportion aussi élevée.",
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant la répartition des apports énergétiques :",
    choices: [
      "Les glucides représentent environ 50 à 55 % de la ration calorique.",
      "Les lipides représentent environ 30 à 35 % de la ration calorique.",
      "Les protéines représentent environ 10 à 12 % de la ration calorique.",
      "Les protéines représentent la majorité de la ration calorique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les ordres de grandeur à retenir sont 50–55 % pour les glucides, 30–35 % pour les lipides et 10–12 % pour les protéines.",
    choiceExplanations: [
      "Cette fourchette est celle donnée pour les glucides.",
      "Cette fourchette est celle donnée pour les lipides.",
      "Cette fourchette est celle donnée pour les protéines.",
      "Les protéines constituent la plus petite des trois parts indiquées.",
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les rôles biologiques des glucides :",
    choices: [
      "Fourniture d'énergie, notamment par le glucose.",
      "Constitution de réserves dans le foie et le muscle.",
      "Participation au soutien structural.",
      "Absence totale de rôle à la surface des cellules.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les glucides fournissent de l'énergie, participent aux réserves et peuvent avoir un rôle structural. Ils interviennent aussi à la surface cellulaire.",
    choiceExplanations: [
      "Le glucose est une source énergétique majeure.",
      "Le glycogène hépatique et musculaire constitue une réserve glucidique.",
      "Certains glucides contribuent aux structures biologiques.",
      "Les glucides de surface participent aux interactions et à la reconnaissance.",
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À la surface des cellules, les glucides peuvent participer :",
    choices: [
      "Aux interactions cellulaires.",
      "À la protection.",
      "Aux signaux de reconnaissance.",
      "Aux déterminants antigéniques, comme ceux des groupes sanguins.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les glucides de surface interviennent dans les interactions, la protection, la reconnaissance et certains déterminants antigéniques.",
    choiceExplanations: [
      "Cet item correspond à un rôle mentionné dans le cours.",
      "Cet item correspond à un rôle mentionné dans le cours.",
      "Cet item correspond à un rôle mentionné dans le cours.",
      "Les groupes sanguins constituent l'exemple donné par la fiche.",
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les glucides entrent dans la constitution de molécules fondamentales telles que :",
    choices: [
      "L'ARN.",
      "L'ADN.",
      "Certaines coenzymes.",
      "Certaines vitamines.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Des motifs glucidiques sont présents dans les acides nucléiques ainsi que dans diverses coenzymes et vitamines.",
    choiceExplanations: [
      "Le ribose est présent dans l'ARN.",
      "Le désoxyribose est présent dans l'ADN.",
      "Certaines coenzymes comportent une partie glucidique.",
      "Certaines vitamines ou leurs dérivés comportent des motifs apparentés.",
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant les maladies ou troubles cités en lien avec les glucides :",
    choices: [
      "Le diabète implique une anomalie du métabolisme du glucose.",
      "La galactosémie implique une anomalie du métabolisme du galactose.",
      "Les glycogénoses peuvent résulter de déficits enzymatiques.",
      "L'intolérance au lactose est identique à l'allergie aux protéines du lait.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La fiche distingue les anomalies métaboliques du glucose ou du galactose, les glycogénoses enzymatiques et l'intolérance au lactose de l'allergie aux protéines du lait.",
    choiceExplanations: [
      "Cette association est correcte.",
      "Cette association est correcte.",
      "Les glycogénoses sont liées à des déficits enzymatiques.",
      "L'intolérance concerne la digestion du lactose, tandis que l'allergie vise des protéines.",
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Un patient digère mal le lactose sans présenter de réaction immunitaire contre les protéines du lait. La situation évoque en premier lieu :",
    choices: [
      "Une intolérance au lactose.",
      "Une allergie aux protéines du lait.",
      "Une glycogénose.",
      "Une galactosémie congénitale certaine.",
    ],
    correctChoiceIndexes: [0],
    explanation: "L'intolérance au lactose est un trouble de digestion du sucre du lait et ne doit pas être confondue avec une allergie aux protéines du lait.",
    choiceExplanations: [
      "La description correspond à une anomalie de digestion du lactose.",
      "Une allergie implique une réponse immunitaire contre des protéines.",
      "Une glycogénose concerne le métabolisme du glycogène.",
      "Le tableau décrit ne suffit pas à diagnostiquer une galactosémie.",
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La structure générale d'un ose simple peut comporter :",
    choices: [
      "Une chaîne carbonée.",
      "Une fonction carbonyle.",
      "Plusieurs fonctions alcool.",
      "Parfois des fonctions acides ou amines dans certains dérivés.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les oses reposent sur une chaîne carbonée portant une fonction carbonyle et plusieurs fonctions alcool ; certains dérivés comportent aussi des fonctions acides ou amines.",
    choiceExplanations: [
      "La charpente carbonée constitue le squelette.",
      "Le carbonyle distingue notamment aldoses et cétoses.",
      "Les nombreux groupes hydroxyle sont caractéristiques.",
      "Cette possibilité est explicitement signalée dans la fiche.",
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Pour un ose simple composé uniquement de carbone, d'hydrogène et d'oxygène, les écritures suivantes sont équivalentes :",
    choices: [
      "$\\mathrm{C_nH_{2n}O_n}$.",
      "$(\\mathrm{CH_2O})_n$.",
      "$\\mathrm{C_n(H_2O)_n}$.",
      "$\\mathrm{C_nH_nO_{2n}}$.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les trois premières écritures traduisent le même rapport atomique général 1:2:1. La quatrième inverse les proportions d'hydrogène et d'oxygène.",
    choiceExplanations: [
      "C'est la formule générale indiquée.",
      "Cette écriture factorise l'unité $\\mathrm{CH_2O}$.",
      "Cette écriture est algébriquement équivalente.",
      "Elle ne respecte pas le rapport 1:2:1.",
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Concernant la chaîne carbonée des oses simples :",
    choices: [
      "Elle comporte au minimum trois carbones.",
      "Elle est décrite comme non ramifiée.",
      "La numérotation débute au carbone le plus oxydé.",
      "La numérotation débute toujours à l'extrémité la moins oxydée.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les oses simples sont présentés comme des chaînes non ramifiées d'au moins trois carbones, numérotées à partir du carbone le plus oxydé.",
    choiceExplanations: [
      "Trois carbones correspondent aux trioses.",
      "L'absence d'embranchement est un repère du cours.",
      "Cette règle fixe la position du carbonyle.",
      "La règle est exactement inverse.",
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un aldose, sous sa forme linéaire :",
    choices: [
      "Porte une fonction aldéhyde en C1.",
      "Est numéroté à partir du carbone du groupe aldéhyde.",
      "Porte nécessairement une fonction cétone en C2.",
      "Peut aussi porter des fonctions alcool primaires et secondaires.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Dans un aldose, le carbone le plus oxydé est celui de l'aldéhyde en C1. Les autres carbones portent généralement des fonctions alcool.",
    choiceExplanations: [
      "Le groupe $\\mathrm{-CHO}$ caractérise l'aldose.",
      "Le carbone aldéhydique reçoit le numéro 1.",
      "Une cétone en C2 caractérise au contraire un cétose.",
      "Ces fonctions alcool complètent la structure.",
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un cétose, sous sa forme linéaire :",
    choices: [
      "Porte classiquement une fonction cétone en C2.",
      "Possède un groupe $\\mathrm{CH_2OH}$ à au moins une extrémité.",
      "Est nécessairement un aldéhyde en C1.",
      "Est numéroté de façon à donner le plus petit indice au carbone le plus oxydé.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le cétose étudié porte une cétone en C2 et des groupes alcool, notamment des groupes $\\mathrm{CH_2OH}$ terminaux.",
    choiceExplanations: [
      "La position C2 est celle retenue dans la fiche.",
      "Les cétoses usuels du cours présentent un alcool primaire terminal.",
      "Un aldéhyde en C1 définirait un aldose.",
      "La numérotation part du côté le plus proche du carbonyle.",
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: "La formule linéaire générale $\\mathrm{CH_2OH-(CHOH)_{n-2}-CHO}$ correspond à :",
    choices: [
      "Un aldose.",
      "Un cétose.",
      "Un acide gras.",
      "Un polyoside cyclique uniquement.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La présence du groupe terminal $\\mathrm{-CHO}$ caractérise un aldose.",
    choiceExplanations: [
      "Le groupe aldéhyde terminal permet l'identification.",
      "Un cétose comporte un groupe $\\mathrm{-CO-}$ interne.",
      "Cette formule ne décrit pas un acide gras.",
      "Elle décrit précisément une forme linéaire.",
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: "La formule linéaire générale $\\mathrm{CH_2OH-CO-(CHOH)_{n-3}-CH_2OH}$ correspond à :",
    choices: [
      "Un aldose.",
      "Un cétose.",
      "Un peptide.",
      "Un stérol.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Le groupe carbonyle interne $\\mathrm{-CO-}$ en C2 caractérise un cétose.",
    choiceExplanations: [
      "Un aldose porte un carbonyle terminal.",
      "La formule présente bien la cétone en C2.",
      "Aucune liaison peptidique n'est présente.",
      "Aucun noyau stérane n'est présent.",
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos des fonctions alcool dans un ose linéaire :",
    choices: [
      "Un groupe $\\mathrm{CH_2OH}$ correspond à un alcool primaire.",
      "Un motif $\\mathrm{H-C-OH}$ interne correspond à un alcool secondaire.",
      "Tout groupe $\\mathrm{-OH}$ d'un ose est une fonction acide carboxylique.",
      "La présence de plusieurs groupes hydroxyle contribue au caractère polyalcool.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les extrémités $\\mathrm{CH_2OH}$ sont des alcools primaires et les carbones internes $\\mathrm{CHOH}$ des alcools secondaires.",
    choiceExplanations: [
      "Le carbone porteur est terminal.",
      "Le carbone porteur est lié à deux carbones.",
      "Un hydroxyle alcoolique ne constitue pas un carboxyle.",
      "Les oses possèdent plusieurs fonctions alcool.",
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le nom d'un ose linéaire dépend notamment :",
    choices: [
      "Du nombre de carbones de sa chaîne.",
      "De sa famille aldose ou cétose.",
      "De la seule couleur de la solution.",
      "De la position du carbonyle.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La nomenclature combine le nombre de carbones et la nature aldéhydique ou cétonique du carbonyle.",
    choiceExplanations: [
      "Tri-, tétr-, pent-, hex- et hept- renseignent sur la longueur.",
      "Aldo- et céto- distinguent les familles.",
      "La couleur n'entre pas dans cette nomenclature.",
      "La position terminale ou interne du carbonyle est déterminante.",
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Associer correctement le nombre de carbones au nom générique :",
    choices: [
      "3 carbones : triose.",
      "4 carbones : tétrose.",
      "5 carbones : pentose.",
      "6 carbones : hexose.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les préfixes tri-, tétr-, pent- et hex- correspondent respectivement à 3, 4, 5 et 6 carbones.",
    choiceExplanations: [
      "Association correcte.",
      "Association correcte.",
      "Association correcte.",
      "Association correcte.",
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Parmi les associations suivantes :",
    choices: [
      "Un aldose à 3 carbones est un aldotriose.",
      "Un cétose à 5 carbones est un cétopentose.",
      "Un aldose à 6 carbones est un aldohexose.",
      "Un cétose à 7 carbones est un cétoheptose.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le préfixe aldo- ou céto- indique la famille et la seconde partie du nom indique le nombre de carbones.",
    choiceExplanations: [
      "Association correcte.",
      "Association correcte.",
      "Association correcte.",
      "Association correcte.",
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: "Le glucose est classé, dans sa forme linéaire, comme :",
    choices: [
      "Un aldotriose.",
      "Un cétotétrose.",
      "Un aldohexose.",
      "Un cétohexose.",
    ],
    correctChoiceIndexes: [2],
    explanation: "Le glucose comporte six carbones et une fonction aldéhyde dans sa forme linéaire : c'est un aldohexose.",
    choiceExplanations: [
      "Le glucose possède plus de trois carbones.",
      "Il n'a ni quatre carbones ni fonction cétone.",
      "Cette classification combine correctement famille et longueur.",
      "Le fructose est l'exemple classique de cétohexose.",
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Deux molécules ont la formule brute $\mathrm{C_3H_6O_3}$. L'une porte un aldéhyde terminal, l'autre une cétone en C2. On peut conclure que :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glyceraldehyde-dihydroxyacetone-linear',
    },
    choices: [
      "La première peut être le glycéraldéhyde.",
      "La seconde peut être la dihydroxyacétone.",
      "Elles appartiennent nécessairement à la même famille fonctionnelle.",
      "La formule brute seule ne suffit pas à distinguer leur structure.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le glycéraldéhyde est un aldotriose et la dihydroxyacétone un cétotriose. Ils partagent une formule brute mais pas la même fonction.",
    choiceExplanations: [
      "Le glycéraldéhyde porte bien un aldéhyde.",
      "La dihydroxyacétone porte une cétone en C2.",
      "Aldose et cétose sont deux familles distinctes.",
      "Une formule développée est nécessaire pour les distinguer.",
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "À propos du fructose :",
    choices: [
      "Sa forme linéaire appartient aux cétoses.",
      "Il comporte six carbones et peut être qualifié de cétohexose.",
      "Son carbonyle linéaire est classiquement en C2.",
      "Il est nécessairement un aldopentose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le fructose est le cétohexose de référence : six carbones et une cétone en C2 dans la forme linéaire.",
    choiceExplanations: [
      "La famille est correcte.",
      "Le nom combine correctement céto- et hexose.",
      "Cette position est celle du carbonyle du fructose.",
      "Cette classification est incompatible avec sa structure.",
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une molécule répond à la formule générale d'un ose avec $n=5$. On peut affirmer que :",
    choices: [
      "Sa formule brute est $\\mathrm{C_5H_{10}O_5}$.",
      "Elle appartient à la famille générique des pentoses.",
      "Elle est forcément un aldose.",
      "Elle peut être un aldopentose ou un cétopentose selon son carbonyle.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Pour $n=5$, la formule générale donne $\\mathrm{C_5H_{10}O_5}$. La nature aldose ou cétose exige une information structurale supplémentaire.",
    choiceExplanations: [
      "Le calcul des indices est correct.",
      "Cinq carbones définissent un pentose.",
      "La formule brute n'impose pas la fonction.",
      "Les deux familles sont possibles.",
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: "Un ose linéaire comporte 7 carbones et une fonction aldéhyde terminale. Son nom générique est :",
    choices: [
      "Aldopentose.",
      "Aldoheptose.",
      "Cétoheptose.",
      "Hexose.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Sept carbones donnent heptose et l'aldéhyde terminal donne le préfixe aldo-.",
    choiceExplanations: [
      "Cinq carbones seraient nécessaires.",
      "La combinaison aldo- + heptose est correcte.",
      "Le préfixe céto- supposerait une cétone.",
      "Le terme hexose correspond à six carbones.",
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une chaîne linéaire $\\mathrm{CHO-CHOH-CHOH-CH_2OH}$ :",
    choices: [
      "Comporte quatre carbones.",
      "Est un aldotétrose.",
      "Possède un alcool primaire terminal.",
      "Est un cétotétrose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le décompte donne quatre carbones ; le groupe $\\mathrm{CHO}$ terminal définit un aldotétrose et le $\\mathrm{CH_2OH}$ un alcool primaire.",
    choiceExplanations: [
      "Le décompte est direct.",
      "La famille et la longueur sont correctement associées.",
      "Le dernier carbone porte un groupe alcool primaire.",
      "Le carbonyle n'est pas une cétone interne.",
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une chaîne linéaire $\\mathrm{CH_2OH-CO-CHOH-CH_2OH}$ :",
    choices: [
      "Comporte quatre carbones.",
      "Est un cétotétrose.",
      "Porte une cétone en C2.",
      "Porte un aldéhyde en C1.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Cette chaîne à quatre carbones possède un carbonyle interne en C2 : c'est un cétotétrose.",
    choiceExplanations: [
      "Le décompte donne quatre.",
      "La classification est correcte.",
      "Le motif $\\mathrm{-CO-}$ occupe C2.",
      "Le C1 est un groupe $\\mathrm{CH_2OH}$, pas un aldéhyde.",
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "La formule brute $\\mathrm{C_6H_{12}O_6}$ :",
    choices: [
      "Est compatible avec la formule générale d'un ose simple.",
      "Suffit à prouver qu'il s'agit du glucose.",
      "Est également compatible avec le fructose.",
      "Ne renseigne pas à elle seule sur la position du carbonyle.",
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: "Une même formule brute peut correspondre à plusieurs oses, notamment glucose et fructose. La structure doit être précisée.",
    choiceExplanations: [
      "Le rapport 1:2:1 est respecté.",
      "Plusieurs isomères partagent cette formule.",
      "Le fructose possède la même formule brute.",
      "La formule développée est nécessaire.",
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un ose simple possède une chaîne non ramifiée de six carbones. Pour le classer précisément, il faut notamment déterminer :",
    choices: [
      "La nature aldéhyde ou cétone du carbonyle.",
      "La position du carbonyle.",
      "Le nombre de carbones, déjà connu.",
      "Son nom commercial éventuel.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La classification repose sur le nombre de carbones et la famille du carbonyle. Un nom commercial n'est pas un critère structural.",
    choiceExplanations: [
      "La nature du carbonyle distingue aldose et cétose.",
      "Sa position contribue à cette distinction.",
      "Six carbones imposent le terme hexose.",
      "La classification biochimique n'utilise pas un nom commercial.",
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Lors d'un bilan biologique, la glycémie mesure la concentration sanguine en glucose. À propos de ce glucose :",
    choices: [
      "Il constitue une source énergétique majeure.",
      "Sa forme linéaire est celle d'un aldohexose.",
      "Une glycémie anormale peut être associée au diabète.",
      "Il ne possède aucun rôle biologique en dehors du sang.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glucose est un aldohexose majeur du métabolisme énergétique ; son contrôle sanguin est central dans le diabète.",
    choiceExplanations: [
      "Son rôle énergétique est fondamental.",
      "Sa classification structurale est correcte.",
      "Le diabète implique une dérégulation de la glycémie.",
      "Le glucose est utilisé dans de très nombreux tissus.",
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Concernant les oses simples étudiés :",
    choices: [
      "Ils possèdent au moins trois carbones.",
      "Le carbone le plus oxydé guide la numérotation.",
      "Aldoses et cétoses peuvent partager une même formule brute.",
      "Tous les items précédents sont vrais.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les trois premières propositions reprennent des caractéristiques du chapitre ; l'item récapitulatif est donc également vrai.",
    choiceExplanations: [
      "Caractéristique correcte.",
      "Règle correcte.",
      "L'exemple glycéraldéhyde/dihydroxyacétone l'illustre.",
      "Puisque A, B et C sont vraies, cet item est vrai.",
    ],
  },
];
