/**
 * UE14 – Biologie cellulaire – Chapitre 9 : Le cycle cellulaire
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du renouvellement cellulaire dans un tissu sain :`,
    choices: [
      `Le nombre total de cellules reste globalement constant.`,
      `Les cellules mortes doivent être remplacées.`,
      `Toutes les cellules ont la même durée de vie.`,
      `Il existe un équilibre entre prolifération et apoptose.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le tissu sain maintient un équilibre régulé entre cellules produites et cellules éliminées.`,
    choiceExplanations: [
      `Exact. Le tissu sain maintient un équilibre régulé entre cellules produites et cellules éliminées.`,
      `Exact. Le tissu sain maintient un équilibre régulé entre cellules produites et cellules éliminées.`,
      `Faux. Le tissu sain maintient un équilibre régulé entre cellules produites et cellules éliminées.`,
      `Exact. Le tissu sain maintient un équilibre régulé entre cellules produites et cellules éliminées.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les deux grandes populations cellulaires d’un tissu sont :`,
    choices: [
      `Une fraction majoritaire quiescente.`,
      `Une fraction minoritaire en prolifération.`,
      `Une fraction exclusivement apoptotique.`,
      `Des cellules différenciées pouvant exercer la fonction du tissu.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le cours distingue une fraction en quiescence et une fraction en croissance.`,
    choiceExplanations: [
      `Exact. Le cours distingue une fraction en quiescence et une fraction en croissance.`,
      `Exact. Le cours distingue une fraction en quiescence et une fraction en croissance.`,
      `Faux. Le cours distingue une fraction en quiescence et une fraction en croissance.`,
      `Exact. Le cours distingue une fraction en quiescence et une fraction en croissance.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant quelques exemples de renouvellement tissulaire :`,
    choices: [
      `Les entérocytes se renouvellent en 3 à 5 jours.`,
      `Les hépatocytes peuvent se renouveler sur plusieurs mois ou années.`,
      `Les cellules du système nerveux se divisent très fréquemment.`,
      `Certaines cellules se remettent à proliférer après une lésion.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les rythmes de renouvellement sont très variables selon le type cellulaire.`,
    choiceExplanations: [
      `Exact. Les rythmes de renouvellement sont très variables selon le type cellulaire.`,
      `Exact. Les rythmes de renouvellement sont très variables selon le type cellulaire.`,
      `Faux. Les rythmes de renouvellement sont très variables selon le type cellulaire.`,
      `Exact. Les rythmes de renouvellement sont très variables selon le type cellulaire.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un tissu tumoral :`,
    choices: [
      `L’apoptose est souvent limitée.`,
      `La fraction en croissance est augmentée.`,
      `Le cycle cellulaire reste parfaitement contrôlé.`,
      `La prolifération devient rapide et anarchique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le tissu tumoral se caractérise par une perte de l’équilibre prolifération/apoptose.`,
    choiceExplanations: [
      `Exact. Le tissu tumoral se caractérise par une perte de l’équilibre prolifération/apoptose.`,
      `Exact. Le tissu tumoral se caractérise par une perte de l’équilibre prolifération/apoptose.`,
      `Faux. Le tissu tumoral se caractérise par une perte de l’équilibre prolifération/apoptose.`,
      `Exact. Le tissu tumoral se caractérise par une perte de l’équilibre prolifération/apoptose.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les cellules HeLa, MCF7 et A549 citées dans la fiche :`,
    choices: [
      `Sont des lignées tumorales cultivées in vitro.`,
      `Ont des temps de doublement proches de 24 heures.`,
      `Sont toutes issues du même type de cancer.`,
      `Illustrent une prolifération rapide de cellules cancéreuses.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Ces lignées proviennent de cancers différents mais présentent des temps de doublement proches d’une journée.`,
    choiceExplanations: [
      `Exact. Ces lignées proviennent de cancers différents mais présentent des temps de doublement proches d’une journée.`,
      `Exact. Ces lignées proviennent de cancers différents mais présentent des temps de doublement proches d’une journée.`,
      `Faux. Ces lignées proviennent de cancers différents mais présentent des temps de doublement proches d’une journée.`,
      `Exact. Ces lignées proviennent de cancers différents mais présentent des temps de doublement proches d’une journée.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `En culture cellulaire :`,
    choices: [
      `Les cellules en mitose peuvent se décrocher du support.`,
      `Les cellules aplaties sont en interphase.`,
      `Les cellules en mitose sont toujours les plus aplaties.`,
      `Une flasque peut être envahie progressivement par la prolifération et la migration.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L’observation morphologique permet de distinguer grossièrement mitose et interphase.`,
    choiceExplanations: [
      `Exact. L’observation morphologique permet de distinguer grossièrement mitose et interphase.`,
      `Exact. L’observation morphologique permet de distinguer grossièrement mitose et interphase.`,
      `Faux. L’observation morphologique permet de distinguer grossièrement mitose et interphase.`,
      `Exact. L’observation morphologique permet de distinguer grossièrement mitose et interphase.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le cycle cellulaire comprend :`,
    choices: [
      `Une interphase longue.`,
      `Une mitose généralement courte.`,
      `Les phases G1, S et G2 pendant l’interphase.`,
      `Une phase S après la mitose et avant G1.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ordre est G1, S, G2 puis M.`,
    choiceExplanations: [
      `Exact. L’ordre est G1, S, G2 puis M.`,
      `Exact. L’ordre est G1, S, G2 puis M.`,
      `Exact. L’ordre est G1, S, G2 puis M.`,
      `Faux. L’ordre est G1, S, G2 puis M.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la phase G1 :`,
    choices: [
      `Elle est post-mitotique et pré-réplicative.`,
      `La quantité d’ADN est de 2c.`,
      `Chaque chromosome possède deux chromatides.`,
      `La cellule augmente de taille et synthétise protéines et ARN.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `En G1, une cellule diploïde somatique possède 2n chromosomes à une chromatide et 2c d’ADN.`,
    choiceExplanations: [
      `Exact. En G1, une cellule diploïde somatique possède 2n chromosomes à une chromatide et 2c d’ADN.`,
      `Exact. En G1, une cellule diploïde somatique possède 2n chromosomes à une chromatide et 2c d’ADN.`,
      `Faux. En G1, une cellule diploïde somatique possède 2n chromosomes à une chromatide et 2c d’ADN.`,
      `Exact. En G1, une cellule diploïde somatique possède 2n chromosomes à une chromatide et 2c d’ADN.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La phase S :`,
    choices: [
      `Correspond à la réplication de l’ADN.`,
      `Fait passer la quantité d’ADN de 2c à 4c.`,
      `Modifie le nombre de chromosomes de 2n à 4n.`,
      `Fait passer chaque chromosome d’une à deux chromatides.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La réplication double les chromatides et la quantité d’ADN, sans changer le nombre de chromosomes.`,
    choiceExplanations: [
      `Exact. La réplication double les chromatides et la quantité d’ADN, sans changer le nombre de chromosomes.`,
      `Exact. La réplication double les chromatides et la quantité d’ADN, sans changer le nombre de chromosomes.`,
      `Faux. La réplication double les chromatides et la quantité d’ADN, sans changer le nombre de chromosomes.`,
      `Exact. La réplication double les chromatides et la quantité d’ADN, sans changer le nombre de chromosomes.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la phase G2 :`,
    choices: [
      `Elle est post-réplicative et pré-mitotique.`,
      `La quantité d’ADN est de 4c.`,
      `La cellule possède 2n chromosomes à deux chromatides.`,
      `L’ADN est entièrement répliqué.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `G2 prépare la mitose après achèvement de la réplication.`,
    choiceExplanations: [
      `Exact. G2 prépare la mitose après achèvement de la réplication.`,
      `Exact. G2 prépare la mitose après achèvement de la réplication.`,
      `Exact. G2 prépare la mitose après achèvement de la réplication.`,
      `Exact. G2 prépare la mitose après achèvement de la réplication.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En phase G1, une cellule diploïde somatique humaine possède :`,
    choices: [
      `2n chromosomes.`,
      `2c d’ADN.`,
      `Une chromatide par chromosome.`,
      `4c d’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le doublement de l’ADN n’a pas encore eu lieu.`,
    choiceExplanations: [
      `Exact. Le doublement de l’ADN n’a pas encore eu lieu.`,
      `Exact. Le doublement de l’ADN n’a pas encore eu lieu.`,
      `Exact. Le doublement de l’ADN n’a pas encore eu lieu.`,
      `Faux. Le doublement de l’ADN n’a pas encore eu lieu.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Cycle et quantité d’ADN](/images/training/ue14/biologie-cellulaire/cycle-cellulaire/cycle-quantite-adn.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `La quantité d’ADN augmente pendant S.`,
      `Elle reste à 4c pendant G2.`,
      `Elle revient à 2c par cellule fille après la mitose.`,
      `Le nombre de chromosomes passe durablement de 2n à 4n en phase S.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le nombre de chromosomes reste 2n ; c’est le nombre de chromatides et la quantité d’ADN qui doublent.`,
    choiceExplanations: [
      `Exact. Le nombre de chromosomes reste 2n ; c’est le nombre de chromatides et la quantité d’ADN qui doublent.`,
      `Exact. Le nombre de chromosomes reste 2n ; c’est le nombre de chromatides et la quantité d’ADN qui doublent.`,
      `Exact. Le nombre de chromosomes reste 2n ; c’est le nombre de chromatides et la quantité d’ADN qui doublent.`,
      `Faux. Le nombre de chromosomes reste 2n ; c’est le nombre de chromatides et la quantité d’ADN qui doublent.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La phase G0 :`,
    choices: [
      `Est une phase de quiescence hors cycle.`,
      `Peut être atteinte si le point de restriction G1 n’est pas franchi.`,
      `Est obligatoirement irréversible.`,
      `Peut permettre une réparation de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche présente G0 comme une phase parallèle au cycle, pouvant être réversible selon le contexte.`,
    choiceExplanations: [
      `Exact. La fiche présente G0 comme une phase parallèle au cycle, pouvant être réversible selon le contexte.`,
      `Exact. La fiche présente G0 comme une phase parallèle au cycle, pouvant être réversible selon le contexte.`,
      `Faux. La fiche présente G0 comme une phase parallèle au cycle, pouvant être réversible selon le contexte.`,
      `Exact. La fiche présente G0 comme une phase parallèle au cycle, pouvant être réversible selon le contexte.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La phase G1 autorise notamment :`,
    choices: [
      `La réparation de l’ADN.`,
      `Une synthèse importante de protéines et d’ARN.`,
      `Une duplication systématique des chromosomes.`,
      `Une augmentation du volume cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La réplication chromosomique a lieu en phase S, non en G1.`,
    choiceExplanations: [
      `Exact. La réplication chromosomique a lieu en phase S, non en G1.`,
      `Exact. La réplication chromosomique a lieu en phase S, non en G1.`,
      `Faux. La réplication chromosomique a lieu en phase S, non en G1.`,
      `Exact. La réplication chromosomique a lieu en phase S, non en G1.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La phase G2 se caractérise par :`,
    choices: [
      `Un point de contrôle avant la mitose.`,
      `Le début de synthèse de l’appareil mitotique.`,
      `Le début de condensation de l’ADN en fin de phase.`,
      `Une quantité d’ADN de 2c.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Après la réplication, la quantité d’ADN est maintenue à 4c jusqu’à la séparation cellulaire.`,
    choiceExplanations: [
      `Exact. Après la réplication, la quantité d’ADN est maintenue à 4c jusqu’à la séparation cellulaire.`,
      `Exact. Après la réplication, la quantité d’ADN est maintenue à 4c jusqu’à la séparation cellulaire.`,
      `Exact. Après la réplication, la quantité d’ADN est maintenue à 4c jusqu’à la séparation cellulaire.`,
      `Faux. Après la réplication, la quantité d’ADN est maintenue à 4c jusqu’à la séparation cellulaire.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La mitose :`,
    choices: [
      `Termine le cycle cellulaire.`,
      `Conduit à la répartition homogène des chromatides.`,
      `Est généralement beaucoup plus longue que l’interphase.`,
      `Se termine par la division cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Dans un cycle d’environ 24 h, la fiche indique une mitose d’environ 1 h.`,
    choiceExplanations: [
      `Exact. Dans un cycle d’environ 24 h, la fiche indique une mitose d’environ 1 h.`,
      `Exact. Dans un cycle d’environ 24 h, la fiche indique une mitose d’environ 1 h.`,
      `Faux. Dans un cycle d’environ 24 h, la fiche indique une mitose d’environ 1 h.`,
      `Exact. Dans un cycle d’environ 24 h, la fiche indique une mitose d’environ 1 h.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la quantité d’ADN au cours du cycle :`,
    choices: [
      `Elle est fixe à 2c en G1.`,
      `Elle augmente progressivement pendant S.`,
      `Elle est fixe à 4c en G2.`,
      `Elle double une nouvelle fois pendant la mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitose répartit l’ADN répliqué entre deux cellules filles ; elle ne provoque pas une nouvelle réplication.`,
    choiceExplanations: [
      `Exact. La mitose répartit l’ADN répliqué entre deux cellules filles ; elle ne provoque pas une nouvelle réplication.`,
      `Exact. La mitose répartit l’ADN répliqué entre deux cellules filles ; elle ne provoque pas une nouvelle réplication.`,
      `Exact. La mitose répartit l’ADN répliqué entre deux cellules filles ; elle ne provoque pas une nouvelle réplication.`,
      `Faux. La mitose répartit l’ADN répliqué entre deux cellules filles ; elle ne provoque pas une nouvelle réplication.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Une cellule observée avec 2n chromosomes à deux chromatides et 4c d’ADN est le plus probablement en :`,
    choices: [
      `G1.`,
      `G2.`,
      `G0.`,
      `Après cytodiérèse.`,
    ],
    correctChoiceIndexes: [1],
    explanation: `G2 suit la réplication et précède la séparation des chromatides.`,
    choiceExplanations: [
      `Faux. G2 suit la réplication et précède la séparation des chromatides.`,
      `Exact. G2 suit la réplication et précède la séparation des chromatides.`,
      `Faux. G2 suit la réplication et précède la séparation des chromatides.`,
      `Faux. G2 suit la réplication et précède la séparation des chromatides.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Une cellule diploïde contient 2n chromosomes à une chromatide et 2c d’ADN. Elle est compatible avec :`,
    choices: [
      `G1.`,
      `La fin de G2.`,
      `La métaphase.`,
      `La fin de S.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `G1 précède la réplication de l’ADN.`,
    choiceExplanations: [
      `Exact. G1 précède la réplication de l’ADN.`,
      `Faux. G1 précède la réplication de l’ADN.`,
      `Faux. G1 précède la réplication de l’ADN.`,
      `Faux. G1 précède la réplication de l’ADN.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’équilibre d’un tissu sain dépend :`,
    choices: [
      `Du renouvellement des cellules mortes.`,
      `D’une fraction proliférative contrôlée.`,
      `D’une apoptose totalement absente.`,
      `De rythmes de renouvellement adaptés au tissu.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La mort cellulaire programmée fait partie de l’équilibre normal.`,
    choiceExplanations: [
      `Exact. La mort cellulaire programmée fait partie de l’équilibre normal.`,
      `Exact. La mort cellulaire programmée fait partie de l’équilibre normal.`,
      `Faux. La mort cellulaire programmée fait partie de l’équilibre normal.`,
      `Exact. La mort cellulaire programmée fait partie de l’équilibre normal.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une culture de cellules tumorales double en environ 24 heures. Cela est cohérent avec :`,
    choices: [
      `Les exemples HeLa, MCF7 et A549 de la fiche.`,
      `Une fraction en croissance importante.`,
      `Une absence nécessaire de toute apoptose.`,
      `Une perte de contrôle du cycle cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche associe les lignées tumorales à une prolifération rapide, sans affirmer une absence absolue d’apoptose.`,
    choiceExplanations: [
      `Exact. La fiche associe les lignées tumorales à une prolifération rapide, sans affirmer une absence absolue d’apoptose.`,
      `Exact. La fiche associe les lignées tumorales à une prolifération rapide, sans affirmer une absence absolue d’apoptose.`,
      `Faux. La fiche associe les lignées tumorales à une prolifération rapide, sans affirmer une absence absolue d’apoptose.`,
      `Exact. La fiche associe les lignées tumorales à une prolifération rapide, sans affirmer une absence absolue d’apoptose.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule en fin de phase S :`,
    choices: [
      `A répliqué la totalité de son ADN.`,
      `Possède encore 2n chromosomes.`,
      `Possède deux chromatides par chromosome.`,
      `Peut initier une nouvelle réplication immédiatement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La phase S est unique : une nouvelle réplication est interdite après achèvement.`,
    choiceExplanations: [
      `Exact. La phase S est unique : une nouvelle réplication est interdite après achèvement.`,
      `Exact. La phase S est unique : une nouvelle réplication est interdite après achèvement.`,
      `Exact. La phase S est unique : une nouvelle réplication est interdite après achèvement.`,
      `Faux. La phase S est unique : une nouvelle réplication est interdite après achèvement.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La figure suivante présente les phases du cycle, les chromosomes, les chromatides et la quantité d’ADN.

![Cycle et quantité d’ADN](/images/training/ue14/biologie-cellulaire/cycle-cellulaire/cycle-quantite-adn.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `La réplication pendant S.`,
      `Le maintien à 4c pendant G2.`,
      `La répartition de l’ADN pendant M.`,
      `Une variation du nombre chromosomique de 2n à 4n.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure suit surtout la quantité d’ADN et le nombre de chromatides, pas une polyploïdisation.`,
    choiceExplanations: [
      `Exact. La figure suit surtout la quantité d’ADN et le nombre de chromatides, pas une polyploïdisation.`,
      `Exact. La figure suit surtout la quantité d’ADN et le nombre de chromatides, pas une polyploïdisation.`,
      `Exact. La figure suit surtout la quantité d’ADN et le nombre de chromatides, pas une polyploïdisation.`,
      `Faux. La figure suit surtout la quantité d’ADN et le nombre de chromatides, pas une polyploïdisation.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule entre en G0 en G1 précoce. On peut en déduire :`,
    choices: [
      `Elle est sortie du cycle actif.`,
      `Elle n’a pas encore répliqué son ADN.`,
      `Elle possède nécessairement 4c d’ADN.`,
      `Elle peut reprendre le cycle si les conditions redeviennent favorables.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `G0 dérive de G1 et conserve une quantité d’ADN de 2c.`,
    choiceExplanations: [
      `Exact. G0 dérive de G1 et conserve une quantité d’ADN de 2c.`,
      `Exact. G0 dérive de G1 et conserve une quantité d’ADN de 2c.`,
      `Faux. G0 dérive de G1 et conserve une quantité d’ADN de 2c.`,
      `Exact. G0 dérive de G1 et conserve une quantité d’ADN de 2c.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pendant l’interphase :`,
    choices: [
      `L’ADN est globalement décondensé.`,
      `La synthèse d’ARN et de protéines est active.`,
      `La préparation de la mitose s’effectue progressivement.`,
      `Les chromosomes sont constamment sous leur forme métaphasique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La condensation extrême des chromosomes caractérise la mitose.`,
    choiceExplanations: [
      `Exact. La condensation extrême des chromosomes caractérise la mitose.`,
      `Exact. La condensation extrême des chromosomes caractérise la mitose.`,
      `Exact. La condensation extrême des chromosomes caractérise la mitose.`,
      `Faux. La condensation extrême des chromosomes caractérise la mitose.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule arrondie et partiellement décrochée d’une flasque est probablement :`,
    choices: [
      `En mitose.`,
      `En interphase aplatie.`,
      `En division possible.`,
      `Observable dans une culture proliférative.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `La fiche indique que les cellules en cours de division peuvent se décrocher du support.`,
    choiceExplanations: [
      `Exact. La fiche indique que les cellules en cours de division peuvent se décrocher du support.`,
      `Faux. La fiche indique que les cellules en cours de division peuvent se décrocher du support.`,
      `Exact. La fiche indique que les cellules en cours de division peuvent se décrocher du support.`,
      `Exact. La fiche indique que les cellules en cours de division peuvent se décrocher du support.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La distinction chromosome/chromatide implique que :`,
    choices: [
      `Le nombre de chromosomes reste 2n en G2.`,
      `Chaque chromosome possède alors deux chromatides.`,
      `La réplication double le nombre de chromosomes.`,
      `La séparation des chromatides en anaphase conduit à leur répartition entre les cellules filles.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La réplication duplique l’ADN sans doubler durablement le nombre chromosomique.`,
    choiceExplanations: [
      `Exact. La réplication duplique l’ADN sans doubler durablement le nombre chromosomique.`,
      `Exact. La réplication duplique l’ADN sans doubler durablement le nombre chromosomique.`,
      `Faux. La réplication duplique l’ADN sans doubler durablement le nombre chromosomique.`,
      `Exact. La réplication duplique l’ADN sans doubler durablement le nombre chromosomique.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Après cytodiérèse, chaque cellule fille diploïde possède :`,
    choices: [
      `2n chromosomes.`,
      `Une chromatide par chromosome.`,
      `2c d’ADN.`,
      `4c d’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La division répartit les chromatides sœurs en deux cellules filles identiques.`,
    choiceExplanations: [
      `Exact. La division répartit les chromatides sœurs en deux cellules filles identiques.`,
      `Exact. La division répartit les chromatides sœurs en deux cellules filles identiques.`,
      `Exact. La division répartit les chromatides sœurs en deux cellules filles identiques.`,
      `Faux. La division répartit les chromatides sœurs en deux cellules filles identiques.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La phase S est dite unique car :`,
    choices: [
      `L’ADN ne doit être répliqué qu’une seule fois par cycle.`,
      `Une nouvelle réplication est empêchée après son achèvement.`,
      `Elle ne contient aucune synthèse de protéines ou d’ARN.`,
      `Elle assure aussi la duplication du centrosome selon la fiche.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La synthèse de protéines et d’ARN reste active pendant S.`,
    choiceExplanations: [
      `Exact. La synthèse de protéines et d’ARN reste active pendant S.`,
      `Exact. La synthèse de protéines et d’ARN reste active pendant S.`,
      `Faux. La synthèse de protéines et d’ARN reste active pendant S.`,
      `Exact. La synthèse de protéines et d’ARN reste active pendant S.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `Le cycle ordonne croissance, réplication et division.`,
      `La quantité d’ADN et le nombre de chromatides varient de manière coordonnée.`,
      `G0 appartient à la mitose.`,
      `La prolifération tissulaire normale est équilibrée par l’apoptose.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `G0 est une phase de quiescence hors du cycle actif.`,
    choiceExplanations: [
      `Exact. G0 est une phase de quiescence hors du cycle actif.`,
      `Exact. G0 est une phase de quiescence hors du cycle actif.`,
      `Faux. G0 est une phase de quiescence hors du cycle actif.`,
      `Exact. G0 est une phase de quiescence hors du cycle actif.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `renouvellement-et-phases-du-cycle`,
    title: `Renouvellement cellulaire et organisation du cycle`,
    description: `Tissus sains ou tumoraux, interphase, mitose et quiescence.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `g1-s-g2-et-quantite-adn`,
    title: `Phases G1, S et G2`,
    description: `Quantité d’ADN, chromosomes, chromatides et préparation de la division.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `raisonnement-sur-le-deroulement-du-cycle`,
    title: `Raisonnement sur le déroulement du cycle`,
    description: `Applications sur G0, prolifération, réplication et cellules filles.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
