import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_ORDER = 1;

export const SECTION_A_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Définition des osides"],
  2: ["Holosides et hétérosides"],
  3: ["Nomenclature selon le nombre de résidus"],
  4: ["Liaison O-glycosidique"],
  5: ["Condensation des oses"],
  6: ["Diholoside non réducteur"],
  7: ["Diholoside réducteur"],
  8: ["Hydrolyse des osides"],
  9: ["Hydrolyse enzymatique"],
  10: ["Hydrolyse chimique"],
  11: ["Diholosides naturels"],
  12: ["Origine du maltose"],
  13: ["Composition du lactose"],
  14: ["Liaison du lactose"],
  15: ["Pouvoir réducteur du lactose"],
  16: ["Hydrolyse du lactose"],
  17: ["Origine et fermentation du lactose"],
  18: ["Composition du saccharose"],
  19: ["Liaison et pouvoir réducteur du saccharose"],
  20: ["Origine et hydrolyse du saccharose"],
  21: ["Composition du maltose"],
  22: ["Pouvoir réducteur du maltose"],
  23: ["Digestion du maltose"],
  24: ["Comparaison des trois diholosides"],
  25: ["Reconnaissance d’un diholoside non réducteur"],
  26: ["Reconnaissance d’un diholoside réducteur"],
  27: ["Spécificité des glycosidases"],
  28: ["Produits d’hydrolyse du saccharose"],
  29: ["Produits d’hydrolyse comparés"],
  30: ["Synthèse sur les diholosides"],
};

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "liaisons-et-classification-des-osides",
    title: "Liaisons et classification des osides",
    description: "Identifier holosides, hétérosides, condensation et hydrolyse.",
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: "lactose-saccharose-maltose",
    title: "Lactose, saccharose et maltose",
    description: "Comparer la composition, les liaisons, le pouvoir réducteur et l’hydrolyse.",
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: "raisonnement-sur-les-diholosides",
    title: "Raisonnement sur les diholosides",
    description: "Mobiliser les structures et les enzymes dans des situations transversales.",
    stage: 'MASTER',
    sectionOrder: 1,
    items: [
      {
        type: 'GROUP',
        title: "Structures et digestion",
        sharedStatement: "Les questions suivantes comparent les principaux diholosides et leur hydrolyse.",
        questionOrders: [21, 22, 23, 24],
      },
      {
        type: 'GROUP',
        title: "Pouvoir réducteur et spécificité",
        sharedStatement: "Les questions suivantes exploitent les centres anomériques et la spécificité enzymatique.",
        questionOrders: [25, 26, 27],
      },
      {
        type: 'GROUP',
        title: "Produits et synthèse",
        sharedStatement: "Les questions suivantes portent sur les produits d’hydrolyse et la synthèse du thème.",
        questionOrders: [28, 29, 30],
      },
    ],
  },
];

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos des osides :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osides-classification',
    },
    choices: [
      "Ils se caractérisent par la présence d’une liaison O-glycosidique.",
      "Ils correspondent à des assemblages comportant une partie glucidique.",
      "Un oside est nécessairement constitué de deux oses seulement.",
      "La fiche les présente comme des polymères d’oses.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les osides sont caractérisés par une liaison O-glycosidique et correspondent à des assemblages glucidiques de taille variable.",
    choiceExplanations: [
      "Vrai. La liaison O-glycosidique est le caractère structural mis en avant.",
      "Vrai. La partie glucidique est centrale dans la définition.",
      "Faux. Un oside peut contenir deux, trois, quatre ou un grand nombre de résidus.",
      "Vrai. C’est la formulation générale donnée dans la fiche.",
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant la classification des osides :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'osides-classification',
    },
    choices: [
      "Un holoside ne contient que des oses.",
      "Un hétéroside associe un ose à une partie non glucidique.",
      "La partie non glucidique d’un hétéroside est appelée aglycone.",
      "Un hétéroside est obligatoirement un diholoside.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les holosides ne contiennent que des résidus glucidiques, tandis que les hétérosides associent une partie glucidique à un aglycone.",
    choiceExplanations: [
      "Vrai. Le substituant relié à l’ose est lui-même un ose.",
      "Vrai. Il existe une partie glucidique et une partie non glucidique.",
      "Vrai. La fiche emploie le terme aglycone.",
      "Faux. Les deux catégories reposent sur la nature des constituants, pas sur le nombre de résidus.",
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les correspondances suivantes :",
    choices: [
      "Deux oses forment un diholoside.",
      "Trois oses forment un triholoside.",
      "Quatre oses forment un tétraholoside.",
      "Un diholoside contient quatre résidus d’ose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La nomenclature des petits holosides dépend du nombre de résidus d’ose.",
    choiceExplanations: [
      "Vrai. Le préfixe di- indique deux résidus.",
      "Vrai. Le préfixe tri- indique trois résidus.",
      "Vrai. Le préfixe tétra- indique quatre résidus.",
      "Faux. Un diholoside en contient deux.",
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Une liaison O-glycosidique :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycosidic-condensation',
    },
    choices: [
      "Intervient dans la constitution des osides.",
      "Relie des résidus par l’intermédiaire d’un atome d’oxygène.",
      "Est toujours résistante à toute hydrolyse.",
      "Peut être clivée par des glycosidases.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La liaison O-glycosidique constitue les osides et peut être hydrolysée, notamment par des enzymes spécifiques.",
    choiceExplanations: [
      "Vrai. C’est le lien caractéristique des osides.",
      "Vrai. Le préfixe O- renvoie à l’atome d’oxygène impliqué.",
      "Faux. La fiche la décrit comme facilement clivable.",
      "Vrai. Les osidases ou glycosidases catalysent cette hydrolyse.",
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La formation d’un diholoside par condensation :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycosidic-condensation',
    },
    choices: [
      "S’accompagne d’une perte d’eau.",
      "Peut impliquer deux fonctions hémiacétaliques.",
      "Peut impliquer une fonction hémiacétalique et une fonction alcool.",
      "Correspond nécessairement à une réaction d’hydrolyse.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Deux modes de condensation sont décrits, tous deux avec perte d’eau.",
    choiceExplanations: [
      "Vrai. La condensation libère une molécule d’eau.",
      "Vrai. Ce cas conduit à un diholoside non réducteur.",
      "Vrai. Ce cas laisse une fonction hémiacétalique libre.",
      "Faux. L’hydrolyse est la réaction inverse.",
    ],
  },
  {
    order: 6,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un diholoside obtenu par réaction entre les deux fonctions hémiacétaliques réductrices :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycosidic-condensation',
    },
    choices: [
      "Ne conserve aucune fonction hémiacétalique libre.",
      "Est qualifié de non réducteur.",
      "Possède obligatoirement deux anomères interconvertibles.",
      "Résulte d’une condensation avec perte d’eau.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Lorsque les deux fonctions hémiacétaliques participent à la liaison, aucune ne reste disponible : le diholoside est non réducteur.",
    choiceExplanations: [
      "Vrai. Les deux centres réducteurs sont engagés.",
      "Vrai. C’est la conséquence structurale indiquée.",
      "Faux. L’absence de fonction hémiacétalique libre empêche l’anomérie réductrice décrite pour le lactose ou le maltose.",
      "Vrai. Il s’agit d’une condensation.",
    ],
  },
  {
    order: 7,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un diholoside formé entre une fonction hémiacétalique et une fonction alcool :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycosidic-condensation',
    },
    choices: [
      "Conserve une fonction hémiacétalique libre.",
      "Peut être réducteur.",
      "Est nécessairement le saccharose.",
      "Résulte d’une perte d’eau.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La fonction hémiacétalique restante confère le caractère réducteur.",
    choiceExplanations: [
      "Vrai. Une seule fonction hémiacétalique est engagée.",
      "Vrai. La fonction restante explique le pouvoir réducteur.",
      "Faux. Le saccharose engage les deux fonctions hémiacétaliques.",
      "Vrai. La liaison se forme par condensation.",
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos de l’hydrolyse d’un diholoside :",
    choices: [
      "Elle rompt la liaison glycosidique.",
      "Les molécules obtenues sont appelées résidus.",
      "Elle ajoute les éléments d’une molécule d’eau.",
      "Elle transforme toujours le diholoside en un polyoside.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’hydrolyse clive la liaison glycosidique et libère les résidus constitutifs.",
    choiceExplanations: [
      "Vrai. C’est le principe de l’hydrolyse.",
      "Vrai. La fiche emploie ce vocabulaire.",
      "Vrai. L’eau intervient dans la rupture de la liaison.",
      "Faux. Elle réduit au contraire le degré de polymérisation.",
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’hydrolyse enzymatique des osides :",
    choices: [
      "Est réalisée par des osidases ou glycosidases.",
      "Est très spécifique.",
      "Peut dépendre de l’anomérie de la liaison.",
      "Nécessite toujours un pH acide à 60 °C pendant une heure.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les glycosidases sont spécifiques, parfois jusque dans la reconnaissance de l’anomère.",
    choiceExplanations: [
      "Vrai. Ce sont les enzymes citées.",
      "Vrai. La spécificité enzymatique est soulignée.",
      "Vrai. Certaines enzymes sont anomère-spécifiques.",
      "Faux. Ces conditions concernent l’hydrolyse chimique décrite.",
    ],
  },
  {
    order: 10,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Selon la fiche, l’hydrolyse chimique d’un oside :",
    choices: [
      "Est peu spécifique.",
      "Peut être réalisée en milieu acide.",
      "Est décrite à 60 °C pendant environ une heure.",
      "Est plus spécifique qu’une hydrolyse enzymatique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’hydrolyse chimique acide est peu spécifique, contrairement à l’hydrolyse enzymatique.",
    choiceExplanations: [
      "Vrai. Le clivage chimique n’est pas ciblé.",
      "Vrai. Le pH acide est précisé.",
      "Vrai. Ce sont les conditions mentionnées.",
      "Faux. La spécificité est au contraire l’avantage de l’enzyme.",
    ],
  },
  {
    order: 11,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les diholosides retrouvés à l’état libre dans la nature selon la fiche :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Le saccharose.",
      "Le lactose.",
      "Le tréhalose.",
      "Le maltose est présenté comme le seul diholoside libre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La fiche cite le saccharose, le lactose et le tréhalose à l’état libre ; le maltose est surtout issu d’hydrolyses.",
    choiceExplanations: [
      "Vrai. Il est présent notamment dans les végétaux.",
      "Vrai. Il est présent dans le lait des mammifères.",
      "Vrai. Il figure dans la liste donnée.",
      "Faux. Le maltose est peu présent à l’état libre.",
    ],
  },
  {
    order: 12,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le maltose :",
    choices: [
      "Peut résulter de l’hydrolyse de l’amidon.",
      "Peut résulter de l’hydrolyse du glycogène.",
      "Est très abondant à l’état libre.",
      "Est retrouvé dans le malt.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le maltose est peu présent à l’état libre mais apparaît lors de l’hydrolyse de polyosides et se rencontre dans le malt.",
    choiceExplanations: [
      "Vrai. L’amylase libère notamment du maltose.",
      "Vrai. Le glycogène peut également en fournir.",
      "Faux. La fiche précise qu’il est peu présent à l’état libre.",
      "Vrai. Le malt correspond à une pousse germée de seigle ou d’orge.",
    ],
  },
  {
    order: 13,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le lactose associe :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Un résidu de galactose.",
      "Un résidu de glucose.",
      "Un résidu de fructose.",
      "Deux résidus de glucose uniquement.",
    ],
    correctChoiceIndexes: [0, 1],
    explanation: "Le lactose est constitué de galactose et de glucose.",
    choiceExplanations: [
      "Vrai. Le galactose est le premier ose du lactose.",
      "Vrai. Le glucose est le second ose.",
      "Faux. Le fructose entre dans le saccharose.",
      "Faux. Cette composition correspond au maltose.",
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La liaison caractéristique du lactose est :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Une liaison β(1→4) osidique.",
      "Une liaison entre le galactose et le glucose.",
      "Une liaison α(1→2) entre glucose et fructose.",
      "Compatible avec une fonction hémiacétalique restante.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le lactose est un β-D-galactosyl-(1→4)-D-glucose et conserve un carbone anomérique libre.",
    choiceExplanations: [
      "Vrai. La fiche indique une liaison β1,4.",
      "Vrai. Elle unit les deux résidus du lactose.",
      "Faux. Cette liaison caractérise le saccharose.",
      "Vrai. Cela explique son caractère réducteur.",
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Concernant le lactose :",
    choices: [
      "Il possède deux anomères possibles.",
      "Ses deux anomères sont réducteurs.",
      "Il ne possède aucune fonction hémiacétalique libre.",
      "Son caractère réducteur est lié au glucose terminal libre.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le lactose conserve le carbone anomérique du glucose libre ; ses deux anomères sont donc réducteurs.",
    choiceExplanations: [
      "Vrai. Le centre anomérique libre peut adopter deux configurations.",
      "Vrai. La fiche le précise explicitement.",
      "Faux. Une fonction hémiacétalique reste libre.",
      "Vrai. C’est le résidu de glucose qui porte ce centre.",
    ],
  },
  {
    order: 16,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’hydrolyse digestive du lactose :",
    choices: [
      "Est assurée par la lactase.",
      "Peut être décrite comme une activité β-galactosidase.",
      "Libère du glucose et du galactose.",
      "Libère exclusivement du fructose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La lactase, ou β-galactosidase, hydrolyse le lactose en glucose et galactose.",
    choiceExplanations: [
      "Vrai. C’est l’enzyme intestinale citée.",
      "Vrai. Les deux appellations sont données.",
      "Vrai. Ce sont les deux résidus constitutifs.",
      "Faux. Le fructose provient du saccharose.",
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos du lactose :",
    choices: [
      "Il provient du lait des mammifères.",
      "La fiche indique environ 50 g/L dans le lait.",
      "Les lactobacilles peuvent le transformer en acide lactique lors de la fermentation fromagère.",
      "Il est décrit comme insoluble dans l’eau.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le lactose est un sucre du lait, soluble, pouvant être fermenté en acide lactique.",
    choiceExplanations: [
      "Vrai. C’est son origine naturelle principale.",
      "Vrai. Cette concentration est donnée.",
      "Vrai. La fermentation fromagère est citée.",
      "Faux. La fiche le décrit comme soluble.",
    ],
  },
  {
    order: 18,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le saccharose associe :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Un résidu de glucose.",
      "Un résidu de fructose.",
      "Deux résidus de galactose.",
      "Des formes α-D-glucose et β-D-fructose dans la représentation donnée.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le saccharose est constitué d’α-D-glucose et de β-D-fructose.",
    choiceExplanations: [
      "Vrai. Le glucose participe à la liaison.",
      "Vrai. Le fructose constitue l’autre résidu.",
      "Faux. Cette composition n’est pas celle du saccharose.",
      "Vrai. Ce sont les configurations indiquées dans la fiche.",
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le saccharose :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Possède une liaison osidique entre C1 du glucose et C2 du fructose.",
      "Engage les deux fonctions hémiacétaliques.",
      "Est non réducteur.",
      "Possède nécessairement deux anomères réducteurs.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le saccharose engage les deux carbones anomériques dans une liaison (1→2) et est non réducteur.",
    choiceExplanations: [
      "Vrai. C’est la liaison décrite.",
      "Vrai. Aucun centre hémiacétalique ne reste libre.",
      "Vrai. C’est la conséquence de cette structure.",
      "Faux. Cette propriété concerne le lactose.",
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos du saccharose :",
    choices: [
      "Il est le sucre de table.",
      "Il provient notamment de la betterave et de la canne à sucre.",
      "Il est hydrolysé dans l’intestin par des saccharases.",
      "Son hydrolyse ne produit que du galactose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le saccharose végétal est hydrolysé en glucose et fructose par des activités saccharasiques.",
    choiceExplanations: [
      "Vrai. C’est son usage courant.",
      "Vrai. Ces végétaux sont cités.",
      "Vrai. β-fructosidase et α-glucosidase sont mentionnées.",
      "Faux. Les produits sont glucose et fructose.",
    ],
  },
  {
    order: 21,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le maltose est constitué :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "De deux résidus de glucose.",
      "De deux formes α-D-glucose dans la représentation donnée.",
      "D’un résidu de galactose et d’un résidu de fructose.",
      "D’une liaison α(1→4).",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le maltose associe deux glucoses par une liaison α(1→4).",
    choiceExplanations: [
      "Vrai. C’est un diglucoside.",
      "Vrai. La fiche le présente ainsi.",
      "Faux. Aucun de ces deux oses n’entre dans le maltose.",
      "Vrai. C’est la liaison caractéristique.",
    ],
  },
  {
    order: 22,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le maltose :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Est un diholoside réducteur.",
      "Conserve une fonction hémiacétalique libre.",
      "Est non réducteur comme le saccharose.",
      "Peut présenter une anomérie au niveau du glucose libre.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Une seule fonction anomérique participe à la liaison α(1→4), laissant l’autre libre.",
    choiceExplanations: [
      "Vrai. La fiche le qualifie de réducteur.",
      "Vrai. C’est la base structurale du pouvoir réducteur.",
      "Faux. Le saccharose engage les deux centres anomériques.",
      "Vrai. Le centre libre peut changer de configuration.",
    ],
  },
  {
    order: 23,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Lors de la digestion :",
    choices: [
      "Le maltose peut être produit à partir de l’amidon par l’amylase.",
      "La maltase hydrolyse le maltose.",
      "L’hydrolyse du maltose fournit deux résidus de glucose.",
      "La lactase est l’enzyme spécifique du maltose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le maltose est un intermédiaire de digestion des polyosides puis est hydrolysé en deux glucoses par la maltase.",
    choiceExplanations: [
      "Vrai. C’est une étape indiquée.",
      "Vrai. C’est l’enzyme intestinale citée.",
      "Vrai. Les deux unités sont des glucoses.",
      "Faux. La lactase agit sur le lactose.",
    ],
  },
  {
    order: 24,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer lactose, saccharose et maltose permet d’affirmer que :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Le lactose et le maltose sont réducteurs.",
      "Le saccharose est non réducteur.",
      "Le lactose et le maltose possèdent tous deux une liaison (1→4).",
      "Les trois contiennent du fructose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le lactose et le maltose gardent un centre anomérique libre ; le saccharose engage les deux.",
    choiceExplanations: [
      "Vrai. Ils conservent une fonction hémiacétalique.",
      "Vrai. Les deux centres anomériques y sont engagés.",
      "Vrai. β1,4 pour le lactose et α1,4 pour le maltose.",
      "Faux. Seul le saccharose contient du fructose.",
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un diholoside dont les deux carbones anomériques participent à la liaison :",
    choices: [
      "Est attendu non réducteur.",
      "Ne conserve pas de fonction hémiacétalique libre.",
      "Correspond au modèle structural du saccharose.",
      "Doit obligatoirement être le lactose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’engagement des deux centres anomériques définit un diholoside non réducteur, illustré par le saccharose.",
    choiceExplanations: [
      "Vrai. Aucun centre réducteur n’est disponible.",
      "Vrai. C’est la conséquence directe.",
      "Vrai. Le saccharose illustre ce cas.",
      "Faux. Le lactose n’engage qu’un centre anomérique.",
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "La présence d’un carbone anomérique libre dans un diholoside :",
    choices: [
      "Permet l’existence d’anomères.",
      "Est compatible avec un pouvoir réducteur.",
      "Est observée pour le lactose et le maltose.",
      "Est caractéristique du saccharose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Un centre anomérique libre explique l’anomérie et le caractère réducteur du lactose et du maltose.",
    choiceExplanations: [
      "Vrai. Il peut adopter les configurations α ou β.",
      "Vrai. La fonction hémiacétalique peut s’ouvrir.",
      "Vrai. Ces deux diholosides sont réducteurs.",
      "Faux. Les deux centres du saccharose sont engagés.",
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une glycosidase anomère-spécifique :",
    choices: [
      "Peut distinguer une liaison α d’une liaison β.",
      "Hydrolyse indifféremment toutes les liaisons osidiques.",
      "Illustre la forte spécificité de l’hydrolyse enzymatique.",
      "Est moins spécifique qu’un traitement acide.",
    ],
    correctChoiceIndexes: [0, 2],
    explanation: "La spécificité enzymatique peut porter sur l’anomérie de la liaison.",
    choiceExplanations: [
      "Vrai. C’est précisément le sens de l’anomère-spécificité.",
      "Faux. Une enzyme spécifique ne clive pas toutes les liaisons.",
      "Vrai. La fiche souligne cette propriété.",
      "Faux. L’hydrolyse acide est peu spécifique.",
    ],
  },
  {
    order: 28,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Après hydrolyse complète du saccharose, on obtient :",
    choices: [
      "Du glucose.",
      "Du fructose.",
      "Du galactose uniquement.",
      "Deux résidus de nature différente.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le saccharose libère un glucose et un fructose.",
    choiceExplanations: [
      "Vrai. Il s’agit de l’un des constituants.",
      "Vrai. Il s’agit de l’autre constituant.",
      "Faux. Le galactose appartient au lactose.",
      "Vrai. Le saccharose est un hétérodiholoside.",
    ],
  },
  {
    order: 29,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos des produits d’hydrolyse :",
    choices: [
      "Le lactose fournit glucose et galactose.",
      "Le maltose fournit deux glucoses.",
      "Le saccharose fournit glucose et fructose.",
      "Les trois diholosides fournissent exactement les mêmes résidus.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La composition des trois diholosides permet de prévoir leurs produits d’hydrolyse.",
    choiceExplanations: [
      "Vrai. Ce sont ses deux constituants.",
      "Vrai. Le maltose est un diglucoside.",
      "Vrai. Ce sont ses deux constituants.",
      "Faux. Leurs compositions diffèrent.",
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une synthèse correcte du cours sur les diholosides comprend :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'lactose-saccharose-maltose',
    },
    choices: [
      "Le saccharose est non réducteur.",
      "Le lactose est hydrolysé par une β-galactosidase.",
      "Le maltose possède une liaison α(1→4).",
      "Toute hydrolyse chimique est plus spécifique qu’une hydrolyse enzymatique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les structures et enzymes permettent de distinguer les trois diholosides principaux.",
    choiceExplanations: [
      "Vrai. Ses deux centres anomériques sont engagés.",
      "Vrai. Lactase et β-galactosidase sont synonymes ici.",
      "Vrai. C’est sa liaison caractéristique.",
      "Faux. L’hydrolyse enzymatique est la plus spécifique.",
    ],
  },
];
