import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_ORDER = 4;

export const SECTION_D_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  91: ["Estérification correspond ici à"],
  92: ["Ose phosphorylé"],
  93: ["À partir du glucose, des esters phosphoriques peuvent être formés"],
  94: ["L’ester phosphorique du glucose particulièrement impliqué dans…"],
  95: ["Fructose peut être phosphorylé"],
  96: ["Fructose phosphorylé en C1 et en C6 est appelé"],
  97: ["Fructose phosphorylé en C2 et en C6 est appelé"],
  98: ["Pour la synthèse des acides nucléiques"],
  99: ["Phosphate du ribose-5-phosphate est porté par"],
  100: ["Les esters sulfuriques d’oses"],
  101: ["Charge négative d’un GAG sulfaté est notamment due"],
  102: ["L’acide ascorbique"],
  103: ["Streptomycine est citée comme"],
  104: ["Comparer phosphorylation et sulfatation d’un ose"],
  105: ["Terme « bisphosphate » indique"],
  106: ["Glucose-1-phosphate et glucose-6-phosphate"],
  107: ["Fructose-1,6-bisphosphate et fructose-2,6-bisphosphate"],
  108: ["Glucose-6-phosphate"],
  109: ["Pentose phosphorylé en C5 peut participer"],
  110: ["Les charges négatives des dérivés d’oses peuvent provenir"],
  111: ["Figure des oses phosphorylés permet d’identifier"],
  112: ["À partir de la figure des GAG sulfatés"],
  113: ["Métabolite nommé fructose-1,6-bisphosphate"],
  114: ["Un nucléotide de l’ARN, le sucre est cohérent avec"],
  115: ["L’acide ascorbique et la streptomycine illustrent"],
  116: ["Pour distinguer un ose phosphorylé d’un ose sulfaté"],
  117: ["Molécule porte deux phosphates en C2 et C6 sur une charpente d…"],
  118: ["GAG fortement sulfaté"],
  119: ["Phosphorylation d’un ose peut"],
  120: ["Synthèse des oses estérifiés et autres dérivés"],
};

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "oses-phosphoryles",
    title: "Oses phosphorylés",
    description: "Reconnaître les principaux esters phosphoriques du glucose, fructose et ribose.",
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 2,
    slug: "sulfates-autres-derives",
    title: "Oses sulfatés et autres dérivés",
    description: "Relier sulfatation, charge négative, vitamine C et streptomycine.",
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 3,
    slug: "esters-oses-metabolisme",
    title: "Esters d’oses et fonctions biologiques",
    description: "Analyser la nomenclature, les charges et les rôles métaboliques des oses estérifiés.",
    stage: 'MASTER',
    sectionOrder: 4,
    items: [
      {
        type: 'GROUP',
        title: "Lecture de figures",
        sharedStatement: "Les questions suivantes utilisent les schémas des oses phosphorylés et des GAG sulfatés.",
        questionOrders: [111, 112],
      },
      {
        type: 'GROUP',
        title: "Métabolites phosphorylés",
        sharedStatement: "Les noms des métabolites indiquent les positions des groupements phosphate.",
        questionOrders: [113, 114],
      },
      {
        type: 'GROUP',
        title: "Diversité des dérivés",
        sharedStatement: "Les questions suivantes relient estérification, charge et fonctions biologiques.",
        questionOrders: [115, 116, 117, 118, 119, 120],
      },
    ],
  },
];

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Une estérification correspond ici à :",
    choices: [
      "La fixation d’un acide sur une fonction alcool.",
      "La réduction d’un carbonyle en alcool.",
      "Le remplacement d’un OH par NH2.",
      "La formation d’une liaison peptidique.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Les oses estérifiés résultent de la réaction d’un OH avec un acide, notamment phosphorique ou sulfurique.",
    choiceExplanations: [
      "C’est la définition retenue.",
      "Cette réaction produit un polyol.",
      "Cette transformation produit une osamine.",
      "Elle concerne acide carboxylique et amine des acides aminés.",
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Un ose phosphorylé :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Est un ester phosphorique.",
      "Porte un groupement phosphate sur une fonction alcool.",
      "Peut constituer un intermédiaire métabolique.",
      "Est obligatoirement un polyol sans carbonyle.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La phosphorylation des OH des oses produit des esters phosphoriques centraux dans le métabolisme.",
    choiceExplanations: [
      "Vrai. L’acide phosphorique est l’acide estérifiant.",
      "Vrai. Le phosphate remplace l’hydrogène d’un OH.",
      "Vrai. La glycolyse en fournit plusieurs exemples.",
      "Faux. La phosphorylation ne définit pas un polyol.",
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À partir du glucose, des esters phosphoriques peuvent être formés :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "En C1.",
      "En C6.",
      "Notamment sous forme de glucose-6-phosphate.",
      "Uniquement sur une fonction amine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glucose peut être phosphorylé sur ses fonctions alcool, notamment en C1 ou C6.",
    choiceExplanations: [
      "Vrai. Le glucose-1-phosphate existe.",
      "Vrai. Le glucose-6-phosphate est majeur.",
      "Vrai. Il intervient dans le métabolisme glucidique.",
      "Faux. Le glucose ne nécessite pas d’amine pour être phosphorylé.",
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "L’ester phosphorique du glucose particulièrement impliqué dans la glycolyse est :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Glucose-6-phosphate.",
      "Glucose-6-sulfate.",
      "Sorbitol.",
      "Acide glucuronique.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Le glucose-6-phosphate constitue une forme phosphorylée centrale de la glycolyse.",
    choiceExplanations: [
      "C’est le métabolite attendu.",
      "Le sulfate n’est pas le groupement de la glycolyse évoqué.",
      "Le sorbitol est un polyol.",
      "L’acide glucuronique est un produit d’oxydation.",
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le fructose peut être phosphorylé :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "En C1.",
      "En C6.",
      "Simultanément en C1 et C6.",
      "Simultanément en C2 et C6.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "La fiche cite plusieurs positions et combinaisons de phosphorylation du fructose.",
    choiceExplanations: [
      "Vrai. Le fructose-1-phosphate existe.",
      "Vrai. Le fructose-6-phosphate existe.",
      "Vrai. Cela donne le fructose-1,6-bisphosphate.",
      "Vrai. Cela donne le fructose-2,6-bisphosphate.",
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Un fructose phosphorylé en C1 et en C6 est appelé :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Fructose-1,6-bisphosphate.",
      "Fructose-1-phosphate seulement.",
      "Glucose-6-phosphate.",
      "Fructose-2,6-bisphosphate.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Deux phosphates portés en C1 et C6 donnent le fructose-1,6-bisphosphate.",
    choiceExplanations: [
      "C’est la nomenclature correcte.",
      "Cette appellation ne mentionne qu’un phosphate.",
      "Il s’agit d’un autre ose.",
      "Les positions sont C2 et C6 dans ce composé.",
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Un fructose phosphorylé en C2 et en C6 est appelé :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Fructose-2,6-bisphosphate.",
      "Fructose-1,6-bisphosphate.",
      "Ribose-5-phosphate.",
      "Mannitol.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Les indices indiquent les deux carbones portant les phosphates.",
    choiceExplanations: [
      "C’est la nomenclature correcte.",
      "Les positions seraient C1 et C6.",
      "Il s’agit d’un pentose phosphorylé.",
      "Le mannitol est un polyol.",
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Pour la synthèse des acides nucléiques :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Le ribose peut être phosphorylé en C5.",
      "Le 2-désoxyribose peut être phosphorylé en C5.",
      "Le ribose-5-phosphate est associé aux constituants de l’ARN.",
      "Le 2-désoxyribose-5-phosphate est associé aux constituants de l’ADN.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "La phosphorylation en C5 prépare les pentoses à leur incorporation dans les nucléotides.",
    choiceExplanations: [
      "Vrai. C5 porte l’alcool primaire.",
      "Vrai. Le même principe s’applique au désoxyribose.",
      "Vrai. Le ribose appartient à l’ARN.",
      "Vrai. Le désoxyribose appartient à l’ADN.",
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Le phosphate du ribose-5-phosphate est porté par :",
    choices: [
      "C1.",
      "C2.",
      "C5.",
      "C6.",
    ],
    correctChoiceIndexes: [2],
    explanation: "Le nom du composé indique une phosphorylation sur le carbone 5.",
    choiceExplanations: [
      "Le nom serait ribose-1-phosphate.",
      "Le nom serait ribose-2-phosphate.",
      "C’est la position indiquée.",
      "Le ribose ne possède que cinq carbones.",
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les esters sulfuriques d’oses :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'sulfated-gag-charge',
    },
    choices: [
      "Se rencontrent dans des glycosaminoglycanes sulfatés.",
      "Contribuent à une charge négative.",
      "Ajoutent des groupements sulfate.",
      "Sont identiques à des esters phosphoriques.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La sulfatation des GAG apporte des charges négatives distinctes des phosphates.",
    choiceExplanations: [
      "Vrai. C’est leur localisation classique.",
      "Vrai. Les sulfates sont anioniques.",
      "Vrai. Il s’agit de la modification chimique.",
      "Faux. Sulfate et phosphate sont des groupements différents.",
    ],
  },
  {
    order: 101,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La charge négative d’un GAG sulfaté est notamment due :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'sulfated-gag-charge',
    },
    choices: [
      "Aux groupements sulfate.",
      "À des méthyles neutres uniquement.",
      "À l’absence d’oxygène.",
      "À des liaisons peptidiques seules.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Les sulfates ionisés contribuent fortement à la charge négative des GAG.",
    choiceExplanations: [
      "C’est l’origine attendue.",
      "Les méthyles ne portent pas cette charge.",
      "Les sulfates contiennent de l’oxygène.",
      "Les GAG sont des glucides, non des chaînes peptidiques.",
    ],
  },
  {
    order: 102,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’acide ascorbique :",
    choices: [
      "Est mieux connu sous le nom de vitamine C.",
      "Dérive initialement du L-gulose selon la fiche.",
      "Subit plusieurs transformations structurales au cours de sa formation.",
      "Doit être reconnu par cœur à partir de sa formule chimique dans ce chapitre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La vitamine C est citée comme dérivé glucidique issu du L-gulose, sans exigence de mémoriser sa formule.",
    choiceExplanations: [
      "Vrai. C’est son nom usuel.",
      "Vrai. Le L-gulose est le précurseur indiqué.",
      "Vrai. Doubles liaisons et cyclisations sont évoquées.",
      "Faux. La fiche précise de ne pas connaître la formule.",
    ],
  },
  {
    order: 103,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La streptomycine est citée comme :",
    choices: [
      "Un antibiotique.",
      "Un polyol alimentaire.",
      "Un acide uronique.",
      "Un ester de cholestérol.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La streptomycine constitue un exemple de dérivé glucidique à activité antibiotique.",
    choiceExplanations: [
      "C’est l’exemple donné.",
      "Ce n’est pas son rôle.",
      "Elle n’est pas classée comme acide uronique.",
      "Elle ne correspond pas à un stéride.",
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer phosphorylation et sulfatation d’un ose :",
    choices: [
      "Les deux sont des estérifications de fonctions alcool.",
      "La première ajoute un phosphate.",
      "La seconde ajoute un sulfate.",
      "Les deux groupements sont chimiquement identiques.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux modifications sont analogues comme estérifications mais impliquent des acides différents.",
    choiceExplanations: [
      "Vrai. Elles portent sur des OH de l’ose.",
      "Vrai. L’acide phosphorique intervient.",
      "Vrai. L’acide sulfurique fournit le sulfate.",
      "Faux. Phosphore et soufre distinguent les deux groupements.",
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le terme « bisphosphate » indique :",
    choices: [
      "Deux groupements phosphate distincts.",
      "Deux positions précisées dans le nom.",
      "Par exemple C1 et C6 pour le fructose-1,6-bisphosphate.",
      "Une seule molécule de phosphate cyclique obligatoire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Bisphosphate décrit deux esters phosphoriques portés par deux positions de l’ose.",
    choiceExplanations: [
      "Vrai. Deux phosphates sont présents.",
      "Vrai. Les indices les localisent.",
      "Vrai. C’est l’exemple majeur.",
      "Faux. Le terme ne signifie pas un phosphate cyclique unique.",
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Glucose-1-phosphate et glucose-6-phosphate :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Sont des isomères de position.",
      "Diffèrent par le carbone phosphorylé.",
      "Conservent la même charpente de glucose.",
      "Sont respectivement un acide aminé et une protéine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Ces molécules diffèrent par la position du phosphate sur le même ose.",
    choiceExplanations: [
      "Vrai. Le groupement change de position.",
      "Vrai. C1 ou C6 est concerné.",
      "Vrai. La charpente carbonée reste celle du glucose.",
      "Faux. Ce sont des dérivés glucidiques.",
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Fructose-1,6-bisphosphate et fructose-2,6-bisphosphate :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Portent chacun deux phosphates.",
      "Diffèrent par une position de phosphorylation.",
      "Sont deux dérivés du fructose.",
      "Sont des polyols issus de réduction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux composés sont des bisphosphates du fructose mais avec des localisations distinctes.",
    choiceExplanations: [
      "Vrai. Le préfixe bis l’indique.",
      "Vrai. C1 ou C2 diffère, C6 étant commun.",
      "Vrai. Leur squelette est celui du fructose.",
      "Faux. Ils résultent d’estérifications phosphoriques.",
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le glucose-6-phosphate :",
    choices: [
      "Est phosphorylé sur l’alcool de C6.",
      "Intervient dans la glycolyse.",
      "Est plus chargé que le glucose non phosphorylé.",
      "Est identique au sorbitol.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’ajout d’un phosphate en C6 produit un métabolite chargé et central.",
    choiceExplanations: [
      "Vrai. Le nom indique la position.",
      "Vrai. C’est son contexte métabolique.",
      "Vrai. Le phosphate est ionisé en milieu biologique.",
      "Faux. Le sorbitol est un polyol non phosphorylé.",
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un pentose phosphorylé en C5 peut participer :",
    choices: [
      "À la formation de nucléotides.",
      "À la constitution des acides nucléiques.",
      "Sous forme de ribose-5-phosphate pour l’ARN.",
      "Uniquement à la synthèse des triglycérides.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les pentoses phosphorylés sont des précurseurs des nucléotides et des acides nucléiques.",
    choiceExplanations: [
      "Vrai. Le phosphate fait partie du squelette nucléotidique.",
      "Vrai. ARN et ADN contiennent un pentose.",
      "Vrai. C’est l’association citée.",
      "Faux. Leur rôle principal ici concerne les acides nucléiques.",
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les charges négatives des dérivés d’oses peuvent provenir :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'sulfated-gag-charge',
    },
    choices: [
      "D’un phosphate ionisé.",
      "D’un sulfate ionisé.",
      "D’un carboxylate comme COO−.",
      "Uniquement d’une amine protonée NH3+.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Phosphates, sulfates et carboxylates sont des sources fréquentes de charges négatives.",
    choiceExplanations: [
      "Vrai. Les esters phosphoriques sont anioniques.",
      "Vrai. Les sulfates le sont également.",
      "Vrai. Le glucuronate ou le NANA en sont des exemples.",
      "Faux. NH3+ porte une charge positive.",
    ],
  },
  {
    order: 111,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La figure des oses phosphorylés permet d’identifier :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Le glucose-6-phosphate.",
      "Le fructose-1,6-bisphosphate.",
      "Le ribose-5-phosphate.",
      "Uniquement des oses sans charge.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La figure rassemble plusieurs esters phosphoriques biologiquement importants.",
    choiceExplanations: [
      "Vrai. Le phosphate est en C6.",
      "Vrai. Deux positions sont occupées.",
      "Vrai. Le pentose est phosphorylé en C5.",
      "Faux. Les phosphates sont ionisables et chargés.",
    ],
  },
  {
    order: 112,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À partir de la figure des GAG sulfatés :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'sulfated-gag-charge',
    },
    choices: [
      "Les sulfates contribuent à la charge négative.",
      "Les carboxylates peuvent également contribuer à cette charge.",
      "La répulsion électrostatique peut influencer la conformation.",
      "Les groupements représentés sont tous positifs.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les GAG cumulent souvent sulfates et carboxylates, à l’origine d’une forte densité de charge négative.",
    choiceExplanations: [
      "Vrai. SO3− est anionique.",
      "Vrai. COO− est également anionique.",
      "Vrai. Les charges de même signe se repoussent.",
      "Faux. Les motifs indiqués sont négatifs.",
    ],
  },
  {
    order: 113,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un métabolite nommé fructose-1,6-bisphosphate :",
    choices: [
      "Dérive du fructose.",
      "Porte un phosphate en C1.",
      "Porte un phosphate en C6.",
      "Ne porte qu’un seul phosphate.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le nom donne directement l’ose et les deux positions phosphorylées.",
    choiceExplanations: [
      "Vrai. Le radical fructose l’indique.",
      "Vrai. Premier indice.",
      "Vrai. Second indice.",
      "Faux. « Bisphosphate » signifie deux phosphates.",
    ],
  },
  {
    order: 114,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans un nucléotide de l’ARN, le sucre est cohérent avec :",
    choices: [
      "Un ribose.",
      "Une phosphorylation en C5 au stade précurseur.",
      "Une charpente à cinq carbones.",
      "Un glucose-6-phosphate comme sucre définitif.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le ribose-5-phosphate est la base glucidique pertinente pour la biosynthèse des nucléotides de l’ARN.",
    choiceExplanations: [
      "Vrai. C’est le pentose de l’ARN.",
      "Vrai. C5 est la position du phosphate.",
      "Vrai. Ribose est un pentose.",
      "Faux. Le glucose n’est pas le sucre de l’ARN.",
    ],
  },
  {
    order: 115,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’acide ascorbique et la streptomycine illustrent :",
    choices: [
      "La diversité des dérivés glucidiques.",
      "Un dérivé vitaminique pour le premier.",
      "Un antibiotique pour la seconde.",
      "Deux polyols simples obtenus par réduction du glucose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Ces exemples montrent que des dérivés de glucides peuvent avoir des fonctions biologiques et thérapeutiques très différentes.",
    choiceExplanations: [
      "Vrai. Leurs structures et rôles sont distincts.",
      "Vrai. L’acide ascorbique est la vitamine C.",
      "Vrai. La streptomycine est un antibiotique.",
      "Faux. Cette description ne correspond à aucun des deux.",
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Pour distinguer un ose phosphorylé d’un ose sulfaté :",
    choices: [
      "Identifier l’atome central P ou S.",
      "Repérer les positions de substitution.",
      "Tenir compte des charges ioniques possibles.",
      "Conclure qu’ils ont forcément le même rôle biologique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Phosphate et sulfate sont des esters différents, avec des localisations et fonctions biologiques propres.",
    choiceExplanations: [
      "Vrai. La nature de l’élément distingue les groupements.",
      "Vrai. La nomenclature positionnelle est informative.",
      "Vrai. Les deux sont généralement chargés.",
      "Faux. Leur rôle dépend du contexte moléculaire.",
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une molécule porte deux phosphates en C2 et C6 sur une charpente de fructose :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "C’est un fructose-2,6-bisphosphate.",
      "Le terme bisphosphate est justifié.",
      "Elle diffère du fructose-1,6-bisphosphate par C1/C2.",
      "C’est un glucose-6-phosphate.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La lecture systématique du nom repose sur la nature de l’ose, le nombre de phosphates et leurs positions.",
    choiceExplanations: [
      "Vrai. Les indices correspondent exactement.",
      "Vrai. Deux groupements sont présents.",
      "Vrai. C6 est commun, l’autre position change.",
      "Faux. La charpente et le nombre de phosphates diffèrent.",
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un GAG fortement sulfaté :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'sulfated-gag-charge',
    },
    choices: [
      "Porte une forte densité de charges négatives.",
      "Peut attirer des contre-ions.",
      "Est riche en esters sulfuriques.",
      "Est nécessairement dépourvu de toute fonction acide uronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La sulfatation confère des charges négatives ; elle peut coexister avec des acides uroniques.",
    choiceExplanations: [
      "Vrai. Chaque sulfate contribue.",
      "Vrai. Les charges attirent des cations.",
      "Vrai. C’est la définition de la sulfatation.",
      "Faux. Beaucoup de GAG associent osamine et acide uronique.",
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "La phosphorylation d’un ose peut :",
    choices: [
      "Modifier sa charge.",
      "Modifier sa réactivité et son destin métabolique.",
      "Le retenir dans certains compartiments cellulaires.",
      "Le transformer obligatoirement en acide aminé.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’ajout d’un phosphate change fortement les propriétés physicochimiques et métaboliques d’un ose.",
    choiceExplanations: [
      "Vrai. Le phosphate est ionisé.",
      "Vrai. Il devient un substrat spécifique d’enzymes.",
      "Vrai. La charge limite notamment la diffusion passive.",
      "Faux. Aucune amination obligatoire n’a lieu.",
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Synthèse des oses estérifiés et autres dérivés :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'phosphorylated-oses',
    },
    choices: [
      "Glucose-6-phosphate intervient dans la glycolyse.",
      "Ribose-5-phosphate est lié aux acides nucléiques.",
      "Les sulfates confèrent des charges négatives aux GAG.",
      "La vitamine C est présentée comme un dérivé du D-mannose réduit.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les esters phosphoriques et sulfuriques sont fonctionnels ; la vitamine C dérive du L-gulose selon la fiche.",
    choiceExplanations: [
      "Vrai. C’est un intermédiaire majeur.",
      "Vrai. Il participe aux nucléotides de l’ARN.",
      "Vrai. Les sulfates sont anioniques.",
      "Faux. Le précurseur cité est le L-gulose et la transformation est plus complexe.",
    ],
  },
];
