/**
 * UE14 – Biologie cellulaire – Chapitre 8
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’expérience historique sur l’entrée des protéines nucléaires utilise :`,
    choices: [
      `La nucléoplasmine.`,
      `Des ovocytes d’amphibiens vivants.`,
      `Un marquage fluorescent des fractions protéiques.`,
      `Des hématies humaines comme modèle principal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est une protéine de la matrice nucléaire.`,
      `Exact. Ils servent de modèle cellulaire.`,
      `Exact. Il permet leur localisation.`,
      `Faux. Les hématies sont dépourvues de noyau.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La nucléoplasmine est décrite comme :`,
    choices: [
      `Un pentamère.`,
      `Chaque monomère possède une partie globulaire.`,
      `Chaque monomère possède une partie effilée.`,
      `Une molécule dépourvue de toute structure modulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle comporte cinq monomères.`,
      `Exact. Cette partie peut être séparée par protéolyse modérée.`,
      `Exact. Cette partie contient le message d’import nucléaire.`,
      `Faux. La fiche distingue clairement deux parties.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après micro-injection de nucléoplasmine entière fluorescente dans le cytoplasme :`,
    choices: [
      `La fluorescence devient nucléaire en trois minutes.`,
      `L’expérience sert de contrôle positif.`,
      `La protéine reste exclusivement cytoplasmique.`,
      `La présence de la partie effilée est compatible avec cet import.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La protéine est rapidement transloquée.`,
      `Exact. Elle vérifie que la protéine marquée reste fonctionnelle.`,
      `Faux. Elle rejoint le noyau.`,
      `Exact. Cette partie porte le NLS.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après micro-injection de la partie globulaire dans le cytoplasme :`,
    choices: [
      `La fluorescence reste cytoplasmique.`,
      `Deux hypothèses initiales sont possibles.`,
      `Cette expérience démontre immédiatement que la partie globulaire ne peut jamais rester dans le noyau.`,
      `L’absence de partie effilée est déterminante.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La partie globulaire n’est pas importée depuis le cytoplasme.`,
      `Exact. Elle peut ne pas entrer ou entrer sans être retenue.`,
      `Faux. Une autre expérience montre qu’elle y demeure si elle y est injectée.`,
      `Exact. Le signal d’import se trouve dans cette partie.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après injection de la partie globulaire directement dans le noyau :`,
    choices: [
      `Elle reste dans le noyau.`,
      `La partie effilée n’est donc pas nécessaire à l’ancrage nucléaire.`,
      `Elle est immédiatement expulsée vers le cytoplasme.`,
      `Cette expérience permet de trancher entre les deux hypothèses précédentes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La fluorescence demeure nucléaire.`,
      `Exact. La rétention est possible sans elle.`,
      `Faux. L’expérience montre le contraire.`,
      `Exact. Elle démontre que le défaut concerne l’entrée, non la rétention.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Après injection de la partie effilée dans le cytoplasme :`,
    choices: [
      `Elle entre dans le noyau.`,
      `Elle y reste au moins pendant l’expérience.`,
      `Cette partie contient le message de translocation nucléaire.`,
      `Elle est dépourvue de toute information d’adressage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La fluorescence devient nucléaire.`,
      `Exact. Le signal est localisé dans le noyau après trois minutes.`,
      `Exact. Elle porte le NLS.`,
      `Faux. C’est précisément elle qui porte le signal.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le signal de localisation nucléaire (NLS) :`,
    choices: [
      `Est une séquence de quelques acides aminés.`,
      `Doit conserver une séquence correcte pour être fonctionnel.`,
      `Est toujours excisé après l’entrée dans le noyau.`,
      `Permet le retour des protéines nucléaires après la mitose.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le message d’adressage est court.`,
      `Exact. Une substitution peut abolir l’import.`,
      `Faux. Le cours précise qu’il n’est pas excisé.`,
      `Exact. Il reste présent après la dispersion mitotique.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans l’antigène T du virus SV40, le NLS sauvage est :`,
    choices: [
      `Lys-Lys-Lys-Arg-Lys.`,
      `Gly-Ala-Gly-Ala-Gly.`,
      `Riche en acides aminés basiques.`,
      `Une séquence lipidique membranaire.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cette séquence de cinq acides aminés est donnée dans la fiche.`,
      `Faux. Ce n’est pas le NLS décrit.`,
      `Exact. La lysine et l’arginine dominent.`,
      `Faux. Il s’agit d’une séquence peptidique.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La mutation Lys → Thr dans le NLS de l’antigène T :`,
    choices: [
      `Empêche sa localisation nucléaire normale.`,
      `Montre l’importance de la séquence exacte.`,
      `Renforce obligatoirement l’import nucléaire.`,
      `Concerne la deuxième lysine du motif présenté.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La protéine mutée reste cytoplasmique.`,
      `Exact. Une seule substitution suffit à perturber le signal.`,
      `Faux. L’import est au contraire aboli.`,
      `Exact. La fiche détaille cette substitution.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les pores nucléaires :`,
    choices: [
      `Permettent des échanges bidirectionnels.`,
      `Contrôlent le trafic entre noyau et cytoplasme.`,
      `Peuvent assurer des passages simultanés.`,
      `Ne servent qu’à l’entrée de protéines.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Import et export peuvent avoir lieu.`,
      `Exact. L’enveloppe n’est pas librement perméable à tout.`,
      `Exact. L’expérience à l’or colloïdal le montre.`,
      `Faux. Ils assurent aussi la sortie des ARN.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans l’expérience à l’or colloïdal :`,
    choices: [
      `L’or-nucléoplasmine de 20 nm est injecté dans le cytoplasme.`,
      `L’or-ARNt de 5 nm est injecté dans le noyau.`,
      `Les deux complexes sont observés au niveau d’un même pore.`,
      `Les deux complexes ont exactement le même diamètre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il suit une voie d’import nucléaire.`,
      `Exact. Il suit une voie d’export.`,
      `Exact. Cela démontre la simultanéité et la bidirectionnalité.`,
      `Faux. Leurs diamètres sont différents : 20 et 5 nm.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la structure du pore nucléaire :`,
    choices: [
      `Il s’agit d’un assemblage protéique.`,
      `Il comporte un anneau principal.`,
      `Il possède huit bras radiaires.`,
      `Il est constitué uniquement de phospholipides.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La coupe en MET révèle un complexe organisé.`,
      `Exact. Cet anneau constitue l’échafaudage.`,
      `Exact. Ces bras délimitent des canaux latéraux.`,
      `Faux. Le pore est un complexe protéique.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le transporteur central du pore nucléaire :`,
    choices: [
      `Est impliqué dans les échanges actifs.`,
      `Peut assurer l’import de protéines nucléaires.`,
      `Peut assurer l’export d’ARN.`,
      `Est le seul lieu de diffusion passive des petites molécules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les complexes d’importation et d’exportation y transitent.`,
      `Exact. Le sens cytoplasme-noyau concerne notamment ces protéines.`,
      `Exact. Le sens noyau-cytoplasme concerne les ARN.`,
      `Faux. Le passage passif emprunte surtout les canaux latéraux.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les échanges passifs à travers le pore :`,
    choices: [
      `Concernent les petites molécules.`,
      `Se font au niveau des canaux latéraux.`,
      `Peuvent laisser passer de l’eau et des ions.`,
      `Nécessitent toujours un complexe d’importation.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La taille limite la diffusion passive.`,
      `Exact. Ils sont situés entre les bras radiaires.`,
      `Exact. Ces exemples sont explicitement cités.`,
      `Faux. Les complexes sont requis pour les échanges actifs.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les échanges actifs nucléocytoplasmiques :`,
    choices: [
      `Impliquent un complexe d’importation ou d’exportation.`,
      `Se déroulent au niveau du transporteur central.`,
      `Sont bidirectionnels selon la cargaison.`,
      `Sont limités à la diffusion de l’eau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La cargaison est associée à une machinerie de transport.`,
      `Exact. C’est le passage actif du pore.`,
      `Exact. Les protéines entrent et les ARN sortent.`,
      `Faux. L’eau relève du passage passif.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En observant la figure :

![Pore nucléaire](/images/training/ue14/biologie-cellulaire/noyau/pore-nucleaire-echanges.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les canaux latéraux sont associés aux passages passifs.`,
      `Le transporteur central assure les échanges actifs.`,
      `Les échanges peuvent avoir lieu dans les deux sens.`,
      `Le pore est fermé à tous les ARN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La figure les montre en périphérie du transporteur central.`,
      `Exact. Les flèches d’import et d’export y convergent.`,
      `Exact. Import et export sont représentés simultanément.`,
      `Faux. Les ARN sont exportés activement.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En observant la figure des expériences de nucléoplasmine :

![Expérience NLS](/images/training/ue14/biologie-cellulaire/noyau/experience-nucleoplasmine-NLS.png)

On peut conclure que :`,
    choices: [
      `La partie effilée contient l’information d’import.`,
      `La partie globulaire peut être retenue dans le noyau si elle y est injectée.`,
      `La partie globulaire porte seule le NLS.`,
      `L’expérience complète distingue import et rétention.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle suffit à diriger une fraction vers le noyau.`,
      `Exact. L’ancrage ne nécessite pas la partie effilée.`,
      `Faux. Injectée dans le cytoplasme, elle ne rejoint pas le noyau.`,
      `Exact. Les injections dans des compartiments différents permettent cette distinction.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le maintien du NLS après l’entrée dans le noyau est utile car :`,
    choices: [
      `L’enveloppe nucléaire disparaît au début de la mitose.`,
      `Les protéines doivent retourner dans le noyau en fin de mitose.`,
      `Le NLS sert uniquement lors de la première synthèse de la protéine.`,
      `Le signal n’est pas excisé.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les protéines nucléaires sont alors dispersées dans le cytoplasme.`,
      `Exact. Le NLS permet une nouvelle importation.`,
      `Faux. Il reste fonctionnel au cours des cycles cellulaires.`,
      `Exact. Cette conservation est explicitement mentionnée.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une protéine nucléaire mutée dans son NLS est observée dans le cytoplasme. Cette observation est cohérente avec :`,
    choices: [
      `Une perte de la capacité d’import nucléaire.`,
      `Une amélioration de l’ancrage dans la matrice nucléaire.`,
      `Le modèle de l’antigène T de SV40.`,
      `La disparition obligatoire de tous les pores.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La mutation peut abolir la reconnaissance du signal.`,
      `Faux. La localisation cytoplasmique traduit surtout un défaut d’entrée.`,
      `Exact. La substitution Lys/Thr produit ce phénotype.`,
      `Faux. Un défaut de signal suffit, sans altération générale des pores.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une molécule de grande taille dépourvue de NLS :`,
    choices: [
      `A peu de chances d’entrer activement dans le noyau comme une protéine nucléaire.`,
      `Entre toujours passivement par les canaux latéraux.`,
      `Peut rester cytoplasmique.`,
      `Est automatiquement transformée en ARN.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle ne peut pas recruter normalement la machinerie d’import.`,
      `Faux. Le passage passif concerne surtout les petites molécules.`,
      `Exact. L’absence de signal d’adressage l’empêche d’être ciblée.`,
      `Faux. La nature de la molécule ne change pas par le pore.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine entière entre dans le noyau, sa partie globulaire seule n’y entre pas depuis le cytoplasme mais y reste si on l’y injecte. L’interprétation correcte est :`,
    choices: [
      `La partie effilée est nécessaire à l’import.`,
      `La partie globulaire contribue à la rétention nucléaire.`,
      `La partie effilée est nécessaire à l’ancrage nucléaire.`,
      `Import et ancrage sont deux propriétés distinctes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle porte le NLS.`,
      `Exact. Elle reste dans le noyau si elle y est placée.`,
      `Faux. La globulaire seule y demeure.`,
      `Exact. Les expériences les dissocient clairement.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une substitution d’un seul acide aminé dans un NLS peut :`,
    choices: [
      `Abolir l’import nucléaire.`,
      `Maintenir la protéine dans le cytoplasme.`,
      `Être sans aucune conséquence par définition.`,
      `Fournir un argument expérimental pour localiser le signal d’adressage.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le motif doit être conservé précisément.`,
      `Exact. C’est le résultat observé pour l’antigène T muté.`,
      `Faux. La séquence exacte est déterminante.`,
      `Exact. La comparaison sauvage/mutant établit la fonction du motif.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une particule de 20 nm associée à une protéine nucléaire est observée dans un pore simultanément à une particule de 5 nm associée à un ARNt. Cela montre :`,
    choices: [
      `La capacité de passage de complexes de tailles différentes.`,
      `La bidirectionnalité du pore.`,
      `La simultanéité possible des échanges.`,
      `L’existence de deux enveloppes nucléaires indépendantes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les deux diamètres sont observés.`,
      `Exact. L’une est importée, l’autre exportée.`,
      `Exact. Les deux complexes sont vus au même pore.`,
      `Faux. L’observation concerne un même pore dans une seule enveloppe.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un passage localisé entre deux bras radiaires du pore correspond préférentiellement :`,
    choices: [
      `À un canal latéral.`,
      `À une voie de diffusion passive.`,
      `Au transporteur central.`,
      `À un nucléole.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ces canaux sont définis par les bras radiaires.`,
      `Exact. Les petites molécules y transitent.`,
      `Faux. Celui-ci occupe le centre du pore.`,
      `Faux. Le nucléole est un compartiment intranucléaire sans lien structurel direct avec le pore.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un complexe protéine-importine se déplaçant du cytoplasme vers le noyau utilise :`,
    choices: [
      `Un échange actif.`,
      `Le transporteur central du pore.`,
      `Les canaux latéraux uniquement.`,
      `Un signal de localisation nucléaire porté par la cargaison.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La cargaison est associée à un complexe d’importation.`,
      `Exact. C’est le trajet actif décrit.`,
      `Faux. Ils concernent surtout les passages passifs.`,
      `Exact. Le NLS permet la reconnaissance de la protéine nucléaire.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un ARN associé à des protéines quitte le noyau :`,
    choices: [
      `Par un échange actif.`,
      `Via le transporteur central du pore.`,
      `En traversant librement la bicouche lipidique.`,
      `Dans le sens noyau-cytoplasme.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La cargaison utilise une machinerie d’export.`,
      `Exact. Le cours place les échanges actifs au centre.`,
      `Faux. L’enveloppe contrôle les échanges via les pores.`,
      `Exact. C’est le sens de l’export des ARN.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les échanges nucléocytoplasmiques sont qualifiés de contrôlés parce que :`,
    choices: [
      `Les pores distinguent petites molécules et complexes.`,
      `Les protéines nucléaires nécessitent souvent un NLS.`,
      `Les ARN sont exportés sous forme de complexes.`,
      `Toutes les molécules traversent selon le même mécanisme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les voies passives et actives diffèrent.`,
      `Exact. L’adressage est spécifique.`,
      `Exact. L’export n’est pas une fuite libre.`,
      `Faux. Plusieurs voies et mécanismes sont distingués.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation touchant les huit bras radiaires d’un pore pourrait perturber particulièrement :`,
    choices: [
      `L’organisation des canaux latéraux.`,
      `Les passages passifs de petites molécules.`,
      `La séquence du NLS de toutes les protéines.`,
      `La structure générale du complexe du pore.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ils sont définis entre les bras.`,
      `Exact. Ces passages utilisent les canaux latéraux.`,
      `Faux. Le NLS appartient aux cargaisons, pas au pore.`,
      `Exact. Les bras participent à l’échafaudage protéique.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos du rôle des pores nucléaires :`,
    choices: [
      `Ils assurent l’import de protéines nucléaires.`,
      `Ils assurent l’export des ARN.`,
      `Ils permettent également des diffusions passives.`,
      `Ils laissent sortir l’ADN chromosomique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cet import peut être actif.`,
      `Exact. Les ARN associés à des protéines quittent le noyau.`,
      `Exact. Les petites molécules empruntent les canaux latéraux.`,
      `Faux. L’ADN ne sort jamais du noyau.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `Le NLS est un signal peptidique d’import nucléaire.`,
      `Les pores possèdent des voies passives et actives.`,
      `Les échanges peuvent être bidirectionnels et simultanés.`,
      `Le trafic nucléaire est purement passif.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il est nécessaire à la reconnaissance de nombreuses protéines nucléaires.`,
      `Exact. Canaux latéraux et transporteur central sont distingués.`,
      `Exact. L’expérience à l’or colloïdal le démontre.`,
      `Faux. De nombreuses cargaisons utilisent des complexes actifs.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `nucleoplasmine-et-NLS`,
    title: `Nucléoplasmine et signal NLS`,
    description: `Expériences historiques, signal d’import et antigène T de SV40.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `pores-et-echanges-nucleocytoplasmiques`,
    title: `Pores et échanges nucléocytoplasmiques`,
    description: `Structure du pore, transports passifs et actifs, bidirectionnalité.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `raisonnement-experimental-import-export`,
    title: `Raisonnement expérimental sur l’import et l’export`,
    description: `Interprétation de protocoles et conséquences de mutations.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
