import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_ORDER = 2;

export const SECTION_B_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  31: ["Carbone asymétrique"],
  32: ["Chiralité du glycéraldéhyde"],
  33: ["Achiralité de la dihydroxyacétone"],
  34: ["Définition de la chiralité"],
  35: ["Priorités autour du carbone asymétrique"],
  36: ["Nomenclature R/S"],
  37: ["Projection de Fischer"],
  38: ["Série D"],
  39: ["Série L"],
  40: ["Signification de D et L"],
  41: ["D-glucose et L-glucose"],
  42: ["Répartition biologique des séries D et L"],
  43: ["L-fucose"],
  44: ["Acide L-iduronique"],
  45: ["Lecture de la série en Fischer"],
  46: ["Application de la série L"],
  47: ["Limites de l'information D/L"],
  48: ["Projection de Newman"],
  49: ["Nombre de stéréoisomères des aldoses"],
  50: ["Nombre de stéréoisomères des cétoses"],
  51: ["Calcul : aldotriose"],
  52: ["Calcul : cétotriose"],
  53: ["Calcul : aldohexose"],
  54: ["Calcul : cétohexose"],
  55: ["Répartition des stéréoisomères"],
  56: ["Filiation des aldotétroses"],
  57: ["Principe de la filiation"],
  58: ["Lecture d'une projection de Fischer"],
  59: ["Image miroir en Fischer"],
  60: ["Synthèse de la section B"],
};

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "decouvrir-chiralite-series-d-l",
    title: "Chiralité et séries D/L",
    description: "Identifier un carbone asymétrique, distinguer molécules chirales et achirales et lire les séries D/L.",
    stage: 'DISCOVER',
    sectionOrder: SECTION_B_ORDER,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 2,
    slug: "sentrainer-fischer-newman-series-d-l",
    title: "Projections et séries D/L",
    description: "Utiliser les projections de Fischer et de Newman et interpréter la distribution biologique des séries D et L.",
    stage: 'PRACTICE',
    sectionOrder: SECTION_B_ORDER,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 3,
    slug: "maitriser-filiation-stereoisomeres",
    title: "Filiation et stéréoisomères",
    description: "Calculer le nombre de configurations et exploiter les motifs de Fischer des aldoses et cétoses.",
    stage: 'MASTER',
    sectionOrder: SECTION_B_ORDER,
    items: [
      {
        type: 'GROUP',
        title: "Trioses et nombre de stéréoisomères",
        sharedStatement: "On applique les relations $2^{n-2}$ pour les aldoses et $2^{n-3}$ pour les cétoses, avec $n$ égal au nombre de carbones.",
        questionOrders: [51, 52],
      },
      { type: 'QUESTION', questionOrder: 53 },
      { type: 'QUESTION', questionOrder: 54 },
      { type: 'QUESTION', questionOrder: 55 },
      { type: 'QUESTION', questionOrder: 56 },
      { type: 'QUESTION', questionOrder: 57 },
      { type: 'QUESTION', questionOrder: 58 },
      { type: 'QUESTION', questionOrder: 59 },
      { type: 'QUESTION', questionOrder: 60 },
    ],
  },
];

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Un carbone asymétrique, noté $\\mathrm{C^*}$ :",
    choices: [
      "Est lié à quatre substituants différents.",
      "Constitue un centre de chiralité.",
      "Est nécessairement lié à quatre atomes de carbone.",
      "Peut contribuer à rendre une molécule chirale.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Un carbone asymétrique est tétraédrique et porte quatre substituants différents. Il constitue un centre de chiralité.",
    choiceExplanations: [
      "C'est la définition retenue.",
      "Cette appellation est équivalente dans le cadre du cours.",
      "Les substituants peuvent contenir H, O ou d'autres atomes.",
      "Un ou plusieurs centres peuvent rendre la molécule chirale.",
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du glycéraldéhyde $\mathrm{CHO-CHOH-CH_2OH}$ :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glyceraldehyde-enantiomers-fischer',
    },
    choices: [
      "Son carbone central est lié à quatre substituants différents.",
      "Il possède un carbone asymétrique.",
      "Il est chiral.",
      "Il ne peut exister que sous une seule configuration spatiale.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le carbone central du glycéraldéhyde porte H, OH, CHO et CH2OH : il est asymétrique et la molécule est chirale.",
    choiceExplanations: [
      "Les quatre groupes sont différents.",
      "Ce carbone répond à la définition de $\\mathrm{C^*}$.",
      "La molécule n'est pas superposable à son image miroir.",
      "Deux énantiomères sont possibles.",
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la dihydroxyacétone $\mathrm{CH_2OH-CO-CH_2OH}$ :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glyceraldehyde-dihydroxyacetone-linear',
    },
    choices: [
      "Elle ne possède aucun carbone asymétrique.",
      "Elle est achirale.",
      "Elle présente un plan de symétrie.",
      "Elle possède deux énantiomères D et L.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La dihydroxyacétone ne possède pas de $\\mathrm{C^*}$ et sa structure symétrique est achirale.",
    choiceExplanations: [
      "Aucun carbone ne porte quatre substituants différents.",
      "L'absence de centre chiral et la symétrie conduisent à l'achiralité.",
      "Les deux groupes $\\mathrm{CH_2OH}$ sont disposés symétriquement.",
      "Une série D/L n'est pas définie ici.",
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Une molécule chirale :",
    choices: [
      "N'est pas superposable à son image dans un miroir.",
      "Ne possède pas de plan de symétrie dans l'exemple étudié.",
      "Possède nécessairement une charge électrique.",
      "Peut exister sous deux formes énantiomères.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La chiralité décrit une relation géométrique avec l'image miroir et n'implique aucune charge.",
    choiceExplanations: [
      "C'est le critère fondamental.",
      "Le glycéraldéhyde illustre cette absence de plan.",
      "La charge n'est pas liée à la chiralité.",
      "Les deux images miroir non superposables sont des énantiomères.",
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Dans l'exemple du glycéraldéhyde, l'ordre de priorité indiqué autour du carbone asymétrique est :",
    choices: [
      "$\\mathrm{H>CH_2OH>CHO>OH}$.",
      "$\\mathrm{OH>CHO>CH_2OH>H}$.",
      "$\\mathrm{CHO>OH>H>CH_2OH}$.",
      "$\\mathrm{CH_2OH>OH>CHO>H}$.",
    ],
    correctChoiceIndexes: [1],
    explanation: "La fiche donne l'ordre $\\mathrm{OH>CHO>CH_2OH>H}$ pour attribuer R ou S dans cet exemple.",
    choiceExplanations: [
      "L'hydrogène est placé en dernière priorité.",
      "C'est l'ordre présenté dans le cours.",
      "Le groupe hydroxyle est prioritaire dans l'exemple.",
      "Le groupe $\\mathrm{CH_2OH}$ n'est pas prioritaire sur OH.",
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La nomenclature R/S :",
    choices: [
      "Peut être attribuée à chaque carbone asymétrique.",
      "Décrit précisément la configuration dans l'espace.",
      "Est la seule nomenclature jamais utilisée en biochimie.",
      "Devient moins parlante lorsque le nombre de centres chiraux augmente.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "R/S est une description précise de chaque centre, mais la biochimie des glucides utilise souvent la série D/L, plus synthétique.",
    choiceExplanations: [
      "Chaque centre peut recevoir une configuration.",
      "La convention vise la géométrie tridimensionnelle.",
      "La série D/L est très utilisée pour les oses.",
      "La multiplication des centres rend la lecture lourde.",
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans une projection de Fischer d'un ose :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glyceraldehyde-enantiomers-fischer',
    },
    choices: [
      "La chaîne carbonée principale est disposée verticalement.",
      "Le carbone le plus oxydé est placé en haut.",
      "Les liaisons horizontales sont conventionnellement dirigées vers l'observateur.",
      "La position du dernier $\\mathrm{C^*}$ sert à définir D ou L.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "La projection de Fischer suit une convention géométrique précise et permet de lire la série D/L à partir du dernier centre chiral.",
    choiceExplanations: [
      "Convention correcte.",
      "Convention correcte.",
      "Convention usuelle de Fischer.",
      "Critère central du chapitre.",
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Dans la projection de Fischer d'un ose de série D, le groupe $\\mathrm{OH}$ du dernier carbone asymétrique est placé :",
    choices: [
      "À gauche.",
      "À droite.",
      "En haut.",
      "Il est absent.",
    ],
    correctChoiceIndexes: [1],
    explanation: "La série D est définie par un groupe OH à droite sur le dernier $\\mathrm{C^*}$.",
    choiceExplanations: [
      "Cette position définit la série L.",
      "C'est le critère de la série D.",
      "Le groupe est porté latéralement.",
      "Le dernier centre chiral porte bien un OH.",
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Dans la projection de Fischer d'un ose de série L, le groupe $\\mathrm{OH}$ du dernier carbone asymétrique est placé :",
    choices: [
      "À gauche.",
      "À droite.",
      "Sur le carbone carbonylé.",
      "Toujours en bas de la chaîne.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La série L est définie par un OH à gauche sur le dernier carbone asymétrique.",
    choiceExplanations: [
      "C'est le critère de la série L.",
      "Cette position définit la série D.",
      "Le carbonyle n'est pas le centre utilisé.",
      "Le groupe est latéral, pas terminal.",
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les termes D et L :",
    choices: [
      "Proviennent de Dextra et Laeva.",
      "Décrivent la configuration relative du dernier carbone asymétrique.",
      "Indiquent directement le signe du pouvoir rotatoire.",
      "Ne renseignent pas, à eux seuls, sur tous les autres centres chiraux.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "D/L décrit une configuration relative à partir du dernier centre chiral. Le signe optique + ou − est une information distincte.",
    choiceExplanations: [
      "Dextra est associé à la droite et Laeva à la gauche.",
      "C'est le critère structural.",
      "Un ose D peut être lévogyre.",
      "Les autres OH doivent être examinés séparément.",
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparer le D-glucose et le L-glucose :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-enantiomers-fischer',
    },
    choices: [
      "Ils sont images l'un de l'autre dans un miroir.",
      "Tous leurs centres chiraux ont une configuration opposée.",
      "Ils appartiennent à la même série D.",
      "Ils possèdent la même formule brute.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le D-glucose et le L-glucose sont deux énantiomères : même formule brute, configurations inversées à tous les centres chiraux.",
    choiceExplanations: [
      "Relation correcte.",
      "C'est le cas d'une paire d'énantiomères.",
      "Le second appartient à la série L.",
      "L'énantiomérie ne modifie pas la formule brute.",
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Concernant la répartition naturelle des séries D et L :",
    choices: [
      "La grande majorité des oses naturels sont de série D.",
      "Des formes L peuvent être rencontrées chez des bactéries ou des virus.",
      "Le L-fucose est une exception rencontrée chez l'Homme.",
      "L'acide L-iduronique est une autre exception citée.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "La fiche insiste sur la prédominance de la série D tout en citant des formes L biologiquement importantes.",
    choiceExplanations: [
      "Repère général du cours.",
      "Exemple de contexte biologique cité.",
      "Présent notamment dans des glycoconjugués.",
      "Présent notamment dans des glycosaminoglycanes.",
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le L-fucose correspond à :",
    choices: [
      "Un ose de série L présent chez l'Homme.",
      "Un constituant de certaines glycoprotéines.",
      "Un constituant de certains glycolipides.",
      "Un exemple prouvant que tous les oses humains sont D.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le L-fucose constitue précisément une exception à la prédominance des oses D chez l'Homme.",
    choiceExplanations: [
      "Association correcte.",
      "Rôle structural cité.",
      "Rôle structural cité.",
      "Il démontre au contraire l'existence d'exceptions L.",
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L'acide L-iduronique peut être décrit :",
    choices: [
      "Comme une forme L rencontrée chez l'Homme.",
      "Comme un constituant de glycosaminoglycanes.",
      "Comme un acide gras saturé.",
      "Comme une exception à la prédominance des formes D.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L'acide L-iduronique est une exception de série L présente dans des glycosaminoglycanes.",
    choiceExplanations: [
      "Association correcte.",
      "Localisation biochimique citée.",
      "Il s'agit d'un dérivé glucidique, pas d'un acide gras.",
      "C'est précisément pourquoi il est mentionné.",
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Pour déterminer la série D ou L d'un aldohexose représenté en Fischer :",
    choices: [
      "On repère le carbone asymétrique le plus éloigné du carbonyle.",
      "Ce carbone est l'avant-dernier de la chaîne.",
      "On observe la position de son groupe OH.",
      "On additionne le nombre total de groupes OH à droite.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La série repose uniquement sur la configuration du dernier centre chiral, qui est l'avant-dernier carbone pour l'aldohexose.",
    choiceExplanations: [
      "Critère correct.",
      "Dans un aldohexose, il s'agit de C5.",
      "OH à droite donne D, à gauche donne L.",
      "Le décompte total des OH ne définit pas la série.",
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: "Un aldohexose possède son groupe OH de C5 à gauche dans une projection de Fischer. Il appartient à la série :",
    choices: [
      "D.",
      "L.",
      "α.",
      "β.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Pour un aldohexose, C5 est le dernier carbone asymétrique ; OH à gauche indique la série L.",
    choiceExplanations: [
      "OH à droite aurait indiqué D.",
      "C'est la bonne lecture.",
      "α concerne l'anomérie après cyclisation.",
      "β concerne également l'anomérie.",
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un ose de série D :",
    choices: [
      "Possède le OH du dernier $\\mathrm{C^*}$ à droite en Fischer.",
      "Peut avoir certains autres OH à gauche.",
      "Est nécessairement dextrogyre.",
      "Peut avoir plusieurs carbones asymétriques.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La série D ne fixe que le dernier centre chiral et ne préjuge ni des autres centres ni du signe optique.",
    choiceExplanations: [
      "Définition correcte.",
      "Les motifs de glucose ou galactose l'illustrent.",
      "D et + ne sont pas synonymes.",
      "Les pentoses et hexoses en possèdent plusieurs.",
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la projection de Newman présentée pour le glycéraldéhyde :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glyceraldehyde-configurations-newman',
    },
    choices: [
      "Elle permet de visualiser l'organisation autour d'un carbone asymétrique.",
      "Deux configurations opposées peuvent être représentées.",
      "Elle ne contient aucune information spatiale.",
      "Elle peut servir à attribuer R ou S après classement des substituants.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La projection de Newman est une représentation spatiale ; avec un ordre de priorité, elle permet de distinguer les configurations.",
    choiceExplanations: [
      "Objectif correct.",
      "Les deux images correspondent à des configurations opposées.",
      "C'est précisément une représentation spatiale.",
      "Le classement des substituants est nécessaire.",
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Pour un aldose linéaire à $n$ carbones, le nombre de stéréoisomères est $2^{n-2}$ car :",
    choices: [
      "Il possède classiquement $n-2$ carbones asymétriques.",
      "Chaque centre asymétrique peut prendre deux configurations.",
      "Le carbone aldéhydique et le carbone terminal $\\mathrm{CH_2OH}$ ne sont pas asymétriques.",
      "Le nombre d'isomères est toujours égal à $n$.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Un aldose à $n$ carbones possède $n-2$ centres chiraux usuels, d'où $2^{n-2}$ combinaisons.",
    choiceExplanations: [
      "Décompte correct.",
      "Deux possibilités par centre conduisent à une puissance de 2.",
      "Ces deux extrémités ne portent pas quatre substituants différents.",
      "Le nombre croît exponentiellement, pas linéairement.",
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Pour un cétose linéaire à $n$ carbones, le nombre de stéréoisomères est $2^{n-3}$ car :",
    choices: [
      "Il possède classiquement $n-3$ carbones asymétriques.",
      "Le carbone carbonylé C2 n'est pas asymétrique.",
      "Les deux carbones terminaux $\\mathrm{CH_2OH}$ ne sont pas asymétriques.",
      "Un cétohexose possède nécessairement 16 stéréoisomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le cétose usuel perd un centre chiral supplémentaire par rapport à l'aldose correspondant, d'où $2^{n-3}$.",
    choiceExplanations: [
      "Décompte correct.",
      "Un carbone trigonal carbonylé n'est pas un $\\mathrm{C^*}$.",
      "Les carbones terminaux portent deux hydrogènes.",
      "Un cétohexose en possède $2^3=8$.",
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Le glycéraldéhyde est un aldotriose. En appliquant $2^{n-2}$ :",
    choices: [
      "Il possède un carbone asymétrique.",
      "Il existe deux stéréoisomères.",
      "Ces deux formes sont D et L.",
      "Il possède quatre stéréoisomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Pour $n=3$, $2^{3-2}=2$ : le D-glycéraldéhyde et le L-glycéraldéhyde.",
    choiceExplanations: [
      "Le carbone central est chiral.",
      "Le calcul donne deux.",
      "Ils forment la paire d'énantiomères de référence.",
      "Quatre nécessiteraient deux centres chiraux.",
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "La dihydroxyacétone est un cétotriose. En appliquant $2^{n-3}$ :",
    choices: [
      "Elle possède zéro carbone asymétrique.",
      "Il n'existe qu'une configuration stéréochimique.",
      "Elle forme une paire D/L.",
      "Le calcul donne $2^0=1$.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Pour $n=3$, le cétotriose possède $n-3=0$ centre chiral et une seule forme.",
    choiceExplanations: [
      "Décompte correct.",
      "Une molécule achirale n'a pas de paire d'énantiomères.",
      "D/L n'est pas applicable ici.",
      "Toute quantité non nulle à la puissance zéro vaut 1.",
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: "Combien de stéréoisomères linéaires possède un aldohexose en appliquant $2^{n-2}$ ?",
    choices: [
      "4.",
      "8.",
      "16.",
      "32.",
    ],
    correctChoiceIndexes: [2],
    explanation: "Pour $n=6$, $2^{6-2}=2^4=16$.",
    choiceExplanations: [
      "Cette valeur correspondrait à deux centres chiraux.",
      "C'est le nombre d'un cétohexose.",
      "Le calcul est correct.",
      "Cette valeur correspondrait à cinq centres.",
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `Combien de stéréoisomères linéaires possède un cétohexose en appliquant $2^{n-3}$ ?

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'ketoses-d-filiation',
    },
    choices: [
      "4.",
      "8.",
      "16.",
      "64.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Pour $n=6$, $2^{6-3}=2^3=8$.",
    choiceExplanations: [
      "Cette valeur serait trop faible.",
      "Le calcul est correct.",
      "C'est le nombre d'un aldohexose.",
      "Cette valeur supposerait six centres chiraux.",
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Parmi les aldohexoses, la moitié des 16 stéréoisomères appartient à la série D et l'autre moitié à la série L. On peut donc compter :",
    choices: [
      "8 D-aldohexoses.",
      "8 L-aldohexoses.",
      "16 formes dans chaque série.",
      "Des paires d'énantiomères D/L.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les 16 formes se répartissent en huit paires d'énantiomères, chacune comportant une forme D et une forme L.",
    choiceExplanations: [
      "Moitié de 16.",
      "Moitié de 16.",
      "Cela doublerait le total.",
      "Chaque configuration D possède son image L.",
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans la filiation des aldotétroses de série D :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'aldoses-d-filiation',
    },
    choices: [
      "Le D-érythrose et le D-thréose sont deux aldotétroses.",
      "Ils diffèrent par la configuration d'un centre chiral.",
      "Ils possèdent tous deux quatre carbones.",
      "Ils sont nécessairement énantiomères l'un de l'autre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le D-érythrose et le D-thréose appartiennent à la même série et diffèrent à un centre : ce sont des diastéréoisomères, non des énantiomères.",
    choiceExplanations: [
      "Noms présents dans la filiation.",
      "Le motif relatif des OH change.",
      "Le suffixe tétrose indique quatre carbones.",
      "Leur image miroir appartientrait à la série L.",
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Lorsqu'on passe d'un aldose à $n$ carbones à la génération suivante à $n+1$ carbones dans l'arbre de filiation :",
    choices: [
      "Un nouveau centre asymétrique peut apparaître.",
      "Chaque ose peut donner deux descendants stéréoisomères.",
      "Le nombre de configurations double.",
      "La famille devient nécessairement cétose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'allongement de chaîne ajoute un centre chiral et double le nombre de stéréoisomères tout en conservant ici la famille aldose.",
    choiceExplanations: [
      "Principe de la filiation.",
      "Deux orientations du nouvel OH sont possibles.",
      "Une puissance de 2 supplémentaire apparaît.",
      "L'arbre des aldoses reste dans la famille aldose.",
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un aldohexose présente, de C2 à C5, les positions d'OH droite-gauche-droite-droite. On peut conclure que :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "Le OH de C5 est à droite.",
      "Il appartient à la série D.",
      "Ce motif correspond au D-glucose.",
      "Il appartient nécessairement à la série L.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le motif droite-gauche-droite-droite est celui du D-glucose ; le dernier OH à droite définit D.",
    choiceExplanations: [
      "Lecture directe du motif.",
      "Critère D/L.",
      "Motif classique R-L-R-R.",
      "La conclusion est opposée.",
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un aldohexose présente, de C2 à C5, les positions d'OH gauche-droite-gauche-gauche. Il s'agit de l'image miroir du motif du D-glucose. On peut conclure que :",
    choices: [
      "Tous les centres ont été inversés.",
      "La molécule appartient à la série L.",
      "Elle correspond au L-glucose.",
      "Elle possède une formule brute différente du D-glucose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'inversion de tous les centres du D-glucose donne le L-glucose, son énantiomère de même formule brute.",
    choiceExplanations: [
      "C'est la condition de l'image miroir.",
      "Le dernier OH est à gauche.",
      "Nom correct.",
      "L'énantiomérie conserve la formule brute.",
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Concernant chiralité et représentation des oses :",
    choices: [
      "Un seul carbone asymétrique suffit à permettre une paire d'énantiomères.",
      "D/L se lit sur le dernier carbone asymétrique en Fischer.",
      "Le nombre maximal de stéréoisomères est une puissance de 2.",
      "Tous les items précédents sont vrais.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les trois principes sont exacts dans le cadre du chapitre ; l'item récapitulatif est donc vrai.",
    choiceExplanations: [
      "Principe exact.",
      "Principe exact.",
      "Deux configurations par centre expliquent cette puissance.",
      "A, B et C étant vraies, cet item l'est aussi.",
    ],
  },
];
