/**
 * UE14 – Biologie cellulaire – Chapitre 1
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la cellule :`,
    choices: [
      `Elle constitue la plus petite unité vivante.`,
      `Elle est limitée par une membrane séparant l'intérieur de l'extérieur.`,
      `Elle est dépourvue de toute organisation interne.`,
      `Un tissu d'un organisme pluricellulaire est formé de plusieurs types de cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La cellule est présentée comme la plus petite unité vivante, délimitée par une membrane. Dans un organisme pluricellulaire, des cellules spécialisées participent à la constitution des tissus.`,
    choiceExplanations: [
      `C'est la définition donnée dans le cours.`,
      `La membrane forme la barrière entre les deux milieux.`,
      `Le cytoplasme contient de nombreuses structures et organites.`,
      `Les cellules spécialisées s'organisent en tissus.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Selon les ordres de grandeur indiqués dans la fiche :`,
    choices: [
      `L'eau représente environ 70 % de la cellule.`,
      `Les macromolécules représentent environ 30 % de la cellule.`,
      `Les protéines représentent environ 15 % de la cellule.`,
      `L'ADN représente environ 10 % de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours propose un modèle simplifié : environ 70 % d'eau et 30 % de macromolécules et autres constituants, dont près de 15 % de protéines et 1 % d'ADN.`,
    choiceExplanations: [
      `Le cours retient environ 70 % d'eau.`,
      `Elles constituent l'autre grande fraction chiffrée.`,
      `Cette proportion est explicitement donnée.`,
      `La fiche indique environ 1 % d'ADN.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Quel ensemble correspond aux quatre composants chimiques principaux cités pour la cellule ?`,
    choices: [
      `Carbone, hydrogène, oxygène et azote.`,
      `Carbone, hélium, oxygène et azote.`,
      `Calcium, hydrogène, or et sodium.`,
      `Carbone, phosphore, soufre et chlore.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Les quatre composants chimiques principaux retenus dans la fiche sont le carbone, l'hydrogène, l'oxygène et l'azote.`,
    choiceExplanations: [
      `C'est l'ensemble CHON indiqué dans la fiche.`,
      `L'hélium remplace à tort l'hydrogène.`,
      `Ces éléments ne constituent pas le quatuor principal cité.`,
      `Ce ne sont pas les quatre éléments majeurs donnés.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des structures cellulaires citées dans le cours :`,
    choices: [
      `La membrane cellulaire sépare l'intérieur de l'extérieur.`,
      `Le cytosquelette participe à la forme de la cellule.`,
      `Le centrosome est mentionné parmi les structures cellulaires.`,
      `Le cytoplasme se situe exclusivement à l'extérieur de la membrane.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La cellule comporte notamment une membrane, un cytoplasme, un cytosquelette et des centrosomes. Le cytoplasme est contenu par la membrane.`,
    choiceExplanations: [
      `C'est son rôle général présenté ici.`,
      `Le cours lui attribue ce rôle.`,
      `Il figure dans la liste du chapitre.`,
      `Le cytoplasme se trouve à l'intérieur de la cellule.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les propositions suivantes concernant les organites :`,
    choices: [
      `Les mitochondries sont citées parmi les organites cellulaires.`,
      `Le réticulum endoplasmique peut être lisse ou rugueux.`,
      `L'appareil de Golgi est présenté comme une structure cellulaire.`,
      `Les lysosomes se trouvent nécessairement à l'extérieur de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche énumère notamment l'appareil de Golgi, le REL, le RER, les lysosomes et les mitochondries parmi les organites.`,
    choiceExplanations: [
      `Elles figurent dans la liste du cours.`,
      `Les formes REL et RER sont distinguées.`,
      `Il est explicitement mentionné.`,
      `Ce sont des organites intracellulaires.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Quelles fonctions sont attribuées aux cellules dans le chapitre ?`,
    choices: [
      `Fabriquer et dégrader des molécules.`,
      `Produire de l'énergie.`,
      `Communiquer avec les cellules environnantes.`,
      `Empêcher tout échange avec le milieu extérieur.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les fonctions générales citées comprennent la fabrication et la dégradation de molécules, la production d'énergie, les échanges, la réponse aux stimuli, la communication et le transport intracellulaire.`,
    choiceExplanations: [
      `Cette fonction est explicitement citée.`,
      `La production d'énergie fait partie de la liste.`,
      `La communication cellulaire est mentionnée.`,
      `La cellule réalise au contraire des échanges avec l'extérieur.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les étapes de la vie cellulaire citées :`,
    choices: [
      `La croissance.`,
      `La différenciation.`,
      `La migration.`,
      `La cristallisation obligatoire de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours retient notamment la croissance, la division, la différenciation, la migration et la mort cellulaire.`,
    choiceExplanations: [
      `Elle fait partie de la liste du cours.`,
      `Elle est explicitement indiquée.`,
      `Elle figure parmi les étapes étudiées.`,
      `Ce phénomène n'est pas une étape générale de la vie cellulaire.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la spécialisation des cellules :`,
    choices: [
      `Des cellules de composition générale semblable peuvent avoir des fonctions différentes.`,
      `La forme d'une cellule peut être adaptée à sa fonction.`,
      `Tous les types cellulaires ont nécessairement exactement la même morphologie.`,
      `Les êtres pluricellulaires comportent plusieurs types de cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Une organisation cellulaire commune n'exclut pas une forte spécialisation morphologique et fonctionnelle selon le type cellulaire.`,
    choiceExplanations: [
      `Chaque type cellulaire possède des spécificités fonctionnelles.`,
      `Les exemples de l'hématie et de l'entérocyte l'illustrent.`,
      `Le cours insiste sur leurs spécificités.`,
      `Cette diversité permet la formation de tissus spécialisés.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans l'exemple de l'hématie donné dans la fiche :`,
    choices: [
      `Elle est observée en microscopie électronique à balayage.`,
      `Sa forme est mise en relation avec son transport dans le sang.`,
      `Elle porte un pôle apical couvert de microvillosités.`,
      `Elle illustre qu'une morphologie peut être liée à une fonction.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'hématie est utilisée comme exemple d'adaptation morphologique, tandis que les microvillosités appartiennent à l'exemple de l'entérocyte.`,
    choiceExplanations: [
      `La fiche associe cet exemple à la MEB.`,
      `L'adaptation morphologique est soulignée.`,
      `Cette caractéristique appartient à l'entérocyte.`,
      `C'est le sens pédagogique de l'exemple.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'entérocyte présenté dans le cours :`,
    choices: [
      `C'est une cellule épithéliale intestinale.`,
      `Son pôle apical est bordé de microvillosités.`,
      `Les microvillosités augmentent l'absorption des nutriments.`,
      `Il est présenté comme une cellule circulante du sang.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'entérocyte est une cellule épithéliale intestinale dont le pôle apical porte des microvillosités favorisant l'absorption.`,
    choiceExplanations: [
      `C'est sa définition dans la fiche.`,
      `Cette spécialisation est explicitement décrite.`,
      `Elles augmentent la surface d'échange.`,
      `Il appartient à l'épithélium intestinal.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'organisation simplifiée d'une cellule eucaryote animale :`,
    choices: [
      `Le noyau contient un nucléole identifiable.`,
      `Le RER porte des ribosomes, contrairement au REL représenté sans ribosomes.`,
      `Le cytosquelette est représenté par des filaments dans le cytoplasme.`,
      `L'appareil de Golgi est situé à l'extérieur de la membrane plasmique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure permet de repérer les grandes structures : noyau et nucléole, RER et REL, Golgi, mitochondries, lysosomes, centrosome, vésicules et cytosquelette.`,
    choiceExplanations: [
      `Le nucléole est représenté dans le noyau.`,
      `La différence graphique correspond à leur dénomination.`,
      `Plusieurs réseaux filamenteux sont dessinés.`,
      `Il est représenté dans le cytoplasme.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Dans le modèle quantitatif simplifié du cours, une cellule de masse arbitraire égale à 100 unités contient approximativement :`,
    choices: [
      `70 unités d'eau et 30 unités de macromolécules et autres constituants.`,
      `30 unités d'eau et 70 unités de protéines.`,
      `15 unités d'eau et 85 unités d'ADN.`,
      `100 unités de protéines uniquement.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La représentation retenue par la fiche est d'environ 70 % d'eau pour 30 % de macromolécules et autres petites molécules ou ions.`,
    choiceExplanations: [
      `Cette répartition reprend directement les proportions du cours.`,
      `Les proportions sont inversées et les 70 % ne correspondent pas aux protéines.`,
      `Les valeurs ne correspondent pas au cours.`,
      `La cellule est chimiquement diversifiée et majoritairement aqueuse.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Selon les proportions indicatives du cours :`,
    choices: [
      `Les protéines constituent la fraction macromoléculaire la plus importante parmi celles chiffrées.`,
      `Les lipides et les sucres sont chacun indiqués autour de 2 %.`,
      `L'ADN est indiqué autour de 1 %.`,
      `L'eau est moins abondante que l'ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les valeurs sont des ordres de grandeur pédagogiques : protéines environ 15 %, lipides 2 %, sucres 2 %, ADN 1 %, dans une cellule composée à environ 70 % d'eau.`,
    choiceExplanations: [
      `Elles sont données à environ 15 %, contre 2 % pour les lipides et les sucres.`,
      `Les deux valeurs figurent dans la fiche.`,
      `Cette proportion est explicitement donnée.`,
      `L'eau est de très loin plus abondante.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une cellule doit à la fois être limitée et échanger avec son environnement. On peut en déduire, dans le cadre du chapitre, que :`,
    choices: [
      `La membrane matérialise la limite entre intérieur et extérieur.`,
      `La cellule réalise néanmoins des échanges avec l'extérieur.`,
      `La présence d'une membrane signifie une absence totale de communication.`,
      `La réponse à des stimuli fait partie des fonctions cellulaires.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La membrane délimite la cellule sans supprimer les échanges ni la communication avec l'environnement.`,
    choiceExplanations: [
      `C'est sa fonction de barrière.`,
      `Ces échanges figurent parmi ses fonctions.`,
      `Barrière ne signifie pas isolement absolu.`,
      `Cette capacité est citée dans le cours.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos du cytosquelette dans l'introduction du chapitre :`,
    choices: [
      `Il participe à la forme de la cellule.`,
      `Il appartient à l'organisation interne de la cellule.`,
      `Il est assimilé à la membrane plasmique.`,
      `Il peut être étudié comme une structure cellulaire à part entière.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le cytosquelette est une organisation intracellulaire distincte de la membrane, participant notamment à la forme cellulaire.`,
    choiceExplanations: [
      `Ce rôle est indiqué dans la fiche.`,
      `Il est situé dans le cytoplasme.`,
      `Ce sont deux structures distinctes.`,
      `Un chapitre ultérieur lui est consacré et il est déjà identifié ici.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans la présentation générale du noyau :`,
    choices: [
      `Il est associé à la machinerie transcriptionnelle.`,
      `Il intervient dans la division cellulaire.`,
      `Il est présenté comme un compartiment situé hors de la cellule.`,
      `Il fait partie des structures repérables sur un schéma cellulaire simplifié.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche associe le noyau à la transcription et à la division cellulaire, tout en le situant au sein de la cellule.`,
    choiceExplanations: [
      `Cette fonction est mentionnée.`,
      `Le chapitre signale ce rôle.`,
      `Il se trouve dans la cellule eucaryote.`,
      `Le noyau est un repère majeur de ces schémas.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos du transport de molécules dans la cellule :`,
    choices: [
      `Il est cité parmi les fonctions cellulaires.`,
      `Des organites et des vacuoles sont associés au trafic moléculaire dans la présentation générale.`,
      `Il rend inutile toute communication avec les cellules voisines.`,
      `Il fait partie des phénomènes que l'on peut chercher à étudier expérimentalement.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le trafic intracellulaire est une fonction générale, étudiable par des approches de culture et de marquage.`,
    choiceExplanations: [
      `Le transport intracellulaire figure dans la liste.`,
      `La fiche les relie à ce trafic.`,
      `Transport interne et communication intercellulaire sont complémentaires.`,
      `Les méthodes présentées servent à explorer les processus cellulaires.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Pour étudier les mécanismes de la vie cellulaire, le cours distingue notamment :`,
    choices: [
      `La culture cellulaire in vitro pour isoler les processus hors de l'organisme.`,
      `Les marqueurs biomoléculaires pour identifier et localiser les molécules participantes.`,
      `L'interdiction d'observer les cellules hors de l'organisme.`,
      `Des approches qui peuvent être complémentaires.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Culture cellulaire et marquages moléculaires répondent à des objectifs complémentaires : modéliser un processus et localiser ses acteurs.`,
    choiceExplanations: [
      `C'est la première stratégie présentée.`,
      `C'est la seconde stratégie générale.`,
      `La culture cellulaire repose précisément sur cette observation in vitro.`,
      `La culture fournit un modèle et les marqueurs permettent d'y suivre des molécules.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans les exemples introductifs de microscopie :`,
    choices: [
      `La MEB est associée à l'observation de l'hématie.`,
      `La MET est associée à l'observation de l'entérocyte et de ses microvillosités.`,
      `Les deux exemples servent à relier structure et fonction.`,
      `La MET est présentée comme une méthode de culture cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les deux techniques sont mobilisées pour illustrer la spécialisation morphologique des cellules.`,
    choiceExplanations: [
      `C'est l'exemple donné.`,
      `C'est l'autre exemple de la fiche.`,
      `La morphologie observée est interprétée fonctionnellement.`,
      `Il s'agit d'une méthode d'observation, non d'un type de culture.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les associations suivantes, lesquelles sont cohérentes avec le cours ?`,
    choices: [
      `Microvillosités de l'entérocyte — augmentation de l'absorption.`,
      `Cytosquelette — participation à la forme cellulaire.`,
      `Membrane — séparation de l'intérieur et de l'extérieur.`,
      `Mitochondrie — formation de la barrière externe de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La compréhension du chapitre repose sur des liens simples entre une structure et une fonction principale.`,
    choiceExplanations: [
      `C'est l'association explicitement enseignée.`,
      `Ce rôle est donné dans l'introduction.`,
      `C'est la définition fonctionnelle retenue.`,
      `La barrière externe est la membrane plasmique.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule épithéliale intestinale présente un pôle apical très riche en microvillosités. À partir des éléments du cours :`,
    choices: [
      `Cette cellule peut être identifiée comme un entérocyte.`,
      `La spécialisation apicale est cohérente avec une fonction d'absorption.`,
      `Cette observation illustre que toutes les cellules ont strictement la même forme.`,
      `Une observation en microscopie électronique peut révéler cette organisation.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'entérocyte illustre l'adaptation d'une structure spécialisée, les microvillosités, à une fonction d'absorption.`,
    choiceExplanations: [
      `L'exemple correspond à l'entérocyte.`,
      `Les microvillosités augmentent les échanges de nutriments.`,
      `Elle illustre au contraire la spécialisation morphologique.`,
      `La fiche associe l'exemple à la MET.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos de la localisation relative des grandes structures d'une cellule eucaryote animale :`,
    choices: [
      `Une structure entourant la cellule est identifiée comme membrane plasmique.`,
      `Des mitochondries, un lysosome et des vésicules sont représentés dans le cytosol.`,
      `Le nucléole est représenté à l'extérieur du noyau.`,
      `Le centrosome et le cytosquelette sont deux structures distinctes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le schéma permet de vérifier la localisation relative des grandes structures d'une cellule eucaryote animale.`,
    choiceExplanations: [
      `La légende pointe la limite externe.`,
      `Ces organites sont visibles sur le schéma.`,
      `Il se trouve à l'intérieur du noyau.`,
      `Ils disposent de légendes séparées.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `En reprenant strictement les proportions simplifiées de la fiche, quelle affirmation est correcte ?`,
    choices: [
      `La fraction de protéines est environ quinze fois plus grande que celle d'ADN.`,
      `La fraction d'ADN est environ quinze fois plus grande que celle de protéines.`,
      `Lipides et sucres représentent ensemble environ 40 %.`,
      `L'eau représente environ 7 %.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `À partir des valeurs 15 % de protéines et 1 % d'ADN, le rapport simplifié est d'environ 15 pour 1.`,
    choiceExplanations: [
      `15 % contre 1 % donne un rapport d'environ 15.`,
      `Le rapport est inversé.`,
      `Ils représentent ensemble environ 4 %.`,
      `La valeur indiquée est environ 70 %.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une équipe veut étudier la migration puis localiser une protéine impliquée dans ce phénomène. Le chapitre permet de proposer :`,
    choices: [
      `Une culture cellulaire pour observer la migration hors de l'organisme.`,
      `Un marquage moléculaire pour localiser la protéine.`,
      `Une combinaison des deux approches.`,
      `La conclusion que la migration ne peut jamais être étudiée in vitro.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le schéma expérimental le plus logique associe un modèle cellulaire in vitro et une méthode de localisation moléculaire.`,
    choiceExplanations: [
      `La culture permet d'isoler et d'observer un processus cellulaire.`,
      `Les marqueurs servent à identifier et localiser les molécules.`,
      `Le modèle de culture peut recevoir le marquage adapté.`,
      `Elle figure parmi les phénomènes étudiables en culture.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos des liens entre cellule et tissu :`,
    choices: [
      `Un tissu est constitué de cellules.`,
      `Plusieurs types cellulaires peuvent participer à l'organisation d'un organisme pluricellulaire.`,
      `La spécialisation cellulaire peut s'accompagner de différences de forme et de fonction.`,
      `La présence d'un tissu implique l'absence de toute membrane autour des cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les tissus reposent sur des cellules délimitées, souvent spécialisées et organisées pour assurer des fonctions particulières.`,
    choiceExplanations: [
      `Cette relation est posée dans l'introduction.`,
      `La diversité cellulaire est un principe clé.`,
      `Les exemples morphologiques l'illustrent.`,
      `Chaque cellule reste délimitée par sa membrane.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On observe une cellule possédant de nombreux organites, un noyau et un réseau de cytosquelette. À propos de cette observation :`,
    choices: [
      `Elle est compatible avec l'organisation générale d'une cellule eucaryote animale.`,
      `Le noyau et le cytoplasme sont deux repères distincts.`,
      `La présence d'organites signifie que la cellule ne peut pas produire d'énergie.`,
      `Le cytosquelette peut contribuer à la forme observée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'identification conjointe d'un noyau, d'organites et du cytosquelette correspond au modèle général de cellule eucaryote animale.`,
    choiceExplanations: [
      `Ces structures sont celles du schéma général.`,
      `Le noyau est un compartiment contenu dans le cytoplasme cellulaire.`,
      `La production d'énergie fait partie des fonctions cellulaires.`,
      `C'est son rôle général présenté ici.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les propositions suivantes :`,
    choices: [
      `Le cytoplasme est situé à l'intérieur de la membrane cellulaire.`,
      `Le centrosome est synonyme de nucléole.`,
      `Le REL et le RER sont deux formes de réticulum endoplasmique.`,
      `Une microvillosité de l'entérocyte est présentée comme favorisant l'absorption.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `Les termes doivent rester distincts : centrosome, nucléole, REL, RER et microvillosité ne sont pas interchangeables.`,
    choiceExplanations: [
      `La fiche le situe à l'intérieur.`,
      `Ce sont deux structures différentes.`,
      `La distinction lisse/rugueux est explicitement donnée.`,
      `C'est le rôle associé dans le cours.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos de la distinction entre fonction cellulaire et étape de la vie cellulaire :`,
    choices: [
      `La production d'énergie est citée comme une fonction.`,
      `La différenciation est citée comme une étape de la vie cellulaire.`,
      `La communication avec les cellules environnantes est citée comme une fonction.`,
      `La membrane plasmique est citée comme une étape de la vie cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours distingue des structures, des fonctions générales et des étapes de la vie cellulaire.`,
    choiceExplanations: [
      `Elle appartient à la liste des fonctions principales.`,
      `Elle fait partie de la liste croissance-division-différenciation-migration-mort.`,
      `Elle figure dans la liste.`,
      `C'est une structure, pas une étape.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour étudier la différenciation d'une cellule et la redistribution d'une molécule au cours de ce processus :`,
    choices: [
      `Un modèle de culture peut servir à suivre la différenciation.`,
      `Un marqueur moléculaire peut fournir une information de localisation.`,
      `Le choix d'une méthode dépend notamment de la nécessité d'observer une cellule vivante ou fixée.`,
      `Aucune observation microscopique ne peut être associée à ces approches.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le protocole doit articuler le modèle biologique, la molécule ciblée et les contraintes d'observation sur cellule vivante ou fixée.`,
    choiceExplanations: [
      `La culture permet d'étudier les étapes de la vie cellulaire.`,
      `C'est sa finalité générale.`,
      `Cette distinction devient centrale dans la partie sur les marquages.`,
      `Les méthodes présentées reposent sur des observations microscopiques.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'organisation générale de la cellule :`,
    choices: [
      `Une composition chimique commune n'empêche pas une spécialisation des types cellulaires.`,
      `Une structure particulière peut être reliée à une fonction particulière.`,
      `La culture cellulaire et les marquages constituent deux grandes stratégies d'étude présentées dans le chapitre.`,
      `Tous les items précédents sont faux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chapitre relie organisation, spécialisation et méthodes d'étude : la cellule possède une base commune, mais chaque type peut présenter des adaptations fonctionnelles.`,
    choiceExplanations: [
      `C'est une idée directrice de l'introduction.`,
      `Les exemples de l'hématie et de l'entérocyte le montrent.`,
      `Elles structurent la suite du cours.`,
      `Les trois premiers items sont exacts.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `organisation-generale-cellule`,
    title: `Organisation générale de la cellule`,
    description: `Définition, composition chimique et grandes structures d'une cellule eucaryote.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `structures-fonctions-cellulaires`,
    title: `Structures et fonctions cellulaires`,
    description: `Relations entre membrane, cytoplasme, organites, cytosquelette et fonctions cellulaires.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `specialisation-analyse-cellulaire`,
    title: `Spécialisation et analyse cellulaire`,
    description: `Applications sur la spécialisation morphologique, la microscopie et le choix d'une stratégie d'étude.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
