/**
 * UE14 – Biologie cellulaire – Chapitre 6
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des peroxysomes :`,
    choices: [
      `Ce sont de petits organites situés dans le cytosol.`,
      `Ils sont entourés d’une seule membrane.`,
      `Ils possèdent un génome propre.`,
      `Ils n’appartiennent pas au système endomembranaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les peroxysomes sont des organites cytosoliques à membrane unique, sans génome et indépendants du système endomembranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les peroxysomes sont présents :`,
    choices: [
      `Dans toutes les cellules eucaryotes selon la fiche.`,
      `Uniquement dans les cellules hépatiques.`,
      `Dans les cellules eucaryotes mais pas comme compartiments du SEM.`,
      `Exclusivement dans les cellules possédant un noyau en division.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `La fiche les décrit dans toutes les cellules eucaryotes, sans les rattacher au système endomembranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant la morphologie des peroxysomes :`,
    choices: [
      `Ils peuvent être ovalaires.`,
      `Ils peuvent être sphériques.`,
      `Leur taille peut varier de moins de 0,2 µm à 1,5 µm.`,
      `Ils sont toujours plus grands que 10 µm.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La morphologie est ovalaire ou sphérique et la taille varie selon le type cellulaire, de moins de 0,2 µm à environ 1,5 µm.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un hépatocyte, la fiche indique approximativement :`,
    choices: [
      `Environ 1 000 peroxysomes.`,
      `Environ 1 % du volume cellulaire total.`,
      `Un seul peroxysome géant.`,
      `Une absence normale de peroxysomes.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `L’hépatocyte est donné comme exemple d’une cellule contenant environ 1 000 peroxysomes représentant près de 1 % de son volume.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La région paracristalline d’un peroxysome :`,
    choices: [
      `Contient des enzymes oxydatives.`,
      `Appartient à sa matrice.`,
      `Correspond à son génome condensé.`,
      `Est située dans le noyau de la cellule.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La région paracristalline est une région de la matrice enrichie en enzymes oxydatives ; elle n’est pas un génome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les peroxysomes peuvent :`,
    choices: [
      `Être isolés.`,
      `Être reliés par de fins canalicules.`,
      `Former un réseau dynamique canaliculaire et particulaire.`,
      `Former obligatoirement un compartiment continu avec le RE.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ils peuvent être isolés ou organisés en réseau dynamique, mais ce réseau reste indépendant du système endomembranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de leur relation avec le système endomembranaire :`,
    choices: [
      `Leur réseau est indépendant du SEM.`,
      `Ils ne font pas partie du SEM.`,
      `Ils communiquent avec le Golgi par les quatre flux du SEM.`,
      `Le fait que leurs phospholipides proviennent du RE ne les transforme pas en compartiment du SEM.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche distingue clairement les peroxysomes du SEM, même si des phospholipides membranaires proviennent du RE par transport cytosolique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Structure et biogenèse du peroxysome](/images/training/ue14/biologie-cellulaire/peroxysomes/structure-biogenese-peroxysome.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Le peroxysome possède une membrane unique.`,
      `Une région paracristalline est représentée dans la matrice.`,
      `La figure montre un réseau canaliculaire et particulaire.`,
      `Le peroxysome représenté possède une double membrane.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure reprend les caractéristiques structurales majeures de la fiche : membrane unique, matrice enzymatique et réseau dynamique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Quel énoncé distingue correctement le peroxysome de la mitochondrie dans ce chapitre ?`,
    choices: [
      `Le peroxysome ne possède pas de génome.`,
      `Le peroxysome possède un ADN circulaire dans sa matrice.`,
      `Le peroxysome possède deux membranes.`,
      `Le peroxysome fait partie du SEM.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La fiche insiste sur l’absence de génome et sur la membrane unique du peroxysome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de l’organisation générale des peroxysomes :`,
    choices: [
      `Ils sont localisés dans le cytosol.`,
      `Leur enveloppe est constituée d’une membrane.`,
      `Leur matrice peut contenir des enzymes oxydatives.`,
      `Ils possèdent une enveloppe nucléaire propre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le peroxysome est un organite cytosolique simple, limité par une membrane et contenant une matrice enzymatique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La biogenèse de nouveaux peroxysomes repose notamment sur :`,
    choices: [
      `Le bourgeonnement d’un réseau canaliculaire préexistant.`,
      `L’intervention de petites protéines G.`,
      `L’utilisation de GTP.`,
      `La division obligatoire du noyau cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours relie le bourgeonnement du réseau peroxysomal à de petites protéines G fonctionnant avec le GTP.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les protéines destinées au peroxysome :`,
    choices: [
      `Sont synthétisées dans le cytosol.`,
      `Peuvent être membranaires ou solubles dans la matrice.`,
      `Sont adressées grâce à des signaux spécifiques.`,
      `Sont toutes traduites par un génome peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `En l’absence de génome peroxysomal, les protéines sont synthétisées dans le cytosol puis importées grâce à des signaux d’adressage.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les phospholipides de la membrane peroxysomale :`,
    choices: [
      `Proviennent du réticulum endoplasmique.`,
      `Sont transférés via un transporteur cytosolique.`,
      `Suivent obligatoirement une vésicule du Golgi.`,
      `Sont apportés selon un principe également cité pour la mitochondrie.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche décrit un transfert de phospholipides depuis le RE par un transporteur cytosolique, comme pour les mitochondries.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les récepteurs PPAR :`,
    choices: [
      `Sont des récepteurs nucléaires.`,
      `Sont contrôlés par des lipides.`,
      `Régulent la transcription de gènes codant des protéines peroxysomales.`,
      `Constituent la région paracristalline du peroxysome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les PPAR sont des récepteurs nucléaires activés par des lipides qui régulent l’expression de constituants peroxysomaux.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le déplacement intracellulaire des peroxysomes :`,
    choices: [
      `Met en jeu le cytosquelette.`,
      `Est compatible avec leur caractère dynamique.`,
      `Nécessite leur appartenance au SEM.`,
      `Peut modifier leur répartition dans la cellule.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche indique un déplacement via le cytosquelette ; ce mouvement ne suppose pas l’appartenance au SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le renouvellement des peroxysomes :`,
    choices: [
      `Est permanent.`,
      `S’accompagne de bourgeonnement de nouveaux organites.`,
      `Est illustré par une durée de vie d’environ 3,5 jours dans les hépatocytes.`,
      `N’existe qu’une seule fois au cours de la vie cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les peroxysomes sont continuellement renouvelés ; la fiche donne environ 3,5 jours dans l’hépatocyte.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La destruction des peroxysomes vieillissants :`,
    choices: [
      `Peut se faire par autophagie.`,
      `Se déroule dans les lysosomes.`,
      `Est comparée à celle des mitochondries.`,
      `Se déroule exclusivement dans le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie leur destruction à l’autophagie lysosomale, comme pour les mitochondries.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La dynamique peroxysomale associe :`,
    choices: [
      `Bourgeonnement.`,
      `Déplacement via le cytosquelette.`,
      `Renouvellement permanent.`,
      `Fusion obligatoire avec l’appareil de Golgi.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le réseau peroxysomal est dynamique mais reste indépendant du Golgi et du SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une cellule dans laquelle les petites protéines G ne fonctionnent plus correctement pourrait présenter, d’après la fiche :`,
    choices: [
      `Une perturbation du bourgeonnement peroxysomal.`,
      `Une diminution de la formation de nouveaux peroxysomes.`,
      `Une transformation des peroxysomes en lysosomes.`,
      `Une perturbation d’un mécanisme utilisant le GTP.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le bourgeonnement du réseau peroxysomal met en jeu des petites protéines G et le GTP ; son inhibition devrait donc perturber ce processus.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le fait que les peroxysomes ne possèdent pas de génome implique, dans le cadre du cours, que :`,
    choices: [
      `Leurs protéines doivent être synthétisées ailleurs.`,
      `Le cytosol assure la synthèse de leurs protéines.`,
      `Des signaux d’adressage sont nécessaires pour l’import.`,
      `Ils ne contiennent aucune protéine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Leurs protéines sont synthétisées dans le cytosol puis importées ; l’absence de génome ne signifie pas absence de protéines.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À partir de la figure suivante :

![Structure et biogenèse du peroxysome](/images/training/ue14/biologie-cellulaire/peroxysomes/structure-biogenese-peroxysome.png)

Quelle(s) interprétation(s) est(sont) correcte(s) ?`,
    choices: [
      `Le réseau préexistant peut donner naissance à de nouveaux peroxysomes.`,
      `Le bourgeonnement participe à la biogenèse.`,
      `Le peroxysome mature est limité par une membrane unique.`,
      `La figure démontre l’existence d’un génome peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure illustre le bourgeonnement d’un réseau dynamique et la structure à membrane unique, sans génome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quel enchaînement respecte la biogenèse décrite dans la fiche ?`,
    choices: [
      `Réseau peroxysomal préexistant → bourgeonnement → nouvel organite.`,
      `Protéines synthétisées dans le cytosol → adressage → import peroxysomal.`,
      `Phospholipides du RE → transporteur cytosolique → membrane peroxysomale.`,
      `Golgi → lysosome → transformation directe en peroxysome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois premiers trajets sont ceux décrits ; le peroxysome n’est pas formé par transformation d’un lysosome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule possède des peroxysomes anormalement immobiles mais de structure conservée. Le processus directement concerné dans la fiche est :`,
    choices: [
      `L’interaction avec le cytosquelette.`,
      `Le déplacement des peroxysomes.`,
      `La synthèse de l’ADN peroxysomal.`,
      `La formation des antigènes ABO.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La mobilité peroxysomale dépend du cytosquelette ; il n’existe pas d’ADN peroxysomal dans la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos de l’autonomie des peroxysomes :`,
    choices: [
      `Ils ne disposent pas d’un génome autonome.`,
      `Ils dépendent de protéines synthétisées dans le cytosol.`,
      `Ils peuvent néanmoins former un réseau propre indépendant du SEM.`,
      `Ils ne peuvent pas se renouveler.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le peroxysome est dépourvu de génome mais possède une dynamique propre, grâce à l’import de constituants et au bourgeonnement.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si le transport cytosolique des phospholipides depuis le RE est bloqué :`,
    choices: [
      `L’approvisionnement de la membrane peroxysomale peut être perturbé.`,
      `La biogenèse membranaire des peroxysomes peut être affectée.`,
      `Les peroxysomes deviennent automatiquement des compartiments du SEM.`,
      `Le transfert décrit dans la fiche ne peut plus se dérouler normalement.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le transfert de phospholipides depuis le RE est nécessaire à l’approvisionnement membranaire, sans changer l’identité du peroxysome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le cycle de vie d’un peroxysome peut comprendre :`,
    choices: [
      `Formation par bourgeonnement.`,
      `Déplacement dans la cellule.`,
      `Renouvellement permanent.`,
      `Destruction par autophagie lysosomale.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La fiche présente un organite dynamique, formé, déplacé, renouvelé puis éventuellement détruit par autophagie.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les peroxysomes et les mitochondries partagent, dans cette fiche, les caractéristiques suivantes :`,
    choices: [
      `Leurs phospholipides peuvent provenir du RE par transport cytosolique.`,
      `Ils peuvent être détruits par autophagie lysosomale.`,
      `Ils appartiennent tous deux au SEM.`,
      `Ils possèdent tous deux une membrane unique.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La fiche rapproche leur approvisionnement lipidique et leur destruction, mais pas leur appartenance au SEM ni leur nombre de membranes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une activation des PPAR peut, selon le mécanisme présenté :`,
    choices: [
      `Modifier la transcription de gènes peroxysomaux.`,
      `Influencer la quantité de protéines peroxysomales.`,
      `Agir depuis le noyau.`,
      `Créer directement du H2O2 dans la matrice sans enzyme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les PPAR régulent l’expression des constituants peroxysomaux ; la production de H2O2 dépend des oxydases.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’hépatocyte est utilisé dans la fiche pour illustrer :`,
    choices: [
      `L’abondance des peroxysomes.`,
      `Leur contribution d’environ 1 % au volume cellulaire.`,
      `Une durée de vie peroxysomale d’environ 3,5 jours.`,
      `L’absence de renouvellement peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’hépatocyte illustre à la fois leur abondance et leur renouvellement rapide.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte sur l’organisation et la biogenèse des peroxysomes ?`,
    choices: [
      `Ils sont à membrane unique et sans génome.`,
      `Ils se renouvellent à partir d’un réseau préexistant.`,
      `Ils importent des constituants synthétisés ou transportés depuis le cytosol.`,
      `Ils constituent un sous-compartiment du Golgi.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les peroxysomes forment un système propre, dépendant d’imports cytosoliques mais indépendant du Golgi et du SEM.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `organisation-generale-peroxysomes`,
    title: `Organisation générale des peroxysomes`,
    description: `Définition, localisation, membrane, génome et morphologie.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `morphologie-reseau-peroxysomal`,
    title: `Morphologie et réseau peroxysomal`,
    description: `Réseau canaliculaire, biogenèse, import des constituants et renouvellement.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `biogenese-dynamique-peroxysomes`,
    title: `Biogenèse et dynamique des peroxysomes`,
    description: `Raisonnement sur le bourgeonnement, la mobilité et le cycle de vie.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
