import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_ORDER = 4;

export const SECTION_D_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  91: ["Composition du dermatane sulfate"],
  92: ["Enchaînement du dermatane"],
  93: ["Sulfatation et taille du dermatane"],
  94: ["Localisation du dermatane"],
  95: ["Composition du kératane sulfate"],
  96: ["Enchaînement du kératane"],
  97: ["Sulfatation et taille du kératane"],
  98: ["Localisation du kératane"],
  99: ["Composition de l’héparane sulfate"],
  100: ["Enchaînement de l’héparane"],
  101: ["Sulfatation de l’héparane"],
  102: ["Taille et rôle de l’héparane"],
  103: ["Structure de l’héparine"],
  104: ["Stockage de l’héparine"],
  105: ["Usage anticoagulant de l’héparine"],
  106: ["Comparaison héparane-héparine"],
  107: ["Définition des protéoglycanes"],
  108: ["Agrégation des protéoglycanes"],
  109: ["Rôles des protéoglycanes"],
  110: ["Définition des glycoprotéines"],
  111: ["Composition glucidique des glycoprotéines"],
  112: ["NANA et glycoprotéines"],
  113: ["Liaison O-glycosidique des glycoprotéines"],
  114: ["Liaison N-glycosidique des glycoprotéines"],
  115: ["Rôles des glycoprotéines"],
  116: ["Protéoglycanes et glycoprotéines"],
  117: ["Limite du cours sur les glycolipides"],
  118: ["Définition d’un hétéroside"],
  119: ["Reconnaissance et groupes sanguins"],
  120: ["Synthèse sur GAG et hétérosides"],
};

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "dermatane-keratane-heparane",
    title: "Dermatane, kératane et héparane",
    description: "Reconnaître les motifs, les liaisons, les sulfatations et les localisations.",
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 2,
    slug: "heparane-heparine-proteoglycanes",
    title: "Héparane, héparine et protéoglycanes",
    description: "Relier structure, charge, usage clinique et organisation matricielle.",
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 3,
    slug: "glycoproteines-et-glycoconjugues",
    title: "Glycoprotéines et glycoconjugués",
    description: "Distinguer les glycoconjugués, leurs liaisons et leurs rôles biologiques.",
    stage: 'MASTER',
    sectionOrder: 4,
    items: [
      {
        type: 'GROUP',
        title: "Composition et liaisons des glycoprotéines",
        sharedStatement: "Les questions suivantes portent sur les oses, les liaisons O et N et la fraction glucidique.",
        questionOrders: [111, 112, 113, 114],
      },
      {
        type: 'GROUP',
        title: "Rôles et comparaison",
        sharedStatement: "Les questions suivantes comparent glycoprotéines et protéoglycanes et leurs fonctions.",
        questionOrders: [115, 116, 117, 118, 119],
      },
      {
        type: 'GROUP',
        title: "Synthèse du thème",
        sharedStatement: "La question suivante rassemble les points clés des GAG sulfatés et hétérosides.",
        questionOrders: [120],
      },
    ],
  },
];

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le dermatane sulfate associe :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'dermatan-keratan',
    },
    choices: [
      "Acide L-iduronique.",
      "N-acétylgalactosamine.",
      "Une liaison α(1→3) au sein du dimère.",
      "Acide D-glucuronique exclusivement.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le motif du dermatane contient iduronate L et N-acétylgalactosamine.",
    choiceExplanations: [
      "Vrai. C’est l’acide uronique caractéristique.",
      "Vrai. C’est l’osamine du motif.",
      "Vrai. Cette liaison est indiquée.",
      "Faux. L’iduronate L est mis en avant.",
    ],
  },
  {
    order: 92,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans le dermatane sulfate :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'dermatan-keratan',
    },
    choices: [
      "Les dimères sont liés par une liaison β(1→4).",
      "La liaison interne du dimère est α(1→3).",
      "La chaîne alterne un acide uronique et une osamine.",
      "Toutes les liaisons sont α(1→6).",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le dermatane alterne des liaisons α1,3 et β1,4.",
    choiceExplanations: [
      "Vrai. C’est la liaison inter-dimères.",
      "Vrai. Elle unit les deux résidus du motif.",
      "Vrai. C’est un GAG typique.",
      "Faux. Cette liaison n’est pas décrite ici.",
    ],
  },
  {
    order: 93,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le dermatane sulfate peut :",
    choices: [
      "Être sulfaté en C2 de l’acide iduronique.",
      "Être sulfaté en C4 de la galactosamine.",
      "Comporter environ 50 résidus.",
      "Être totalement dépourvu de sulfate.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les positions C2 et C4 sont indiquées, pour une chaîne d’environ 50 résidus.",
    choiceExplanations: [
      "Vrai. C’est une possibilité.",
      "Vrai. C’est l’autre possibilité décrite.",
      "Vrai. n = 50 est indiqué.",
      "Faux. Son nom et sa structure impliquent une sulfatation.",
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le dermatane sulfate :",
    choices: [
      "A été isolé initialement du derme.",
      "Se trouve dans la matrice extracellulaire de tous les tissus selon la fiche.",
      "Est un GAG sulfaté.",
      "Est exclusivement présent dans la lumière intestinale.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le dermatane est un GAG de la MEC, initialement isolé du derme.",
    choiceExplanations: [
      "Vrai. Cette origine est donnée.",
      "Vrai. Sa distribution est large.",
      "Vrai. La sulfatation est structurale.",
      "Faux. Ce n’est pas sa localisation décrite.",
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le kératane sulfate associe :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'dermatan-keratan',
    },
    choices: [
      "Du galactose.",
      "De la N-acétylglucosamine.",
      "Une liaison β(1→4) au sein du dimère.",
      "Un acide uronique obligatoire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le kératane se distingue des autres GAG cités par l’association galactose–N-acétylglucosamine sans acide uronique.",
    choiceExplanations: [
      "Vrai. C’est l’ose simple du motif.",
      "Vrai. C’est l’osamine.",
      "Vrai. Cette liaison les unit.",
      "Faux. Il ne contient pas d’acide uronique dans le motif donné.",
    ],
  },
  {
    order: 96,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans le kératane sulfate :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'dermatan-keratan',
    },
    choices: [
      "Les dimères sont liés par des liaisons β(1→3).",
      "La liaison interne est β(1→4).",
      "Le motif alterne galactose et N-acétylglucosamine.",
      "Les dimères sont liés par des liaisons peptidiques.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le kératane alterne les liaisons β1,4 et β1,3.",
    choiceExplanations: [
      "Vrai. C’est la liaison inter-dimères.",
      "Vrai. Elle unit les résidus du motif.",
      "Vrai. C’est l’alternance structurale.",
      "Faux. Il s’agit de liaisons osidiques.",
    ],
  },
  {
    order: 97,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le kératane sulfate :",
    choices: [
      "Peut être sulfaté en C6 du galactose.",
      "Peut être sulfaté en C6 de la glucosamine.",
      "Est décrit avec environ 10 résidus.",
      "Est toujours plus long que l’acide hyaluronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux résidus peuvent être sulfatés en C6 ; la chaîne décrite est courte.",
    choiceExplanations: [
      "Vrai. Cette position est indiquée.",
      "Vrai. Cette position est également indiquée.",
      "Vrai. n = 10 est donné.",
      "Faux. L’acide hyaluronique atteint des centaines à milliers de résidus.",
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le kératane sulfate :",
    choices: [
      "A été isolé initialement de la cornée.",
      "Se trouve dans la MEC de tous les tissus selon la fiche.",
      "Peut être associé aux chondroïtines et dermatanes sulfates.",
      "Est décrit comme le GAG le plus abondant.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le kératane est peu abondant, initialement isolé de la cornée et associé à d’autres GAG.",
    choiceExplanations: [
      "Vrai. Cette origine explique son nom.",
      "Vrai. La fiche le dit présent dans la MEC.",
      "Vrai. Cette association est citée.",
      "Faux. Il est retrouvé en faible quantité.",
    ],
  },
  {
    order: 99,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’héparane sulfate peut comporter :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "Acide L-iduronique et glucosamine liés en α(1→4).",
      "Acide D-glucuronique et glucosamine liés en β(1→4).",
      "Un mélange de deux structures.",
      "Uniquement du galactose et aucune osamine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’héparane sulfate est hétérogène et combine des motifs iduronate ou glucuronate avec la glucosamine.",
    choiceExplanations: [
      "Vrai. C’est l’un des motifs.",
      "Vrai. C’est l’autre motif.",
      "Vrai. La remarque de la fiche le souligne.",
      "Faux. La glucosamine est centrale.",
    ],
  },
  {
    order: 100,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans l’héparane sulfate :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "Les dimères sont reliés par une liaison α(1→4).",
      "Les motifs peuvent différer par la nature de l’acide uronique.",
      "La glucosamine participe aux motifs.",
      "La chaîne est un homoglycane de fructose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’héparane est un hétéroglycane à motifs variables, enchaînés en α1,4.",
    choiceExplanations: [
      "Vrai. C’est la liaison inter-dimères.",
      "Vrai. Iduronique L ou glucuronique D sont cités.",
      "Vrai. Elle est l’osamine commune.",
      "Faux. Plusieurs résidus différents sont présents.",
    ],
  },
  {
    order: 101,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "L’héparane sulfate peut être O-sulfaté :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "En C2 de l’acide uronique.",
      "En C6 de la glucosamine.",
      "En C3 de la glucosamine, plus rarement.",
      "Uniquement en C1 du galactose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les positions C2, C6 et plus rarement C3 sont indiquées.",
    choiceExplanations: [
      "Vrai. Cette position concerne l’acide uronique.",
      "Vrai. C’est la position principale sur la glucosamine.",
      "Vrai. La fiche précise que cette position est plus rare.",
      "Faux. Le galactose n’est pas le résidu caractéristique.",
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’héparane sulfate :",
    choices: [
      "Comporte environ 20 à 100 résidus.",
      "A été isolé initialement du foie.",
      "Joue un rôle dans la signalisation cellulaire.",
      "Est absent de la MEC.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’héparane est un GAG de taille intermédiaire, largement présent et impliqué dans la signalisation.",
    choiceExplanations: [
      "Vrai. C’est l’intervalle donné.",
      "Vrai. Cette origine est citée.",
      "Vrai. C’est son rôle mis en avant.",
      "Faux. Il se trouve dans la MEC de tous les tissus selon la fiche.",
    ],
  },
  {
    order: 103,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’héparine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "Est très proche de l’héparane sulfate.",
      "Possède des chaînes plus courtes, autour de 10 résidus.",
      "Est fortement sulfatée.",
      "Est identique à l’acide hyaluronique non sulfaté.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’héparine est une forme courte et très sulfatée, proche de l’héparane.",
    choiceExplanations: [
      "Vrai. La proximité structurale est soulignée.",
      "Vrai. n = 10 est indiqué.",
      "Vrai. La fiche note « sulfatée ++++ ».",
      "Faux. L’acide hyaluronique n’est pas sulfaté et est beaucoup plus long.",
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’héparine est :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "Stockée dans les granulations des mastocytes.",
      "Libérée lors de la dégranulation en cas de besoin.",
      "Une réserve de glucose du muscle.",
      "Associée à des cellules immunitaires.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’héparine est stockée dans les mastocytes et libérée par dégranulation.",
    choiceExplanations: [
      "Vrai. C’est son lieu de stockage.",
      "Vrai. C’est le mécanisme de libération décrit.",
      "Faux. Cette fonction appartient au glycogène.",
      "Vrai. Les mastocytes sont des cellules de l’immunité.",
    ],
  },
  {
    order: 105,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "L’héparine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "A une activité anticoagulante puissante.",
      "Est utilisée dans des médicaments.",
      "Peut être employée dans des situations à risque de thrombose.",
      "Est utilisée pour favoriser directement la coagulation.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La forte sulfatation de l’héparine est associée à son activité anticoagulante thérapeutique.",
    choiceExplanations: [
      "Vrai. C’est son rôle clinique majeur.",
      "Vrai. La fiche le précise.",
      "Vrai. C’est l’indication citée.",
      "Faux. Elle limite la coagulation.",
    ],
  },
  {
    order: 106,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Comparer héparane sulfate et héparine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "Leurs structures sont proches.",
      "L’héparine est plus courte dans la description donnée.",
      "L’héparine est beaucoup plus sulfatée.",
      "L’héparane est présenté comme l’anticoagulant médicamenteux principal.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’héparine se distingue par des chaînes courtes, une forte sulfatation et un usage anticoagulant.",
    choiceExplanations: [
      "Vrai. Elles appartiennent à la même famille structurale.",
      "Vrai. Environ 10 contre 20 à 100 résidus.",
      "Vrai. C’est une différence majeure.",
      "Faux. L’usage médicamenteux est attribué à l’héparine.",
    ],
  },
  {
    order: 107,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les protéoglycanes :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'proteoglycan-aggregate',
    },
    choices: [
      "Sont formés de GAG sulfatés accrochés à une protéine cœur.",
      "Correspondent à des GAG non libres dans les tissus.",
      "Sont des hétérosides.",
      "Sont uniquement constitués de glucose libre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Un protéoglycane associe une protéine cœur et une ou plusieurs chaînes de GAG.",
    choiceExplanations: [
      "Vrai. C’est leur structure.",
      "Vrai. Les GAG sont liés à la protéine.",
      "Vrai. Ils associent une partie glucidique et non glucidique.",
      "Faux. Leur structure est beaucoup plus complexe.",
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les protéoglycanes peuvent :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'proteoglycan-aggregate',
    },
    choices: [
      "Être non agrégés.",
      "Être agrégés sur un long filament d’acide hyaluronique.",
      "Former des ensembles avec plusieurs protéines cœur.",
      "Être obligatoirement isolés et sans interaction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Plusieurs protéoglycanes peuvent s’assembler autour d’un filament d’acide hyaluronique.",
    choiceExplanations: [
      "Vrai. Cette forme existe.",
      "Vrai. C’est le modèle agrégé décrit.",
      "Vrai. Chaque protéoglycane comporte sa protéine cœur.",
      "Faux. L’agrégation est fréquente.",
    ],
  },
  {
    order: 109,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les rôles cités pour les protéoglycanes comprennent :",
    choices: [
      "L’hydratation.",
      "L’amortissement des chocs.",
      "La signalisation cellulaire.",
      "La production directe d’ATP mitochondrial.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les protéoglycanes participent aux propriétés mécaniques et à la communication de la matrice.",
    choiceExplanations: [
      "Vrai. Les GAG retiennent l’eau.",
      "Vrai. Les agrégats résistent à la compression.",
      "Vrai. Ce rôle est cité.",
      "Faux. Ce n’est pas une fonction décrite.",
    ],
  },
  {
    order: 110,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les glycoprotéines :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycoprotein-linkages',
    },
    choices: [
      "Sont à la fois des hétérosides et des hétéroprotéines.",
      "Associent une fraction protéique et une fraction glucidique.",
      "Ont une fraction glucidique souvent ramifiée.",
      "Sont des homoglycanes purs sans protéine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Une glycoprotéine associe une protéine à des chaînes glucidiques ramifiées.",
    choiceExplanations: [
      "Vrai. Les deux classifications s’appliquent.",
      "Vrai. C’est leur définition.",
      "Vrai. La fiche insiste sur les ramifications.",
      "Faux. Une protéine est nécessaire.",
    ],
  },
  {
    order: 111,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La fraction glucidique des glycoprotéines peut contenir :",
    choices: [
      "D-mannose et D-galactose.",
      "Des osamines N-acétylées.",
      "Du L-fucose.",
      "Uniquement un seul glucose non ramifié.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les glycoprotéines utilisent une grande diversité d’oses et dérivés.",
    choiceExplanations: [
      "Vrai. Ces oses simples sont cités.",
      "Vrai. Glucosamine et galactosamine peuvent être N-acétylées.",
      "Vrai. Le 6-désoxy-L-galactose est cité.",
      "Faux. La fraction est souvent très ramifiée et diverse.",
    ],
  },
  {
    order: 112,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’acide N-acétylneuraminique ou NANA :",
    choices: [
      "Peut entrer dans la fraction glucidique des glycoprotéines.",
      "Est un acide sialique.",
      "Contribue à la diversité des chaînes glucidiques.",
      "Est une protéine cœur.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le NANA est un dérivé d’ose acide pouvant terminer des chaînes glycoprotéiques.",
    choiceExplanations: [
      "Vrai. Il est cité parmi les composants.",
      "Vrai. C’est son autre appellation.",
      "Vrai. Il ajoute une charge et une identité structurale.",
      "Faux. Il appartient à la partie glucidique.",
    ],
  },
  {
    order: 113,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une liaison O-glycosidique entre sucre et protéine implique dans la fiche :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycoprotein-linkages',
    },
    choices: [
      "L’extrémité réductrice du sucre.",
      "La fonction alcool de la sérine ou de la thréonine.",
      "Un atome d’oxygène.",
      "La fonction amide de l’asparagine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La O-glycosylation relie le sucre à l’oxygène d’un groupement hydroxyle de Ser ou Thr.",
    choiceExplanations: [
      "Vrai. C’est la partie glucidique réactive.",
      "Vrai. Ces deux acides aminés portent un alcool.",
      "Vrai. Il donne son nom à la liaison.",
      "Faux. Cette fonction correspond à la N-glycosylation décrite.",
    ],
  },
  {
    order: 114,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une liaison N-glycosidique entre sucre et protéine :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glycoprotein-linkages',
    },
    choices: [
      "Implique une fonction amide d’acide aminé dans la fiche.",
      "Peut concerner l’asparagine.",
      "Est distinguée de la liaison O-glycosidique.",
      "Implique exclusivement la fonction alcool de la sérine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La N-glycosylation met en jeu un azote de fonction amide, notamment celui de l’asparagine.",
    choiceExplanations: [
      "Vrai. C’est le type de fonction indiqué.",
      "Vrai. Cet acide aminé est cité.",
      "Vrai. Les deux modes de liaison sont opposés.",
      "Faux. La sérine intervient dans la O-glycosylation.",
    ],
  },
  {
    order: 115,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La fraction sucrée des glycoprotéines contribue à :",
    choices: [
      "La reconnaissance spécifique.",
      "Les interactions cellulaires.",
      "Le repliement et la protection contre les protéases.",
      "La spécificité des groupes sanguins.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Les chaînes glucidiques assurent de nombreux rôles de reconnaissance, de structure et de protection.",
    choiceExplanations: [
      "Vrai. C’est un rôle majeur.",
      "Vrai. Les contacts cellulaires sont cités.",
      "Vrai. Ces deux fonctions sont mentionnées.",
      "Vrai. Les déterminants de groupes sanguins sont glucidiques.",
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Comparer protéoglycanes et glycoprotéines :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'proteoglycan-aggregate',
    },
    choices: [
      "Les deux associent une partie glucidique à une protéine.",
      "Les protéoglycanes portent des chaînes de GAG sur une protéine cœur.",
      "Les glycoprotéines possèdent des chaînes glucidiques ramifiées et diverses.",
      "Les deux sont des protéines dépourvues de glucides.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux sont des glycoconjugués, mais la nature et l’organisation de leurs glucides diffèrent.",
    choiceExplanations: [
      "Vrai. Ils sont des hétérosides.",
      "Vrai. C’est leur définition.",
      "Vrai. C’est la description donnée.",
      "Faux. La composante glucidique est essentielle.",
    ],
  },
  {
    order: 117,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Dans cette fiche :",
    choices: [
      "Les glycolipides sont mentionnés mais non développés.",
      "Les protéoglycanes et glycoprotéines sont développés.",
      "Il est possible d’affirmer que la structure détaillée des glycolipides n’est pas fournie ici.",
      "Les glycolipides constituent la totalité du chapitre.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La fiche signale les glycolipides sans les traiter dans cette séquence.",
    choiceExplanations: [
      "Vrai. La dernière ligne le précise.",
      "Vrai. Ils occupent la section sur les hétérosides.",
      "Vrai. Il faut respecter cette limite documentaire.",
      "Faux. Le chapitre couvre de nombreux autres osides.",
    ],
  },
  {
    order: 118,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Un hétéroside :",
    choices: [
      "Associe une partie glucidique et une partie non glucidique.",
      "Comporte un aglycone.",
      "Peut être représenté par une glycoprotéine.",
      "Est nécessairement composé exclusivement d’oses.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les hétérosides réunissent une fraction glucidique et un aglycone.",
    choiceExplanations: [
      "Vrai. C’est la définition.",
      "Vrai. C’est le nom de la partie non glucidique.",
      "Vrai. La protéine constitue la partie non glucidique.",
      "Faux. Cette définition correspondrait à un holoside.",
    ],
  },
  {
    order: 119,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les chaînes glucidiques des glycoprotéines peuvent intervenir dans :",
    choices: [
      "La reconnaissance spécifique.",
      "Les interactions entre cellules.",
      "La spécificité des groupes sanguins.",
      "L’absence totale de signalisation cellulaire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les motifs glucidiques de surface participent à l’identité et aux interactions cellulaires.",
    choiceExplanations: [
      "Vrai. C’est explicitement cité.",
      "Vrai. Les interactions cellulaires sont citées.",
      "Vrai. Les groupes sanguins en sont un exemple.",
      "Faux. Les glucides contribuent au contraire à la communication.",
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une synthèse correcte comprend :",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'heparan-heparin',
    },
    choices: [
      "L’héparine est fortement sulfatée et anticoagulante.",
      "Les protéoglycanes associent GAG et protéine cœur.",
      "Les glycoprotéines peuvent être O- ou N-glycosylées.",
      "Le kératane sulfate est constitué uniquement d’acide iduronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les GAG sulfatés et les glycoconjugués se distinguent par leurs motifs, leurs liaisons et leurs rôles.",
    choiceExplanations: [
      "Vrai. C’est son intérêt clinique majeur.",
      "Vrai. C’est leur structure fondamentale.",
      "Vrai. Les deux modes de liaison sont décrits.",
      "Faux. Il associe galactose et N-acétylglucosamine.",
    ],
  },
];
