/**
 * UE14 – Biologie cellulaire – Chapitre 8
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SYNTHESIS_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l’organisation générale du noyau :`,
    choices: [
      `L’enveloppe nucléaire comporte deux membranes.`,
      `Les pores contrôlent les échanges avec le cytoplasme.`,
      `La matrice nucléaire organise le nucléoplasme.`,
      `Le noyau est un compartiment totalement fermé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elles sont séparées par l’espace périnucléaire.`,
      `Exact. Ils assurent import, export et diffusion passive.`,
      `Exact. Lamina et réseau NuMA constituent le nucléosquelette.`,
      `Faux. Les pores permettent des échanges sélectifs.`,
    ],
  },
  {
    order: 122,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les relations structure–fonction :`,
    choices: [
      `Lamina — forme et résistance du noyau.`,
      `NLS — import des protéines nucléaires.`,
      `Nucléole — synthèse et maturation des ARNr.`,
      `Hétérochromatine — transcription maximale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle constitue le squelette périphérique.`,
      `Exact. Il est reconnu par la machinerie d’import.`,
      `Exact. Il organise la biogenèse ribosomale.`,
      `Faux. La condensation réduit l’activité.`,
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le noyau interphasique peut comporter simultanément :`,
    choices: [
      `Des territoires chromosomiques.`,
      `De l’euchromatine et de l’hétérochromatine.`,
      `Un ou plusieurs nucléoles.`,
      `Un fuseau mitotique complet à l’intérieur d’une enveloppe intacte.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Chaque chromosome occupe un volume restreint.`,
      `Exact. Les niveaux de compaction coexistent.`,
      `Exact. Ils compartimentent le nucléoplasme.`,
      `Faux. Le fuseau se forme lors de la mitose après désorganisation nucléaire.`,
    ],
  },
  {
    order: 124,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une protéine nucléaire après mitose :`,
    choices: [
      `Peut utiliser son NLS pour retourner dans le noyau.`,
      `Traverse un pore nucléaire après reformation de l’enveloppe.`,
      `Doit recevoir un nouvel ADN pour entrer.`,
      `Peut être reconnue par un complexe d’importation.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le signal n’est pas excisé.`,
      `Exact. L’import actif reprend.`,
      `Faux. L’import dépend d’un signal peptidique, pas d’ADN.`,
      `Exact. Les échanges actifs utilisent une machinerie spécifique.`,
    ],
  },
  {
    order: 125,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la dynamique mitotique du noyau :`,
    choices: [
      `L’enveloppe se fragmente au début.`,
      `La chromatine se condense en chromosomes.`,
      `Les nucléoles disparaissent transitoirement.`,
      `Le noyau reste inchangé pendant toute la division.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle se fond dans le RE.`,
      `Exact. La compaction maximale facilite la répartition.`,
      `Exact. Ils se réorganisent après la mitose.`,
      `Faux. Il subit une profonde réorganisation.`,
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une mutation de la lamina et une mutation du NLS n’auraient pas le même effet car :`,
    choices: [
      `La lamina touche surtout la structure nucléaire.`,
      `Le NLS touche surtout l’adressage d’une protéine.`,
      `Les deux mutations touchent exactement la même molécule.`,
      `Elles peuvent néanmoins toutes deux perturber le fonctionnement nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle soutient forme et enveloppe.`,
      `Exact. Il conditionne son import.`,
      `Faux. Lamines et protéines à NLS sont distinctes.`,
      `Exact. Structure et transport sont tous deux essentiels.`,
    ],
  },
  {
    order: 127,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une région d’ADN active en transcription est probablement :`,
    choices: [
      `Décondensée.`,
      `Proche d’une machinerie de polymérase ancrée à la matrice.`,
      `Sous forme de chromosome mitotique.`,
      `Associée à des nucléosomes modulables.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. L’euchromatine est accessible.`,
      `Exact. La matrice organise les sites de synthèse.`,
      `Faux. Cet état est trop condensé.`,
      `Exact. La compaction locale peut varier.`,
    ],
  },
  {
    order: 128,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une cellule très active en synthèse protéique peut présenter :`,
    choices: [
      `Un nucléole développé.`,
      `Une euchromatine abondante.`,
      `Une disparition permanente des pores nucléaires.`,
      `Un trafic important d’ARN et de sous-unités ribosomales.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La production de sous-unités ribosomales est élevée.`,
      `Exact. De nombreux gènes peuvent être transcrits.`,
      `Faux. Les échanges sont indispensables.`,
      `Exact. Ces molécules doivent être exportées.`,
    ],
  },
  {
    order: 129,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les pores nucléaires et le nucléole sont fonctionnellement liés car :`,
    choices: [
      `Les sous-unités ribosomales produites dans le nucléole sont exportées par les pores.`,
      `Les protéines nécessaires à la biogenèse ribosomale peuvent entrer par les pores.`,
      `Le nucléole constitue lui-même un pore.`,
      `Ils participent ensemble au flux d’information du noyau vers le cytoplasme.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elles rejoignent le cytoplasme.`,
      `Exact. Les protéines nucléaires sont importées.`,
      `Faux. Ce sont des structures distinctes.`,
      `Exact. La production d’ARNr et l’export des sous-unités sont coordonnées.`,
    ],
  },
  {
    order: 130,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Synthèse transversale du chapitre :`,
    choices: [
      `Le noyau combine architecture, stockage, expression et transport.`,
      `La structure de la chromatine conditionne l’activité des gènes.`,
      `L’enveloppe et les pores assurent la séparation sans isolement total.`,
      `Le noyau est un simple réservoir passif d’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ces fonctions sont intégrées.`,
      `Exact. La compaction régule l’accessibilité.`,
      `Exact. Le trafic reste contrôlé.`,
      `Faux. Il est le siège d’activités métaboliques et structurales complexes.`,
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une équipe micro-injecte dans le cytoplasme une protéine entière, sa partie globulaire et sa partie effilée. Quelle(s) observation(s) permettent d’identifier le NLS ?`,
    choices: [
      `La protéine entière rejoint le noyau.`,
      `La partie effilée seule rejoint le noyau.`,
      `La partie globulaire seule reste cytoplasmique.`,
      `Les trois fractions restent obligatoirement cytoplasmiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle possède le signal fonctionnel.`,
      `Exact. Elle suffit à l’import.`,
      `Exact. Elle ne porte pas le signal d’entrée.`,
      `Faux. Les fractions contenant la partie effilée sont importées.`,
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une seconde expérience injecte la partie globulaire directement dans le noyau. Elle y reste. On en déduit que :`,
    choices: [
      `La partie globulaire peut assurer une rétention nucléaire.`,
      `La partie effilée n’est pas nécessaire à l’ancrage.`,
      `La partie globulaire possède forcément le NLS.`,
      `Import et rétention sont deux fonctions distinctes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle ne ressort pas pendant l’expérience.`,
      `Exact. Elle est surtout nécessaire à l’import.`,
      `Faux. Son injection cytoplasmique n’aboutit pas à un import.`,
      `Exact. Les expériences permettent de les dissocier.`,
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine T sauvage est nucléaire, tandis qu’une protéine T portant une substitution Lys→Thr reste cytoplasmique. Cette comparaison montre :`,
    choices: [
      `La nécessité d’une séquence NLS correcte.`,
      `Le rôle des acides aminés basiques du motif.`,
      `L’indépendance totale de la localisation vis-à-vis de la séquence.`,
      `La possibilité d’utiliser une mutation pour tester un signal d’adressage.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Une seule substitution perturbe la localisation.`,
      `Exact. Le NLS sauvage est riche en Lys/Arg.`,
      `Faux. La mutation modifie précisément la localisation.`,
      `Exact. La comparaison sauvage/mutée apporte une preuve fonctionnelle.`,
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un pore nucléaire est observé avec un complexe importé et un complexe exporté au même instant. On conclut :`,
    choices: [
      `Les échanges sont bidirectionnels.`,
      `Les échanges peuvent être simultanés.`,
      `Le pore est un complexe dynamique de transport.`,
      `L’ADN chromosomique doit nécessairement sortir.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les flux vont dans les deux sens.`,
      `Exact. Les deux cargaisons partagent un même pore.`,
      `Exact. Il ne constitue pas une simple ouverture passive.`,
      `Faux. L’expérience concerne protéines et ARNt, non l’ADN.`,
    ],
  },
  {
    order: 135,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule présente une rupture de la lamina, une forme nucléaire irrégulière et une désorganisation des LAD. Cela est cohérent avec :`,
    choices: [
      `Une altération du squelette périphérique nucléaire.`,
      `Une perturbation de l’organisation chromatinienne périphérique.`,
      `Une mutation obligatoire de l’ADNr.`,
      `Une altération des lamines A, B ou C.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La lamina assure la forme et l’ancrage.`,
      `Exact. Les LAD s’associent à la lamina.`,
      `Faux. Ce n’est pas nécessaire pour expliquer ces anomalies.`,
      `Exact. Ces protéines constituent la lamina.`,
    ],
  },
  {
    order: 136,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une région passe d’hétérochromatine à euchromatine. Les conséquences possibles sont :`,
    choices: [
      `Une diminution de la condensation.`,
      `Une meilleure accessibilité aux polymérases.`,
      `Une disparition de tous les nucléosomes.`,
      `Une activation transcriptionnelle locale.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. L’euchromatine est décondensée.`,
      `Exact. La transcription ou la duplication deviennent possibles.`,
      `Faux. La chromatine décondensée reste nucléosomique.`,
      `Exact. La décondensation peut permettre l’expression des gènes.`,
    ],
  },
  {
    order: 137,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une altération du nucléole réduisant la maturation des ARNr peut entraîner :`,
    choices: [
      `Une diminution de la production des sous-unités ribosomales.`,
      `Une perturbation de la traduction cytoplasmique.`,
      `Une augmentation directe de la sortie de l’ADN.`,
      `Une modification de l’activité d’une cellule à forte demande protéique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les ARNr sont indispensables à leur assemblage.`,
      `Exact. Moins de ribosomes fonctionnels sont formés.`,
      `Faux. L’ADN reste nucléaire.`,
      `Exact. Ces cellules dépendent d’une biogenèse ribosomale efficace.`,
    ],
  },
  {
    order: 138,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule tumorale présente un rapport nucléocytoplasmique élevé, une anisocaryose et plusieurs nucléoles irréguliers :`,
    choices: [
      `Ces éléments constituent des critères morphologiques compatibles avec une anomalie tumorale.`,
      `Ils doivent être comparés aux cellules normales du même prélèvement.`,
      `Ils prouvent à eux seuls le type moléculaire précis de la tumeur.`,
      `La texture de la chromatine doit également être examinée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ils sont explicitement recherchés.`,
      `Exact. La comparaison contextualise le diagnostic.`,
      `Faux. L’analyse morphologique ne suffit pas à toutes les caractérisations.`,
      `Exact. La chromatine grossière est un autre critère cité.`,
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les cinq figures suivantes résument l’organisation du noyau, les échanges nucléocytoplasmiques, la compaction de la chromatine et l’organisation du nucléole.

![Structure du noyau](/images/training/ue14/biologie-cellulaire/noyau/structure-noyau-enveloppe.png)

![Expérience NLS](/images/training/ue14/biologie-cellulaire/noyau/experience-nucleoplasmine-NLS.png)

![Pore nucléaire](/images/training/ue14/biologie-cellulaire/noyau/pore-nucleaire-echanges.png)

![Compaction de la chromatine](/images/training/ue14/biologie-cellulaire/noyau/compaction-chromatine.png)

![Territoires et nucléole](/images/training/ue14/biologie-cellulaire/noyau/territoires-nucleole.png)

En croisant ces figures, quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `L’architecture nucléaire est liée au RER et aux pores.`,
      `Le NLS permet l’import sélectif de protéines.`,
      `La chromatine et le nucléole sont organisés à plusieurs échelles.`,
      `Le noyau est dépourvu de toute organisation interne.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. L’enveloppe et les échanges sont structurés.`,
      `Exact. Les expériences de nucléoplasmine l’établissent.`,
      `Exact. Compaction, territoires et biogenèse ribosomale sont intégrés.`,
      `Faux. L’ensemble du chapitre démontre le contraire.`,
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Conclusion générale :`,
    choices: [
      `Le noyau protège l’ADN tout en permettant son expression contrôlée.`,
      `Le nucléosquelette organise forme, chromatine et sites fonctionnels.`,
      `Les pores assurent le dialogue avec le cytoplasme.`,
      `Le nucléole est un organite membranaire indépendant du noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La compaction et les échanges sont régulés.`,
      `Exact. Lamina, NuMA, LAD et MAR interviennent.`,
      `Exact. Import de protéines et export d’ARN sont essentiels.`,
      `Faux. Il s’agit d’un compartiment nucléaire sans membrane propre.`,
    ],
  },
];

export const SYNTHESIS_QUIZZES: SeedQuiz[] = [
  {
    order: 13,
    slug: `noyau-synthese-transversale`,
    title: `Organisation et fonctions du noyau`,
    description: `Révision transversale de l’enveloppe, des échanges, de la matrice et de la chromatine.`,
    stage: 'PRACTICE',
    sectionOrder: 5,
    questionOrders: [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
  },
  {
    order: 14,
    slug: `synthese-experimentale-noyau`,
    title: `Synthèse expérimentale du chapitre`,
    description: `Situations intégratives proches de l’examen et questions liées.`,
    stage: 'MASTER',
    sectionOrder: 5,
    items: [
      { type: 'GROUP', title: `Import nucléaire de la nucléoplasmine`, sharedStatement: `Une équipe reprend les expériences de micro-injection de la nucléoplasmine et de ses fragments afin de distinguer import et rétention nucléaires.`, questionOrders: [131, 132] },
      { type: 'GROUP', title: `NLS et pore nucléaire`, sharedStatement: `Une seconde équipe compare une protéine à NLS sauvage ou muté et observe les flux bidirectionnels au niveau des pores.`, questionOrders: [133, 134] },
      { type: 'GROUP', title: `Architecture et activité nucléaires`, sharedStatement: `Des anomalies touchant la lamina, la chromatine et le nucléole sont ensuite analysées.`, questionOrders: [135, 136, 137] },
      { type: 'QUESTION', questionOrder: 138 },
      { type: 'QUESTION', questionOrder: 139 },
      { type: 'QUESTION', questionOrder: 140 },
    ],
  },
];
