/**
 * Cartographie éditoriale V2
 * UE14 – Chimie organique – Chapitre 2.1
 * Nomenclature chimique et fonctions organiques
 */

export const UE14_CH5_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 1,
    slug: 'decouvrir-formule-brute-composition-molecules-organiques',
    title: `Formule brute et composition des molécules organiques`,
    description: `Repères fondamentaux sur la nomenclature, la formule brute, les valences usuelles et la microanalyse chimique.`,
    stage: 'DISCOVER' as const,
    questionOrders: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    sectionOrder: 1,
    order: 2,
    slug: 'sentrainer-formule-brute-composition-molecules-organiques',
    title: `Formule brute et composition des molécules organiques`,
    description: `Applications sur le décompte des atomes, la masse molaire, les pourcentages massiques et le passage formule empirique–formule brute.`,
    stage: 'PRACTICE' as const,
    questionOrders: [11,12,13,14,15,16,17,18,19,20,21,22],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'decouvrir-fonctions-chimiques-oxygenees',
    title: `Fonctions chimiques oxygénées`,
    description: `Repères sur les alcools, acides carboxyliques, éthers, esters, cétones, aldéhydes, peroxydes et carbonates.`,
    stage: 'DISCOVER' as const,
    questionOrders: [23,24,25,26,27,28,29,30,31,32],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'sentrainer-fonctions-chimiques-oxygenees',
    title: `Fonctions chimiques oxygénées`,
    description: `Reconnaissance transversale des fonctions oxygénées dans des molécules simples, polyfonctionnelles et d’intérêt médical.`,
    stage: 'PRACTICE' as const,
    questionOrders: [33,34,35,36,37,38,39,40,41,42,43,44],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'decouvrir-fonctions-azotees-soufrees',
    title: `Fonctions azotées et soufrées`,
    description: `Repères sur les amines, amides, nitriles, carbamates, ammoniums quaternaires et thiols.`,
    stage: 'DISCOVER' as const,
    questionOrders: [45,46,47,48,49,50,51,52,53,54],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'sentrainer-fonctions-azotees-soufrees',
    title: `Fonctions azotées et soufrées`,
    description: `Applications sur la distinction amine/amide/ammonium, les molécules polyfonctionnelles et la reconnaissance des motifs azotés et soufrés.`,
    stage: 'PRACTICE' as const,
    questionOrders: [55,56,57,58,59,60,61,62,63,64,65,66],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'decouvrir-chaines-carbonees-nomenclature-base',
    title: `Chaînes carbonées et nomenclature`,
    description: `Repères sur la convention rémoise de classification des carbones et la lecture des formules semi-développées ou topologiques.`,
    stage: 'DISCOVER' as const,
    questionOrders: [67,68,69,70,71,72,73,74,75,76],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'sentrainer-chaines-carbonees-nomenclature-base',
    title: `Chaînes carbonées et nomenclature`,
    description: `Applications distinguant degré des carbones et classe des alcools, puis utilisation des préfixes et groupes alkyles.`,
    stage: 'PRACTICE' as const,
    questionOrders: [77,78,79,80,81,82,83,84,85,86,87,88],
  },
  {
    sectionOrder: 4,
    order: 3,
    slug: 'maitriser-chaines-carbonees-nomenclature-base',
    title: `Chaînes carbonées et nomenclature`,
    description: `Maîtrise de la lecture des chaînes ramifiées, du choix du parent, des substituants et du passage entre nom et structure.`,
    stage: 'MASTER' as const,
    questionOrders: [89,90,91,92,93,94,95,96,97,98,99,100],
  },
  {
    sectionOrder: 5,
    order: 1,
    slug: 'sentrainer-synthese-nomenclature-fonctions-organiques',
    title: `Nomenclature et fonctions organiques`,
    description: `Synthèse appliquée mêlant composition, reconnaissance des fonctions, classification des carbones et nomenclature des chaînes.`,
    stage: 'PRACTICE' as const,
    questionOrders: [101,102,103,104,105,106,107,108,109,110],
  },
  {
    sectionOrder: 5,
    order: 2,
    slug: 'maitriser-synthese-nomenclature-fonctions-organiques',
    title: `Nomenclature et fonctions organiques`,
    description: `Maîtrise transversale du chapitre dans des situations proches de l’examen, sans transformer le quiz en examen blanc.`,
    stage: 'MASTER' as const,
    questionOrders: [111,112,113,114,115,116,117,118,119,120,121,122],
  },
] as const;

export const UE14_CH5_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Nomenclature et limites de la formule brute`],
  2: [`Nomenclature et limites de la formule brute`],
  3: [`Nomenclature et limites de la formule brute`],
  4: [`Éléments constitutifs et valences usuelles`],
  5: [`Éléments constitutifs et valences usuelles`],
  6: [`Éléments constitutifs et valences usuelles`],
  7: [`Microanalyse et composition élémentaire`],
  8: [`Calcul de masse molaire`],
  9: [`Pourcentage massique d’un élément`],
  10: [`Microanalyse et composition élémentaire`],
  11: [`Formule brute, microanalyse et calculs de composition`],
  12: [`Formule brute, microanalyse et calculs de composition`],
  13: [`Formule brute, microanalyse et calculs de composition`],
  14: [`Formule empirique et formule brute`],
  15: [`Détermination d’une formule empirique`],
  16: [`Pourcentage massique de l’azote`],
  17: [`Formule brute à partir de la masse molaire`],
  18: [`Formule brute, microanalyse et calculs de composition`],
  19: [`Formule brute, microanalyse et calculs de composition`],
  20: [`Formule brute, microanalyse et calculs de composition`],
  21: [`Formule brute, microanalyse et calculs de composition`],
  22: [`Formule brute, microanalyse et calculs de composition`],
  23: [`Fonction alcool et classes`],
  24: [`Fonction alcool et classes`],
  25: [`Fonction alcool et classes`],
  26: [`Fonctions oxygénées : motifs caractéristiques`],
  27: [`Fonctions oxygénées : motifs caractéristiques`],
  28: [`Fonctions oxygénées : motifs caractéristiques`],
  29: [`Fonctions oxygénées : motifs caractéristiques`],
  30: [`Fonctions oxygénées : motifs caractéristiques`],
  31: [`Fonctions oxygénées : motifs caractéristiques`],
  32: [`Fonctions oxygénées : motifs caractéristiques`],
  33: [`Paracétamol : fonctions oxygénées et amide`],
  34: [`Aspirine : acide carboxylique et ester`],
  35: [`Fonctions oxygénées : reconnaissance transversale`],
  36: [`Fonctions oxygénées : reconnaissance transversale`],
  37: [`Fonctions oxygénées : reconnaissance transversale`],
  38: [`Fonctions oxygénées : reconnaissance transversale`],
  39: [`Fonctions oxygénées : reconnaissance transversale`],
  40: [`Propofol : phénol et fonctions oxygénées`],
  41: [`Fonctions oxygénées : classement QRPL`],
  42: [`Fonctions oxygénées : reconnaissance transversale`],
  43: [`Fonctions oxygénées : reconnaissance transversale`],
  44: [`Fonctions oxygénées : reconnaissance transversale`],
  45: [`Amines et ammoniums quaternaires`],
  46: [`Amines et ammoniums quaternaires`],
  47: [`Amines et ammoniums quaternaires`],
  48: [`Amides, nitriles, carbamates et thiols`],
  49: [`Amides, nitriles, carbamates et thiols`],
  50: [`Amides, nitriles, carbamates et thiols`],
  51: [`Amides, nitriles, carbamates et thiols`],
  52: [`Amides, nitriles, carbamates et thiols`],
  53: [`Choline : ammonium quaternaire`],
  54: [`Cystéine : thiol, amine et acide carboxylique`],
  55: [`Acétylcholine : ester et ammonium quaternaire`],
  56: [`Fonctions azotées et soufrées : reconnaissance transversale`],
  57: [`N-acétylcystéine : lecture polyfonctionnelle`],
  58: [`Fonctions azotées et soufrées : reconnaissance transversale`],
  59: [`Fonctions azotées et soufrées : classement QRPL`],
  60: [`Fonctions azotées et soufrées : reconnaissance transversale`],
  61: [`Captopril : lecture polyfonctionnelle`],
  62: [`Fonctions azotées et soufrées : reconnaissance transversale`],
  63: [`Fonctions azotées et soufrées : reconnaissance transversale`],
  64: [`Thiol et pont disulfure`],
  65: [`Fonctions azotées et soufrées : reconnaissance transversale`],
  66: [`Fonctions azotées et soufrées : reconnaissance transversale`],
  67: [`Convention locale de classification des carbones`],
  68: [`Degré des carbones : convention du cours`],
  69: [`Degré des carbones : convention du cours`],
  70: [`Degré des carbones : convention du cours`],
  71: [`Degré des carbones : convention du cours`],
  72: [`Carbone carbonylé : convention locale`],
  73: [`Degré des carbones : convention du cours`],
  74: [`Degré des carbones : convention du cours`],
  75: [`Degré des carbones : convention du cours`],
  76: [`Degré des carbones : convention du cours`],
  77: [`Carbone quaternaire et alcool tertiaire`],
  78: [`Degré des carbones et classe des alcools`],
  79: [`Degré des carbones et classe des alcools`],
  80: [`Degré des carbones et classe des alcools`],
  81: [`Degré des carbones et classe des alcools`],
  82: [`Préfixes méth- à pent-`],
  83: [`Préfixes hex- à déc-`],
  84: [`Préfixes et groupes alkyles`],
  85: [`Préfixes et groupes alkyles`],
  86: [`Préfixes et groupes alkyles`],
  87: [`Groupes alkyles`],
  88: [`Préfixes et groupes alkyles`],
  89: [`Nomenclature des chaînes carbonées`],
  90: [`Nomenclature des chaînes carbonées`],
  91: [`Nomenclature des chaînes carbonées`],
  92: [`3-méthylhexane : chaîne et substituant`],
  93: [`Isooctane : 2,2,4-triméthylpentane`],
  94: [`Nomenclature des chaînes carbonées`],
  95: [`Nomenclature des chaînes carbonées`],
  96: [`3-méthylhexan-2-ol : chaîne et alcool`],
  97: [`Nomenclature des chaînes carbonées`],
  98: [`Nomenclature des chaînes carbonées`],
  99: [`Nomenclature des chaînes carbonées`],
  100: [`Nomenclature des chaînes carbonées`],
  101: [`Synthèse : composition et fonctions organiques`],
  102: [`Synthèse : composition et fonctions organiques`],
  103: [`Synthèse : composition et fonctions organiques`],
  104: [`Synthèse : composition et fonctions organiques`],
  105: [`Synthèse : composition et fonctions organiques`],
  106: [`Synthèse : composition et fonctions organiques`],
  107: [`Synthèse : composition et fonctions organiques`],
  108: [`Repérage QZONE du motif ester`],
  109: [`Synthèse : composition et fonctions organiques`],
  110: [`Synthèse : composition et fonctions organiques`],
  111: [`Microanalyse : formule empirique`],
  112: [`Synthèse transversale de nomenclature organique`],
  113: [`Acétylcholine : synthèse fonctionnelle`],
  114: [`Synthèse transversale de nomenclature organique`],
  115: [`Synthèse transversale de nomenclature organique`],
  116: [`Synthèse transversale de nomenclature organique`],
  117: [`Synthèse transversale de nomenclature organique`],
  118: [`Molécules polyfonctionnelles : classement QRPL`],
  119: [`Synthèse transversale de nomenclature organique`],
  120: [`Synthèse transversale de nomenclature organique`],
  121: [`Synthèse transversale de nomenclature organique`],
  122: [`Synthèse générale du chapitre`],
};
