/**
 * UE14 – Biologie cellulaire – Chapitre 7
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la mitochondrie :`,
    choices: [
      `C’est un organite cellulaire complexe.`,
      `Son origine est bactérienne.`,
      `Elle est présente dans les hématies matures selon la fiche.`,
      `Elle est présente chez les eucaryotes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche présente la mitochondrie comme un organite complexe d’origine bactérienne, présent dans les cellules eucaryotes à l’exception des hématies.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant l’origine de la mitochondrie :`,
    choices: [
      `Elle est reliée à une symbiose ancienne.`,
      `La fiche évoque la colonisation d’une cellule eucaryote primitive par une bactérie aérobie.`,
      `Cette origine aide à expliquer son génome propre.`,
      `Elle dérive directement du noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’origine endosymbiotique est mobilisée dans la fiche pour expliquer plusieurs particularités mitochondriales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les ordres de grandeur indiqués sont :`,
    choices: [
      `Longueur inférieure à 7 µm.`,
      `Diamètre inférieur à 1 µm.`,
      `Toujours une seule mitochondrie par cellule.`,
      `Environ 1000 à 3000 mitochondries par cellule selon le contexte.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le nombre et la morphologie varient selon le type et l’activité cellulaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La répartition des mitochondries :`,
    choices: [
      `Peut être uniforme dans le cytoplasme.`,
      `Peut être spécialisée selon le type cellulaire.`,
      `Dans le muscle, elles peuvent être disposées près des myofibrilles.`,
      `Est toujours totalement aléatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La localisation mitochondriale peut être adaptée aux besoins énergétiques locaux.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant la dynamique mitochondriale :`,
    choices: [
      `Les mitochondries peuvent être fixes ou mobiles.`,
      `Le cytosquelette peut participer à leur mobilité.`,
      `Les mitochondries âgées peuvent être éliminées par autophagie dans le compartiment lysosomal.`,
      `Elles ne peuvent jamais se diviser.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche décrit une mobilité dépendant du cytosquelette, une division de mitochondries préexistantes et une élimination autophagique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La mitochondrie possède :`,
    choices: [
      `Une double membrane d’enveloppe.`,
      `Un espace intermembranaire.`,
      `Une matrice mitochondriale.`,
      `Une enveloppe nucléaire autour de son ADNmt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitochondrie possède deux membranes et deux espaces principaux, mais son ADNmt n’est pas entouré d’une enveloppe nucléaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos du génome mitochondrial :`,
    choices: [
      `Chaque mitochondrie comporte 2 à 10 copies d’ADNmt selon la fiche.`,
      `L’ADNmt est distinct de l’ADN nucléaire.`,
      `Il est enfermé dans un noyau mitochondrial.`,
      `Il est cohérent avec l’origine bactérienne de l’organite.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L’ADNmt est présent dans la matrice sans enveloppe nucléaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante :

![Organisation d’une mitochondrie](/images/training/ue14/biologie-cellulaire/mitochondrie/structure-compartiments-mitochondrie.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `La membrane interne forme des crêtes.`,
      `La matrice contient notamment ADNmt et ribosomes mitochondriaux.`,
      `L’espace intermembranaire se situe entre les deux membranes.`,
      `Le glycocalyx constitue le principal contenu de la matrice.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure résume les compartiments et constituants majeurs de la mitochondrie.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La membrane externe mitochondriale :`,
    choices: [
      `Comporte plus de protéines que la membrane plasmique selon la fiche.`,
      `Contient de nombreuses porines.`,
      `Échange avec le cytosol.`,
      `Est dépourvue de tout système d’import.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane externe assure des échanges et porte plusieurs systèmes d’import.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les porines de la membrane externe :`,
    choices: [
      `Sont des canaux ou pores aqueux.`,
      `Participent au passage de petites molécules.`,
      `Sont citées pour l’import d’ADP, de phosphate ou de pyruvate.`,
      `Sont les sous-unités catalytiques F1 de l’ATP synthase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les porines sont des perméases passives de la membrane externe, distinctes de l’ATP synthase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des complexes TOM, TIM et SAM :`,
    choices: [
      `TOM intervient dans la translocation de protéines solubles à travers la membrane externe.`,
      `TIM prolonge l’import vers la matrice à travers la membrane interne.`,
      `SAM participe à l’insertion de protéines insolubles dans la membrane externe.`,
      `Tous trois correspondent à des complexes de la chaîne respiratoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces complexes concernent l’import et l’assemblage des protéines mitochondriales, non le transfert d’électrons.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe le schéma d’import :

![Import des constituants](/images/training/ue14/biologie-cellulaire/mitochondrie/import-proteines-mitochondriales.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Une protéine soluble peut traverser TOM puis TIM.`,
      `Une protéine insoluble peut être prise en charge par SAM.`,
      `Le cholestérol dispose d’un système de transport spécifique.`,
      `Toutes les protéines mitochondriales sont codées par l’ADNmt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La plupart des protéines mitochondriales sont codées par le génome nucléaire et importées depuis le cytosol.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’espace intermembranaire :`,
    choices: [
      `Est situé entre les membranes externe et interne.`,
      `Est un lieu de transit de molécules et notamment de protons.`,
      `Contient davantage de H+ que la matrice pendant la phosphorylation oxydative.`,
      `Est le lieu principal de synthèse de l’ADNmt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le gradient protonique se constitue entre matrice et espace intermembranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La membrane interne mitochondriale :`,
    choices: [
      `Présente des replis appelés crêtes.`,
      `Est constituée d’environ 80 % de protéines selon la fiche.`,
      `Porte des perméases et le complexe TIM.`,
      `Est plus perméable que la membrane externe à toutes les petites molécules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane interne est très riche en protéines et fortement spécialisée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les éléments associés à la membrane interne, la fiche cite :`,
    choices: [
      `Les quatre complexes de la chaîne respiratoire.`,
      `L’ATP synthase.`,
      `Des protéines de découplage UCP.`,
      `Les antigènes du système ABO.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane interne concentre les équipements de respiration, de phosphorylation et de découplage.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La matrice mitochondriale contient notamment :`,
    choices: [
      `Des enzymes du cycle de Krebs.`,
      `Des enzymes de β-oxydation des acides gras.`,
      `Des ribosomes mitochondriaux.`,
      `La majorité des antigènes glucidiques de l’hématie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La matrice réunit des enzymes métaboliques, l’ADNmt, des ribosomes et des granules ioniques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les granules denses de la matrice sont associés dans la fiche à :`,
    choices: [
      `Des ions Ca2+.`,
      `Des ions Mg2+.`,
      `Des réserves de glycocalyx.`,
      `La matrice finement granulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche mentionne des granules denses contenant notamment Ca2+ et Mg2+.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de l’ADN mitochondrial :`,
    choices: [
      `Il est circulaire.`,
      `Sa taille indiquée est d’environ 17 kb.`,
      `Son code génétique peut différer du code nucléaire.`,
      `Il est linéaire et enfermé dans une enveloppe nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ADNmt est petit, circulaire et non entouré d’une enveloppe nucléaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le génome mitochondrial est caractérisé par :`,
    choices: [
      `Une transmission maternelle selon la fiche.`,
      `Une réplication indépendante de la phase S.`,
      `Une autonomie complète vis-à-vis du génome nucléaire.`,
      `Une autonomie limitée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le fonctionnement mitochondrial dépend largement de protéines codées par le noyau.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le génome nucléaire contrôle le fonctionnement mitochondrial car :`,
    choices: [
      `Beaucoup de protéines mitochondriales sont codées par le noyau.`,
      `Ces protéines sont synthétisées dans le cytosol puis importées.`,
      `L’ADNmt code à lui seul toutes les protéines de l’organite.`,
      `L’autonomie mitochondriale est limitée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La coopération entre génomes nucléaire et mitochondrial est indispensable.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine soluble codée par le noyau doit rejoindre la matrice. Le trajet le plus cohérent est :`,
    choices: [
      `Synthèse dans le cytosol.`,
      `Passage par TOM.`,
      `Passage par TIM.`,
      `Insertion par SAM uniquement dans la membrane externe.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’import vers la matrice associe classiquement TOM puis TIM dans le cadre du cours.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une protéine insoluble destinée à la membrane externe peut faire intervenir :`,
    choices: [
      `Une synthèse cytosolique.`,
      `Le complexe TOM au début de son adressage selon le schéma général.`,
      `Le complexe SAM pour son assemblage membranaire.`,
      `Le complexe IV comme machine d’insertion.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `SAM est la machine d’assemblage citée pour les protéines insolubles de la membrane externe.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule très active énergétiquement pourrait présenter :`,
    choices: [
      `Un grand nombre de mitochondries.`,
      `Une répartition mitochondriale adaptée aux zones consommatrices d’ATP.`,
      `Des crêtes augmentant la surface de membrane interne.`,
      `L’absence totale de cytosquelette.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le nombre, la répartition et la surface de membrane interne peuvent s’adapter à l’activité cellulaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La dégradation d’une mitochondrie vieillissante :`,
    choices: [
      `Peut passer par l’autophagie.`,
      `S’effectue dans le compartiment lysosomal.`,
      `Illustre une coopération entre organites.`,
      `Dépend nécessairement d’une fusion avec le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie le renouvellement mitochondrial à l’autophagie et aux lysosomes.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La double membrane mitochondriale permet de distinguer :`,
    choices: [
      `La membrane externe tournée vers le cytosol.`,
      `La membrane interne portant la chaîne respiratoire.`,
      `L’espace intermembranaire où s’accumulent les H+.`,
      `Un lumen golgien interne.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les compartiments mitochondriaux ne correspondent pas aux citernes de Golgi.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation d’une protéine nucléaire nécessaire au complexe TIM pourrait perturber :`,
    choices: [
      `L’import de protéines solubles vers la matrice.`,
      `Le fonctionnement de nombreuses voies mitochondriales.`,
      `L’autonomie limitée de l’organite.`,
      `La présence des antigènes ABO sur l’hématie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une altération de TIM peut affecter des protéines codées par le noyau et destinées à la matrice.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle(s) proposition(s) relie(nt) correctement structure et fonction ?`,
    choices: [
      `Les crêtes augmentent la surface disponible pour les protéines de la membrane interne.`,
      `Les porines facilitent le passage de petites molécules à travers la membrane externe.`,
      `La matrice contient les enzymes du cycle de Krebs.`,
      `L’ADNmt se trouve dans l’espace extracellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Chaque compartiment porte des fonctions propres et complémentaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’absence de mitochondries dans les hématies matures est cohérente avec :`,
    choices: [
      `L’exception explicitement donnée dans la fiche.`,
      `La nécessité d’éviter d’attribuer les structures mitochondriales à toutes les cellules eucaryotes sans exception.`,
      `La présence néanmoins d’une membrane plasmique dans l’hématie.`,
      `L’idée que toutes les cellules eucaryotes ont toujours 3000 mitochondries.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche précise une exception importante : les hématies.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les deux figures suivantes présentent la structure de la mitochondrie et l’import de ses constituants.

![Organisation d’une mitochondrie](/images/training/ue14/biologie-cellulaire/mitochondrie/structure-compartiments-mitochondrie.png)

![Import des constituants](/images/training/ue14/biologie-cellulaire/mitochondrie/import-proteines-mitochondriales.png)

En croisant ces deux figures, quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Les membranes externe et interne portent des équipements différents.`,
      `La matrice dépend d’imports depuis le cytosol.`,
      `L’ADNmt suffit à produire toutes les protéines de l’organite.`,
      `La compartimentation est essentielle au fonctionnement mitochondrial.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La mitochondrie est autonome seulement de façon limitée et dépend d’imports nucléaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle conclusion résume le mieux la section ?`,
    choices: [
      `La mitochondrie associe double membrane, compartiments et génome propre.`,
      `Sa structure est adaptée à l’import, au métabolisme et à la production d’énergie.`,
      `Elle reste fortement dépendante du génome nucléaire.`,
      `Elle appartient au système endomembranaire et ne possède aucun ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La mitochondrie possède une organisation spécifique et une autonomie limitée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `organisation-generale-mitochondrie`,
    title: `Organisation générale de la mitochondrie`,
    description: `Origine, morphologie, nombre, répartition et renouvellement.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `membranes-import-et-compartiments`,
    title: `Membranes, import et compartiments`,
    description: `Porines, TOM, TIM, SAM, membrane interne et matrice.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `genome-et-integration-structure-fonction`,
    title: `Génome et intégration structure-fonction`,
    description: `ADNmt, autonomie limitée et raisonnement sur l’organisation mitochondriale.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
