/** Cartographie éditoriale V2 — auteur */

export const UE14_BIOCH_CH12_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-immunoglobulines-protection",
    "title": "Structure et fonctions des immunoglobulines",
    "description": "Repères sur antigènes, épitopes, architecture H2L2 et classes d’immunoglobulines.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-structure-classes-immunoglobulines",
    "title": "Immunoglobulines : classes, domaines et fragments",
    "description": "Applications sur formes multimériques, peptide J, domaines et fragments Fab/Fc.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-recepteurs-nucleaires-metabotropiques",
    "title": "Récepteurs nucléaires et métabotropiques",
    "description": "Distinguer récepteurs nucléaires, métabotropiques et grands principes de signalisation.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-insuline-rcpg-rhodopsine",
    "title": "Signalisation : insuline, RCPG et rhodopsine",
    "description": "Applications sur récepteur à l’insuline, RCPG, rhodopsine et terminologie locale des récepteurs opioïdes.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-canaux-pompes",
    "title": "Canaux ioniques et pompes",
    "description": "Distinguer récepteurs ionotropiques, diffusion facilitée et transport actif.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-abc-pgp-cftr",
    "title": "Transporteurs ABC, P-gp et CFTR",
    "description": "Applications sur Na+/K+ ATPase, transporteurs ABC, P-glycoprotéine et CFTR.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-adhesion-selectines-integrines",
    "title": "Molécules d’adhérence : sélectines et intégrines",
    "description": "Repères sur les quatre familles d’adhérence, sélectines et structure des intégrines.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-integrines-rgd",
    "title": "Intégrines : ligand, activation et adhésion focale",
    "description": "Applications sur motif RGD, cations divalents, changement conformationnel et plaques d’adhésion focale.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-adhesion-integrines",
    "title": "Adhérence cellulaire et intégrines",
    "description": "Maîtrise transversale de l’adhérence cellule-cellule et cellule-matrice.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-roles-proteines-partie-1",
    "title": "Synthèse : rôles biologiques des protéines, partie 1",
    "description": "Consolidation transversale des fonctions de protection, réception, transport et adhérence.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-roles-biologiques-proteines-partie-1",
    "title": "Synthèse : rôles biologiques des protéines, partie 1",
    "description": "Maîtrise du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH12_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["l’importance générale des protéines"],
  2: ["l’antigène et l’épitope"],
  3: ["la structure H2L2 des immunoglobulines"],
  4: ["les classes d’immunoglobulines"],
  5: ["les chaînes légères κ et λ"],
  6: ["les associations monomériques et multimériques des immunoglobulines"],
  7: ["le peptide J"],
  8: ["l’organisation modulaire des immunoglobulines"],
  9: ["les fragments Fab après action de la papaïne"],
  10: ["le fragment Fc"],
  11: ["la structure H2L2 des immunoglobulines"],
  12: ["les classes d’immunoglobulines"],
  13: ["les chaînes légères κ et λ"],
  14: ["les associations monomériques et multimériques des immunoglobulines"],
  15: ["le peptide J"],
  16: ["la structure H2L2 des immunoglobulines"],
  17: ["les fragments Fab après action de la papaïne"],
  18: ["le fragment Fc"],
  19: ["les associations monomériques et multimériques des immunoglobulines"],
  20: ["l’antigène et l’épitope"],
  21: ["l’importance générale des protéines", "l’antigène et l’épitope", "la structure H2L2 des immunoglobulines"],
  22: ["l’antigène et l’épitope", "la structure H2L2 des immunoglobulines", "les classes d’immunoglobulines", "les chaînes légères κ et λ", "les associations monomériques et multimériques des immunoglobulines"],
  23: ["l’architecture générale d’un récepteur membranaire"],
  24: ["les récepteurs nucléaires"],
  25: ["les ligands des récepteurs nucléaires"],
  26: ["le fonctionnement transcriptionnel des récepteurs nucléaires"],
  27: ["les récepteurs métabotropiques"],
  28: ["la structure du récepteur à l’insuline"],
  29: ["la voie du récepteur à l’insuline"],
  30: ["les récepteurs couplés aux protéines G"],
  31: ["la rhodopsine"],
  32: ["les récepteurs opioïdes dans la fiche"],
  33: ["les ligands des récepteurs nucléaires"],
  34: ["le fonctionnement transcriptionnel des récepteurs nucléaires"],
  35: ["les récepteurs métabotropiques"],
  36: ["la structure du récepteur à l’insuline"],
  37: ["la voie du récepteur à l’insuline"],
  38: ["les récepteurs opioïdes dans la fiche"],
  39: ["la rhodopsine"],
  40: ["les récepteurs opioïdes dans la fiche"],
  41: ["l’architecture générale d’un récepteur membranaire"],
  42: ["les récepteurs nucléaires"],
  43: ["l’architecture générale d’un récepteur membranaire", "les récepteurs nucléaires", "les ligands des récepteurs nucléaires"],
  44: ["les récepteurs nucléaires", "les ligands des récepteurs nucléaires", "le fonctionnement transcriptionnel des récepteurs nucléaires", "les récepteurs métabotropiques", "la structure du récepteur à l’insuline"],
  45: ["les récepteurs ionotropiques"],
  46: ["le récepteur 5-HT3"],
  47: ["le récepteur GABA-A"],
  48: ["le transport par les canaux ioniques"],
  49: ["la Na+/K+ ATPase"],
  50: ["la stœchiométrie de la Na+/K+ ATPase"],
  51: ["la structure générale des transporteurs ABC"],
  52: ["la P-glycoprotéine et la résistance aux médicaments"],
  53: ["le canal CFTR"],
  54: ["la distinction entre canal et pompe"],
  55: ["le récepteur GABA-A"],
  56: ["le transport par les canaux ioniques"],
  57: ["la Na+/K+ ATPase"],
  58: ["la stœchiométrie de la Na+/K+ ATPase"],
  59: ["la structure générale des transporteurs ABC"],
  60: ["la stœchiométrie de la Na+/K+ ATPase"],
  61: ["le canal CFTR"],
  62: ["la distinction entre canal et pompe"],
  63: ["les récepteurs ionotropiques"],
  64: ["le récepteur 5-HT3"],
  65: ["les récepteurs ionotropiques", "le récepteur 5-HT3", "le récepteur GABA-A"],
  66: ["le récepteur 5-HT3", "le récepteur GABA-A", "le transport par les canaux ioniques", "la Na+/K+ ATPase", "la stœchiométrie de la Na+/K+ ATPase"],
  67: ["les familles de molécules d’adhérence"],
  68: ["les trois types de sélectines"],
  69: ["la reconnaissance par les sélectines"],
  70: ["la structure des intégrines"],
  71: ["la diversité des sous-unités d’intégrines dans la fiche"],
  72: ["le motif RGD reconnu par les intégrines"],
  73: ["le rôle des cations dans l’interaction des intégrines"],
  74: ["l’activation conformationnelle des intégrines"],
  75: ["les plaques d’adhésion focale"],
  76: ["l’absence d’activité kinasique intrinsèque des intégrines"],
  77: ["la reconnaissance par les sélectines"],
  78: ["la structure des intégrines"],
  79: ["la diversité des sous-unités d’intégrines dans la fiche"],
  80: ["le motif RGD reconnu par les intégrines"],
  81: ["le rôle des cations dans l’interaction des intégrines"],
  82: ["les trois types de sélectines"],
  83: ["les plaques d’adhésion focale"],
  84: ["l’absence d’activité kinasique intrinsèque des intégrines"],
  85: ["la diversité des sous-unités d’intégrines dans la fiche"],
  86: ["les trois types de sélectines"],
  87: ["les familles de molécules d’adhérence", "les trois types de sélectines", "la reconnaissance par les sélectines"],
  88: ["les trois types de sélectines", "la reconnaissance par les sélectines", "la structure des intégrines", "la diversité des sous-unités d’intégrines dans la fiche", "le motif RGD reconnu par les intégrines"],
  89: ["le motif RGD reconnu par les intégrines"],
  90: ["les trois types de sélectines", "la diversité des sous-unités d’intégrines dans la fiche"],
  91: ["la reconnaissance par les sélectines", "le motif RGD reconnu par les intégrines"],
  92: ["la structure des intégrines", "le rôle des cations dans l’interaction des intégrines"],
  93: ["la diversité des sous-unités d’intégrines dans la fiche", "l’activation conformationnelle des intégrines"],
  94: ["le motif RGD reconnu par les intégrines", "les plaques d’adhésion focale"],
  95: ["le rôle des cations dans l’interaction des intégrines", "l’absence d’activité kinasique intrinsèque des intégrines"],
  96: ["l’activation conformationnelle des intégrines", "les familles de molécules d’adhérence"],
  97: ["les plaques d’adhésion focale", "les trois types de sélectines"],
  98: ["l’absence d’activité kinasique intrinsèque des intégrines", "les familles de molécules d’adhérence", "les trois types de sélectines"],
  99: ["les familles de molécules d’adhérence", "la structure des intégrines"],
  100: ["les trois types de sélectines", "la reconnaissance par les sélectines", "la structure des intégrines", "la diversité des sous-unités d’intégrines dans la fiche", "le motif RGD reconnu par les intégrines"],
  101: ["l’importance générale des protéines", "les récepteurs nucléaires"],
  102: ["les chaînes légères κ et λ", "la structure du récepteur à l’insuline"],
  103: ["les fragments Fab après action de la papaïne", "les récepteurs opioïdes dans la fiche"],
  104: ["les ligands des récepteurs nucléaires", "le transport par les canaux ioniques"],
  105: ["la voie du récepteur à l’insuline", "la P-glycoprotéine et la résistance aux médicaments"],
  106: ["les récepteurs ionotropiques", "les trois types de sélectines"],
  107: ["la Na+/K+ ATPase", "le motif RGD reconnu par les intégrines"],
  108: ["le canal CFTR", "l’absence d’activité kinasique intrinsèque des intégrines"],
  109: ["la Na+/K+ ATPase", "la stœchiométrie de la Na+/K+ ATPase", "la structure générale des transporteurs ABC"],
  110: ["la P-glycoprotéine et la résistance aux médicaments", "le canal CFTR", "la distinction entre canal et pompe", "les familles de molécules d’adhérence", "les trois types de sélectines"],
  111: ["l’antigène et l’épitope", "le fonctionnement transcriptionnel des récepteurs nucléaires", "le transport par les canaux ioniques"],
  112: ["le peptide J", "les récepteurs ionotropiques", "la diversité des sous-unités d’intégrines dans la fiche"],
  113: ["les récepteurs nucléaires", "la P-glycoprotéine et la résistance aux médicaments", "les associations monomériques et multimériques des immunoglobulines"],
  114: ["la voie du récepteur à l’insuline", "la diversité des sous-unités d’intégrines dans la fiche"],
  115: ["le récepteur 5-HT3", "l’antigène et l’épitope", "la P-glycoprotéine et la résistance aux médicaments"],
  116: ["la structure générale des transporteurs ABC", "les fragments Fab après action de la papaïne", "les plaques d’adhésion focale"],
  117: ["les fragments Fab après action de la papaïne"],
  118: ["le rôle des cations dans l’interaction des intégrines", "le récepteur GABA-A", "les récepteurs ionotropiques"],
  119: ["l’antigène et l’épitope", "la distinction entre canal et pompe", "les trois types de sélectines"],
  120: ["le peptide J", "le rôle des cations dans l’interaction des intégrines", "la structure H2L2 des immunoglobulines"],
  121: ["l’architecture générale d’un récepteur membranaire", "les récepteurs nucléaires", "les ligands des récepteurs nucléaires"],
  122: ["la structure du récepteur à l’insuline", "la voie du récepteur à l’insuline", "les récepteurs couplés aux protéines G", "la rhodopsine", "les récepteurs opioïdes dans la fiche"],
};
