import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_ORDER = 4;

export const SECTION_D_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  91: ["Principe de la cyclisation"],
  92: ["Pyranoses et furanoses"],
  93: ["Cyclisation pyranique du glucose"],
  94: ["Cyclisation furanique du glucose"],
  95: ["Conformations des pyranoses"],
  96: ["Conformation des furanoses"],
  97: ["Carbone anomérique des aldoses"],
  98: ["Position anomérique des aldoses"],
  99: ["Position anomérique des cétoses"],
  100: ["Définition des anomères"],
  101: ["Anomère alpha"],
  102: ["Anomère beta"],
  103: ["Relations entre anomères"],
  104: ["Cyclisation furanique du fructose"],
  105: ["Cyclisation pyranique du fructose"],
  106: ["Équilibre des formes à pH 7"],
  107: ["Effet du pH selon la fiche"],
  108: ["Interconversion alpha-beta"],
  109: ["Interconversion aldose-cétose"],
  110: ["Mutarotation"],
  111: ["Principe du pouvoir rotatoire"],
  112: ["Dextrorotation"],
  113: ["Lévogyrie"],
  114: ["Indépendance D-L et signe optique"],
  115: ["Exemples de pouvoir rotatoire"],
  116: ["Rotation des anomères du glucose"],
  117: ["Application : mutarotation du glucose"],
  118: ["Mélange racémique"],
  119: ["Calcul d'un mélange racémique"],
  120: ["Calcul de rotation d'un mélange non racémique"],
};

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "decouvrir-cyclisation-anomeres",
    title: "Cyclisation et anomères",
    description: "Comprendre la fermeture des cycles, les formes pyraniques et furaniques et la naissance du carbone anomérique.",
    stage: 'DISCOVER',
    sectionOrder: SECTION_D_ORDER,
    questionOrders: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  {
    order: 2,
    slug: "sentrainer-conformations-interconversion",
    title: "Conformations et interconversion",
    description: "Comparer les anomères, cycliser glucose et fructose et interpréter l'équilibre entre formes linéaires et cycliques.",
    stage: 'PRACTICE',
    sectionOrder: SECTION_D_ORDER,
    questionOrders: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  {
    order: 3,
    slug: "maitriser-pouvoir-rotatoire-mutarotation",
    title: "Pouvoir rotatoire et mutarotation",
    description: "Distinguer D/L de +/−, exploiter les rotations des anomères et calculer la rotation de mélanges d'énantiomères.",
    stage: 'MASTER',
    sectionOrder: SECTION_D_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 111 },
      { type: 'QUESTION', questionOrder: 112 },
      { type: 'QUESTION', questionOrder: 113 },
      { type: 'QUESTION', questionOrder: 114 },
      {
        type: 'GROUP',
        title: "Polarimétrie du glucose",
        sharedStatement: "Le glucose naturel est D(+). La fiche indique environ $+113^\\circ$ pour l'α-D-glucose et $+19^\\circ$ pour le β-D-glucose ; les deux formes s'interconvertissent en solution.",
        questionOrders: [115, 116, 117],
      },
      { type: 'QUESTION', questionOrder: 118 },
      { type: 'QUESTION', questionOrder: 119 },
      { type: 'QUESTION', questionOrder: 120 },
    ],
  },
];

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Lors de la cyclisation d'un ose :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-cyclization-anomers',
    },
    choices: [
      "Un hétérocycle contenant un atome d'oxygène peut se former.",
      "La chaîne linéaire se referme sur elle-même.",
      "La formule brute de l'ose est conservée.",
      "Tous les atomes de carbone sont éliminés.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La cyclisation est une transformation intramoléculaire qui ferme la chaîne sans modifier la formule brute.",
    choiceExplanations: [
      "L'oxygène participe au cycle.",
      "Principe de la réaction.",
      "Aucun atome n'est perdu dans le bilan global.",
      "La charpente carbonée est conservée.",
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos des formes cycliques des oses :",
    choices: [
      "Une forme pyranique possède un cycle à six sommets.",
      "Une forme furanique possède un cycle à cinq sommets.",
      "Le nom pyranose dérive du noyau pyrane.",
      "Une forme furanique possède nécessairement six carbones dans le cycle.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les termes pyranose et furanose décrivent respectivement des cycles à six et cinq sommets, oxygène compris.",
    choiceExplanations: [
      "Définition correcte.",
      "Définition correcte.",
      "Origine du nom correcte.",
      "Le cycle furanique compte cinq sommets.",
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La forme pyranique du D-glucose résulte principalement :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-cyclization-anomers',
    },
    choices: [
      "D'une cyclisation entre C1 et C5.",
      "De l'intervention de la fonction aldéhyde de C1.",
      "De la formation d'un cycle à six sommets.",
      "D'une liaison directe entre C2 et C6.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le D-glucose forme majoritairement un hémiacétal cyclique par rapprochement de C1 et du OH de C5.",
    choiceExplanations: [
      "Positions correctes.",
      "Le carbonyle aldéhydique participe.",
      "Le cycle obtenu est pyranique.",
      "Cette association concerne une autre situation.",
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La forme furanique du D-glucose :",
    choices: [
      "Peut résulter d'un pont entre C1 et C4.",
      "Possède un cycle à cinq sommets.",
      "Est décrite comme peu fréquente et instable pour les aldoses.",
      "Est la forme très majoritaire du glucose selon la fiche.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glucose peut former un cycle furanique C1–C4, mais sa forme pyranique est beaucoup plus stable et fréquente.",
    choiceExplanations: [
      "Positions correctes.",
      "Définition du furanose.",
      "Repère du cours.",
      "La forme pyranique est majoritaire.",
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Une forme pyranique peut adopter :",
    choices: [
      "Une conformation chaise.",
      "Une conformation bateau.",
      "Une conformation enveloppe comme seule possibilité.",
      "Une conformation chaise généralement plus stable.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Les cycles pyraniques peuvent être en chaise ou en bateau ; la chaise est la plus stable.",
    choiceExplanations: [
      "Conformation correcte.",
      "Conformation correcte.",
      "L'enveloppe est associée au cycle furanique.",
      "Repère de stabilité du cours.",
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La conformation typique représentée pour une forme furanique est :",
    choices: [
      "La chaise.",
      "Le bateau.",
      "L'enveloppe.",
      "La forme linéaire.",
    ],
    correctChoiceIndexes: [2],
    explanation: "Le cycle furanique à cinq sommets est représenté en conformation enveloppe.",
    choiceExplanations: [
      "La chaise concerne surtout les cycles à six.",
      "Le bateau concerne également les pyranoses.",
      "C'est la conformation indiquée.",
      "Une forme cyclique n'est pas linéaire.",
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La cyclisation d'un aldose :",
    choices: [
      "Transforme le carbone carbonylé C1 en nouveau carbone asymétrique.",
      "Crée le carbone anomérique.",
      "Permet l'apparition de deux anomères α et β.",
      "Supprime tous les centres chiraux préexistants.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le carbone C1 devient tétraédrique lors de la fermeture du cycle et constitue le nouveau centre anomérique.",
    choiceExplanations: [
      "Conséquence structurale correcte.",
      "Nom du nouveau centre.",
      "Deux orientations sont possibles.",
      "Les centres préexistants sont conservés.",
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Pour un aldose cyclisé, le carbone anomérique est généralement :",
    choices: [
      "C1.",
      "C2.",
      "C5.",
      "C6.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Le carbone anomérique provient du carbone aldéhydique C1.",
    choiceExplanations: [
      "Position correcte.",
      "C2 est anomérique pour un cétose typique.",
      "C5 fournit souvent le OH de cyclisation.",
      "C6 est terminal dans un hexose.",
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Pour un cétose cyclisé comme le fructose, le carbone anomérique est généralement :",
    choices: [
      "C1.",
      "C2.",
      "C5.",
      "C6.",
    ],
    correctChoiceIndexes: [1],
    explanation: "Le carbone anomérique dérive du carbone cétonique C2.",
    choiceExplanations: [
      "C1 est un groupe $\\mathrm{CH_2OH}$ dans le fructose.",
      "Position correcte.",
      "C5 peut fournir le OH de cyclisation.",
      "C6 peut intervenir dans une cyclisation pyranique.",
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Pour un D-aldose cyclisé, selon les conventions usuelles de représentation :

[[QUESTION_DIAGRAM]]`,
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-cyclization-anomers',
    },
    choices: [
      "L'anomère α a le OH anomérique trans au groupe $\\mathrm{CH_2OH}$.",
      "L'anomère β a le OH anomérique cis au groupe $\\mathrm{CH_2OH}$.",
      "α et β diffèrent uniquement au carbone anomérique.",
      "α et β sont deux isomères de fonction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les anomères ont la même connectivité et diffèrent uniquement par l'orientation du OH anomérique.",
    choiceExplanations: [
      "Définition de α.",
      "Définition de β.",
      "Critère exact.",
      "La fonction globale ne change pas.",
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos de l'anomère α d'un D-aldose :",
    choices: [
      "Le OH anomérique et le groupe $\\mathrm{CH_2OH}$ sont de part et d'autre du plan moyen du cycle.",
      "La relation est dite trans.",
      "Il possède, selon la fiche, un pouvoir rotatoire plus élevé que l'anomère β du glucose.",
      "Il appartient nécessairement à la série L.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Pour un D-aldose, α correspond à une disposition trans ; la série D/L reste celle de la forme linéaire.",
    choiceExplanations: [
      "Description correcte.",
      "Vocabulaire correct.",
      "Exemple donné pour le glucose.",
      "L'anomérie ne change pas la série D.",
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos de l'anomère β d'un D-aldose :",
    choices: [
      "Le OH anomérique et le groupe $\\mathrm{CH_2OH}$ sont du même côté du cycle.",
      "La relation est dite cis.",
      "Il est l'énantiomère complet de l'anomère α.",
      "Il diffère de α au seul carbone anomérique.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "β correspond à la disposition cis et ne diffère de α qu'au carbone anomérique.",
    choiceExplanations: [
      "Description correcte.",
      "Vocabulaire correct.",
      "Les autres centres ne sont pas inversés.",
      "Définition de l'anomérie.",
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les anomères α et β d'un même ose :",
    choices: [
      "Sont des diastéréoisomères.",
      "Peuvent être considérés comme des épimères au carbone anomérique.",
      "Ont des pouvoirs rotatoires différents.",
      "Ont nécessairement des formules brutes différentes.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les anomères partagent la même formule brute et diffèrent à un seul centre, ce qui modifie leur rotation optique.",
    choiceExplanations: [
      "Catégorie correcte.",
      "Relation précise.",
      "Exemple du glucose.",
      "La stéréoisomérie conserve la formule brute.",
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La cyclisation furanique du D-fructose :",
    choices: [
      "Implique C2 et C5.",
      "Produit un cycle à cinq sommets.",
      "Est la forme la plus fréquente du fructose selon la fiche.",
      "Implique obligatoirement C1 et C4.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le fructose forme fréquemment un furanose par fermeture entre le carbonyle C2 et le OH de C5.",
    choiceExplanations: [
      "Positions correctes.",
      "Définition du furanose.",
      "Repère du cours.",
      "C1–C4 décrit la forme furanique d'un aldose comme le glucose.",
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La cyclisation pyranique du D-fructose :",
    choices: [
      "Peut impliquer C2 et C6.",
      "Produit un cycle à six sommets.",
      "Conserve C2 comme carbone anomérique.",
      "Transforme le fructose en aldose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le fructose peut former un pyranose C2–C6 tout en restant un dérivé cyclique du cétose.",
    choiceExplanations: [
      "Positions correctes.",
      "Définition du pyranose.",
      "Le carbonyle initial détermine le centre anomérique.",
      "La famille d'origine n'est pas changée par la seule cyclisation.",
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À pH 7, les proportions à l'équilibre indiquent que :",
    choices: [
      "Environ 99 % des oses considérés sont sous forme cyclique.",
      "Environ un tiers correspond à la forme α.",
      "Environ deux tiers correspondent à la forme β.",
      "Environ 99 % sont sous forme linéaire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La fiche retient à pH 7 une très forte majorité de formes cycliques, avec environ 1/3 α et 2/3 β.",
    choiceExplanations: [
      "Valeur donnée.",
      "Proportion donnée.",
      "Proportion donnée.",
      "Cette valeur est attribuée par la fiche au milieu basique.",
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "En milieu basique :",
    choices: [
      "La proportion de forme linéaire peut devenir très élevée.",
      "Une valeur de 99 % de formes linéaires est indiquée.",
      "L'ouverture du cycle est favorisée dans le modèle présenté.",
      "Les oses sont définitivement incapables de se refermer.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Dans le cadre strict de la fiche, le milieu basique favorise fortement la forme linéaire ; l'interconversion reste possible.",
    choiceExplanations: [
      "Idée retenue par le cours.",
      "Valeur explicitement indiquée.",
      "Conséquence cohérente avec le schéma.",
      "L'équilibre n'est pas décrit comme irréversible.",
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le passage d'un anomère α à l'anomère β :",
    choices: [
      "Peut s'effectuer par ouverture vers une forme linéaire.",
      "Implique ensuite une nouvelle cyclisation.",
      "Est une interconversion des oses.",
      "Exige de changer la formule brute.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'anomérisation passe par l'ouverture du cycle puis sa fermeture selon l'autre orientation.",
    choiceExplanations: [
      "Étape correcte.",
      "Étape correcte.",
      "Exemple d'interconversion.",
      "La composition atomique reste inchangée.",
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L'interconversion des oses peut aussi :",
    choices: [
      "Permettre le passage d'un aldose à un cétose.",
      "Permettre le passage inverse d'un cétose à un aldose.",
      "Conserver la formule brute tout en modifiant la fonction.",
      "Transformer nécessairement un glucide en protéine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les aldoses et cétoses de même formule peuvent s'interconvertir par réarrangement.",
    choiceExplanations: [
      "Possibilité citée.",
      "Réversibilité citée.",
      "Il s'agit d'une isomérisation de fonction.",
      "Aucun lien avec une synthèse protéique.",
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Lorsqu'une solution contenant un anomère pur évolue vers un équilibre α/β :",
    choices: [
      "Le pouvoir rotatoire mesuré évolue.",
      "L'ouverture transitoire de la forme cyclique intervient.",
      "La composition en anomères change.",
      "La formule brute de chaque molécule change.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le phénomène de mutarotation correspond à l'évolution du pouvoir rotatoire due à l'interconversion des anomères.",
    choiceExplanations: [
      "Conséquence observable.",
      "Mécanisme nécessaire.",
      "Cause du changement optique.",
      "La formule brute reste identique.",
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Le pouvoir rotatoire d'un ose :",
    choices: [
      "Correspond à sa capacité à dévier le plan de la lumière polarisée.",
      "Nécessite une molécule chirale dans le cadre du cours.",
      "Peut être positif ou négatif.",
      "Est identique pour tous les anomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les oses chiraux peuvent être dextrogyres ou lévogyres et leurs anomères peuvent présenter des rotations différentes.",
    choiceExplanations: [
      "Définition correcte.",
      "Lien avec les centres asymétriques.",
      "Deux sens de rotation existent.",
      "L'exemple α/β-glucose montre le contraire.",
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un ose dextrogyre :",
    choices: [
      "Dévie la lumière polarisée vers la droite.",
      "Est noté par le signe (+).",
      "Est nécessairement de série D.",
      "Peut être comparé à un ose lévogyre noté (−).",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Le signe optique décrit le sens de rotation et reste indépendant de la série D/L.",
    choiceExplanations: [
      "Définition correcte.",
      "Notation correcte.",
      "D et + ne sont pas équivalents.",
      "Les deux signes sont opposés.",
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un ose lévogyre :",
    choices: [
      "Dévie la lumière polarisée vers la gauche.",
      "Est noté par le signe (−).",
      "Est nécessairement de série L.",
      "Peut appartenir à la série D.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "Un ose lévogyre porte le signe −, mais il peut être D, comme le fructose cité dans le cours.",
    choiceExplanations: [
      "Définition correcte.",
      "Notation correcte.",
      "L et − ne sont pas synonymes.",
      "Le D-fructose en est l'exemple.",
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Concernant les notations D/L et +/− :",
    choices: [
      "D/L décrit une configuration.",
      "+/− décrit un sens de rotation optique.",
      "Il n'existe pas de correspondance obligatoire entre les deux couples.",
      "Tout ose D est obligatoirement (+).",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux systèmes décrivent des propriétés différentes : structure relative d'une part, mesure optique d'autre part.",
    choiceExplanations: [
      "Nature correcte de D/L.",
      "Nature correcte de +/−.",
      "Point d'attention majeur du cours.",
      "Le D-fructose est D(−).",
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Parmi les exemples de pouvoir rotatoire :",
    choices: [
      "Le glucose naturel est D(+).",
      "Le fructose naturel est D(−).",
      "L'arabinose peut être L(+).",
      "La lettre D suffit donc à prévoir le signe +.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Ces trois exemples illustrent précisément l'absence de lien automatique entre série et signe optique.",
    choiceExplanations: [
      "Exemple cité.",
      "Contre-exemple majeur.",
      "Autre contre-exemple cité.",
      "Les exemples B et C invalident cette conclusion.",
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Pour les anomères du D-glucose, les valeurs usuelles sont environ :",
    choices: [
      "$+113^\\circ$ pour l'anomère α.",
      "$+19^\\circ$ pour l'anomère β.",
      "Des valeurs différentes pour α et β.",
      "Une valeur négative identique pour les deux.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les deux anomères sont dextrogyres mais ne dévient pas la lumière du même angle.",
    choiceExplanations: [
      "Valeur donnée.",
      "Valeur donnée.",
      "Conséquence de leur différence stéréochimique.",
      "Les deux valeurs indiquées sont positives et distinctes.",
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Une solution initialement riche en α-D-glucose évolue vers l'équilibre. On peut prévoir que :",
    choices: [
      "La rotation observée diminue par rapport à $+113^\\circ$.",
      "La proportion de β-D-glucose augmente.",
      "Une forme linéaire transitoire permet l'interconversion.",
      "La solution devient nécessairement racémique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L'équilibre contient les deux anomères et conduit à une rotation intermédiaire ; il ne s'agit pas d'un mélange d'énantiomères.",
    choiceExplanations: [
      "L'anomère β a une rotation plus faible.",
      "L'équilibre est plus riche en β selon la fiche.",
      "Mécanisme correct.",
      "α et β ne sont pas des énantiomères.",
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un mélange racémique :",
    choices: [
      "Contient des quantités équimolaires de deux énantiomères.",
      "Présente une rotation optique globale nulle.",
      "Résulte de l'annulation de rotations opposées de même amplitude.",
      "Est un mélange équimolaire quelconque de deux diastéréoisomères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le racémique associe une paire d'énantiomères en proportions égales, ce qui annule le pouvoir rotatoire.",
    choiceExplanations: [
      "Définition correcte.",
      "Conséquence correcte.",
      "Mécanisme d'annulation.",
      "Des diastéréoisomères n'ont pas nécessairement des rotations opposées.",
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "On mélange des quantités égales de D-glucose de rotation $+52{,}5^\\circ$ et de L-glucose de rotation $-52{,}5^\\circ$. On obtient :",
    choices: [
      "Un mélange racémique.",
      "Une rotation globale nulle.",
      "Un mélange de deux énantiomères.",
      "Une rotation globale de $+105^\\circ$.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les rotations égales et opposées s'annulent dans un mélange équimolaire.",
    choiceExplanations: [
      "Définition satisfaite.",
      "Somme pondérée nulle.",
      "Relation exacte.",
      "Il ne faut pas additionner les valeurs absolues.",
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: "Une solution contient 75 % de D-glucose de rotation spécifique $+52{,}5^\\circ$ et 25 % de L-glucose de rotation $-52{,}5^\\circ$, dans les mêmes conditions. La rotation moyenne attendue est :",
    choices: [
      "$0^\\circ$.",
      "$+26{,}25^\\circ$.",
      "$+52{,}5^\\circ$.",
      "$-26{,}25^\\circ$.",
    ],
    correctChoiceIndexes: [1],
    explanation: "La moyenne pondérée vaut $0{,}75\\times52{,}5+0{,}25\\times(-52{,}5)=26{,}25^\\circ$.",
    choiceExplanations: [
      "La composition n'est pas équimolaire.",
      "Calcul correct.",
      "Cette valeur correspondrait à l'énantiomère D pur.",
      "Le D-glucose est majoritaire, donc le signe reste positif.",
    ],
  },
];
