import type { SeedQuestion, SeedQuiz } from './health-training-ue13.shared';

export const SECTION_E_QUESTIONS: SeedQuestion[] = [
  {
    order: 81,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le microscope optique :",
    choices: [
      "Utilise de la lumière blanche composée de photons.",
      "Fait traverser le prélèvement par la lumière.",
      "Utilise des lentilles pour former une image agrandie.",
      "Fonctionne uniquement avec un canon à électrons.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La microscopie optique repose sur la transmission de photons à travers l’échantillon et leur focalisation par des lentilles.",
    choiceExplanations: [
      "Le cours décrit une source de lumière blanche.",
      "La lumière traverse le prélèvement.",
      "Les lentilles assurent l’agrandissement.",
      "Le canon à électrons appartient à la microscopie électronique.",
    ],
  },
  {
    order: 82,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos de la résolution :",
    choices: [
      "Elle correspond à la capacité de distinguer deux points.",
      "Une valeur plus basse traduit une meilleure précision.",
      "La résolution du microscope optique est de l’ordre de 1 µm.",
      "Elle est strictement identique au grossissement.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La résolution mesure le pouvoir séparateur ; elle ne doit pas être confondue avec le grossissement.",
    choiceExplanations: [
      "C’est la définition donnée.",
      "Plus la distance minimale discernable est petite, meilleure est la résolution.",
      "Cet ordre de grandeur est indiqué.",
      "Agrandir une image ne crée pas nécessairement de nouveaux détails.",
    ],
  },
  {
    order: 83,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Le microscope électronique :",
    choices: [
      "Utilise des électrons plutôt que des photons.",
      "Atteint une résolution de l’ordre du nanomètre.",
      "Améliore d’environ mille fois la résolution indiquée pour l’optique.",
      "Permet seulement de voir des objets plus grands que ceux observés en optique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’utilisation d’électrons permet d’observer des structures beaucoup plus petites.",
    choiceExplanations: [
      "C’est le principe fondamental.",
      "Le nanomètre est l’ordre de grandeur donné.",
      "Le facteur mille est indiqué dans le cours.",
      "La microscopie électronique donne accès à des détails plus fins.",
    ],
  },
  {
    order: 84,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La microscopie optique à fond clair :",
    choices: [
      "Est la plus courante en histologie.",
      "Est adaptée aux lames colorées.",
      "Permet de discerner les structures tissulaires.",
      "N’utilise jamais de lumière blanche.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le fond clair constitue la technique optique de routine pour les lames histologiques colorées.",
    choiceExplanations: [
      "Le cours la présente comme la plus courante.",
      "Les colorations HES ou spécifiques y sont observées.",
      "C’est son objectif.",
      "La lumière blanche est au contraire utilisée.",
    ],
  },
  {
    order: 85,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les éléments du microscope optique décrits dans le cours :",
    choices: [
      "Une source de lumière blanche.",
      "Des miroirs.",
      "Une platine portant la lame.",
      "Des objectifs et des oculaires.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le schéma du cours identifie ces cinq grandes composantes du microscope optique.",
    choiceExplanations: [
      "La source éclaire l’échantillon.",
      "Les miroirs participent au trajet lumineux.",
      "La platine reçoit la lame.",
      "Objectifs et oculaires contribuent au grossissement.",
    ],
  },
  {
    order: 86,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Avec un objectif ×1 et un oculaire ×10 :",
    choices: [
      "Le grossissement total est ×10.",
      "Les cellules ne sont pas encore distinguées selon le cours.",
      "On observe surtout des zones colorées.",
      "Le grossissement total est ×1000.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le grossissement total correspond au produit objectif × oculaire.",
    choiceExplanations: [
      "Un multiplié par dix donne dix.",
      "Le cours indique que les cellules ne sont pas distinguées.",
      "Les grandes zones colorées sont visibles.",
      "×1000 correspondrait à un objectif ×100 avec un oculaire ×10.",
    ],
  },
  {
    order: 87,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Avec un objectif ×2 et un oculaire ×10 :",
    choices: [
      "Le grossissement total est ×20.",
      "Des bandes de contrastes différents peuvent être repérées.",
      "Les cellules restent difficiles à distinguer.",
      "La forme précise de chaque cellule est déjà parfaitement visible.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "À ×20, l’organisation générale se précise, mais les cellules ne sont pas encore individualisées.",
    choiceExplanations: [
      "Le calcul donne vingt.",
      "Cette observation est décrite.",
      "Le cours indique que les cellules ne sont pas discernables.",
      "La forme cellulaire devient visible à des grossissements plus élevés.",
    ],
  },
  {
    order: 88,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Avec un objectif ×10 et un oculaire ×10 :",
    choices: [
      "Le grossissement total est ×100.",
      "Les noyaux commencent à être distingués les uns des autres.",
      "C’est le premier grossissement cité permettant cette distinction nucléaire.",
      "La résolution devient automatiquement nanométrique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le cours situe à ×100 le début de la distinction des noyaux cellulaires.",
    choiceExplanations: [
      "Le produit est égal à cent.",
      "C’est l’observation décrite.",
      "Le cours insiste sur ce seuil pratique.",
      "La résolution reste celle de la microscopie optique.",
    ],
  },
  {
    order: 89,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Avec un objectif ×20 et un oculaire ×10 :",
    choices: [
      "Le grossissement total est ×200.",
      "La forme des cellules peut être distinguée.",
      "Ce grossissement est supérieur à ×100.",
      "Les structures intracellulaires nanométriques deviennent toutes visibles.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "À ×200, la forme cellulaire devient accessible, sans atteindre la résolution électronique.",
    choiceExplanations: [
      "Le calcul donne deux cents.",
      "Cette capacité est indiquée.",
      "Deux cents est bien supérieur à cent.",
      "La résolution optique ne permet pas tous les détails nanométriques.",
    ],
  },
  {
    order: 90,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Avec un objectif ×40 et un oculaire ×10 :",
    choices: [
      "Le grossissement total est ×400.",
      "La forme des cellules est observée avec davantage de précision.",
      "L’organisation des tissus peut être étudiée.",
      "Le prélèvement est nécessairement observé en microscopie électronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le grossissement ×400 reste optique et permet une lecture fine de la morphologie cellulaire et tissulaire.",
    choiceExplanations: [
      "Le calcul donne quatre cents.",
      "Le cours cite notamment les formes cylindrique ou fusiforme.",
      "L’organisation tissulaire est mieux appréciée.",
      "Il s’agit encore de microscopie optique.",
    ],
  },
  {
    order: 91,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Avec un objectif ×100 et un oculaire ×10 :",
    choices: [
      "Le grossissement total est ×1000.",
      "Il s’agit du plus fort grossissement optique cité.",
      "L’image peut devenir floue parce que la résolution limite l’analyse.",
      "Le grossissement garantit une résolution meilleure que celle du microscope électronique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "À ×1000, le grossissement atteint la limite pratique décrite pour l’optique, sans améliorer suffisamment la résolution.",
    choiceExplanations: [
      "Le produit donne mille.",
      "C’est la limite indiquée dans le cours.",
      "L’image peut être agrandie sans nouveaux détails nets.",
      "La microscopie électronique conserve une résolution bien supérieure.",
    ],
  },
  {
    order: 92,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Calculer et interpréter un grossissement total :",
    choices: [
      "Un objectif ×20 avec un oculaire ×10 donne ×200.",
      "Un objectif ×40 avec un oculaire ×10 donne ×400.",
      "Le grossissement total s’obtient en multipliant les deux valeurs.",
      "Un grossissement plus élevé améliore toujours sans limite la résolution.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le grossissement total est multiplicatif, mais il reste limité par le pouvoir séparateur du système.",
    choiceExplanations: [
      "Le calcul est correct.",
      "Le calcul est correct.",
      "C’est la règle utilisée dans les exemples.",
      "Au-delà de la résolution utile, l’image peut seulement être plus grande et plus floue.",
    ],
  },
  {
    order: 93,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La microscopie à fond clair numérique, ou scanner de lame :",
    choices: [
      "Ne change pas la préparation de la lame.",
      "Conserve le principe général du microscope optique.",
      "Capte l’image avec une caméra numérique.",
      "Permet une visualisation sur ordinateur.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le scanner numérise l’observation sans modifier les étapes de création de la lame.",
    choiceExplanations: [
      "Le cours précise l’absence de changement.",
      "Le principe optique est conservé.",
      "La caméra remplace l’observation directe exclusive.",
      "L’image est consultée numériquement.",
    ],
  },
  {
    order: 94,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La pathologie digitale peut, d’après le cours :",
    choices: [
      "Faciliter les échanges de lames entre médecins.",
      "Permettre l’intégration d’outils d’intelligence artificielle dans l’interprétation.",
      "S’appuyer sur des images de lames numérisées.",
      "Supprimer toute nécessité de préparer une lame.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La numérisation facilite le partage et ouvre la voie à l’assistance informatique, sans supprimer la préparation histologique.",
    choiceExplanations: [
      "Le partage devient plus simple.",
      "Cette possibilité est explicitement mentionnée.",
      "Le scanner produit ces images.",
      "Le cours précise que la création de la lame ne change pas.",
    ],
  },
  {
    order: 95,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer microscopie électronique à transmission et à balayage :",
    choices: [
      "En transmission, les électrons traversent l’échantillon.",
      "En balayage, les électrons explorent la surface.",
      "La transmission est adaptée aux structures intracellulaires.",
      "Le balayage permet de reconstituer des reliefs.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le MET renseigne sur l’intérieur d’une coupe très fine, tandis que le MEB décrit la surface et son relief.",
    choiceExplanations: [
      "C’est le principe du MET.",
      "C’est le principe du MEB.",
      "La résolution et la transmission permettent cette observation.",
      "Le capteur reconstruit le relief de surface.",
    ],
  },
  {
    order: 96,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La préparation d’un échantillon pour la microscopie électronique à transmission comprend :",
    choices: [
      "Une inclusion dans une résine.",
      "Une coupe de quelques dizaines de nanomètres.",
      "L’utilisation d’un ultramicrotome.",
      "Le dépôt sur une grille.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le MET nécessite un support très solide et des coupes ultrafines placées sur des grilles.",
    choiceExplanations: [
      "La résine remplace la paraffine.",
      "Cette épaisseur est celle du cours.",
      "Cet appareil réalise les coupes ultrafines.",
      "La grille porte l’échantillon.",
    ],
  },
  {
    order: 97,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le microscope électronique à transmission nécessite une colonne sous vide parce que :",
    choices: [
      "Les électrons sont déviés dans l’air libre.",
      "Le vide favorise un trajet plus rectiligne des électrons.",
      "L’appareil comporte un canon à électrons.",
      "Le vide sert principalement à colorer les noyaux en violet.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le vide permet au faisceau électronique de se propager correctement jusqu’à l’échantillon et au détecteur.",
    choiceExplanations: [
      "C’est la difficulté indiquée.",
      "Le trajet est plus direct dans le vide.",
      "Le canon produit le faisceau.",
      "La couleur violette appartient à l’HES, pas au fonctionnement électronique.",
    ],
  },
  {
    order: 98,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Sur l’image en noir et blanc obtenue en transmission :",
    choices: [
      "Une zone blanche correspond à des électrons ayant traversé.",
      "Une zone noire correspond à une structure ayant bloqué davantage d’électrons.",
      "Le contraste dépend de la transmission électronique.",
      "Toutes les structures sont naturellement observées en leurs couleurs réelles.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le détecteur traduit la quantité d’électrons transmis en niveaux de gris.",
    choiceExplanations: [
      "Le blanc correspond au passage d’électrons selon le cours.",
      "Le noir traduit une moindre transmission.",
      "Le contraste repose sur cette différence.",
      "L’image obtenue est en noir et blanc.",
    ],
  },
  {
    order: 99,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "En microscopie électronique à balayage :",
    choices: [
      "L’échantillon n’est pas coupé comme pour le MET.",
      "Le faisceau balaie la surface.",
      "Des électro-aimants orientent le faisceau.",
      "Le capteur aide à reconstituer les reliefs.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le MEB produit une information de surface grâce à un faisceau mobile.",
    choiceExplanations: [
      "Le cours précise l’absence de coupe.",
      "Le balayage donne son nom à la technique.",
      "Les électro-aimants déplacent le faisceau.",
      "Le relief est le résultat recherché.",
    ],
  },
  {
    order: 100,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Choisir le microscope selon l’objectif :",
    choices: [
      "Observer l’organisation générale d’une lame HES — microscope optique à fond clair.",
      "Étudier une structure intracellulaire très fine — microscope électronique à transmission.",
      "Étudier le relief de cils vibratiles — microscope électronique à balayage.",
      "Partager numériquement une lame entre médecins — scanner de lame.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Chaque dispositif répond à un besoin d’observation différent.",
    choiceExplanations: [
      "Le fond clair est adapté aux lames colorées.",
      "Le MET donne accès à l’ultrastructure interne.",
      "Le MEB visualise les reliefs de surface.",
      "La numérisation facilite le partage.",
    ],
  },
];

export const SECTION_E_QUIZZES: SeedQuiz[] = [
  {
    order: 9,
    slug: "microscopie-optique-grossissement",
    title: "Microscopie optique et grossissement",
    description: "Principes du microscope optique à fond clair, résolution, composants et niveaux de grossissement.",
    stage: 'DISCOVER',
    sectionOrder: 5,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
  {
    order: 10,
    slug: "microscopies-numeriques-electroniques",
    title: "Microscopies numériques et électroniques",
    description: "Limites du grossissement optique, scanner de lame, MET et MEB.",
    stage: 'PRACTICE',
    sectionOrder: 5,
    items: [
      { type: 'QUESTION', questionOrder: 91 },
      { type: 'QUESTION', questionOrder: 92 },
      {
        type: 'GROUP',
        title: "Numérisation d’une lame histologique",
        sharedStatement: "Une lame histologique colorée est numérisée à l’aide d’un scanner de lame afin d’être consultée sur ordinateur et partagée entre médecins.",
        questionOrders: [93, 94],
      },
      { type: 'QUESTION', questionOrder: 95 },
      { type: 'QUESTION', questionOrder: 96 },
      { type: 'QUESTION', questionOrder: 97 },
      { type: 'QUESTION', questionOrder: 98 },
      { type: 'QUESTION', questionOrder: 99 },
      { type: 'QUESTION', questionOrder: 100 },
    ],
  },
];
