import type { SeedQuestion, SeedQuiz } from './health-training-ue13.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 41,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La coloration HES associe :",
    choices: [
      "L’hématoxyline.",
      "L’éosine.",
      "Le safran.",
      "L’orcéine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "HES signifie hématoxyline-éosine-safran.",
    choiceExplanations: [
      "Le H de HES correspond à l’hématoxyline.",
      "Le E correspond à l’éosine.",
      "Le S correspond au safran.",
      "L’orcéine est une coloration spécifique distincte.",
    ],
  },
  {
    order: 42,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Dans une coloration HES, l’hématoxyline :",
    choices: [
      "Met en évidence les noyaux.",
      "Colore les noyaux en violet.",
      "Met principalement le collagène en orange.",
      "Contribue au contraste nucléaire.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’hématoxyline fournit le contraste violet des noyaux cellulaires.",
    choiceExplanations: [
      "Le noyau est sa cible principale dans le cours.",
      "Le violet est la couleur attendue.",
      "Le collagène orange dépend du safran.",
      "Le contraste nucléaire facilite l’identification des cellules.",
    ],
  },
  {
    order: 43,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Dans une coloration HES, l’éosine :",
    choices: [
      "Met en évidence les protéines en rose.",
      "Colore le cytoplasme en rose.",
      "Peut rendre les membranes plus foncées et les contours plus visibles.",
      "Colore spécifiquement les fibres de réticuline en noir.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’éosine donne les teintes roses des constituants protéiques et des contours cellulaires.",
    choiceExplanations: [
      "Cette fonction est indiquée dans le cours.",
      "Le cytoplasme prend globalement une teinte rose.",
      "Les bordures cellulaires peuvent apparaître plus foncées.",
      "La réticuline nécessite une coloration spécifique.",
    ],
  },
  {
    order: 44,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Dans une coloration HES, le safran :",
    choices: [
      "Met en évidence le collagène.",
      "Colore le collagène en orange.",
      "Participe à la visualisation de l’environnement extracellulaire.",
      "Est le principal colorant nucléaire violet.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le safran fournit le contraste orange du collagène dans l’environnement extracellulaire.",
    choiceExplanations: [
      "Le collagène est la structure ciblée.",
      "La couleur orange est celle du cours.",
      "Le collagène appartient à l’environnement extracellulaire.",
      "La coloration nucléaire violette dépend de l’hématoxyline.",
    ],
  },
  {
    order: 45,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Sur une coupe HES classique :",
    choices: [
      "Les noyaux apparaissent violets.",
      "Le cytoplasme apparaît rose.",
      "L’environnement extracellulaire riche en collagène apparaît orangé.",
      "Le mucus est nécessairement fuchsia.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La combinaison violet-rose-orange correspond aux contrastes de base de l’HES.",
    choiceExplanations: [
      "Cette couleur est liée à l’hématoxyline.",
      "Cette couleur est liée à l’éosine.",
      "Cette couleur est liée au safran.",
      "Le mucus fuchsia est caractéristique de la coloration PAS.",
    ],
  },
  {
    order: 46,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Après la coloration de la coupe :",
    choices: [
      "Une lamelle transparente peut être posée sur la lame.",
      "Une colle transparente peut maintenir la lamelle.",
      "La lamelle contribue à protéger la préparation.",
      "La coupe est obligatoirement retirée de la lame pour être observée.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le montage final protège la coupe colorée sous une lamelle transparente.",
    choiceExplanations: [
      "Cette étape est décrite dans le cours.",
      "La colle transparente assure le montage.",
      "La protection de la lame est l’objectif.",
      "La coupe reste sur son support de verre.",
    ],
  },
  {
    order: 47,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La coloration PAS :",
    choices: [
      "Correspond à l’acide périodique-Schiff.",
      "Met en évidence le mucus.",
      "Donne au mucus une teinte fuchsia.",
      "Est la coloration standard du collagène III en noir.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le PAS est utilisé pour révéler le mucus, peu visible en HES, sous une teinte fuchsia.",
    choiceExplanations: [
      "Le sigle est développé ainsi dans le cours.",
      "Le mucus est la cible indiquée.",
      "Le fuchsia est la couleur attendue.",
      "Le collagène III est mis en évidence par la réticuline.",
    ],
  },
  {
    order: 48,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La coloration à l’orcéine :",
    choices: [
      "Met en évidence les fibres élastiques.",
      "Révèle l’élastine.",
      "Donne une teinte marron à noire.",
      "Est inutile pour une structure incolore en HES.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’orcéine révèle l’élastine, qui est incolore dans la coloration HES.",
    choiceExplanations: [
      "Les fibres élastiques constituent la cible.",
      "L’élastine est la molécule mise en évidence.",
      "Le cours indique une couleur marron voire noire.",
      "Elle est précisément utile parce que l’élastine est peu visible en HES.",
    ],
  },
  {
    order: 49,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La coloration à la réticuline :",
    choices: [
      "Est spécifique du collagène de type III.",
      "Met les fibres de réticuline en noir.",
      "Peut aider à distinguer le collagène III du collagène I.",
      "Colore tous les noyaux en fuchsia.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La réticuline met spécifiquement en évidence les fibres de collagène III.",
    choiceExplanations: [
      "Cette spécificité est indiquée.",
      "Le noir est la couleur observée.",
      "La coloration spécifique facilite cette distinction.",
      "Cette proposition ne correspond pas à son usage.",
    ],
  },
  {
    order: 50,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Pour différencier du collagène III d’un collagène I sur une coupe :",
    choices: [
      "Une coloration à la réticuline peut être utile.",
      "Le safran seul colore globalement le collagène sans cette spécificité.",
      "Des fibres noires après réticuline orientent vers le collagène III.",
      "La coloration PAS est la méthode spécifique indiquée pour cette distinction.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le safran révèle le collagène en général, alors que la réticuline cible le collagène III.",
    choiceExplanations: [
      "C’est l’indication spécifique du cours.",
      "Le safran n’apporte pas la même spécificité.",
      "Le noir est le contraste attendu.",
      "Le PAS est surtout présenté pour le mucus.",
    ],
  },
  {
    order: 51,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une coupe montre des noyaux violets, des cytoplasmes roses et du collagène orangé. On peut conclure que :",
    choices: [
      "La coloration HES est compatible avec cet aspect.",
      "L’hématoxyline explique le violet nucléaire.",
      "L’éosine explique le rose cytoplasmique.",
      "L’orcéine est nécessairement l’unique coloration utilisée.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La combinaison des trois contrastes correspond au profil attendu d’une coloration HES.",
    choiceExplanations: [
      "Les trois couleurs sont celles de l’HES.",
      "Le noyau violet dépend de l’hématoxyline.",
      "Le cytoplasme rose dépend de l’éosine.",
      "L’orcéine est une coloration spécifique de l’élastine.",
    ],
  },
  {
    order: 52,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Sur cette même coupe HES, une zone riche en mucus reste peu visible. Pour mieux l’étudier :",
    choices: [
      "Une coloration PAS peut être demandée.",
      "Le mucus devrait alors apparaître fuchsia.",
      "L’absence de coloration du mucus en HES est compatible avec le cours.",
      "Une coloration à la réticuline est la méthode spécifique du mucus.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le PAS complète l’HES lorsqu’on souhaite mettre le mucus en évidence.",
    choiceExplanations: [
      "Le PAS est la coloration spécifique indiquée.",
      "Le fuchsia est le contraste attendu.",
      "Le cours précise que le mucus n’est pas coloré en HES.",
      "La réticuline cible le collagène III.",
    ],
  },
  {
    order: 53,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un anatomopathologiste souhaite visualiser des fibres élastiques peu visibles sur l’HES. Il peut :",
    choices: [
      "Utiliser une coloration à l’orcéine.",
      "Rechercher une teinte marron à noire.",
      "S’attendre à mieux voir l’élastine.",
      "Choisir prioritairement le PAS parce qu’il colore spécifiquement l’élastine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’orcéine est la coloration spécifique présentée pour les fibres élastiques.",
    choiceExplanations: [
      "C’est l’indication appropriée.",
      "C’est la teinte décrite.",
      "L’élastine est la structure ciblée.",
      "Le PAS met surtout en évidence le mucus.",
    ],
  },
  {
    order: 54,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Des fibres deviennent noires après une coloration spécifique du collagène III. Ces éléments :",
    choices: [
      "Peuvent correspondre à des fibres de réticuline.",
      "Sont révélés par la coloration à la réticuline.",
      "Permettent de distinguer ce collagène du collagène I.",
      "Correspondent nécessairement à du mucus coloré par le PAS.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le noir des fibres de réticuline est un repère du collagène III.",
    choiceExplanations: [
      "Cette identification est celle du cours.",
      "La méthode porte le nom de la structure révélée.",
      "La spécificité aide à la distinction.",
      "Le mucus PAS apparaît fuchsia, non noir.",
    ],
  },
  {
    order: 55,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Associer correctement une cible à une coloration :",
    choices: [
      "Noyau violet — hématoxyline.",
      "Protéines cytoplasmiques roses — éosine.",
      "Collagène orange — safran.",
      "Mucus fuchsia — PAS.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Ces associations résument les principaux contrastes présentés dans le chapitre.",
    choiceExplanations: [
      "Association correcte.",
      "Association correcte.",
      "Association correcte.",
      "Association correcte.",
    ],
  },
  {
    order: 56,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À propos de la nécessité de colorer les lames histologiques :",
    choices: [
      "La plupart des cellules sont naturellement peu colorées.",
      "La coloration augmente le contraste entre les structures.",
      "La mélanine, la bile et l’hémoglobine sont citées comme couleurs naturelles.",
      "Une lame blanche offre toujours spontanément les mêmes contrastes que l’HES.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La coloration transforme une coupe presque incolore en préparation interprétable.",
    choiceExplanations: [
      "C’est la raison générale de la coloration.",
      "Le contraste permet de distinguer les constituants.",
      "Ces trois exemples sont cités dans le cours.",
      "La lame blanche est précisément non colorée.",
    ],
  },
  {
    order: 57,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une coupe peut être étudiée successivement ou comparativement avec plusieurs colorations parce que :",
    choices: [
      "L’HES fournit une vue d’ensemble.",
      "Des colorations spécifiques peuvent cibler certaines structures.",
      "Le PAS, l’orcéine et la réticuline répondent à des objectifs différents.",
      "Toutes les colorations donnent exactement les mêmes informations.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’HES sert de coloration de base, complétée selon la structure recherchée.",
    choiceExplanations: [
      "L’HES contraste les principaux compartiments tissulaires.",
      "Les colorations spéciales apportent une information ciblée.",
      "Leurs cibles respectives sont différentes.",
      "La complémentarité existe précisément parce que les informations diffèrent.",
    ],
  },
  {
    order: 58,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une structure est orange sur une lame HES et noire sur une coloration spécifique de réticuline. On peut proposer que :",
    choices: [
      "Elle appartient à l’environnement extracellulaire.",
      "Elle contient du collagène.",
      "La coloration spécifique oriente vers du collagène III.",
      "Elle correspond obligatoirement à un noyau cellulaire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le safran révèle le collagène en orange et la réticuline cible le collagène III en noir.",
    choiceExplanations: [
      "Le collagène se situe dans la matrice extracellulaire.",
      "L’orange HES est compatible avec du collagène.",
      "Le noir après réticuline apporte la spécificité de type III.",
      "Un noyau serait surtout violet avec l’hématoxyline.",
    ],
  },
  {
    order: 59,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Parmi les affirmations suivantes sur l’HES :",
    choices: [
      "Elle constitue la coloration de base des lames histologiques.",
      "Elle associe trois colorants.",
      "Elle met parfaitement en évidence l’élastine sans coloration complémentaire.",
      "Elle permet de contraster noyaux, cytoplasmes et environnement extracellulaire.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’HES est une coloration générale ; certaines structures nécessitent une méthode spécifique.",
    choiceExplanations: [
      "Le cours la présente comme la coloration de base.",
      "Son nom correspond à trois colorants.",
      "L’élastine est décrite comme incolore en HES.",
      "C’est sa fonction générale.",
    ],
  },
  {
    order: 60,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une biopsie d’une muqueuse produit beaucoup de mucus. Pour documenter ce produit de sécrétion :",
    choices: [
      "Une coloration PAS est pertinente.",
      "Une teinte fuchsia est attendue dans les zones riches en mucus.",
      "L’HES peut être insuffisante pour mettre le mucus en évidence.",
      "La coloration à l’orcéine est la méthode spécifique indiquée pour le mucus.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le PAS est la coloration complémentaire adaptée à la visualisation du mucus.",
    choiceExplanations: [
      "Cette indication correspond au cours.",
      "C’est le contraste attendu.",
      "Le mucus n’est pas mis en évidence par l’HES selon le document.",
      "L’orcéine cible les fibres élastiques.",
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 5,
    slug: "principes-coloration-hes",
    title: "Principes de la coloration HES",
    description: "Rôle de l’hématoxyline, de l’éosine et du safran, puis découverte des colorations spécifiques.",
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: "choisir-interpreter-coloration",
    title: "Choisir et interpréter une coloration",
    description: "Interprétation de contrastes et choix raisonné entre HES, PAS, orcéine et réticuline.",
    stage: 'PRACTICE',
    sectionOrder: 3,
    items: [
      {
        type: 'GROUP',
        title: "Lecture comparative d’une coupe de muqueuse",
        sharedStatement: "Une coupe histologique présente des noyaux violets, des cytoplasmes roses et du collagène orangé. Une zone riche en mucus reste cependant peu visible.",
        questionOrders: [51, 52],
      },
      { type: 'QUESTION', questionOrder: 53 },
      { type: 'QUESTION', questionOrder: 54 },
      { type: 'QUESTION', questionOrder: 55 },
      { type: 'QUESTION', questionOrder: 56 },
      { type: 'QUESTION', questionOrder: 57 },
      { type: 'QUESTION', questionOrder: 58 },
      { type: 'QUESTION', questionOrder: 59 },
      { type: 'QUESTION', questionOrder: 60 },
    ],
  },
];
