/**
 * Cartographie éditoriale V2 — auteur
 */

export const UE14_BIOCH_CH8_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-sterane-sterols-sterides",
    "title": "Noyau stérane, stérols, stérides et stéroïdes",
    "description": "Repères sur le noyau stérane et la distinction stérol, stéride et stéroïde.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-classes-steroliques",
    "title": "Noyau stérane, stérols, stérides et stéroïdes",
    "description": "Applications sur numérotation, fonctions C3, estérification et squalène.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-cholesterol",
    "title": "Cholestérol et dérivés",
    "description": "Repères structuraux et physicochimiques sur le cholestérol libre et estérifié.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-cholesterol-derives",
    "title": "Cholestérol et dérivés",
    "description": "Applications sur membranes, lipoprotéines, acides biliaires et vitamine D.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-hormones-steroides-noyaux",
    "title": "Hormones stéroïdiennes : noyaux et origines",
    "description": "Repères sur les noyaux estrane, androstane et prégnane et leurs hormones.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-origines-hormones-steroides",
    "title": "Hormones stéroïdiennes : noyaux et origines",
    "description": "Applications sur corticosurrénales, gonades, placenta et classes hormonales.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-corticosteroides-hormones-sexuelles",
    "title": "Fonctions des corticostéroïdes et hormones sexuelles",
    "description": "Repères sur aldostérone, cortisol, androgènes, œstrogènes et progestérone.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-physiologie-hormonale",
    "title": "Fonctions des corticostéroïdes et hormones sexuelles",
    "description": "Applications physiologiques et médicales sur rein, inflammation, métabolisme et cycle ovarien.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-endocrinologie-steroides",
    "title": "Fonctions hormonales des stéroïdes",
    "description": "Maîtrise des couples hormone–origine–structure–fonction et des pièges signalés.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-sterols-steroides",
    "title": "Stérols, stéroïdes et stérides",
    "description": "Synthèse appliquée des structures, dérivés du cholestérol et hormones stéroïdiennes.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-sterols-steroides-sterides",
    "title": "Stérols, stéroïdes et stérides",
    "description": "Maîtrise transversale du chapitre dans l'esprit de l'examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH8_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Noyau stérane et classes"],
  2: ["Noyau stérane et classes"],
  3: ["Noyau stérane et classes"],
  4: ["Noyau stérane et classes"],
  5: ["Noyau stérane et classes"],
  6: ["Noyau stérane et classes"],
  7: ["Noyau stérane et classes"],
  8: ["Noyau stérane et classes"],
  9: ["Noyau stérane et classes"],
  10: ["Noyau stérane et classes"],
  11: ["Noyau stérane et classes"],
  12: ["Noyau stérane et classes"],
  13: ["Noyau stérane et classes"],
  14: ["Noyau stérane et classes"],
  15: ["Noyau stérane et classes"],
  16: ["Noyau stérane et classes"],
  17: ["Noyau stérane et classes"],
  18: ["Noyau stérane et classes"],
  19: ["Noyau stérane et classes"],
  20: ["Noyau stérane et classes"],
  21: ["Noyau stérane et classes"],
  22: ["Noyau stérane et classes"],
  23: ["Cholestérol et dérivés"],
  24: ["Cholestérol et dérivés"],
  25: ["Cholestérol et dérivés"],
  26: ["Cholestérol et dérivés"],
  27: ["Cholestérol et dérivés"],
  28: ["Cholestérol et dérivés"],
  29: ["Cholestérol et dérivés"],
  30: ["Cholestérol et dérivés"],
  31: ["Cholestérol et dérivés"],
  32: ["Cholestérol et dérivés"],
  33: ["Cholestérol et dérivés"],
  34: ["Cholestérol et dérivés"],
  35: ["Cholestérol et dérivés"],
  36: ["Cholestérol et dérivés"],
  37: ["Cholestérol et dérivés"],
  38: ["Cholestérol et dérivés"],
  39: ["Cholestérol et dérivés"],
  40: ["Cholestérol et dérivés"],
  41: ["Cholestérol et dérivés"],
  42: ["Cholestérol et dérivés"],
  43: ["Cholestérol et dérivés"],
  44: ["Cholestérol et dérivés"],
  45: ["Hormones stéroïdiennes : noyaux et origines"],
  46: ["Hormones stéroïdiennes : noyaux et origines"],
  47: ["Hormones stéroïdiennes : noyaux et origines"],
  48: ["Hormones stéroïdiennes : noyaux et origines"],
  49: ["Hormones stéroïdiennes : noyaux et origines"],
  50: ["Hormones stéroïdiennes : noyaux et origines"],
  51: ["Hormones stéroïdiennes : noyaux et origines"],
  52: ["Hormones stéroïdiennes : noyaux et origines"],
  53: ["Hormones stéroïdiennes : noyaux et origines"],
  54: ["Hormones stéroïdiennes : noyaux et origines"],
  55: ["Hormones stéroïdiennes : noyaux et origines"],
  56: ["Hormones stéroïdiennes : noyaux et origines"],
  57: ["Hormones stéroïdiennes : noyaux et origines"],
  58: ["Hormones stéroïdiennes : noyaux et origines"],
  59: ["Hormones stéroïdiennes : noyaux et origines"],
  60: ["Hormones stéroïdiennes : noyaux et origines"],
  61: ["Hormones stéroïdiennes : noyaux et origines"],
  62: ["Hormones stéroïdiennes : noyaux et origines"],
  63: ["Hormones stéroïdiennes : noyaux et origines"],
  64: ["Hormones stéroïdiennes : noyaux et origines"],
  65: ["Hormones stéroïdiennes : noyaux et origines"],
  66: ["Hormones stéroïdiennes : noyaux et origines"],
  67: ["Physiologie des hormones stéroïdiennes"],
  68: ["Physiologie des hormones stéroïdiennes"],
  69: ["Physiologie des hormones stéroïdiennes"],
  70: ["Physiologie des hormones stéroïdiennes"],
  71: ["Physiologie des hormones stéroïdiennes"],
  72: ["Physiologie des hormones stéroïdiennes"],
  73: ["Physiologie des hormones stéroïdiennes"],
  74: ["Physiologie des hormones stéroïdiennes"],
  75: ["Physiologie des hormones stéroïdiennes"],
  76: ["Physiologie des hormones stéroïdiennes"],
  77: ["Physiologie des hormones stéroïdiennes"],
  78: ["Physiologie des hormones stéroïdiennes"],
  79: ["Physiologie des hormones stéroïdiennes"],
  80: ["Physiologie des hormones stéroïdiennes"],
  81: ["Physiologie des hormones stéroïdiennes"],
  82: ["Physiologie des hormones stéroïdiennes"],
  83: ["Physiologie des hormones stéroïdiennes"],
  84: ["Physiologie des hormones stéroïdiennes"],
  85: ["Physiologie des hormones stéroïdiennes"],
  86: ["Physiologie des hormones stéroïdiennes"],
  87: ["Physiologie des hormones stéroïdiennes"],
  88: ["Physiologie des hormones stéroïdiennes"],
  89: ["QZONE : corticosurrénale"],
  90: ["Physiologie des hormones stéroïdiennes"],
  91: ["Physiologie des hormones stéroïdiennes"],
  92: ["Cortisol = hydrocortisone"],
  93: ["Physiologie des hormones stéroïdiennes"],
  94: ["Physiologie des hormones stéroïdiennes"],
  95: ["Physiologie des hormones stéroïdiennes"],
  96: ["Physiologie des hormones stéroïdiennes"],
  97: ["Hormones stéroïdiennes : fonctions"],
  98: ["Physiologie des hormones stéroïdiennes"],
  99: ["Physiologie des hormones stéroïdiennes"],
  100: ["Physiologie des hormones stéroïdiennes"],
  101: ["Synthèse appliquée"],
  102: ["Synthèse appliquée"],
  103: ["Synthèse appliquée"],
  104: ["Synthèse appliquée"],
  105: ["Synthèse appliquée"],
  106: ["Synthèse appliquée"],
  107: ["Synthèse appliquée"],
  108: ["Synthèse appliquée"],
  109: ["Synthèse appliquée"],
  110: ["Synthèse appliquée"],
  111: ["Maîtrise transversale"],
  112: ["Maîtrise transversale"],
  113: ["Maîtrise transversale"],
  114: ["Maîtrise transversale"],
  115: ["Aldostérone : minéralocorticoïde"],
  116: ["Maîtrise transversale"],
  117: ["Maîtrise transversale"],
  118: ["Maîtrise transversale"],
  119: ["Maîtrise transversale"],
  120: ["Maîtrise transversale"],
  121: ["Maîtrise transversale"],
  122: ["Maîtrise transversale"],
};
