/**
 * Métadonnées éditoriales V2 – UE14 Chimie générale – Chapitre 1.
 *
 * Le premier quiz DISCOVER « Atomes » est déjà intégré et validé dans le repo.
 * Ce fichier décrit les 7 quiz restant à migrer.
 */

export const UE14_CH1_V2_QUIZ_MAP = [
  {
    sectionOrder: 1,
    order: 2,
    slug: 'sentrainer-generalites-atome',
    title: `Généralités sur l'atome`,
    description: `Applications sur la structure atomique, les nucléides, les isotopes, les ions simples et les ordres de grandeur.`,
    stage: 'PRACTICE' as const,
    questionOrders: [25, 14, 26, 16, 17, 18, 19, 20, 23, 24],
  },
  {
    sectionOrder: 2,
    order: 1,
    slug: 'decouvrir-organisation-configuration-electronique',
    title: `Organisation et configuration électronique`,
    description: `Repères fondamentaux sur les nombres quantiques, sous-couches, orbitales, règle de Hund et configurations électroniques.`,
    stage: 'DISCOVER' as const,
    questionOrders: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
  },
  {
    sectionOrder: 2,
    order: 2,
    slug: 'sentrainer-organisation-configuration-electronique',
    title: `Organisation et configuration électronique`,
    description: `Applications sur les nombres quantiques, les capacités électroniques, les cases quantiques et l'ordre énergétique des sous-couches.`,
    stage: 'PRACTICE' as const,
    items: [
      { type: 'QUESTION' as const, questionOrder: 28 },
      { type: 'QUESTION' as const, questionOrder: 29 },
      { type: 'QUESTION' as const, questionOrder: 40 },
      { type: 'QUESTION' as const, questionOrder: 41 },
      { type: 'QUESTION' as const, questionOrder: 42 },
      { type: 'QUESTION' as const, questionOrder: 43 },
      {
        type: 'GROUP' as const,
        title: `Élément fer`,
        sharedStatement:
          `On considère l'atome de fer ($\\mathrm{Z}=26$), dont la configuration électronique dans l'état fondamental se termine par $4\\mathrm{s}^2\\,3\\mathrm{d}^6$.`,
        questionOrders: [44, 45],
      },
      { type: 'QUESTION' as const, questionOrder: 46 },
      { type: 'QUESTION' as const, questionOrder: 47 },
      { type: 'QUESTION' as const, questionOrder: 5 },
      { type: 'QUESTION' as const, questionOrder: 6 },
    ],
  },
  {
    sectionOrder: 3,
    order: 1,
    slug: 'decouvrir-classification-periodique',
    title: `Classification périodique`,
    description: `Repères sur les périodes, colonnes, blocs, familles et éléments du vivant.`,
    stage: 'DISCOVER' as const,
    questionOrders: [8, 57, 56, 9, 58, 59, 60, 61, 62, 10],
  },
  {
    sectionOrder: 3,
    order: 2,
    slug: 'sentrainer-classification-periodique',
    title: `Classification périodique`,
    description: `Applications sur les familles, les configurations de valence, les éléments du vivant et le repérage dans le tableau périodique.`,
    stage: 'PRACTICE' as const,
    items: [
      { type: 'QUESTION' as const, questionOrder: 55 },
      { type: 'QUESTION' as const, questionOrder: 64 },
      {
        type: 'GROUP' as const,
        title: `Métaux, non-métaux et métalloïdes`,
        sharedStatement:
          `La classification périodique distingue principalement les métaux à gauche et au centre, les non-métaux à droite, et des métalloïdes à leur frontière.`,
        questionOrders: [66, 67],
      },
      { type: 'QUESTION' as const, questionOrder: 65 },
      { type: 'QUESTION' as const, questionOrder: 68 },
      { type: 'QUESTION' as const, questionOrder: 69 },
      { type: 'QUESTION' as const, questionOrder: 70 },
      { type: 'QUESTION' as const, questionOrder: 72 },
      { type: 'QUESTION' as const, questionOrder: 73 },
    ],
  },
  {
    sectionOrder: 4,
    order: 1,
    slug: 'sentrainer-synthese-atomes',
    title: `Éléments et classification`,
    description: `Synthèse appliquée reliant nucléides, organisation électronique, classification et éléments d'intérêt biologique ou médical.`,
    stage: 'PRACTICE' as const,
    items: [
      {
        type: 'GROUP' as const,
        title: `Iode et isotopes`,
        sharedStatement:
          `L'iode est un oligoélément halogène concentré par la thyroïde. On considère $\\ce{^{127}_{53}I}$ et $\\ce{^{131}_{53}I}$, deux de ses nucléides.`,
        questionOrders: [75, 76],
      },
      { type: 'QUESTION' as const, questionOrder: 77 },
      {
        type: 'GROUP' as const,
        title: `Calcium et classification périodique`,
        sharedStatement:
          `Le calcium fait partie des éléments de base du vivant. On considère son atome neutre de numéro atomique $\\mathrm{Z}=20$.`,
        questionOrders: [78, 79],
      },
      {
        type: 'GROUP' as const,
        title: `Phosphore et organisation électronique`,
        sharedStatement:
          `Le phosphore fait partie des éléments de base du vivant. Son numéro atomique est $\\mathrm{Z}=15$.`,
        questionOrders: [80, 81],
      },
      { type: 'QUESTION' as const, questionOrder: 82 },
      { type: 'QUESTION' as const, questionOrder: 83 },
      { type: 'QUESTION' as const, questionOrder: 84 },
    ],
  },
  {
    sectionOrder: 4,
    order: 2,
    slug: 'synthese-atomes',
    title: `Éléments et classification`,
    description: `Maîtrise transversale du chapitre : noyau, orbitales, configurations électroniques, classification et calculs isotopiques.`,
    stage: 'MASTER' as const,
    items: [
      { type: 'QUESTION' as const, questionOrder: 27 },
      { type: 'QUESTION' as const, questionOrder: 48 },
      { type: 'QUESTION' as const, questionOrder: 49 },
      { type: 'QUESTION' as const, questionOrder: 50 },
      { type: 'QUESTION' as const, questionOrder: 51 },
      {
        type: 'GROUP' as const,
        title: `Élément nickel`,
        sharedStatement:
          `On considère l'atome de nickel ($\\mathrm{Z}=28$), dont la configuration électronique dans l'état fondamental se termine par $4\\mathrm{s}^2\\,3\\mathrm{d}^8$.`,
        questionOrders: [52, 53],
      },
      { type: 'QUESTION' as const, questionOrder: 54 },
      { type: 'QUESTION' as const, questionOrder: 71 },
      { type: 'QUESTION' as const, questionOrder: 74 },
      { type: 'QUESTION' as const, questionOrder: 7 },
      { type: 'QUESTION' as const, questionOrder: 63 },
    ],
  },
] as const;

export const UE14_CH1_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  5: [`Capacité électronique d'une sous-couche d`],
  6: [`Capacité électronique de la couche M`],
  7: [`Capacité électronique maximale de la couche N`],
  8: [`Organisation générale de la classification périodique`],
  9: [`Famille des gaz rares`],
  10: [`Oligoéléments du vivant`],
  14: [`Propriétés physiques et chimiques des isotopes`],
  16: [`Défaut de masse et composition des noyaux`],
  17: [`Validité d'une notation nucléaire générique`],
  18: [`Neutralité atomique et nombres de particules`],
  19: [`Répartition de la masse dans l'atome`],
  20: [`Fluor 18 : composition nucléaire et imagerie TEP`],
  23: [`Unité de masse atomique et dalton`],
  24: [`Ordres de grandeur : hématie et atome`],
  25: [`Conversion nanomètre – ångström`],
  26: [`Composition électronique d'un ion aluminium`],
  27: [`Synthèse du modèle atomique et nucléaire`],
  28: [`Rôle des nombres quantiques`],
  29: [`Nombre d'orbitales d'une sous-couche d`],
  30: [`Association nombres quantiques – niveaux électroniques`],
  31: [`Nombre quantique secondaire et sous-couche p`],
  32: [`Configuration électronique du bore`],
  33: [`Nombre quantique principal`],
  34: [`Configuration électronique de l'azote en cases quantiques`],
  35: [`Correspondance entre l et s/p/d/f`],
  36: [`Couche de valence du fer`],
  37: [`Valeurs de l pour n = 4`],
  38: [`Nombre d'orbitales d'une sous-couche p`],
  39: [`Règle de Hund`],
  40: [`Configuration électronique de l'oxygène en cases quantiques`],
  41: [`Violation de la règle de Hund`],
  42: [`Définition probabiliste d'une orbitale atomique`],
  43: [`Organisation et forme des orbitales atomiques`],
  44: [`Occupation 3d du fer`],
  45: [`Électrons de valence du fer selon le cours`],
  46: [`Validité de quadruplets de nombres quantiques`],
  47: [`Ordre énergétique 4s – 3d`],
  48: [`Capacité électronique d'une sous-couche f`],
  49: [`Synthèse sur les orbitales atomiques`],
  50: [`Ordre énergétique par la règle n + l`],
  51: [`Identification du chlore par sa configuration électronique`],
  52: [`Occupation 3d du nickel`],
  53: [`Couche de valence du nickel selon le cours`],
  54: [`Configuration ns2 et position dans la classification`],
  55: [`Organisation électronique et classification périodique`],
  56: [`Identification de l'oxygène par Z`],
  57: [`Position du bloc p`],
  58: [`Identification du sodium par sa configuration`],
  59: [`Magnésium : période et colonne`],
  60: [`Halogènes : colonne et configuration externe`],
  61: [`Métaux, métalloïdes et non-métaux`],
  62: [`Reconnaissance du bloc p par la configuration externe`],
  63: [`Calcul de masse atomique moyenne du chlore`],
  64: [`Iode : famille des halogènes`],
  65: [`Oligoéléments : sélection dans une liste longue`],
  66: [`Reconnaissance des métalloïdes`],
  67: [`Propriétés générales des métaux, métalloïdes et non-métaux`],
  68: [`Repérage spatial d'une configuration 3s2 dans le tableau périodique`],
  69: [`Configuration ns2 et métaux alcalino-terreux`],
  70: [`Chlore : période 3 et colonne 17`],
  71: [`Ordre des éléments de la deuxième période`],
  72: [`Zirconium : bloc d, période et application aux implants`],
  73: [`Lanthanides, actinides et bloc f`],
  74: [`Identification du fer et position dans la classification`],
  75: [`Comparaison neutronique des isotopes de l'iode`],
  76: [`Relation isotopique et propriétés de l'iode`],
  77: [`Cobalt 60 : nucléide et classification`],
  78: [`Configuration électronique du calcium`],
  79: [`Nombre quantique secondaire des électrons 4s du calcium`],
  80: [`Configuration de valence du phosphore en cases quantiques`],
  81: [`Électrons célibataires du phosphore`],
  82: [`Bore 10 : masse moyenne et contexte BNCT`],
  83: [`Sélénium : configuration externe et position`],
  84: [`Gadolinium : lanthanide, bloc f et agents de contraste IRM`],
};
