/**
 * UE14 – Biologie cellulaire – Chapitre 6
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les oxydases peroxysomales :`,
    choices: [
      `Utilisent de l’oxygène.`,
      `Oxydent des substrats.`,
      `Produisent du H2O2.`,
      `Détruisent toujours le H2O2 en H2O et O2.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les oxydases produisent le peroxyde d’hydrogène ; sa destruction relève notamment de la catalase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Le nom « peroxysome » est lié à la production de :`,
    choices: [
      `Peroxyde d’hydrogène H2O2.`,
      `ADN mitochondrial.`,
      `Acide lactique uniquement.`,
      `Mannose-6-phosphate.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La production de H2O2 par les oxydases explique le nom de l’organite.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La catalase :`,
    choices: [
      `Est très abondante dans le peroxysome.`,
      `Utilise le H2O2 produit par les oxydases.`,
      `Peut détruire l’excès de H2O2.`,
      `Produit toujours le H2O2 à la place des oxydases.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La catalase utilise ou élimine le H2O2 ; les oxydases sont responsables de sa production.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Oxydases et catalase](/images/training/ue14/biologie-cellulaire/peroxysomes/oxydases-catalase-h2o2.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les oxydases produisent du H2O2.`,
      `La catalase peut utiliser le H2O2 pour oxyder un substrat.`,
      `La catalase peut convertir l’excès de H2O2 en H2O et O2.`,
      `Le H2O2 est produit par la catalase dans toutes les réactions.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure met en évidence la succession production par les oxydases puis utilisation ou destruction par la catalase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’action des oxydases et de la catalase est décrite en deux étapes :`,
    choices: [
      `Production de H2O2 lors de l’oxydation initiale.`,
      `Utilisation du H2O2 par la catalase.`,
      `Destruction possible de l’excès de H2O2.`,
      `Synthèse préalable d’un génome peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le système repose sur une succession de réactions enzymatiques, sans intervention d’un génome peroxysomal.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La catalase peut :`,
    choices: [
      `Oxyder certains substrats en utilisant le H2O2.`,
      `Détruire l’excès de H2O2.`,
      `Produire H2O et O2 lors de la décomposition du H2O2.`,
      `Assurer seule la synthèse des acides nucléiques puriques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La catalase joue un rôle de détoxification oxydative ; elle n’assure pas la synthèse des purines.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `La destruction de l’excès de H2O2 par la catalase produit :`,
    choices: [
      `H2O et O2.`,
      `Uniquement du glucose.`,
      `Des acides gras à très longue chaîne.`,
      `De l’ADN peroxysomal.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La fiche indique une conversion du H2O2 en eau et oxygène.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La β-oxydation peroxysomale :`,
    choices: [
      `Concerne des acides gras à chaînes longues ou très longues.`,
      `Raccourcit ces acides gras.`,
      `Produit de l’acétyl-CoA.`,
      `Concerne exclusivement les acides gras à chaîne très courte.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le peroxysome raccourcit les chaînes longues ou très longues et produit notamment de l’acétyl-CoA.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les fonctions métaboliques peroxysomales citées :`,
    choices: [
      `La synthèse d’acides biliaires.`,
      `La dégradation d’acides aminés.`,
      `La β-oxydation d’acides gras longs ou très longs.`,
      `La réplication du génome peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois premières voies font intervenir des oxydases ; le peroxysome ne possède pas de génome à répliquer.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La dégradation peroxysomale d’acides aminés implique :`,
    choices: [
      `Des aminoacides oxydases.`,
      `Une réaction oxydative.`,
      `Une production possible de H2O2.`,
      `Une urate oxydase humaine obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les aminoacides oxydases font partie des voies produisant du H2O2 ; l’Homme ne possède pas d’urate oxydase selon la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Après la β-oxydation peroxysomale, les produits :`,
    choices: [
      `Peuvent sortir par des perméases.`,
      `Rejoignent le cytosol.`,
      `Peuvent ensuite rejoindre les mitochondries.`,
      `Restent tous définitivement dans le peroxysome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les acides gras raccourcis et l’acétyl-CoA sortent du peroxysome puis rejoignent les mitochondries.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’acétyl-CoA produit par le peroxysome :`,
    choices: [
      `Peut rejoindre la mitochondrie.`,
      `Peut contribuer ensuite à la production d’énergie.`,
      `Est produit lors de la β-oxydation.`,
      `Est directement transformé en ADN peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’acétyl-CoA est transféré vers la mitochondrie pour participer au métabolisme énergétique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Dans le foie, la catalase intervient dans :`,
    choices: [
      `Le catabolisme d’une fraction de l’alcool consommé.`,
      `Un ordre de grandeur de 25 à 50 % de la consommation d’alcool selon la fiche.`,
      `La dégradation de l’acétaldéhyde.`,
      `La synthèse de l’éthanol à partir d’acétyl-CoA.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche attribue à la catalase une part importante du catabolisme hépatique de l’alcool et de l’acétaldéhyde.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Au cours du catabolisme de l’alcool présenté :`,
    choices: [
      `L’éthanol est transformé en acétaldéhyde.`,
      `L’acétaldéhyde est dangereux.`,
      `La catalase contribue à sa destruction.`,
      `L’acétaldéhyde est une enzyme peroxysomale protectrice.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’acétaldéhyde est un intermédiaire toxique, non une enzyme protectrice.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les effets dangereux attribués à l’acétaldéhyde dans la fiche comprennent :`,
    choices: [
      `Des atteintes du cytosquelette.`,
      `Un blocage du transport axonal.`,
      `Une atteinte possible du système nerveux.`,
      `Une stimulation directe de l’urate oxydase humaine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche relie l’acétaldéhyde à des atteintes cytosquelettiques et à un blocage du transport axonal.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le rôle détoxifiant de la catalase repose sur :`,
    choices: [
      `L’utilisation du H2O2.`,
      `L’oxydation de certains substrats toxiques.`,
      `La destruction de l’excès de H2O2.`,
      `La production systématique d’un surplus de H2O2.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La catalase protège la cellule en utilisant ou en éliminant le H2O2, sans en être la principale source.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un excès de H2O2 dans la matrice devrait être limité par :`,
    choices: [
      `La catalase.`,
      `Sa conversion en H2O et O2.`,
      `La forte abondance de l’enzyme catalase.`,
      `L’urate oxydase humaine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La catalase décompose le H2O2 ; l’Homme ne dispose pas d’urate oxydase selon la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À partir de la figure suivante :

![Oxydases et catalase](/images/training/ue14/biologie-cellulaire/peroxysomes/oxydases-catalase-h2o2.png)

Quelle(s) relation(s) est(sont) correcte(s) ?`,
    choices: [
      `O2 + substrat réduit — oxydase → substrat oxydé + H2O2.`,
      `H2O2 + substrat — catalase → produit oxydé.`,
      `Excès de H2O2 — catalase → H2O + O2.`,
      `Catalase — réaction principale → production initiale de H2O2.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le schéma distingue la production initiale du H2O2 par l’oxydase et ses utilisations par la catalase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Associe correctement fonction et enzyme :`,
    choices: [
      `Production de H2O2 — oxydase.`,
      `Destruction de l’excès de H2O2 — catalase.`,
      `Dégradation d’acides aminés — aminoacides oxydases.`,
      `Formation d’ADN — catalase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les oxydases et la catalase assurent des fonctions métaboliques et détoxifiantes, non la synthèse d’ADN.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le fait que la matrice utilise l’oxygène est cohérent avec :`,
    choices: [
      `La présence d’oxydases.`,
      `La production de H2O2.`,
      `La production d’O2 lors de la décomposition du H2O2.`,
      `L’absence complète de réactions d’oxydoréduction.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le peroxysome est un organite d’oxydations utilisant l’oxygène et manipulant le H2O2.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les trois voies oxydatives citées avec production de H2O2 comprennent :`,
    choices: [
      `La β-oxydation des acides gras longs ou très longs.`,
      `La synthèse d’acides biliaires.`,
      `La dégradation d’acides aminés.`,
      `La réplication de l’ADN nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche regroupe ces trois voies métaboliques parmi les activités des oxydases peroxysomales.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `L’affirmation « la catalase produit le H2O2 » est :`,
    choices: [
      `Fausse dans le schéma général du cours.`,
      `À corriger en indiquant que les oxydases produisent le H2O2.`,
      `À nuancer car la catalase utilise le H2O2.`,
      `Exacte pour toutes les réactions peroxysomales.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La catalase consomme ou décompose le H2O2 produit par les oxydases.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La coopération entre oxydases et catalase permet :`,
    choices: [
      `D’oxyder des substrats.`,
      `D’exploiter le H2O2 produit.`,
      `De limiter l’accumulation de H2O2.`,
      `De rendre inutile toute perméase membranaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cette coopération concerne les réactions de matrice ; les perméases restent nécessaires aux échanges de produits.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une oxydase est active mais la catalase est fortement déficiente. On peut prévoir, à partir du cours :`,
    choices: [
      `Une production maintenue de H2O2.`,
      `Une dégradation moins efficace de l’excès de H2O2.`,
      `Une perturbation de certaines fonctions détoxifiantes.`,
      `Une disparition immédiate de toutes les oxydases.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La catalase agit en aval des oxydases ; son déficit affecte l’utilisation et la destruction du H2O2.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le catabolisme peroxysomal de l’alcool illustre :`,
    choices: [
      `Une fonction de détoxification.`,
      `L’utilisation du H2O2 par la catalase.`,
      `La destruction d’un intermédiaire dangereux.`,
      `La production d’acide urique par la catalase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Cet exemple relie catalase, H2O2 et élimination de l’acétaldéhyde toxique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un blocage du transport axonal après exposition à l’acétaldéhyde est cohérent avec :`,
    choices: [
      `L’atteinte du cytosquelette décrite.`,
      `La toxicité de l’acétaldéhyde.`,
      `L’intérêt de sa destruction par la catalase.`,
      `Une protection assurée par l’acétaldéhyde lui-même.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche présente l’acétaldéhyde comme toxique et justifie son élimination par la catalase.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les produits de la β-oxydation peroxysomale doivent franchir la membrane grâce notamment à :`,
    choices: [
      `Des perméases.`,
      `Des protéines membranaires de transport.`,
      `Un passage vers le cytosol.`,
      `Une fusion obligatoire avec le noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les produits sortent via des perméases puis rejoignent le cytosol et les mitochondries.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le peroxysome associe fonctions lipidiques et autres métabolismes car il intervient dans :`,
    choices: [
      `La β-oxydation.`,
      `La synthèse d’acides biliaires.`,
      `La dégradation d’acides aminés.`,
      `La formation des chromosomes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La diversité enzymatique peroxysomale dépasse le seul métabolisme lipidique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La présence d’oxygène dans les réactions peroxysomales est directement reliée à :`,
    choices: [
      `L’activité des oxydases.`,
      `La formation de H2O2.`,
      `La détoxification par la catalase.`,
      `La duplication du génome peroxysomal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le peroxysome est un compartiment d’oxydations et de gestion du H2O2, sans génome propre.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte sur les fonctions enzymatiques du peroxysome ?`,
    choices: [
      `Les oxydases produisent du H2O2.`,
      `La catalase utilise ou détruit le H2O2.`,
      `Plusieurs voies métaboliques sont concernées.`,
      `La catalase est absente de la matrice.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Oxydases et catalase structurent le fonctionnement métabolique et détoxifiant du peroxysome.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue au peroxysome une propriété non décrite.`,
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: `oxydases-catalase-h2o2`,
    title: `Oxydases, catalase et peroxyde d’hydrogène`,
    description: `Production, utilisation et détoxification du H2O2.`,
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: `voies-metaboliques-peroxysomales`,
    title: `Voies métaboliques peroxysomales`,
    description: `β-oxydation, acides biliaires, acides aminés et détoxification de l’alcool.`,
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 9,
    slug: `integration-fonctions-oxydatives`,
    title: `Intégration des fonctions oxydatives`,
    description: `Raisonnement sur les enzymes, les produits et les échanges de métabolites.`,
    stage: 'MASTER',
    sectionOrder: 3,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];
