/** UE14 – Biologie cellulaire – Chapitre 6 — V2 active */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';
const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'peroxysomes';
const sections: SeedSection[] = [
  { order: 1, title: `Identité, biogenèse et adressage`, description: `Organisation générale, dynamique, protéines PEX et signaux PTS.`, kind: 'THEME' },
  { order: 2, title: `Oxydases, catalase et H₂O₂`, description: `Réactions oxydatives et contrôle du peroxyde d’hydrogène.`, kind: 'THEME' },
  { order: 3, title: `Métabolismes peroxysomaux`, description: `β-oxydation, lipides, acides biliaires et coopérations.`, kind: 'THEME' },
  { order: 4, title: `Pathologies et intégration`, description: `Déficits peroxysomaux, X-ALD, Zellweger et raisonnement transversal.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Révision transversale des peroxysomes.`, kind: 'SYNTHESIS' },
];
const questions: SeedQuestion[] = [...SECTION_A_QUESTIONS, ...SECTION_B_QUESTIONS, ...SECTION_C_QUESTIONS, ...SECTION_D_QUESTIONS, ...SYNTHESIS_QUESTIONS];
const quizSeeds: SeedQuiz[] = [...SECTION_A_QUIZZES, ...SECTION_B_QUIZZES, ...SECTION_C_QUIZZES, ...SECTION_D_QUIZZES, ...SYNTHESIS_QUIZZES];
const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Identité, biogenèse et adressage`],
  2: [`Identité, biogenèse et adressage`],
  3: [`Identité, biogenèse et adressage`],
  4: [`Identité, biogenèse et adressage`],
  5: [`Identité, biogenèse et adressage`],
  6: [`Identité, biogenèse et adressage`],
  7: [`Identité, biogenèse et adressage`],
  8: [`Identité, biogenèse et adressage`],
  9: [`Identité, biogenèse et adressage`],
  10: [`Identité, biogenèse et adressage`],
  11: [`Identité, biogenèse et adressage`],
  12: [`Identité, biogenèse et adressage`],
  13: [`Identité, biogenèse et adressage`],
  14: [`Identité, biogenèse et adressage`],
  15: [`Identité, biogenèse et adressage`],
  16: [`Identité, biogenèse et adressage`],
  17: [`Identité, biogenèse et adressage`],
  18: [`Identité, biogenèse et adressage`],
  19: [`Identité, biogenèse et adressage`],
  20: [`Identité, biogenèse et adressage`],
  21: [`Identité, biogenèse et adressage`],
  22: [`Identité, biogenèse et adressage`],
  23: [`Oxydases, catalase et H₂O₂`],
  24: [`Oxydases, catalase et H₂O₂`],
  25: [`Oxydases, catalase et H₂O₂`],
  26: [`Oxydases, catalase et H₂O₂`],
  27: [`Oxydases, catalase et H₂O₂`],
  28: [`Oxydases, catalase et H₂O₂`],
  29: [`Oxydases, catalase et H₂O₂`],
  30: [`Oxydases, catalase et H₂O₂`],
  31: [`Oxydases, catalase et H₂O₂`],
  32: [`Oxydases, catalase et H₂O₂`],
  33: [`Oxydases, catalase et H₂O₂`],
  34: [`Oxydases, catalase et H₂O₂`],
  35: [`Oxydases, catalase et H₂O₂`],
  36: [`Oxydases, catalase et H₂O₂`],
  37: [`Oxydases, catalase et H₂O₂`],
  38: [`Oxydases, catalase et H₂O₂`],
  39: [`Oxydases, catalase et H₂O₂`],
  40: [`Oxydases, catalase et H₂O₂`],
  41: [`Oxydases, catalase et H₂O₂`],
  42: [`Oxydases, catalase et H₂O₂`],
  43: [`Oxydases, catalase et H₂O₂`],
  44: [`Oxydases, catalase et H₂O₂`],
  45: [`Métabolismes peroxysomaux`],
  46: [`Métabolismes peroxysomaux`],
  47: [`Métabolismes peroxysomaux`],
  48: [`Métabolismes peroxysomaux`],
  49: [`Métabolismes peroxysomaux`],
  50: [`Métabolismes peroxysomaux`],
  51: [`Métabolismes peroxysomaux`],
  52: [`Métabolismes peroxysomaux`],
  53: [`Métabolismes peroxysomaux`],
  54: [`Métabolismes peroxysomaux`],
  55: [`Métabolismes peroxysomaux`],
  56: [`Métabolismes peroxysomaux`],
  57: [`Métabolismes peroxysomaux`],
  58: [`Métabolismes peroxysomaux`],
  59: [`Métabolismes peroxysomaux`],
  60: [`Métabolismes peroxysomaux`],
  61: [`Métabolismes peroxysomaux`],
  62: [`Métabolismes peroxysomaux`],
  63: [`Métabolismes peroxysomaux`],
  64: [`Métabolismes peroxysomaux`],
  65: [`Métabolismes peroxysomaux`],
  66: [`Métabolismes peroxysomaux`],
  67: [`Pathologies et intégration`],
  68: [`Pathologies et intégration`],
  69: [`Pathologies et intégration`],
  70: [`Pathologies et intégration`],
  71: [`Pathologies et intégration`],
  72: [`Pathologies et intégration`],
  73: [`Pathologies et intégration`],
  74: [`Pathologies et intégration`],
  75: [`Pathologies et intégration`],
  76: [`Pathologies et intégration`],
  77: [`Pathologies et intégration`],
  78: [`Pathologies et intégration`],
  79: [`Pathologies et intégration`],
  80: [`Pathologies et intégration`],
  81: [`Pathologies et intégration`],
  82: [`Pathologies et intégration`],
  83: [`Pathologies et intégration`],
  84: [`Pathologies et intégration`],
  85: [`Pathologies et intégration`],
  86: [`Pathologies et intégration`],
  87: [`Pathologies et intégration`],
  88: [`Pathologies et intégration`],
  89: [`Pathologies et intégration`],
  90: [`Pathologies et intégration`],
  91: [`Pathologies et intégration`],
  92: [`Pathologies et intégration`],
  93: [`Pathologies et intégration`],
  94: [`Pathologies et intégration`],
  95: [`Pathologies et intégration`],
  96: [`Pathologies et intégration`],
  97: [`Pathologies et intégration`],
  98: [`Pathologies et intégration`],
  99: [`Pathologies et intégration`],
  100: [`Pathologies et intégration`],
  101: [`Synthèse des peroxysomes`],
  102: [`Synthèse des peroxysomes`],
  103: [`Synthèse des peroxysomes`],
  104: [`Synthèse des peroxysomes`],
  105: [`Synthèse des peroxysomes`],
  106: [`Synthèse des peroxysomes`],
  107: [`Synthèse des peroxysomes`],
  108: [`Synthèse des peroxysomes`],
  109: [`Synthèse des peroxysomes`],
  110: [`Synthèse des peroxysomes`],
  111: [`Synthèse des peroxysomes`],
  112: [`Synthèse des peroxysomes`],
  113: [`Synthèse des peroxysomes`],
  114: [`Synthèse des peroxysomes`],
  115: [`Synthèse des peroxysomes`],
  116: [`Synthèse des peroxysomes`],
  117: [`Synthèse des peroxysomes`],
  118: [`Synthèse des peroxysomes`],
  119: [`Synthèse des peroxysomes`],
  120: [`Synthèse des peroxysomes`],
  121: [`Synthèse des peroxysomes`],
  122: [`Synthèse des peroxysomes`],
};
export async function seedHealthTrainingUe14BiologieCellulairePeroxysomes(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 6',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
    purgeObsoleteQuestions: true,
  });
}
