/** UE14 – Biologie cellulaire – Chapitre 9 : Le cycle cellulaire */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-cycle-cellulaire.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';

const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'cycle-cellulaire';

const sections: SeedSection[] = [
  { order: 1, title: `Renouvellement et déroulement du cycle`, description: `Tissus sains ou tumoraux, G0, G1, S, G2, mitose et quantité d’ADN.`, kind: 'THEME' },
  { order: 2, title: `Cyclines et CDK`, description: `Succession des complexes cycline-CDK et transitions du cycle.`, kind: 'THEME' },
  { order: 3, title: `Points de contrôle`, description: `Contrôles G1, G2 et métaphasique, protéines activatrices et inhibitrices.`, kind: 'THEME' },
  { order: 4, title: `Mitose et cytodiérèse`, description: `Phases de mitose, fuseau, APC/C, séparase, cohésines et sortie de mitose.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Consolidation transversale et raisonnement expérimental.`, kind: 'SYNTHESIS' },
];

const questions: SeedQuestion[] = [
  ...SECTION_A_QUESTIONS, ...SECTION_B_QUESTIONS, ...SECTION_C_QUESTIONS, ...SECTION_D_QUESTIONS, ...SYNTHESIS_QUESTIONS,
];
const quizSeeds: SeedQuiz[] = [
  ...SECTION_A_QUIZZES, ...SECTION_B_QUIZZES, ...SECTION_C_QUIZZES, ...SECTION_D_QUIZZES, ...SYNTHESIS_QUIZZES,
];

const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Renouvellement et phases du cycle`],
  2: [`Renouvellement et phases du cycle`],
  3: [`Renouvellement et phases du cycle`],
  4: [`Renouvellement et phases du cycle`],
  5: [`Renouvellement et phases du cycle`],
  6: [`Renouvellement et phases du cycle`],
  7: [`Renouvellement et phases du cycle`],
  8: [`Renouvellement et phases du cycle`],
  9: [`Renouvellement et phases du cycle`],
  10: [`Renouvellement et phases du cycle`],
  11: [`Renouvellement et phases du cycle`],
  12: [`Renouvellement et phases du cycle`],
  13: [`Renouvellement et phases du cycle`],
  14: [`Renouvellement et phases du cycle`],
  15: [`Renouvellement et phases du cycle`],
  16: [`Renouvellement et phases du cycle`],
  17: [`Renouvellement et phases du cycle`],
  18: [`Renouvellement et phases du cycle`],
  19: [`Renouvellement et phases du cycle`],
  20: [`Renouvellement et phases du cycle`],
  21: [`Renouvellement et phases du cycle`],
  22: [`Renouvellement et phases du cycle`],
  23: [`Renouvellement et phases du cycle`],
  24: [`Renouvellement et phases du cycle`],
  25: [`Renouvellement et phases du cycle`],
  26: [`Renouvellement et phases du cycle`],
  27: [`Renouvellement et phases du cycle`],
  28: [`Renouvellement et phases du cycle`],
  29: [`Renouvellement et phases du cycle`],
  30: [`Renouvellement et phases du cycle`],
  31: [`Cyclines et CDK`],
  32: [`Cyclines et CDK`],
  33: [`Cyclines et CDK`],
  34: [`Cyclines et CDK`],
  35: [`Cyclines et CDK`],
  36: [`Cyclines et CDK`],
  37: [`Cyclines et CDK`],
  38: [`Cyclines et CDK`],
  39: [`Cyclines et CDK`],
  40: [`Cyclines et CDK`],
  41: [`Cyclines et CDK`],
  42: [`Cyclines et CDK`],
  43: [`Cyclines et CDK`],
  44: [`Cyclines et CDK`],
  45: [`Cyclines et CDK`],
  46: [`Cyclines et CDK`],
  47: [`Cyclines et CDK`],
  48: [`Cyclines et CDK`],
  49: [`Cyclines et CDK`],
  50: [`Cyclines et CDK`],
  51: [`Cyclines et CDK`],
  52: [`Cyclines et CDK`],
  53: [`Cyclines et CDK`],
  54: [`Cyclines et CDK`],
  55: [`Cyclines et CDK`],
  56: [`Cyclines et CDK`],
  57: [`Cyclines et CDK`],
  58: [`Cyclines et CDK`],
  59: [`Cyclines et CDK`],
  60: [`Cyclines et CDK`],
  61: [`Points de contrôle`],
  62: [`Points de contrôle`],
  63: [`Points de contrôle`],
  64: [`Points de contrôle`],
  65: [`Points de contrôle`],
  66: [`Points de contrôle`],
  67: [`Points de contrôle`],
  68: [`Points de contrôle`],
  69: [`Points de contrôle`],
  70: [`Points de contrôle`],
  71: [`Points de contrôle`],
  72: [`Points de contrôle`],
  73: [`Points de contrôle`],
  74: [`Points de contrôle`],
  75: [`Points de contrôle`],
  76: [`Points de contrôle`],
  77: [`Points de contrôle`],
  78: [`Points de contrôle`],
  79: [`Points de contrôle`],
  80: [`Points de contrôle`],
  81: [`Points de contrôle`],
  82: [`Points de contrôle`],
  83: [`Points de contrôle`],
  84: [`Points de contrôle`],
  85: [`Points de contrôle`],
  86: [`Points de contrôle`],
  87: [`Points de contrôle`],
  88: [`Points de contrôle`],
  89: [`Points de contrôle`],
  90: [`Points de contrôle`],
  91: [`Mitose et fuseau`],
  92: [`Mitose et fuseau`],
  93: [`Mitose et fuseau`],
  94: [`Mitose et fuseau`],
  95: [`Mitose et fuseau`],
  96: [`Mitose et fuseau`],
  97: [`Mitose et fuseau`],
  98: [`Mitose et fuseau`],
  99: [`Mitose et fuseau`],
  100: [`Mitose et fuseau`],
  101: [`Mitose et fuseau`],
  102: [`Mitose et fuseau`],
  103: [`Mitose et fuseau`],
  104: [`Mitose et fuseau`],
  105: [`Mitose et fuseau`],
  106: [`Mitose et fuseau`],
  107: [`Mitose et fuseau`],
  108: [`Mitose et fuseau`],
  109: [`Mitose et fuseau`],
  110: [`Mitose et fuseau`],
  111: [`Mitose et fuseau`],
  112: [`Mitose et fuseau`],
  113: [`Mitose et fuseau`],
  114: [`Mitose et fuseau`],
  115: [`Mitose et fuseau`],
  116: [`Mitose et fuseau`],
  117: [`Mitose et fuseau`],
  118: [`Mitose et fuseau`],
  119: [`Mitose et fuseau`],
  120: [`Mitose et fuseau`],
  121: [`Synthèse du cycle cellulaire`],
  122: [`Synthèse du cycle cellulaire`],
  123: [`Synthèse du cycle cellulaire`],
  124: [`Synthèse du cycle cellulaire`],
  125: [`Synthèse du cycle cellulaire`],
  126: [`Synthèse du cycle cellulaire`],
  127: [`Synthèse du cycle cellulaire`],
  128: [`Synthèse du cycle cellulaire`],
  129: [`Synthèse du cycle cellulaire`],
  130: [`Synthèse du cycle cellulaire`],
  131: [`Synthèse du cycle cellulaire`],
  132: [`Synthèse du cycle cellulaire`],
  133: [`Synthèse du cycle cellulaire`],
  134: [`Synthèse du cycle cellulaire`],
  135: [`Synthèse du cycle cellulaire`],
  136: [`Synthèse du cycle cellulaire`],
  137: [`Synthèse du cycle cellulaire`],
  138: [`Synthèse du cycle cellulaire`],
  139: [`Synthèse du cycle cellulaire`],
  140: [`Synthèse du cycle cellulaire`],
 };

export async function seedHealthTrainingUe14BiologieCellulaireCycleCellulaire(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 9',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
  });
}
