/** Cartographie éditoriale V2 — auteur */

export const UE14_CELL_CH1_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-generalites-cellule",
    "title": "Repères sur l’organisation cellulaire",
    "description": "Définition, composition chimique, grandes structures et fonctions de la cellule.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-composition-fonctions-cellule",
    "title": "Organisation, composition et fonctions cellulaires",
    "description": "Applications sur les repères quantitatifs et la spécialisation cellulaire.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-culture-cellulaire-principes",
    "title": "Principes de culture cellulaire",
    "description": "Conditions de culture, observation, PSM, cryothèque et culture primaire.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-passages-lignees-cellulaires",
    "title": "Cultures primaires, passages et lignées",
    "description": "Confluence, passages successifs, cultures normales et lignées immortelles.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-explants-modeles",
    "title": "Explants et cellules dissociées",
    "description": "Explant, cellules dissociées et intérêt de ces modèles.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-modeles-2d-3d-air-liquide",
    "title": "Modèles 2D, 3D et interface air-liquide",
    "description": "Comparer monocouche 2D, modèles 3D et interface air-liquide.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-marquages-moleculaires",
    "title": "Méthodes de marquage moléculaire",
    "description": "Repères sur les quatre stratégies de localisation moléculaire.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-immunomarquage-gfp-hybridation",
    "title": "Choisir et interpréter un marquage moléculaire",
    "description": "Applications sur anticorps, sondes, GFP, transfection, électroporation et micro-injection.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-methodes-localisation",
    "title": "Maîtriser les méthodes de localisation moléculaire",
    "description": "Choisir une stratégie de marquage adaptée à une question expérimentale.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-organisation-methodes",
    "title": "Synthèse : organisation et méthodes d’étude",
    "description": "Synthèse transversale du chapitre.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-organisation-methodes-etude-cellule",
    "title": "Synthèse : organisation et méthodes d’étude",
    "description": "Maîtrise du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_CELL_CH1_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["la définition de la cellule"],
  2: ["les principaux éléments chimiques cellulaires"],
  3: ["la proportion d’eau dans la cellule selon la fiche"],
  4: ["les proportions de macromolécules indiquées dans la fiche"],
  5: ["les grandes structures cellulaires"],
  6: ["les fonctions générales de la cellule"],
  7: ["les étapes de la vie cellulaire citées"],
  8: ["l’hématie et l’entérocyte comme exemples de spécialisation"],
  9: ["la définition de la cellule"],
  10: ["les principaux éléments chimiques cellulaires"],
  11: ["la proportion d’eau dans la cellule selon la fiche"],
  12: ["les proportions de macromolécules indiquées dans la fiche"],
  13: ["les grandes structures cellulaires"],
  14: ["les fonctions générales de la cellule"],
  15: ["les étapes de la vie cellulaire citées"],
  16: ["les principaux éléments chimiques cellulaires"],
  17: ["la définition de la cellule"],
  18: ["les principaux éléments chimiques cellulaires"],
  19: ["la définition de la cellule", "les principaux éléments chimiques cellulaires", "la proportion d’eau dans la cellule selon la fiche"],
  20: ["les proportions de macromolécules indiquées dans la fiche"],
  21: ["les grandes structures cellulaires"],
  22: ["les proportions de macromolécules indiquées dans la fiche", "les grandes structures cellulaires", "les fonctions générales de la cellule", "les étapes de la vie cellulaire citées", "l’hématie et l’entérocyte comme exemples de spécialisation"],
  23: ["la définition de la culture cellulaire"],
  24: ["les conditions d’incubation de la fiche"],
  25: ["l’observation et la manipulation des cultures"],
  26: ["la cryoconservation"],
  27: ["la culture primaire"],
  28: ["la confluence et le passage cellulaire"],
  29: ["la durée de vie des cultures normales"],
  30: ["les lignées cellulaires tumorales ou transformées"],
  31: ["la définition de la culture cellulaire"],
  32: ["les conditions d’incubation de la fiche"],
  33: ["l’observation et la manipulation des cultures"],
  34: ["la cryoconservation"],
  35: ["la culture primaire"],
  36: ["la confluence et le passage cellulaire"],
  37: ["la durée de vie des cultures normales"],
  38: ["la confluence et le passage cellulaire"],
  39: ["la définition de la culture cellulaire"],
  40: ["les conditions d’incubation de la fiche"],
  41: ["la définition de la culture cellulaire", "les conditions d’incubation de la fiche", "l’observation et la manipulation des cultures"],
  42: ["la cryoconservation"],
  43: ["la culture primaire"],
  44: ["la cryoconservation", "la culture primaire", "la confluence et le passage cellulaire", "la durée de vie des cultures normales", "les lignées cellulaires tumorales ou transformées"],
  45: ["les explants"],
  46: ["l’intérêt clinique des explants cité dans la fiche"],
  47: ["les cellules dissociées en 2D"],
  48: ["les modèles cellulaires 3D"],
  49: ["la culture en interface air-liquide"],
  50: ["l’intérêt des modèles de culture pour étudier la vie cellulaire"],
  51: ["la différence entre modèle in vitro et situation in vivo"],
  52: ["les explants"],
  53: ["l’intérêt clinique des explants cité dans la fiche"],
  54: ["les cellules dissociées en 2D"],
  55: ["les cellules dissociées en 2D"],
  56: ["les modèles cellulaires 3D"],
  57: ["la culture en interface air-liquide"],
  58: ["l’intérêt des modèles de culture pour étudier la vie cellulaire"],
  59: ["la différence entre modèle in vitro et situation in vivo"],
  60: ["les explants"],
  61: ["l’intérêt clinique des explants cité dans la fiche"],
  62: ["les cellules dissociées en 2D"],
  63: ["l’intérêt clinique des explants cité dans la fiche", "les cellules dissociées en 2D", "les modèles cellulaires 3D"],
  64: ["la culture en interface air-liquide"],
  65: ["l’intérêt des modèles de culture pour étudier la vie cellulaire"],
  66: ["la culture en interface air-liquide", "l’intérêt des modèles de culture pour étudier la vie cellulaire", "la différence entre modèle in vitro et situation in vivo", "les explants", "l’intérêt clinique des explants cité dans la fiche"],
  67: ["les quatre grandes méthodes de marquage moléculaire de la fiche"],
  68: ["l’immunomarquage"],
  69: ["le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence"],
  70: ["l’hybridation in situ"],
  71: ["les protéines autofluorescentes"],
  72: ["la transfection selon la fiche"],
  73: ["l’électroporation"],
  74: ["la micro-injection de protéines marquées"],
  75: ["la compatibilité des méthodes avec cellules vivantes ou fixées"],
  76: ["le choix d’une méthode de localisation moléculaire"],
  77: ["le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence"],
  78: ["l’hybridation in situ"],
  79: ["les protéines autofluorescentes"],
  80: ["la transfection selon la fiche"],
  81: ["l’électroporation"],
  82: ["le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence"],
  83: ["la compatibilité des méthodes avec cellules vivantes ou fixées"],
  84: ["le choix d’une méthode de localisation moléculaire"],
  85: ["la compatibilité des méthodes avec cellules vivantes ou fixées", "le choix d’une méthode de localisation moléculaire", "les quatre grandes méthodes de marquage moléculaire de la fiche"],
  86: ["l’immunomarquage"],
  87: ["le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence"],
  88: ["l’immunomarquage", "le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence", "l’hybridation in situ", "les protéines autofluorescentes", "la transfection selon la fiche"],
  89: ["l’immunomarquage"],
  90: ["l’immunomarquage", "les protéines autofluorescentes"],
  91: ["le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence", "la transfection selon la fiche"],
  92: ["l’hybridation in situ", "l’électroporation"],
  93: ["les protéines autofluorescentes", "la micro-injection de protéines marquées"],
  94: ["la transfection selon la fiche", "la compatibilité des méthodes avec cellules vivantes ou fixées"],
  95: ["l’électroporation", "le choix d’une méthode de localisation moléculaire"],
  96: ["la micro-injection de protéines marquées", "les quatre grandes méthodes de marquage moléculaire de la fiche"],
  97: ["la compatibilité des méthodes avec cellules vivantes ou fixées", "l’immunomarquage"],
  98: ["le choix d’une méthode de localisation moléculaire", "les quatre grandes méthodes de marquage moléculaire de la fiche", "l’immunomarquage"],
  99: ["les quatre grandes méthodes de marquage moléculaire de la fiche", "l’hybridation in situ"],
  100: ["l’immunomarquage", "le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence", "l’hybridation in situ", "les protéines autofluorescentes", "la transfection selon la fiche"],
  101: ["la définition de la cellule", "les conditions d’incubation de la fiche"],
  102: ["les fonctions générales de la cellule", "la durée de vie des cultures normales"],
  103: ["l’observation et la manipulation des cultures", "les modèles cellulaires 3D"],
  104: ["les lignées cellulaires tumorales ou transformées", "l’immunomarquage"],
  105: ["la culture en interface air-liquide", "l’électroporation"],
  106: ["le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence", "les principaux éléments chimiques cellulaires"],
  107: ["la micro-injection de protéines marquées", "les étapes de la vie cellulaire citées"],
  108: ["la proportion d’eau dans la cellule selon la fiche", "la cryoconservation"],
  109: ["l’immunomarquage", "le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence", "l’hybridation in situ"],
  110: ["les protéines autofluorescentes", "la transfection selon la fiche", "l’électroporation", "la micro-injection de protéines marquées", "la compatibilité des méthodes avec cellules vivantes ou fixées"],
  111: ["les principaux éléments chimiques cellulaires", "les fonctions générales de la cellule", "la culture primaire"],
  112: ["la définition de la culture cellulaire", "les explants", "le fluorochrome Alexa 488 dans l’exemple d’immunofluorescence"],
  113: ["les lignées cellulaires tumorales ou transformées", "les protéines autofluorescentes", "les fonctions générales de la cellule"],
  114: ["la différence entre modèle in vitro et situation in vivo", "les fonctions générales de la cellule", "les cellules dissociées en 2D"],
  115: ["l’électroporation", "les explants", "la compatibilité des méthodes avec cellules vivantes ou fixées"],
  116: ["les proportions de macromolécules indiquées dans la fiche", "les protéines autofluorescentes", "la cryoconservation"],
  117: ["les conditions d’incubation de la fiche"],
  118: ["l’intérêt clinique des explants cité dans la fiche", "les explants", "les grandes structures cellulaires"],
  119: ["l’immunomarquage", "les protéines autofluorescentes", "l’intérêt clinique des explants cité dans la fiche"],
  120: ["la compatibilité des méthodes avec cellules vivantes ou fixées", "les fonctions générales de la cellule", "la micro-injection de protéines marquées"],
  121: ["les grandes structures cellulaires", "les fonctions générales de la cellule", "les étapes de la vie cellulaire citées"],
  122: ["la cryoconservation", "la culture primaire", "la confluence et le passage cellulaire", "la durée de vie des cultures normales", "les lignées cellulaires tumorales ou transformées"],
};
