import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_ORDER = 1;

export const SECTION_A_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Glycéraldéhyde et de la dihydroxyacétone"],
  2: ["Le glucose"],
  3: ["La fiche, quelle proportion approximative du glucose est repré…"],
  4: ["Les rôles ou caractéristiques biologiques du glucose"],
  5: ["Le galactose"],
  6: ["Galactose est un épimère du glucose en position"],
  7: ["Mannose est un épimère du glucose en position"],
  8: ["Mannose"],
  9: ["Le fructose"],
  10: ["Ribose et du 2-désoxyribose"],
  11: ["Les oses simples présentent généralement"],
  12: ["Bonne hydrosolubilité des oses simples s’explique principaleme…"],
  13: ["Sur le plan physique, les oses simples sont décrits comme"],
  14: ["Les propriétés chimiques des oses simples citées dans le cours"],
  15: ["Pouvoir réducteur d’un aldose est relié dans la fiche à"],
  16: ["Réaction positive avec la liqueur de Fehling conduit classique…"],
  17: ["La réaction de Fehling appliquée à un aldose"],
  18: ["Comparer glucose et fructose permet d’affirmer que"],
  19: ["Comparer glucose, mannose et galactose permet de conclure que"],
  20: ["Les oses impliqués directement dans les acides nucléiques comp…"],
  21: ["À partir de la figure comparant les trioses"],
  22: ["À partir des projections de Fischer présentées"],
  23: ["Chez un patient, une glycémie durablement mal contrôlée"],
  24: ["Ose identifié comme « lévulose » dans un compte rendu ancien c…"],
  25: ["Forme furanique du fructose est cohérente avec les proposition…"],
  26: ["Forme pyranique du glucose"],
  27: ["Galactose peut être retrouvé"],
  28: ["Mannose et le galactose ont en commun"],
  29: ["Ose simple est très hydrosoluble et donne un test de Fehling p…"],
  30: ["Synthèse sur les principaux oses simples"],
};

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: "principaux-oses-simples",
    title: "Principaux oses simples",
    description: "Reconnaître le glucose, le galactose, le mannose, le fructose, le ribose et les trioses.",
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: "proprietes-oses-simples",
    title: "Propriétés des oses simples",
    description: "Relier fonctions hydroxyle, hydrosolubilité, thermodégradation et pouvoir réducteur.",
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: "comparaison-roles-oses",
    title: "Comparaison et rôles biologiques des oses",
    description: "Mobiliser les structures, épiméries et rôles biologiques dans des situations variées.",
    stage: 'MASTER',
    sectionOrder: 1,
    items: [
      {
        type: 'GROUP',
        title: "Lecture comparée de structures",
        sharedStatement: "Les questions suivantes s’appuient sur des représentations structurales des principaux oses.",
        questionOrders: [21, 22],
      },
      {
        type: 'GROUP',
        title: "Applications biologiques et cliniques",
        sharedStatement: "Les questions suivantes mobilisent les rôles biologiques et les contextes cliniques associés aux oses.",
        questionOrders: [23, 24, 25, 26, 27, 28],
      },
      {
        type: 'GROUP',
        title: "Raisonnement transversal",
        sharedStatement: "Les questions suivantes croisent propriétés physiques, chimiques et classification.",
        questionOrders: [29, 30],
      },
    ],
  },
];

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos du glycéraldéhyde et de la dihydroxyacétone :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glyceraldehyde-dihydroxyacetone-linear',
    },
    choices: [
      "Ce sont des oses à trois atomes de carbone.",
      "Le glycéraldéhyde est un aldose.",
      "La dihydroxyacétone est un cétose.",
      "Leurs formes phosphorylées sont étrangères à la glycolyse.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glycéraldéhyde et la dihydroxyacétone sont les trioses de référence ; leurs dérivés phosphorylés interviennent dans la glycolyse.",
    choiceExplanations: [
      "Vrai. Ce sont les oses les plus simples cités dans la fiche.",
      "Vrai. Il porte une fonction aldéhyde.",
      "Vrai. Il porte une fonction cétone.",
      "Faux. Leurs formes phosphorylées correspondent à une étape importante de la glycolyse.",
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant le glucose :",
    choices: [
      "Il est aussi appelé dextrose.",
      "Il appartient à la famille des aldoses.",
      "Il est l’ose le plus répandu dans la nature.",
      "Sa forme majoritaire est nécessairement furanique.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glucose, ou dextrose, est un aldose très répandu, majoritairement sous forme pyranique.",
    choiceExplanations: [
      "Vrai. Dextrose est un synonyme du glucose.",
      "Vrai. Sa forme linéaire porte une fonction aldéhyde.",
      "Vrai. C’est l’ose le plus répandu selon la fiche.",
      "Faux. Le glucose est très majoritairement pyranique.",
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Quelle proportion approximative du glucose est représentée sous forme pyranique ?\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-cyclization-anomers',
    },
    choices: [
      "1 %",
      "25 %",
      "50 %",
      "99 %",
    ],
    correctChoiceIndexes: [3],
    explanation: "La forme pyranique représente environ 99 % du glucose.",
    choiceExplanations: [
      "Cette valeur correspond plutôt à la fraction très minoritaire des formes non pyraniques.",
      "La forme pyranique est bien plus abondante.",
      "La répartition n’est pas équimolaire.",
      "C’est la valeur donnée dans le cours.",
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les rôles ou caractéristiques biologiques du glucose :",
    choices: [
      "Il constitue une source énergétique majeure.",
      "Il est présenté comme une source énergétique exclusive du fœtus.",
      "La glycémie correspond à sa concentration sanguine.",
      "Un défaut de contrôle de la glycémie est sans rapport avec le diabète.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le glucose est central sur le plan énergétique et sa concentration sanguine doit être régulée.",
    choiceExplanations: [
      "Vrai. Il est la source d’énergie par excellence.",
      "Vrai. Cette formulation figure dans la fiche.",
      "Vrai. C’est la définition de la glycémie.",
      "Faux. Une glycémie non contrôlée est au cœur du diabète.",
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant le galactose :",
    choices: [
      "Il entre dans la composition du lactose.",
      "Le lactose associe galactose et glucose.",
      "Son métabolisme est connecté à celui du glucose.",
      "Il est un cétose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le galactose est un aldose, composant du lactose, dont le métabolisme rejoint celui du glucose.",
    choiceExplanations: [
      "Vrai. Le lactose contient un résidu de galactose.",
      "Vrai. Il s’agit des deux oses du lactose.",
      "Vrai. Le cours insiste sur cette connexion métabolique.",
      "Faux. Le galactose est un aldose.",
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Le galactose est un épimère du glucose en position :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "C1",
      "C2",
      "C4",
      "C6",
    ],
    correctChoiceIndexes: [2],
    explanation: "Le galactose diffère du glucose par la configuration du carbone C4.",
    choiceExplanations: [
      "C1 correspond notamment au carbone anomérique dans la forme cyclique.",
      "Le mannose, et non le galactose, est l’épimère en C2.",
      "C’est la position à retenir.",
      "L’épimérie glucose–galactose ne porte pas sur C6.",
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Le mannose est un épimère du glucose en position :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "C1",
      "C2",
      "C4",
      "C5",
    ],
    correctChoiceIndexes: [1],
    explanation: "Le mannose et le glucose diffèrent par la configuration du carbone C2.",
    choiceExplanations: [
      "Ce n’est pas la position de leur différence.",
      "C’est la position à retenir.",
      "C4 distingue glucose et galactose.",
      "C5 détermine notamment la série D/L des aldohexoses.",
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos du mannose :",
    choices: [
      "C’est un aldose.",
      "Il est présent dans les végétaux.",
      "Il se retrouve en quantité importante dans des glycoprotéines.",
      "Il est l’épimère en C4 du glucose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le mannose est un aldose présent notamment dans les végétaux et les glycoprotéines ; il est épimère en C2 du glucose.",
    choiceExplanations: [
      "Vrai. Il appartient aux aldoses.",
      "Vrai. L’écorce d’orange est citée comme exemple.",
      "Vrai. La fiche le souligne.",
      "Faux. L’épimérie porte sur C2.",
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Concernant le fructose :",
    choices: [
      "Il est aussi appelé lévulose.",
      "Il appartient aux cétoses.",
      "Il est naturellement présent dans les fruits et le miel.",
      "Il est absent du saccharose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le fructose, ou lévulose, est un cétose naturel présent notamment dans les fruits, le miel et le saccharose.",
    choiceExplanations: [
      "Vrai. Lévulose est un nom traditionnel du fructose.",
      "Vrai. Sa forme linéaire porte une cétone.",
      "Vrai. Ce sont des sources alimentaires citées.",
      "Faux. Le saccharose associe glucose et fructose.",
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "À propos du ribose et du 2-désoxyribose :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-fructose-ribose-fischer',
    },
    choices: [
      "Le ribose entre dans la constitution de l’ARN.",
      "Le 2-désoxyribose entre dans la constitution de l’ADN.",
      "Le ribose est un pentose.",
      "Le 2-désoxyribose est le sucre principal de l’ARN.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le ribose est le pentose de l’ARN, tandis que le 2-désoxyribose est celui de l’ADN.",
    choiceExplanations: [
      "Vrai. ARN signifie acide ribonucléique.",
      "Vrai. ADN contient du 2-désoxyribose.",
      "Vrai. Il possède cinq carbones.",
      "Faux. Cette fonction revient au ribose.",
    ],
  },
  {
    order: 11,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les oses simples présentent généralement :",
    choices: [
      "De nombreuses fonctions hydroxyle.",
      "La capacité de former de multiples liaisons hydrogène.",
      "Une bonne hydrosolubilité.",
      "Une absence totale d’interactions avec l’eau.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les nombreux groupements OH favorisent les liaisons hydrogène et l’hydrosolubilité.",
    choiceExplanations: [
      "Vrai. Les oses sont polyhydroxylés.",
      "Vrai. Les OH sont donneurs et accepteurs de liaisons hydrogène.",
      "Vrai. Cela explique leur affinité pour l’eau.",
      "Faux. Leur interaction avec l’eau est au contraire importante.",
    ],
  },
  {
    order: 12,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "La bonne hydrosolubilité des oses simples s’explique principalement par :",
    choices: [
      "Leur richesse en fonctions alcool.",
      "Leur absence d’oxygène.",
      "Une longue chaîne hydrocarbonée apolaire.",
      "La présence systématique d’un ion métallique.",
    ],
    correctChoiceIndexes: [0],
    explanation: "Les fonctions alcool permettent de nombreuses interactions par liaison hydrogène avec l’eau.",
    choiceExplanations: [
      "C’est le mécanisme principal.",
      "Les oses contiennent plusieurs atomes d’oxygène.",
      "Ils ne sont pas dominés par une longue portion apolaire.",
      "Aucun ion métallique n’est requis.",
    ],
  },
  {
    order: 13,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Sur le plan physique, les oses simples sont décrits comme :",
    choices: [
      "Hydrosolubles.",
      "Thermodégradables.",
      "Susceptibles de caraméliser.",
      "Toujours insolubles dans l’eau froide.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les oses sont hydrosolubles et peuvent se dégrader sous l’effet de la chaleur, notamment par caramélisation.",
    choiceExplanations: [
      "Vrai. Les OH favorisent la solubilité.",
      "Vrai. Ils sont sensibles à la chaleur.",
      "Vrai. La caramélisation est l’exemple donné.",
      "Faux. Cette propriété est contraire à leur hydrosolubilité.",
    ],
  },
  {
    order: 14,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les propriétés chimiques des oses simples :",
    choices: [
      "Un goût souvent sucré.",
      "Un pouvoir réducteur pour les aldoses.",
      "Une réaction possible avec la liqueur de Fehling.",
      "L’impossibilité de subir une oxydation.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les aldoses sont des sucres réducteurs détectables notamment par la liqueur de Fehling.",
    choiceExplanations: [
      "Vrai. Le goût sucré est cité.",
      "Vrai. Leur fonction hémiacétalique peut s’ouvrir vers la forme aldéhydique.",
      "Vrai. Il s’agit d’un test classique des sucres réducteurs.",
      "Faux. Leur pouvoir réducteur implique précisément une oxydation de l’ose.",
    ],
  },
  {
    order: 15,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Le pouvoir réducteur d’un aldose est relié à :",
    choices: [
      "Sa fonction hémiacétalique.",
      "Une fonction amide.",
      "Une liaison peptidique.",
      "Un noyau stérane.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La fonction hémiacétalique permet l’équilibre avec une forme portant une fonction aldéhyde oxydable.",
    choiceExplanations: [
      "C’est la fonction concernée.",
      "Une fonction amide n’explique pas ce pouvoir.",
      "Une liaison peptidique concerne les peptides.",
      "Le noyau stérane appartient aux stéroïdes.",
    ],
  },
  {
    order: 16,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: "Une réaction positive avec la liqueur de Fehling conduit classiquement à :",
    choices: [
      "Un précipité rouge brique de Cu2O.",
      "Un dégagement de chlore.",
      "Un précipité noir de carbone.",
      "Une fluorescence bleue obligatoire.",
    ],
    correctChoiceIndexes: [0],
    explanation: "La réduction des ions cuivre conduit à l’oxyde cuivreux Cu2O, de couleur rouge brique.",
    choiceExplanations: [
      "C’est le résultat caractéristique.",
      "Le chlore n’intervient pas dans ce test.",
      "Aucun dépôt de carbone n’est attendu.",
      "Cette fluorescence ne caractérise pas la réaction de Fehling.",
    ],
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Dans la réaction de Fehling appliquée à un aldose :",
    choices: [
      "L’aldéhyde est oxydé en carboxylate.",
      "Les ions Cu2+ sont réduits.",
      "Du Cu2O est formé.",
      "L’ose est réduit en polyol.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le sucre réducteur s’oxyde tandis que le cuivre(II) est réduit en oxyde cuivreux.",
    choiceExplanations: [
      "Vrai. R–CHO devient un dérivé carboxylate.",
      "Vrai. Le cuivre gagne des électrons.",
      "Vrai. C’est le précipité rouge brique.",
      "Faux. La transformation de l’ose est une oxydation, non une réduction en polyol.",
    ],
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer glucose et fructose permet d’affirmer que :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-fructose-ribose-fischer',
    },
    choices: [
      "Ils comportent chacun six carbones.",
      "Le glucose est un aldose.",
      "Le fructose est un cétose.",
      "Ils sont nécessairement épimères.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Glucose et fructose sont deux hexoses de familles fonctionnelles différentes ; ce ne sont pas des épimères.",
    choiceExplanations: [
      "Vrai. Ce sont deux hexoses.",
      "Vrai. Le glucose porte un aldéhyde en forme linéaire.",
      "Vrai. Le fructose porte une cétone.",
      "Faux. L’épimérie suppose des stéréoisomères ne différant qu’en un centre asymétrique.",
    ],
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer glucose, mannose et galactose permet de conclure que :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "Ce sont des aldohexoses.",
      "Le mannose est épimère en C2 du glucose.",
      "Le galactose est épimère en C4 du glucose.",
      "Le mannose et le galactose sont tous deux des cétoses.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les trois sont des aldohexoses ; les deux épiméries de référence concernent C2 et C4.",
    choiceExplanations: [
      "Vrai. Ils ont six carbones et une fonction aldéhyde dans la forme ouverte.",
      "Vrai. C2 est la seule différence glucose–mannose.",
      "Vrai. C4 est la seule différence glucose–galactose.",
      "Faux. Mannose et galactose sont des aldoses.",
    ],
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Les oses impliqués directement dans les acides nucléiques comprennent :",
    choices: [
      "Le ribose pour l’ARN.",
      "Le 2-désoxyribose pour l’ADN.",
      "Des pentoses.",
      "Exclusivement des hexoses.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les acides nucléiques contiennent des pentoses : ribose ou 2-désoxyribose.",
    choiceExplanations: [
      "Vrai. Le ribose est le sucre de l’ARN.",
      "Vrai. Le désoxyribose est le sucre de l’ADN.",
      "Vrai. Ces deux sucres ont cinq carbones.",
      "Faux. Ils ne sont pas des hexoses.",
    ],
  },
  {
    order: 21,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À partir de la figure comparant les trioses :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glyceraldehyde-dihydroxyacetone-linear',
    },
    choices: [
      "Le glycéraldéhyde porte une fonction aldéhyde.",
      "La dihydroxyacétone porte une fonction cétone.",
      "Les deux molécules ont le même nombre de carbones.",
      "La dihydroxyacétone est un aldohexose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La figure oppose un aldotriose et un cétotriose.",
    choiceExplanations: [
      "Vrai. Le groupement CHO est terminal.",
      "Vrai. Le carbonyle est situé sur le carbone central.",
      "Vrai. Elles comportent trois carbones.",
      "Faux. Elle est un cétotriose.",
    ],
  },
  {
    order: 22,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "À partir des projections de Fischer présentées :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-mannose-galactose-fischer',
    },
    choices: [
      "Le mannose diffère du glucose en C2.",
      "Le galactose diffère du glucose en C4.",
      "Les trois molécules appartiennent aux aldoses.",
      "Le galactose diffère du glucose sur tous ses carbones asymétriques.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La lecture comparative visualise les deux épiméries classiques.",
    choiceExplanations: [
      "Vrai. L’OH de C2 change de côté.",
      "Vrai. L’OH de C4 change de côté.",
      "Vrai. Leur carbonyle ouvert est aldéhydique.",
      "Faux. Une seule configuration diffère.",
    ],
  },
  {
    order: 23,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Chez un patient, une glycémie durablement mal contrôlée :",
    choices: [
      "Concerne la concentration sanguine en glucose.",
      "Peut s’inscrire dans un diabète.",
      "Est sans lien avec le métabolisme glucidique.",
      "N’implique pas que le glucose cesse d’être un ose.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La glycémie est la concentration de glucose sanguin ; son dérèglement caractérise le diabète sans modifier la nature chimique du glucose.",
    choiceExplanations: [
      "Vrai. C’est la définition de la glycémie.",
      "Vrai. C’est le contexte pathologique cité.",
      "Faux. Le glucose est un glucide central.",
      "Vrai. Une anomalie de concentration ne change pas la classification chimique.",
    ],
  },
  {
    order: 24,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: "Un ose identifié comme « lévulose » dans un compte rendu ancien correspond au :",
    choices: [
      "Galactose.",
      "Mannose.",
      "Fructose.",
      "Ribose.",
    ],
    correctChoiceIndexes: [2],
    explanation: "Lévulose est un nom traditionnel du fructose.",
    choiceExplanations: [
      "Le galactose n’est pas appelé lévulose.",
      "Le mannose n’est pas appelé lévulose.",
      "C’est le synonyme recherché.",
      "Le ribose n’est pas appelé lévulose.",
    ],
  },
  {
    order: 25,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La forme furanique du fructose est cohérente avec les propositions suivantes :",
    choices: [
      "Le fructose est un cétose.",
      "Les formes furaniques sont particulièrement stables pour les cétoses.",
      "Le fructose peut participer au saccharose.",
      "Le fructose est un pentose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le fructose est un cétohexose souvent représenté sous forme furanique.",
    choiceExplanations: [
      "Vrai. Sa fonction carbonyle ouverte est une cétone.",
      "Vrai. C’est le repère donné dans le cours.",
      "Vrai. Il est associé au glucose dans le saccharose.",
      "Faux. Il possède six carbones.",
    ],
  },
  {
    order: 26,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "La forme pyranique du glucose :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-cyclization-anomers',
    },
    choices: [
      "Est très stable pour un aldose.",
      "Est majoritaire en solution.",
      "Comporte un cycle à six sommets, oxygène inclus.",
      "Transforme le glucose en cétose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La cyclisation pyranique est la forme dominante du glucose sans changer sa famille fondamentale.",
    choiceExplanations: [
      "Vrai. C’est une forme stable des aldoses.",
      "Vrai. Environ 99 % selon la fiche.",
      "Vrai. Le terme pyranose renvoie à un cycle à six sommets.",
      "Faux. La cyclisation ne convertit pas l’aldose en cétose.",
    ],
  },
  {
    order: 27,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le galactose peut être retrouvé :",
    choices: [
      "Dans des glycoprotéines.",
      "Dans des glycolipides.",
      "Sous forme de dérivés cérébrogalactosides.",
      "Uniquement à l’état libre dans le sang.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le galactose entre dans plusieurs glycoconjugués, notamment des structures cérébrales.",
    choiceExplanations: [
      "Vrai. Il peut constituer les chaînes glucidiques de glycoprotéines.",
      "Vrai. Il est également présent dans des glycolipides.",
      "Vrai. L’exemple cérébral est cité.",
      "Faux. Ses formes incorporées dans des molécules complexes sont nombreuses.",
    ],
  },
  {
    order: 28,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Le mannose et le galactose ont en commun :",
    choices: [
      "D’être des aldoses.",
      "D’être des hexoses.",
      "D’être impliqués dans des glycoconjugués.",
      "D’être tous deux épimères du glucose en C2.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Mannose et galactose sont des aldohexoses présents dans des glycoconjugués, mais leurs positions d’épimérie diffèrent.",
    choiceExplanations: [
      "Vrai. Leur forme ouverte porte une fonction aldéhyde.",
      "Vrai. Ils possèdent six carbones.",
      "Vrai. Ils sont présents notamment dans des glycoprotéines ou glycolipides.",
      "Faux. Seul le mannose est épimère en C2 ; le galactose l’est en C4.",
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Un ose simple est très hydrosoluble et donne un test de Fehling positif. On peut raisonnablement envisager :",
    choices: [
      "La présence de plusieurs groupes OH.",
      "Un caractère réducteur.",
      "Une forme ouverte aldéhydique accessible.",
      "Une structure exclusivement hydrocarbonée.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les propriétés décrites sont cohérentes avec un aldose polyhydroxylé et réducteur.",
    choiceExplanations: [
      "Vrai. Les OH expliquent l’hydrosolubilité.",
      "Vrai. Le test positif traduit un pouvoir réducteur.",
      "Vrai. L’équilibre avec une forme aldéhydique permet l’oxydation.",
      "Faux. Une structure purement hydrocarbonée serait peu compatible avec ces propriétés.",
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: "Synthèse sur les principaux oses simples :\n\n[[QUESTION_DIAGRAM]]",
    questionDiagram: {
      type: 'carbohydrate',
      diagram: 'glucose-fructose-ribose-fischer',
    },
    choices: [
      "Glucose, mannose et galactose sont des aldohexoses.",
      "Le fructose est un cétohexose.",
      "Le ribose est associé à l’ARN.",
      "La dihydroxyacétone est un aldohexose.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les familles et rôles de référence permettent de distinguer les principaux oses.",
    choiceExplanations: [
      "Vrai. Ils ont six carbones et une fonction aldéhyde ouverte.",
      "Vrai. Le fructose possède six carbones et une cétone.",
      "Vrai. Il constitue le sucre de l’ARN.",
      "Faux. La dihydroxyacétone est un cétotriose.",
    ],
  },
];
