/** Cartographie éditoriale V2 — auteur */

export const UE14_CELL_CH3_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-reseaux-microtubules",
    "title": "Réseaux du cytosquelette et microtubules",
    "description": "Comparer microtubules, microfilaments d’actine et filaments intermédiaires.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-centrosome-polarite",
    "title": "Organisation et polarité des microtubules",
    "description": "Applications sur structure, centrosome, polarité et microtubules stabilisés.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-polymérisation-mt",
    "title": "Polymérisation et fonctions des microtubules",
    "description": "Tubuline, GTP, polymérisation et grandes fonctions des microtubules.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-moteurs-cils-fuseau",
    "title": "Moteurs, cils, flagelles et fuseau mitotique",
    "description": "Applications sur kinésine, dynéine, cils, flagelles et fuseau mitotique.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-actine",
    "title": "Structure et dynamique de l’actine",
    "description": "Repères sur actine G, polarité et polymérisation des microfilaments.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-actine-contraction",
    "title": "Actine, cortex, cytodiérèse et contraction",
    "description": "Applications sur cortex, microvillosités, cytodiérèse et contraction.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-migration-fi",
    "title": "Migration et filaments intermédiaires",
    "description": "Migration cellulaire et propriétés générales des filaments intermédiaires.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-remodelage-actine-fi",
    "title": "Remodelage de l’actine et fonctions des FI",
    "description": "Applications sur front migratoire, zone de rétraction et marqueurs de FI.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-migration-cytosquelette",
    "title": "Maîtriser migration et architecture cytosquelettique",
    "description": "Maîtrise transversale de la migration et de la mécanique cellulaire.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-cytosquelette",
    "title": "Synthèse : cytosquelette",
    "description": "Synthèse transversale du chapitre.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-cytosquelette",
    "title": "Synthèse : cytosquelette",
    "description": "Maîtrise du chapitre dans un esprit proche des questions d’examen.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_CELL_CH3_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["les trois types de structures du cytosquelette"],
  2: ["le diamètre des microtubules"],
  3: ["le diamètre des microfilaments d’actine"],
  4: ["les filaments intermédiaires dans le tableau général"],
  5: ["la localisation des microtubules"],
  6: ["les microtubules chez les cellules humaines"],
  7: ["la structure des microtubules"],
  8: ["les microtubules instables"],
  9: ["les structures à microtubules stabilisés"],
  10: ["l’axonème des cils et flagelles mobiles selon la fiche"],
  11: ["le diamètre des microfilaments d’actine"],
  12: ["les filaments intermédiaires dans le tableau général"],
  13: ["la localisation des microtubules"],
  14: ["les microtubules chez les cellules humaines"],
  15: ["la structure des microtubules"],
  16: ["le diamètre des microtubules"],
  17: ["les structures à microtubules stabilisés"],
  18: ["l’axonème des cils et flagelles mobiles selon la fiche"],
  19: ["les structures à microtubules stabilisés", "l’axonème des cils et flagelles mobiles selon la fiche", "les cils primaires selon la fiche"],
  20: ["le centrosome"],
  21: ["la polarité des microtubules"],
  22: ["le centrosome", "la polarité des microtubules", "les trois types de structures du cytosquelette", "le diamètre des microtubules", "le diamètre des microfilaments d’actine"],
  23: ["la tubuline α et la tubuline β"],
  24: ["la polymérisation des microtubules"],
  25: ["le rôle du GTP dans la polymérisation des microtubules"],
  26: ["le rôle des microtubules dans les cils respiratoires"],
  27: ["le flagelle du spermatozoïde"],
  28: ["les microtubules comme rails intracellulaires"],
  29: ["la kinésine et la dynéine"],
  30: ["la structure simplifiée des moteurs microtubulaires"],
  31: ["les microtubules et la division cellulaire"],
  32: ["l’énergie des moteurs moléculaires sur microtubules"],
  33: ["le rôle du GTP dans la polymérisation des microtubules"],
  34: ["le rôle des microtubules dans les cils respiratoires"],
  35: ["le flagelle du spermatozoïde"],
  36: ["les microtubules comme rails intracellulaires"],
  37: ["la kinésine et la dynéine"],
  38: ["la kinésine et la dynéine"],
  39: ["les microtubules et la division cellulaire"],
  40: ["l’énergie des moteurs moléculaires sur microtubules"],
  41: ["les microtubules et la division cellulaire", "l’énergie des moteurs moléculaires sur microtubules", "les contextes fonctionnels des microtubules"],
  42: ["la tubuline α et la tubuline β"],
  43: ["la polymérisation des microtubules"],
  44: ["la tubuline α et la tubuline β", "la polymérisation des microtubules", "le rôle du GTP dans la polymérisation des microtubules", "le rôle des microtubules dans les cils respiratoires", "le flagelle du spermatozoïde"],
  45: ["la localisation des microfilaments d’actine"],
  46: ["l’abondance de l’actine"],
  47: ["l’actine G"],
  48: ["l’activité ATPase de l’actine G"],
  49: ["les extrémités de l’actine"],
  50: ["la structure des microfilaments d’actine"],
  51: ["la nucléation de l’actine selon la fiche"],
  52: ["les microvillosités et l’actine"],
  53: ["l’anneau contractile de cytodiérèse"],
  54: ["l’actine et la contraction musculaire"],
  55: ["l’actine G"],
  56: ["l’activité ATPase de l’actine G"],
  57: ["les extrémités de l’actine"],
  58: ["la structure des microfilaments d’actine"],
  59: ["la nucléation de l’actine selon la fiche"],
  60: ["la nucléation de l’actine selon la fiche"],
  61: ["l’anneau contractile de cytodiérèse"],
  62: ["l’actine et la contraction musculaire"],
  63: ["l’anneau contractile de cytodiérèse", "l’actine et la contraction musculaire", "les fonctions dynamiques de l’actine"],
  64: ["la localisation des microfilaments d’actine"],
  65: ["l’abondance de l’actine"],
  66: ["la localisation des microfilaments d’actine", "l’abondance de l’actine", "l’actine G", "l’activité ATPase de l’actine G", "les extrémités de l’actine"],
  67: ["les contextes physiologiques de migration cellulaire"],
  68: ["les plaques d’adhérence pendant la migration"],
  69: ["les lamellipodes et filopodes"],
  70: ["la zone intermédiaire de la cellule migrante"],
  71: ["la zone de rétraction"],
  72: ["l’α-actinine dans la migration"],
  73: ["la myosine I au front migratoire selon la fiche"],
  74: ["la localisation des filaments intermédiaires"],
  75: ["les propriétés structurales des filaments intermédiaires"],
  76: ["les grandes protéines de filaments intermédiaires citées"],
  77: ["les lamellipodes et filopodes"],
  78: ["la zone intermédiaire de la cellule migrante"],
  79: ["la zone de rétraction"],
  80: ["l’α-actinine dans la migration"],
  81: ["la myosine I au front migratoire selon la fiche"],
  82: ["la localisation des filaments intermédiaires"],
  83: ["les propriétés structurales des filaments intermédiaires"],
  84: ["les grandes protéines de filaments intermédiaires citées"],
  85: ["les propriétés structurales des filaments intermédiaires", "les grandes protéines de filaments intermédiaires citées", "les fonctions mécaniques des filaments intermédiaires"],
  86: ["les filaments intermédiaires en pathologie"],
  87: ["les contextes physiologiques de migration cellulaire"],
  88: ["les filaments intermédiaires en pathologie", "les contextes physiologiques de migration cellulaire", "les plaques d’adhérence pendant la migration", "les lamellipodes et filopodes", "la zone intermédiaire de la cellule migrante"],
  89: ["les lamellipodes et filopodes"],
  90: ["les plaques d’adhérence pendant la migration", "la zone de rétraction"],
  91: ["les lamellipodes et filopodes", "l’α-actinine dans la migration"],
  92: ["la zone intermédiaire de la cellule migrante", "la myosine I au front migratoire selon la fiche"],
  93: ["la zone de rétraction", "la localisation des filaments intermédiaires"],
  94: ["l’α-actinine dans la migration", "les propriétés structurales des filaments intermédiaires"],
  95: ["la myosine I au front migratoire selon la fiche", "les grandes protéines de filaments intermédiaires citées"],
  96: ["la localisation des filaments intermédiaires", "les fonctions mécaniques des filaments intermédiaires"],
  97: ["les propriétés structurales des filaments intermédiaires", "les filaments intermédiaires en pathologie"],
  98: ["les grandes protéines de filaments intermédiaires citées", "les fonctions mécaniques des filaments intermédiaires", "les filaments intermédiaires en pathologie"],
  99: ["les fonctions mécaniques des filaments intermédiaires", "les plaques d’adhérence pendant la migration"],
  100: ["les filaments intermédiaires en pathologie", "les contextes physiologiques de migration cellulaire", "les plaques d’adhérence pendant la migration", "les lamellipodes et filopodes", "la zone intermédiaire de la cellule migrante"],
  101: ["les trois types de structures du cytosquelette", "l’axonème des cils et flagelles mobiles selon la fiche"],
  102: ["les microtubules chez les cellules humaines", "la polymérisation des microtubules"],
  103: ["les cils primaires selon la fiche", "la kinésine et la dynéine"],
  104: ["le rôle du GTP dans la polymérisation des microtubules", "la localisation des microfilaments d’actine"],
  105: ["la structure simplifiée des moteurs microtubulaires", "la structure des microfilaments d’actine"],
  106: ["l’abondance de l’actine", "les fonctions dynamiques de l’actine"],
  107: ["la nucléation de l’actine selon la fiche", "la zone de rétraction"],
  108: ["les contextes physiologiques de migration cellulaire", "les grandes protéines de filaments intermédiaires citées"],
  109: ["la localisation des microfilaments d’actine", "l’abondance de l’actine", "l’actine G"],
  110: ["l’activité ATPase de l’actine G", "les extrémités de l’actine", "la structure des microfilaments d’actine", "la nucléation de l’actine selon la fiche", "les microvillosités et l’actine"],
  111: ["le diamètre des microtubules", "les microtubules chez les cellules humaines", "la polarité des microtubules"],
  112: ["les structures à microtubules stabilisés", "le rôle des microtubules dans les cils respiratoires", "l’abondance de l’actine"],
  113: ["le rôle du GTP dans la polymérisation des microtubules", "l’activité ATPase de l’actine G", "la zone intermédiaire de la cellule migrante"],
  114: ["l’énergie des moteurs moléculaires sur microtubules", "la zone intermédiaire de la cellule migrante", "la localisation des microtubules"],
  115: ["la structure des microfilaments d’actine", "le diamètre des microfilaments d’actine", "le flagelle du spermatozoïde"],
  116: ["les plaques d’adhérence pendant la migration", "la tubuline α et la tubuline β", "la nucléation de l’actine selon la fiche"],
  117: ["la kinésine et la dynéine"],
  118: ["les filaments intermédiaires dans le tableau général", "les contextes physiologiques de migration cellulaire", "l’axonème des cils et flagelles mobiles selon la fiche"],
  119: ["les cils primaires selon la fiche", "les filaments intermédiaires en pathologie", "l’énergie des moteurs moléculaires sur microtubules"],
  120: ["le flagelle du spermatozoïde", "les cils primaires selon la fiche", "les contextes physiologiques de migration cellulaire"],
  121: ["les contextes fonctionnels des microtubules", "la localisation des microfilaments d’actine", "l’abondance de l’actine"],
  122: ["la nucléation de l’actine selon la fiche", "les microvillosités et l’actine", "l’anneau contractile de cytodiérèse", "l’actine et la contraction musculaire", "les fonctions dynamiques de l’actine"],
};
