/**
 * UE14 – Biologie cellulaire – Chapitre 8
 * Contenu fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_C_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La matrice nucléaire est définie expérimentalement comme :`,
    choices: [
      `Un ensemble de protéines nucléaires persistant après extraction.`,
      `Une structure comprenant la lamina.`,
      `Une structure comprenant un réseau fibreux interne.`,
      `Un ensemble constitué uniquement d’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle reste après élimination de nombreux constituants.`,
      `Exact. La lamina est sa composante périphérique.`,
      `Exact. Le réseau NuMA occupe le nucléoplasme.`,
      `Faux. L’ADN est éliminé par DNase lors de la préparation.`,
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La lamina :`,
    choices: [
      `Est au contact de la membrane interne de l’enveloppe.`,
      `A une épaisseur d’environ 0,2 µm dans la fiche.`,
      `Est constituée de lamines A, B et C.`,
      `Est localisée dans le cytoplasme loin du noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle tapisse sa face nucléoplasmique.`,
      `Exact. Cette valeur est donnée explicitement.`,
      `Exact. Ces protéines sont les éléments structuraux de la lamina.`,
      `Faux. Elle est une structure nucléaire périphérique.`,
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les lamines A, B et C :`,
    choices: [
      `Appartiennent à la famille des filaments intermédiaires.`,
      `Forment un maillage régulier.`,
      `Sont des histones du nucléosome.`,
      `Participent au nucléosquelette périphérique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le cours les rattache au cytosquelette.`,
      `Exact. Cette organisation assure la résistance de l’enveloppe.`,
      `Faux. Les histones sont H2A, H2B, H3, H4 et H1.`,
      `Exact. Elles constituent la lamina.`,
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le réseau fibreux nucléaire :`,
    choices: [
      `Est constitué de protéines NuMA.`,
      `Est présent dans tout le nucléoplasme.`,
      `Peut être visualisé en fluorescence.`,
      `Est uniquement localisé dans l’espace périnucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. NuMA signifie Nuclear Matrix.`,
      `Exact. Il forme un réseau interne.`,
      `Exact. Les protéines NuMA apparaissent en vert dans l’exemple.`,
      `Faux. Il occupe le volume du noyau.`,
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La matrice nucléaire contribue :`,
    choices: [
      `À la forme du noyau.`,
      `À la taille du noyau.`,
      `À l’organisation des sites de duplication et de transcription.`,
      `À l’export direct de l’ADN hors du noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle joue un rôle de squelette.`,
      `Exact. La forme et la taille persistent après extraction.`,
      `Exact. Les polymérases sont ancrées sur ou près de la matrice.`,
      `Faux. L’ADN reste nucléaire.`,
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les domaines LAD et MAR :`,
    choices: [
      `Les LAD s’associent à la lamina.`,
      `Les MAR s’associent à la matrice nucléaire.`,
      `Participent à l’ancrage de la chromatine.`,
      `Sont des enzymes de digestion lysosomale.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. LAD signifie Lamina Associated Domains.`,
      `Exact. MAR signifie Matrix Associated Regions.`,
      `Exact. Ils organisent la chromatine dans le noyau.`,
      `Faux. Ce sont des régions d’ADN associées au nucléosquelette.`,
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un noyau 2n en phase G2, la fiche indique environ :`,
    choices: [
      `1,8 m d’ADN.`,
      `1,8 nm d’ADN.`,
      `Une forte contrainte de rangement dans le noyau.`,
      `Aucun besoin de compaction.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cette longueur illustre la nécessité de compaction.`,
      `Faux. La valeur indiquée est de l’ordre du mètre.`,
      `Exact. La chromatine doit être condensée de façon ordonnée.`,
      `Faux. La longueur de l’ADN impose une organisation hiérarchique.`,
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’organisation de la chromatine doit concilier :`,
    choices: [
      `La compaction de l’ADN.`,
      `La décondensation locale pour transcription et duplication.`,
      `Des niveaux de condensation imbriqués.`,
      `Une condensation maximale permanente de tout le génome.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle permet de le contenir dans le noyau.`,
      `Exact. Les polymérases nécessitent l’accessibilité de l’ADN.`,
      `Exact. La compaction est hiérarchisée.`,
      `Faux. Cela empêcherait toute activité de polymérase.`,
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le noyau nucléosomique est constitué :`,
    choices: [
      `D’un octamère d’histones.`,
      `De deux exemplaires de H2A, H2B, H3 et H4.`,
      `D’ADN enroulé autour de l’octamère.`,
      `Uniquement d’histone H1.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Il comprend deux exemplaires de quatre histones.`,
      `Exact. C’est la composition de l’octamère.`,
      `Exact. Le cours décrit environ deux boucles.`,
      `Faux. H1 stabilise l’ensemble mais ne constitue pas l’octamère central.`,
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’histone H1 :`,
    choices: [
      `Stabilise l’ensemble nucléosomique.`,
      `Fait partie des huit histones centrales de l’octamère.`,
      `Intervient dans l’organisation de la fibre.`,
      `Est une enzyme de réplication de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle est associée à l’ADN internucléosomique.`,
      `Faux. L’octamère contient H2A, H2B, H3 et H4 en double.`,
      `Exact. Elle contribue à la stabilité de la structure.`,
      `Faux. C’est une protéine histone structurale.`,
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La fibre nucléosomique :`,
    choices: [
      `Correspond à un collier de perles.`,
      `Est la structure chromatinienne la plus décondensée décrite.`,
      `Peut être observée en microscopie électronique.`,
      `Est plus compacte qu’un chromosome mitotique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les nucléosomes sont disposés les uns à la suite des autres.`,
      `Exact. Elle est visible après étalement de la chromatine.`,
      `Exact. La fiche présente des images MET.`,
      `Faux. Le chromosome est l’état le plus condensé.`,
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La fibre de 30 nm :`,
    choices: [
      `Résulte de l’enroulement de la fibre nucléosomique.`,
      `Représente un premier ordre de compaction.`,
      `Est plus décondensée que le collier de perles.`,
      `S’inscrit dans une succession de niveaux conduisant au chromosome.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle constitue un niveau supérieur de compaction.`,
      `Exact. Le cours l’identifie ainsi.`,
      `Faux. Elle est au contraire plus condensée.`,
      `Exact. La compaction est hiérarchique.`,
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En microscopie électronique nucléaire :`,
    choices: [
      `Une zone foncée correspond à de la chromatine condensée.`,
      `Une zone gris clair correspond à de la chromatine décondensée.`,
      `Une zone blanche peut correspondre au nucléole.`,
      `Toutes les zones ont la même signification.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La densité électronique est plus élevée.`,
      `Exact. Elle est plus accessible.`,
      `Exact. La fiche utilise cette convention d’interprétation.`,
      `Faux. Les contrastes renseignent sur la compaction.`,
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `En observant la figure de compaction :

![Compaction de la chromatine](/images/training/ue14/biologie-cellulaire/noyau/compaction-chromatine.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `L’ADN s’enroule autour d’octamères d’histones.`,
      `La fibre nucléosomique peut être compactée en fibre de 30 nm.`,
      `Les boucles sont ancrées par des régions MAR.`,
      `L’hétérochromatine est l’état le plus accessible aux polymérases.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cela forme les nucléosomes.`,
      `Exact. Le schéma montre cette étape.`,
      `Exact. Elles relient la chromatine à la matrice.`,
      `Faux. C’est l’euchromatine qui est accessible.`,
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’expérience d’extraction de la matrice nucléaire montre que :`,
    choices: [
      `La forme générale du noyau peut persister après retrait de nombreux constituants.`,
      `La matrice joue un rôle de squelette.`,
      `La forme nucléaire dépend uniquement de l’ADN.`,
      `Le nucléosquelette comprend des éléments périphériques et internes.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La matrice conserve une forme similaire au noyau initial.`,
      `Exact. Elle soutient la forme et la taille.`,
      `Faux. Elle persiste même après extraction de la chromatine.`,
      `Exact. Lamina et réseau fibreux sont distingués.`,
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les polymérases nucléaires :`,
    choices: [
      `Sont ancrées sur ou à proximité de la matrice nucléaire.`,
      `Participent à l’organisation fonctionnelle des sites de duplication et transcription.`,
      `Flottent obligatoirement sans aucune association structurale.`,
      `Nécessitent une chromatine localement accessible.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Le cours relie la matrice aux sites de synthèse.`,
      `Exact. Leur positionnement contribue à ces activités.`,
      `Faux. La fiche souligne leur ancrage.`,
      `Exact. La transcription et la duplication demandent une décondensation locale.`,
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les boucles de fibre nucléosomique :`,
    choices: [
      `Ont leurs extrémités ancrées à la matrice par des MAR.`,
      `Contiennent une origine de réplication selon la fiche.`,
      `Peuvent contenir plusieurs gènes.`,
      `Sont totalement dépourvues d’ADN non codant.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ces régions sont des séquences spécifiques d’ADN non codant.`,
      `Exact. Chaque boucle est organisée comme une unité de réplication.`,
      `Exact. Plusieurs origines de transcription sont possibles.`,
      `Faux. Les MAR sont précisément des séquences non codantes.`,
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La longueur d’une boucle nucléosomique est donnée comme étant d’environ :`,
    choices: [
      `500 nucléosomes.`,
      `5 nucléosomes.`,
      `Une organisation pouvant porter plusieurs gènes.`,
      `Un chromosome entier sans organisation interne.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. C’est l’ordre de grandeur indiqué.`,
      `Faux. La boucle est bien plus longue.`,
      `Exact. Cette longueur permet plusieurs unités transcriptionnelles.`,
      `Faux. Un chromosome contient de nombreuses boucles.`,
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des territoires chromosomiques :`,
    choices: [
      `Chaque chromosome occupe un volume restreint du noyau.`,
      `Ils peuvent être visualisés par FISH multicouleur.`,
      `Ils témoignent d’une organisation spatiale très poussée.`,
      `Tous les chromosomes occupent exactement le même espace.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les fibres de chromosomes différents ne sont pas mélangées au hasard.`,
      `Exact. La fiche montre un noyau interphasique coloré.`,
      `Exact. La chromatine est structurée dans le nucléoplasme.`,
      `Faux. Chaque chromosome possède son propre territoire préférentiel.`,
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’ancrage de la chromatine à la matrice :`,
    choices: [
      `Implique les LAD au niveau de la lamina.`,
      `Implique les MAR au niveau du réseau matriciel.`,
      `Participe à l’organisation tridimensionnelle du génome.`,
      `Détruit toute possibilité de transcription.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Ces domaines associent l’ADN à la périphérie nucléaire.`,
      `Exact. Ces régions ancrent notamment les boucles.`,
      `Exact. L’ADN n’est pas réparti au hasard.`,
      `Faux. L’organisation permet au contraire une régulation localisée.`,
    ],
  },
  {
    order: 81,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation majeure des lamines pourrait théoriquement affecter :`,
    choices: [
      `La forme et la résistance du noyau.`,
      `L’ancrage de certaines régions chromatiniennes LAD.`,
      `La séquence du NLS de toutes les protéines.`,
      `L’organisation de la membrane interne.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La lamina constitue le squelette périphérique.`,
      `Exact. Ces domaines s’associent à la lamina.`,
      `Faux. Le NLS est porté par les protéines elles-mêmes.`,
      `Exact. La lamina est directement au contact de cette membrane.`,
    ],
  },
  {
    order: 82,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Après DNase, RNase et extraction des protéines solubles, une structure nucléaire conserve sa forme. Il s’agit :`,
    choices: [
      `De la matrice nucléaire.`,
      `D’un argument en faveur de son rôle de squelette.`,
      `De la chromatine intacte.`,
      `D’une structure comprenant lamina et réseau fibreux.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle est définie par ce résidu structural.`,
      `Exact. La forme persiste malgré les extractions.`,
      `Faux. L’ADN a été hydrolysé par DNase.`,
      `Exact. Ce sont les composantes reconnues en microscopie.`,
    ],
  },
  {
    order: 83,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `Une région d’ADN associée spécifiquement à la lamina est appelée :`,
    choices: [
      `LAD.`,
      `MAR.`,
      `NLS.`,
      `M6P.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Lamina Associated Domain est le terme du cours.`,
      `Faux. MAR désigne l’association à la matrice interne.`,
      `Faux. NLS est un signal peptidique d’import nucléaire.`,
      `Faux. M6P est un signal d’adressage lysosomal, hors de ce chapitre.`,
    ],
  },
  {
    order: 84,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une région MAR se situe préférentiellement :`,
    choices: [
      `Aux extrémités d’une boucle nucléosomique.`,
      `Dans de l’ADN non codant selon la fiche.`,
      `Dans la membrane externe de l’enveloppe.`,
      `À l’interface entre chromatine et matrice nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle permet son ancrage à la matrice.`,
      `Exact. Ces séquences ont un rôle structural.`,
      `Faux. Il s’agit d’ADN, non de membrane.`,
      `Exact. C’est la fonction d’une Matrix Associated Region.`,
    ],
  },
  {
    order: 85,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si toute la chromatine restait sous forme de chromosome mitotique :`,
    choices: [
      `La transcription serait fortement compromise.`,
      `La duplication serait compromise.`,
      `L’accessibilité aux polymérases serait maximale.`,
      `La cellule perdrait la possibilité de réguler localement la compaction.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Les polymérases n’accèdent pas à l’ADN condensé.`,
      `Exact. L’ADN doit être décondensé localement.`,
      `Faux. La condensation maximale réduit l’accessibilité.`,
      `Exact. La fonction exige des niveaux modulables.`,
    ],
  },
  {
    order: 86,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une observation en MET montre un aspect « collier de perles ». Il s’agit vraisemblablement :`,
    choices: [
      `De la fibre nucléosomique.`,
      `D’un état relativement décondensé.`,
      `D’un pore nucléaire vu de face.`,
      `D’ADN associé à des histones.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Chaque perle correspond à un nucléosome.`,
      `Exact. C’est la structure la moins compacte décrite.`,
      `Faux. Le pore présente une symétrie radiaire différente.`,
      `Exact. Les nucléosomes reposent sur cette association.`,
    ],
  },
  {
    order: 87,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une boucle chromatinienne comporte une origine de réplication et plusieurs gènes. Cela permet :`,
    choices: [
      `De coordonner une unité de duplication avec plusieurs unités transcriptionnelles.`,
      `Une régulation locale de l’activité.`,
      `De supprimer tout besoin d’ancrage matriciel.`,
      `D’organiser l’ADN dans un volume restreint.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. La boucle porte une origine de réplication et plusieurs origines de transcription.`,
      `Exact. Les gènes peuvent être actifs ou inactifs.`,
      `Faux. Les extrémités restent ancrées par les MAR.`,
      `Exact. La boucle participe à la compaction hiérarchique.`,
    ],
  },
  {
    order: 88,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `En observant un noyau interphasique par FISH multicouleur :`,
    choices: [
      `Chaque chromosome peut apparaître dans une zone distincte.`,
      `Les chromosomes ne sont pas complètement mélangés.`,
      `La chromatine est nécessairement sous forme de chromosomes mitotiques condensés.`,
      `L’organisation spatiale du génome peut être étudiée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Cela révèle les territoires chromosomiques.`,
      `Exact. Ils occupent des volumes restreints.`,
      `Faux. Il s’agit d’un noyau interphasique.`,
      `Exact. La méthode met en évidence les territoires.`,
    ],
  },
  {
    order: 89,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une chromatine localement décondensée au voisinage d’une polymérase ancrée à la matrice :`,
    choices: [
      `Peut être en cours de transcription.`,
      `Peut être en cours de duplication.`,
      `Est nécessairement inactive.`,
      `Illustre le lien entre structure et fonction nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. L’accessibilité permet l’activité de l’ARN polymérase.`,
      `Exact. L’ADN polymérase nécessite aussi une chromatine accessible.`,
      `Faux. La décondensation est associée à l’activité.`,
      `Exact. La matrice organise les sites actifs.`,
    ],
  },
  {
    order: 90,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Synthèse de la section :`,
    choices: [
      `La matrice nucléaire organise la forme et les activités du noyau.`,
      `La chromatine est compactée selon plusieurs niveaux.`,
      `L’organisation spatiale inclut des boucles et des territoires chromosomiques.`,
      `La chromatine est distribuée au hasard sans ancrage.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les propositions exactes correspondent aux notions explicitement présentées dans la fiche du Tutorat Santé de Reims.`,
    choiceExplanations: [
      `Exact. Elle sert de squelette et d’ancrage.`,
      `Exact. Du nucléosome au chromosome, les ordres sont imbriqués.`,
      `Exact. Le génome est structuré tridimensionnellement.`,
      `Faux. Les LAD, MAR et territoires montrent le contraire.`,
    ],
  },
];

export const SECTION_C_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: `matrice-nucleaire-et-lamina`,
    title: `Matrice nucléaire et lamina`,
    description: `Lamina, NuMA, LAD, MAR et rôle structural de la matrice.`,
    stage: 'DISCOVER',
    sectionOrder: 3,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: `nucleosomes-et-compaction`,
    title: `Nucléosomes et compaction de la chromatine`,
    description: `Octamère d’histones, fibres nucléosomique et de 30 nm, boucles.`,
    stage: 'PRACTICE',
    sectionOrder: 3,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  {
    order: 9,
    slug: `organisation-tridimensionnelle-chromatine`,
    title: `Organisation tridimensionnelle de la chromatine`,
    description: `Applications sur les territoires chromosomiques et l’ancrage matriciel.`,
    stage: 'MASTER',
    sectionOrder: 3,
    questionOrders: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
];
