/**
 * UE14 – Biologie cellulaire – Chapitre 7
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La fonction principale de la mitochondrie dans la fiche est :`,
    choices: [
      `La synthèse d’ATP.`,
      `La fourniture d’une grande partie de l’énergie cellulaire.`,
      `La production exclusive d’ARN ribosomal nucléaire.`,
      `La participation à la respiration cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La mitochondrie transforme l’énergie issue du catabolisme en ATP par phosphorylation oxydative.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les nutriments contribuant à la production d’ATP comprennent :`,
    choices: [
      `Les protéines.`,
      `Les glucides.`,
      `Les lipides.`,
      `Uniquement le cholestérol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les trois grandes familles de nutriments sont reliées au catabolisme énergétique dans la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le glucose et certains acides aminés peuvent conduire à la formation de :`,
    choices: [
      `Pyruvate.`,
      `Acétyl-CoA après oxydation mitochondriale.`,
      `NADH et FADH2 via le cycle de Krebs.`,
      `Glycocalyx mitochondrial.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le pyruvate et les acides gras alimentent l’acétyl-CoA puis le cycle de Krebs.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des acides gras :`,
    choices: [
      `Ils peuvent entrer dans la mitochondrie grâce à des perméases.`,
      `Leur oxydation contribue à former de l’acétyl-CoA.`,
      `Ils peuvent alimenter la production de NADH et FADH2.`,
      `Ils sont transformés directement en ADNmt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La β-oxydation des acides gras participe à l’approvisionnement énergétique de la chaîne respiratoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le cycle de Krebs :`,
    choices: [
      `Se déroule dans la matrice mitochondriale selon la fiche.`,
      `Produit notamment NADH et FADH2.`,
      `Est aussi appelé cycle de l’acide citrique.`,
      `Se déroule uniquement dans l’espace intermembranaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cycle de Krebs est une voie matricielle fournissant des coenzymes réduits.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les coenzymes réduits NADH et FADH2 :`,
    choices: [
      `Transportent des électrons à haute énergie.`,
      `Alimentent la chaîne respiratoire.`,
      `Sont produits notamment par le cycle de Krebs et la β-oxydation.`,
      `Sont des antigènes membranaires du système ABO.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `NADH et FADH2 relient le catabolisme à la chaîne respiratoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La respiration cellulaire décrite implique :`,
    choices: [
      `Une consommation d’O2.`,
      `Une production de CO2 et d’H2O.`,
      `Le transfert d’électrons dans la chaîne respiratoire.`,
      `Une absence totale de gradient protonique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le transfert électronique permet la constitution d’un gradient de protons.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Observe le schéma métabolique :

![Métabolismes et cycle de Krebs](/images/training/ue14/biologie-cellulaire/mitochondrie/metabolismes-cycle-krebs.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Les nutriments convergent vers des intermédiaires comme le pyruvate ou l’acétyl-CoA.`,
      `Le cycle de Krebs produit des coenzymes réduits.`,
      `NADH et FADH2 apportent des électrons à la chaîne respiratoire.`,
      `Le cycle de Krebs est localisé dans le glycocalyx.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le schéma relie le catabolisme des nutriments à la chaîne respiratoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La chaîne respiratoire comporte :`,
    choices: [
      `Quatre complexes enzymatiques dans la membrane interne.`,
      `Le complexe I ou NADH-déshydrogénase.`,
      `Le complexe II ou succinate-déshydrogénase.`,
      `Un unique complexe soluble dans le cytosol.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les complexes I à IV sont implantés dans la membrane interne.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les complexes III et IV correspondent respectivement à :`,
    choices: [
      `Le complexe b-c1.`,
      `La cytochrome oxydase.`,
      `L’ATP synthase F1.`,
      `Des éléments de la chaîne respiratoire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L’ATP synthase est distincte des complexes III et IV.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les électrons peuvent entrer dans la chaîne respiratoire :`,
    choices: [
      `Au complexe I à partir du NADH.`,
      `Au complexe II à partir du FADH2 ou de certaines navettes.`,
      `Directement à l’ATP synthase sans passer par les complexes.`,
      `Puis converger vers le complexe III.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les voies d’entrée I et II convergent ensuite vers le complexe III.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Les navettes citées dans la fiche sont :`,
    choices: [
      `La navette malate-aspartate.`,
      `La navette glycérol-phosphate.`,
      `Des systèmes transportant les équivalents réducteurs du NADH cytosolique.`,
      `La navette KDEL.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `KDEL est un signal de rétention du RE, sans rapport avec ce chapitre mitochondrial.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le transfert des électrons entre les complexes fait intervenir :`,
    choices: [
      `L’ubiquinone entre les complexes I/II et III.`,
      `Le cytochrome c entre III et IV.`,
      `Une perte progressive d’énergie des électrons.`,
      `Une production directe de glucose par le complexe IV.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les transporteurs mobiles assurent la continuité du transfert électronique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À l’extrémité de la chaîne respiratoire :`,
    choices: [
      `L’oxygène accepte les électrons.`,
      `De l’eau est formée.`,
      `Le complexe IV intervient.`,
      `Le complexe II synthétise directement l’ADNmt.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le complexe IV transfère les électrons à l’oxygène, qui est réduit en eau.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La chaîne respiratoire expulse des protons de la matrice vers l’espace intermembranaire au niveau :`,
    choices: [
      `Du complexe I.`,
      `Du complexe III.`,
      `Du complexe IV.`,
      `Du complexe II selon la fiche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche précise qu’il n’y a pas de sortie de protons au complexe II.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le complexe II se distingue car :`,
    choices: [
      `Il ne pompe pas de protons selon la fiche.`,
      `Son système d’oxydoréduction est décrit comme trop faible pour cette expulsion.`,
      `Il peut transmettre des électrons vers l’ubiquinone.`,
      `Il est identique à l’ATP synthase.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le complexe II participe au transfert d’électrons mais pas au pompage protonique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la chaîne respiratoire :

![Chaîne respiratoire et ATP synthase](/images/training/ue14/biologie-cellulaire/mitochondrie/chaine-respiratoire-atp-synthase.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `Les complexes I, III et IV pompent des protons.`,
      `Le complexe II ne pompe pas de protons.`,
      `Les électrons transitent par Q puis le cytochrome c.`,
      `L’ATP synthase expulse les électrons vers l’oxygène.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ATP synthase exploite le gradient protonique ; elle ne transfère pas les électrons à l’oxygène.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La force motrice protonique dépend :`,
    choices: [
      `D’une différence de concentration en H+ de part et d’autre de la membrane interne.`,
      `D’une accumulation de H+ dans l’espace intermembranaire.`,
      `Du fonctionnement de la chaîne respiratoire.`,
      `D’une absence complète de membrane interne.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La membrane interne permet de conserver le gradient électrochimique de protons.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La phosphorylation oxydative :`,
    choices: [
      `Utilise le gradient protonique.`,
      `Produit de l’ATP à partir d’ADP et de phosphate.`,
      `Se déroule grâce à l’ATP synthase.`,
      `Est indépendante de la respiration cellulaire dans la fiche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La phosphorylation oxydative est couplée à la respiration et au gradient protonique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `L’ATP nouvellement synthétisé :`,
    choices: [
      `Est produit du côté de la matrice.`,
      `Peut être exporté vers le cytosol par des perméases actives.`,
      `Alimente des réactions dans divers compartiments cellulaires.`,
      `Reste obligatoirement enfermé dans la mitochondrie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ATP doit être distribué à la cellule après sa synthèse mitochondriale.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition du complexe I empêcherait directement :`,
    choices: [
      `L’utilisation normale d’une partie du NADH.`,
      `Le transfert initial d’électrons entrant par la voie du complexe I.`,
      `Une part du pompage protonique.`,
      `Tout passage d’électrons entrant au complexe II dans tous les cas.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie du complexe II peut encore alimenter la chaîne en aval si elle reste fonctionnelle.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition du complexe III aurait pour conséquences attendues :`,
    choices: [
      `Une interruption du transfert vers le cytochrome c.`,
      `Une diminution du pompage protonique au complexe III.`,
      `Une perturbation de la réduction de l’oxygène en aval.`,
      `Une augmentation automatique de la synthèse d’ATP.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le blocage de III réduit le flux électronique et la force motrice protonique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une inhibition du complexe IV pourrait provoquer :`,
    choices: [
      `Un défaut de transfert des électrons à l’oxygène.`,
      `Une diminution de la formation d’eau en bout de chaîne.`,
      `Un arrêt rapide de la respiration mitochondriale.`,
      `Une stimulation directe du cycle de Krebs sans conséquence énergétique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le complexe IV constitue l’étape terminale de la chaîne respiratoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si la membrane interne devient librement perméable aux protons :`,
    choices: [
      `Le gradient protonique diminue.`,
      `La phosphorylation oxydative devient moins efficace.`,
      `Le retour contrôlé par l’ATP synthase perd une partie de son avantage énergétique.`,
      `Le complexe II se transforme en porine.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La conservation du gradient dépend de l’imperméabilité relative de la membrane interne aux protons.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une cellule privée d’oxygène ne peut plus normalement :`,
    choices: [
      `Utiliser l’oxygène comme accepteur final d’électrons.`,
      `Maintenir durablement le flux de la chaîne respiratoire.`,
      `Assurer normalement la phosphorylation oxydative.`,
      `Effectuer toute réaction cytosolique quelle qu’elle soit.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’absence d’oxygène compromet la respiration mitochondriale, sans supprimer instantanément toutes les réactions cytosoliques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les coenzymes NADH et FADH2 relient :`,
    choices: [
      `Le cycle de Krebs à la chaîne respiratoire.`,
      `La β-oxydation à la chaîne respiratoire.`,
      `Le catabolisme des nutriments à la production d’ATP.`,
      `Le système ABO au noyau.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Ces coenzymes sont des intermédiaires énergétiques majeurs.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le schéma suivant présente la convergence des nutriments vers l’acétyl-CoA et le cycle de Krebs.

![Métabolismes et cycle de Krebs](/images/training/ue14/biologie-cellulaire/mitochondrie/metabolismes-cycle-krebs.png)

Dans ce schéma intégré, quelle(s) proposition(s) est(sont) exacte(s) concernant l’acétyl-CoA ?`,
    choices: [
      `Constitue un point de convergence métabolique.`,
      `Alimente le cycle de Krebs.`,
      `Contribue indirectement à produire NADH et FADH2.`,
      `Est le produit final de la chaîne respiratoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La chaîne respiratoire utilise les électrons, tandis que l’acétyl-CoA alimente le cycle de Krebs.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation du cytochrome c pourrait perturber :`,
    choices: [
      `Le transfert d’électrons entre III et IV.`,
      `La respiration cellulaire.`,
      `La constitution du gradient protonique en aval.`,
      `Le passage des petites molécules par les porines uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cytochrome c appartient à la chaîne respiratoire et non au système des porines.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La localisation de la chaîne respiratoire dans la membrane interne permet :`,
    choices: [
      `D’associer transfert d’électrons et pompage protonique.`,
      `De séparer matrice et espace intermembranaire.`,
      `De créer une force motrice protonique.`,
      `De transcrire directement l’ADN nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La compartimentation de la membrane interne est essentielle au couplage énergétique.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?`,
    choices: [
      `Les nutriments fournissent des électrons via NADH et FADH2.`,
      `Les complexes I à IV transfèrent ces électrons jusqu’à l’oxygène.`,
      `Le pompage protonique prépare la synthèse d’ATP.`,
      `Le complexe II est la principale pompe à protons de la chaîne.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le complexe II est précisément celui qui ne pompe pas de protons selon la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit les éléments de la fiche ou attribue à la mitochondrie une propriété non décrite.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `nutriments-acetyl-coa-cycle-krebs`,
    title: `Des nutriments au cycle de Krebs`,
    description: `Pyruvate, acides gras, acétyl-CoA, NADH et FADH2.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `organisation-chaine-respiratoire`,
    title: `Organisation de la chaîne respiratoire`,
    description: `Complexes I à IV, ubiquinone, cytochrome c et oxygène.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `gradient-protonique-et-respiration`,
    title: `Gradient protonique et respiration`,
    description: `Couplage entre transfert électronique, pompage des protons et phosphorylation.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
