/** UE14 – Biologie cellulaire – Chapitre 6 */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-peroxysomes.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';

const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'peroxysomes';

const sections: SeedSection[] = [
  { order: 1, title: `Généralités, morphologie et biogenèse`, description: `Organisation, réseau peroxysomal, bourgeonnement, mobilité et renouvellement.`, kind: 'THEME' },
  { order: 2, title: `Composition, adressage et régulation`, description: `Membrane, matrice, perméases ABC, import des protéines, phospholipides et PPAR.`, kind: 'THEME' },
  { order: 3, title: `Oxydases, catalase et fonctions métaboliques`, description: `Production et détoxification du H2O2, β-oxydation, acides biliaires, acides aminés et alcool.`, kind: 'THEME' },
  { order: 4, title: `Coopération métabolique et pathologies`, description: `Très longues chaînes, mitochondries, fibrates, acide urique, leucodystrophies et maladies héréditaires.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Approche transversale de la structure, des fonctions et des pathologies peroxysomales.`, kind: 'SYNTHESIS' },
];

const questions: SeedQuestion[] = [
  ...SECTION_A_QUESTIONS,
  ...SECTION_B_QUESTIONS,
  ...SECTION_C_QUESTIONS,
  ...SECTION_D_QUESTIONS,
  ...SYNTHESIS_QUESTIONS,
];

const quizSeeds: SeedQuiz[] = [
  ...SECTION_A_QUIZZES,
  ...SECTION_B_QUIZZES,
  ...SECTION_C_QUIZZES,
  ...SECTION_D_QUIZZES,
  ...SYNTHESIS_QUIZZES,
];

const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Généralités et biogenèse`],
  2: [`Généralités et biogenèse`],
  3: [`Généralités et biogenèse`],
  4: [`Généralités et biogenèse`],
  5: [`Généralités et biogenèse`],
  6: [`Généralités et biogenèse`],
  7: [`Généralités et biogenèse`],
  8: [`Généralités et biogenèse`],
  9: [`Généralités et biogenèse`],
  10: [`Généralités et biogenèse`],
  11: [`Généralités et biogenèse`],
  12: [`Généralités et biogenèse`],
  13: [`Généralités et biogenèse`],
  14: [`Généralités et biogenèse`],
  15: [`Généralités et biogenèse`],
  16: [`Généralités et biogenèse`],
  17: [`Généralités et biogenèse`],
  18: [`Généralités et biogenèse`],
  19: [`Généralités et biogenèse`],
  20: [`Généralités et biogenèse`],
  21: [`Généralités et biogenèse`],
  22: [`Généralités et biogenèse`],
  23: [`Généralités et biogenèse`],
  24: [`Généralités et biogenèse`],
  25: [`Généralités et biogenèse`],
  26: [`Généralités et biogenèse`],
  27: [`Généralités et biogenèse`],
  28: [`Généralités et biogenèse`],
  29: [`Généralités et biogenèse`],
  30: [`Généralités et biogenèse`],
  31: [`Composition et régulation`],
  32: [`Composition et régulation`],
  33: [`Composition et régulation`],
  34: [`Composition et régulation`],
  35: [`Composition et régulation`],
  36: [`Composition et régulation`],
  37: [`Composition et régulation`],
  38: [`Composition et régulation`],
  39: [`Composition et régulation`],
  40: [`Composition et régulation`],
  41: [`Composition et régulation`],
  42: [`Composition et régulation`],
  43: [`Composition et régulation`],
  44: [`Composition et régulation`],
  45: [`Composition et régulation`],
  46: [`Composition et régulation`],
  47: [`Composition et régulation`],
  48: [`Composition et régulation`],
  49: [`Composition et régulation`],
  50: [`Composition et régulation`],
  51: [`Composition et régulation`],
  52: [`Composition et régulation`],
  53: [`Composition et régulation`],
  54: [`Composition et régulation`],
  55: [`Composition et régulation`],
  56: [`Composition et régulation`],
  57: [`Composition et régulation`],
  58: [`Composition et régulation`],
  59: [`Composition et régulation`],
  60: [`Composition et régulation`],
  61: [`Fonctions oxydatives`],
  62: [`Fonctions oxydatives`],
  63: [`Fonctions oxydatives`],
  64: [`Fonctions oxydatives`],
  65: [`Fonctions oxydatives`],
  66: [`Fonctions oxydatives`],
  67: [`Fonctions oxydatives`],
  68: [`Fonctions oxydatives`],
  69: [`Fonctions oxydatives`],
  70: [`Fonctions oxydatives`],
  71: [`Fonctions oxydatives`],
  72: [`Fonctions oxydatives`],
  73: [`Fonctions oxydatives`],
  74: [`Fonctions oxydatives`],
  75: [`Fonctions oxydatives`],
  76: [`Fonctions oxydatives`],
  77: [`Fonctions oxydatives`],
  78: [`Fonctions oxydatives`],
  79: [`Fonctions oxydatives`],
  80: [`Fonctions oxydatives`],
  81: [`Fonctions oxydatives`],
  82: [`Fonctions oxydatives`],
  83: [`Fonctions oxydatives`],
  84: [`Fonctions oxydatives`],
  85: [`Fonctions oxydatives`],
  86: [`Fonctions oxydatives`],
  87: [`Fonctions oxydatives`],
  88: [`Fonctions oxydatives`],
  89: [`Fonctions oxydatives`],
  90: [`Fonctions oxydatives`],
  91: [`Métabolisme et pathologies`],
  92: [`Métabolisme et pathologies`],
  93: [`Métabolisme et pathologies`],
  94: [`Métabolisme et pathologies`],
  95: [`Métabolisme et pathologies`],
  96: [`Métabolisme et pathologies`],
  97: [`Métabolisme et pathologies`],
  98: [`Métabolisme et pathologies`],
  99: [`Métabolisme et pathologies`],
  100: [`Métabolisme et pathologies`],
  101: [`Métabolisme et pathologies`],
  102: [`Métabolisme et pathologies`],
  103: [`Métabolisme et pathologies`],
  104: [`Métabolisme et pathologies`],
  105: [`Métabolisme et pathologies`],
  106: [`Métabolisme et pathologies`],
  107: [`Métabolisme et pathologies`],
  108: [`Métabolisme et pathologies`],
  109: [`Métabolisme et pathologies`],
  110: [`Métabolisme et pathologies`],
  111: [`Métabolisme et pathologies`],
  112: [`Métabolisme et pathologies`],
  113: [`Métabolisme et pathologies`],
  114: [`Métabolisme et pathologies`],
  115: [`Métabolisme et pathologies`],
  116: [`Métabolisme et pathologies`],
  117: [`Métabolisme et pathologies`],
  118: [`Métabolisme et pathologies`],
  119: [`Métabolisme et pathologies`],
  120: [`Métabolisme et pathologies`],
  121: [`Synthèse des peroxysomes`],
  122: [`Synthèse des peroxysomes`],
  123: [`Synthèse des peroxysomes`],
  124: [`Synthèse des peroxysomes`],
  125: [`Synthèse des peroxysomes`],
  126: [`Synthèse des peroxysomes`],
  127: [`Synthèse des peroxysomes`],
  128: [`Synthèse des peroxysomes`],
  129: [`Synthèse des peroxysomes`],
  130: [`Synthèse des peroxysomes`],
  131: [`Synthèse des peroxysomes`],
  132: [`Synthèse des peroxysomes`],
  133: [`Synthèse des peroxysomes`],
  134: [`Synthèse des peroxysomes`],
  135: [`Synthèse des peroxysomes`],
  136: [`Synthèse des peroxysomes`],
  137: [`Synthèse des peroxysomes`],
  138: [`Synthèse des peroxysomes`],
  139: [`Synthèse des peroxysomes`],
  140: [`Synthèse des peroxysomes`],
};

export async function seedHealthTrainingUe14BiologieCellulairePeroxysomes(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 6',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
  });
}
