import type { HealthTrainingAuthorQuestion } from './health-training-ue14.shared';

/**
 * UE14 – Chimie générale
 * Chapitre 3 – Orbitales moléculaires
 * Section A – Orbitales moléculaires et liaisons sigma/pi
 */

export const UE14_CH3_OM_DISCOVER_V2_QUESTIONS: HealthTrainingAuthorQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    format: 'QRM',
    question: `À propos de la notion d'orbitale moléculaire, quelles propositions sont exactes ?`,
    choices: [
      { content: `Elle décrit une région de l'espace associée à l'édifice moléculaire dans laquelle des électrons peuvent être présents.`, correct: true, explanation: `Vrai : l'orbitale moléculaire appartient à la molécule.` },
      { content: `Elle peut résulter de la combinaison d'orbitales atomiques compatibles.`, correct: true, explanation: `Vrai : c'est le principe présenté dans le cours.` },
      { content: `Elle décrit la trajectoire précise d'un électron autour d'un seul noyau.`, correct: false, explanation: `Faux : une orbitale ne correspond pas à une trajectoire classique.` },
      { content: `Elle est nécessairement localisée sur un seul atome.`, correct: false, explanation: `Faux : une orbitale moléculaire s'étend sur l'édifice moléculaire.` },
    ],
    explanation: `Une orbitale moléculaire résulte de la combinaison d'orbitales atomiques et décrit une distribution électronique à l'échelle de la molécule.`,
  },
  {
    order: 2,
    difficulty: 'EASY',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Sélectionnez exactement les deux caractéristiques d'une liaison $\\sigma$.`,
    choices: [
      { content: `Elle résulte d'un recouvrement axial selon l'axe internucléaire.`, correct: true, explanation: `Vrai.` },
      { content: `Elle possède une symétrie axiale autour de l'axe de liaison.`, correct: true, explanation: `Vrai.` },
      { content: `Elle résulte obligatoirement d'un recouvrement latéral de deux orbitales $\\mathrm{p}$.`, correct: false, explanation: `Le recouvrement latéral caractérise une liaison $\\pi$.` },
      { content: `Elle interdit par elle-même toute rotation autour d'une liaison simple.`, correct: false, explanation: `Une liaison $\\sigma$ isolée conserve son recouvrement lors d'une rotation autour de son axe.` },
    ],
    explanation: `La liaison $\\sigma$ provient d'un recouvrement axial et possède une symétrie axiale, ce qui autorise en principe la rotation autour d'une liaison simple isolée.`,
  },
  {
    order: 3,
    difficulty: 'EASY',
    format: 'QRM',
    question: `Quelles combinaisons d'orbitales atomiques peuvent conduire à une liaison $\\sigma$ si leur orientation est adaptée ?`,
    choices: [
      { content: `Recouvrement $\\mathrm{s-s}$.`, correct: true, explanation: `Deux orbitales s peuvent se recouvrir axialement.` },
      { content: `Recouvrement $\\mathrm{s-p}$.`, correct: true, explanation: `Une orbitale p orientée selon l'axe peut se recouvrir avec une orbitale s.` },
      { content: `Recouvrement axial $\\mathrm{p-p}$.`, correct: true, explanation: `Deux orbitales p face à face peuvent former une liaison sigma.` },
      { content: `Recouvrement latéral $\\mathrm{p-p}$.`, correct: false, explanation: `Un recouvrement latéral de deux orbitales p conduit à une liaison pi.` },
    ],
    explanation: `Les liaisons $\\sigma$ peuvent être obtenues par des recouvrements axiaux $\\mathrm{s-s}$, $\\mathrm{s-p}$ ou $\\mathrm{p-p}$.`,
  },
  {
    order: 4,
    difficulty: 'EASY',
    format: 'QRU',
    question: `Deux orbitales atomiques compatibles se combinent. Quelle proposition est correcte ?`,
    choices: [
      { content: `Elles donnent une seule orbitale moléculaire.`, correct: false, explanation: `Deux orbitales atomiques donnent deux combinaisons moléculaires.` },
      { content: `Elles donnent une orbitale moléculaire liante et une orbitale moléculaire antiliante.`, correct: true, explanation: `C'est le schéma simplifié retenu dans le chapitre.` },
      { content: `Elles deviennent deux noyaux supplémentaires.`, correct: false, explanation: `La combinaison concerne les fonctions orbitalaires, pas les noyaux.` },
      { content: `L'orbitale antiliante est toujours moins énergétique que l'orbitale liante.`, correct: false, explanation: `L'orbitale antiliante est au contraire plus énergétique.` },
    ],
    explanation: `Deux orbitales atomiques donnent deux orbitales moléculaires : une combinaison liante stabilisée et une combinaison antiliante déstabilisée.`,
  },
  {
    order: 5,
    difficulty: 'EASY',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Sélectionnez exactement les deux caractéristiques d'une liaison $\\pi$.`,
    choices: [
      { content: `Elle provient d'un recouvrement latéral de deux orbitales $\\mathrm{p}$ parallèles.`, correct: true, explanation: `Vrai.` },
      { content: `Sa densité électronique est située de part et d'autre de l'axe internucléaire.`, correct: true, explanation: `Vrai.` },
      { content: `Elle possède une symétrie axiale permettant une rotation libre.`, correct: false, explanation: `La rotation désaligne les orbitales p et diminue le recouvrement.` },
      { content: `Elle constitue toujours le premier doublet partagé entre deux atomes.`, correct: false, explanation: `Le premier doublet partagé forme une liaison sigma.` },
    ],
    explanation: `Une liaison $\\pi$ est issue d'un recouvrement latéral d'orbitales p parallèles et ne possède pas la symétrie axiale d'une liaison sigma.`,
  },
  {
    order: 6,
    difficulty: 'EASY',
    format: 'QRM',
    question: `En comparant les liaisons $\\sigma$ et $\\pi$, quelles propositions sont exactes ?`,
    choices: [
      { content: `Le recouvrement axial d'une liaison $\\sigma$ est généralement plus important que le recouvrement latéral d'une liaison $\\pi$.`, correct: true, explanation: `Vrai dans le modèle qualitatif du cours.` },
      { content: `Une liaison $\\pi$ est généralement moins stable qu'une liaison $\\sigma$ comparable.`, correct: true, explanation: `Son recouvrement latéral est moins efficace.` },
      { content: `Une liaison $\\pi$ limite la rotation autour de l'axe internucléaire.`, correct: true, explanation: `La rotation désaligne les orbitales p.` },
      { content: `Une double liaison contient deux liaisons $\\sigma$.`, correct: false, explanation: `Une double liaison contient une sigma et une pi.` },
    ],
    explanation: `La liaison sigma est associée à un recouvrement axial plus efficace ; la liaison pi est plus fragile et impose une contrainte de rotation.`,
  },
  {
    order: 7,
    difficulty: 'EASY',
    format: 'QRU',
    question: `Dans le modèle simplifié du cours, la double liaison $\\ce{O=O}$ du dioxygène comporte :`,
    choices: [
      { content: `Une liaison $\\sigma$ et une liaison $\\pi$.`, correct: true, explanation: `C'est la composition d'une double liaison.` },
      { content: `Deux liaisons $\\sigma$.`, correct: false, explanation: `Il ne peut exister qu'une composante sigma selon l'axe internucléaire.` },
      { content: `Deux liaisons $\\pi$.`, correct: false, explanation: `Une double liaison ne comporte qu'une composante pi.` },
      { content: `Une seule liaison $\\pi$.`, correct: false, explanation: `La composante sigma reste indispensable.` },
    ],
    explanation: `Une double liaison associe toujours une première composante $\\sigma$ et une seconde composante $\\pi$.`,
  },
  {
    order: 8,
    difficulty: 'EASY',
    format: 'QROC',
    question: `Le peroxyde d'hydrogène $\\ce{H-O-O-H}$ ne comporte que des liaisons simples. Combien possède-t-il de liaisons $\\sigma$ ?`,
    answer: { type: 'number', value: 3, tolerance: 0 },
    explanation: `Les deux liaisons O–H et la liaison O–O sont simples : elles sont toutes les trois de type $\\sigma$.`,
  },
  {
    order: 9,
    difficulty: 'EASY',
    format: 'QRU',
    question: `À propos de la liaison simple $\\ce{H-Cl}$ dans le chlorure d'hydrogène gazeux, quelle proposition est correcte ?`,
    choices: [
      { content: `Elle peut être décrite par un recouvrement axial $\\mathrm{s-p}$ et est de type $\\sigma$.`, correct: true, explanation: `L'orbitale 1s de H peut recouvrir axialement une orbitale p du chlore.` },
      { content: `Elle comporte obligatoirement une liaison $\\pi$.`, correct: false, explanation: `Une liaison simple est une liaison sigma.` },
      { content: `Elle résulte d'un recouvrement latéral de deux orbitales p.`, correct: false, explanation: `Ce serait une liaison pi.` },
      { content: `Elle ne peut pas être décrite par un modèle orbitalaire.`, correct: false, explanation: `Le recouvrement d'orbitales atomiques permet justement de la décrire.` },
    ],
    explanation: `Une liaison simple H–Cl peut être décrite comme une liaison $\\sigma$ issue d'un recouvrement axial s–p.`,
  },
  {
    order: 10,
    difficulty: 'EASY',
    format: 'QROC',
    question: `Dans une triple liaison, combien de liaisons $\\pi$ sont présentes ?`,
    answer: { type: 'number', value: 2, tolerance: 0 },
    explanation: `Une triple liaison comporte une liaison $\\sigma$ et deux liaisons $\\pi$.`,
  },
];

export const UE14_CH3_OM_PRACTICE_V2_QUESTIONS: HealthTrainingAuthorQuestion[] = [
  {
    order: 11,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Le cyanure d'hydrogène, $\\ce{H-C#N}$, comporte une liaison simple et une liaison triple. Combien possède-t-il au total de liaisons $\\sigma$ ?`,
    answer: { type: 'number', value: 2, tolerance: 0 },
    explanation: `La liaison H–C apporte une sigma et la liaison triple C≡N comporte une sigma et deux pi : on compte donc deux liaisons sigma au total.`,
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `L'urée $\\ce{O=C(NH2)2}$ est le principal déchet azoté éliminé dans les urines. Sa formule développée comporte une liaison $\\ce{C=O}$, deux liaisons $\\ce{C-N}$ et quatre liaisons $\\ce{N-H}$. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Une molécule d'urée comporte 7 liaisons $\\sigma$.`, correct: true, explanation: `Six liaisons simples et la composante sigma du carbonyle.` },
      { content: `Une molécule d'urée comporte 1 liaison $\\pi$.`, correct: true, explanation: `Le carbonyle apporte une composante pi.` },
      { content: `$0{,}10\\,\\mathrm{mol}$ d'urée correspondent à $0{,}70\\,\\mathrm{mol}$ de liaisons $\\sigma$.`, correct: true, explanation: `7 × 0,10 = 0,70 mol.` },
      { content: `La double liaison $\\ce{C=O}$ contient deux liaisons $\\sigma$.`, correct: false, explanation: `Elle contient une sigma et une pi.` },
    ],
    explanation: `L'urée comporte 7 liaisons sigma et 1 liaison pi par molécule ; les quantités de matière de liaisons se déduisent par proportionnalité.`,
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Le méthanamide $\\ce{H-C(=O)-NH2}$ possède un carbonyle. Sélectionnez exactement les deux propositions correctes.`,
    choices: [
      { content: `Il comporte 5 liaisons $\\sigma$ et 1 liaison $\\pi$.`, correct: true, explanation: `Quatre liaisons simples + sigma du carbonyle ; une pi du carbonyle.` },
      { content: `La composante $\\pi$ du carbonyle résulte d'un recouvrement latéral d'orbitales $\\mathrm{p}$.`, correct: true, explanation: `C'est l'origine de la liaison pi.` },
      { content: `La double liaison $\\ce{C=O}$ autorise une rotation libre autour de l'axe C–O.`, correct: false, explanation: `La composante pi s'oppose à cette rotation.` },
      { content: `Le carbonyle comporte deux liaisons $\\sigma$.`, correct: false, explanation: `Il comporte une sigma et une pi.` },
    ],
    explanation: `Le méthanamide illustre simultanément le décompte des liaisons et la limitation de rotation liée à la composante pi du carbonyle.`,
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `On retient l'ordre énergétique simplifié $E(\\sigma)<E(\\mathrm{OA})<E(\\sigma^*)$. Sélectionnez exactement les deux propositions correctes.`,
    choices: [
      { content: `Deux orbitales atomiques donnent deux orbitales moléculaires.`, correct: true, explanation: `Le nombre de fonctions orbitalaires est conservé.` },
      { content: `L'orbitale $\\sigma$ liante est stabilisée par rapport aux orbitales atomiques initiales.`, correct: true, explanation: `Son énergie est plus basse.` },
      { content: `$\\sigma^*$ est une orbitale atomique antiliante.`, correct: false, explanation: `C'est une orbitale moléculaire antiliante.` },
      { content: `$\\sigma^*$ est plus stable que $\\sigma$.`, correct: false, explanation: `Son énergie est plus élevée.` },
    ],
    explanation: `La combinaison de deux OA produit une OM liante plus basse en énergie et une OM antiliante plus haute en énergie.`,
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `Les deux profils ci-dessous représentent la densité électronique $\\rho(x)$ le long de l'axe internucléaire. Le point $x=0$ est situé entre les noyaux.\n\n![Profils de densité électronique liante et antiliante](/images/training/ue14/orbitales-moleculaires/profils-densite-electronique-sigma.png)`,
    choices: [
      { content: `Le profil A est compatible avec une orbitale moléculaire liante.`, correct: true, explanation: `La densité internucléaire y est élevée.` },
      { content: `Le profil B est compatible avec une orbitale moléculaire antiliante.`, correct: true, explanation: `Il présente un nœud entre les noyaux.` },
      { content: `$\\rho_B(0)=0$ traduit un nœud internucléaire.`, correct: true, explanation: `Un nœud correspond à une densité nulle.` },
      { content: `Le profil B est nécessairement plus stable que A.`, correct: false, explanation: `Le nœud internucléaire est associé à un caractère antiliant.` },
    ],
    explanation: `Une OM liante concentre la densité entre les noyaux ; une OM antiliante présente un nœud dans cette région.`,
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `Les schémas suivants montrent deux orientations de deux orbitales atomiques $\\mathrm{p}$ avant combinaison.\n\n![Recouvrements axial et latéral de deux orbitales p](/images/training/ue14/orbitales-moleculaires/recouvrements-orbitales-p.png)`,
    choices: [
      { content: `Un face-à-face selon l'axe internucléaire peut conduire à une liaison $\\sigma$.`, correct: true, explanation: `C'est un recouvrement axial p–p.` },
      { content: `Deux orbitales p parallèles peuvent former une liaison $\\pi$ par recouvrement latéral.`, correct: true, explanation: `C'est le principe d'une liaison pi.` },
      { content: `Les lobes dessinés avant combinaison sont déjà des orbitales moléculaires $\\sigma^*$.`, correct: false, explanation: `Il s'agit encore d'orbitales atomiques.` },
      { content: `Le parallélisme des orbitales p doit être conservé pour maintenir une liaison $\\pi$.`, correct: true, explanation: `Une rotation diminue le recouvrement latéral.` },
    ],
    explanation: `L'orientation relative des orbitales p détermine la nature du recouvrement : axial pour sigma, latéral pour pi.`,
  },
  {
    order: 17,
    difficulty: 'MEDIUM',
    format: 'QRU',
    question: `La double liaison $\\ce{O=O}$ du dioxygène impose quelle conséquence géométrique dans le modèle orbitalaire simplifié ?`,
    choices: [
      { content: `La composante $\\pi$ limite la rotation car les orbitales $\\mathrm{p}$ doivent rester parallèles.`, correct: true, explanation: `La rotation désalignerait les orbitales p.` },
      { content: `La composante $\\sigma$ interdit toute rotation à elle seule.`, correct: false, explanation: `La symétrie axiale de sigma autorise la rotation.` },
      { content: `La double liaison contient deux orbitales sigma indépendantes.`, correct: false, explanation: `Elle associe sigma et pi.` },
      { content: `La liaison pi est plus stable que la liaison sigma correspondante.`, correct: false, explanation: `Le recouvrement latéral est moins efficace.` },
    ],
    explanation: `C'est la composante pi d'une double liaison qui impose l'alignement des orbitales p et limite la rotation.`,
  },
  {
    order: 18,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Le diazote $\\ce{N#N}$ possède une triple liaison. Combien de liaisons $\\sigma$ et $\\pi$ contient-il au total ? Saisissez le nombre total de composantes de liaison.`,
    answer: { type: 'number', value: 3, tolerance: 0 },
    explanation: `La triple liaison est constituée d'une liaison sigma et de deux liaisons pi, soit trois composantes de liaison.`,
  },
  {
    order: 19,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Le dioxyde de carbone $\\ce{O=C=O}$ comporte deux doubles liaisons. Combien possède-t-il de liaisons $\\pi$ ?`,
    answer: { type: 'number', value: 2, tolerance: 0 },
    explanation: `Chaque double liaison apporte une liaison pi : deux doubles liaisons donnent donc deux liaisons pi.`,
  },
  {
    order: 20,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `On compare $\\ce{HCN}$, l'urée $\\ce{O=C(NH2)2}$ et le méthanamide $\\ce{H-C(=O)-NH2}$. Quelles propositions sont exactes ?`,
    choices: [
      { content: `$\\ce{HCN}$ possède deux liaisons $\\pi$.`, correct: true, explanation: `La triple liaison C≡N contient deux pi.` },
      { content: `L'urée et le méthanamide possèdent chacun un carbonyle et donc une composante $\\pi$.`, correct: true, explanation: `Chaque carbonyle contient une liaison pi.` },
      { content: `L'urée possède davantage de liaisons $\\sigma$ que le méthanamide.`, correct: true, explanation: `7 sigma contre 5.` },
      { content: `Les trois molécules ne contiennent aucune liaison $\\sigma$.`, correct: false, explanation: `Toutes comportent des liaisons sigma.` },
    ],
    explanation: `Le décompte sigma/pi permet de comparer des molécules de structures très différentes avec la même logique orbitale.`,
  },
  {
    order: 81,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Sélectionnez exactement les deux espèces comportant deux liaisons $\\pi$ dans les représentations simplifiées proposées.`,
    choices: [
      { content: `$\\ce{N2}$.`, correct: true, explanation: `La triple liaison comporte deux pi.` },
      { content: `$\\ce{CO2}$.`, correct: true, explanation: `Chaque double liaison C=O apporte une pi.` },
      { content: `$\\ce{H2O2}$.`, correct: false, explanation: `Cette molécule ne comporte que des liaisons simples.` },
      { content: `$\\ce{HCl}$.`, correct: false, explanation: `La liaison H–Cl est une liaison simple sigma.` },
    ],
    explanation: `$\\ce{N2}$ et $\\ce{CO2}$ comportent chacun deux composantes pi, bien que leurs structures soient différentes.`,
  },
  {
    order: 82,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Une molécule contient trois doubles liaisons et aucune triple liaison. Combien de liaisons $\\pi$ comporte-t-elle ?`,
    answer: { type: 'number', value: 3, tolerance: 0 },
    explanation: `Chaque double liaison apporte une seule liaison pi : trois doubles liaisons correspondent donc à trois liaisons pi.`,
  },
];
