/**
 * UE14 – Biologie cellulaire – Chapitre 4
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_B_QUESTIONS: SeedQuestion[] = [
  {
    order: 31,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le transport vésiculaire nécessite toujours :`,
    choices: [
      `Des facteurs cytosoliques.`,
      `Des protéines du cytosquelette.`,
      `Du GTP.`,
      `L’absence de protéines membranaires.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cours associe facteurs cytosoliques, cytosquelette et GTP au transport vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 32,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le transport vésiculaire comporte quatre étapes :`,
    choices: [
      `Bourgeonnement.`,
      `Perte du revêtement.`,
      `Transport dans le cytosol.`,
      `Amarrage et fusion.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Ces quatre étapes constituent la séquence générale du transport vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 33,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Lors du bourgeonnement, le revêtement peut comporter :`,
    choices: [
      `Clathrine et adaptines.`,
      `Cavéoline.`,
      `ARF-FAPP.`,
      `Des histones.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les histones ne sont pas un revêtement vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 34,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le bourgeonnement vésiculaire est associé dans la fiche :`,
    choices: [
      `À du GTP.`,
      `À la formation d’un revêtement protéique.`,
      `À une courbure de membrane.`,
      `À une perte préalable de toute membrane.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le bourgeonnement déforme une membrane et forme une vésicule revêtue.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 35,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Après le bourgeonnement, la vésicule doit :`,
    choices: [
      `Perdre son revêtement pour devenir lisse.`,
      `Conserver obligatoirement sa cage pendant tout le trajet.`,
      `Fusionner immédiatement avec le noyau.`,
      `Détruire son contenu.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La perte du revêtement précède le transport dans le cytosol.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 36,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le transport cytosolique de la vésicule :`,
    choices: [
      `Suit la perte du revêtement.`,
      `Met en jeu le cytosquelette.`,
      `Conduit vers un compartiment receveur.`,
      `Exclut toute dépense énergétique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le déplacement vésiculaire implique des facteurs et de l’énergie.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 37,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L’amarrage et la fusion permettent :`,
    choices: [
      `La reconnaissance du compartiment receveur.`,
      `La fixation de la vésicule.`,
      `Le déversement du contenu protéique.`,
      `La conservation définitive de la vésicule comme compartiment indépendant.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fusion intègre la membrane vésiculaire au compartiment receveur.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 38,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les revêtements vésiculaires :`,
    choices: [
      `Participent au bourgeonnement.`,
      `Sont perdus avant le transport.`,
      `Peuvent être de natures différentes.`,
      `Sont constitués uniquement de phospholipides.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche décrit des revêtements protéiques variés.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 39,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Clathrine et adaptines sont associées :`,
    choices: [
      `À la formation de certaines vésicules.`,
      `À un revêtement protéique.`,
      `Au bourgeonnement.`,
      `À la synthèse de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Clathrine et adaptines interviennent dans la formation de vésicules.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 40,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La cavéoline et ARF-FAPP :`,
    choices: [
      `Peuvent participer à des revêtements vésiculaires.`,
      `Sont citées dans le transport vésiculaire.`,
      `Sont des histones nucléaires.`,
      `Peuvent être associées à des voies d’exocytose constitutive.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La fiche relie cavéoline et ARF-FAPP à des vésicules du trafic membranaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 41,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure suivante.

![Transport vésiculaire en quatre étapes](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-1/transport-vesiculaire-quatre-etapes.png)

Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `La vésicule est d’abord revêtue.`,
      `Elle perd son revêtement avant le transport.`,
      `Le cytosquelette participe au déplacement.`,
      `La fusion précède le bourgeonnement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La figure suit l’ordre bourgeonnement → déshabillage → transport → fusion.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 42,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une vésicule restant recouverte de clathrine pendant tout son trajet serait en contradiction avec :`,
    choices: [
      `La nécessité du déshabillage.`,
      `La formation d’une vésicule lisse.`,
      `L’étape de transport cytosolique décrite.`,
      `L’existence d’un bourgeonnement initial.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La perte du revêtement est nécessaire après le bourgeonnement.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 43,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un défaut du cytosquelette peut perturber :`,
    choices: [
      `Le déplacement des vésicules.`,
      `L’acheminement vers le compartiment cible.`,
      `La dynamique des flux membranaires.`,
      `La présence d’une lumière dans les cavités.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cytosquelette est surtout requis pour les mouvements vésiculaires.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 44,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un défaut des protéines d’amarrage ou de fusion peut entraîner :`,
    choices: [
      `Une difficulté à reconnaître le compartiment receveur.`,
      `Une accumulation de vésicules non fusionnées.`,
      `Un défaut de déversement du contenu.`,
      `Une augmentation automatique de la transcription nucléaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’amarrage et la fusion sont les dernières étapes du transport vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 45,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le GTP intervient :`,
    choices: [
      `Au cours du bourgeonnement.`,
      `Avec certains facteurs cytosoliques.`,
      `Dans la formation des flux.`,
      `Comme unique constituant du revêtement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le GTP fournit de l’énergie mais n’est pas le matériau du revêtement.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 46,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le matériel transporté par une vésicule peut être :`,
    choices: [
      `Dans la membrane vésiculaire.`,
      `Dans la lumière vésiculaire.`,
      `Un agent pathogène internalisé.`,
      `Uniquement une protéine soluble.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La diversité du contenu vésiculaire est explicitement soulignée.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 47,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Un revêtement de clathrine + adaptines :`,
    choices: [
      `Organise la courbure et le bourgeonnement.`,
      `Est transitoire.`,
      `Doit être retiré pour le transport.`,
      `Constitue le contenu luminal de la vésicule.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le revêtement est externe et transitoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 48,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le passage d’une vésicule revêtue à une vésicule lisse :`,
    choices: [
      `Correspond au déshabillage.`,
      `Précède le déplacement cytosolique.`,
      `Permet un transport plus adapté.`,
      `Détruit nécessairement les signaux d’adressage de la cargaison.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le déshabillage ne signifie pas la destruction des signaux d’adressage.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 49,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le compartiment receveur :`,
    choices: [
      `Est la destination de la vésicule.`,
      `Fusionne avec la vésicule après amarrage.`,
      `Reçoit le contenu luminal ou membranaire.`,
      `Est toujours la membrane plasmique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Selon le flux, différents compartiments peuvent être receveurs.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 50,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le transport vésiculaire relie la structure et la fonction car :`,
    choices: [
      `Le revêtement forme la vésicule.`,
      `Le cytosquelette assure son déplacement.`,
      `L’amarrage assure la spécificité de destination.`,
      `La fusion permet la livraison de la cargaison.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Chaque étape contribue à la réussite du transport.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 51,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation empêche la perte du revêtement d’une vésicule. On peut prévoir :`,
    choices: [
      `Un défaut de transport cytosolique.`,
      `Une difficulté d’amarrage.`,
      `Une accumulation de vésicules revêtues.`,
      `Une disparition du SEM entier.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le défaut concerne surtout la progression du transport vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 52,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une mutation bloque l’amarrage mais pas le bourgeonnement. On peut observer :`,
    choices: [
      `Des vésicules formées.`,
      `Des vésicules transportées mais non fusionnées.`,
      `Un défaut de livraison de la cargaison.`,
      `Une absence totale de membrane plasmique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le blocage terminal entraîne une accumulation avant fusion.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 53,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un inhibiteur du GTP peut perturber :`,
    choices: [
      `La formation de certains bourgeons.`,
      `La dynamique de flux.`,
      `Le détachement de certaines vésicules.`,
      `La présence du cholestérol dans le cytosol uniquement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le GTP participe à plusieurs étapes du trafic vésiculaire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 54,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La présence de signaux d’adressage sur une cargaison est cohérente avec :`,
    choices: [
      `La nécessité de sélectionner une destination.`,
      `La coexistence de plusieurs flux.`,
      `La spécificité d’un compartiment receveur.`,
      `Un transport totalement aléatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les signaux s’opposent à un transport aléatoire.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 55,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une vésicule transportant une protéine transmembranaire et une protéine soluble peut :`,
    choices: [
      `Porter la première dans sa membrane.`,
      `Contenir la seconde dans sa lumière.`,
      `Acheminer les deux vers un même compartiment.`,
      `Transformer les deux en protéines cytosoliques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le transport vésiculaire conserve la séparation membrane/lumière.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 56,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À partir de la figure des quatre étapes :

![Transport vésiculaire en quatre étapes](/images/training/ue14/biologie-cellulaire/systeme-endomembranaire-1/transport-vesiculaire-quatre-etapes.png)

Quelle(s) proposition(s) est(sont) exacte(s) ?`,
    choices: [
      `Le revêtement est associé au bourgeonnement.`,
      `La vésicule lisse se déplace dans le cytosol.`,
      `La fusion intervient à la fin.`,
      `Le transport se fait sans cytosquelette.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le cytosquelette est explicitement requis.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 57,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les couples étape–fonction, lesquels sont corrects ?`,
    choices: [
      `Bourgeonnement — formation de la vésicule.`,
      `Déshabillage — perte du revêtement.`,
      `Transport — déplacement cytosolique.`,
      `Fusion — livraison du contenu.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les quatre couples correspondent à la séquence de la fiche.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 58,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un défaut de revêtement peut affecter :`,
    choices: [
      `La sélection de la cargaison.`,
      `La courbure de la membrane.`,
      `La formation de la vésicule.`,
      `Uniquement la réplication de l’ADN.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le revêtement participe au tri et à la formation du bourgeon.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
  {
    order: 59,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le trafic vésiculaire illustre une coopération entre :`,
    choices: [
      `Membranes.`,
      `Protéines cytosoliques.`,
      `Cytosquelette.`,
      `Nucléotides énergétiques comme le GTP.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Le processus combine structures membranaires et facteurs cytosoliques énergétiques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
    ],
  },
  {
    order: 60,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est correcte ?`,
    choices: [
      `Le transport vésiculaire est ordonné en quatre étapes.`,
      `Le revêtement est transitoire.`,
      `L’amarrage et la fusion déterminent la livraison.`,
      `Les vésicules se déplacent sans aucune aide cellulaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le déplacement dépend notamment du cytosquelette et de facteurs cytosoliques.`,
    choiceExplanations: [
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Exact : conforme aux éléments de la fiche.`,
      `Faux : contredit ou dépasse les éléments de la fiche.`,
    ],
  },
];

export const SECTION_B_QUIZZES: SeedQuiz[] = [
  {
    order: 4,
    slug: `etapes-transport-vesiculaire`,
    title: `Étapes du transport vésiculaire`,
    description: `Bourgeonnement, déshabillage, transport, amarrage et fusion.`,
    stage: 'DISCOVER',
    sectionOrder: 2,
    questionOrders: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  {
    order: 5,
    slug: `revetements-et-cytosquelette`,
    title: `Revêtements et cytosquelette`,
    description: `Clathrine, adaptines, cavéoline, ARF-FAPP et facteurs du transport.`,
    stage: 'PRACTICE',
    sectionOrder: 2,
    questionOrders: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  {
    order: 6,
    slug: `raisonnement-transport-vesiculaire`,
    title: `Raisonnement sur le transport vésiculaire`,
    description: `Conséquences de défauts de revêtement, de déplacement, d’amarrage et de fusion.`,
    stage: 'MASTER',
    sectionOrder: 2,
    questionOrders: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
];
