import type { SeedQuestion, SeedQuiz } from './health-training-ue13.shared';

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 61,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La technique cytologique permet principalement :",
    choices: [
      "D’étudier des cellules.",
      "De préparer des cellules présentes dans un liquide.",
      "D’observer ensuite ces cellules au microscope.",
      "D’analyser uniquement l’architecture complète d’un organe.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La cytologie s’intéresse aux cellules isolées ou dispersées, et non à l’organisation complète d’un tissu.",
    choiceExplanations: [
      "C’est l’objectif principal.",
      "Le cours décrit des cellules déposées à partir d’un liquide.",
      "L’observation microscopique clôt la préparation.",
      "L’architecture tissulaire relève surtout de l’histologie.",
    ],
  },
  {
    order: 62,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Les grandes étapes de la technique cytologique citées dans le cours sont :",
    choices: [
      "Fixation.",
      "Création de la lame.",
      "Analyse au microscope.",
      "Inclusion systématique dans un bloc de paraffine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La séquence cytologique est plus courte que la chaîne histologique décrite.",
    choiceExplanations: [
      "La fixation est indiquée.",
      "La lame doit ensuite être préparée.",
      "L’analyse microscopique constitue l’étape finale.",
      "L’inclusion en paraffine n’est pas donnée comme étape systématique de cette technique.",
    ],
  },
  {
    order: 63,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Parmi les prélèvements pouvant être étudiés en cytologie :",
    choices: [
      "Les urines.",
      "Les ponctions d’organes, de kystes ou de ganglions.",
      "Les frottis.",
      "Les cellules en culture.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Le cours cite ces quatre grandes sources de cellules pour l’analyse cytologique.",
    choiceExplanations: [
      "Les urines sont citées.",
      "Les ponctions sont citées.",
      "Les frottis sont cités.",
      "Les cultures cellulaires sont citées.",
    ],
  },
  {
    order: 64,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Un frottis cytologique :",
    choices: [
      "Repose sur un prélèvement par frottement.",
      "Peut être utilisé au niveau cervico-utérin.",
      "Peut contribuer au dépistage du cancer du col de l’utérus.",
      "Nécessite toujours une pièce opératoire entière.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le frottis cervico-utérin est l’exemple clinique donné dans le cours.",
    choiceExplanations: [
      "C’est le principe du frottis.",
      "Cette localisation est citée.",
      "Cette finalité de dépistage est citée.",
      "Un frottis ne repose pas sur l’étude d’une pièce entière.",
    ],
  },
  {
    order: 65,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La filtration d’un prélèvement cytologique permet :",
    choices: [
      "De sélectionner les cellules à observer.",
      "De retenir certains éléments sur des filtres.",
      "De préparer une lame à partir d’un liquide.",
      "De couper les cellules en tranches de 4 µm.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La filtration est l’une des méthodes permettant de concentrer ou sélectionner les cellules d’un prélèvement liquide.",
    choiceExplanations: [
      "C’est l’objectif décrit.",
      "Les éléments non retenus pour l’observation peuvent rester sur le filtre.",
      "La technique s’applique à des prélèvements liquides.",
      "Les cellules cytologiques sont déposées, non coupées.",
    ],
  },
  {
    order: 66,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Lors d’un étalement cytologique :",
    choices: [
      "Une goutte de prélèvement est placée entre deux lames.",
      "Le prélèvement est réparti pour être analysé.",
      "Le sang constitue un exemple d’application.",
      "Un bloc de paraffine est obligatoirement fabriqué avant l’étalement.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "L’étalement répartit directement une goutte de prélèvement, comme pour un frottis sanguin.",
    choiceExplanations: [
      "Cette manipulation est décrite.",
      "L’étalement facilite l’observation cellulaire.",
      "Le sang est l’exemple donné.",
      "Cette étape ne nécessite pas systématiquement de bloc de paraffine.",
    ],
  },
  {
    order: 67,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La centrifugation en cytologie :",
    choices: [
      "Permet d’obtenir un culot de cellules.",
      "Concentre les cellules avant leur observation.",
      "Peut être utilisée pour préparer un prélèvement liquide.",
      "Remplace nécessairement toute coloration.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La centrifugation concentre les cellules sous forme de culot, qui sera ensuite préparé et observé.",
    choiceExplanations: [
      "Le culot est le résultat indiqué.",
      "La concentration facilite la récupération des cellules.",
      "La méthode est adaptée aux liquides.",
      "Les lames sont ensuite colorées pour distinguer les cellules.",
    ],
  },
  {
    order: 68,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Sur une lame de cytologie :",
    choices: [
      "Les cellules sont déposées sur la lame.",
      "Les cellules ne sont pas coupées comme dans une coupe histologique.",
      "Une coloration aide à distinguer les types cellulaires.",
      "L’organisation tridimensionnelle complète du tissu est toujours conservée.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La cytologie montre des cellules déposées, avec une information architecturale plus limitée que l’histologie.",
    choiceExplanations: [
      "C’est le principe de la préparation.",
      "Cette différence est explicitement mentionnée.",
      "La coloration facilite l’identification.",
      "Le dépôt de cellules ne conserve pas nécessairement l’architecture tissulaire complète.",
    ],
  },
  {
    order: 69,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "La coloration HES est moins adaptée à la cytologie décrite dans le cours parce que :",
    choices: [
      "Le safran colore le milieu extracellulaire.",
      "Le milieu extracellulaire n’est pas présent comme dans une coupe tissulaire.",
      "Un colorant nucléaire reste nécessaire.",
      "Aucun colorant cytoplasmique ne peut jamais être utilisé.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "En cytologie, on privilégie un contraste nucléaire et cytoplasmique sans intérêt particulier pour le safran.",
    choiceExplanations: [
      "Le rôle du safran explique sa moindre utilité.",
      "Les cellules sont déposées sans la matrice tissulaire habituelle.",
      "L’hématoxyline conserve son intérêt pour le noyau.",
      "Un colorant cytoplasmique est au contraire utilisé, mais il peut varier.",
    ],
  },
  {
    order: 70,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: "Dans la coloration cytologique décrite :",
    choices: [
      "L’hématoxyline reste le colorant nucléaire.",
      "Le colorant cytoplasmique peut varier selon ce que l’on souhaite observer.",
      "Le safran est indispensable dans tous les cas.",
      "Le contraste doit permettre de distinguer les types cellulaires.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "La stratégie associe un colorant nucléaire constant et un colorant cytoplasmique adapté.",
    choiceExplanations: [
      "L’hématoxyline est conservée.",
      "Le choix cytoplasmique dépend de l’objectif.",
      "Le safran n’a pas d’intérêt majeur ici selon le cours.",
      "C’est la finalité de la coloration.",
    ],
  },
  {
    order: 71,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Comparer histologie et cytologie :",
    choices: [
      "L’histologie étudie l’organisation des cellules au sein d’un tissu.",
      "La cytologie étudie des cellules déposées sur une lame.",
      "La cytologie conserve toujours toute la matrice extracellulaire du tissu d’origine.",
      "Les deux approches utilisent une observation microscopique.",
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: "L’histologie privilégie l’architecture tissulaire ; la cytologie privilégie l’étude des cellules.",
    choiceExplanations: [
      "Cette distinction est fondamentale.",
      "C’est le mode de préparation cytologique.",
      "Le milieu extracellulaire est justement absent ou très limité.",
      "Le microscope intervient dans les deux approches.",
    ],
  },
  {
    order: 72,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un laboratoire reçoit un échantillon d’urines pour rechercher des cellules anormales. D’après le cours :",
    choices: [
      "Une préparation cytologique est adaptée.",
      "Une filtration ou une centrifugation peut être envisagée.",
      "Les cellules pourront être déposées puis colorées sur une lame.",
      "Une pièce opératoire doit obligatoirement être obtenue avant toute analyse.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les urines sont un exemple de liquide pouvant fournir des cellules pour la cytologie.",
    choiceExplanations: [
      "Le type de prélèvement figure dans la liste du cours.",
      "Ces méthodes permettent de récupérer les cellules d’un liquide.",
      "La préparation de la lame suit cette récupération.",
      "La cytologie ne nécessite pas nécessairement de pièce opératoire.",
    ],
  },
  {
    order: 73,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Pour préparer un frottis sanguin :",
    choices: [
      "L’étalement d’une goutte entre deux lames est compatible avec le cours.",
      "Les cellules seront observées sans être coupées en tranches.",
      "Une coloration permettra de distinguer les types cellulaires.",
      "Une inclusion nocturne en paraffine est obligatoire.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le sang illustre la méthode d’étalement cytologique.",
    choiceExplanations: [
      "C’est l’exemple d’étalement donné.",
      "La cytologie dépose les cellules intactes.",
      "Le contraste coloré aide à l’identification.",
      "Cette inclusion n’est pas une étape systématique du frottis.",
    ],
  },
  {
    order: 74,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une ponction ganglionnaire fournit un liquide contenant peu de cellules. Pour préparer la lame :",
    choices: [
      "Une centrifugation peut permettre d’obtenir un culot.",
      "Une filtration peut contribuer à récupérer les cellules.",
      "Les cellules récupérées peuvent être fixées et colorées.",
      "La seule méthode possible consiste à découper un bloc à 4 µm.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Plusieurs méthodes cytologiques peuvent être utilisées pour concentrer les cellules d’un prélèvement liquide.",
    choiceExplanations: [
      "La centrifugation est adaptée à la concentration cellulaire.",
      "La filtration est également citée.",
      "Fixation et coloration préparent l’observation.",
      "La coupe à 4 µm appartient à la technique histologique en paraffine.",
    ],
  },
  {
    order: 75,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Des cellules cultivées in vitro doivent être observées au microscope. Selon le chapitre :",
    choices: [
      "Les cellules en culture peuvent être étudiées en cytologie.",
      "Elles peuvent être déposées sur une lame.",
      "Une coloration nucléaire et cytoplasmique peut être utilisée.",
      "Elles doivent obligatoirement être réassemblées en organe avant l’analyse.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Les cellules en culture font partie des supports cytologiques cités.",
    choiceExplanations: [
      "Ce type de prélèvement figure dans le cours.",
      "Le dépôt sur lame est compatible avec la technique.",
      "Le contraste facilite l’analyse.",
      "Aucune reconstruction d’organe n’est requise.",
    ],
  },
  {
    order: 76,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Après centrifugation d’un prélèvement liquide, le technicien observe un dépôt compact au fond du tube. Il s’agit :",
    choices: [
      "D’un culot cellulaire.",
      "D’un résultat attendu de la centrifugation.",
      "D’un matériel pouvant être transféré sur une lame.",
      "D’un bloc de paraffine déjà prêt pour le microtome.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le culot concentre les cellules récupérées dans le liquide.",
    choiceExplanations: [
      "Le terme est celui utilisé dans le cours.",
      "La centrifugation produit ce dépôt.",
      "Le culot doit ensuite être préparé pour l’observation.",
      "Il ne s’agit pas d’un bloc inclus en paraffine.",
    ],
  },
  {
    order: 77,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Un frottis cervico-utérin est réalisé dans un contexte de dépistage. Cette situation illustre :",
    choices: [
      "Un prélèvement par frottement.",
      "Une analyse cytologique.",
      "L’étude de cellules déposées sur une lame.",
      "L’observation obligatoire d’une coupe complète de la paroi utérine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "Le frottis cervico-utérin est l’exemple clinique emblématique de cytologie donné dans le cours.",
    choiceExplanations: [
      "Le prélèvement est obtenu par frottement.",
      "La technique porte sur des cellules.",
      "Les cellules sont préparées sur une lame.",
      "Une coupe complète n’est pas nécessaire à ce type d’examen.",
    ],
  },
  {
    order: 78,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "L’information fournie par une lame de cytologie porte surtout sur :",
    choices: [
      "La morphologie des cellules présentes.",
      "La diversité des types cellulaires.",
      "Les contrastes nucléaires et cytoplasmiques.",
      "L’architecture topographique complète de tout le tissu d’origine.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La cytologie fournit une analyse cellulaire, mais une information plus limitée sur l’architecture tissulaire.",
    choiceExplanations: [
      "La forme cellulaire peut être étudiée.",
      "La coloration aide à distinguer les populations.",
      "Ces deux compartiments sont spécifiquement colorés.",
      "Cette architecture complète relève davantage d’une coupe histologique.",
    ],
  },
  {
    order: 79,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Parmi les affirmations suivantes sur les lames cytologiques :",
    choices: [
      "Elles peuvent provenir d’un frottis, d’une ponction ou d’un liquide biologique.",
      "Les cellules sont généralement préparées puis déposées sur le support.",
      "L’hématoxyline peut être utilisée pour le noyau.",
      "Le safran est choisi avant tout pour colorer une matrice extracellulaire abondante sur la lame.",
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: "La préparation cytologique recherche surtout le contraste cellulaire, et non celui d’une matrice tissulaire abondante.",
    choiceExplanations: [
      "Ces origines sont citées.",
      "C’est le principe général.",
      "Le colorant nucléaire reste l’hématoxyline.",
      "Le faible intérêt du safran est précisément lié à l’absence de milieu extracellulaire.",
    ],
  },
  {
    order: 80,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: "Une chaîne cytologique cohérente peut comprendre :",
    choices: [
      "Recueil d’un liquide ou réalisation d’un frottis.",
      "Récupération des cellules par filtration, étalement ou centrifugation.",
      "Fixation et coloration de la lame.",
      "Analyse microscopique des cellules.",
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: "Ces étapes résument la préparation cytologique décrite dans le chapitre.",
    choiceExplanations: [
      "Le prélèvement constitue le point de départ.",
      "Ces trois méthodes sont celles présentées.",
      "La lame doit être préparée et contrastée.",
      "L’observation microscopique constitue la finalité.",
    ],
  },
];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 7,
    slug: "principes-cytologie",
    title: "Principes de la cytologie",
    description: "Objectifs, prélèvements, préparation des cellules et coloration des lames cytologiques.",
    stage: 'DISCOVER',
    sectionOrder: 4,
    questionOrders: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  {
    order: 8,
    slug: "prelevements-preparation-lames-cytologiques",
    title: "Prélèvements et préparation des lames cytologiques",
    description: "Applications aux urines, frottis, ponctions et cultures cellulaires, avec comparaison à l’histologie.",
    stage: 'PRACTICE',
    sectionOrder: 4,
    questionOrders: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
];
