/** UE14 – Biologie cellulaire – Chapitre 7 — V2 active */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-mitochondrie.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-mitochondrie.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-mitochondrie.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-mitochondrie.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-mitochondrie.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';
const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'mitochondrie';
const sections: SeedSection[] = [
  { order: 1, title: `Structure, import et génome`, description: `Organisation, membranes, systèmes TOM/TIM/SAM et ADN mitochondrial.`, kind: 'THEME' },
  { order: 2, title: `Métabolismes et chaîne respiratoire`, description: `Acétyl-CoA, cycle de Krebs, navettes et complexes respiratoires.`, kind: 'THEME' },
  { order: 3, title: `Phosphorylation oxydative`, description: `Gradient protonique, ATP synthase, rendement et inhibiteurs.`, kind: 'THEME' },
  { order: 4, title: `Autres fonctions et pathologies`, description: `Stéroïdogenèse, apoptose, thermogenèse, ROS et cytopathies.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Révision transversale de la mitochondrie.`, kind: 'SYNTHESIS' },
];
const questions: SeedQuestion[] = [...SECTION_A_QUESTIONS, ...SECTION_B_QUESTIONS, ...SECTION_C_QUESTIONS, ...SECTION_D_QUESTIONS, ...SYNTHESIS_QUESTIONS];
const quizSeeds: SeedQuiz[] = [...SECTION_A_QUIZZES, ...SECTION_B_QUIZZES, ...SECTION_C_QUIZZES, ...SECTION_D_QUIZZES, ...SYNTHESIS_QUIZZES];
const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: [`Structure, import et génome`],
  2: [`Structure, import et génome`],
  3: [`Structure, import et génome`],
  4: [`Structure, import et génome`],
  5: [`Structure, import et génome`],
  6: [`Structure, import et génome`],
  7: [`Structure, import et génome`],
  8: [`Structure, import et génome`],
  9: [`Structure, import et génome`],
  10: [`Structure, import et génome`],
  11: [`Structure, import et génome`],
  12: [`Structure, import et génome`],
  13: [`Structure, import et génome`],
  14: [`Structure, import et génome`],
  15: [`Structure, import et génome`],
  16: [`Structure, import et génome`],
  17: [`Structure, import et génome`],
  18: [`Structure, import et génome`],
  19: [`Structure, import et génome`],
  20: [`Structure, import et génome`],
  21: [`Structure, import et génome`],
  22: [`Structure, import et génome`],
  23: [`Métabolismes et chaîne respiratoire`],
  24: [`Métabolismes et chaîne respiratoire`],
  25: [`Métabolismes et chaîne respiratoire`],
  26: [`Métabolismes et chaîne respiratoire`],
  27: [`Métabolismes et chaîne respiratoire`],
  28: [`Métabolismes et chaîne respiratoire`],
  29: [`Métabolismes et chaîne respiratoire`],
  30: [`Métabolismes et chaîne respiratoire`],
  31: [`Métabolismes et chaîne respiratoire`],
  32: [`Métabolismes et chaîne respiratoire`],
  33: [`Métabolismes et chaîne respiratoire`],
  34: [`Métabolismes et chaîne respiratoire`],
  35: [`Métabolismes et chaîne respiratoire`],
  36: [`Métabolismes et chaîne respiratoire`],
  37: [`Métabolismes et chaîne respiratoire`],
  38: [`Métabolismes et chaîne respiratoire`],
  39: [`Métabolismes et chaîne respiratoire`],
  40: [`Métabolismes et chaîne respiratoire`],
  41: [`Métabolismes et chaîne respiratoire`],
  42: [`Métabolismes et chaîne respiratoire`],
  43: [`Métabolismes et chaîne respiratoire`],
  44: [`Métabolismes et chaîne respiratoire`],
  45: [`Phosphorylation oxydative`],
  46: [`Phosphorylation oxydative`],
  47: [`Phosphorylation oxydative`],
  48: [`Phosphorylation oxydative`],
  49: [`Phosphorylation oxydative`],
  50: [`Phosphorylation oxydative`],
  51: [`Phosphorylation oxydative`],
  52: [`Phosphorylation oxydative`],
  53: [`Phosphorylation oxydative`],
  54: [`Phosphorylation oxydative`],
  55: [`Phosphorylation oxydative`],
  56: [`Phosphorylation oxydative`],
  57: [`Phosphorylation oxydative`],
  58: [`Phosphorylation oxydative`],
  59: [`Phosphorylation oxydative`],
  60: [`Phosphorylation oxydative`],
  61: [`Phosphorylation oxydative`],
  62: [`Phosphorylation oxydative`],
  63: [`Phosphorylation oxydative`],
  64: [`Phosphorylation oxydative`],
  65: [`Phosphorylation oxydative`],
  66: [`Phosphorylation oxydative`],
  67: [`Autres fonctions et pathologies`],
  68: [`Autres fonctions et pathologies`],
  69: [`Autres fonctions et pathologies`],
  70: [`Autres fonctions et pathologies`],
  71: [`Autres fonctions et pathologies`],
  72: [`Autres fonctions et pathologies`],
  73: [`Autres fonctions et pathologies`],
  74: [`Autres fonctions et pathologies`],
  75: [`Autres fonctions et pathologies`],
  76: [`Autres fonctions et pathologies`],
  77: [`Autres fonctions et pathologies`],
  78: [`Autres fonctions et pathologies`],
  79: [`Autres fonctions et pathologies`],
  80: [`Autres fonctions et pathologies`],
  81: [`Autres fonctions et pathologies`],
  82: [`Autres fonctions et pathologies`],
  83: [`Autres fonctions et pathologies`],
  84: [`Autres fonctions et pathologies`],
  85: [`Autres fonctions et pathologies`],
  86: [`Autres fonctions et pathologies`],
  87: [`Autres fonctions et pathologies`],
  88: [`Autres fonctions et pathologies`],
  89: [`Autres fonctions et pathologies`],
  90: [`Autres fonctions et pathologies`],
  91: [`Autres fonctions et pathologies`],
  92: [`Autres fonctions et pathologies`],
  93: [`Autres fonctions et pathologies`],
  94: [`Autres fonctions et pathologies`],
  95: [`Autres fonctions et pathologies`],
  96: [`Autres fonctions et pathologies`],
  97: [`Autres fonctions et pathologies`],
  98: [`Autres fonctions et pathologies`],
  99: [`Autres fonctions et pathologies`],
  100: [`Autres fonctions et pathologies`],
  101: [`Synthèse de la mitochondrie`],
  102: [`Synthèse de la mitochondrie`],
  103: [`Synthèse de la mitochondrie`],
  104: [`Synthèse de la mitochondrie`],
  105: [`Synthèse de la mitochondrie`],
  106: [`Synthèse de la mitochondrie`],
  107: [`Synthèse de la mitochondrie`],
  108: [`Synthèse de la mitochondrie`],
  109: [`Synthèse de la mitochondrie`],
  110: [`Synthèse de la mitochondrie`],
  111: [`Synthèse de la mitochondrie`],
  112: [`Synthèse de la mitochondrie`],
  113: [`Synthèse de la mitochondrie`],
  114: [`Synthèse de la mitochondrie`],
  115: [`Synthèse de la mitochondrie`],
  116: [`Synthèse de la mitochondrie`],
  117: [`Synthèse de la mitochondrie`],
  118: [`Synthèse de la mitochondrie`],
  119: [`Synthèse de la mitochondrie`],
  120: [`Synthèse de la mitochondrie`],
  121: [`Synthèse de la mitochondrie`],
  122: [`Synthèse de la mitochondrie`],
};
export async function seedHealthTrainingUe14BiologieCellulaireMitochondrie(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 7',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
    purgeObsoleteQuestions: true,
  });
}
