import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_E_ORDER = 5;

export const SECTION_E_SYNTHESIS_PRACTICE_QUIZ_SLUG =
  `section-e-synthesis-practice-derives-monofonctionnels`;
export const SECTION_E_SYNTHESIS_MASTER_QUIZ_SLUG =
  `section-e-synthesis-master-examen-derives-monofonctionnels`;

export const SECTION_E_SYNTHESIS_PRACTICE_QUESTION_ORDERS: number[] = [121, 122, 123, 124, 125, 126, 127, 128, 129, 130];
export const SECTION_E_SYNTHESIS_MASTER_QUESTION_ORDERS: number[] = [131, 132, 133, 134, 135, 136, 137, 138, 139, 140];

export const SECTION_E_QUIZZES: SeedQuiz[] = [
  {
    order: 13,
    slug: SECTION_E_SYNTHESIS_PRACTICE_QUIZ_SLUG,
    title: `Synthèse guidée : alcools, amines et dérivés halogénés`,
    description: `Mobiliser les principales préparations et réactions du chapitre dans des situations courtes et dans un enchaînement de transformations.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_E_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 121 },
      { type: 'QUESTION', questionOrder: 122 },
      { type: 'QUESTION', questionOrder: 123 },
      { type: 'QUESTION', questionOrder: 124 },
      { type: 'QUESTION', questionOrder: 125 },
      { type: 'QUESTION', questionOrder: 126 },
      { type: 'QUESTION', questionOrder: 127 },
      {
        type: 'GROUP',
        title: `Du propène à un alcool tertiaire`,
        sharedStatement: `On étudie la séquence suivante : **étape 1**, hydratation du propène $\mathrm{CH_3{-}CH{=}CH_2}$ donnant notamment le propan-2-ol ; **étape 2**, oxydation du propan-2-ol en propanone ; **étape 3**, réaction de la propanone avec $\mathrm{CH_3MgBr}$ suivie d'une hydrolyse.`,
        questionOrders: [128, 129, 130],
      },
    ],
  },
  {
    order: 14,
    slug: SECTION_E_SYNTHESIS_MASTER_QUIZ_SLUG,
    title: `Synthèse type examen : transformations et stéréochimie`,
    description: `Résoudre des questions transversales mêlant choix des réactifs, classes fonctionnelles, enchaînements de synthèse et conséquences stéréochimiques des substitutions.`,
    stage: 'MASTER',
    sectionOrder: SECTION_E_ORDER,
    items: [
      {
        type: 'GROUP',
        title: `Réactivité d'un alcool tertiaire de synthèse`,
        sharedStatement: `Un intermédiaire de synthèse, le 2-méthylpropan-2-ol $\mathrm{(CH_3)_3C{-}OH}$, est obtenu par addition de $\mathrm{CH_3MgBr}$ sur la propanone puis hydrolyse. On étudie ensuite son oxydation et sa déshydratation.`,
        questionOrders: [131, 132, 133],
      },
      { type: 'QUESTION', questionOrder: 134 },
      { type: 'QUESTION', questionOrder: 135 },
      { type: 'QUESTION', questionOrder: 136 },
      { type: 'QUESTION', questionOrder: 137 },
      {
        type: 'GROUP',
        title: `Trois voies à partir d'un dérivé halogéné chiral`,
        sharedStatement: `Un dérivé halogéné optiquement pur $\mathrm{R^*{-}X}$ est étudié lors de la préparation d'un intermédiaire pharmaceutique. **Voie I** : substitution selon $\mathrm{S_N1}$ ; **voie II** : substitution selon $\mathrm{S_N2}$ ; **voie III** : réaction avec le magnésium donnant $\mathrm{R^*MgX}$.`,
        questionOrders: [138, 139, 140],
      },
    ],
  },
];

export const SECTION_E_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les associations suivantes, laquelle ou lesquelles correspondent au cours ?`,
    choices: [
      `Aldéhyde + $\mathrm{NaBH_4}$ → alcool primaire.`,
      `Cétone + $\mathrm{NaBH_4}$ → alcool secondaire.`,
      `Alcool secondaire + oxydation → cétone.`,
      `Alcool tertiaire + oxydation simple → aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les réductions des composés carbonylés et l'oxydation des alcools sont des transformations inverses pour les couples aldéhyde/alcool primaire et cétone/alcool secondaire.`,
    choiceExplanations: [
      `Le motif $\mathrm{-CHO}$ devient $\mathrm{-CH_2OH}$.`,
      `Le carbone carbonylé lié à deux carbones devient un alcool secondaire.`,
      `Le carbone portant $\mathrm{-OH}$ devient carbonylé.`,
      `La fiche considère l'alcool tertiaire comme insensible à l'oxydation simple.`,
    ],
  },
  {
    order: 122,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On souhaite transformer la propanone en propan-2-ol sans modifier le squelette carboné.`,
    choices: [
      `$\mathrm{NaBH_4}$ peut être utilisé selon le cours.`,
      `La transformation est une réduction.`,
      `Le produit est un alcool secondaire.`,
      `Un organomagnésien est indispensable et doit ajouter un carbone.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réduction de la cétone convertit le groupe $\mathrm{C{=}O}$ en groupe $\mathrm{CHOH}$ sans former de nouvelle liaison carbone-carbone.`,
    choiceExplanations: [
      `C'est le réducteur doux cité.`,
      `Le niveau d'oxydation du carbone diminue.`,
      `Le carbone fonctionnel reste lié à deux groupes méthyle.`,
      `Une réduction simple suffit et conserve les trois carbones.`,
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À partir de l'éthanol, quelles transformations sont cohérentes ?`,
    choices: [
      `Oxydation douce → éthanal.`,
      `Oxydation forte → acide éthanoïque.`,
      `Réaction avec un chlorure d'acyle → ester.`,
      `Déshydratation → éthène + eau.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `L'éthanol peut illustrer les quatre grandes voies de réactivité des alcools étudiées dans cette section.`,
    choiceExplanations: [
      `L'éthanol est primaire.`,
      `L'oxydation poussée atteint l'acide carboxylique.`,
      `Le groupe hydroxyle est acylé.`,
      `L'élimination d'eau forme la double liaison de l'éthène.`,
    ],
  },
  {
    order: 124,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des transformations des amines :`,
    choices: [
      `Une amine primaire peut former une imine avec un composé carbonylé.`,
      `Une amine secondaire peut former un ion iminium avec un composé carbonylé.`,
      `Une amine primaire ou secondaire peut être amidifiée par un acide activé.`,
      `Une amine tertiaire est identique à un ammonium quaternaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La classe de l'amine détermine le type de produit formé avec un carbonyle et sa capacité d'amidification dans le cadre du cours.`,
    choiceExplanations: [
      `Le bilan produit également de l'eau.`,
      `Le produit azoté est chargé positivement dans la représentation proposée.`,
      `Ces deux classes possèdent au moins une liaison $\mathrm{N{-}H}$.`,
      `L'ammonium quaternaire possède quatre substituants et une charge positive.`,
    ],
  },
  {
    order: 125,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On compare un dérivé halogéné $\mathrm{R{-}X}$ et l'organomagnésien $\mathrm{RMgX}$ qui en est issu.`,
    choices: [
      `Dans $\mathrm{R{-}X}$, le carbone lié à $\mathrm{X}$ est électrophile.`,
      `Dans $\mathrm{RMgX}$, le carbone organique est nucléophile.`,
      `La réaction avec le magnésium inverse le caractère du carbone.`,
      `Les deux espèces ont exactement la même réactivité vis-à-vis d'un carbone carbonylé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La conversion en réactif de Grignard constitue une inversion de polarité : le carbone passe d'électrophile à nucléophile.`,
    choiceExplanations: [
      `La liaison carbone-halogène est polarisée dans ce sens.`,
      `Le carbone possède un caractère carbanionique.`,
      `C'est l'idée essentielle de cette préparation.`,
      `Le dérivé halogéné et le Grignard jouent des rôles opposés.`,
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des substitutions nucléophiles $\mathrm{S_N1}$ et $\mathrm{S_N2}$ :`,
    choices: [
      `La $\mathrm{S_N1}$ passe par un carbocation plan.`,
      `La $\mathrm{S_N2}$ est concertée.`,
      `La $\mathrm{S_N1}$ peut racémiser un centre asymétrique.`,
      `La $\mathrm{S_N2}$ peut provoquer une inversion de configuration.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les quatre propositions résument les différences mécanistiques et stéréochimiques fondamentales entre les deux voies.`,
    choiceExplanations: [
      `Le carbocation apparaît après le départ de $\mathrm{X^-}$.`,
      `L'attaque et le départ sont simultanés.`,
      `Les deux faces du carbocation sont accessibles.`,
      `L'attaque arrière impose l'inversion.`,
    ],
  },
  {
    order: 127,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `On fait réagir séparément un chlorure d'acyle avec un alcool puis avec une amine primaire.`,
    choices: [
      `L'alcool peut donner un ester.`,
      `L'amine primaire peut donner un amide.`,
      `Le chlorure d'acyle est un acide activé dans les deux cas.`,
      `Les deux nucléophiles donnent nécessairement le même groupe fonctionnel.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le même groupe acyle peut être transféré sur un oxygène alcoolique ou sur un azote aminé, donnant respectivement un ester ou un amide.`,
    choiceExplanations: [
      `Le motif final est $\mathrm{COO}$. `,
      `Le motif final est $\mathrm{CON}$. `,
      `Il fournit le centre acyle électrophile.`,
      `La nature du nucléophile détermine la fonction obtenue.`,
    ],
  },
  {
    order: 128,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'étape 1 de la séquence :`,
    choices: [
      `Il s'agit d'une hydratation d'alcène.`,
      `Une liaison $\mathrm{C{=}C}$ est consommée.`,
      `Le propan-2-ol obtenu est un alcool secondaire.`,
      `Une molécule d'eau est éliminée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'ajout des éléments de l'eau sur le propène forme un alcool ; lorsque le groupe $\mathrm{-OH}$ est sur le carbone central, le produit est secondaire.`,
    choiceExplanations: [
      `L'eau est ajoutée sur l'alcène.`,
      `La liaison pi disparaît.`,
      `Le carbone fonctionnel est lié à deux carbones.`,
      `L'élimination d'eau correspond au sens inverse.`,
    ],
  },
  {
    order: 129,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'étape 2 de la séquence :`,
    choices: [
      `La propanone est une cétone.`,
      `La transformation est une oxydation d'un alcool secondaire.`,
      `Le nombre de carbones est conservé.`,
      `Le produit est un aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le carbone central du propan-2-ol devient le carbone carbonylé de la propanone.`,
    choiceExplanations: [
      `Son groupe carbonyle est lié à deux groupes méthyle.`,
      `C'est le devenir caractéristique d'un alcool secondaire.`,
      `Le squelette à trois carbones reste intact.`,
      `Un aldéhyde proviendrait d'un alcool primaire.`,
    ],
  },
  {
    order: 130,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'étape 3 de la séquence :`,
    choices: [
      `Le groupe méthyle de $\mathrm{CH_3MgBr}$ se fixe sur le carbone carbonylé.`,
      `Une nouvelle liaison carbone-carbone est formée.`,
      `Après hydrolyse, le produit est le 2-méthylpropan-2-ol.`,
      `L'alcool final est tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La propanone porte déjà deux groupes méthyle ; l'organomagnésien en apporte un troisième, donnant le tert-butanol après hydrolyse.`,
    choiceExplanations: [
      `Le carbone nucléophile du Grignard attaque le carbonyle.`,
      `Cette addition allonge le squelette d'un carbone.`,
      `Le produit s'écrit $\mathrm{(CH_3)_3C{-}OH}$. `,
      `Le carbone fonctionnel possède trois voisins carbonés.`,
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la préparation de l'intermédiaire de l'énoncé commun :`,
    choices: [
      `La propanone est une cétone.`,
      `$\mathrm{CH_3MgBr}$ apporte un groupe méthyle nucléophile.`,
      `Une nouvelle liaison carbone-carbone est formée.`,
      `Le produit final est un alcool secondaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'addition du groupe méthyle sur une cétone conduit, après hydrolyse, à un alcool tertiaire.`,
    choiceExplanations: [
      `Le carbone carbonylé est lié à deux groupes méthyle.`,
      `Le carbone lié au magnésium est nucléophile.`,
      `Le fragment du Grignard est incorporé au squelette.`,
      `Trois groupes carbonés entourent le carbone portant $\mathrm{-OH}$.`,
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant l'oxydation de cet intermédiaire :`,
    choices: [
      `Il s'agit d'un alcool tertiaire.`,
      `Le carbone portant $\mathrm{-OH}$ ne porte aucun hydrogène.`,
      `Il est considéré comme insensible à l'oxydation dans les conditions du cours.`,
      `Il donne directement le 2-méthylpropanal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'absence d'hydrogène sur le carbone fonctionnel empêche le schéma simple d'oxydation en carbonyle.`,
    choiceExplanations: [
      `Le carbone fonctionnel est lié à trois groupes méthyle.`,
      `Ses quatre liaisons sont déjà engagées avec trois carbones et l'oxygène.`,
      `C'est la conclusion indiquée dans la fiche.`,
      `Aucun aldéhyde n'est prévu.`,
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la déshydratation de cet intermédiaire :`,
    choices: [
      `Une élimination d'eau peut former le 2-méthylpropène.`,
      `Une double liaison carbone-carbone est créée.`,
      `La fonction alcool disparaît.`,
      `La transformation produit un acide carboxylique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le tert-butanol peut perdre les éléments de l'eau pour former l'alcène correspondant, le 2-méthylpropène.`,
    choiceExplanations: [
      `Le squelette ramifié est conservé.`,
      `L'élimination crée l'insaturation.`,
      `Le groupe $\mathrm{-OH}$ est consommé.`,
      `Aucune oxydation en acide n'est impliquée.`,
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un chlorure d'acyle est mis en présence d'éthanol puis, dans une autre expérience, de méthylamine.`,
    choices: [
      `L'éthanol peut conduire à un ester.`,
      `La méthylamine peut conduire à un amide.`,
      `L'éthanol et la méthylamine jouent tous deux un rôle nucléophile.`,
      `Les deux produits possèdent nécessairement une fonction alcool libre inchangée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'oxygène de l'alcool et l'azote de l'amine attaquent le groupe acyle, mais les fonctions obtenues sont différentes.`,
    choiceExplanations: [
      `Le motif final est $\mathrm{RCOOCH_2CH_3}$. `,
      `Le motif final contient $\mathrm{CONHCH_3}$. `,
      `Ils apportent chacun un doublet au centre acyle.`,
      `Le groupe hydroxyle de l'éthanol est transformé et la méthylamine n'en contient pas.`,
    ],
  },
  {
    order: 135,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On fait réagir un aldéhyde séparément avec une amine primaire et une amine secondaire.`,
    choices: [
      `L'amine primaire peut donner une imine.`,
      `L'amine secondaire peut donner un iminium.`,
      `De l'eau est formée dans les deux condensations.`,
      `Les deux réactions peuvent être inversées par hydrolyse.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La classe de l'amine distingue le produit azoté, mais les deux bilans sont des condensations réversibles avec formation d'eau.`,
    choiceExplanations: [
      `C'est le produit caractéristique d'une amine primaire.`,
      `C'est le produit caractéristique d'une amine secondaire.`,
      `L'élimination d'eau accompagne la formation de la liaison carbone-azote.`,
      `L'eau permet de régénérer les réactifs.`,
    ],
  },
  {
    order: 136,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Lors d'alkylations successives de l'ammoniac par un dérivé halogéné $\mathrm{R{-}X}$ :`,
    choices: [
      `Une amine primaire peut être obtenue après la première alkylation.`,
      `Une amine tertiaire peut être obtenue avant l'ammonium quaternaire.`,
      `L'ammonium quaternaire porte quatre groupes carbonés et une charge positive.`,
      `L'ammonium quaternaire est encore une amine neutre possédant un doublet libre.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La suite d'alkylations augmente progressivement la substitution de l'azote jusqu'à l'espèce tétracoordonnée chargée.`,
    choiceExplanations: [
      `Un seul groupe $\mathrm{R}$ est alors lié à l'azote.`,
      `Elle correspond au stade à trois substituants.`,
      `La quatrième liaison entraîne la charge positive.`,
      `Le doublet libre a été utilisé pour former cette quatrième liaison.`,
    ],
  },
  {
    order: 137,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos des dérivés halogénés et de leurs transformations :`,
    choices: [
      `Un alcène peut donner un dérivé halogéné par addition de $\mathrm{HX}$.`,
      `Un alcool peut donner un dérivé halogéné avec un agent halogénant adapté.`,
      `Un dérivé halogéné peut donner un organomagnésien avec le magnésium.`,
      `Toutes les propositions précédentes sont exactes.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les trois premières propositions constituent trois relations importantes du réseau de transformations du chapitre.`,
    choiceExplanations: [
      `Les éléments de $\mathrm{HX}$ s'ajoutent sur la double liaison.`,
      `Le groupe $\mathrm{-OH}$ est remplacé par $\mathrm{X}$. `,
      `La réaction forme $\mathrm{RMgX}$. `,
      `Les trois associations sont correctes.`,
    ],
  },
  {
    order: 138,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la voie **I** :`,
    choices: [
      `Un carbocation plan est formé.`,
      `Le nucléophile peut attaquer les deux faces.`,
      `Une racémisation est possible.`,
      `La pureté optique initiale est nécessairement conservée avec une configuration unique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie $\mathrm{S_N1}$ efface temporairement l'information stéréochimique par formation d'un carbocation plan.`,
    choiceExplanations: [
      `Il apparaît après le départ de $\mathrm{X^-}$.`,
      `La planéité ouvre deux trajectoires.`,
      `Les deux énantiomères peuvent être produits.`,
      `La $\mathrm{S_N1}$ entraîne au contraire une perte de pureté énantiomérique.`,
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la voie **II** :`,
    choices: [
      `La substitution se déroule en une étape concertée.`,
      `Une attaque arrière du nucléophile est attendue.`,
      `Le produit subit une inversion de configuration.`,
      `Un mélange racémique est la conséquence obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie $\mathrm{S_N2}$ remplace $\mathrm{X}$ par $\mathrm{Nu}$ selon une trajectoire unique et stéréospécifique.`,
    choiceExplanations: [
      `Formation et rupture de liaison sont simultanées.`,
      `Le nucléophile arrive du côté opposé au groupe partant.`,
      `C'est l'inversion caractéristique.`,
      `La racémisation est associée à la voie $\mathrm{S_N1}$.`,
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant la voie **III** :`,
    choices: [
      `Le produit est un réactif de Grignard.`,
      `Le carbone qui était électrophile dans $\mathrm{R^*{-}X}$ acquiert un caractère nucléophile.`,
      `Le produit peut ensuite attaquer un carbone carbonylé électrophile.`,
      `La réaction avec le magnésium transforme directement le dérivé halogéné en amide.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La formation de $\mathrm{R^*MgX}$ inverse la polarité du carbone et prépare sa réaction avec un composé carbonylé.`,
    choiceExplanations: [
      `C'est l'autre nom d'un organomagnésien.`,
      `La liaison carbone-magnésium est polarisée vers le carbone.`,
      `Une nouvelle liaison carbone-carbone peut alors être formée.`,
      `Aucun groupe carbonyle ou azote n'est introduit à cette étape.`,
    ],
  },
];
