/**
 * Cartographie éditoriale V2 — auteur
 */

export const UE14_BIOCH_CH6_V2_QUIZ_MAP = [
  {
    "sectionOrder": 1,
    "order": 1,
    "slug": "section-a-discovery-glycerol-acylglycerols",
    "title": "Glycérol et acylglycérols",
    "description": "Repères sur le glycérol, sa numérotation et les mono-, di- et triacylglycérols.",
    "stage": "DISCOVER",
    "questionOrders": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ]
  },
  {
    "sectionOrder": 1,
    "order": 2,
    "slug": "section-a-practice-nomenclature-acylglycerols",
    "title": "Glycérol et acylglycérols",
    "description": "Applications sur positions d'estérification, nomenclature et triglycérides homogènes ou mixtes.",
    "stage": "PRACTICE",
    "questionOrders": [
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ]
  },
  {
    "sectionOrder": 2,
    "order": 1,
    "slug": "section-b-discovery-triglycerides-proprietes",
    "title": "Triacylglycérols : propriétés, stockage et rôles",
    "description": "Repères sur point de fusion, stockage énergétique et propriétés des triglycérides.",
    "stage": "DISCOVER",
    "questionOrders": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32
    ]
  },
  {
    "sectionOrder": 2,
    "order": 2,
    "slug": "section-b-practice-stockage-protection-triglycerides",
    "title": "Triacylglycérols : propriétés, stockage et rôles",
    "description": "Applications biologiques et alimentaires sur adipocytes, protections et huile de palme.",
    "stage": "PRACTICE",
    "questionOrders": [
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44
    ]
  },
  {
    "sectionOrder": 3,
    "order": 1,
    "slug": "section-c-discovery-acide-phosphatidique-classes",
    "title": "Acide phosphatidique et classes de glycérophospholipides",
    "description": "Repères structuraux sur l'acide phosphatidique et les principales têtes polaires.",
    "stage": "DISCOVER",
    "questionOrders": [
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54
    ]
  },
  {
    "sectionOrder": 3,
    "order": 2,
    "slug": "section-c-practice-phospholipides-tetes-polaires",
    "title": "Acide phosphatidique et classes de glycérophospholipides",
    "description": "Applications sur PS, PE, PC, PG, PI et lysophospholipides.",
    "stage": "PRACTICE",
    "questionOrders": [
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66
    ]
  },
  {
    "sectionOrder": 4,
    "order": 1,
    "slug": "section-d-discovery-membranes-phospholipases",
    "title": "Membranes, phospholipases et signalisation",
    "description": "Repères sur amphiphilie, bicouches, liposomes et sites de clivage des phospholipases.",
    "stage": "DISCOVER",
    "questionOrders": [
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76
    ]
  },
  {
    "sectionOrder": 4,
    "order": 2,
    "slug": "section-d-practice-pip2-pi3k-plasmalogenes",
    "title": "Membranes, phospholipases et signalisation",
    "description": "Applications sur PIP2, DAG/IP3, PI3K-AKT, PTEN, plasmalogènes et PAF.",
    "stage": "PRACTICE",
    "questionOrders": [
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88
    ]
  },
  {
    "sectionOrder": 4,
    "order": 3,
    "slug": "section-d-master-signalisation-phospholipides",
    "title": "Signalisation et médiateurs phospholipidiques",
    "description": "Maîtrise des phospholipases, seconds messagers et voies PI3K-AKT avec contextes biologiques et médicaux.",
    "stage": "MASTER",
    "questionOrders": [
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100
    ]
  },
  {
    "sectionOrder": 5,
    "order": 1,
    "slug": "section-e-synthesis-practice-glycerides-phospholipides",
    "title": "Glycérides et glycérophospholipides",
    "description": "Synthèse appliquée des structures, rôles et voies de signalisation.",
    "stage": "PRACTICE",
    "questionOrders": [
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ]
  },
  {
    "sectionOrder": 5,
    "order": 2,
    "slug": "maitriser-synthese-glycerides-glycerophospholipides",
    "title": "Glycérides et glycérophospholipides",
    "description": "Maîtrise transversale du chapitre sans constituer un examen blanc.",
    "stage": "MASTER",
    "questionOrders": [
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122
    ]
  }
] as const;

export const UE14_BIOCH_CH6_V2_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Glycérol et acylglycérols"],
  2: ["Glycérol et acylglycérols"],
  3: ["Glycérol et acylglycérols"],
  4: ["Glycérol et acylglycérols"],
  5: ["Glycérol et acylglycérols"],
  6: ["Glycérol et acylglycérols"],
  7: ["Glycérol et acylglycérols"],
  8: ["Glycérol et acylglycérols"],
  9: ["Glycérol et acylglycérols"],
  10: ["Glycérol et acylglycérols"],
  11: ["Glycérol et acylglycérols"],
  12: ["Glycérol et acylglycérols"],
  13: ["Glycérol et acylglycérols"],
  14: ["Glycérol et acylglycérols"],
  15: ["Glycérol et acylglycérols"],
  16: ["Glycérol et acylglycérols"],
  17: ["Glycérol et acylglycérols"],
  18: ["Glycérol et acylglycérols"],
  19: ["Glycérol et acylglycérols"],
  20: ["Glycérol et acylglycérols"],
  21: ["Glycérol et acylglycérols"],
  22: ["Glycérol et acylglycérols"],
  23: ["Triacylglycérols : propriétés et rôles"],
  24: ["Triacylglycérols : propriétés et rôles"],
  25: ["Triacylglycérols : propriétés et rôles"],
  26: ["Triacylglycérols : propriétés et rôles"],
  27: ["Triacylglycérols : propriétés et rôles"],
  28: ["Triacylglycérols : propriétés et rôles"],
  29: ["Triacylglycérols : propriétés et rôles"],
  30: ["Triacylglycérols : propriétés et rôles"],
  31: ["Triacylglycérols : propriétés et rôles"],
  32: ["Triacylglycérols : propriétés et rôles"],
  33: ["Triacylglycérols : propriétés et rôles"],
  34: ["Triacylglycérols : propriétés et rôles"],
  35: ["Triacylglycérols : propriétés et rôles"],
  36: ["Triacylglycérols : propriétés et rôles"],
  37: ["Triacylglycérols : propriétés et rôles"],
  38: ["Triacylglycérols : propriétés et rôles"],
  39: ["Triacylglycérols : propriétés et rôles"],
  40: ["Triacylglycérols : propriétés et rôles"],
  41: ["Triacylglycérols : propriétés et rôles"],
  42: ["Triacylglycérols : propriétés et rôles"],
  43: ["Triacylglycérols : propriétés et rôles"],
  44: ["Triacylglycérols : propriétés et rôles"],
  45: ["Acide phosphatidique et classes"],
  46: ["Acide phosphatidique et classes"],
  47: ["Acide phosphatidique et classes"],
  48: ["Acide phosphatidique et classes"],
  49: ["Acide phosphatidique et classes"],
  50: ["Acide phosphatidique et classes"],
  51: ["Acide phosphatidique et classes"],
  52: ["Acide phosphatidique et classes"],
  53: ["Acide phosphatidique et classes"],
  54: ["Acide phosphatidique et classes"],
  55: ["Acide phosphatidique et classes"],
  56: ["Acide phosphatidique et classes"],
  57: ["Acide phosphatidique et classes"],
  58: ["Acide phosphatidique et classes"],
  59: ["Acide phosphatidique et classes"],
  60: ["Acide phosphatidique et classes"],
  61: ["Acide phosphatidique et classes"],
  62: ["Acide phosphatidique et classes"],
  63: ["Acide phosphatidique et classes"],
  64: ["Acide phosphatidique et classes"],
  65: ["Acide phosphatidique et classes"],
  66: ["Acide phosphatidique et classes"],
  67: ["Membranes, phospholipases et signalisation"],
  68: ["Membranes, phospholipases et signalisation"],
  69: ["Membranes, phospholipases et signalisation"],
  70: ["Membranes, phospholipases et signalisation"],
  71: ["Membranes, phospholipases et signalisation"],
  72: ["Membranes, phospholipases et signalisation"],
  73: ["Membranes, phospholipases et signalisation"],
  74: ["Membranes, phospholipases et signalisation"],
  75: ["Membranes, phospholipases et signalisation"],
  76: ["Membranes, phospholipases et signalisation"],
  77: ["Membranes, phospholipases et signalisation"],
  78: ["Membranes, phospholipases et signalisation"],
  79: ["Membranes, phospholipases et signalisation"],
  80: ["Membranes, phospholipases et signalisation"],
  81: ["Membranes, phospholipases et signalisation"],
  82: ["Membranes, phospholipases et signalisation"],
  83: ["Membranes, phospholipases et signalisation"],
  84: ["Membranes, phospholipases et signalisation"],
  85: ["Membranes, phospholipases et signalisation"],
  86: ["Membranes, phospholipases et signalisation"],
  87: ["Membranes, phospholipases et signalisation"],
  88: ["Membranes, phospholipases et signalisation"],
  89: ["QZONE : site de la phospholipase A2"],
  90: ["Membranes, phospholipases et signalisation"],
  91: ["Membranes, phospholipases et signalisation"],
  92: ["PIP2 → DAG + IP3"],
  93: ["Membranes, phospholipases et signalisation"],
  94: ["Membranes, phospholipases et signalisation"],
  95: ["Membranes, phospholipases et signalisation"],
  96: ["Membranes, phospholipases et signalisation"],
  97: ["PLA2 : arachidonate et lysophospholipide"],
  98: ["Membranes, phospholipases et signalisation"],
  99: ["Membranes, phospholipases et signalisation"],
  100: ["Membranes, phospholipases et signalisation"],
  101: ["Synthèse appliquée"],
  102: ["Synthèse appliquée"],
  103: ["Synthèse appliquée"],
  104: ["Synthèse appliquée"],
  105: ["Synthèse appliquée"],
  106: ["Synthèse appliquée"],
  107: ["Synthèse appliquée"],
  108: ["Synthèse appliquée"],
  109: ["Synthèse appliquée"],
  110: ["Synthèse appliquée"],
  111: ["Maîtrise transversale"],
  112: ["Maîtrise transversale"],
  113: ["Maîtrise transversale"],
  114: ["Maîtrise transversale"],
  115: ["PI3K : PIP2 → PIP3"],
  116: ["Maîtrise transversale"],
  117: ["Maîtrise transversale"],
  118: ["Maîtrise transversale"],
  119: ["Maîtrise transversale"],
  120: ["Maîtrise transversale"],
  121: ["Maîtrise transversale"],
  122: ["Maîtrise transversale"],
};
