import type { HealthTrainingAuthorQuestion } from './health-training-ue14.shared';

/**
 * UE14 – Chimie générale
 * Chapitre 3 – Orbitales moléculaires
 * Section E – Synthèse
 */

export const UE14_CH3_SYNTHESIS_PRACTICE_V2_QUESTIONS: HealthTrainingAuthorQuestion[] = [
  {
    order: 61,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `L'aspirine possède la formule topologique suivante : [[QUESTION_DIAGRAM]] Combien de ses neuf atomes de carbone sont hybridés $\\mathrm{sp}^2$ ?`,
    questionDiagram: { type: 'molecule', molecule: 'aspirin-topological' },
    answer: { type: 'number', value: 8, tolerance: 0 },
    explanation: `Les six carbones aromatiques et les deux carbones carbonylés sont sp2 ; seul le carbone du groupe méthyle est sp3.`,
  },
  {
    order: 62,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `À propos de la structure de l'aspirine, sélectionnez exactement les deux propositions correctes.`,
    choices: [
      { content: `Le cycle aromatique comporte six carbones $\\mathrm{sp}^2$.`, correct: true, explanation: `Chaque carbone du cycle est trigonal plan.` },
      { content: `Le carbone du groupe méthyle est $\\mathrm{sp}^3$.`, correct: true, explanation: `Il ne forme que des liaisons simples.` },
      { content: `Les carbones carbonylés sont $\\mathrm{sp}^3$.`, correct: false, explanation: `Ils sont sp2.` },
      { content: `Le cycle aromatique est constitué de carbones $\\mathrm{sp}$.`, correct: false, explanation: `Les carbones aromatiques sont sp2.` },
    ],
    explanation: `L'aspirine permet de repérer dans une même molécule des carbones aromatiques et carbonylés sp2 ainsi qu'un carbone méthylique sp3.`,
  },
  {
    order: 63,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Dans le dioxyde de carbone $\\ce{O=C=O}$ de l'énoncé commun, combien de liaisons $\\pi$ sont présentes ?`,
    answer: { type: 'number', value: 2, tolerance: 0 },
    explanation: `Chaque double liaison C=O comporte une liaison pi ; CO2 en possède donc deux.`,
  },
  {
    order: 64,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `On compare le carbone du $\\ce{CO2}$ et celui de l'ion hydrogénocarbonate $\\ce{HCO3-}$ dans l'énoncé commun. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Dans $\\ce{CO2}$, le carbone est décrit comme $\\mathrm{sp}$ et l'édifice est linéaire.`, correct: true, explanation: `Deux directions de liaison.` },
      { content: `Dans $\\ce{HCO3-}$, le carbone est décrit comme $\\mathrm{sp}^2$ avec trois directions approximativement coplanaires.`, correct: true, explanation: `Trois directions C–O.` },
      { content: `Le carbone de $\\ce{CO2}$ est $\\mathrm{sp}^3$.`, correct: false, explanation: `Il ne possède que deux directions de liaison.` },
      { content: `Le carbone de $\\ce{HCO3-}$ est linéaire.`, correct: false, explanation: `Trois directions conduisent à une organisation trigonale plane.` },
    ],
    explanation: `Le passage de deux à trois directions autour du carbone fait passer du modèle sp linéaire au modèle sp2 trigonal plan.`,
  },
  {
    order: 65,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Le cyanure d'hydrogène $\\ce{H-C#N}$ est un composé très toxique. Sélectionnez exactement les deux propositions correctes.`,
    choices: [
      { content: `Le carbone est hybridé $\\mathrm{sp}$.`, correct: true, explanation: `Deux directions sigma autour du carbone.` },
      { content: `La molécule possède deux liaisons $\\pi$.`, correct: true, explanation: `La triple liaison C≡N contient deux pi.` },
      { content: `La molécule est coudée.`, correct: false, explanation: `Elle est linéaire.` },
      { content: `Le carbone est $\\mathrm{sp}^3$.`, correct: false, explanation: `Une hybridation sp3 est incompatible avec la triple liaison.` },
    ],
    explanation: `HCN associe un carbone sp, une géométrie linéaire et une triple liaison comportant deux composantes pi.`,
  },
  {
    order: 66,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Le diazote $\\ce{N2}$ peut être utilisé comme atmosphère inerte pour certaines préparations. Combien de liaisons $\\pi$ contient sa triple liaison ?`,
    answer: { type: 'number', value: 2, tolerance: 0 },
    explanation: `Une triple liaison est constituée d'une sigma et de deux pi.`,
  },
  {
    order: 67,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `À propos du benzène $\\ce{C6H6}$, quelles propositions sont exactes ?`,
    choices: [
      { content: `Les six carbones sont $\\mathrm{sp}^2$.`, correct: true, explanation: `Chaque carbone est trigonal plan.` },
      { content: `Les six orbitales p non hybridées sont perpendiculaires au plan du cycle.`, correct: true, explanation: `Elles permettent le système pi.` },
      { content: `Les électrons du système $\\pi$ sont délocalisés sur l'ensemble du cycle dans le modèle du cours.`, correct: true, explanation: `C'est la notion de cycle aromatique présentée.` },
      { content: `Le benzène est un cycle de carbones $\\mathrm{sp}^3$.`, correct: false, explanation: `Il est plan et sp2.` },
    ],
    explanation: `L'aromaticité du benzène est reliée à six carbones sp2 et à un système pi délocalisé au-dessus et au-dessous du plan du cycle.`,
  },
  {
    order: 68,
    difficulty: 'MEDIUM',
    format: 'QRM',
    question: `On compare $\\ce{NH3}$, $\\ce{NH4+}$, $\\ce{H2O}$ et $\\ce{H3O+}$. Quelles propositions sont exactes ?`,
    choices: [
      { content: `$\\ce{NH3}$ et $\\ce{H3O+}$ sont de type $\\mathrm{AX}_3\\mathrm{E}_1$ et pyramidaux.`, correct: true, explanation: `Trois liaisons et un doublet non liant.` },
      { content: `$\\ce{NH4+}$ est de type $\\mathrm{AX}_4$ et tétraédrique.`, correct: true, explanation: `Quatre liaisons sans doublet non liant.` },
      { content: `$\\ce{H2O}$ est de type $\\mathrm{AX}_2\\mathrm{E}_2$ et coudée.`, correct: true, explanation: `Deux liaisons et deux doublets non liants.` },
      { content: `Tous les atomes centraux sont $\\mathrm{sp}^2$.`, correct: false, explanation: `Ils sont décrits par quatre domaines électroniques compatibles avec sp3.` },
    ],
    explanation: `Le décompte des doublets liants et non liants permet de relier hybridation sp3, notation de Gillespie et géométrie moléculaire.`,
  },
  {
    order: 69,
    difficulty: 'MEDIUM',
    format: 'QROC',
    question: `Dans l'exemple de l'hémoglobine donné par la fiche, le fer $\\ce{Fe^2+}$ est placé au centre d'une organisation de type $\\mathrm{AX}_6$. Combien de directions de coordination cela représente-t-il ?`,
    answer: { type: 'number', value: 6, tolerance: 0 },
    explanation: `Une géométrie AX6 comporte six directions autour du centre et correspond à une organisation octaédrique dans le modèle de Gillespie.`,
  },
  {
    order: 70,
    difficulty: 'MEDIUM',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Le carbone du groupe carbonyle de l'acétone $\\ce{CH3-C(=O)-CH3}$ est $\\mathrm{sp}^2$. Sélectionnez exactement les deux propositions correctes.`,
    choices: [
      { content: `Il possède trois directions $\\sigma$ approximativement coplanaires.`, correct: true, explanation: `Organisation sp2.` },
      { content: `Il conserve une orbitale p non hybridée participant à la liaison $\\pi$ C=O.`, correct: true, explanation: `C'est la quatrième orbitale de valence non hybridée.` },
      { content: `Il est tétraédrique $\\mathrm{sp}^3$.`, correct: false, explanation: `Le carbone carbonylé est sp2.` },
      { content: `Il conserve deux orbitales p non hybridées.`, correct: false, explanation: `Deux p restantes correspondent à sp, pas sp2.` },
    ],
    explanation: `Un carbone carbonylé est un exemple fréquent de carbone sp2 avec trois directions sigma et une orbitale p engagée dans la composante pi.`,
  },
];

export const UE14_CH3_SYNTHESIS_MASTER_V2_QUESTIONS: HealthTrainingAuthorQuestion[] = [
  {
    order: 71,
    difficulty: 'HARD',
    format: 'QRM',
    question: `L'aspirine possède la formule topologique suivante : [[QUESTION_DIAGRAM]] Quelles propositions sont exactes ?`,
    questionDiagram: { type: 'molecule', molecule: 'aspirin-topological' },
    choices: [
      { content: `Les six carbones du cycle aromatique sont $\\mathrm{sp}^2$.`, correct: true, explanation: `Chaque carbone du cycle est trigonal plan.` },
      { content: `Les deux carbones des groupes carbonyle sont $\\mathrm{sp}^2$.`, correct: true, explanation: `Un carbone carbonylé est sp2.` },
      { content: `Le carbone du groupe méthyle est $\\mathrm{sp}^3$.`, correct: true, explanation: `Il ne forme que des liaisons simples.` },
      { content: `Les neuf carbones sont $\\mathrm{sp}^3$.`, correct: false, explanation: `Huit sont sp2 et un seul est sp3.` },
    ],
    explanation: `L'aspirine rassemble dans une même molécule un système aromatique, deux carbonyles et un groupe méthyle, ce qui permet une lecture locale des hybridations.`,
  },
  {
    order: 72,
    difficulty: 'HARD',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `Le protoxyde d'azote $\\ce{N2O}$ est utilisé pour ses propriétés antalgiques et sédatives. On retient uniquement son squelette linéaire $\\ce{N-N-O}$. Sélectionnez exactement les deux propositions correctes concernant l'atome d'azote central.`,
    choices: [
      { content: `Il possède deux directions de liaison et peut être décrit par un type $\\mathrm{AX}_2$.`, correct: true, explanation: `Une direction vers chacun des deux atomes terminaux.` },
      { content: `Une organisation linéaire est compatible avec une hybridation $\\mathrm{sp}$.`, correct: true, explanation: `Deux directions opposées.` },
      { content: `La présence de trois atomes impose une géométrie trigonale plane.`, correct: false, explanation: `La géométrie dépend des domaines autour de l'atome central.` },
      { content: `L'atome central est nécessairement $\\mathrm{sp}^3$.`, correct: false, explanation: `Deux directions sont compatibles avec sp.` },
    ],
    explanation: `Le nombre total d'atomes de la molécule ne détermine pas la géométrie : ce sont les domaines autour du centre qui comptent.`,
  },
  {
    order: 73,
    difficulty: 'HARD',
    format: 'QRM',
    question: `Le couple $\\ce{CO2}/\\ce{HCO3-}$ intervient dans le transport du dioxyde de carbone et le pouvoir tampon du sang. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Dans $\\ce{CO2}$, le carbone est $\\mathrm{sp}$ et la molécule est linéaire.`, correct: true, explanation: `Deux directions autour du carbone.` },
      { content: `Dans $\\ce{HCO3-}$, le carbone est $\\mathrm{sp}^2$ et les trois directions C–O sont approximativement coplanaires.`, correct: true, explanation: `Trois directions autour du carbone.` },
      { content: `$\\ce{CO2}$ possède deux liaisons $\\sigma$ et deux liaisons $\\pi$.`, correct: true, explanation: `Deux doubles liaisons C=O.` },
      { content: `Le carbone garde la même hybridation dans les deux espèces.`, correct: false, explanation: `Il passe du modèle sp au modèle sp2.` },
    ],
    explanation: `Cette comparaison relie décompte des liaisons, nombre de directions électroniques, hybridation et géométrie.`,
  },
  {
    order: 74,
    difficulty: 'HARD',
    format: 'QRM',
    question: `Le méthanal $\\ce{H2C=O}$ est utilisé pour la fixation de prélèvements en anatomopathologie. Quelles propositions sont exactes autour de son carbone ?`,
    choices: [
      { content: `Il possède trois directions de liaison $\\sigma$.`, correct: true, explanation: `Deux C–H et la composante sigma de C=O.` },
      { content: `Il est hybridé $\\mathrm{sp}^2$.`, correct: true, explanation: `Trois directions sigma.` },
      { content: `Une orbitale p non hybridée participe à la liaison $\\pi$ du carbonyle.`, correct: true, explanation: `La composante pi vient du recouvrement p–p.` },
      { content: `Son environnement est linéaire.`, correct: false, explanation: `Il est trigonal plan.` },
    ],
    explanation: `Le carbone carbonylé du méthanal est un centre sp2 trigonal plan conservant une orbitale p pour la liaison pi.`,
  },
  {
    order: 75,
    difficulty: 'HARD',
    format: 'QRM',
    question: `À propos de l'éthylène $\\ce{CH2=CH2}$, quelles propositions sont exactes ?`,
    choices: [
      { content: `Chaque carbone est $\\mathrm{sp}^2$.`, correct: true, explanation: `Trois directions sigma par carbone.` },
      { content: `Les six atomes de la molécule sont coplanaires dans le modèle simplifié.`, correct: true, explanation: `Les plans sp2 des deux carbones sont alignés.` },
      { content: `La liaison $\\pi$ limite la rotation autour de C=C.`, correct: true, explanation: `Les orbitales p doivent rester parallèles.` },
      { content: `Une rotation libre autour de C=C conserve intégralement le recouvrement latéral.`, correct: false, explanation: `Elle désaligne les orbitales p.` },
    ],
    explanation: `L'éthylène relie directement hybridation sp2, planéité et rigidité de la double liaison.`,
  },
  {
    order: 76,
    difficulty: 'HARD',
    format: 'QRU',
    question: `Le carbone du cyanure d'hydrogène $\\ce{H-C#N}$ est $\\mathrm{sp}$. Quelle représentation de ses orbitales de valence après hybridation est correcte ?`,
    choices: [
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{sp}', boxes: ['up', 'up'] }, { label: '2\\mathrm{p}', boxes: ['up', 'up'] }] },
        correct: true,
        explanation: `Deux sp et deux p non hybridées, chacune simplement occupée.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{sp}^{2}', boxes: ['up', 'up', 'up'] }, { label: '2\\mathrm{p}', boxes: ['up'] }] },
        correct: false,
        explanation: `Cela correspond à sp2.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{sp}^{3}', boxes: ['up', 'up', 'up', 'up'] }] },
        correct: false,
        explanation: `Cela correspond à sp3.`,
      },
      {
        content: { type: 'quantum-boxes', orbitals: [{ label: '2\\mathrm{s}', boxes: ['pair'] }, { label: '2\\mathrm{p}', boxes: ['up', 'up', 'empty'] }] },
        correct: false,
        explanation: `État atomique avant redistribution et hybridation.`,
      },
    ],
    explanation: `Un carbone sp utilise deux orbitales hybrides pour les deux composantes sigma et conserve deux orbitales p pour les deux composantes pi.`,
  },
  {
    order: 77,
    difficulty: 'HARD',
    format: 'QRM',
    question: `Deux orbitales atomiques $\\mathrm{p}$ compatibles se combinent axialement. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Deux orbitales atomiques conduisent à deux orbitales moléculaires.`, correct: true, explanation: `Le nombre d'orbitales est conservé.` },
      { content: `Une combinaison peut être liante $\\sigma$ et l'autre antiliante $\\sigma^*$.`, correct: true, explanation: `Combinaison en phase et en opposition de phase.` },
      { content: `L'orbitale liante présente une densité accrue entre les noyaux.`, correct: true, explanation: `Cette densité stabilise l'édifice.` },
      { content: `$\\sigma^*$ est une orbitale atomique localisée sur un seul atome.`, correct: false, explanation: `C'est une orbitale moléculaire.` },
    ],
    explanation: `La combinaison des OA produit une paire d'OM, l'une liante et l'autre antiliante, de propriétés énergétiques opposées.`,
  },
  {
    order: 78,
    difficulty: 'HARD',
    format: 'QRM',
    question: `On compare $\\ce{NH3}$, $\\ce{NH4+}$, $\\ce{H2O}$ et $\\ce{H3O+}$. Quelles propositions sont exactes ?`,
    choices: [
      { content: `$\\ce{NH3}$ et $\\ce{H3O+}$ sont $\\mathrm{AX}_3\\mathrm{E}_1$ et pyramidaux.`, correct: true, explanation: `Trois liaisons et un doublet.` },
      { content: `$\\ce{NH4+}$ est $\\mathrm{AX}_4$ et tétraédrique.`, correct: true, explanation: `Quatre liaisons sans doublet.` },
      { content: `$\\ce{H2O}$ est $\\mathrm{AX}_2\\mathrm{E}_2$ et son angle est inférieur à celui de $\\ce{NH3}$.`, correct: true, explanation: `Deux doublets non liants compriment davantage l'angle.` },
      { content: `Les quatre centres sont décrits comme $\\mathrm{sp}^2$.`, correct: false, explanation: `Ils sont compatibles avec quatre domaines sp3.` },
    ],
    explanation: `La géométrie visible dépend du nombre de doublets non liants, même lorsque l'organisation électronique repose sur quatre domaines.`,
  },
  {
    order: 79,
    difficulty: 'HARD',
    format: 'QRM',
    question: `On compare $\\ce{PCl5}$ et $\\ce{SF6}$ dans le modèle de Gillespie. Quelles propositions sont exactes ?`,
    choices: [
      { content: `$\\ce{PCl5}$ est $\\mathrm{AX}_5$ et bipyramidal trigonal.`, correct: true, explanation: `Cinq directions autour du phosphore.` },
      { content: `$\\ce{SF6}$ est $\\mathrm{AX}_6$ et octaédrique.`, correct: true, explanation: `Six directions autour du soufre.` },
      { content: `Dans $\\ce{PCl5}$, les positions axiales et équatoriales ne sont pas géométriquement équivalentes.`, correct: true, explanation: `Leurs environnements angulaires diffèrent.` },
      { content: `$\\ce{SF6}$ ne comporte que deux directions de liaison.`, correct: false, explanation: `Il en comporte six.` },
    ],
    explanation: `Les coordinences cinq et six permettent de distinguer bipyramide trigonale et octaèdre.`,
  },
  {
    order: 80,
    difficulty: 'HARD',
    format: 'QRP',
    requiredSelectionCount: 2,
    question: `On compare $\\ce{HCN}$, l'éthylène $\\ce{C2H4}$ et le benzène $\\ce{C6H6}$. Sélectionnez exactement les deux propositions correctes.`,
    choices: [
      { content: `Dans $\\ce{HCN}$, le carbone est $\\mathrm{sp}$ et la molécule est linéaire.`, correct: true, explanation: `Deux directions autour du carbone.` },
      { content: `Dans le benzène, les carbones sont $\\mathrm{sp}^2$ et le système $\\pi$ est délocalisé.`, correct: true, explanation: `C'est la base du cycle aromatique.` },
      { content: `Dans l'éthylène, chaque carbone est $\\mathrm{sp}$ et la rotation C=C est libre.`, correct: false, explanation: `Les carbones sont sp2 et la liaison pi limite la rotation.` },
      { content: `Dans le benzène, les carbones sont $\\mathrm{sp}^3$.`, correct: false, explanation: `Ils sont sp2.` },
    ],
    explanation: `HCN, l'éthylène et le benzène illustrent respectivement sp, sp2 localisé et sp2 associé à un système pi aromatique délocalisé.`,
  },
  {
    order: 85,
    difficulty: 'HARD',
    format: 'QRPL',
    requiredSelectionCount: 5,
    question: `Parmi les dix associations suivantes, sélectionnez exactement les cinq correctes.`,
    choices: [
      { content: `$\\ce{CO2}$ → centre carboné $\\mathrm{sp}$, linéaire.`, correct: true, explanation: `Deux directions C–O.` },
      { content: `$\\ce{CH4}$ → carbone $\\mathrm{sp}^3$, tétraédrique.`, correct: true, explanation: `Quatre liaisons simples.` },
      { content: `$\\ce{BH3}$ → bore $\\mathrm{sp}^2$, trigonal plan.`, correct: true, explanation: `Trois directions.` },
      { content: `$\\ce{NH3}$ → centre $\\mathrm{sp}^3$, géométrie pyramidale.`, correct: true, explanation: `Trois liaisons et un doublet.` },
      { content: `$\\ce{SF6}$ → type $\\mathrm{AX}_6$, octaédrique.`, correct: true, explanation: `Six directions.` },
      { content: `$\\ce{H2O}$ → centre $\\mathrm{sp}$, linéaire.`, correct: false, explanation: `L'oxygène est sp3 et la molécule coudée.` },
      { content: `$\\ce{C2H2}$ → carbones $\\mathrm{sp}^3$.`, correct: false, explanation: `Ils sont sp.` },
      { content: `$\\ce{C2H4}$ → carbones $\\mathrm{sp}$.`, correct: false, explanation: `Ils sont sp2.` },
      { content: `$\\ce{PCl5}$ → type $\\mathrm{AX}_4$, tétraédrique.`, correct: false, explanation: `Il est AX5, bipyramidal trigonal.` },
      { content: `$\\ce{BeH2}$ → centre $\\mathrm{sp}^2$, trigonal plan.`, correct: false, explanation: `Il est sp et linéaire.` },
    ],
    explanation: `Cette sélection croise hybridation et nomenclature de Gillespie pour plusieurs géométries de référence du chapitre.`,
  },
  {
    order: 86,
    difficulty: 'HARD',
    format: 'QRM',
    question: `Le lactate est mesuré dans certaines situations d'hypoperfusion. On considère l'acide lactique $\\ce{CH3-CH(OH)-C(=O)-OH}$. Quelles propositions sont exactes ?`,
    choices: [
      { content: `Le carbone du méthyle est $\\mathrm{sp}^3$.`, correct: true, explanation: `Quatre directions de liaisons simples.` },
      { content: `Le carbone portant le groupe OH est $\\mathrm{sp}^3$.`, correct: true, explanation: `Il ne participe qu'à des liaisons simples.` },
      { content: `Le carbone du carboxyle est $\\mathrm{sp}^2$ et conserve une orbitale p non hybridée.`, correct: true, explanation: `Le carbonyle impose une composante pi.` },
      { content: `Les trois carbones possèdent la même hybridation.`, correct: false, explanation: `Deux sont sp3 et un est sp2.` },
    ],
    explanation: `Une même molécule biologique peut contenir plusieurs environnements d'hybridation, déterminés localement par les liaisons de chaque carbone.`,
  },
];
