import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_E_ORDER = 5;

export const SECTION_E_SYNTHESIS_PRACTICE_QUIZ_SLUG =
  `section-e-synthesis-practice-aldehydes-cetones`;
export const SECTION_E_SYNTHESIS_MASTER_QUIZ_SLUG =
  `section-e-synthesis-master-examen-aldehydes-cetones`;

export const SECTION_E_SYNTHESIS_PRACTICE_QUESTION_ORDERS: number[] = [121, 122, 123, 124, 125, 126, 127, 128, 129, 130];
export const SECTION_E_SYNTHESIS_MASTER_QUESTION_ORDERS: number[] = [131, 132, 133, 134, 135, 136, 137, 138, 139, 140];

export const SECTION_E_QUIZZES: SeedQuiz[] = [
  {
    order: 13,
    slug: SECTION_E_SYNTHESIS_PRACTICE_QUIZ_SLUG,
    title: `Synthèse guidée : aldéhydes et cétones`,
    description: `Mobiliser les préparations, propriétés électroniques et principales réactions des composés carbonylés dans des situations guidées.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_E_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 121 },
      { type: 'QUESTION', questionOrder: 122 },
      { type: 'QUESTION', questionOrder: 123 },
      { type: 'QUESTION', questionOrder: 124 },
      { type: 'QUESTION', questionOrder: 125 },
      { type: 'QUESTION', questionOrder: 126 },
      { type: 'QUESTION', questionOrder: 127 },
      {
        type: 'GROUP',
        title: `Un organomagnésien face à deux carbonyles`,
        sharedStatement: `Le bromure d’éthylmagnésium $\\mathrm{CH_3CH_2MgBr}$ réagit séparément avec **A**, l’éthanal, et **B**, la propanone. Les deux milieux sont ensuite hydrolysés.`,
        questionOrders: [128, 129, 130],
      },
    ],
  },
  {
    order: 14,
    slug: SECTION_E_SYNTHESIS_MASTER_QUIZ_SLUG,
    title: `Synthèse type examen : composés carbonylés`,
    description: `Résoudre des questions transversales mêlant voies de préparation, polarité, additions nucléophiles, oxydabilité et cyclisation des sucres.`,
    stage: 'MASTER',
    sectionOrder: SECTION_E_ORDER,
    items: [
      {
        type: 'GROUP',
        title: `Enchaînement de synthèse en deux étapes`,
        sharedStatement: `**Étape 1** : le chlorure de propanoyle est réduit de manière contrôlée. **Étape 2** : le produit obtenu réagit avec le bromure d’éthylmagnésium, puis le milieu est hydrolysé.`,
        questionOrders: [131, 132, 133],
      },
      { type: 'QUESTION', questionOrder: 134 },
      { type: 'QUESTION', questionOrder: 135 },
      { type: 'QUESTION', questionOrder: 136 },
      { type: 'QUESTION', questionOrder: 137 },
      {
        type: 'GROUP',
        title: `Cyclisation de la forme linéaire du glucose`,
        sharedStatement: `Un groupe hydroxyle interne du glucose attaque sa fonction aldéhyde terminale et forme la forme cyclique majoritaire.`,
        questionOrders: [138, 139, 140],
      },
    ],
  },
];

export const SECTION_E_QUESTIONS: SeedQuestion[] = [
  {
    order: 121,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Parmi les associations suivantes, lesquelles sont correctes ?`,
    choices: [
      `Alcool primaire + oxydation ménagée → aldéhyde.`,
      `Alcool secondaire + oxydation → cétone.`,
      `Aldéhyde + réduction → alcool primaire.`,
      `Cétone + réduction → alcool tertiaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les transformations de base relient alcool primaire–aldéhyde et alcool secondaire–cétone ; la réduction d'une cétone donne un alcool secondaire.`,
    choiceExplanations: [
      `C'est la préparation classique.`,
      `Le carbonyle interne est formé.`,
      `Le groupe $\\mathrm{-CHO}$ devient $\\mathrm{-CH_2OH}$.`,
      `Le produit est secondaire, pas tertiaire.`,
    ],
  },
  {
    order: 122,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la polarité d'un composé carbonylé :`,
    choices: [
      `Le carbone du carbonyle est électrophile.`,
      `Un hydrure peut l'attaquer.`,
      `Un organomagnésien peut former avec lui une liaison carbone–carbone.`,
      `L'oxygène rend le carbone carbonylé nucléophile.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La polarisation $\\mathrm{C^{\\delta+}{=}O^{\\delta-}}$ explique les additions nucléophiles.`,
    choiceExplanations: [
      `Le carbone est déficitaire en électrons.`,
      `L'hydrure est nucléophile.`,
      `Le fragment carboné est ajouté.`,
      `Le carbone est électrophile.`,
    ],
  },
  {
    order: 123,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Comparaison des organomagnésiens :`,
    choices: [
      `Avec un aldéhyde, ils conduisent généralement à un alcool secondaire.`,
      `Avec une cétone, ils conduisent généralement à un alcool tertiaire.`,
      `Une hydrolyse finale est nécessaire.`,
      `Ils retirent toujours un carbone au substrat.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'organomagnésien ajoute un groupe carboné et l'hydrolyse transforme l'alcoolate en alcool.`,
    choiceExplanations: [
      `Un second substituant carboné est ajouté à l'aldéhyde.`,
      `Un troisième est ajouté à la cétone.`,
      `Elle fournit le proton du groupe $\\mathrm{OH}$.`,
      `Le squelette est allongé, non raccourci.`,
    ],
  },
  {
    order: 124,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Réactions avec les amines :`,
    choices: [
      `Une amine primaire peut donner une imine.`,
      `Une amine secondaire peut donner un iminium.`,
      `L'élimination d'eau favorise la condensation.`,
      `Une amine tertiaire donne nécessairement un alcool primaire selon la fiche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La classe de l'amine conditionne le produit carbone–azote obtenu.`,
    choiceExplanations: [
      `C'est l'association du cours.`,
      `C'est l'association du cours.`,
      `L'eau est un produit qu'il est utile d'éliminer.`,
      `Cette transformation n'est pas indiquée.`,
    ],
  },
  {
    order: 125,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos du carbone en position alpha d'un carbonyle :`,
    choices: [
      `Il peut être déprotoné par une base forte s'il porte un hydrogène.`,
      `Il peut alors devenir nucléophile.`,
      `Il peut réagir avec un électrophile.`,
      `Il est toujours identique au carbone carbonylé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fonctionnalisation alpha exploite un centre carboné voisin du carbonyle, distinct du carbone $\\mathrm{C{=}O}$.`,
    choiceExplanations: [
      `La base enlève un proton alpha.`,
      `L'espèce obtenue est riche en électrons.`,
      `Une nouvelle liaison se forme.`,
      `Les deux carbones sont adjacents, pas identiques.`,
    ],
  },
  {
    order: 126,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Oxydabilité :`,
    choices: [
      `Un aldéhyde peut s'oxyder en acide carboxylique.`,
      `Une cétone est présentée comme inerte dans les conditions simples du cours.`,
      `Un aldéhyde oxydé réduit l'agent oxydant.`,
      `Une cétone est toujours plus réductrice qu'un aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La différence d'oxydabilité permet de distinguer aldéhydes et cétones.`,
    choiceExplanations: [
      `Le groupe $\\mathrm{-CHO}$ devient $\\mathrm{-COOH}$.`,
      `C'est la propriété retenue.`,
      `Les deux demi-réactions sont couplées.`,
      `Le cours affirme l'inverse.`,
    ],
  },
  {
    order: 127,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un aldéhyde peut être obtenu :`,
    choices: [
      `Par oxydation ménagée d'un alcool primaire.`,
      `Par réduction contrôlée d'un chlorure d'acyle.`,
      `Par oxydation d'un alcool secondaire.`,
      `Dans certains cas par coupure oxydante d'un alcène.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Plusieurs voies convergent vers l'aldéhyde : alcool primaire, dérivé d'acide activé et certains alcènes.`,
    choiceExplanations: [
      `C'est une voie directe.`,
      `Le chlorure d'acyle est réductible en aldéhyde.`,
      `Un alcool secondaire donne une cétone.`,
      `La nature des substituants peut conduire à un aldéhyde.`,
    ],
  },
  {
    order: 128,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quel produit obtient-on à partir de l'éthanal ?`,
    choices: [
      `Un alcool secondaire.`,
      `Un alcool contenant le groupe éthyle ajouté.`,
      `Un alcool primaire.`,
      `Un produit formé après hydrolyse de l'intermédiaire magnésien.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `L'éthanal reçoit un groupe éthyle et donne un alcool secondaire après hydrolyse.`,
    choiceExplanations: [
      `Le carbone alcoolique porte deux groupes carbonés.`,
      `Le nucléophile est incorporé.`,
      `Un aldéhyde autre que le méthanal ne donne pas un alcool primaire avec un organomagnésien.`,
      `L'hydrolyse est indispensable.`,
    ],
  },
  {
    order: 129,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Quel produit obtient-on à partir de la propanone ?`,
    choices: [
      `Un alcool tertiaire.`,
      `Un alcool dont le carbone fonctionnel porte trois groupes carbonés.`,
      `Un aldéhyde.`,
      `Un produit ayant une liaison carbone–carbone nouvelle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La cétone possède déjà deux groupes carbonés ; l'organomagnésien apporte le troisième.`,
    choiceExplanations: [
      `C'est la classe obtenue.`,
      `Le carbone alcoolique est trisubstitué.`,
      `Le carbonyle est converti en alcool.`,
      `Le groupe éthyle est ajouté.`,
    ],
  },
  {
    order: 130,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans les deux expériences :`,
    choices: [
      `Le carbone carbonylé est le centre électrophile attaqué.`,
      `Le fragment éthyle agit comme nucléophile.`,
      `La réaction diminue le nombre d'atomes de carbone.`,
      `Une hydrolyse finale forme le groupe $\\mathrm{OH}$.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les deux additions suivent le même principe électronique, mais la classe de l'alcool dépend du substrat.`,
    choiceExplanations: [
      `La liaison $\\mathrm{C{=}O}$ est polarisée.`,
      `Le groupe éthyle apporte des électrons.`,
      `Un carbone supplémentaire est incorporé.`,
      `L'alcoolate est protoné.`,
    ],
  },
  {
    order: 131,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Après l'étape 1, quel intermédiaire organique est attendu ?`,
    choices: [
      `Un aldéhyde.`,
      `Le propanal.`,
      `Une cétone.`,
      `Un alcool primaire.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `La réduction contrôlée du chlorure de propanoyle donne le propanal.`,
    choiceExplanations: [
      `Le motif $\\mathrm{-COCl}$ devient $\\mathrm{-CHO}$.`,
      `Le squelette compte trois carbones.`,
      `Aucun second groupe carboné n'est ajouté.`,
      `La réduction n'est pas encore poussée à l'alcool.`,
    ],
  },
  {
    order: 132,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Après l'étape 2, quel produit est attendu ?`,
    choices: [
      `Un alcool secondaire.`,
      `Un alcool comportant cinq carbones.`,
      `Un alcool tertiaire.`,
      `Un produit ayant incorporé le groupe éthyle.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le propanal à trois carbones reçoit un groupe éthyle à deux carbones et donne un alcool secondaire.`,
    choiceExplanations: [
      `L'aldéhyde porte déjà un groupe propyle et un hydrogène.`,
      `Le nombre total est $3+2=5$.`,
      `Une cétone aurait conduit à un alcool tertiaire.`,
      `Le nucléophile carboné est ajouté.`,
    ],
  },
  {
    order: 133,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quels principes expliquent l'enchaînement ?`,
    choices: [
      `L'activation de l'acide permet l'accès sélectif à l'aldéhyde.`,
      `Le carbone de l'aldéhyde est électrophile.`,
      `Le fragment carboné de l'organomagnésien est nucléophile.`,
      `La seconde étape est une oxydation de l'aldéhyde.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La première étape prépare le carbonyle ; la seconde construit une liaison $\\mathrm{C{-}C}$ par addition nucléophile.`,
    choiceExplanations: [
      `Le chlorure d'acyle est un dérivé activé.`,
      `L'oxygène polarise la liaison.`,
      `Il attaque le carbonyle.`,
      `Il s'agit d'une addition suivie d'hydrolyse, pas d'une oxydation.`,
    ],
  },
  {
    order: 134,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les transformations suivantes, lesquelles augmentent le degré d'oxydation du carbone fonctionnel ?`,
    choices: [
      `Alcool primaire → aldéhyde.`,
      `Aldéhyde → acide carboxylique.`,
      `Cétone → alcool secondaire.`,
      `Aldéhyde → alcool primaire.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Les deux premières sont des oxydations ; les deux dernières sont des réductions.`,
    choiceExplanations: [
      `Le carbone perd des liaisons à l'hydrogène et gagne un carbonyle.`,
      `Le groupe $\\mathrm{-CHO}$ devient $\\mathrm{-COOH}$.`,
      `Le carbonyle devient alcool.`,
      `Le groupe aldéhyde devient $\\mathrm{CH_2OH}$.`,
    ],
  },
  {
    order: 135,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une molécule $\\mathrm{RCOCH_2R'}$ est traitée par une base forte puis par $\\mathrm{E^+}$. À propos du bilan :`,
    choices: [
      `Le carbone $\\mathrm{CH_2}$ voisin peut être fonctionnalisé.`,
      `Le groupe $\\mathrm{E}$ peut se fixer en position alpha.`,
      `Le carbonyle est nécessairement réduit en alcool.`,
      `La première étape crée un centre nucléophile carboné.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La séquence exploite l'acidité des hydrogènes alpha et la réaction du centre nucléophile avec l'électrophile.`,
    choiceExplanations: [
      `Il porte l'hydrogène arraché.`,
      `La nouvelle liaison est formée à ce site.`,
      `Aucun hydrure n'est utilisé.`,
      `La base prépare l'attaque.`,
    ],
  },
  {
    order: 136,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Un composé carbonylé réagit avec une amine secondaire. Quelles propositions sont cohérentes avec la fiche ?`,
    choices: [
      `L'amine agit comme nucléophile.`,
      `Un iminium peut être formé.`,
      `L'élimination d'eau favorise le produit.`,
      `Un alcool primaire est le produit direct obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La condensation carbone–azote se distingue d'une réduction : aucun alcool n'est attendu sans hydrure.`,
    choiceExplanations: [
      `Le doublet de l'azote attaque.`,
      `C'est le produit associé à l'amine secondaire.`,
      `La réaction est une condensation.`,
      `Aucun réducteur n'est présent.`,
    ],
  },
  {
    order: 137,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans le cadre simplifié du cours appliqué aux sucres :`,
    choices: [
      `La fonction aldéhyde du glucose explique son caractère réducteur.`,
      `La fonction cétone du fructose est présentée comme non oxydable.`,
      `La forme cyclique du glucose est un hémiacétal.`,
      `La cyclisation nécessite obligatoirement une amine primaire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les applications aux sucres mobilisent à la fois l'oxydabilité des carbonyles et la formation intramoléculaire d'un hémiacétal.`,
    choiceExplanations: [
      `L'aldéhyde peut s'oxyder.`,
      `C'est la simplification de la fiche.`,
      `Un alcool attaque l'aldéhyde.`,
      `Aucun azote n'est impliqué.`,
    ],
  },
  {
    order: 138,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle fonction de la forme linéaire est attaquée lors de la cyclisation ?`,
    choices: [
      `La fonction aldéhyde.`,
      `Le carbone électrophile du groupe $\\mathrm{CHO}$.`,
      `Une fonction amide.`,
      `Le groupe $\\mathrm{CH_2OH}$ comme électrophile principal.`,
    ],
    correctChoiceIndexes: [0, 1],
    explanation: `Le groupe hydroxyle interne attaque le carbone du carbonyle terminal.`,
    choiceExplanations: [
      `C'est le groupe carbonylé du glucose.`,
      `La polarisation rend ce carbone électrophile.`,
      `Le glucose n'en possède pas.`,
      `Le groupe alcool agit plutôt comme nucléophile.`,
    ],
  },
  {
    order: 139,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle fonction nouvelle apparaît ?`,
    choices: [
      `Un hémiacétal.`,
      `Un centre lié à deux oxygènes, dont un groupe $\\mathrm{OH}$.`,
      `Une cétone.`,
      `Un cycle oxygéné.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le carbone aldéhydique devient un carbone hémiacétalique et l'oxygène de l'alcool entre dans le cycle.`,
    choiceExplanations: [
      `C'est la fonction issue de l'addition alcool–aldéhyde.`,
      `C'est sa signature structurale.`,
      `Le carbonyle est consommé.`,
      `La fermeture intramoléculaire l'introduit.`,
    ],
  },
  {
    order: 140,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelles affirmations décrivent correctement la représentation du produit ?`,
    choices: [
      `Une représentation en perspective est plus fidèle au relief du cycle.`,
      `Le cycle réel n'est pas strictement plan.`,
      `La formule brute du glucose change lors de la cyclisation.`,
      `La stéréochimie des substituants doit être respectée.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La cyclisation est une réorganisation sans changement de formule brute, mais elle crée une structure tridimensionnelle dont la stéréochimie est essentielle.`,
    choiceExplanations: [
      `Elle montre la conformation spatiale.`,
      `Le cycle est plissé.`,
      `Aucun atome n'est ajouté ou retiré.`,
      `Les orientations au-dessus ou au-dessous du cycle ont un sens.`,
    ],
  },
];
