import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_D_ORDER = 4;

export const SECTION_D_HALOGENES_GRIGNARD_DISCOVERY_QUIZ_SLUG =
  `section-d-discovery-derives-halogenes-organomagnesiens`;
export const SECTION_D_SN1_PRACTICE_QUIZ_SLUG =
  `section-d-practice-substitution-nucleophile-sn1`;
export const SECTION_D_SN2_COMPARISON_MASTER_QUIZ_SLUG =
  `section-d-master-substitution-nucleophile-sn2-comparaison`;

export const SECTION_D_HALOGENES_GRIGNARD_DISCOVERY_QUESTION_ORDERS: number[] = [91, 92, 93, 94, 95, 96, 97, 98, 99, 100];
export const SECTION_D_SN1_PRACTICE_QUESTION_ORDERS: number[] = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110];
export const SECTION_D_SN2_COMPARISON_MASTER_QUESTION_ORDERS: number[] = [111, 112, 113, 114, 115, 116, 117, 118, 119, 120];

export const SECTION_D_QUIZZES: SeedQuiz[] = [
  {
    order: 10,
    slug: SECTION_D_HALOGENES_GRIGNARD_DISCOVERY_QUIZ_SLUG,
    title: `Dérivés halogénés : propriétés, préparation et organomagnésiens`,
    description: `Reconnaître un dérivé halogéné, prévoir sa préparation à partir d'un alcène ou d'un alcool et comprendre la formation d'un réactif de Grignard.`,
    stage: 'DISCOVER',
    sectionOrder: SECTION_D_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 91 },
      { type: 'QUESTION', questionOrder: 92 },
      { type: 'QUESTION', questionOrder: 93 },
      { type: 'QUESTION', questionOrder: 94 },
      { type: 'QUESTION', questionOrder: 95 },
      { type: 'QUESTION', questionOrder: 96 },
      { type: 'QUESTION', questionOrder: 97 },
      {
        type: 'GROUP',
        title: `De l'alcène au réactif de Grignard`,
        sharedStatement: `On considère la séquence suivante : un alcène réagit d'abord avec $\mathrm{HX}$ pour donner un dérivé halogéné $\mathrm{R{-}X}$ ; ce dernier réagit ensuite avec le magnésium pour former $\mathrm{RMgX}$.`,
        questionOrders: [98, 99, 100],
      },
    ],
  },
  {
    order: 11,
    slug: SECTION_D_SN1_PRACTICE_QUIZ_SLUG,
    title: `Substitution nucléophile de type SN1`,
    description: `Décomposer le mécanisme SN1 en deux étapes, caractériser le carbocation plan et prévoir la racémisation d'un centre asymétrique.`,
    stage: 'PRACTICE',
    sectionOrder: SECTION_D_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 101 },
      { type: 'QUESTION', questionOrder: 102 },
      { type: 'QUESTION', questionOrder: 103 },
      { type: 'QUESTION', questionOrder: 104 },
      { type: 'QUESTION', questionOrder: 105 },
      { type: 'QUESTION', questionOrder: 106 },
      { type: 'QUESTION', questionOrder: 107 },
      {
        type: 'GROUP',
        title: `SN1 sur un dérivé halogéné chiral`,
        sharedStatement: `Un dérivé halogéné optiquement pur possède un carbone asymétrique lié à $\mathrm{X}$ et à trois substituants différents. Il réagit selon un mécanisme $\mathrm{S_N1}$ avec un nucléophile $\mathrm{Nu^-}$.`,
        questionOrders: [108, 109, 110],
      },
    ],
  },
  {
    order: 12,
    slug: SECTION_D_SN2_COMPARISON_MASTER_QUIZ_SLUG,
    title: `Substitution nucléophile de type SN2 et comparaison SN1/SN2`,
    description: `Reconnaître le mécanisme concerté SN2, prévoir l'inversion de configuration et comparer ses conséquences stéréochimiques à celles de la SN1.`,
    stage: 'MASTER',
    sectionOrder: SECTION_D_ORDER,
    items: [
      { type: 'QUESTION', questionOrder: 111 },
      { type: 'QUESTION', questionOrder: 112 },
      { type: 'QUESTION', questionOrder: 113 },
      { type: 'QUESTION', questionOrder: 114 },
      { type: 'QUESTION', questionOrder: 115 },
      { type: 'QUESTION', questionOrder: 116 },
      { type: 'QUESTION', questionOrder: 117 },
      {
        type: 'GROUP',
        title: `Choix d'un mécanisme en synthèse stéréosélective`,
        sharedStatement: `Lors de la synthèse d'un intermédiaire chiral destiné à une molécule d'intérêt médical, deux conditions sont comparées pour remplacer $\mathrm{X}$ par $\mathrm{Nu}$ : **I**, conditions favorisant une $\mathrm{S_N1}$ ; **II**, conditions favorisant une $\mathrm{S_N2}$. Le dérivé halogéné initial est optiquement pur.`,
        questionOrders: [118, 119, 120],
      },
    ],
  },
];

export const SECTION_D_QUESTIONS: SeedQuestion[] = [
  {
    order: 91,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des dérivés halogénés :`,
    choices: [
      `Ils peuvent être notés $\mathrm{R{-}X}$.`,
      `$\mathrm{R}$ représente un radical carboné.`,
      `$\mathrm{X}$ représente un halogène.`,
      `Ils sont présentés comme des produits généralement très toxiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `La notation générale associe un squelette carboné à un halogène ; la fiche attire aussi l'attention sur leur toxicité fréquente.`,
    choiceExplanations: [
      `C'est la formule générale utilisée.`,
      `Il s'agit de la partie carbonée.`,
      `Le symbole peut représenter notamment le chlore ou le brome.`,
      `Cette propriété impose des précautions de manipulation.`,
    ],
  },
  {
    order: 92,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `L'addition électrophile de $\mathrm{HX}$ sur un alcène :`,
    choices: [
      `Consomme la double liaison carbone-carbone.`,
      `Ajoute globalement un hydrogène et un halogène.`,
      `Peut conduire à un dérivé halogéné $\mathrm{R{-}X}$.`,
      `Correspond à une déshydratation d'alcool.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les éléments de $\mathrm{HX}$ s'ajoutent de part et d'autre de l'ancienne double liaison pour former un haloalcane.`,
    choiceExplanations: [
      `La liaison pi de l'alcène disparaît.`,
      `Ce sont les deux fragments incorporés.`,
      `Le produit porte une liaison carbone-halogène.`,
      `Une déshydratation élimine de l'eau et concerne un alcool.`,
    ],
  },
  {
    order: 93,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Lors de la préparation d'un dérivé chloré à partir d'un alcool :`,
    choices: [
      `Le groupe $\mathrm{-OH}$ peut être remplacé par un atome de chlore.`,
      `Un agent halogénant est utilisé.`,
      `Le produit peut s'écrire $\mathrm{R{-}Cl}$.`,
      `Le squelette carboné doit nécessairement être détruit.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La transformation substitue le groupe hydroxyle par le chlore sans modifier le squelette carboné dans le bilan simplifié.`,
    choiceExplanations: [
      `C'est la modification fonctionnelle recherchée.`,
      `Il active le remplacement du groupe hydroxyle.`,
      `Cette formule correspond au dérivé chloré obtenu.`,
      `Le radical $\mathrm{R}$ est conservé.`,
    ],
  },
  {
    order: 94,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les agents halogénants cités pour obtenir un dérivé chloré figurent :`,
    choices: [
      `$\mathrm{PCl_5}$.`,
      `$\mathrm{SOCl_2}$.`,
      `$\mathrm{POCl_3}$.`,
      `$\mathrm{NaBH_4}$ comme agent chlorant principal.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche cite plusieurs réactifs chlorés adaptés à la conversion d'un alcool en dérivé chloré.`,
    choiceExplanations: [
      `Il est explicitement mentionné.`,
      `Le chlorure de thionyle est également cité.`,
      `Il figure dans la liste du cours.`,
      `Le borohydrure de sodium est un réducteur, non un agent chlorant.`,
    ],
  },
  {
    order: 95,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un dérivé halogéné de type $\mathrm{RCH_2{-}X}$, le carbone lié à l'halogène :`,
    choices: [
      `Présente un caractère électrophile.`,
      `Peut être attaqué par un nucléophile.`,
      `Porte nécessairement une charge négative complète avant toute réaction.`,
      `Est le centre impliqué dans une substitution nucléophile.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La polarisation de la liaison carbone-halogène rend le carbone déficient en électrons et donc sensible à l'attaque d'un nucléophile.`,
    choiceExplanations: [
      `C'est le caractère indiqué dans le cours.`,
      `Le nucléophile apporte un doublet à ce centre.`,
      `La charge négative apparaît sur le carbone dans l'organomagnésien, pas dans le dérivé initial.`,
      `Le nucléophile remplace l'halogène sur ce carbone.`,
    ],
  },
  {
    order: 96,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La formation d'un organomagnésien à partir d'un dérivé halogéné peut s'écrire :`,
    choices: [
      `$\mathrm{R{-}X + Mg → RMgX}$.`,
      `Le produit est appelé réactif de Grignard.`,
      `Le magnésium s'insère dans la liaison carbone-halogène dans l'écriture simplifiée.`,
      `Le produit est nécessairement un alcool.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le magnésium transforme le dérivé halogéné en organomagnésien $\mathrm{RMgX}$, qui est un réactif carboné nucléophile.`,
    choiceExplanations: [
      `C'est le bilan présenté.`,
      `Les deux appellations sont équivalentes dans le cours.`,
      `La formule du produit place le magnésium entre $\mathrm{R}$ et $\mathrm{X}$.`,
      `L'alcool ne sera obtenu qu'après réaction avec un composé électrophile puis hydrolyse.`,
    ],
  },
  {
    order: 97,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Dans un réactif de Grignard $\mathrm{RMgX}$ :`,
    choices: [
      `Le carbone lié au magnésium possède un caractère nucléophile.`,
      `Le carbone peut être représenté avec un caractère négatif.`,
      `La réactivité du carbone est inversée par rapport au dérivé halogéné initial.`,
      `Le carbone ne peut réagir avec aucun centre électrophile.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La liaison carbone-magnésium confère au carbone un caractère carbanionique, donc nucléophile, alors qu'il était électrophile dans $\mathrm{R{-}X}$.`,
    choiceExplanations: [
      `Il peut donner son doublet à un centre pauvre en électrons.`,
      `Cette représentation traduit sa polarisation.`,
      `C'est une inversion de polarité fonctionnelle.`,
      `Il réagit précisément avec des carbones électrophiles.`,
    ],
  },
  {
    order: 98,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant la première étape de la séquence :`,
    choices: [
      `Il s'agit d'une addition sur un alcène.`,
      `$\mathrm{H}$ et $\mathrm{X}$ sont ajoutés sur les deux carbones de l'ancienne double liaison.`,
      `Un dérivé halogéné est formé.`,
      `Le produit est déjà un organomagnésien.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'alcène est transformé en haloalcane par addition de $\mathrm{HX}$ ; le magnésium n'intervient qu'à l'étape suivante.`,
    choiceExplanations: [
      `La double liaison est consommée.`,
      `C'est le bilan de l'addition électrophile.`,
      `La nouvelle fonction est $\mathrm{C{-}X}$.`,
      `Aucun magnésium n'a encore été ajouté.`,
    ],
  },
  {
    order: 99,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant la deuxième étape de la séquence :`,
    choices: [
      `Le dérivé halogéné réagit avec le magnésium.`,
      `Un réactif de Grignard est obtenu.`,
      `Le carbone lié au magnésium devient nucléophile.`,
      `Le carbone conserve exclusivement le caractère électrophile qu'il avait dans $\mathrm{R{-}X}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'insertion du magnésium produit $\mathrm{RMgX}$ et inverse la polarité du carbone organique.`,
    choiceExplanations: [
      `C'est le réactif minéral ajouté.`,
      `$\mathrm{RMgX}$ est l'organomagnésien attendu.`,
      `La liaison $\mathrm{C{-}Mg}$ est polarisée dans ce sens.`,
      `Le comportement du carbone est justement inversé.`,
    ],
  },
  {
    order: 100,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Le produit final $\mathrm{RMgX}$ de la séquence peut ensuite :`,
    choices: [
      `Réagir avec un aldéhyde.`,
      `Réagir avec une cétone.`,
      `Réagir avec un ester.`,
      `Former une nouvelle liaison carbone-carbone avec un carbone électrophile.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les organomagnésiens réagissent avec les composés carbonylés et, plus généralement, avec les composés possédant un carbone électrophile.`,
    choiceExplanations: [
      `L'aldéhyde possède un carbone carbonylé électrophile.`,
      `Il en va de même pour la cétone.`,
      `L'ester peut subir deux additions selon le cours.`,
      `Le groupe carboné de l'organomagnésien est incorporé au produit.`,
    ],
  },
  {
    order: 101,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le bilan général d'une substitution nucléophile sur un dérivé halogéné peut s'écrire :`,
    choices: [
      `$\mathrm{R{-}X + Nu^- → R{-}Nu + X^-}$.`,
      `Le nucléophile remplace l'halogène.`,
      `L'halogène part sous forme d'ion $\mathrm{X^-}$ dans le bilan simplifié.`,
      `Le produit conserve nécessairement la liaison $\mathrm{C{-}X}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Une substitution remplace le groupe partant halogéné par le nucléophile sur le même carbone.`,
    choiceExplanations: [
      `C'est l'équation générale du cours.`,
      `Une nouvelle liaison $\mathrm{C{-}Nu}$ est formée.`,
      `Le groupe partant emporte le doublet de la liaison.`,
      `La liaison carbone-halogène est rompue.`,
    ],
  },
  {
    order: 102,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une substitution nucléophile de type $\mathrm{S_N1}$ :`,
    choices: [
      `Se déroule en deux temps.`,
      `Passe par la formation d'un carbocation.`,
      `Présente une étape de départ de $\mathrm{X^-}$ avant l'attaque du nucléophile.`,
      `Est un mécanisme concerté en une seule étape.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La $\mathrm{S_N1}$ est séquentielle : ionisation du dérivé halogéné puis attaque du carbocation par le nucléophile.`,
    choiceExplanations: [
      `Deux étapes distinctes sont retenues.`,
      `C'est l'intermédiaire réactionnel central.`,
      `Le groupe partant quitte d'abord le substrat.`,
      `Cette description correspond plutôt à la $\mathrm{S_N2}$.`,
    ],
  },
  {
    order: 103,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le carbocation intermédiaire d'une $\mathrm{S_N1}$ est présenté comme :`,
    choices: [
      `Plan autour du carbone chargé.`,
      `Électrophile.`,
      `Accessible au nucléophile par les deux faces du plan.`,
      `Tétraédrique rigide imposant une attaque par une seule face.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La géométrie plane du carbocation permet au nucléophile d'attaquer de part et d'autre.`,
    choiceExplanations: [
      `C'est la géométrie indiquée dans le schéma.`,
      `La charge positive rend le carbone déficient en électrons.`,
      `Cette accessibilité explique la racémisation.`,
      `La planéité ne bloque pas une face unique.`,
    ],
  },
  {
    order: 104,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors de la première étape d'une $\mathrm{S_N1}$ :`,
    choices: [
      `La liaison carbone-halogène se rompt.`,
      `$\mathrm{X^-}$ quitte le substrat.`,
      `Un carbocation est formé.`,
      `Le nucléophile est déjà lié au carbone avant le départ de $\mathrm{X^-}$.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'ionisation précède l'attaque nucléophile : le départ du groupe halogéné crée le carbocation.`,
    choiceExplanations: [
      `C'est la rupture déterminante.`,
      `Il joue le rôle de groupe partant.`,
      `Le carbone devient positivement chargé.`,
      `L'attaque intervient dans la seconde étape.`,
    ],
  },
  {
    order: 105,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors de la seconde étape d'une $\mathrm{S_N1}$ :`,
    choices: [
      `Le nucléophile attaque le carbocation.`,
      `Une nouvelle liaison carbone-nucléophile est formée.`,
      `L'attaque peut avoir lieu sur l'une ou l'autre face du carbocation plan.`,
      `Un second carbocation doit obligatoirement être formé.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le nucléophile capture l'intermédiaire plan ; les deux faces accessibles conduisent aux deux configurations possibles lorsque le carbone devient asymétrique.`,
    choiceExplanations: [
      `Il fournit le doublet de la nouvelle liaison.`,
      `C'est le produit de substitution.`,
      `La planéité autorise les deux trajectoires.`,
      `Aucun second carbocation n'est requis dans ce schéma.`,
    ],
  },
  {
    order: 106,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `La racémisation associée à une $\mathrm{S_N1}$ s'explique par :`,
    choices: [
      `La planéité du carbocation intermédiaire.`,
      `L'attaque possible du nucléophile par les deux faces.`,
      `La formation des deux configurations en proportions idéalisées voisines.`,
      `Une inversion unique et obligatoire sans mélange.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le passage par un intermédiaire achiral plan efface l'information de face et permet la formation des deux énantiomères.`,
    choiceExplanations: [
      `Le centre initial perd sa géométrie tétraédrique.`,
      `Les deux côtés sont accessibles.`,
      `Le cours schématise une probabilité de 50 % de chaque côté.`,
      `Cette conséquence caractérise la $\mathrm{S_N2}$, non la $\mathrm{S_N1}$.`,
    ],
  },
  {
    order: 107,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la stéréochimie d'une $\mathrm{S_N1}$ sur un centre asymétrique optiquement pur :`,
    choices: [
      `L'intermédiaire carbocationique est plan et non chiral au centre concerné.`,
      `Le produit peut être un mélange racémique.`,
      `L'activité optique globale du mélange peut s'annuler.`,
      `La configuration initiale est nécessairement conservée à 100 %.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le centre asymétrique disparaît temporairement dans le carbocation plan, puis les deux configurations sont recréées lors de l'attaque.`,
    choiceExplanations: [
      `La planéité supprime l'asymétrie locale.`,
      `Les deux énantiomères sont formés.`,
      `Leurs rotations opposées se compensent dans un racémique idéal.`,
      `La réaction ne donne pas un produit unique de configuration conservée.`,
    ],
  },
  {
    order: 108,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Au départ de $\mathrm{X^-}$ dans l'énoncé commun :`,
    choices: [
      `Un carbocation plan est formé.`,
      `Le centre asymétrique initial perd momentanément son caractère tétraédrique.`,
      `Le nucléophile a déjà imposé une configuration unique.`,
      `Cette étape précède l'attaque de $\mathrm{Nu^-}$.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La première étape de la $\mathrm{S_N1}$ efface la configuration du centre en formant un carbocation plan.`,
    choiceExplanations: [
      `C'est l'intermédiaire du mécanisme.`,
      `La géométrie autour du carbone devient plane.`,
      `Le nucléophile n'a pas encore attaqué.`,
      `L'ordre des étapes est ionisation puis capture.`,
    ],
  },
  {
    order: 109,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Lors de l'attaque de $\mathrm{Nu^-}$ dans l'énoncé commun :`,
    choices: [
      `Les deux faces du carbocation sont accessibles.`,
      `Les deux configurations du produit peuvent être formées.`,
      `Une racémisation est attendue dans le modèle du cours.`,
      `Le nucléophile ne peut attaquer que du côté opposé à $\mathrm{X}$, resté en place.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Puisque $\mathrm{X^-}$ est déjà parti et que le carbocation est plan, le nucléophile peut arriver de chaque côté.`,
    choiceExplanations: [
      `Aucune face n'est imposée dans le modèle simplifié.`,
      `Les attaques opposées donnent des énantiomères.`,
      `C'est la conséquence stéréochimique retenue.`,
      `Le groupe $\mathrm{X}$ n'est plus lié au carbone.`,
    ],
  },
  {
    order: 110,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À l'issue de cette $\mathrm{S_N1}$ :`,
    choices: [
      `Le groupe $\mathrm{X}$ a été remplacé par $\mathrm{Nu}$.`,
      `Le produit peut être un mélange racémique.`,
      `L'obtention d'un seul énantiomère pur n'est pas la conséquence attendue du mécanisme.`,
      `La réaction s'est déroulée en une étape concertée.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le produit de substitution est formé via deux étapes et la planéité de l'intermédiaire entraîne une perte de pureté énantiomérique.`,
    choiceExplanations: [
      `C'est le bilan de substitution.`,
      `Les deux configurations sont obtenues.`,
      `La $\mathrm{S_N1}$ n'est donc pas privilégiée lorsque la pureté optique doit être conservée.`,
      `Le mécanisme concerté correspond à la $\mathrm{S_N2}$.`,
    ],
  },
  {
    order: 111,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une substitution nucléophile de type $\mathrm{S_N2}$ :`,
    choices: [
      `Se déroule en une seule étape.`,
      `Est un mécanisme concerté.`,
      `Associe progressivement la formation de la liaison $\mathrm{C{-}Nu}$ et la rupture de la liaison $\mathrm{C{-}X}$.`,
      `Passe obligatoirement par un carbocation isolable.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Dans une $\mathrm{S_N2}$, l'attaque du nucléophile et le départ du groupe halogéné ont lieu simultanément au sein d'une étape unique.`,
    choiceExplanations: [
      `Aucun intermédiaire n'est isolé dans le schéma.`,
      `Les changements de liaison sont couplés.`,
      `L'une se forme pendant que l'autre se rompt.`,
      `Le carbocation est caractéristique de la $\mathrm{S_N1}$.`,
    ],
  },
  {
    order: 112,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans le mécanisme $\mathrm{S_N2}$ présenté :`,
    choices: [
      `Le nucléophile s'approche du côté opposé au groupe partant.`,
      `Le départ de $\mathrm{X}$ est provoqué au fur et à mesure de l'approche.`,
      `Le carbone subit une inversion de sa disposition spatiale.`,
      `Le nucléophile attaque indifféremment les deux faces d'un carbocation plan.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'attaque arrière impose une trajectoire unique et provoque l'inversion de configuration du centre concerné.`,
    choiceExplanations: [
      `Le groupe partant occupe l'autre côté du carbone.`,
      `Les deux événements sont simultanés.`,
      `La géométrie s'inverse comme un parapluie.`,
      `Aucun carbocation plan n'est formé.`,
    ],
  },
  {
    order: 113,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La conséquence stéréochimique caractéristique d'une $\mathrm{S_N2}$ sur un centre asymétrique est :`,
    choices: [
      `Une inversion de configuration.`,
      `La conservation de l'asymétrie du centre si les quatre substituants restent différents.`,
      `L'obtention d'un seul produit stéréochimique à partir d'un substrat optiquement pur dans le modèle du cours.`,
      `Une racémisation obligatoire.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La réaction est stéréospécifique : une seule trajectoire d'attaque transforme une configuration en l'autre.`,
    choiceExplanations: [
      `C'est l'inversion décrite dans la fiche.`,
      `Le centre reste chiral, mais sa configuration est renversée.`,
      `Un substrat pur conduit à un produit de substitution pur dans le modèle idéal.`,
      `La racémisation est associée à la $\mathrm{S_N1}$.`,
    ],
  },
  {
    order: 114,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `À propos de l'intermédiaire réactionnel en $\mathrm{S_N2}$ :`,
    choices: [
      `Aucun carbocation libre n'est formé.`,
      `La réaction passe par un état de transition et non par deux étapes séparées.`,
      `Le nucléophile et le groupe partant sont impliqués simultanément.`,
      `Un carbocation plan est indispensable à l'inversion.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le mécanisme concerté ne possède pas d'intermédiaire carbocationique ; l'inversion résulte de l'attaque arrière.`,
    choiceExplanations: [
      `Le carbone ne devient pas un cation isolé.`,
      `L'état de transition relie directement réactifs et produit.`,
      `La liaison entrante et la liaison sortante évoluent ensemble.`,
      `La présence d'un carbocation conduirait plutôt à une $\mathrm{S_N1}$.`,
    ],
  },
  {
    order: 115,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On compare $\mathrm{S_N1}$ et $\mathrm{S_N2}$. Quelle(s) proposition(s) est(sont) correcte(s) ?`,
    choices: [
      `La $\mathrm{S_N1}$ comporte deux étapes, la $\mathrm{S_N2}$ une seule.`,
      `La $\mathrm{S_N1}$ passe par un carbocation, la $\mathrm{S_N2}$ non.`,
      `La $\mathrm{S_N1}$ peut racémiser, la $\mathrm{S_N2}$ inverse la configuration.`,
      `Les deux mécanismes ont nécessairement les mêmes conséquences stéréochimiques.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les mécanismes diffèrent à la fois par leur nombre d'étapes, leur intermédiaire et leur stéréochimie.`,
    choiceExplanations: [
      `C'est la distinction cinétique et mécanistique majeure.`,
      `Le carbocation est spécifique au schéma $\mathrm{S_N1}$.`,
      `Planéité et attaque arrière produisent des résultats différents.`,
      `Leurs conséquences sont au contraire opposées dans le modèle du cours.`,
    ],
  },
  {
    order: 116,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Les facteurs mentionnés comme pouvant orienter une substitution vers $\mathrm{S_N1}$ ou $\mathrm{S_N2}$ comprennent :`,
    choices: [
      `La nature du nucléophile.`,
      `La nature du solvant.`,
      `L'environnement du carbone portant le groupe partant.`,
      `Uniquement la couleur du produit.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La fiche cite le nucléophile, le solvant et la nature des substituants autour du carbone comme paramètres d'orientation.`,
    choiceExplanations: [
      `Sa force et sa disponibilité peuvent influencer le mécanisme.`,
      `Il stabilise différemment les espèces impliquées.`,
      `L'encombrement et la stabilité du centre interviennent.`,
      `La couleur n'est pas un critère mécanistique.`,
    ],
  },
  {
    order: 117,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans une stratégie visant à préserver une pureté optique élevée :`,
    choices: [
      `Une $\mathrm{S_N2}$ peut être privilégiée lorsque les autres facteurs le permettent.`,
      `La $\mathrm{S_N2}$ donne une inversion prévisible.`,
      `Une $\mathrm{S_N1}$ risque de conduire à une racémisation.`,
      `Une $\mathrm{S_N1}$ garantit toujours un seul énantiomère.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le caractère stéréospécifique de la $\mathrm{S_N2}$ est souvent recherché lorsque l'identité stéréochimique du produit est importante.`,
    choiceExplanations: [
      `Elle évite le passage par un intermédiaire plan.`,
      `La configuration finale peut être anticipée.`,
      `Le mélange des deux énantiomères réduit la pureté optique.`,
      `C'est précisément ce que la $\mathrm{S_N1}$ ne garantit pas.`,
    ],
  },
  {
    order: 118,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant les conditions **I** favorisant la $\mathrm{S_N1}$ :`,
    choices: [
      `Un carbocation plan est attendu.`,
      `Le mécanisme comporte deux étapes.`,
      `Une racémisation du centre concerné est possible.`,
      `Une inversion unique est garantie sans mélange.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La voie $\mathrm{S_N1}$ passe par l'ionisation puis l'attaque des deux faces du carbocation.`,
    choiceExplanations: [
      `La perte de $\mathrm{X^-}$ crée cet intermédiaire.`,
      `Le nucléophile intervient après sa formation.`,
      `Les deux configurations peuvent être obtenues.`,
      `Cette conséquence correspond à la voie $\mathrm{S_N2}$.`,
    ],
  },
  {
    order: 119,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant les conditions **II** favorisant la $\mathrm{S_N2}$ :`,
    choices: [
      `Le nucléophile attaque du côté opposé au groupe partant.`,
      `La réaction est concertée.`,
      `Une inversion de configuration est attendue.`,
      `Un carbocation plan libre est formé avant l'attaque.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L'attaque arrière et le départ simultané de $\mathrm{X}$ conduisent à une inversion stéréospécifique.`,
    choiceExplanations: [
      `C'est la trajectoire géométrique imposée.`,
      `Une seule étape relie substrat et produit.`,
      `Le centre chiral est renversé.`,
      `Aucun carbocation n'est impliqué.`,
    ],
  },
  {
    order: 120,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Pour la synthèse de l'intermédiaire médical chiral de l'énoncé :`,
    choices: [
      `La voie $\mathrm{S_N2}$ est la plus cohérente avec l'obtention d'un produit optiquement pur dans le modèle du cours.`,
      `La configuration du produit $\mathrm{S_N2}$ sera inversée par rapport à celle du substrat.`,
      `La voie $\mathrm{S_N1}$ expose à une perte de pureté énantiomérique.`,
      `Le choix du mécanisme est sans importance pour la stéréochimie.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Lorsque l'objectif est un seul stéréoisomère, la $\mathrm{S_N2}$ offre une inversion prévisible, tandis que la $\mathrm{S_N1}$ tend à racémiser.`,
    choiceExplanations: [
      `Elle conserve l'information stéréochimique sous forme inversée.`,
      `C'est la conséquence de l'attaque arrière.`,
      `Les deux faces du carbocation peuvent être attaquées.`,
      `Le mécanisme détermine directement la distribution stéréochimique.`,
    ],
  },
];
