/** UE14 – Biologie cellulaire – Chapitre 2 */
import type { SeedQuestion, SeedQuiz } from './health-training-ue14.shared';

export const SECTION_A_QUESTIONS: SeedQuestion[] = [
  {
    order: 1,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos de la membrane plasmique :` ,
    choices: [
      `Elle délimite la cellule.`,
      `Elle sépare cytosol et milieu extracellulaire.`,
      `Elle fusionne spontanément avec la membrane voisine.`,
      `Elle entoure toutes les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La membrane plasmique est la limite de la cellule ; un espace persiste entre deux cellules adjacentes.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 2,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `La membrane plasmique :` ,
    choices: [
      `A une épaisseur d’environ 7,5 nm.`,
      `Est classiquement visible en microscopie optique.`,
      `Présente deux feuillets denses aux électrons en ME.`,
      `Peut entourer des cellules régulières ou irrégulières.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `Le cours insiste sur sa très faible épaisseur et son étude en microscopie électronique.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 3,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Sa composition globale simplifiée est :` ,
    choices: [
      `70 % de lipides.`,
      `30 % de protéines.`,
      `Un petit peu de glucides.`,
      `Toujours identique selon les cellules.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La composition varie selon les cellules et les zones membranaires.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 4,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant les lipides membranaires :` ,
    choices: [
      `Les phospholipides sont amphiphiles.`,
      `Le cholestérol stabilise la bicouche.`,
      `Ils ont une tête hydrophile et des queues hydrophobes.`,
      `Les têtes se font face au centre de la bicouche.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les têtes sont orientées vers les milieux aqueux et les queues vers le centre hydrophobe.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 5,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Lorsqu’on mélange des phospholipides à l’eau :` ,
    choices: [
      `Ils peuvent former une émulsion.`,
      `Ils peuvent s’organiser en bicouche.`,
      `Les têtes se tournent vers l’eau.`,
      `La bicouche laisse passer librement toutes les molécules hydrophiles.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La bicouche constitue au contraire une barrière relative aux molécules hydrophiles.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 6,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Les protéines transmembranaires :` ,
    choices: [
      `Traversent la bicouche grâce à des segments hydrophobes.`,
      `Sont souvent organisées en hélice alpha.`,
      `Participent à la perméabilité sélective.`,
      `Sont uniquement hydrophobes.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Elles comportent aussi des domaines hydrophiles exposés aux milieux aqueux.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 7,
    difficulty: 'EASY',
    answerFormat: 'SINGLE',
    question: `Orientation générale indiquée pour une protéine transmembranaire :` ,
    choices: [
      `COOH interne et NH2 externe.`,
      `COOH externe et NH2 interne.`,
      `Les deux extrémités sont du même côté.`,
      `Aucune orientation n’est mentionnée.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La fiche précise une orientation générale COOH intracellulaire / NH2 extracellulaire.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 8,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Parmi les ancrages membranaires cités :` ,
    choices: [
      `Acides gras : face intracellulaire.`,
      `GPI : face extracellulaire.`,
      `Boucle hydrophobe : cavéoline.`,
      `NCAM : exemple d’ancrage GPI.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les trois modes d’association non transmembranaires sont explicitement détaillés.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 9,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `À propos des glucides membranaires :` ,
    choices: [
      `Ils peuvent former des glycolipides.`,
      `Ils peuvent former des glycoprotéines.`,
      `Ils sont externes.`,
      `Ils participent au glycocalyx.`,
    ],
    correctChoiceIndexes: [0, 1, 2, 3],
    explanation: `Les glucides membranaires sont localisés à la face externe.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 10,
    difficulty: 'EASY',
    answerFormat: 'MULTIPLE',
    question: `Concernant l’hématie :` ,
    choices: [
      `La spectrine est l’élément principal du cytosquelette.`,
      `La glycophorine est riche en charges négatives.`,
      `L’ankyrine est une protéine périphérique interne.`,
      `La bande 3 n’intervient pas dans les échanges gazeux.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `La bande 3 participe au transport du CO2.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 11,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos de la bande 3 :` ,
    choices: [
      `Le dimère de bande 3 participe au transport du CO2.`,
      `Sa polarité est dite inversée.`,
      `La bande 4.1 interagit avec la glycophorine.`,
      `L’ankyrine augmente la diffusion latérale illimitée de la bande 3.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `L’ankyrine limite au contraire la diffusion latérale de la bande 3.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 12,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Le système ABO :` ,
    choices: [
      `Dépend d’antigènes glucidiques sur les hématies.`,
      `Comporte des anticorps dans le sérum.`,
      `Le groupe O n’a pas de motif A ou B.`,
      `Repose sur des protéines transmembranaires A ou B.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les déterminants ABO sont de nature glucidique.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 13,
    difficulty: 'MEDIUM',
    answerFormat: 'SINGLE',
    question: `Quel exemple correspond à une protéine ancrée par acides gras sur la face intracellulaire ?` ,
    choices: [
      `La protéine G.`,
      `La NCAM.`,
      `La fibronectine.`,
      `La glycophorine.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La protéine G est l’exemple donné pour cet ancrage lipidique.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 14,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Observe la figure :

![Structure](/images/training/ue14/biologie-cellulaire/membrane-plasmique/structure-membrane-plasmique.png)

Quelles propositions sont correctes ?` ,
    choices: [
      `Le glycocalyx est externe.`,
      `Le cholestérol est inséré dans la bicouche.`,
      `Les phosphatidylsérines sont indiquées surtout à l’extérieur.`,
      `Une protéine périphérique est dessinée côté cytosolique.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le schéma rappelle l’asymétrie membranaire et la localisation externe du glycocalyx.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 15,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `À propos des faces membranaires :` ,
    choices: [
      `Les glycolipides sont externes.`,
      `Les glycoprotéines participent au glycocalyx.`,
      `Le cytosol correspond au milieu extracellulaire.`,
      `La phosphatidylcholine est plutôt externe.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le cytosol désigne le milieu intracellulaire.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 16,
    difficulty: 'MEDIUM',
    answerFormat: 'MULTIPLE',
    question: `Une bicouche phospholipidique pure est relativement imperméable :` ,
    choices: [
      `À la plupart des molécules hydrosolubles.`,
      `Parce que son cœur est hydrophobe.`,
      `Ce qui justifie l’existence de transporteurs.`,
      `Seulement à O2 et CO2.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `O2 et CO2 diffusent plus librement que les solutés hydrophiles.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 17,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `On compare une protéine qui traverse la membrane et une autre accolée à la face interne :` ,
    choices: [
      `La première est transmembranaire.`,
      `La seconde peut être périphérique.`,
      `La seconde est nécessairement un glycolipide.`,
      `La première peut participer aux transports.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Une protéine périphérique ne traverse pas la bicouche.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 18,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Concernant l’hématie et sa membrane :` ,
    choices: [
      `La spectrine contribue à la forme biconcave.`,
      `La glycophorine favorise la répulsion entre hématies.`,
      `La bande 3 est une protéine périphérique libre du cytosol.`,
      `L’ankyrine limite la diffusion latérale de la bande 3.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La bande 3 est une protéine membranaire, non une protéine périphérique libre.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 19,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `Quel couple est correctement associé ?` ,
    choices: [
      `NCAM — ancrage GPI extracellulaire.`,
      `Protéine G — ancrage GPI extracellulaire.`,
      `Cavéoline — glycoprotéine de MEC.`,
      `Fibronectine — protéine transmembranaire de l’hématie.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `La NCAM est l’exemple d’ancrage GPI cité.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 20,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Parmi les propositions suivantes :` ,
    choices: [
      `La composition membranaire peut varier d’une cellule à l’autre.`,
      `Elle peut varier selon les zones d’une même membrane.`,
      `La membrane est homogène et statique.`,
      `Elle contient lipides, protéines et glucides.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `La membrane est dynamique et hétérogène.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 21,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `En observant la figure de structure membranaire :` ,
    choices: [
      `La bicouche sépare milieu extracellulaire et cytosol.`,
      `La protéine transmembranaire traverse la bicouche.`,
      `Le glycocalyx est interne.`,
      `Le cholestérol participe à l’organisation de la bicouche.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Le glycocalyx est externe.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 22,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le caractère amphiphile des phospholipides explique que :` ,
    choices: [
      `Les têtes interagissent avec l’eau.`,
      `Les queues se regroupent au centre.`,
      `La bicouche crée une barrière entre deux milieux aqueux.`,
      `Les ions diffusent alors librement.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les ions diffusent mal dans le cœur hydrophobe.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 23,
    difficulty: 'HARD',
    answerFormat: 'SINGLE',
    question: `Quel élément appartient surtout à la face interne de l’hématie ?` ,
    choices: [
      `L’ankyrine.`,
      `La fibronectine.`,
      `Le glycocalyx.`,
      `Le collagène IV.`,
    ],
    correctChoiceIndexes: [0],
    explanation: `L’ankyrine est une protéine périphérique interne de l’hématie.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 24,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Dans le groupe O du système ABO :` ,
    choices: [
      `Les hématies ne portent pas de motif A ou B.`,
      `Il existe une protéine O transmembranaire spécifique.`,
      `Les antigènes ABO sont glucidiques.`,
      `La notion de groupe implique aussi des anticorps sériques.`,
    ],
    correctChoiceIndexes: [0, 2, 3],
    explanation: `Il n’existe pas de protéine O spécifique dans ce cadre.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 25,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Une membrane riche en glycoprotéines externes :` ,
    choices: [
      `Participe au glycocalyx.`,
      `Expose ces glucides au milieu extracellulaire.`,
      `Est compatible avec une membrane plasmique.`,
      `Porte ces glucides exclusivement côté cytosolique.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Les glucides membranaires sont externes.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 26,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `La membrane est à la fois fine et résistante :` ,
    choices: [
      `Sa solidité n’empêche pas sa faible épaisseur.`,
      `Elle est classiquement étudiée en microscopie électronique.`,
      `Elle correspond à une monocouche lipidique rigide.`,
      `Elle peut limiter des cellules de formes variées.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Il s’agit d’une bicouche, non d’une monocouche.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 27,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Si l’on compare une glycoprotéine et une protéine transmembranaire sans glucides :` ,
    choices: [
      `La première peut contribuer au glycocalyx.`,
      `La seconde peut participer à la perméabilité sélective.`,
      `Les deux sont obligatoirement périphériques.`,
      `Une glycoprotéine peut être transmembranaire.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les catégories “glycoprotéine” et “transmembranaire” ne s’excluent pas.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 28,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Relèvent principalement de la face externe :` ,
    choices: [
      `Le glycocalyx.`,
      `Les glycolipides.`,
      `Les phosphatidylsérines.`,
      `Les glycoprotéines.`,
    ],
    correctChoiceIndexes: [0, 1, 3],
    explanation: `Les phosphatidylsérines sont plutôt internes.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
    ],
  },
  {
    order: 29,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Le passage de l’hématie dans un petit capillaire est favorisé par :` ,
    choices: [
      `La spectrine.`,
      `Le glycocalyx de toutes les cellules sanguines.`,
      `La forme biconcave.`,
      `Le collagène IV.`,
    ],
    correctChoiceIndexes: [0, 2],
    explanation: `Le cytosquelette membranaire de l’hématie contribue à sa déformabilité.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Non conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
  {
    order: 30,
    difficulty: 'HARD',
    answerFormat: 'MULTIPLE',
    question: `Quelle synthèse est juste ?` ,
    choices: [
      `La membrane est une bicouche contenant aussi protéines, cholestérol et glucides.`,
      `Elle est asymétrique.`,
      `La membrane de l’hématie illustre une spécialisation cellulaire.`,
      `Elle est inerte et uniforme.`,
    ],
    correctChoiceIndexes: [0, 1, 2],
    explanation: `Le chapitre présente une membrane spécialisée et fonctionnelle.` ,
    choiceExplanations: [
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Conforme au cours.`,
      `Non conforme au cours.`,
    ],
  },
];

export const SECTION_A_QUIZZES: SeedQuiz[] = [
  {
    order: 1,
    slug: `generalites-membrane-plasmique`,
    title: `Généralités sur la membrane plasmique`,
    description: `Définition, composition générale et lipides membranaires.`,
    stage: 'DISCOVER',
    sectionOrder: 1,
    questionOrders: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    order: 2,
    slug: `proteines-glucides-membranaires`,
    title: `Protéines et glucides membranaires`,
    description: `Ancrages, glycocalyx, membrane de l’hématie et système ABO.`,
    stage: 'PRACTICE',
    sectionOrder: 1,
    questionOrders: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  {
    order: 3,
    slug: `membrane-hematie-et-analyse-structurale`,
    title: `Membrane de l’hématie et analyse structurale`,
    description: `Applications et lecture de schéma membranaire.`,
    stage: 'MASTER',
    sectionOrder: 1,
    questionOrders: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
];
