/**
 * UE14 – Biologie cellulaire – Chapitre 4
 * Contenu pédagogique fondé sur la fiche 2024-2025 du Tutorat Santé de Reims.
 */
import type { PrismaClient } from '@prisma/client';
import type { SeedQuestion, SeedQuiz, SeedSection } from './health-training-ue14.shared';
import { SECTION_A_QUESTIONS, SECTION_A_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-1.section-a.seed';
import { SECTION_B_QUESTIONS, SECTION_B_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-1.section-b.seed';
import { SECTION_C_QUESTIONS, SECTION_C_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-1.section-c.seed';
import { SECTION_D_QUESTIONS, SECTION_D_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-1.section-d.seed';
import { SYNTHESIS_QUESTIONS, SYNTHESIS_QUIZZES } from './health-training-ue14-biologie-cellulaire-systeme-endomembranaire-1.synthesis.seed';
import { seedHealthTrainingChapter } from './health-training-ue14.shared';

const SUBJECT_LONG_DESCRIPTION = 'Sciences de la Vie et de la Terre';
const CHAPTER_SLUG = 'systeme-endomembranaire-flux-vesiculaires-endocytose-exocytose';

const sections: SeedSection[] = [
  { order: 1, title: `Compartiments et flux du système endomembranaire`, description: `Définition du SEM, compartiments, signaux et quatre flux membranaires.`, kind: 'THEME' },
  { order: 2, title: `Transport vésiculaire`, description: `Bourgeonnement, revêtements, déshabillage, cytosquelette, amarrage et fusion.`, kind: 'THEME' },
  { order: 3, title: `Endocytose`, description: `Pinocytose, phagocytose, voies par récepteurs et cavéoles, exemple du LDL.`, kind: 'THEME' },
  { order: 4, title: `Exocytose et fonctions intégrées`, description: `Exocytose constitutive ou régulée, transcytose, nutrition, mouvement et infection.`, kind: 'THEME' },
  { order: 5, title: `Synthèse du chapitre`, description: `Consolidation transversale des flux endo- et exocytaires.`, kind: 'SYNTHESIS' },
];

const questions: SeedQuestion[] = [
  ...SECTION_A_QUESTIONS,
  ...SECTION_B_QUESTIONS,
  ...SECTION_C_QUESTIONS,
  ...SECTION_D_QUESTIONS,
  ...SYNTHESIS_QUESTIONS,
];

const quizSeeds: SeedQuiz[] = [
  ...SECTION_A_QUIZZES,
  ...SECTION_B_QUIZZES,
  ...SECTION_C_QUIZZES,
  ...SECTION_D_QUIZZES,
  ...SYNTHESIS_QUIZZES,
];

const QUESTION_THEME_LABELS_BY_ORDER: Record<number, string[]> = {
  1: ["Compartiments et flux du SEM"],
  2: ["Compartiments et flux du SEM"],
  3: ["Compartiments et flux du SEM"],
  4: ["Compartiments et flux du SEM"],
  5: ["Compartiments et flux du SEM"],
  6: ["Compartiments et flux du SEM"],
  7: ["Compartiments et flux du SEM"],
  8: ["Compartiments et flux du SEM"],
  9: ["Compartiments et flux du SEM"],
  10: ["Compartiments et flux du SEM"],
  11: ["Compartiments et flux du SEM"],
  12: ["Compartiments et flux du SEM"],
  13: ["Compartiments et flux du SEM"],
  14: ["Compartiments et flux du SEM"],
  15: ["Compartiments et flux du SEM"],
  16: ["Compartiments et flux du SEM"],
  17: ["Compartiments et flux du SEM"],
  18: ["Compartiments et flux du SEM"],
  19: ["Compartiments et flux du SEM"],
  20: ["Compartiments et flux du SEM"],
  21: ["Compartiments et flux du SEM"],
  22: ["Compartiments et flux du SEM"],
  23: ["Compartiments et flux du SEM"],
  24: ["Compartiments et flux du SEM"],
  25: ["Compartiments et flux du SEM"],
  26: ["Compartiments et flux du SEM"],
  27: ["Compartiments et flux du SEM"],
  28: ["Compartiments et flux du SEM"],
  29: ["Compartiments et flux du SEM"],
  30: ["Compartiments et flux du SEM"],
  31: ["Transport vésiculaire"],
  32: ["Transport vésiculaire"],
  33: ["Transport vésiculaire"],
  34: ["Transport vésiculaire"],
  35: ["Transport vésiculaire"],
  36: ["Transport vésiculaire"],
  37: ["Transport vésiculaire"],
  38: ["Transport vésiculaire"],
  39: ["Transport vésiculaire"],
  40: ["Transport vésiculaire"],
  41: ["Transport vésiculaire"],
  42: ["Transport vésiculaire"],
  43: ["Transport vésiculaire"],
  44: ["Transport vésiculaire"],
  45: ["Transport vésiculaire"],
  46: ["Transport vésiculaire"],
  47: ["Transport vésiculaire"],
  48: ["Transport vésiculaire"],
  49: ["Transport vésiculaire"],
  50: ["Transport vésiculaire"],
  51: ["Transport vésiculaire"],
  52: ["Transport vésiculaire"],
  53: ["Transport vésiculaire"],
  54: ["Transport vésiculaire"],
  55: ["Transport vésiculaire"],
  56: ["Transport vésiculaire"],
  57: ["Transport vésiculaire"],
  58: ["Transport vésiculaire"],
  59: ["Transport vésiculaire"],
  60: ["Transport vésiculaire"],
  61: ["Endocytose"],
  62: ["Endocytose"],
  63: ["Endocytose"],
  64: ["Endocytose"],
  65: ["Endocytose"],
  66: ["Endocytose"],
  67: ["Endocytose"],
  68: ["Endocytose"],
  69: ["Endocytose"],
  70: ["Endocytose"],
  71: ["Endocytose"],
  72: ["Endocytose"],
  73: ["Endocytose"],
  74: ["Endocytose"],
  75: ["Endocytose"],
  76: ["Endocytose"],
  77: ["Endocytose"],
  78: ["Endocytose"],
  79: ["Endocytose"],
  80: ["Endocytose"],
  81: ["Endocytose"],
  82: ["Endocytose"],
  83: ["Endocytose"],
  84: ["Endocytose"],
  85: ["Endocytose"],
  86: ["Endocytose"],
  87: ["Endocytose"],
  88: ["Endocytose"],
  89: ["Endocytose"],
  90: ["Endocytose"],
  91: ["Exocytose et fonctions intégrées"],
  92: ["Exocytose et fonctions intégrées"],
  93: ["Exocytose et fonctions intégrées"],
  94: ["Exocytose et fonctions intégrées"],
  95: ["Exocytose et fonctions intégrées"],
  96: ["Exocytose et fonctions intégrées"],
  97: ["Exocytose et fonctions intégrées"],
  98: ["Exocytose et fonctions intégrées"],
  99: ["Exocytose et fonctions intégrées"],
  100: ["Exocytose et fonctions intégrées"],
  101: ["Exocytose et fonctions intégrées"],
  102: ["Exocytose et fonctions intégrées"],
  103: ["Exocytose et fonctions intégrées"],
  104: ["Exocytose et fonctions intégrées"],
  105: ["Exocytose et fonctions intégrées"],
  106: ["Exocytose et fonctions intégrées"],
  107: ["Exocytose et fonctions intégrées"],
  108: ["Exocytose et fonctions intégrées"],
  109: ["Exocytose et fonctions intégrées"],
  110: ["Exocytose et fonctions intégrées"],
  111: ["Exocytose et fonctions intégrées"],
  112: ["Exocytose et fonctions intégrées"],
  113: ["Exocytose et fonctions intégrées"],
  114: ["Exocytose et fonctions intégrées"],
  115: ["Exocytose et fonctions intégrées"],
  116: ["Exocytose et fonctions intégrées"],
  117: ["Exocytose et fonctions intégrées"],
  118: ["Exocytose et fonctions intégrées"],
  119: ["Exocytose et fonctions intégrées"],
  120: ["Exocytose et fonctions intégrées"],
  121: ["Synthèse du chapitre"],
  122: ["Synthèse du chapitre"],
  123: ["Synthèse du chapitre"],
  124: ["Synthèse du chapitre"],
  125: ["Synthèse du chapitre"],
  126: ["Synthèse du chapitre"],
  127: ["Synthèse du chapitre"],
  128: ["Synthèse du chapitre"],
  129: ["Synthèse du chapitre"],
  130: ["Synthèse du chapitre"],
  131: ["Synthèse du chapitre"],
  132: ["Synthèse du chapitre"],
  133: ["Synthèse du chapitre"],
  134: ["Synthèse du chapitre"],
  135: ["Synthèse du chapitre"],
  136: ["Synthèse du chapitre"],
  137: ["Synthèse du chapitre"],
  138: ["Synthèse du chapitre"],
  139: ["Synthèse du chapitre"],
  140: ["Synthèse du chapitre"],
};

export async function seedHealthTrainingUe14BiologieCellulaireSystemeEndomembranaire1(prisma: PrismaClient) {
  await seedHealthTrainingChapter({
    prisma,
    subjectLongDescription: SUBJECT_LONG_DESCRIPTION,
    chapterSlug: CHAPTER_SLUG,
    logLabel: 'UE14 Biologie cellulaire — chapitre 4',
    questionThemeLabelsByOrder: QUESTION_THEME_LABELS_BY_ORDER,
    questions,
    sections,
    quizSeeds,
    cleanupSectionOrders: [1, 2, 3, 4, 5],
  });
}