import { cn } from "@/lib/utils";

export const PROTEIN_DIAGRAM_NAMES = [
  "acid-basic-amino-acids",
  "amino-acid-chirality",
  "amino-acid-codes",
  "amino-acid-families",
  "amino-acid-general-structure",
  "amino-acid-ionization",
  "amino-acid-overview",
  "aromatic-amino-acids",
  "branched-amino-acids",
  "essential-amino-acids",
  "fischer-amino-acids",
  "hydroxyl-sulfur-amino-acids",
  "ninhydrin-reaction",
  "polarity-classes",
  "polarity-solubility",
  "proline-hydroxyproline",
  "uv-absorption",
  "alpha-helix",
  "beta-sheet",
  "ck-dimers",
  "disulfide-proteolysis",
  "four-levels-primary",
  "peptide-bond",
  "peptide-bond-rigidity",
  "peptide-size",
  "peptide-termini",
  "phi-psi-angles",
  "posttranslational-modifications",
  "proline-peptide-kink",
  "protein-denaturation-classification",
  "protein-domains",
  "protein-g-trimer",
  "quaternary-assemblies",
  "quaternary-structure",
  "tertiary-structure",
  "tetramer-examples",
  "aa-biological-precursors",
  "aa-neurotransmitter-precursors",
  "aa-structural-roles",
  "amyloid-app",
  "cyclosporine-aspartame",
  "cytokines-interleukins",
  "essential-aa-needs",
  "glucagon-insulin",
  "glucogenic-ketogenic-aa",
  "growth-factors",
  "insulin-maturation",
  "interferons-chemokines",
  "natriuretic-peptides",
  "opioid-peptides",
  "peptide-antibiotics",
  "peptide-biological-roles",
  "peptide-hormone-signaling",
  "pomc-glutathione",
  "transamination-methionine",
  "urea-cycle-aa",
  "abc-pgp",
  "adhesion-families",
  "antibody-classes",
  "antibody-epitope",
  "antibody-fab-fc",
  "antibody-h2l2",
  "antibody-multimers",
  "cftr-channel",
  "connexin-gap-junction",
  "gpcr-rhodopsin",
  "igcam",
  "insulin-receptor",
  "integrin-focal-adhesion",
  "ionotropic-channel",
  "metabotropic-receptor",
  "nuclear-receptor",
  "receptor-general",
  "selectin-cadherin",
  "serotonin-gaba-channels",
  "sodium-potassium-pump",
  "actin-microtubules",
  "collagen-alpha-chain",
  "collagen-classification",
  "collagen-crosslinks",
  "collagen-fibril",
  "collagen-gly-x-y",
  "collagen-overview",
  "collagen-triple-helix",
  "collagen-type-iv",
  "cytoskeleton-overview",
  "extracellular-matrix",
  "fibronectin",
  "hemoglobin-anomalies",
  "hemoglobin-conformations",
  "hemoglobin-structure",
  "laminin",
  "matrix-glycoproteins",
  "myosin-cycle",
  "protein-role-acronym",
  "sickle-albumin-lipoprotein",
] as const;

export type ProteinDiagramName = (typeof PROTEIN_DIAGRAM_NAMES)[number];

export function isProteinDiagramName(value: string): value is ProteinDiagramName {
  return (PROTEIN_DIAGRAM_NAMES as readonly string[]).includes(value);
}

const DATA: Record<ProteinDiagramName, { title: string; items: string[] }> = {
  "acid-basic-amino-acids": {"title": "Les acides aminés acides, leurs amides et les basiques", "items": ["L’acide aspartique et l’acide glutamique possèdent un second carboxyle.", "L’asparagine est l’amide dérivé de l’acide aspartique.", "La glutamine est l’amide dérivé de l’acide glutamique.", "Lysine, arginine et histidine sont classées parmi les acides aminés basiques."]},
  "amino-acid-chirality": {"title": "La chiralité des acides aminés", "items": ["Les acides aminés naturels sont des acides α-aminés.", "La glycine ne possède pas de centre chiral au carbone α.", "Un objet chiral n’est pas superposable à son image dans un miroir.", "Deux formes miroir sont appelées énantiomères."]},
  "amino-acid-codes": {"title": "La nomenclature des acides aminés", "items": ["Un acide aminé possède un nom usuel.", "Il peut être désigné par une abréviation à trois lettres.", "Il peut être désigné par une abréviation à une lettre.", "L’alanine peut être abrégée Ala ou A."]},
  "amino-acid-families": {"title": "Les acides aminés aliphatiques", "items": ["Leur chaîne latérale est carbonée, ouverte et linéaire ou ramifiée.", "La glycine possède un radical réduit à un hydrogène.", "L’alanine possède un radical méthyle.", "Leur chaîne latérale est décrite comme très apolaire et hydrophobe."]},
  "amino-acid-general-structure": {"title": "La structure commune d’un acide aminé", "items": ["Le carbone α porte une fonction amine.", "Le carbone α porte une fonction acide carboxylique.", "Le radical R différencie les acides aminés.", "Un hydrogène est également lié au carbone α dans la structure typique."]},
  "amino-acid-ionization": {"title": "L’ionisation et le point isoélectrique", "items": ["Les acides aminés possèdent au moins deux fonctions ionisables.", "Ils sont amphotères.", "Au pH isoélectrique, la charge nette est nulle.", "Les acides aminés basiques ont un pHi élevé et les acides un pHi bas."]},
  "amino-acid-overview": {"title": "Les acides aminés du monde vivant", "items": ["Le monde vivant compte environ 500 acides aminés différents.", "La masse molaire moyenne indiquée est d’environ 110 Da.", "Seuls 20 acides aminés protéinogènes entrent dans les protéines animales.", "Les acides aminés sont les unités de base des protéines."]},
  "aromatic-amino-acids": {"title": "Les acides aminés aromatiques", "items": ["La phénylalanine porte un noyau benzénique.", "La tyrosine porte un groupement phénol.", "Le tryptophane porte un noyau indole.", "L’indole associe un noyau benzénique et un cycle pyrrole accolés."]},
  "branched-amino-acids": {"title": "Les acides aminés branchés", "items": ["La valine possède un radical isopropyle.", "La leucine possède un radical isobutyle.", "L’isoleucine est un isomère de la leucine.", "Valine, leucine et isoleucine sont des acides aminés ramifiés."]},
  "essential-amino-acids": {"title": "Les acides aminés essentiels", "items": ["Un acide aminé essentiel n’est pas synthétisé par l’Homme en quantité suffisante.", "Il doit être apporté par l’alimentation.", "Leucine, thréonine, lysine et tryptophane figurent dans la liste du cours.", "Valine, méthionine, phénylalanine et isoleucine figurent dans la liste du cours."]},
  "fischer-amino-acids": {"title": "Les séries L et D en projection de Fischer", "items": ["Le COOH est placé en haut dans la projection décrite.", "Le carbone α est placé au centre.", "Un NH2 à gauche correspond à la série L.", "Un NH2 à droite correspond à la série D."]},
  "hydroxyl-sulfur-amino-acids": {"title": "Les acides aminés hydroxylés", "items": ["La sérine porte un alcool primaire.", "La thréonine porte un alcool secondaire.", "Le groupement hydroxyle confère un caractère polaire.", "Ces chaînes latérales peuvent former des liaisons hydrogène avec l’eau."]},
  "ninhydrin-reaction": {"title": "La réaction à la ninhydrine", "items": ["La ninhydrine réagit avec les acides aminés à amine primaire.", "La coloration obtenue est pourpre ou violette.", "La proline et l’hydroxyproline donnent une coloration jaune.", "La réaction est utilisée pour la séparation et le dosage des acides aminés."]},
  "polarity-classes": {"title": "La classification selon la polarité", "items": ["Glycine, alanine, valine, leucine et isoleucine figurent parmi les non polaires.", "Cystéine, tyrosine, sérine et thréonine figurent parmi les polaires neutres.", "Aspartate et glutamate sont polaires acides et chargés négativement.", "Lysine, arginine et histidine sont polaires basiques et chargés positivement."]},
  "polarity-solubility": {"title": "La solubilité des acides aminés", "items": ["La solubilité dépend du caractère hydrophile ou hydrophobe du radical.", "Les chaînes polaires favorisent les interactions avec l’eau.", "L’eau et l’éthanol sont cités comme solvants polaires.", "Deux acides aminés différents peuvent avoir des solubilités différentes."]},
  "proline-hydroxyproline": {"title": "La proline et la 4-hydroxyproline", "items": ["La proline possède une amine secondaire.", "Sa structure cyclique peut anguler une chaîne polypeptidique.", "La 4-hydroxyproline dérive de l’hydroxylation de la proline.", "La proline est classée parmi les acides aminés non polaires dans la fiche."]},
  "uv-absorption": {"title": "L’absorption ultraviolette des acides aminés", "items": ["La plupart des acides aminés absorbent à des longueurs d’onde inférieures à 230 nm.", "Les acides aminés aromatiques absorbent vers 280 nm.", "Phénylalanine, tyrosine et tryptophane sont concernés.", "La fiche ajoute l’histidine parmi les exceptions absorbant vers 280 nm."]},
  "alpha-helix": {"title": "L’hélice alpha", "items": ["L’hélice α est un enroulement régulier vers la droite.", "Les chaînes latérales sont orientées vers l’extérieur.", "Elle comporte environ 3,6 acides aminés par tour.", "Sa stabilité repose sur des liaisons hydrogène parallèles à l’axe."]},
  "beta-sheet": {"title": "Les feuillets plissés beta", "items": ["Ils sont formés de brins reliés par des liaisons hydrogène.", "Les brins peuvent être parallèles ou antiparallèles.", "Les chaînes latérales alternent de part et d’autre du feuillet.", "Les immunoglobulines sont riches en feuillets β."]},
  "ck-dimers": {"title": "Les créatine kinases CK-MM et CK-MB", "items": ["CK-MM est un homodimère.", "CK-MM possède deux sous-unités M.", "CK-MB est un hétérodimère.", "CK-MB associe une sous-unité M et une sous-unité B."]},
  "disulfide-proteolysis": {"title": "Le clivage protéolytique et les ponts disulfure", "items": ["Un clivage protéolytique peut activer un précurseur.", "La trypsine est citée comme exemple de protéine activée par clivage.", "Un pont disulfure résulte de l’oxydation de deux cystéines.", "Les ponts disulfure peuvent être intra- ou interchaînes."]},
  "four-levels-primary": {"title": "La structure primaire", "items": ["Elle correspond à l’enchaînement des acides aminés.", "Elle se forme au cours de la traduction de l’ARNm.", "L’ordre dépend de l’information génétique.", "La séquence influence la structure spatiale et l’activité."]},
  "peptide-bond": {"title": "La liaison peptidique", "items": ["Elle relie le carboxyle d’un acide aminé à l’amine du suivant.", "Elle permet l’association en chaîne des acides aminés.", "Peptides et protéines comportent des liaisons peptidiques.", "La séquence et la conformation influencent la fonction."]},
  "peptide-bond-rigidity": {"title": "La rigidité de la liaison peptidique", "items": ["La liaison peptidique est plane.", "Elle est rigide.", "La rotation autour de la liaison C–N est bloquée.", "La résonance contribue au caractère partiellement double de la liaison."]},
  "peptide-size": {"title": "La taille des peptides et protéines", "items": ["La fiche place les peptides entre plus de 2 et moins de 100 acides aminés.", "Une protéine comporte plus de 100 acides aminés ou plusieurs chaînes polypeptidiques.", "Un dipeptide contient deux résidus.", "Un tripeptide contient trois résidus."]},
  "peptide-termini": {"title": "Les extrémités N- et C-terminales", "items": ["La chaîne est écrite de l’extrémité N-terminale vers l’extrémité C-terminale.", "L’extrémité N-terminale possède une fonction amine libre.", "L’extrémité C-terminale possède une fonction carboxyle libre.", "Les codes à une ou trois lettres peuvent écrire la séquence."]},
  "phi-psi-angles": {"title": "Les angles phi et psi", "items": ["La rotation reste possible autour des liaisons voisines du carbone α.", "L’angle φ concerne la liaison N–Cα.", "L’angle ψ concerne la liaison Cα–CO.", "Ces angles participent à la conformation de la chaîne."]},
  "posttranslational-modifications": {"title": "Les hydroxylations et carboxylations", "items": ["La proline peut devenir 4-hydroxyproline.", "La lysine peut devenir hydroxylysine.", "Le glutamate peut devenir γ-carboxyglutamate.", "Le γ-carboxyglutamate participe à la fixation du calcium en coagulation."]},
  "proline-peptide-kink": {"title": "La proline dans une chaîne peptidique", "items": ["Les chaînes latérales alternent de part et d’autre de la chaîne.", "Un résidu de proline peut provoquer une angulation.", "La structure cyclique de la proline explique cet effet.", "La proline peut perturber une structure régulière."]},
  "protein-denaturation-classification": {"title": "La dénaturation et la classification des protéines", "items": ["La dénaturation peut être réversible ou irréversible.", "Elle dépend notamment du pH, de la température et de la force ionique.", "Une holoprotéine est constituée uniquement d’acides aminés.", "Une hétéroprotéine comporte une partie protéique et une partie non protéique."]},
  "protein-domains": {"title": "Les domaines et l’organisation globulaire", "items": ["Un domaine est une unité structurale et fonctionnelle.", "Un même domaine peut exister dans des protéines différentes.", "Les zones charnières permettent des mouvements entre domaines.", "Dans une protéine globulaire, les résidus hydrophobes sont plutôt internes et les polaires périphériques."]},
  "protein-g-trimer": {"title": "Les protéines G hétérotrimériques", "items": ["Une protéine G hétérotrimérique possède trois sous-unités.", "Les sous-unités sont α, β et γ.", "Les trois sous-unités sont différentes.", "Elle constitue un exemple de structure quaternaire."]},
  "quaternary-assemblies": {"title": "Les homo- et hétéropolymères", "items": ["Un homopolymère comporte des sous-unités identiques.", "Un hétéropolymère comporte des sous-unités différentes.", "Le préfixe homo renseigne sur l’identité des sous-unités.", "Le préfixe hétéro renseigne sur leur diversité."]},
  "quaternary-structure": {"title": "La structure quaternaire", "items": ["Elle associe plusieurs chaînes polypeptidiques.", "Chaque chaîne possède sa propre structure tertiaire.", "Les sous-unités sont souvent unies par des interactions non covalentes.", "L’assemblage forme un complexe fonctionnel."]},
  "tertiary-structure": {"title": "Les coudes et la structure tertiaire", "items": ["Les coudes permettent un changement de direction de la chaîne.", "Ils impliquent souvent proline ou glycine.", "La structure tertiaire rapproche des résidus éloignés dans la séquence.", "Elle est stabilisée par interactions non covalentes et ponts disulfure."]},
  "tetramer-examples": {"title": "Les tétramères LDH et hémoglobine", "items": ["La lactate déshydrogénase est tétramérique.", "LD M4 est une isoforme hépatique et musculaire.", "LD H4 est une isoforme cardiaque.", "L’hémoglobine possède une structure α2β2."]},
  "aa-biological-precursors": {"title": "La glycine, la créatine et les nucléotides", "items": ["La glycine participe à la biosynthèse de l’hème.", "La glycine participe à la conjugaison de certains acides biliaires.", "Glycine, aspartate et glutamine participent à la biosynthèse des bases nucléiques.", "Glycine et arginine participent à la biosynthèse de la créatine."]},
  "aa-neurotransmitter-precursors": {"title": "Les précurseurs de neurotransmetteurs et hormones", "items": ["La tyrosine est précurseur de catécholamines.", "La tyrosine participe à la formation des hormones thyroïdiennes.", "Le tryptophane est précurseur de sérotonine et mélatonine.", "Le glutamate est précurseur du GABA par décarboxylation."]},
  "aa-structural-roles": {"title": "Le rôle structural des acides aminés", "items": ["Ils sont les éléments de base des peptides et protéines.", "Vingt acides aminés sont pris en compte par le code génétique.", "Ils sont reliés par des liaisons peptidiques.", "La sérine entre dans la composition de la phosphatidylsérine."]},
  "amyloid-app": {"title": "Les peptides beta-amyloïdes et APP", "items": ["APP est une protéine transmembranaire à une traversée.", "Un clivage anormal peut libérer des peptides amyloïdes.", "Aβ40 et Aβ42 sont cités.", "Ces peptides insolubles s’agrègent en plaques séniles dans la maladie d’Alzheimer."]},
  "cyclosporine-aspartame": {"title": "La cyclosporine et l’aspartame", "items": ["La cyclosporine est un peptide cyclique.", "Elle comporte 11 acides aminés.", "Elle est utilisée pour prévenir le rejet de greffe.", "L’aspartame est un dipeptide Asp-Phe à fort pouvoir sucrant."]},
  "cytokines-interleukins": {"title": "Les cytokines et interleukines", "items": ["Les cytokines sont de petites protéines ou peptides.", "Interleukines, TNFα, interférons et chimiokines sont cités.", "Les interleukines participent à la communication immunitaire.", "IL1 et IL6 sont pro-inflammatoires alors que IL10 est anti-inflammatoire."]},
  "essential-aa-needs": {"title": "Les besoins en acides aminés indispensables", "items": ["Les acides aminés essentiels doivent être apportés par l’alimentation.", "Leucine, thréonine, lysine et tryptophane sont cités.", "Phénylalanine, valine, méthionine et isoleucine sont citées.", "Histidine et arginine sont semi-essentielles au cours de la croissance."]},
  "glucagon-insulin": {"title": "Le glucagon", "items": ["Le glucagon possède une chaîne de 29 acides aminés.", "Il est synthétisé par les cellules α du pancréas.", "Il dérive du proglucagon par clivage.", "Il est hyperglycémiant et stimule la glycogénolyse hépatique."]},
  "glucogenic-ketogenic-aa": {"title": "Le rôle énergétique des acides aminés", "items": ["Les acides aminés en excès ne sont pas stockés comme tels.", "Les acides aminés glucoformateurs peuvent alimenter la néoglucogenèse.", "Les acides aminés cétoformateurs peuvent donner acétyl-CoA ou acétoacétyl-CoA.", "Leur catabolisme peut participer à la production d’énergie."]},
  "growth-factors": {"title": "Les facteurs de croissance", "items": ["Ils se fixent sur des récepteurs spécifiques.", "Ils déclenchent une transduction intracellulaire.", "Ils contrôlent la prolifération et l’expression des gènes.", "EGF, TGFβ, IGF et FGF sont cités."]},
  "insulin-maturation": {"title": "La maturation de l’insuline", "items": ["La préproinsuline est synthétisée à partir d’un gène unique.", "L’élimination de la séquence signal forme la proinsuline.", "Le clivage du peptide C forme l’insuline mature.", "L’insuline comporte deux chaînes A et B reliées par deux ponts disulfure."]},
  "interferons-chemokines": {"title": "Les interférons et chimiokines", "items": ["Les interférons de type I comprennent IFN-α et IFN-β.", "Ils sont induits notamment par virus et bactéries.", "L’IFN-γ est un interféron de type II surtout produit par les lymphocytes.", "Les chimiokines sont chimiotactiques pour les cellules immunitaires."]},
  "natriuretic-peptides": {"title": "Les peptides natriurétiques", "items": ["ANP et BNP sont produits par les cardiomyocytes.", "ANP comporte 28 acides aminés et BNP 32.", "Ils favorisent natriurèse et diurèse.", "Le dosage BNP ou NT-proBNP aide au diagnostic d’insuffisance cardiaque."]},
  "opioid-peptides": {"title": "Les endorphines et encéphalines", "items": ["Ce sont de petits peptides neuromédiateurs.", "Ils comportent environ 5 à 30 acides aminés.", "Ils sont des opioïdes endogènes.", "Ils se lient aux récepteurs opioïdes."]},
  "peptide-antibiotics": {"title": "Les peptides antibiotiques", "items": ["Certains peptides ralentissent ou empêchent la croissance bactérienne.", "La pénicilline possède une structure cyclique ressemblant à un tripeptide.", "Polymyxines et bacitracine sont citées.", "Certains peptides bactériens contiennent des acides aminés de série D."]},
  "peptide-biological-roles": {"title": "La définition et l’intérêt des peptides", "items": ["Un peptide associe plusieurs acides aminés par des liaisons peptidiques.", "La fiche retient moins de 100 acides aminés pour un peptide.", "De nombreuses hormones sont peptidiques.", "Facteurs de croissance, cytokines et médicaments peuvent être peptidiques."]},
  "peptide-hormone-signaling": {"title": "Les hormones peptidiques", "items": ["Une hormone transmet une information à une cellule cible.", "Elle se fixe sur un récepteur.", "La fixation déclenche une transduction intracellulaire.", "Insuline, glucagon et peptides issus de la POMC sont des exemples."]},
  "pomc-glutathione": {"title": "La POMC et les peptides non ribosomaux", "items": ["La pro-opiomélanocortine est un précurseur protéique.", "Des clivages différents peuvent produire ACTH, γ-lipotropine et β-endorphine.", "Le glutathion est un tripeptide γGlu-Cys-Gly.", "La synthèse non ribosomale nécessite de l’ATP et concerne surtout de petits peptides."]},
  "transamination-methionine": {"title": "Les interconversions et la méthionine", "items": ["La méthionine peut donner un groupement méthyle.", "Elle peut être transformée en homocystéine.", "Une transamination est catalysée par une aminotransférase.", "Aspartate et 2-oxoglutarate peuvent donner oxaloacétate et glutamate."]},
  "urea-cycle-aa": {"title": "Le cycle de l’uréogenèse", "items": ["Citrulline, ornithine et arginine participent au cycle de l’urée.", "Le cycle permet de détoxifier l’ammoniaque.", "L’azote est éliminé sous forme d’urée.", "Des acides aminés non protéinogènes peuvent être des intermédiaires essentiels."]},
  "abc-pgp": {"title": "Les transporteurs ABC et la P-glycoprotéine", "items": ["ABC signifie ATP Binding Cassette.", "Ces transporteurs utilisent l’hydrolyse de l’ATP.", "La P-glycoprotéine peut excréter des médicaments.", "Sa surexpression peut provoquer une résistance aux anticancéreux."]},
  "adhesion-families": {"title": "Les familles de molécules d’adhérence", "items": ["Les quatre familles citées sont sélectines, cadhérines, Ig-CAM et intégrines.", "Elles assurent des interactions cellule-cellule ou cellule-matrice.", "Elles participent à la migration cellulaire.", "Elles sont importantes dans la communication tissulaire."]},
  "antibody-classes": {"title": "Les classes d’immunoglobulines", "items": ["Les cinq classes sont IgA, IgD, IgE, IgG et IgM.", "La classe dépend de la chaîne lourde.", "Les chaînes lourdes correspondantes sont α, δ, ε, γ et μ.", "Les chaînes légères humaines sont κ ou λ."]},
  "antibody-epitope": {"title": "Les antigènes et épitopes", "items": ["Les immunoglobulines reconnaissent des antigènes variés.", "Un épitope est la partie reconnue par l’anticorps.", "Un épitope peut être une séquence ou une conformation.", "Un même antigène peut comporter plusieurs épitopes."]},
  "antibody-fab-fc": {"title": "Les domaines et fragments Fab/Fc", "items": ["Les régions V sont variables et les régions C constantes.", "La papaïne donne deux fragments Fab et un fragment Fc.", "Les fragments Fab conservent la liaison à l’antigène.", "Le fragment Fc intervient dans le complément et la fixation cellulaire."]},
  "antibody-h2l2": {"title": "La structure H2L2 des immunoglobulines", "items": ["Une immunoglobuline comporte deux chaînes lourdes identiques.", "Elle comporte deux chaînes légères identiques.", "Les chaînes sont unies par des ponts disulfure.", "La structure générale est H2L2."]},
  "antibody-multimers": {"title": "Les formes monomériques et multimériques", "items": ["IgD, IgE et IgG sont monomériques.", "IgA peut être dimérique.", "IgM peut être pentamérique.", "Le peptide J participe à l’association de IgA et IgM."]},
  "cftr-channel": {"title": "Le canal CFTR", "items": ["CFTR transporte des ions chlorure.", "Il est exprimé dans des cellules épithéliales.", "La mutation ΔF508 est citée.", "Les mutations de CFTR sont à l’origine de la mucoviscidose."]},
  "connexin-gap-junction": {"title": "Les connexines et connexons", "items": ["Une connexine possède quatre domaines transmembranaires.", "Six connexines forment un connexon.", "Deux connexons de cellules voisines forment un canal.", "Des mutations de connexines peuvent provoquer des surdités congénitales."]},
  "gpcr-rhodopsin": {"title": "Les RCPG et la rhodopsine", "items": ["Les RCPG possèdent sept traversées membranaires en hélice α.", "Ils activent une protéine G dépendante du GTP.", "La rhodopsine contient du 11-cis-rétinal.", "Un photon isomérise le rétinal et active la transducine."]},
  "igcam": {"title": "Les Ig-CAM", "items": ["Ig-CAM signifie Immunoglobulin-Cell Adhesion Molecules.", "Elles possèdent des domaines de type immunoglobuline.", "Elles réalisent des interactions hétérotypiques.", "ICAM-1 participe aux interactions leucocyte-endothélium."]},
  "insulin-receptor": {"title": "Le récepteur à l’insuline", "items": ["Il est un hétérotétramère associant deux chaînes α et deux chaînes β.", "Les chaînes α sont extracellulaires.", "Les chaînes β portent le domaine transmembranaire et tyrosine kinase.", "La voie IRS/PI3K/PIP3/PKB module le métabolisme et la survie cellulaire."]},
  "integrin-focal-adhesion": {"title": "Les intégrines et plaques d’adhésion focale", "items": ["Une intégrine est un hétérodimère αβ.", "Chaque sous-unité possède une traversée membranaire.", "Les intégrines reconnaissent notamment la séquence RGD.", "Elles recrutent des protéines reliant la matrice au cytosquelette d’actine."]},
  "ionotropic-channel": {"title": "Les récepteurs ionotropiques", "items": ["La même molécule assure les fonctions réceptrice et effectrice.", "La fixation du ligand ouvre un canal ionique.", "Les canaux sont sélectifs de certains ions.", "Le flux suit le gradient électrochimique."]},
  "metabotropic-receptor": {"title": "Les récepteurs métabotropiques", "items": ["Les fonctions réceptrice et effectrice sont portées par des molécules différentes.", "La transmission utilise un second messager chimique ou enzymatique.", "Certains possèdent une activité enzymatique intrinsèque.", "Les récepteurs à activité tyrosine kinase appartiennent à cette catégorie."]},
  "nuclear-receptor": {"title": "Les récepteurs nucléaires", "items": ["Ils sont localisés dans le cytosol ou le noyau.", "Leurs ligands comprennent hormones stéroïdiennes, thyroïdiennes, vitamine D et acide rétinoïque.", "Après fixation du ligand, ils peuvent se dimériser.", "Ils se lient à l’ADN comme facteurs de transcription."]},
  "receptor-general": {"title": "Les récepteurs cellulaires", "items": ["Ils fixent un ou plusieurs ligands.", "Ils transmettent un message modifiant le comportement cellulaire.", "Un récepteur membranaire possède des domaines extracellulaire, transmembranaire et cytoplasmique.", "Les récepteurs peuvent être nucléaires, membranaires ou associés à d’autres compartiments."]},
  "selectin-cadherin": {"title": "Les sélectines et cadhérines", "items": ["E-, L- et P-sélectines correspondent à endothélium, leucocytes et plaquettes.", "Les sélectines reconnaissent des glycanes sialyl-Lewis.", "Les cadhérines réalisent des interactions homotypiques.", "Les cadhérines nécessitent du Ca2+."]},
  "serotonin-gaba-channels": {"title": "Les récepteurs 5-HT3 et GABAA", "items": ["Le récepteur 5-HT3 s’ouvre après fixation de la sérotonine.", "Il permet une entrée de Na+ et une dépolarisation.", "Le récepteur GABAA permet une entrée de Cl−.", "Le GABAA provoque une hyperpolarisation et un effet inhibiteur."]},
  "sodium-potassium-pump": {"title": "La pompe Na+/K+-ATPase", "items": ["Elle utilise l’énergie de l’ATP.", "Elle transporte les ions contre leurs gradients.", "Elle expulse trois Na+ et fait entrer deux K+.", "Elle contribue au potentiel de repos."]},
  "actin-microtubules": {"title": "L’actine et les microtubules", "items": ["L’actine G est monomérique et l’actine F filamenteuse.", "La polymérisation de l’actine dépend de l’ATP.", "Les microtubules sont formés de dimères α/β-tubuline.", "La dynamique des microtubules dépend du GTP et diffère entre extrémités + et −."]},
  "collagen-alpha-chain": {"title": "La chaîne alpha du collagène I", "items": ["Sa structure secondaire est une hélice gauche.", "Elle n’est pas une hélice α classique.", "Elle est de type polyproline II.", "Elle comporte généralement trois résidus par tour."]},
  "collagen-classification": {"title": "La classification des collagènes", "items": ["Les collagènes fibrillaires incluent notamment les types I, II et III.", "Le type IV forme des réseaux.", "Le type VII est un collagène de jonction ou d’ancrage.", "Les FACIT sont associés aux fibres avec triple hélice interrompue."]},
  "collagen-crosslinks": {"title": "Les liaisons croisées et fibres de collagène", "items": ["Les liaisons croisées sont covalentes.", "Elles dérivent de résidus de lysine transformés par la lysyl-oxydase.", "Les fibrilles s’associent en fibres puis en faisceaux.", "Le diamètre augmente au cours de ces niveaux d’assemblage."]},
  "collagen-fibril": {"title": "Les fibrilles de collagène I", "items": ["Le monomère est appelé tropocollagène.", "Les molécules sont décalées d’un quart de leur longueur.", "Le décalage correspond à environ 67 nm.", "Il produit un aspect strié en microscopie électronique."]},
  "collagen-gly-x-y": {"title": "Le motif Gly-X-X’ du collagène", "items": ["Le motif Gly-X-X’ est répété dans la structure primaire.", "X est fréquemment une proline.", "X’ peut être une 4-hydroxyproline.", "La glycine représente environ un résidu sur trois."]},
  "collagen-overview": {"title": "L’abondance et les critères des collagènes", "items": ["Les collagènes représentent environ un tiers des protéines de l’organisme.", "La famille comprend 28 types numérotés I à XXVIII.", "Un collagène possède des domaines en triple hélice.", "Il forme des assemblages supramoléculaires."]},
  "collagen-triple-helix": {"title": "La triple hélice du collagène", "items": ["Elle associe trois chaînes α.", "Le surenroulement forme une superhélice droite.", "Les OH de l’hydroxyproline contribuent aux liaisons hydrogène.", "La glycine est située au centre en raison de son faible encombrement."]},
  "collagen-type-iv": {"title": "Le collagène de type IV", "items": ["Il est typique des membranes basales.", "Il est présent notamment dans les reins et les poumons.", "Il forme des réseaux.", "Les domaines 7S et NC1 participent à l’organisation du réseau."]},
  "cytoskeleton-overview": {"title": "Les constituants du cytosquelette", "items": ["Les trois systèmes sont filaments d’actine, filaments intermédiaires et microtubules.", "Ils participent à l’architecture cellulaire.", "Ils transmettent des forces mécaniques.", "Ils servent de rails à des moteurs comme myosines, dynéines et kinésines."]},
  "extracellular-matrix": {"title": "La matrice extracellulaire", "items": ["Elle forme un réseau autour des cellules.", "Elle soutient l’organisation des cellules en tissus.", "Elle contient collagènes, élastine, glycoprotéines et protéoglycanes.", "Plusieurs protéines matricielles ont une longue demi-vie."]},
  "fibronectin": {"title": "La fibronectine", "items": ["Elle est un dimère de deux chaînes d’environ 235 kDa.", "Les chaînes sont reliées par leur extrémité C-terminale.", "La molécule a une forme de V.", "Elle se lie aux intégrines, à la fibrine et à d’autres protéines matricielles."]},
  "hemoglobin-anomalies": {"title": "Le monoxyde de carbone et la méthémoglobine", "items": ["Le CO possède une affinité pour l’hème supérieure à celle de l’O2.", "Il forme de la carboxyhémoglobine.", "La méthémoglobine contient du fer Fe3+.", "La méthémoglobine ne fixe pas correctement l’O2."]},
  "hemoglobin-conformations": {"title": "La fixation de l’oxygène par l’hémoglobine", "items": ["L’hémoglobine transporte l’O2 des poumons vers les tissus.", "Elle participe au retour du CO2 vers les poumons.", "L’équilibre entre conformations influence l’affinité pour l’O2.", "Le pH et la pression en CO2 influencent la fixation."]},
  "hemoglobin-structure": {"title": "La structure de l’hémoglobine A", "items": ["L’hémoglobine contient un groupement prosthétique hème.", "Le fer Fe2+ de l’hème fixe le dioxygène.", "L’hémoglobine A est α2β2.", "Elle possède quatre hèmes et quatre sites de fixation de l’O2."]},
  "laminin": {"title": "La laminine", "items": ["Elle possède trois chaînes α, β et γ.", "Les chaînes forment une structure en croix.", "Sa masse moléculaire est élevée, autour de 850 kDa dans la fiche.", "Elle est très importante dans les membranes basales."]},
  "matrix-glycoproteins": {"title": "Les glycoprotéines matricielles", "items": ["Elles participent aux interactions cellule-matrice.", "Leur partie glucidique peut résulter de N- ou O-glycosylation.", "Elles possèdent des domaines structuraux communs.", "Fibronectines, laminines, tenascines et vitronectine sont citées."]},
  "myosin-cycle": {"title": "Les myosines", "items": ["Les myosines sont des moteurs moléculaires.", "Leur fonctionnement dépend de l’hydrolyse de l’ATP.", "Elles interviennent dans migration, adhésion et transport intracellulaire.", "La myosine II participe à la contraction musculaire."]},
  "protein-role-acronym": {"title": "Les rôles énergie, influx nerveux et enzymes", "items": ["En dénutrition, les protéines peuvent fournir des acides aminés énergétiques.", "Les canaux ioniques participent à l’influx nerveux.", "Les enzymes ont des rôles majeurs dans le métabolisme.", "Une protéine peut avoir une fonction différente selon sa structure."]},
  "sickle-albumin-lipoprotein": {"title": "La drépanocytose, l’albumine et les apolipoprotéines", "items": ["La drépanocytose résulte d’une substitution Glu→Val en position 6 de la chaîne β.", "L’HbS est moins soluble et peut s’agréger.", "L’albumine représente environ 60 % des protéines sériques et régule la pression oncotique.", "Les apolipoprotéines constituent l’enveloppe protéique des lipoprotéines."]},
};

type Props = { diagram: ProteinDiagramName; className?: string };

export function ProteinDiagram({ diagram, className }: Props) {
  const data = DATA[diagram];

  return (
    <figure className={cn("my-5 rounded-2xl border border-border bg-card p-4 text-foreground", className)}>
      <div className="mb-4 text-center text-base font-semibold">{data.title}</div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {data.items.map((item, index) => (
          <div
            key={diagram + "-" + item}
            className="relative rounded-xl border border-border bg-background/60 p-3 text-center text-sm"
          >
            <div className="mb-2 text-xs font-semibold text-muted-foreground">{index + 1}</div>
            <div>{item}</div>
            {index < data.items.length - 1 ? (
              <div className="absolute -right-3 top-1/2 hidden -translate-y-1/2 text-muted-foreground lg:block">
                →
              </div>
            ) : null}
          </div>
        ))}
      </div>
    </figure>
  );
}
